### ISSUE TITLE
Can not load the file 'Magick.NET.Wrapper-x64.DLL'

### ISSUE THREAD

**Issue by crazyboy12** [dlemstra/Magick.NET#1]
hey,I use the  Magick.NET 7.0.0.0021,it is working good in window7 32bit but when i put it in windows 
2012R2 ,it can not load the file 'Magick.NET.Wrapper-x64.DLL'. I have install theVisual C++ Redistributable for Visual Studio 2015, and I also write the  MagickAnyCPU.CacheDirectory, it make the file success but ,it still show this error.

**Comment by dlemstra** [comment]
Did you install the 64 bit version of the C++ redistributable?

**Comment by crazyboy12** [comment]
yes , i install 64 bit version of the c++ redistributable in sever

**Comment by dlemstra** [comment]
What is the complete error message that you are receiving? It normally tells you why the wrapper could not be loaded.

**Comment by crazyboy12** [comment]
@dlemstra  the error message is mostly like this
ファイルまたはアセンブリ 'Magick.NET-Q16.Wrapper-x64.dll'、またはその依存関係の 1 つが読み込めませんでした。指定されたモジュールが見つかりません。

説明: 現在の Web 要求を実行中に、ハンドルされていない例外が発生しました。エラーに関する詳細および例外の発生場所については、スタック トレースを参照してください。 

例外の詳細: System.IO.FileNotFoundException: ファイルまたはアセンブリ 'Magick.NET-Q16.Wrapper-x64.dll'、またはその依存関係の 1 つが読み込めませんでした。指定されたモジュールが見つかりません。

ソース エラー: 

現在の Web 要求の実行中にハンドルされていない例外が生成されました。障害の原因および発生場所に関する情報については、下の例外スタック トレースを使って確認できます。

スタック トレース: 


[FileNotFoundException: ファイルまたはアセンブリ 'Magick.NET-Q16.Wrapper-x64.dll'、またはその依存関係の 1 つが読み込めませんでした。指定されたモジュールが見つかりません。]
   ImageMagick.MagickImageCollection..ctor() +0

**Comment by dlemstra** [comment]
When you get the message 'The specified module could not be found.' it normally is relayed to the fact that the c++ redistributable is not installed. Did you reboot your machine? Do you see any files in the folder that you set for `MagickAnyCPU.CacheDirectory`?

**Comment by crazyboy12** [comment]
thanks for your help,It works by my re-install the redistributable,thanks for your help
