### ISSUE TITLE
Bug in Composite() method

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#10]
I tried to use the Composite method with the following arguments :
```
public void Composite(MagickImage image, MagickGeometry offset, CompositeOperator compose)
{
    Composite(image, offset, compose, null); //Call to the below method with a null args parameter
}
```
Infortunately, it throws a ArgumentNullException because it passes a null argument:
```
public void Composite(MagickImage image, MagickGeometry offset, CompositeOperator compose, string args)
{
    Throw.IfNull("image", image);
    Throw.IfNull("offset", offset);

    _NativeInstance.SetArtifact("compose:args", args); // Throws ArgumentNullException if args is null
    _NativeInstance.CompositeGeometry(image, MagickGeometry.ToString(offset), compose);
}
```

**Comment by dlemstra** [comment]
The example that you are showing does not throw an ArgumentNullException but it used to call SetArtifact (not the method on _NativeInstance) that throws the exception. The following commit resolved this: https://github.com/dlemstra/Magick.NET/commit/3cd2390dc12b291709a250befb7fbcbabf716c51. It will be fixed in Magick.NET 7.0.0.105 that will be publish this Saturday.

**Comment by DavidRouyer** [comment]
Thanks! You should add unit tests to avoid regressions like that :)

**Comment by dlemstra** [comment]
I took another look at the code and started wondering why I used MagickGeometry. It turns out that the width and height are not used so I decided to change the MagickGeometry to a PointD instead. And as you suggested :+1: I added a unit test that touches that path to make sure it stays fixed.

**Comment by owenblacker** [comment]
It would have been very useful if you had kept the overload using a `Rectangle`. I've just inherited a project where I'm trying to upgrade the version of ImageMagick and I have _a lot_ of compiler errors right now. :(

**Comment by owenblacker** [comment]
(At least all I needed to do was correct this error mind :)
