### ISSUE TITLE
Wrong example in delay time (creating gif)

### ISSUE THREAD

**Issue by Boquete** [dlemstra/Magick.NET#100]
https://github.com/dlemstra/Magick.NET/blob/master/Documentation/CombiningImages.md

> // Add second image, set the animation delay to 100ms and flip the image
    collection.Add("Snakeware.png");
    collection[1].AnimationDelay = 100;

Actually 100/10 is 100ms.  

1) How to reproduce
Easiest way - set delay to 1000, as documentation ^ says it would be 1000ms (1 seconds) but in reality it's 10 seconds after each frame) 

2) Source
http://www.imagemagick.org/Usage/anim_basics/

> Set the time delay (in 1/100th of a second) to pause after drawing the images that are read in or created after this setting has been defined.

(ms is 1/1000th of seconds)

**Comment by dlemstra** [comment]
Would you mind sending a pull request for the docs and the code in the `Samples`? And thanks for noticing.

**Comment by Boquete** [comment]
Sure. :)
