### ISSUE TITLE
Add support of ReadOnlySequence and IBufferWriter

### ISSUE THREAD

**Issue by DanilovSoft** [dlemstra/Magick.NET#1001]
### Description

MagickImage recently began support initialization from `ReadOnlySpan<byte>`, which is great! But some times source memory can be fragmented and to prevent heap allocation it would be nice to have initialization from `ReadOnlySequence<byte>`. Also writing output is still restricted to `Stream` and coresponding to Span's it would be good to have overload for `IBufferWriter<byte>`.

### Proposal

Add constructor overload `MagickImage(ReadOnlySequence<byte> data)` and coresponding `Read` overload.
Add Write overload `MagickImage.Write(IBufferWriter<byte> buffer)`.

### System Configuration

- Magick.NET version: Magick.NET-Q16-x64 8.1.0
- Environment (Operating system, version and so on): Windows 10 x64

**Comment by dlemstra** [comment]
It looks like `ReadOnlySequence<byte>` is not always a noncontiguous "byte array" and that is required for the native code of Magick.NET. But it is probably possible to add support for an `IBufferWriter<byte>`.

**Comment by dlemstra** [comment]
Just realized it might also be possible to use the ` ReadOnlySequence<byte>`, will need to run some experiments.

**Comment by dlemstra** [comment]
Support for both `ReadOnlySequence<byte>` and `IBufferWriter<byte>` will become available in the next release.

**Comment by DanilovSoft** [comment]
An infinite loop occurs in `ReadOnlySequenceWrapper.Read` when there are more than one segments in `ReadOnlySequence`.

**Comment by dlemstra** [comment]
I added a unit test for this to make sure this works but it I only tested this with `1` byte sequences. This probably fails with sequences of a specific size will add a test for this and get this fixed.
