### ISSUE TITLE
BGRA Jpg incorrectly decoded.

### ISSUE THREAD

**Issue by Drake53** [dlemstra/Magick.NET#1011]
### Description
Trying to load a .jpg file with BGRA data gets incorrectly decoded as if it's YCbCr. As a result, the colours are incorrect and there's no alpha channel.

### Steps to Reproduce
Simply load the example .jpg file:
https://github.com/Drake53/War3Net/blob/master/tests/War3Net.Common.Testing/TestData/Blp/VillageFallStonePath.jpg

Note that github doesn't display it correctly either, it should look like this:
https://github.com/Drake53/War3Net/blob/master/tests/War3Net.Common.Testing/TestData/Blp/VillageFallStonePath.png

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU v8.2.1
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
The JPEG format has no alpha channel. Are you sure that your input image is a JPEG file?

**Comment by Drake53** [comment]
Yes I'm sure it's a JPEG file, you can look at the example that I linked.
It's very rarely used though and most libraries I tried don't decode it correctly either, only WPF does it correctly.

**Comment by dlemstra** [comment]
I did some research and it looks like `jpeg-turbo` does not support reading this image as `BGRA` so I am going to need to close this. 

You can however still use this library to read those kind of images but you will need to swap and negate the channels yourself:


```C#
using (var image = new MagickImage("VillageFallStonePath.jpg"))
{
    using (var channels = new MagickImageCollection(image.Separate()))
    {
        var red = channels[2];
        channels.Remove(red);

        var blue = channels[0];
        channels.Remove(blue);

        channels.Insert(0, red);
        channels.Insert(2, blue);

        foreach (var channel in channels)
        {
            channel.Negate();
        }

        using (var output = channels.Combine())
        {
            output.Write("VillageFallStonePath.png");
        }
    }
}
```
