### ISSUE TITLE
Invalid date format specified for png:tIME@ error/png.c/write_tIME_chunk/8178"

### ISSUE THREAD

**Issue by Boquete** [dlemstra/Magick.NET#102]
Sometimes error like this appear: 
+		$exception	{"Invalid date format specified for png:tIME `template4-3.png' @ error/png.c/write_tIME_chunk/8178"}	ImageMagick.MagickCoderErrorException

Code:
```
        public static void CutPic(Uri pic, int height, int width)
        {
            var mPic = pic.ToString().Replace("file:///", "");
            using (var cropPic = new MagickImage(mPic))
            {
                cropPic.Crop(width, height);
                cropPic.Write(mPic);
            }
        }

```
Error appears when rewriting image - basically I'm rewriting old image with new image, sometimes it works sometimes it don't - another function similar to this:
```

                  var mFrame = frame.ToString().Replace("file:///", "");
                    if (((new MagickImageInfo(mFrame)).Height) != gPicHeight)
                    {
                        using (MagickImage rFrame = new MagickImage(mFrame))
                        {
                            rFrame.Resize(0, gPicHeight);
                            rFrame.Write(mFrame);
                        }
                    }
```

again I'm writing rewriting image.

**Comment by dlemstra** [comment]
Do you have an input image I can reproduce this with?

**Comment by dlemstra** [comment]
@Boquete Can you still reproduce this with the latest version?

**Comment by Boquete** [comment]
Sorry for not answering @dlemstra , was pretty busy.

It looks like problem is gone in newest version :)
