### ISSUE TITLE
GetPixelsUnsafe operations reset ColorType

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#1022]
### Description
Using `GetPixelsUnsafe` for either read or write results in the `MagickImage` object itself resetting the `ColorType` to `TrueColor` regardless of what it was set to before.

### Steps to Reproduce
```
m.ColorType = ColorType.Grayscale;
using (var pix = m.GetPixelsUnsafe())
{
       return pix.ToArray();
}
Console.WriteLine(m.ColorType);
```

### System Configuration

- Magick.NET version: 8.3 (also reproducible in previous 8.x builds)
- Environment (Operating system, version and so on): Windows 10

**Comment by dlemstra** [comment]
Do you also have this issue with `GetPixels` or is that only with the `Unsafe` version?

**Comment by daxpandhi** [comment]
Good question - I only use Unsafe so not sure. I'll investigate and get back to you when I'm at the PC again.

**Comment by dlemstra** [comment]
I am unable to reproduce your issue. The following works with a local debug build:
```C#
using (var image = new MagickImage(MagickColors.Red, 1, 1))
{
    float[] data;
    image.ColorType = ColorType.Grayscale;
    using (var pix = image.GetPixelsUnsafe())
    {
        data = pix.ToArray();
    }

    Assert.Equal(ColorType.Grayscale, image.ColorType);
}
```

**Comment by daxpandhi** [comment]
```
            var mm = new MagickImage(MagickColors.Black,
                                     (int)Math.Sqrt(heightMap.Length),
                                     (int)Math.Sqrt(heightMap.Length))
            {
                ColorType = ColorType.Grayscale,
            };

            mm.Alpha(AlphaOption.Off);
            using (var mem = mm.GetPixelsUnsafe())
            {
                mem.SetPixels(heightMap);
            }
            return mm;
```
I set two breakpoints, before and after the `GetPixelsUnsafe` and this is what I get:
![fsDyfEtWUG](https://user-images.githubusercontent.com/6795809/132400983-bb6abc60-d9ee-42e9-8671-02c6623fe0bc.png)
![vwY554uUfj](https://user-images.githubusercontent.com/6795809/132400996-f9c4b8cf-8392-4b59-a3e7-048dcc8da26b.png)

Further down the line, our code breaks down because it queries the color type, which hints at an RGB image but our data is single channel only. It is not a showstopper as we added further checks and assertions later so we can re-assign the values.

I forgot to write in my initial notes that the runtime is .NET Framework 4.8 and Magick is Magick.NET-Q16-HDRI-OpenMP-x64 8.3.0.

**Comment by dlemstra** [comment]
This is caused by the call to `mm.Alpha(AlphaOption.Off)`. Not sure why this is happening though.

**Comment by daxpandhi** [comment]
Might it be something like the drawing methods? I remember you mentioned a long time ago that when we call drawing operations, the image resets back to TrueColor from Grayscale (I forget the exact reason, but it was something inherent or a performance thing perhaps).

**Comment by dlemstra** [comment]
I don't think we need to do anything when the image already has no alpha channel. Just pushed a commit to not do anything when the image is already missing the alpha channel. Now testing if that broke anything. But in other cases the image type will be reset.

**Comment by dlemstra** [comment]
Can I close this issue @daxpandhi?

**Comment by daxpandhi** [comment]
Yes, thank you!
