### ISSUE TITLE
Bounding box coordinates for Trim

### ISSUE THREAD

**Issue by saikatguha** [dlemstra/Magick.NET#1025]
### Is your feature request related to a problem? Please describe
I have a binary image with black background and white object. I need a _high performance_ method to extract the bounding box for the white object. It is acceptable for bounding box to always be parallel to the edges. 

I tried `MinimumBoundingBox()`, but it is too slow due to Rotating Calipers algorithm to recover angled bounding boxes (which I anyway grow to edge parallel bounding box). 

I tried using `Trim()` which is performant, but it doesn't provide the bounding box coordinates. On the command line there is a way to get Trim to return the bounding box info.

### Describe the solution you'd like
A fast edge parallel minimum bounding box method.
Alternatively, a version of Trim() to return bounding box coordinates relative to original image. 

### Describe alternatives you've considered
MinimumBoundingBox and Trim

**Comment by dlemstra** [comment]
Have you tried the `BoundingBox` property of the image?

**Comment by saikatguha** [comment]
I get an access violation exception (below) when I try to access BoundingBox; code below.

```csharp
using var img = segmentedImage.Clone();
img.ColorFuzz = new Percentage(2);
img.InverseOpaque(new MagickColor("#FF0000"), _black);
var bb = img.BoundingBox;     // <- Throws exception
```

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at ImageMagick.MagickImage+NativeMethods+X64.MagickImage_BoundingBox_Get(IntPtr)
     at ImageMagick.MagickImage+NativeMethods+X64.MagickImage_BoundingBox_Get(IntPtr)
     at ImageMagick.MagickImage+NativeMagickImage.get_BoundingBox()
     at ImageMagick.MagickImage.get_BoundingBox()
     ...
```

**Comment by dlemstra** [comment]
Is it possible to create a sample that I can use to reproduce this? And have you tried upgrading to the most recent version?

**Comment by saikatguha** [comment]
Updating to `8.3.0` didn't solve the issue. Still throws AccessViolationException after 30 images.

Commenting out call to `InverseOpaque(...)` avoids the AccessViolationException (but not the intended output image). Leak in InverseOpaque?

**Comment by saikatguha** [comment]
If you want to repro, try using attached image (`segmentedImage` in the code above).
![segmented](https://user-images.githubusercontent.com/308774/133073567-5c342dcc-e2b4-4027-a9ba-0ada54c6a8ef.png)

Call the above code in a loop 30 or so times.

**Comment by saikatguha** [comment]
I also tried with `InverseTransparent` and `InverseFloodFill`. Both of them result in the same AccessViolationException after the 30 iteration through the loop.

**Comment by dlemstra** [comment]
Thanks for reporting this. The problem is that in your example a warning is raised but the native code is not getting a pointer due to a bug in Magick.NET. This warning is raised because the bounding box is 0x0. This will return `null` in the next release of Magick.NET instead.

**Comment by dlemstra** [comment]
The new release has been published. Can you test this again @saikatguha and close this issue if it is resolved?

**Comment by saikatguha** [comment]
Works great. Thanks for the super quick resolution!
