### ISSUE TITLE
Showing character spacing in file name when opening PDF file on browser

### ISSUE THREAD

**Issue by FarshanAhamed** [dlemstra/Magick.NET#1028]
### Description
Previously I was using `Magick.NET-Q8-AnyCPU` version `7.10.1` and I was converting image to pdf and I could open the pdf file in the browser with the filename I have provided like below

![image](https://user-images.githubusercontent.com/15251751/133420436-4254cf42-6d7d-472b-b472-c6a849ba882e.png)

After upgrading to `8.3.1`, the filename is showing spaces in the browser like below

![image](https://user-images.githubusercontent.com/15251751/133420650-b6eeb8c4-642b-4ac4-879a-4a6bbd408e46.png)

### Steps to Reproduce
```c#

var imagePath = Path.Combine(imageDir, $"Student-{Id}.jpg");
var pdfPath = Path.Combine(pdfDir, $"Student-{Id}.pdf");
using (var image = new MagickImage(imagePath))
{
    image.Write(pdfPath);    
}
```

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU 8.3.1
- Environment (Windows 10, version and  .NET 5):
- Additional information: nuget version 7.10.1 works fine in this same system configuration.

**Comment by dlemstra** [comment]
Maybe this has to do with the PDF version that is used and how the browser handles this? I don't think the file name is stored inside the PDF file.

**Comment by FarshanAhamed** [comment]
@dlemstra when I opened both pdf in text editor, I found that the title is saving inside the file.

PDF using nuget version `7.10.1`

![image](https://user-images.githubusercontent.com/15251751/133459012-3f8c4b2c-bd60-48b9-8fb1-d8031779edba.png)
 
 PDF using nuget version `8.3.1`

![image](https://user-images.githubusercontent.com/15251751/133459202-f149ff4b-5a48-4ccd-955d-008e30232e4f.png)

**Comment by dlemstra** [comment]
It appears that we are missing a byte order mark at the start of /Title. I just pushed a fix for it that will be resolved in the next release.

**Comment by FarshanAhamed** [comment]
Thank you. I'm glad I could help.
