### ISSUE TITLE
How to Get Layers name in a PSD Document ?..

### ISSUE THREAD

**Issue by pc8181** [dlemstra/Magick.NET#103]
Hi i m newbie to magick.net i just download the version 7.0.6.1002
can you help to extract layers name to text file or xml file or copy to clipboard into a
photoshop document ?

get layers name or particular layer names or layer names starts with some specific string like
'drawing1...drawing25" ?

Thanks

**Comment by dlemstra** [comment]
When you read the PSD document with the `MagickImageCollection` you will get all the layers. Each image in the collection will have the `Label` property set to the name of the layer when the layer has a name.

**Comment by dlemstra** [comment]
@pc8181 Can we close this issue?

**Comment by pc8181** [comment]
k sir

**Comment by pc8181** [comment]
hi sir,
 How to get Text Layers Only ? .... i can read layers name but how to find layer type ?.
