### ISSUE TITLE
Seems to be unable to read image some files format.

### ISSUE THREAD

**Issue by hotline** [dlemstra/Magick.NET#104]
### code 
```c#
 Debug.WriteLine(ImageMagick.MagickNET.Version);
  foreach (var ext in new string[] { "gif", "jpg", "png", "bmp", "tif" })
  {
      try
      {
          using (MagickImage image = new MagickImage(@"test." + ext))
          {
              Debug.WriteLine("OK: {0}: Size:{1}x{2} Depth:{3}", ext, image.Width, image.Height, image.Depth);
          }
      } catch(Exception e) {
          Debug.WriteLine("NG: {0}: {1}",ext, e.Message.Split('\n')[0]);
      }
  }
```
### identify.exe .\Debug\test.*
```text
\Debug\test.bmp BMP 768x1024 768x1024+0+0 8-bit sRGB 2.359MB 0.016u 0:00.062
\Debug\test.gif GIF 768x1024 768x1024+0+0 8-bit sRGB 256c 574KB 0.000u 0:00.000
\Debug\test.jpg JPEG 768x1024 768x1024+0+0 8-bit sRGB 340KB 0.016u 0:00.031
\Debug\test.png PNG 768x1024 768x1024+0+0 8-bit sRGB 1.408MB 0.000u 0:00.000
\Debug\test.tif TIFF 768x1024 768x1024+0+0 8-bit sRGB 2.36MB 0.000u 0:00.014
```
### Result
```text
Magick.NET Q8 AnyCPU net40 7.0.7.0
OK: gif: Size:768x1024 Depth:8
NG: jpg: insufficient image data in file `test.jpg' @ error/jpeg.c/ReadJPEGImage/1068
NG: png: insufficient image data in file `test.png' @ error/png.c/ReadPNGImage/4222
NG: bmp: insufficient image data in file `test.bmp' @ error/bmp.c/ReadBMPImage/949
OK: tif: Size:768x1024 Depth:8
```

**Comment by dlemstra** [comment]
Are you sure that those files are correct? Can you add a link to those files? The reason that identify works is because it only `pings` the image. When you create a `MagickImage` it will read all the pixel data. I wonder if `identify -verbose` works for those images.

**Comment by hotline** [comment]
OK,　Attach the files used for the test. 
Please Verification, thanks.

[test-images.zip](https://github.com/dlemstra/Magick.NET/files/1292286/test-images.zip)

**Comment by dlemstra** [comment]
I cannot reproduce your issue with the code and the test images that you provided. Are we testing the same thing?

**Comment by dlemstra** [comment]
@hotline Can you still reproduce this issue?

**Comment by EyeAndTea** [comment]
I apologize if this is not the right conduct. I am having the same problem on a Windows XP x86 set up, and the net40 Q8 AnyCPU version (<= 7.6.0) of the library, which, appear to be very similar to the relevant parameters of the original poster. The same compiled code works under a Windows 7 x64 set up.

**Comment by EyeAndTea** [comment]
An update. It appears that version 7.0.6.101 is the last release version to work with the same other parameters as indicated in my previous comment on my Windows XP X86 set up.

**Comment by EyeAndTea** [comment]
An update. It appears that version 7.0.6.101 is the last release version to work with the same other parameters as indicated in my previous comment on the same Windows XP X86 set up.

**Comment by dlemstra** [comment]
Thanks for the update @EyeAndTea. I have decided to stop supporting Windows XP support a while back. And Microsoft stopped supporting it back in 2014: https://www.microsoft.com/en-ww/windowsforbusiness/end-of-xp-support.
