### ISSUE TITLE
Image is failing to read because IDAT: chunk data is too large

### ISSUE THREAD

**Issue by coderangerdan** [dlemstra/Magick.NET#105]
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I try and read the image below and i get an "because IDAT: chunk data is too large" error message:

![testimage](https://user-images.githubusercontent.com/1733292/30274811-ed8429e8-96f6-11e7-8e75-6d28de1ea669.png)

Earlier version (v7.0.6.102 specifically) of ImageMagick worked fine, I upgraded to v7.07 and now it doesn't.

The image opens in all image editors fine.

If I open the image in paint.net and save it back out in same format and using Auto-Depth settings, the size reduces from 65kb to 4kb and ImageMagick then has no problems reading it.

### Steps to Reproduce
```
var readSettings = new MagickReadSettings();
readSettings.Format = MagickFormat.Png;

using( var downloadStream = new FileStream( "TestImage.png", FileMode.Open ) )
using( var resizedImageStream = new MemoryStream() )
using( var image = new MagickImage( downloadStream, readSettings ) )  // exception thrown here
{
    image.Strip();                // Strip out all profile info...
    image.Quality = 100;

    image.Write( resizedImageStream, readSettings.Format );
    resizedImageStream.Position = 0;

    // we do something with the memory stream....
}
```

Stack trace:
```
Source: Magick.NET-Q16-x64
IDAT: chunk data is too large `' @ error/png.c/MagickPNGErrorHandler/1711
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
   at ImageMagick.MagickImage..ctor(Stream stream, MagickReadSettings readSettings)
```
### System Configuration
Windows 10 Visual Studio 2017, but also on Windows Server multiple versions

- ImageMagick version: Magick.NET-Q16-x64 v7.07
- Environment (Operating system, version and so on): Windows (any)
- Additional information: none not already mentioned above

**Comment by dlemstra** [comment]
@glennrp replied here: https://github.com/ImageMagick/ImageMagick/issues/747. It appears to be an issue in libpng. Will need to upgrade/downgrade libpng to resolve this issue.

**Comment by dlemstra** [comment]
@coderangerdan Can I add your image to my repository and use it in a unit test?

**Comment by coderangerdan** [comment]
Sure no problem

**Comment by dlemstra** [comment]
The bug has been found and fixed. This will be resolved in the next version of Magick.NET

**Comment by danludwig** [comment]
Has this been released in the nuget package yet?

**Comment by dlemstra** [comment]
@danludwig This has been resolved in the latest release
