### ISSUE TITLE
Magick.net CreateProcess interacts with other created processes in application

### ISSUE THREAD

**Issue by tomasr78** [dlemstra/Magick.NET#1054]
This issue is follow-up from https://github.com/dlemstra/Magick.NET/discussions/1024 but I think it should be opened as an issue.

When I try to convert Image to PDF sometimes the file is not released after conversion and I get an error that the file is used.

I have tried to narrow down the problems and that's what I found. It seems the problem is not related directly to Magick.net but to `Process.Start`. I suppose you also use `Process.Start` to launch ImageMagick.

So the problem is that Magick.Net and my code use `Process.Start` at the same time to start other console apps and somehow they interact and lock each other files.

This problem only happens when `Process.StartInfo.UseShellExecute` is set to `False`. 
```
    using (var p = new Process
    {
        StartInfo =
        {
            FileName = "c:\commandLine.exe",
            Arguments = "c:\file.jpg",
            UseShellExecute = false,
            RedirectStandardError = true,
            RedirectStandardOutput = true
        }
    })
    {
        try
        {
            p.Start();
            p.PriorityClass = ProcessPriorityClass.Normal;

            p.WaitForExit();

            var output = await p.StandardOutput.ReadToEndAsync();
            var error = await p.StandardError.ReadToEndAsync();
            var exitCode = p.ExitCode;
            return .....; 

        }
        finally
        {
            try
            {
                if (!p.HasExited)
                    p.Kill();
            }
            catch (InvalidOperationException)
            {
                //The process is not found, probably executable was not fount                    
            }

            p.Close();
        }
    } 
```

Dirk, could you show me the code where you run ImageMagick? I think there is a bug because if we remove Magick.Net our Processes start working fine and files are not locked anymore.

**Comment by dlemstra** [comment]
I am sorry but I really don't understand what you are trying to tell me? It all looks like there is an issue with App2 not working properly.

**Comment by tomasr78** [comment]
I could create a console application demo to demonstrate the issue, it is easy to reproduce on any Windows OS.

**Comment by tomasr78** [comment]
@dlemstra I have created a demo project at https://github.com/tomasr78/FileLockingDemo
I am using additional two command-line utilities MuTool(https://mupdf.com/) and CPDF(https://community.coherentpdf.com/) which work with pdf files to simulate the problem.

When you run the project you will find that files are being locked. 

Fixes that solves the problem:

* Remove ImageMagick Task and run again, everything would work fine. I am using ImageMagick, can't remove it :)
* Process.StartInfo.UseShellExecute to True instead of False. I need to have Process.StartInfo.UseShellExecute to set to False to be able to read console output.

**Comment by dlemstra** [comment]
Can this issue be closed @tomasr78?
