### ISSUE TITLE
Cannot open TGA file.

### ISSUE THREAD

**Issue by SebastianStehle** [dlemstra/Magick.NET#1080]
### Description
Not sure, if it is a bug, but I cannot open TGA files. I get the following error:

```
ImageMagick.MagickMissingDelegateErrorException : no decode delegate for this image format `' @ error/blob.c/BlobToImage/458
```

### Steps to Reproduce
Load the following file:
https://www.dropbox.com/s/wr3lzt66u4krbzv/logo.tga?dl=0

(Cannot be uploaded to github)

### System Configuration
- Magick.NET version: 8.4
- Environment (Operating system, version and so on): Windows, .NET 6, AnyCPU
- Additional information:

**Comment by dlemstra** [comment]
Adding zipped version of the file to the issue. [logo.zip](https://github.com/dlemstra/Magick.NET/files/7595048/logo.zip)

**Comment by SebastianStehle** [comment]
Stupid me :D

**Comment by dlemstra** [comment]
How are you reading the image? You will probably need to specify the format.

**Comment by dlemstra** [comment]
Can we close this issue?

**Comment by SebastianStehle** [comment]
No, sorry ... I have not seen your answer. I do not specify the format. I just use the stream.

**Comment by dlemstra** [comment]
When you read a `TGA` file from a `stream` you will need to use the overload that specifies the `format`. The Magick.NET library cannot automatically determine that it is a `TGA` file.

**Comment by SebastianStehle** [comment]
Let my try that.

**Comment by SebastianStehle** [comment]
It works partially. Loading images works but there is no solution if you just need the metadata, e.g. Ping or MagickImageInfo

**Comment by dlemstra** [comment]
You can do this:

```C#
var readSettings = new MagickReadSettings
{
    Format = MagickFormat.Tga
};
image.Ping(stream, readSettings);
```

Because this is not a very common use case there is no `format` overload in the `Ping` method.

**Comment by SebastianStehle** [comment]
Awesome, this works great :)
