### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by smoketlt** [dlemstra/Magick.NET#1085]
### Description
Resize psd file. Doesn't give the correct result. The layers shift relative to each other.
![Resize](https://user-images.githubusercontent.com/95740394/145169898-90ed4b8c-98f0-4332-aca8-0bce02866795.jpg)

```
MagickImageCollection magickImages = new MagickImageCollection(filePath);
foreach(var layers in magickImages){
  layers.Resize(new Percentage(50));
}
magickImages.Write(dir +".psd");
```

### System Configuration
- Magick.NET-Q16-AnyCPU  v8.4.0.0
- Visual studio 2019; Windows Forms app; Windows 10
- Scale, Sample, give the same result
- psd file https://drive.google.com/file/d/13kcUV2yJNohaMMkPu5Wf6rrBTXBmft5w/view?usp=sharing
Thank you!

**Comment by dlemstra** [comment]
Attaching file zipped: [ImResizeTest.zip](https://github.com/dlemstra/Magick.NET/files/7675926/ImResizeTest.zip)

**Comment by smoketlt** [comment]
@dlemstra  What this mean? I do something wrong? Please do some answer.

**Comment by dlemstra** [comment]
I attached your image to this issue to make sure I can still access the image in case it gets removed from the google drive.

**Comment by dlemstra** [comment]
Can you give it another try with the new release that has just been published?

**Comment by smoketlt** [comment]
Perfect! Work like a charm! Thanks a lot!
