### ISSUE TITLE
MagickImageCollection is empty on Linux

### ISSUE THREAD

**Issue by d00ML0rDz** [dlemstra/Magick.NET#1088]
### Description
When I run the code below on Ubuntu 20.04, the collection.Count always returns 0. I have ffmpeg installed and accessible via the command line, so I'm not quite sure what's going wrong. I also have ubuntu-restricted-extras and libavcodec58 installed as per this post: https://askubuntu.com/questions/214421/how-to-install-the-mpeg-4-aac-decoder-and-the-h-264-decoder to ensure that I can play the MP4 video.  This does seem to run correctly on Windows.
```
var file = @"{path_to_mp4_file}";
using (var collection = new MagickImageCollection(file, MagickFormat.Mp4))
{
    Console.WriteLine(collection.Count);
}
```

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 8.4.0
- Environment (Operating system, version and so on): Ubuntu 20.04
- Additional information: FFmpeg version 4.2.4-1ubuntu0.1

**Comment by dlemstra** [comment]
It turns out that you found a bug inside ImageMagick. The Linux build of Magick.NET uses the built-in delegates of ImageMagick to execute the ffmpeg command. But that built-in table seemed to have an incorrect configuration for the `mp4` delegate. This issue will be resolved in the next release.

**Comment by d00ML0rDz** [comment]
Glad that I could help. Just as a heads up, I also tried running the same test project on a Mac VM and it had the same issue.

Will let you know if this is resolved on my end when the update comes out. Cheers 😊

**Comment by dlemstra** [comment]
Can you give this another try with the latest release @d00ML0rDz?

**Comment by d00ML0rDz** [comment]
Yep, that looks to be working now. Thank you for the quick fix
