### ISSUE TITLE
Extent bug with background color

### ISSUE THREAD

**Issue by mykmykpet** [dlemstra/Magick.NET#109]
I'm trying convert TIFF with transparent background to JPG with white back with Extent method, but output has black background until I pass to method different dimensions.
Look a demo: [https://youtu.be/AJVLo4kKz6M](https://youtu.be/AJVLo4kKz6M)

**Comment by dlemstra** [comment]
The black pixels are most likely transparent. The windows image viewer shows this as black. I have created a n image viewer myself that shows this better: http://magickviewer.azurewebsites.net/. 

When you try to extent the image and it already has the correct size nothing will happen. You could call `image.ColorAlpha(MagickColors.White)` before you call extent to make sure you always get a white background.

**Comment by dlemstra** [comment]
@mykmykpet Can we close this issue?

**Comment by mykmykpet** [comment]
Yes, your solution works
