### ISSUE TITLE
pdf to image wrongly converted (€ ==>B)

### ISSUE THREAD

**Issue by fogerau** [dlemstra/Magick.NET#1093]
### Description
I have one pdf thas is wrongly converted to image,
![image](https://user-images.githubusercontent.com/96244439/146381407-eb9e4fec-faf2-44e9-b29a-6a45c8f6a0fd.png)
is converted to 
![image](https://user-images.githubusercontent.com/96244439/146381745-c62f2d9f-8541-4103-b4bd-3568c120bbf9.png)

### Steps to Reproduce

using ImageMagick;
using PdfSharpCore.Drawing;
using PdfSharpCore.Pdf;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace Ged.WebService.Core.Utils
{
    public class ImageConverter
    {
        public static byte[] PdfToPdfImage(byte[] pdf)
        {
            PdfDocument s_document = new();

            MagickNET.SetTempDirectory(@"c:\tmp");
            using (MagickImageCollection images = new())
            {
                MagickReadSettings se = new()
                {
                    Density = new Density(144, 144),
                    Debug=true,
                    Verbose=true                     
                };

                EventHandler<WarningEventArgs> warningDelegate = delegate (object sender, WarningEventArgs arguments)
                {
                    Console.WriteLine(arguments.Message);
                }; 
                images.Warning += warningDelegate;
                images.Read(pdf, se);
                for (int i = 0; i < images.Count; i++)
                {
                    PdfPage page = s_document.AddPage();

                    XGraphics gfx = XGraphics.FromPdfPage(page);
                    MemoryStream ms = new MemoryStream();
                    images[i].Write(ms, MagickFormat.Png);

                    XImage ximage = XImage.FromStream(() => new MemoryStream(ms.ToArray()));
                        

                    page.Width = ximage.PointWidth;
                    page.Height = ximage.PointHeight;

                    images[i].Dispose();
                    gfx.DrawImage(ximage, 0, 0);
                }
                MemoryStream ss2 = new();
                s_document.Save(ss2);
                return ss2.ToArray();
            }
      }
}
- Magick.NET version: Magick.NET-Q16-HDRI-x64
- Environment : Windows 10
- Additional information: .net 5.0

**Comment by dlemstra** [comment]
This looks like a Ghostscript issue. Which version do you have installed? It might also be possible that you are getting this output because the font that is being used cannot render a `€`.

**Comment by Loongle** [comment]
Yes, this is a Ghostscript issue, The system lacks a font famliy, but how do you set the default font to notify GhostScript?

**Comment by dlemstra** [comment]
Are you using a recent version of Ghostscript? Upgrading might help, there does not appear to be an option for this.
