### ISSUE TITLE
No pixels defined in cache for some PDF's

### ISSUE THREAD

**Issue by kdeconinck** [dlemstra/Magick.NET#1094]
### Description
When using the `Ping` command on a specific PDF asset, the following exception is raised:

**Exception Message:** _no pixels defined in cache `C:/Users/KDECON~1/AppData/Local/Temp/magick-igIAnLjjffRbTW8Wg69TDYJeHOBYM2i41' @ error/cache.c/OpenPixelCache/3682_

**Stacktrace:** _at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /\_/src/Magick.NET/Native/NativeInstance.cs:line 57
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings\`1 settings) in /\_/src/Magick.NET/Native/MagickImage.cs:line 5309
   at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings\`1 readSettings, Boolean ping) in /\_/src/Magick.NET/MagickImage.cs:line 7258
   at ImageMagick.MagickImage.Ping(String fileName, IMagickReadSettings\`1 readSettings) in /\_/src/Magick.NET/MagickImage.cs:line 4717
   at ImageMagick.MagickImage.Ping(String fileName) in /_/src/Magick.NET/MagickImage.cs:line 4708
   at Program.<<Initialize>>d__0.MoveNext() in :line 8

### Steps to Reproduce
Upload the following asset file: [asset.pdf](https://github.com/dlemstra/Magick.NET/files/7735578/asset.pdf)
Ensure that GhostScript is installed on your machine. I'm using GhostScript 9.04 (but it can be reproduced on machine running GhostScript 9.54 as well) - Other versions have not been tested.
Use the following RoslynPad script to reproduce the error.
_**NOTE:** Change the path of the actual PDF to the correct location.

```
#r "nuget:Magick.NET-Q16-AnyCPU/8.5.0"

var image = @"C:\Temp\asset.pdf";
var imageMagickImage = new ImageMagick.MagickImage();

try
{
    imageMagickImage.Ping(image);
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
    Console.WriteLine(ex.StackTrace);
}
```

### System Configuration

- Magick.NET version: 8.5.0 - But can be reproduced with version 7.23.2.1 - Other versions have not been tested.
- Environment (Operating system, version and so on): Microsoft Windows 10 Professional - Version	10.0.19043 Build 19043.

**Comment by kdeconinck** [comment]
After some further investigation, I do have found some more information which can help investigating this issue.

![image](https://user-images.githubusercontent.com/3583827/146654200-c127399c-17e1-45ba-8005-fc6c7bd5a071.png)

**Comment by dlemstra** [comment]
Thanks for reporting this. You are getting this error message because it seems that we set the colorspace before we check the image size. I just made a patch and now I get this error message:

```
I:\issues\magick\1094>identify asset.pdf
identify: negative or zero image size `C:/Users/Dirk/AppData/Local/Temp/magick-ALFy9diAQkA6X6ltcRux5maMsQIh_X2o1' @ error/pnm.c/ReadPNMImage/481.
identify: PDFDelegateFailed `[ghostscript library 9.55] -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pamcmyk32" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r2.0x2.0" -dPrinted=false  "-sOutputFile=C:/Users/Dirk/AppData/Local/Temp/magick-ALFy9diAQkA6X6ltcRux5maMsQIh_X2o%d" "-fC:/Users/Dirk/AppData/Local/Temp/magick-0eQQzsOWqDeLVmLfCASs1__wHut6iNGL" "-fC:/Users/Dirk/AppData/Local/Temp/magick-4kWkQfYZ7k-s2vetGuqOuonw0F0151qK": (null)' @ error/pdf.c/ReadPDFImage/714.
```

**Comment by kdeconinck** [comment]
Thank you for this patch. Is there any way to be able to retrieve the color space (even with a negative or image zero size)?
When we're using ImageMagick's `Identify.exe`, we can retrieve the color space.

```
admin in C:\Program Files (x86)\ImageMagick-6.7.4-Q16 λ .\identify.exe  -verbose -ping  -size 32x32 -density 5 -format "Width: %W\r\nHeight: %H\r\nFormat: %m\r\nColorSpace: %[colorspace]\r\nPhotoshop Path: %[8BIM:2999,2999]\r\nClipping Path: %[8BIM:1999,2998:#1]\r\n"  "asset.pdf"
Width: 4
Height: 1
Format: PDF
ColorSpace: CMYK
Photoshop Path:
Clipping Path:
```

**Comment by dlemstra** [comment]
Good point. I think my patch broke that now. Will need to check if I can still add that though.

**Comment by dlemstra** [comment]
You will not be able to get the information because we don't return an image and it's information when an error occurs. 

Are you testing this with the same `asset.pdf` file? The version that you are using (`6.7.4`) is an ancient version of ImageMagick that should not be used anymore. I don't understand why you don't get an error with that old version. Maybe you are also using a different version of Ghostscript there?
