### ISSUE TITLE
AntiAliasing property does nothing for SVG

### ISSUE THREAD

**Issue by IvanMurzak** [dlemstra/Magick.NET#1095]
### Description
Changing ```AntiAliasing``` property in the Settings instance does not reflect a result. For my project I need to rasterize svg to png without anti-aliasing. But for some reason, Magick.NET ignores the setup and forces to anti-aliasing always. Also, I tried to add in svg file the field ```<svg shape-rendering="crispEdges"> ... </svg>```, it didn't help.

### Steps to Reproduce
```
        var antiAliasing = false;

        var settings = new MagickReadSettings 
        { 
            Format = MagickFormat.Svg, 
            BackgroundColor = MagickColors.Transparent, 
            AntiAlias = antiAliasing,
            StrokeAntiAlias = antiAliasing
        };

        var svg = File.ReadAllText(svgFilePath);
        using (var image = new MagickImage(Encoding.UTF8.GetBytes(svg), settings))
        {
            if (!File.Exists(pngFilePath))
                File.Create(pngFilePath);

            image.Write(new FileInfo(pngFilePath), MagickFormat.Png32);
        }
```

### System Configuration
- Packages downloaded from Nuget, unpacked, DLLs for .NET standard 2.0 taken into my Unity project. Just that DLLs are in usage.
-- Magick.NET.Core
-- Magick.NET.SystemDrawing
-- Magick.Native-Q16-x64 (for windows)

- Magick.NET version: ```8.5.0```
- Environment (Operating system, version and so on): Windows 10 x64

**Comment by dlemstra** [comment]
Do you have a sample svg file that can be used to reproduce this issue?

**Comment by IvanMurzak** [comment]
Sorry, my mistake, I used SVG which contained a rasterized image inside 🤣

**Comment by dlemstra** [comment]
No problem. But I did some research and it might be possible to set the font anti-aliasing of the library that we are using to read the SVG files. But I needed a good test file to check this,
