### ISSUE TITLE
ImageMagick.Number value conversion

### ISSUE THREAD

**Issue by RobertPastisss** [dlemstra/Magick.NET#1096]
Hello, I have a problem when I want to convert an image with exif data.
For the tag "{pixelxdimension}" and "{pixelydimension}", I try to convert the value with different types (Ushort, short ...) but I have a conversion error back. In addition, the type is always {imagemagick.number} despite the conversion (with Tostring () and when I want to keep the value). Is it a bug? Or do I use a bad type for conversion?

I use the last version of Magick.NET (8.5.0)

![CaptureIssueMagick](https://user-images.githubusercontent.com/96741869/147510785-2561a56a-2b5f-4a7c-afdf-21ab0bcfeef9.PNG)

Thanks !

**Comment by dlemstra** [comment]
I don't understand what you are trying to ask me?
