### ISSUE TITLE
mp4 video file get->save = not the same frameRate? AnimationDelay/AnimationTicksPerSecond props?

### ISSUE THREAD

**Issue by Nigrimmist** [dlemstra/Magick.NET#1102]
Hello! I am using latest magick (windows 10, 16-any-cpu) to get frames from mp4 (through the latest ffmpeg) and can't understand why if 
1) parse mp4 file to magickImage collection
2) save collection to another one mp4

i getting file with incorrect timing between frames? Sample of code is pretty simple : 

```
string incomingFilePath = AppContext.BaseDirectory + "TempGifs/test3.mp4";                   

using (var videoFrames = new MagickImageCollection(incomingFilePath, MagickFormat.Mp4))
{                        
    videoFrames.Write(AppContext.BaseDirectory + "Temp\\orig" + (long)DateTime.UtcNow.Subtract(DateTime.UnixEpoch).TotalSeconds + ".mp4", MagickFormat.Mp4);
}
```

Another one question - in case i configure for each image in collection AnimationDelay and then save i am getting not the same speed of frames. AnimationDelay i am counting from
`image.AnimationTicksPerSecond / 10`
So question number 2 is **how can i set correct delay number** as for mp4 "test2.mp4" correct delay is 5, but for "test3.mp4" is about ~9, but first image from both collections has AnimationTicksPerSecond the same = 100. So no idea, how to calculate it right. Could you please make an advice? Attaching test2.mp4 and test3.mp4 (originally it was gifs, but Telegram converted all gifs to mp4 files, so files are from Telegram servers after conversion from gif, if it is matters by some reason).

https://user-images.githubusercontent.com/1579535/148592197-c10b51f5-33eb-4055-aa69-e7768b730186.mp4

https://user-images.githubusercontent.com/1579535/148592200-4ab1b109-8b9b-4c54-9902-ecbfae5a6d2b.mp4

**Comment by dlemstra** [comment]
We made some changes in ImageMagick that might fix this. Can you give this another try with the next release of Magick.NET @Nigrimmist when that has been published?

**Comment by Nigrimmist** [comment]
Ok, thank you. So waiting the new release for testing 👍

**Comment by dlemstra** [comment]
Can we close this issue @Nigrimmist?

**Comment by Nigrimmist** [comment]
Checked few mins ago. Output mp4 is not the same as input after simple "re-make" without any additional configuring, but seems like it is "almost the same", so may be closed i think. Thanks
