### ISSUE TITLE
Fontconfig error: Cannot load default config file

### ISSUE THREAD

**Issue by chrisheil** [dlemstra/Magick.NET#1106]
### Description
Similar to #598, but those steps did not resolve the errors. After following those steps I get an error, but the application keeps running.

```
// hundreds of errors like this
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 4: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/conf.d/90-synthetic.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'
// ...
Cannot load config file from /etc/fonts/fonts.conf
```

### Steps to Reproduce

New .NET 6 console application

``` csharp
using ImageMagick;

var fileStr = File.ReadAllBytes("./Images/test.tiff");
using var image = new MagickImage(fileBytes);

image.Annotate("Hello world", Gravity.North);
image.Write("newImage.tiff");
```

Run this code results in the following error

```
Fontconfig error: Cannot load default config file
```

In the same terminal, run the command `export FONTCONFIG_PATH=/etc/fonts` and re-run the application. Results in the error message I included in the section above.

### System Configuration

- Magick.NET version: Q8-x64 version 8.5.0
- Environment (Operating system, version and so on): Ubuntu 20.04 (fresh install), .NET 6 SDK
- Additional information:
  - Running the commands from the [related ticket](https://github.com/dlemstra/Magick.NET/issues/598#issuecomment-605603721) did not change the error for me.
  - Suggestions from other projects in GitHub with similar issues did not resolve the issue either. Each item below were suggestions that did not work
  - Reinstalling `fontconfig`
  - Backup original `/etc/fonts` folder, delete it, then installed `fontconfig-config` to re-initialize config
  - Removing the user cache file using `rm -r ~/.cache/fontconfig`
  - Installed `libfontconfig1-dev`

**Comment by dlemstra** [comment]
Can you also reproduce this issue on a docker container? Can you share a repostory with a `Dockerfile`? That would make it easier for me to debug your issue.

**Comment by chrisheil** [comment]
I have created a repo which reproduces this issue here: https://github.com/chrisheil/magicknet.1106

I used the `ubuntu:20.04` docker image, and included the steps provided by 598 in the Dockerfile

**Comment by dlemstra** [comment]
Thanks for the repository. I can reproduce your issue but I have no idea what is causing this issue. I just tested if upgrading the fontconfig library that is being used my the Native library would resolve the issue but that didn't seem to work. I think you will probably need to create your own version of `fonts.conf` and put that in a directory that you pass to `MagickNET.SetFontConfigDirectory("yourfolder")`

**Comment by chrisheil** [comment]
I noticed in [this file](https://github.com/dlemstra/Magick.NET/blob/ecc4e2ac3bd2eb963a53493b0e82084fca86fc91/src/Magick.Native/libraries/linux/Notice.txt) the version of fontconfig Magick.NET is using looks like it is 2.12.6. In Ubuntu 20.04 (and now the dotnet sdk for 3.1 and 6.0) it seems the version of fontconfig is 2.13.1.

If you update the Dockerfile from my example to run Ubuntu:18.04 it will complete successfully, and Ubuntu 18.04 runs fontconfig 2.12.6. I think this might be the cause of the issue.

**Comment by chrisheil** [comment]
I took your recommendation and got it to work. For future reference if anyone else runs into this issue, here are examples to get it working.

``` dockerfile
FROM ubuntu:18.04
RUN apt-get update && apt-get upgrade -y
RUN apt-get install fontconfig -y
```

Copy fonts folder from docker container

``` bash
docker cp <containerId>:/etc/fonts/* ~/Downloads
sudo mkdir /etc/fonts/2.12
sudo mv ~/Downloads/fonts/* /etc/fonts/2.12
```

Run Console app from ubuntu 20.04 or any OS with fontconfig 2.13+ installed

``` csharp
using ImageMagick;
MagickNET.SetFontConfigDirectory("/etc/fonts/2.12");
using var image = new MagickImage("./Images/test.tiff");
image.Annotate("Hello world", Gravity.North);
image.Write(@"temp.tiff");
```

I am not sure if the commands in [the related issue](https://github.com/dlemstra/Magick.NET/issues/598#issuecomment-605603721) are required or not, but if this fails give that a try as well
