### ISSUE TITLE
Improper Image Header when reading PNG

### ISSUE THREAD

**Issue by coderangerdan** [dlemstra/Magick.NET#111]
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am getting the following exception when attempting to read the attached image; i guess this is another libpng issue.

Resaving from paint.net fixes the problem.

### Stack Trace
```
MagickCorruptImageErrorException: ImageMagick.MagickCorruptImageErrorException: improper image header `newfile-temp.png' @ error/png.c/ReadPNGImage/4216 
at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) 
at ImageMagick.MagickImage.NativeMagickImage.ReadFile(MagickSettings settings) 
at ImageMagick.MagickImage..ctor(String fileName, MagickReadSettings readSettings) 
```

![010553a9-bd0c-4fe8-95d2-1ecabe5facad-id-xtra-white-copy-002-](https://user-images.githubusercontent.com/1733292/31231946-42dd503a-a9e0-11e7-9139-4f1318ef9937.png)

### System Configuration
Windows 10 Visual Studio 2017, but also on Windows Server multiple versions

- ImageMagick version: Magick.NET-Q16-x64 v7.0.7.300
- Environment (Operating system, version and so on): Windows (any)
- Additional information: none not already mentioned above

**Comment by dlemstra** [comment]
Could you add a link to the original image? It looks like Github changed it into a JPEG file.

**Comment by coderangerdan** [comment]
Heres a zip version which shouldnt be messed with ... I hope :-)

[BadImageFormat-ID-Xtra-White-copy-002-.zip](https://github.com/dlemstra/Magick.NET/files/1366847/BadImageFormat-ID-Xtra-White-copy-002-.zip)

**Comment by coderangerdan** [comment]
After discussing with Dirk. The image uploaded is actually a JPEG and not a PNG as described by the file extension.

Therefore it’s not a bug but a user error.
