### ISSUE TITLE
SVG with realtive paths to images not converted correctly

### ISSUE THREAD

**Issue by devviktoria** [dlemstra/Magick.NET#1113]
### Description
I have an SVG with linked images using relative paths. I  want to convert this using Magick.Net. If I execute the command convert thumb.svg thumb.jpg from the directory where the SVG is, it converts it correctly. But if I use one of the sample code provided with absolute paths it doesn't work, the images are not appearing on the converted image.

### Steps to Reproduce
string svgFileName = "full path to thumb.svg";
string jpgFileName = "full path to thumb.svg";
using (var image = new MagickImage(svgFileName))
{
        image.Write(jpgFileName);
}

### System Configuration
- Magick.NET version:  8.6.1
- Environment (Operating system, version and so on): Ubuntu 18.04

Isn't there any setting where I can specify the current directory or that relative paths should be used during processing the SVG file?

**Comment by dlemstra** [comment]
Can you share your input and the corresponding files so I can try go figure out what kind of issue you got.

**Comment by dlemstra** [comment]
I am going through my old issues and I found this one. I am sorry for the late response but I am unable to reproduce your issue. This might have been fixed now? Another reason could be that you are reading from a network share and then referenced images don't work. Closing this issue now but feel free to re-open it if you can reproduce this with the latest version.
