### ISSUE TITLE
MagickImage.Format/ExifProfile.GetValue() allocate 2KB/11KB of memory after each call

### ISSUE THREAD

**Issue by rpnetcoder** [dlemstra/Magick.NET#1122]
### Description
Hello Devs,

I've been profiling a website's memory and detected an enormous amount of memory allocated by ImageMagick's MagickImage.Format/ExifProfile.GetValue() methods - new 2KB/11KB added after each call. These members call EnumHelper.Parse() methods, which in its turn call Enum.GetValues()/Enum.GetNames methods. When invoked on MagickFormat enum, Enum.GetValues()/Enum.GetNames return arrays with 267 values which after method execution immediately become memory garbage and intensify GC pressure thus slowing down the website. The extensive memory allocation is also present when invoking EnumHelper.ConvertFlags() due to the same reason - Enum.GetValues().

### Steps to Reproduce

The MagickImage.Format allocation can be reproduced on any image, while the ExifProfile.GetValue() allocation is reproducible when executing a benchmark below on any image with Exif data:

![image](https://user-images.githubusercontent.com/98753567/151812764-1367629a-49d5-48d8-881b-a619189a4495.png)

`
using BenchmarkDotNet.Attributes;
using ImageMagick;

namespace Benchmarks.ImageMagick
{
	[MemoryDiagnoser]
	public class MagickImageBenchmark
	{
		private MagickImage _image;

		[GlobalSetup]
		public void GlobalSetup()
		{
			_image = new MagickImage(@"..\..\..\..\..\..\..\..\Data\Images\MagickImageBenchmark\station.jpg");
		}

		// result: mean 5.5 microseconds, allocated 2 KB
		[Benchmark]
		public MagickFormat BenchmarkImageMagickFormat() => _image.Format;

		// result: mean 466.6 microseconds, allocated 11 KB
		[Benchmark]
		public IExifValue? BenchmarkExifProfileGetValue() => _image.GetExifProfile().GetValue(ExifTag.Orientation);

		[GlobalCleanup]
		public void GlobalCleanup()
		{
			_image.Dispose();
		}
	}
}
`

### System Configuration

- Magick.NET version: Magick.NET-Q16-x64, 9.0.0
- Environment: Windows 10

### Solution

I've created a fix to the issue that you can use for free in Magick.NET as is, or modify it before applying. Here is the result of a benchmark that executes the original and fixed version of Parse(string, Enum), Parse(int, Enum), Parse(ushort, Enum), ConvertFlags(Enum) 10 times and measures the execution time and memory allocation. 

![image](https://user-images.githubusercontent.com/98753567/151815904-52906d49-1a79-4c6e-83f8-a6c94e6388c6.png)

As you can see the execution time and memory allocations decreased dramatically. The benchmark itself:

`
using BenchmarkDotNet.Attributes;
using ImageMagick;
using ImageMagick.Formats;

namespace Benchmarks.ImageMagick
{
	[MemoryDiagnoser]
	public class EnumHelperBenchmark
	{
		private static readonly string[] Formats = { "Jpg", "Png", "WebP", "Tiff", "Gif", "Bmp", "Svg", "Avif", "Psd", "Pdf" };
		private static readonly int[] FormatValues = { 111, 179, 250, 231, 78, 18, 225, 12, 193, 164 };

		private static readonly JpegProfileTypes[] ProfileTypes = { 
			JpegProfileTypes.App, JpegProfileTypes.App | JpegProfileTypes.Exif, JpegProfileTypes.App | JpegProfileTypes.Xmp,
			JpegProfileTypes.Icc, JpegProfileTypes.Icc | JpegProfileTypes.Xmp, JpegProfileTypes.Icc | JpegProfileTypes.Iptc,
			JpegProfileTypes.Xmp, JpegProfileTypes.Xmp | JpegProfileTypes.Exif, JpegProfileTypes.Xmp | JpegProfileTypes.Iptc,
			JpegProfileTypes.App | JpegProfileTypes.Xmp | JpegProfileTypes.Exif | JpegProfileTypes.Icc | JpegProfileTypes.Iptc
		};

		[Benchmark]
		public void BenchmarkOriginalStringEnumParse()
		{
			foreach (string format in Formats)
			{
				EnumHelper.Parse(format, MagickFormat.Unknown);
			}
		}

		[Benchmark]
		public void BenchmarkImprovedStringEnumParse()
		{
			foreach (string format in Formats)
			{
				EnumHelperImproved.Parse(format, MagickFormat.Unknown);
			}
		}

		[Benchmark]
		public void BenchmarkOriginalIntEnumParse()
		{
			foreach (int formatValue in FormatValues)
			{
				EnumHelper.Parse(formatValue, MagickFormat.Unknown);
			}
		}

		[Benchmark]
		public void BenchmarkImprovedIntEnumParse()
		{
			foreach (int formatValue in FormatValues)
			{
				EnumHelperImproved.Parse(formatValue, MagickFormat.Unknown);
			}
		}

		[Benchmark]
		public void BenchmarkOriginalUshortEnumParse()
		{
			foreach (int formatValue in FormatValues)
			{
				EnumHelper.Parse((ushort)formatValue, MagickFormat.Unknown);
			}
		}

		[Benchmark]
		public void BenchmarkImprovedUshortEnumParse()
		{
			foreach (int formatValue in FormatValues)
			{
				EnumHelperImproved.Parse((ushort)formatValue, MagickFormat.Unknown);
			}
		}

		[Benchmark]
		public void BenchmarkOriginalConvertFlags()
		{
			foreach (JpegProfileTypes profileType in ProfileTypes)
			{
				EnumHelper.ConvertFlags(profileType);
			}
		}

		[Benchmark]
		public void BenchmarkImprovedConvertFlags()
		{
			foreach (JpegProfileTypes profileType in ProfileTypes)
			{
				EnumHelperImproved.ConvertFlags(profileType);
			}
		}
	}
}
`
### Solution details

ConvertFlags() :
* Stores a copy of Enum.GetValues() in a thread-safe cache implemented as ConcurrentDictionary.
* Removes redundant ToArray() call in "string.Join(",", flags.ToArray())" code.

Parse(string, Enum) :
* Stores a copy of Enum.GetNames() in a thread-safe cache implemented as ConcurrentDictionary.
* Applies a binary search while seeking for an Enum name in the cache. Note that a cache item is getting sorted before populating the cache in order to be eligible for the binary search.

Parse(int, Enum)/Parse(ushort, Enum) : 
* Stores a copy of Enum.GetValues() in a thread-safe cache implemented as ConcurrentDictionary.
* Applies a binary search while seeking for an Enum value in the cache. Note that a cache item is getting sorted before populating the cache in order to be eligible for the binary search.

The fixed version of EnumHelper is here: 
[EnumHelper.cs.txt](https://github.com/dlemstra/Magick.NET/files/7971899/EnumHelper.cs.txt)

And thanks for creating this awesome library!

**Comment by dlemstra** [comment]
Thanks for reporting this and your research ❤. 

This class uses this kind of code to be compatible with .NET 2.0. In previous version I had two classes. One for .NET Framework and one for .NET Core. I removed that a while back so I don't need to maintain both implementations. But looking at your results I do think that I should restore this again. Thanks for sending the class but I am going for an implementation where I won't have a cache. With that patch I get the following results:

```
.NET 6.0
|              Method |         Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|-------------------- |-------------:|----------:|----------:|--------:|-------:|----------:|
| StringEnumParse_Org |  12,491.5 ns |  44.83 ns |  41.94 ns |  3.4790 | 0.1221 |  21,887 B |
| StringEnumParse_New |   4,165.8 ns |  11.22 ns |   8.76 ns |       - |      - |         - |
| StringEnumParse_Imp |   5,054.8 ns |  23.05 ns |  21.56 ns |  0.0381 |      - |     241 B |
|    IntEnumParse_Org | 255,806.5 ns | 425.41 ns | 332.14 ns | 28.8086 |      - | 181,341 B |
|    IntEnumParse_New |   1,184.2 ns |   7.19 ns |   6.73 ns |  0.0763 |      - |     480 B |
|    IntEnumParse_Imp |     969.4 ns |   2.14 ns |   2.00 ns |  0.0381 |      - |     240 B |
| UshortEnumParse_Org | 255,197.4 ns | 471.03 ns | 417.55 ns | 28.8086 |      - | 181,341 B |
| UshortEnumParse_New |   1,254.7 ns |   3.97 ns |   3.52 ns |  0.0763 |      - |     480 B |
| UshortEnumParse_Imp |     988.8 ns |  11.17 ns |  10.45 ns |  0.0381 |      - |     240 B |
|    ConvertFlags_Org |  12,132.3 ns |  69.07 ns |  64.61 ns |  1.8463 |      - |  11,593 B |
|    ConvertFlags_New |  10,376.5 ns |  36.60 ns |  34.24 ns |  0.9613 |      - |   6,073 B |
|    ConvertFlags_Imp |   3,406.1 ns |  26.29 ns |  24.59 ns |  0.4311 |      - |   2,712 B |

.NET 4.8
|              Method |       Mean |     Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|-------------------- |-----------:|----------:|----------:|--------:|-------:|----------:|
| StringEnumParse_Org |  16.742 us | 0.0876 us | 0.0777 us |  3.6316 | 0.1221 |  22,920 B |
| StringEnumParse_New |  17.112 us | 0.0417 us | 0.0370 us |  0.1831 |      - |   1,207 B |
| StringEnumParse_Imp |   7.818 us | 0.0533 us | 0.0499 us |  0.1831 |      - |   1,206 B |
|    IntEnumParse_Org | 399.132 us | 1.6433 us | 1.4568 us | 28.8086 |      - | 181,875 B |
|    IntEnumParse_New |   2.050 us | 0.0037 us | 0.0033 us |  0.1144 |      - |     722 B |
|    IntEnumParse_Imp |   1.383 us | 0.0018 us | 0.0017 us |  0.0381 |      - |     241 B |
| UshortEnumParse_Org | 400.787 us | 2.4682 us | 2.3087 us | 28.8086 |      - | 181,875 B |
| UshortEnumParse_New |   2.057 us | 0.0038 us | 0.0035 us |  0.1144 |      - |     722 B |
| UshortEnumParse_Imp |   1.374 us | 0.0022 us | 0.0020 us |  0.0381 |      - |     241 B |
|    ConvertFlags_Org |  19.842 us | 0.0944 us | 0.0883 us |  1.9531 |      - |  12,326 B |
|    ConvertFlags_New |  18.107 us | 0.0330 us | 0.0293 us |  1.5259 |      - |   9,758 B |
|    ConvertFlags_Imp |   6.469 us | 0.0176 us | 0.0156 us |  0.6027 |      - |   3,820 B |
```

And yes `ConvertFlags` could probably still need some more improvements but I can settle with the current changes. The primary methods that needed to be improved were `Parse` for `int` and `ushort` and they are a lot better now.

**Comment by rpnetcoder** [comment]
If we can achieve such impressive results without the internal cache, that would be even better because of easier implementation. Thanks for taking care of this.

**Comment by dlemstra** [comment]
Those changes have been pushed yesterday and I will try to publish a new release later this week.

**Comment by rpnetcoder** [comment]
By the way, if one day you decide to improve EnumHelper.ConvertFlags(), there could be a simple solution "return value.ToString().Replace(", ", ",")" because Enum.ToString() already takes care of detecting Flags attribute.

The benchmark that runs ConvertFlags() 10 times in a loop displays the following results:

|                   Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------- |----------:|----------:|----------:|-------:|----------:|
| BenchmarkOldConvertFlags | 57.174 us | 0.3161 us | 0.2957 us | 1.7090 |   5,433 B |
| BenchmarkNewConvertFlags |  4.171 us | 0.0258 us | 0.0228 us | 0.2670 |     856 B |

However, the values returned by the old and new implementations are little different so it requires testing and reviewing:

Channels enum1 = Channels.Blue | Channels.Red;
string strOld1 = EnumHelper.ConvertFlagsOld(enum1); // None,Red,Yellow
string strNew1 = EnumHelper.ConvertFlagsNew(enum1); // Cyan,Blue

JpegProfileTypes enum2 = JpegProfileTypes.App | JpegProfileTypes.Exif | JpegProfileTypes.Xmp;
string strOld2 = EnumHelper.ConvertFlagsOld(enum2); // App,Exif,Xmp
string strNew2 = EnumHelper.ConvertFlagsNew(enum2); // App,Exif,Xmp

LogEvents enum3 = LogEvents.Exception | LogEvents.Image;
string strOld3 = EnumHelper.ConvertFlagsOld(enum3); // None,Exception,Image
string strNew3 = EnumHelper.ConvertFlagsNew(enum3); // Exception,Image

**Comment by dlemstra** [comment]
Thanks for continuing your research. It looks like you actually found a "bug" with this. I don't think we should include None in the first example. It is not an issue but  it would be a beter idea to exclude it.

But this solution won't work when someone does a value that is not possible with the enumeration. For example `(JpegProfileTypes) 64`. This returns `"64"`. And checking `Enum.IsDefined(Channels.Blue | Channels.Red)` returns false. But maybe we should ignore that and let that fail/be ignored inside ImageMagick?

**Comment by rpnetcoder** [comment]
Enum.IsDefined(Channels.Blue | Channels.Red) might return false because Channels enumeration has duplicate values. Anyway, what I also noticed that ConvertFlags() isn't used as heavily as Parse(). So if there are any doubts that this change can break the existing functionality, then we can live with it, at least for now.

**Comment by dlemstra** [comment]
Turns out that I can use `ToString()` without removing the spaces works with ImageMagick so this will also be included in the next release.

**Comment by dlemstra** [comment]
The new package that includes the patches has just been published.

**Comment by rpnetcoder** [comment]
Works like a charm:

|                       Method |       Mean |     Error |    StdDev |  Gen 0 | Allocated |
|----------------------------- |-----------:|----------:|----------:|-------:|----------:|
|   BenchmarkImageMagickFormat |   1.768 us | 0.0232 us | 0.0217 us | 0.0191 |      64 B |
| BenchmarkExifProfileGetValue | 376.911 us | 4.6195 us | 3.8575 us | 0.4883 |   2,078 B |

Thank you!
