### ISSUE TITLE
MagickImage.Thumbnail(MagickGeometry): significant performance degradation between 9.0.0 and 9.1.0

### ISSUE THREAD

**Issue by rpnetcoder** [dlemstra/Magick.NET#1125]
### Description

After upgrading to 9.1.0, the application server had a high CPU usage and much slower image processing times.

As the result of an investigation, it became evident that MagickImage.Thumbnail(MagickGeometry) runs a few times slower between 9.0.0 and 9.1.0.

### Steps to Reproduce

Here below the benchmark which was executed with two images https://github.com/dlemstra/Magick.NET/files/8021544/images.zip and Magick.NET 9.0.0 / 9.1.0:

```
[MemoryDiagnoser]
public class MagickImageBenchmarks
{
  private MagickImage _image;
  
  [IterationSetup]
  public void IterationSetup()
  {
	  _image = new MagickImage(@"..\..\..\..\..\..\..\..\Data\Images\station.jpg");
  }
  
  [Benchmark]
  public void BenchmarkImageMagickThumbnail()
  {
	  MagickGeometry size = new MagickGeometry(1843, 1843)
	  {
		  Greater = true
	  };
	  _image.Thumbnail(size);
  }
  
  [IterationCleanup]
  public void IterationCleanup()
  {
	  _image.Dispose();
  }
}
```
The results below demonstrates from 3 to 63 times slower execution times:

**boats-5918×3947-2.5.jpg:**

9.0.0

|                          Method |    Mean |   Error |  StdDev | Allocated |
|-------------------------------- |--------:|--------:|--------:|----------:|
|   BenchmarkImageMagickThumbnail | 10.33 s | 0.103 s | 0.086 s |     640 B |

9.1.0

|                          Method |    Mean |   Error |  StdDev | Allocated |
|-------------------------------- |--------:|--------:|--------:|----------:|
|   BenchmarkImageMagickThumbnail | 31.48 s | 0.404 s | 0.358 s |     640 B |

**station.jpg:**

9.0.0

|                          Method |      Mean |     Error |    StdDev | Allocated |
|-------------------------------- |----------:|----------:|----------:|----------:|
|   BenchmarkImageMagickThumbnail |  36.03 ms |  0.714 ms |  1.425 ms |     640 B |

9.1.0

|                          Method |       Mean |    Error |   StdDev | Allocated |
|-------------------------------- |-----------:|---------:|---------:|----------:|
|   BenchmarkImageMagickThumbnail | 2,288.1 ms | 34.04 ms | 34.96 ms |     640 B |

### System Configuration
* Magick.NET version: Magick.NET-Q16-x64, 9.0.0 / 9.1.0
* Environment: Windows 10 /  Server 2019

### Analysis

The issue was most likely introduced by ImageMagick itself between releases of Magick.NET 9.0.0 / 9.1.0

Thanks

**Comment by rpnetcoder** [comment]
Looks like that the performance breaking change was reverted https://github.com/ImageMagick/ImageMagick/commit/75d1dbf70f63ae365e3359d4b8c473a546d68bca

**Comment by dlemstra** [comment]
Yup we decided to revert our change. Going to need to update ImageMagick this weekend and then run your benchmark locally to check this.

**Comment by rpnetcoder** [comment]
I have executed the benchmark with 9.1.2 and do confirm that the performance issue got fixed. Thanks a lot!
