### ISSUE TITLE
Graphics driver crash. OpenCL.

### ISSUE THREAD

**Issue by DanielSanIT** [dlemstra/Magick.NET#113]
When I change the size of a large photo (> 3Mb) - the graphic driver fails (not always). The processed image is completely black.
Tried on 2 different computers.
Tried 2 libraries - Magick.NET-Q8-AnyCPU and Magick.NET-Q16-HDRI-AnyCPU.
After disabling the Openlink "OpenCL.IsEnabled = false" - the library works stably.

**Comment by dlemstra** [comment]
Could you give it another try with the latest release we have made some OpenCL improvements.

**Comment by DanielSanIT** [comment]
I update to version 7.0.7.900.
The video driver falls on the first image of the first application launch.
The following images are processed normally. Before the program is restarted. The image is also black with the desired resolution.

Depends on the size of the image is not detected.
I checked it on one computer.

**Comment by Augus** [comment]
Some of our client report this issue too, but I can reproduce this problem in my evn.

**Comment by dlemstra** [comment]
I cannot reproduce your issue because I don't have the same hardware and drivers. It is probably an issue with your video card driver. I would advice you to disable OpenCL (`OpenCL.IsEnabled = false`) in your situation.

**Comment by Augus** [comment]
Thanks @dlemstra.
If disable OpenCL, will it cause any impact?

**Comment by DanielSanIT** [comment]
After disabling "OpenCL.IsEnabled = false" - the library works stably all time.

**Comment by dlemstra** [comment]
@Augus The impact of disabling OpenCL is that some operations might be a bit slower. But if you keep getting reports of issues with OpenCL from your clients you might want to just want to disable it.
