### ISSUE TITLE
Option to hide annotations when converting pdf to image

### ISSUE THREAD

**Issue by DSPAUL** [dlemstra/Magick.NET#1139]
Ghostscript has a flag "-dShowAnnots=false" that allows you to hide annotations when converting a pdf to an image. There seems to be no way in Magick.NET to use this flag or achieve this functionality. I hoped to find the option in MagickReadSettings but it is not there. 

It would be great if this option could be added or if someone knows another way to hide annotations when converting a pdf to an image.

**Comment by dlemstra** [comment]
It should be possible to add this option but it might take a while before this will become available. I am planning a new release this weekend and I don't think I can add and test it before doing that release.

**Comment by dlemstra** [comment]
Good news, it will be in the next release as a property called `HideAnnotations` in the `PdfReadDefines`.

**Comment by DSPAUL** [comment]
Awesome, thanks for implementing this so quickly!
