### ISSUE TITLE
Reverse sigmoidal contrast not implemented

### ISSUE THREAD

**Issue by neilgd** [dlemstra/Magick.NET#1141]
### Description
**Reverse** sigmoidal contrast doesn't seem to be possible

### Steps to Reproduce
As well as Sigmoidal Contrast, Image Magick as a Sigmoidal Contrast *Reduction* function (e.g. -sigmoidal-contrast 10,50% as well as +sigmoidal-contrast 10,50% - note the plus and minus signs). I don't think this is possible in Magick.NET.

See https://legacy.imagemagick.org/Usage/color_mods/#sigmoidal for more information

Not sure if this is a bug / feature request / if I'm not doing it correctly - sorry if I got this wrong.

**Comment by dlemstra** [comment]
That feature is actually already available it's now a boolean for the `SigmoidalContrast` method. When I added that method years ago I was not aware that it was used to perform an inverse `SigmoidalContrast`. The next release of Magick.NET will include an `InverseSigmoidalContrast` method and the boolean overloads will be removed. So for now you could use the boolean overloads but I will try to publish a new release with this change today or tomorrow.

**Comment by neilgd** [comment]
Ah, thank you! I hadn't spotted that overload.

**Comment by dlemstra** [comment]
Yeah that wasn't clear and that is why I will add the new method in the next release.

p.s. Thanks for sponsoring me!
