### ISSUE TITLE
Initialize MagickImage from ushort array

### ISSUE THREAD

**Issue by pindumb** [dlemstra/Magick.NET#1142]
Hello,

would it make sense to implement a MagickImage constructor which takes a ushort array instead of a byte array (for Q16)?

My input data is a ushort array and at the moment I have to convert it into a byte array using Buffer.BlockCopy. This conversion takes ~30 ms for large images. Can this conversion be avoided or does the internal C API require bytes?

**Comment by dlemstra** [comment]
The internal API requires a byte array. Why is your image data an ushort array?

**Comment by pindumb** [comment]
My input is from an industrial camera: ushort array of 16-bit gray values. But if the internal API requires a byte array this conversion can not be avoided. Thanks. :)

**Comment by dlemstra** [comment]
If those are just pixels you could also do this:

```C#
var width = 100;
var height = 100;
ushort[] data = GetData();
using var image = new MagickImage();
using var pixels = image.GetPixels();
pixels.SetArea(0, 0, width, height, data);
```

**Comment by pindumb** [comment]
> If those are just pixels you could also do this:
> 
> ```cs
> var width = 100;
> var height = 100;
> ushort[] data = GetData();
> using var image = new MagickImage();
> using var pixels = image.GetPixels();
> pixels.SetArea(0, 0, width, height, data);
> ```

This fails for me with "Invalid X coordinate: 0. Parametername: x'"

I think this is because Height and Width are not set for the MagickImage.

**Comment by dlemstra** [comment]
Woops sorry :) You should indeed size the size of the image, that should be: `new MagickImage(MagickColors.Black, width, height);`

**Comment by pindumb** [comment]
> Woops sorry :) You should indeed set the size of the image, that should be: `new MagickImage(MagickColors.Black, width, height);`

I couldn't get it working. It wants three channels, I only have one. ;)
I also tried with "image.Format = MagickFormat.Gray" after constructor. 

System.ArgumentException: 'Values should have 3 channels. Parametername: values'

**Comment by dlemstra** [comment]
I keep forgetting that I have a `ReadPixels` method in the `MagickImage` class. It does seem that this could use an extra overload where you can read the pixels in the quantum type of the image. I will add that later this week.

**Comment by pindumb** [comment]
Thank you @dlemstra :)

What "mapping" can I use for PixelReadSettings when I have gray values? I tried "R" and it works, but it feels wrong. ;)

**Comment by dlemstra** [comment]
Maybe `I` for intensity?
