### ISSUE TITLE
Apply SigmoidalContrast() to specific channels

### ISSUE THREAD

**Issue by neilgd** [dlemstra/Magick.NET#1144]
It would be useful to able to apply SigmoidalContrast() to a particular channel. For example, the ImageMagick commandline equivalent of:

`magick -channel R +sigmoidal-contrast 5,100%`

### Describe the solution you'd like
Ideally, pass in Channels as a parameter to SigmoidalContrast(), as is possible with the Evaluate() function, so an override like:

`image.SigmoidalContrast(Channels, Percentage, Percentage)`

### Describe alternatives you've considered
I've thought about extracting the channel, applying the function, and then rewriting it but it seems like overkill.

**Comment by dlemstra** [comment]
This will become available in the next release. Thanks for suggesting this.
