### ISSUE TITLE
Cannot read frames for a WebM file

### ISSUE THREAD

**Issue by sellorio2** [dlemstra/Magick.NET#1145]
### Description

I'm trying to use `MagickImageCollection` to get the frames of a `.webm` file but the frame list is empty. Also noticed that unlike `.png` I need to specify the Format for it to work.

### Steps to Reproduce

1. Load a `.webm` file into memory (byte array).
2. Use `new MagickImageCollection(data, MagickFormat.WebM)` to get the image collection instance.
3. Observe that the `Count` is zero.

### System Configuration

.Net Core 3.1 running a MVC Core web api.
Windows 10.
`Magick.NET-Q16-AnyCPU` version 10.0.0

I'm also happy to get any tips as to how to get the frame data by other means. I can't find anything online except for FFMpeg which requires files to be stored on the disk before being processed (obviously unacceptable for a web server).

**Comment by dlemstra** [comment]
Can you share a file that can be uaed to reproduce your issue?
