### ISSUE TITLE
Memory leak when using Thumbnail

### ISSUE THREAD

**Issue by trockefeller-pathway** [dlemstra/Magick.NET#1148]
### Magick.NET version

10.0.0

### Environment (Operating system, version and so on)

Windows 10

### Description

If you resize a `MagickImage` using the `Thumbnail` command, there is an apparent memory leak.

### Steps to Reproduce

I wrote a very simple console application that creates a `MagickImage` from grayscale pixel data (just to match the application that I originally ran into this problem with, it may have issues as well if the `MagickImage` is created in different ways)

When running the below code, my debugging console ended at around 3.7gb of used memory. When I commented out the Thumbnail line the console held steady at around 22mb of used memory.

I also tested with `Resize` and `Scale` and it appears that neither of those methods cause the same memory leak.

```csharp
var width = 16;
var height = 16;
var bytes = new byte[width * height];
for(var i = 0; i < bytes.Length; i++)
{
    bytes[i] = (byte)i;
}

var readSettings = new PixelReadSettings(width, height, StorageType.Char, "R");
for(var i = 0; i < 99999; i++)
{
    using (var image = new MagickImage(bytes, readSettings))
    {
        image.Format = MagickFormat.Jpg;
        //if this line is commented out, then there is no memory leak
        image.Thumbnail(new Percentage(50), new Percentage(50));
        if (i % 100 == 0)
            Console.WriteLine($"Working on {i}");
    }
}
```

**Comment by dlemstra** [comment]
Thanks for reporting this. I just pushed a patch to fix this inside ImageMagick and I will try to publish a new release this weekend.
