### ISSUE TITLE
Convert Image to GIF using a custom color map and dithering

### ISSUE THREAD

**Issue by julianaii2007** [dlemstra/Magick.NET#115]
I would like to change the existing color table of the GIF image to the Web-safe colors in Magick.NET.
Something like the following command taken from ImageMagick documentation:
_convert logo.png  -dither FloydSteinberg -remap colortable.gif  remap_logo_fs.gif_
However, I don't know if there is a way to set the color map without using an GIF image file.

I'm using the following code (C#), where myPalette is the color Map for the web-safe colors:
            using (MagickImage image = new MagickImage(filename))
            {
                image.Format = MagickFormat.Gif;
                image.ColorType = ColorType.Palette;
                image.ColorSpace = ColorSpace.RGB;
                image.Depth = 8;
                QuantizeSettings settings = new QuantizeSettings
                {
                    DitherMethod = DitherMethod.FloydSteinberg,
                };

                for (int i = 0; i < myPalette.Entries.Length; i++)
                {
                    image.SetColormap(i, new MagickColor(myPalette.Entries[i].R, myPalette.Entries[i].G, myPalette.Entries[i].B));
                }
                image.Write(@"C:\logo.png");
            }

Thanks in advance,

**Comment by dlemstra** [comment]
What you could do is create 1x1 images for your colors and combine (`append`) that with a `MagickImageCollection` into one image and use that for the `Map` method.

**Comment by julianaii2007** [comment]
Thanks for your reply,
I did what you told me, but it didn't work, so I think I'm not doing something correctly. The image I'm getting is completely black. :(
See my code below:

            using (MagickImage image = new MagickImage(@"C:\dogs-87a.JPG"))
            {
                image.Format = MagickFormat.Gif;
                image.ColorType = ColorType.Palette;
                image.ColorSpace = ColorSpace.RGB;
                image.Depth = 8;
                QuantizeSettings settings = new QuantizeSettings
                {
                    DitherMethod = DitherMethod.FloydSteinberg,
                };

                using (MagickImageCollection colors = new MagickImageCollection())
                {
                    for (int i = 0; i < myPalette.Entries.Length; i++)
                    {
                        colors.Add(new MagickImage(new MagickColor(myPalette.Entries[i].R, myPalette.Entries[i].G, myPalette.Entries[i].B), 1, 1));
                    }

                    using (MagickImage colorMap = (MagickImage)colors.AppendHorizontally())
                    {
                        image.Map(colorMap, settings);
                    }
                }
                image.Write(@"C:\logo.png");
            }

Thanks again for your fast response.

**Comment by dlemstra** [comment]
Could you also share your input image? I wonder if it is related to your input image.

**Comment by julianaii2007** [comment]
This is the image.
![labrador-retriever-wallpaper-720x340](https://user-images.githubusercontent.com/32944606/31907346-6bd96a4e-b7e8-11e7-91b5-3d93fe9aaca4.jpg)

**Comment by dlemstra** [comment]
And what are the entries of your palette?

**Comment by julianaii2007** [comment]
this is the palette I'm using: [R, G , B]
255 , 255 , 255
255 , 255 , 204
255 , 255 , 153
255 , 255 , 102
255 , 255 , 51
255 , 255 , 0
255 , 204 , 255
255 , 204 , 204
255 , 204 , 153
255 , 204 , 102
255 , 204 , 51
255 , 204 , 0
255 , 153 , 255
255 , 153 , 204
255 , 153 , 153
255 , 153 , 102
255 , 153 , 51
255 , 153 , 0
255 , 102 , 255
255 , 102 , 204
255 , 102 , 153
255 , 102 , 102
255 , 102 , 51
255 , 102 , 0
255 , 51 , 255
255 , 51 , 204
255 , 51 , 153
255 , 51 , 102
255 , 51 , 51
255 , 51 , 0
255 , 0 , 255
255 , 0 , 204
255 , 0 , 153
255 , 0 , 102
255 , 0 , 51
255 , 0 , 0
204 , 255 , 255
204 , 255 , 204
204 , 255 , 153
204 , 255 , 102
204 , 255 , 51
204 , 255 , 0
204 , 204 , 255
204 , 204 , 204
204 , 204 , 153
204 , 204 , 102
204 , 204 , 51
204 , 204 , 0
204 , 153 , 255
204 , 153 , 204
204 , 153 , 153
204 , 153 , 102
204 , 153 , 51
204 , 153 , 0
204 , 102 , 255
204 , 102 , 204
204 , 102 , 153
204 , 102 , 102
204 , 102 , 51
204 , 102 , 0
204 , 51 , 255
204 , 51 , 204
204 , 51 , 153
204 , 51 , 102
204 , 51 , 51
204 , 51 , 0
204 , 0 , 255
204 , 0 , 204
204 , 0 , 153
204 , 0 , 102
204 , 0 , 51
204 , 0 , 0
153 , 255 , 255
153 , 255 , 204
153 , 255 , 153
153 , 255 , 102
153 , 255 , 51
153 , 255 , 0
153 , 204 , 255
153 , 204 , 204
153 , 204 , 153
153 , 204 , 102
153 , 204 , 51
153 , 204 , 0
153 , 153 , 255
153 , 153 , 204
153 , 153 , 153
153 , 153 , 102
153 , 153 , 51
153 , 153 , 0
153 , 102 , 255
153 , 102 , 204
153 , 102 , 153
153 , 102 , 102
153 , 102 , 51
153 , 102 , 0
153 , 51 , 255
153 , 51 , 204
153 , 51 , 153
153 , 51 , 102
153 , 51 , 51
153 , 51 , 0
153 , 0 , 255
153 , 0 , 204
153 , 0 , 153
153 , 0 , 102
153 , 0 , 51
153 , 0 , 0
102 , 255 , 255
102 , 255 , 204
102 , 255 , 153
102 , 255 , 102
102 , 255 , 51
102 , 255 , 0
102 , 204 , 255
102 , 204 , 204
102 , 204 , 153
102 , 204 , 102
102 , 204 , 51
102 , 204 , 0
102 , 153 , 255
102 , 153 , 204
102 , 153 , 153
102 , 153 , 102
102 , 153 , 51
102 , 153 , 0
102 , 102 , 255
102 , 102 , 204
102 , 102 , 153
102 , 102 , 102
102 , 102 , 51
102 , 102 , 0
102 , 51 , 255
102 , 51 , 204
102 , 51 , 153
102 , 51 , 102
102 , 51 , 51
102 , 51 , 0
102 , 0 , 255
102 , 0 , 204
102 , 0 , 153
102 , 0 , 102
102 , 0 , 51
102 , 0 , 0
51 , 255 , 255
51 , 255 , 204
51 , 255 , 153
51 , 255 , 102
51 , 255 , 51
51 , 255 , 0
51 , 204 , 255
51 , 204 , 204
51 , 204 , 153
51 , 204 , 102
51 , 204 , 51
51 , 204 , 0
51 , 153 , 255
51 , 153 , 204
51 , 153 , 153
51 , 153 , 102
51 , 153 , 51
51 , 153 , 0
51 , 102 , 255
51 , 102 , 204
51 , 102 , 153
51 , 102 , 102
51 , 102 , 51
51 , 102 , 0
51 , 51 , 255
51 , 51 , 204
51 , 51 , 153
51 , 51 , 102
51 , 51 , 51
51 , 51 , 0
51 , 0 , 255
51 , 0 , 204
51 , 0 , 153
51 , 0 , 102
51 , 0 , 51
51 , 0 , 0
0 , 255 , 255
0 , 255 , 204
0 , 255 , 153
0 , 255 , 102
0 , 255 , 51
0 , 255 , 0
0 , 204 , 255
0 , 204 , 204
0 , 204 , 153
0 , 204 , 102
0 , 204 , 51
0 , 204 , 0
0 , 153 , 255
0 , 153 , 204
0 , 153 , 153
0 , 153 , 102
0 , 153 , 51
0 , 153 , 0
0 , 102 , 255
0 , 102 , 204
0 , 102 , 153
0 , 102 , 102
0 , 102 , 51
0 , 102 , 0
0 , 51 , 255
0 , 51 , 204
0 , 51 , 153
0 , 51 , 102
0 , 51 , 51
0 , 51 , 0
0 , 0 , 255
0 , 0 , 204
0 , 0 , 153
0 , 0 , 102
0 , 0 , 51
0 , 0 , 0
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255
255 , 255 , 255

**Comment by julianaii2007** [comment]
Are the entries of my palette correct?

**Comment by dlemstra** [comment]
I suspect that you are using the Q16 version of Magick.NET and then you will need to create the color differently. The constructor expects values in the range of 0-65535 with the Q16 build. If you want to use a value in the range of 0-255 you should create the color with `MagickColor.FromRgb(r,g,b)`

**Comment by julianaii2007** [comment]
Yes, you were right, I'm using the Q16 version of Magick.NET, so I did what you said, and I also changed the classtype to Pseudo in order to get the whole color map entries and I removed the last 40 entries because I realized the correct palette should have 216 entries.
Now, the image is using the correct palette, however the order of the colors are not properly set
How can I keep the same index order as it was created?
Thank you so much!

        private MagickColor[] getMagickColorPalette()
        {
            int i=0;
            MagickColor[] myEntries = new MagickColor[216];

            //write a custom palette
            for (int x = 0; x < 256; x += 51)
            {
                for (int y = 0; y < 256; y += 51)
                {
                    for (int z = 0; z < 256; z += 51)
                    {
                        myEntries[i] = MagickColor.FromRgb((byte)(255 - x), (byte)(255 - y), (byte)(255 - z));
                        i++;
                    }
                }
            }
            return myEntries;
        }

//**************************************        
   
            using (MagickImage image = new MagickImage(@"C:\dogs-87a.JPG"))
            {
                MagickColor[] myEntries = new MagickColor[216];
                myEntries = getMagickColorPalette();

                image.Format = MagickFormat.Gif;
                image.ColorType = ColorType.Palette;
                image.Depth = 8;
                image.CompressionMethod = CompressionMethod.NoCompression;
                image.Interlace = Interlace.NoInterlace;
                image.ClassType = ClassType.Pseudo;
                image.Resize(maxWidth, maxHeight);

                QuantizeSettings settings = new QuantizeSettings
                {
                    DitherMethod = DitherMethod.FloydSteinberg,
                };

                using (MagickImageCollection colors = new MagickImageCollection())
                {
                    for (int i = 0; i < myEntries.Length; i++)
                    {
                        //colors.Add(new MagickImage(new MagickColor(bmp.Palette.Entries[i].R, bmp.Palette.Entries[i].G, bmp.Palette.Entries[i].B), 1, 1));
                        colors.Add(new MagickImage(myEntries[i], 1, 1));
                    }

                    using (MagickImage colorMap = (MagickImage)colors.AppendHorizontally())
                    {
                        image.Map(colorMap, settings);
                    }
                }

                image.Write(@"C:\logo2.gif");
               
            }

This is the colormap when I convert the image to GIF with GIMP:
![correct order](https://user-images.githubusercontent.com/32944606/32198535-b6e47af4-bd85-11e7-9ad3-1c87498cf3fd.PNG)

This is the colormap when I convert the image with my code:
![order i got using the code](https://user-images.githubusercontent.com/32944606/32198536-b713c8fe-bd85-11e7-8b05-0cbc10c01dda.PNG)

**Comment by dlemstra** [comment]
There is no option to preserve the "order" because colors are added from the "map-image" to the palette of the image when a color is found in the image. Why is it so important to preserve the order of your colors?
