### ISSUE TITLE
Error writing stream when using icon:auto-resize

### ISSUE THREAD

**Issue by artyomszasa** [dlemstra/Magick.NET#1150]
### Magick.NET version

10.0.0

### Environment (Operating system, version and so on)

linux-x64 (ubuntu 20.04)

### Description

When setting "icon:auto-resize=xxx" option with multuple sizes and using **stream** version (i.e. Write(stream)) of the Write method only partial data is written into the stream.

When using **path** (i.e. Write("/path/to")) version of the Write method on the same object with the exact same options the icon is written properly.

Looking into the written binaries it seems that when stream is used only the first icon entry is written. The "count" byte denotes that multiple images are present, yet the file contains only single entry.

### Steps to Reproduce

Minimal program to reproduce can be found here: https://gist.github.com/artyomszasa/101f32a7dda0a0d32c562855f38951c9
(the "image.png" must be replaced with a valid path).

**Comment by dlemstra** [comment]
Thanks for reporting this and providing me with an example that I can use to reproduce this. I just pushed a commit to the ImageMagick repository to fix this. This will be resolved in the next release of Magick.NET.
