### ISSUE TITLE
The removal of multiple profiles using a single method

### ISSUE THREAD

**Issue by egbakou** [dlemstra/Magick.NET#1155]
### Is your feature request related to a problem? Please describe

If someone wants to remove multiple profiles(exif, icc, xmp for example) from an image, he would probably call the `RemoveProfile ` method 3 times.

### Describe the solution you'd like

We can implement a method which can take multiple profiles or profile names to make it simple.
My solution:
```csharp
image.RemoveProfiles(colorProfile, exifProfile, xmpProfile);
// Or
image.RemoveProfiles("icc", "exif", "xmp");
```

**Comment by dlemstra** [comment]
Thanks for your contribution but I don't want to add this to the API. Someone could just call the method multiple times. If you really want this in your own software you could change this into an extension method.

**Comment by egbakou** [comment]
Ok no problem :)
