### ISSUE TITLE
Method 'InverseSigmoidalContrast' does not have an implementation

### ISSUE THREAD

**Issue by gsemac** [dlemstra/Magick.NET#1157]
### Magick.NET version

8.6.1

### Environment (Operating system, version and so on)

Windows 8.1

### Description

I'm using the `Magick.NET-Q16-AnyCPU` (8.6.1) and `Magick.NET.SystemDrawing` (4.0.18) packages in a project targeting .NET 4.8.

Any attempt to use the library throws the following exception:

```
System.TypeLoadException: 'Method 'InverseSigmoidalContrast' in type 'ImageMagick.MagickImage' from assembly 'Magick.NET-Q16-AnyCPU, Version=8.6.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' does not have an implementation.'
```

If I downgrade `Magick.NET.SystemDrawing` to version 4.0.16, the issue no longer occurs. It is only a problem when referencing versions 4.0.17 and above.

### Steps to Reproduce

Attempting to load an image is enough to reproduce the issue:

```csharp
ImageMagick.MagickImage image = new ImageMagick.MagickImage("image.png");
```

**Comment by dlemstra** [comment]
`Magick.NET.SystemDrawing` requires `Magick.NET.Core (>= 10.1.0)` and that means you will need to upgrade `Magick.NET` to the same version also.

**Comment by gsemac** [comment]
You're right, updating `Magick.NET-Q16-AnyCPU` to the latest version solves the problem for projects targeting .NET 4.8.

That said, does this mean `Magick.NET.SystemDrawing` is no longer compatible with earlier versions of .NET Framework that don't support .NET Standard? The package claims to support .NET 4.0, but that's not possible if the latest versions of Magick.NET are required for it to work, since they only target .NET Standard.

**Comment by dlemstra** [comment]
It is still compatible with older .NET versions. If you want ancient support (.NET 2.0) you will need to use the `x64` or the `x86` version of Magick.NET instead.
