### ISSUE TITLE
Memory leak when using MagickImage constructor with Stream argument for large WebP image.

### ISSUE THREAD

**Issue by REC-James** [dlemstra/Magick.NET#1163]
### Magick.NET version

10.1.0

### Environment (Operating system, version and so on)

Windows 11

### Description

Hi.  I think I've found a memory leak specifically in the MagickImage constructor that takes a Stream argument.  

When loading a 6MB animated WebP image using the MagickImage class, I've noticed that the large memory usage used during the loading does not clear itself after the Using block.  This only happens when using the constructor that takes a Stream argument, the other constructors seem to work fine.  (I understand that Magick.NET loads in the image as uncompressed pixel data, so the initial memory usage is high, but it clears after the object is disposed normally.)  Shown below I have two sets of code to demonstrate the problem.

I can provide a large animated WebP file if you need, but I will have to edit it to take out our customer's specific information first.

### Steps to Reproduce

This code shows that the memory after loading the image is released correctly when using the file path constructor.  If you look at the memory usage in the Task Manager once it is at the ReadLine() line, it will be low.
```
using System;
using ImageMagick;

namespace WebPMemLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            const string IMAGE_PATH = "test.webp";

            using (MagickImage image = new MagickImage(IMAGE_PATH))
            {
                Console.WriteLine("Image loaded");
            }
            Console.WriteLine("Note the memory usage in the Task Manager, it is low.");
            Console.ReadLine();
        }
    }
}
```

This code shows that the memory after loading the image is still high when using the Stream constructor.  If you look at the memory usage in the Task Manager once it is at the ReadLine() line, it will be high.  Note that the file stream is closed properly with a Using block.
```
using System;
using ImageMagick;

namespace WebPMemLeak
{
    class Program
    {
        static void Main(string[] args)
        {
            const string IMAGE_PATH = "test.webp";

            using (System.IO.FileStream fs = new System.IO.FileStream(IMAGE_PATH, System.IO.FileMode.Open, System.IO.FileAccess.Read))
            {
                using (MagickImage image = new MagickImage(fs))
                {
                    Console.WriteLine("Image loaded");
                }
            }
            Console.WriteLine("Note the memory usage in the Task Manager, it is high.");
            Console.ReadLine();
        }
    }
}
```

**Comment by dlemstra** [comment]
This is a symptom of a non-deterministic GC. The GC does not make any guarantees at all about when memory will be freed. This is normal, expected and wanted behavior. When you put this inside a for loop and run it multiple times you will probably see a different behavior.

**Comment by REC-James** [comment]
I don't think that's it.  I put the code in for loop and threw in a GC.Collect within the loop for good measure and the memory usage just kept going up.  I attached a memory profiler and it was saying that most of the used memory was native memory, not managed.

**Comment by dlemstra** [comment]
Can you share your image? It might be related to that image.

**Comment by REC-James** [comment]
Sure, I've made a copy of the image with personally identifiable information removed and checked that this image still exhibits the same behaviour.  I had to upload it with a .gif extension as GitHub wouldn't allow the WebP extension, but it is a WebP animation.  (Rename to .webp if required.)
![test](https://user-images.githubusercontent.com/101612672/158715842-cb2f4356-d8e4-4750-b791-c82f46d7ff6f.gif)
.

**Comment by dlemstra** [comment]
Found and fixed the issue. This will be resolved in the next release of Magick.NET.
