### ISSUE TITLE
Problem reading TIFF files with custom tags

### ISSUE THREAD

**Issue by magneka** [dlemstra/Magick.NET#1164]
### Magick.NET version

Magick.NET-Q16-HDRI-AnyCPU 10.1.0

### Environment (Operating system, version and so on)

Windows, AWS Lambda (linux)

### Description

**My problem**
I am trying to use Magic.Net.Core insida an AWS Lambda function to convert images, 
but a large number of the images fails due to a problem with custom tags.

**using MAGIC.NET**
When loading the image, i get some sanity check error, or Can not read TIFF directory count.
This happens on 50% of the files i have tried.

**Checking with TIFFINFO**
Using the linux tool tiffinfo, it also reports the same error.

**IMAGE APPLICATIONS**
However image applications (gimp, ms paint etc.) seems to read the files fine.

**USING "convert" application**
However, using convert like this:

C:>convert FileWithcustomTag.TIFF FileWithcustomTag.jpg

gives output:
convert: Unknown field with tag 34152 (0x8568) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/956.
convert: Sanity check on directory count failed, this is probably not a valid IFD offset. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/596.
convert: Failed to read custom directory at offset 63112580. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/596.
convert: Unknown field with tag 34152 (0x8568) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/956.
convert: improper image header `FileWithcustomTag.TIFF' @ error/psd.c/ReadPSDLayersInternal/2020.

But: it produces a file which is OK.

### Steps to Reproduce

To reproduce the error,
I have created a VS Studio solution [git repository](https://github.com/magneka/MagickNetProblem), images are included.

**Comment by dlemstra** [comment]
It looks like ImageMagick 6 (`convert`) creates an output image but Magick.NET that uses ImageMagick 7 is more strict about this. Your files are corrupt and that is why they cannot be read.
