### ISSUE TITLE
Trouble creating thumbs for video files

### ISSUE THREAD

**Issue by ChuckSavage** [dlemstra/Magick.NET#1166]
### Magick.NET version

Core 10.1, SystemDrawing 4.0.18, Net-Q16-AnyCPU 10.1

### Environment (Operating system, version and so on)

Windows 10 Pro

### Description

I'm getting are the following exceptions for creating a thumbnail for video files. I've verified that the video files exist, but it is the temp file(s) that doesn't for each instance. I presume that this library is creating it, or should be creating it. Here are a few of the exceptions.

FailedToExecuteCommand `"ffmpeg.exe" -nostdin -loglevel error -i "D:\JDisk\My Pictures\Nature\Hawaii Volcano Eruption Update - Thursday Morning (June 21, 2018).mp4" -an -f rawvideo -y -vframes 1 -vcodec webp "C:/Users/chuck/AppData/Local/Temp/magick-V45-I_OiH3AsTi4aI7Ks2UdY_f1aZdGZ"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/516

FailedToExecuteCommand `"ffmpeg.exe" -nostdin -loglevel error -i "D:\JDisk\My Pictures\Nature\12220689_850498591738119_1627000975_n.mp4" -an -f rawvideo -y -vframes 1 -vcodec webp "C:/Users/chuck/AppData/Local/Temp/magick-uXyznQ7ZgTZ8L7IYhlivVod47-ihkQef"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/516

FailedToExecuteCommand `"ffmpeg.exe" -nostdin -loglevel error -i "D:\JDisk\My Pictures\Nature\Spain b 001.mp4" -an -f rawvideo -y -vframes 1 -vcodec webp "C:/Users/chuck/AppData/Local/Temp/magick-m4ql_XoVdz_XsMZGWj2yWLNuj2_NOYZ3"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/516

### Steps to Reproduce

If you need copies of videos that aren't working, I can share them. Below is the code I'm using.

```
try
{
    using MagickImage image = new MagickImage(imageFile.FullName); 
    image.Thumbnail(ThumbSizeDTO.Size.Width, ThumbSizeDTO.Size.Height);
    image.Write(thumb.FullName);
}
catch (MagickDelegateErrorException ex)
{
    // 'FailedToExecuteCommand `"ffmpeg.exe" -nostdin -loglevel error -i
    // "D:\JDisk\My Pictures\camera\2013-07-14 Jamaryn\Jamaryn 001.AVI" -vcodec pam -an -f rawvideo -y -vframes 1 "C:/Users/chuck/AppData/Local/Temp/magick-MXRojhQ8gUC0ryxOQ17KNTf3FGQMPucq"'
    // (The system cannot find the file specified.) @ error / delegate.c / ExternalDelegateCommand / 516'
    _ = ex;
}
catch { }
```

**Comment by dlemstra** [comment]
Did you install `ffmpeg`? This is required to be able to read video files.

**Comment by ChuckSavage** [comment]
Okay, thanks. I'm having additional issues, but I'll open something in discussions.
