### ISSUE TITLE
Can open some gif error/gif.c/ReadGIFImage/1388

### ISSUE THREAD

**Issue by lindexi** [dlemstra/Magick.NET#117]
I try to use this to show gif in wpf.  All the time it can work perfect but it cant open some gif.

I found some gif open in this code will throw the exception.

`collection = new MagickImageCollection("E:\\temp\\201710.gif");`

The exception is `corrupt image 'E:\temp\201710.gif' @ error/gif.c/ReadGIFImage/1388`

Click [here](http://7xqpl8.com1.z0.glb.clouddn.com/34fdad35-5dfe-a75b-2b4b-8c5e313038e2%2F201710.gif) to download the gif file.

**Comment by dlemstra** [comment]
You are getting that exception because your image is corrupt/incorrect. The ImageMagick library is very picky when it comes to corrupt files and an exception will be thrown when the file is corrupt.

**Comment by lindexi** [comment]
@dlemstra Chrome and windows picture can open it. Some gif I use ScreenToGif  make may cant open in MagickImageCollection

**Comment by dlemstra** [comment]
Those programs can open it because they ignore the fact that the image is invalid. ImageMagick requires the image to be correct.

**Comment by lindexi** [comment]
@dlemstra I should find some way to fix the invalid images, and do you have any suggestion?

**Comment by dlemstra** [comment]
You can't really fix them but it might be possible to read them with Bitmap and then save it again as a valid gif file.

**Comment by lindexi** [comment]
But as you can see, it's an animation image. If I read it as Bitmap and save it again , I will make the animation image as a static image.

**Comment by dlemstra** [comment]
@lindexi I am sorry but I don't have an idea on how you can solve this.
