### ISSUE TITLE
Transparent PNG Converting Badly to JPEG

### ISSUE THREAD

**Issue by danpetitt** [dlemstra/Magick.NET#1172]
### Magick.NET version

11.0.0

### Environment (Operating system, version and so on)

Windows 10 Pro

### Description

Loading a PNG with transparency and saving as JPG 100% produces a JPG with a lot of artifacts in the old transparent portion.

Compared with paint.net which does not show the artifacts and has a clean solid colour.

Test PNG:
![TestTransparent](https://user-images.githubusercontent.com/1733292/162026326-29d5ea8c-95c7-46e4-9605-5d19a25e8c81.png)

Produces JPG:
![TestTransparent](https://user-images.githubusercontent.com/1733292/162026420-1ae1ef6e-1c5a-43c6-bb32-381e78efdd8e.jpg)

Paint.net Conversion:
![TestTransparent-paintnet](https://user-images.githubusercontent.com/1733292/162026592-c5dd55a8-d41a-4c18-856d-f8d129bf3cfc.jpg)

### Steps to Reproduce

```c#
var readSettings = new MagickReadSettings()
{
    Format = MagickFormat.Png
};

using( var image = new MagickImage( "TestTransparent.png", readSettings ) )
{
    image.Quality = 100;
    image.Write( "TestTransparent.jpg", MagickFormat.Jpeg );
}
```

Example .net framework 4.8 project:
[ImageMagickTest.zip](https://github.com/dlemstra/Magick.NET/files/8428902/ImageMagickTest.zip)

**Comment by dlemstra** [comment]
I suspect that paint.net is doing something different. When ImageMagick writes the jpeg image it disables the transparent pixels and shows what is under it. That is the same as when you would do `image.Alpha(AlphaOption.Off)`. I think that paint.net does something like this: `image.ColorAlpha(MagickColors.White)` instead.

**Comment by danpetitt** [comment]
That makes total sense; adding that Color setting has done it; thanks Dirk
