### ISSUE TITLE
Supports for Net Framework 4.x

### ISSUE THREAD

**Issue by fabiomaulo** [dlemstra/Magick.NET#1173]
We are using Magick.NET in some projects which target are : `netstandard2.0`, `netcoreapp3.1`

We are moving some others prj from `net472` to `netcoreapp3.1`.
In these prjs the **last working** Magik version is : 7.24.1 (the last with `net40` target)

In our NetFW project, we tried to force VS to use the `netstandard2.0` Magik DLL (v11.0.0) but it fail training to load the dynamically generated dll (at runtime it can't read/understand the assembly manifest).

Can you please re-add the `net40` target to the last version? (v11.x)
Thanks in advance.

Related issue #802

**Comment by dlemstra** [comment]
Official support for net40 has stopped in 2016. I am not planning to restore support for that in this library. And I don't understand your issue, `net472` should work with `netstandard2.0`.

**Comment by fabiomaulo** [comment]
I know the matter of `net40`, I have mentioned it because it was the one used for v7.24.1 and, perhaps, it is easier to support for you.
Magick.NET.Core currently (even the last v11.1.0) has support for `net20` and you know it died a lot of years ago.
A FullFramework project (4.7.2) allows the reference to a Magick 11.0.0 but when you run the project it fails because it can't read the assembly manifest.

btw I'm investigating which is the problem because installing the 11.0.1 in a simple FW-Console where I tried the 7.24, now it works again (the v11.1.0 work well).

**Comment by fabiomaulo** [comment]
This is the result for v11.0.0 in a FW4.7.2 console

Having this in the csprj
```
<Reference Include="Magick.NET-Q8-AnyCPU, Version=11.0.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec, processorArchitecture=MSIL">
  <HintPath>..\packages\Magick.NET-Q8-AnyCPU.11.0.0\lib\netstandard20\Magick.NET-Q8-AnyCPU.dll</HintPath>
</Reference>
<Reference Include="Magick.NET.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec, processorArchitecture=MSIL">
  <HintPath>..\packages\Magick.NET.Core.11.0.0\lib\net20\Magick.NET.Core.dll</HintPath>
</Reference>
```

the exception processing an image is:
```
System.IO.FileLoadException: 'Could not load file or assembly 'Magick.NET.Core, Version=11.1.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Inner Exception:
FileLoadException: Could not load file or assembly 'Magick.NET.Core, Version=11.0.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Removing both v11.0.0 packages and installing the las v11.1.0 the csprj is:
```
    <Reference Include="Magick.NET-Q8-AnyCPU, Version=11.1.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec, processorArchitecture=MSIL">
      <HintPath>..\packages\Magick.NET-Q8-AnyCPU.11.1.0\lib\netstandard20\Magick.NET-Q8-AnyCPU.dll</HintPath>
    </Reference>
    <Reference Include="Magick.NET.Core, Version=11.1.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec, processorArchitecture=MSIL">
      <HintPath>..\packages\Magick.NET.Core.11.1.0\lib\net20\Magick.NET.Core.dll</HintPath>
    </Reference>
```
and everything works correctly.
Apparently, something has changed in `Magick.NET.Core` between 11.0.0 and 11.1.0

### Resuming
With 11.1.0 there is no problem working with NET FW 4.7.2

If you need I can investigate more, if no, we can close this issue and I'll be happy using the las very very fresh version 😉

**Comment by dlemstra** [comment]
If your error message it says `'Could not load file or assembly 'Magick.NET.Core, Version=11.1.0.0,` when you are using the `11.0.0` version. It looks like you are mixing different versions in your application. I am also a bit surprised that your application is using `lib\net20\Magick.NET.Core.dll` when it should be using `netstandard20`. And to get back to your `net20` remark, I am aware it is deprecated even longer and I am planning to remove support for it later this year.

**Comment by fabiomaulo** [comment]
I found the real source of the problem.
There was another very old package whose intent to load everything in the `bin` folder without any kind of check about what is each `.dll`.
Removed that package, the v11.1.0 works as expected even in a WEB NetFW prj.
Thanks.
