### ISSUE TITLE
MagickImage cannot detect correct image format with `ReadAsync`

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#1174]
### Magick.NET version

11.1.0 - Magick.NET-Q16-OpenMP-x64

### Environment (Operating system, version and so on)

Windows 10 21H2

### Description

- Probably similar to #422 but happens to both
`<MagickImage>.ReadAsync()` and `<MagickImageCollection>.ReadAsync()` function.
- I'm using `ReadAsync` because it supports `CancellationToken`, and it's convenient to do some quick check before loading entire image file which is time-consuming.
- Error:
  ```
  TIFF directory is missing required "ImageLength" field. `MissingRequired' @ error/tiff.c/TIFFErrors/656
  ```
- Sample file: [icon256.zip](https://github.com/dlemstra/Magick.NET/files/8457034/icon256.zip)
- See Step to Reproduce for more details.

### Code produces error:

```cs
var filename = @"D:\icon256.ico";

// Some settings
var settings = new MagickReadSettings();

using var imgM = new MagickImage();
// Check something here
// ...
// ...

// read image file async
await imgM.ReadAsync(filename, settings, cancelToken);

// ❌ Error:
// TIFF directory is missing required "ImageLength" field.
// `MissingRequired' @ error/tiff.c/TIFFErrors/656

```

#### Solution 1: Directly pass filename to constructor
```cs
using var imgM = new MagickImage(filename, settings);

// no error!
```

#### Solution 2: Tell what the format is
```cs

// Some settings
var settings = new MagickReadSettings() {
    Format = MagickFormat.Ico,
};

using var imgM = new MagickImage();
// Check something here
// ...
// ...

// read image file async
await imgM.ReadAsync(filename, settings, cancelToken);

// no error!
```

You can access full source code at:
https://github.com/d2phap/ImageGlass/blob/v9/v9/IgCodecs/ImageMagickIgCodec/Main.cs#L493

**Comment by dlemstra** [comment]
Thanks for reporting this I just pushed a fix for this issue that will be resolved in the next release.

**Comment by d2phap** [comment]
I hope this fix can be released some time this week, or else I will miss it for ImageGlass 9.0 beta 1 🕊

**Comment by d2phap** [comment]
Hi @dlemstra,

The bug still persists when using `MagickImageCollection.ReadAsync()` 😅
Sample file: [icon256.zip](https://github.com/dlemstra/Magick.NET/files/8457034/icon256.zip)
```cs
using var imgColl = new MagickImageCollection();

// ❌ CANNOT detect format
settings.Format = MagickFormat.Ico;
await imgColl.ReadAsync(filename, settings, cancelToken);

// ✅ CAN detect format
await imgColl.ReadAsync(filename, settings, cancelToken);

// ✅ CAN detect format
imgColl.Read(filename, settings);
```

I checked the MagickImageCollection source code a bit, and found this:
`filename` is not passed to the `AddImages()`
https://github.com/dlemstra/Magick.NET/blob/8a4f9de5f6809a1a7435dec94f61bbfc7371a1e0/src/Magick.NET/Netstandard21/MagickImageCollection.cs#L292-L301

`settings.FileName = null;`
https://github.com/dlemstra/Magick.NET/blob/8a4f9de5f6809a1a7435dec94f61bbfc7371a1e0/src/Magick.NET/Netstandard21/MagickImageCollection.cs#L582-L601

**Comment by dlemstra** [comment]
Seems that I only fixed this in the `MagickImage` class and not in the `MagickImageCollection`. Just pushed a patch for this and I will publish a new release this weekend for you.
