### ISSUE TITLE
Cannot read custom font

### ISSUE THREAD

**Issue by TomLing** [dlemstra/Magick.NET#118]
Hi 

I have a custom font in my Windows Font folder but when I try instantiate a new DrawableFont like so -
`drawables.Add(new DrawableFont("CustomFontName", FontStyleType.Any, FontWeight.Weight500, FontStretch.Normal));`

I get the following exception when calling `image.Draw(drawables)` - `GraphicsMagick.MagickTypeErrorException: 'ProjectName: Unable to read font (n019003l.pfb) reported by ..\..\magick\annotate.c:1063 (RenderFreetype)'`

Is there something I am missing?

Thanks

**Comment by dlemstra** [comment]
Are you posting this message in the wrong repository? This project does not contain the `GraphicsMagick` namespace.

**Comment by TomLing** [comment]
I am implementing the GraphicsMagick.NET-Q16-x64 nuget version 1.3.23.1.

I have changed the actual project name to 'ProjectName' in the exception.

**Comment by dlemstra** [comment]
Could you open an issue here instead: https://github.com/dlemstra/GraphicsMagick.NET/issues?
