### ISSUE TITLE
no encode delegate for this image format `XC' @ error/constitute.c/WriteImage/1252

### ISSUE THREAD

**Issue by tavershimafx** [dlemstra/Magick.NET#1180]
### Magick.NET version

7.22.2.2

### Environment (Operating system, version and so on)

Win 10 x64

### Description

I just attempt performing a combination of two images and when I try to read out the stream, I keep getting the error
`no encode delegate for this image format 'XC' @ error/constitute.c/WriteImage/1252`
The image is a `.jpg` image

### Steps to Reproduce

``` c#
                        using (MagickImageCollection images = new())
                        {
                            images.Add(new MagickImage(MagickColor.FromRgb(0, 0, 0), 400, 400));
                            images.Add(image); // image is a .jpg file loaded into another MagickImage object

                            using (IMagickImage result = images.Mosaic())
                            {
                                // Save the result
                                result.Resize(400, 400);
                                var s = new MemoryStream();
                                result.Write(s); // the error throws on this line
                                await SaveFile(s, Path.GetFileName(item), path); // my save method
                            }
                        }
```

**Comment by tavershimafx** [comment]
added some comments to the coded

**Comment by dlemstra** [comment]
The format of the `result` image is `xc` because that was the format of the first image. You will need to specify the new format in `result.Write` for example: `result.Write(s, MagickFormat.Jpg);`

**Comment by tavershimafx** [comment]
solution fixed the problem
