### ISSUE TITLE
It doesn't create the Magick.NET-Q16-x64.Native.dll

### ISSUE THREAD

**Issue by robisoft** [dlemstra/Magick.NET#119]
I use the library inside a website. At the beginning, I call the MagickNET.SetTempDirectory and I set the write permissions to IIS_Users to the temp directory.
I see that the library doesn't create anything inside the temp directory, so the error "not found Magick.NET-Q16-x64.Native.dll" occurs.
What I wrong?

**Comment by dlemstra** [comment]
Are you using the AnyCPU version of Magick.NET? And do you want to specify an alternative location for the temp directory where the native library is stored? If you are trying to do this you should use the property `MagickAnyCPU.CacheDirectory`

**Comment by robisoft** [comment]
Thank you very much Dirk, the MagickAnyCPU.CacheDirectory solves my problem. Now it works fine.
