### ISSUE TITLE
Auto-orient stopped working with 11.2 compared to 11.1.2

### ISSUE THREAD

**Issue by kirk-marple** [dlemstra/Magick.NET#1199]
### Magick.NET version

11.2.0

### Environment (Operating system, version and so on)

Windows 11, .NET 6.0, C#

### Description

Noticed recently that we upgraded to 11.2 and some images started being loaded upside down.  Seems like 'top-right' orientation iPhone files (both JPEG and HEIC).

		<PackageReference Include="Magick.NET-Q8-AnyCPU" Version="11.2.0" />

Just back-dated to 11.1.2, and the problem went away.

### Steps to Reproduce

Simply using this call to load images from (Azure blob) stream.

```
                var image = new MagickImage(stream);

                image.AutoOrient();
```

Attached two example files which come in fine with 11.1.2, but upside down with 11.2.

![IMG_1719](https://user-images.githubusercontent.com/13594550/173954595-7c1b3bd6-ffa3-4067-84b0-b540092bfd44.jpg)
![IMG_1289](https://user-images.githubusercontent.com/13594550/173954597-72fe789c-d0e0-488a-bcc6-d07f961b30a0.jpg)

**Comment by dlemstra** [comment]
This was indeed a bug that was introduced in the recent version because we misunderstood the information in this document: http://sylvana.net/jpegcrop/exif_orientation.html. This will be resolved in the next release.
