### ISSUE TITLE
Wrong behavior with CompositeOperator.Plus when calling Composite()

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#12]
I'm trying to mix a JPG image with a monochromatic image generated with MagickImage:
```
using (MagickImage image = new MagickImage(String.Format("{0}\\FujiFilmFinePixS1Pro.jpg", AppDomain.CurrentDomain.BaseDirectory)))
{
	using (MagickImage image2 = new MagickImage(new MagickColor(236, 236, 236, 255), image.Width, image.Height))
	{
		image.Composite(image2, CompositeOperator.Plus);
	}

	image.Write(String.Format("{0}\\result.png", AppDomain.CurrentDomain.BaseDirectory));
}
```
And it's not working, the result is the exact same JPG image.
It seems to work when 

- I load 2 PNG images (You can find them in the documentation (http://www.imagemagick.org/Usage/compose/#plus)

- I load a JPG image and a PNG one

**Comment by dlemstra** [comment]
This is probably happening because you are using a Q16 version of ImageMagick. The color you are specifying is an almost black color. An when you add it to the other color nothing really happens. You can see that it works when you use the following color instead:

```C#
using (var image2 = new MagickImage(MagickColors.Fuchsia, image.Width, image.Height))
```

**Comment by DavidRouyer** [comment]
The color (236, 236, 236) is almost white no? (0, 0, 0) is black because you don't have any color

**Comment by dlemstra** [comment]
The color (236, 236, 236) is only almost white when you use the Q8 (0-255) version of ImageMagick and when you use the Q16 (0-65535) version the value is almost black.

**Comment by DavidRouyer** [comment]
Thanks for the tip! I'll try tomorrow!

**Comment by DavidRouyer** [comment]
But when I think about it, if I am on a range of (0-65535), the result should be very dark, and I saw the exact same image. I'll try again tomorrow.

**Comment by dlemstra** [comment]
Its not the exact same image. You are 'adding' 236 to each channel and that is hardly noticeable.
