### ISSUE TITLE
Regression in MagickImage.Resize: negative arguments are not correctly handled

### ISSUE THREAD

**Issue by hrumhurum** [dlemstra/Magick.NET#1203]
### Magick.NET version

11.2.0

### Environment (Operating system, version and so on)

Windows 11 x64, .NET 4.7.2

### Description

In older versions of Magick.NET it was possible to resize an image using just one component of its size: either `width` or `height`. But the new version requires both `width` and `height` values to be specified.

An example that no longer works:

``` c#
image.Resize(-1, 37);
```

In older Magick.NET version 7.4.1 it resized the image to make its height 37 while preserving the original aspect ratio of the image. Newer Magick.NET versions do not support that handy semantics anymore, just throwing `ArgumentException` when one of the parameters is negative.

### Steps to Reproduce

``` c#
var image = new MagickImage(MagickColors.Transparent, 1024, 768);
image.Resize(-1, 37);
```

**Comment by dlemstra** [comment]
The `-1` value worked by accident and at some point in time I added checks for this. If you use `0` instead you will get the behavior that you are looking for.
