### ISSUE TITLE
Magick.Native build breaks on Windows if there are spaces in the path

### ISSUE THREAD

**Issue by fozzzgate** [dlemstra/Magick.NET#1205]
### Magick.NET version

11.2.1

### Environment (Operating system, version and so on)

Windows 10.0.19044

### Description

install.cmd fails if there are spaces in the path with the error:

Installing Magick.Native.2022.6.21.613.nupkg
install: invalid arguments.

It fails at the line:

$process = Start-Process -FilePath $nugetPath -ArgumentList "install Magick.Native -Version $version -OutputDirectory $target" -PassThru -NoNewWindow

### Steps to Reproduce

Clone repository to a directory containing spaces and follow instructions at:

https://github.com/dlemstra/Magick.NET/blob/main/Building.md

**Comment by dlemstra** [comment]
Thanks for reporting this. Can you give it another try? I just pushed a patch that should solve this. And can you close this issue if this solves your issue?

**Comment by fozzzgate** [comment]
Wow. That was quick. Unfortunately, I was just about to add an additional comment that the copy routines in install.ps1 also break with spaces. Haven't tried the patch yet, but I'm pretty sure it won't work.

**Comment by dlemstra** [comment]
I gave it a try locally and it looked like the copy actions where working? All the copy actions have quotes around the paths?

**Comment by fozzzgate** [comment]
Yes, you are correct. Since I did not expect a patch so quickly, I manually ran the NuGet command then tried to execute install.ps1 to copy the files to the correct locations and it errored out stating that the file couldn't be found and I assumed that was a space issue also.

Just checked it and it seems to work. Closing the issue.
