### ISSUE TITLE
Is not possible to load Magick.NET on Mono Framework

### ISSUE THREAD

**Issue by freakmaxi** [dlemstra/Magick.NET#121]
Hi,

I'm trying to run the Magick.NET on one of my project. I tried everything to make it work but I didn't find any solution.

I'm taking this error:

`Could not load signature of ImageMagick.MagickImage:ToBitmapSource due to: Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:<unknown type> member:<none>
Could not load signature of ImageMagick.IMagickImage:ToBitmapSource due to: Could not load file or assembly 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. assembly:PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 type:<unknown type> member:<none>`

When I put PresentationCore.dll to the project folder, error is disappearing but Magick.NET still does not work.

I have Magick.NET files in my project folder.
Magick.NET-Q16-HDRI-x64.dll
Magick.NET-Q16-HDRI-x64.Native.dll.so
Magick.NET-Q16-HDRI-x64.xml

and also libraries are there

`linux-vdso.so.1 =>  (0x00007ffe14f0f000)
	libMagickCore-7.Q16HDRI.so.4 => /usr/local/lib/libMagickCore-7.Q16HDRI.so.4 (0x00007f7ffa2c3000)
	libMagickWand-7.Q16HDRI.so.4 => /usr/local/lib/libMagickWand-7.Q16HDRI.so.4 (0x00007f7ff9fb9000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f7ff9d60000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7ff9a57000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7ff968d000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f7ff946b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7ff9255000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7ff9038000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7ffaaa0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7ff8e34000)`

I really don't know what is wrong... Can you help me?

**Comment by dlemstra** [comment]
It looks like you copied the .NET framework version of Magick.NET-Q16-HDRI-x64.dll instead of the .NET standard one. What happens when you use the .NET standard version?

**Comment by xeora** [comment]
Actually, I also tried that. I copied standard version and try. it was throwing error like this

`System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Magick.NET-Q16-x64.Native.dll
  at (wrapper managed-to-native) ImageMagick.Environment+NativeMethods+X64:Environment_Initialize ()
  at ImageMagick.Environment+NativeEnvironment.Initialize () [0x00000] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 
  at ImageMagick.Environment.Initialize () [0x00019] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 
  at ImageMagick.MagickSettings+NativeMagickSettings..cctor () [0x00000] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 
   --- End of inner exception stack trace ---
  at <0x00000 + 0x00000> <unknown method>
  at ImageMagick.MagickSettings..ctor () [0x00011] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 
  at ImageMagick.MagickImage..ctor () [0x00006] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 
  at ImageMagick.MagickImage..ctor (System.IO.Stream stream) [0x00000] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 
  at SolidAssist.Tools.Converter+Image.ResizeTo (System.IO.Stream& InputImage, System.IO.Stream& OutputImage, SolidAssist.Tools.Converter+Image+ImageSize& OutputSize, SolidAssist.Tools.Converter+Image+ResizeModes ResizeMode, SolidAssist.Tools.Converter+Image+ImageFormats OutputFormat, SolidAssist.Tools.Converter+Image+QualityTypes Quality) [0x00053] in <198545fcba9542a1a2911d4d2a52be34>:0 
`

even the mentioned dll is there.

because when i get the error I put this dll and project folder has these files

Magick.NET-Q16-HDRI-x64.dll
Magick.NET-Q16-HDRI-x64.Native.dll
Magick.NET-Q16-HDRI-x64.Native.dll.so
Magick.NET-Q16-HDRI-x64.xml

**Comment by freakmaxi** [comment]
Actually, I also tried that. I copied standard version and try. it was throwing error like this

`System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Magick.NET-Q16-x64.Native.dll at (wrapper managed-to-native) ImageMagick.Environment+NativeMethods+X64:Environment_Initialize () at ImageMagick.Environment+NativeEnvironment.Initialize () [0x00000] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 at ImageMagick.Environment.Initialize () [0x00019] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 at ImageMagick.MagickSettings+NativeMagickSettings..cctor () [0x00000] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 --- End of inner exception stack trace --- at <0x00000 + 0x00000> <unknown method> at ImageMagick.MagickSettings..ctor () [0x00011] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 at ImageMagick.MagickImage..ctor () [0x00006] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 at ImageMagick.MagickImage..ctor (System.IO.Stream stream) [0x00000] in <7e3a89b0e36c4fb68938b7fedc6f1ba8>:0 at SolidAssist.Tools.Converter+Image.ResizeTo (System.IO.Stream& InputImage, System.IO.Stream& OutputImage, SolidAssist.Tools.Converter+Image+ImageSize& OutputSize, SolidAssist.Tools.Converter+Image+ResizeModes ResizeMode, SolidAssist.Tools.Converter+Image+ImageFormats OutputFormat, SolidAssist.Tools.Converter+Image+QualityTypes Quality) [0x00053] in <198545fcba9542a1a2911d4d2a52be34>:0`

even the mentioned dll is there.

because when i get the error I put this dll and project folder has these files

Magick.NET-Q16-HDRI-x64.dll
Magick.NET-Q16-HDRI-x64.Native.dll
Magick.NET-Q16-HDRI-x64.Native.dll.so
Magick.NET-Q16-HDRI-x64.xml

**Comment by freakmaxi** [comment]
Meanwhile, I tried Q16 version cause i thought maybe Q16-HDRI version has any problem. that's why it turned to Q16. :)

**Comment by freakmaxi** [comment]
Today, I'll setup everything from the beginning. I'll let you know if I reached any success or not.

**Comment by dlemstra** [comment]
You will need the netstandard version of the dll together with the Native.dll.so. Let me know if you need more help.

**Comment by freakmaxi** [comment]
hey,

I tried everything. I even change the project to .net standard 1.3. I compile from source, I compile for linux. I think I didn't every possible combinations but still getting this error

`System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Magick.NET-Q16-HDRI-x64.Native.dll
  at (wrapper managed-to-native) ImageMagick.Environment+NativeMethods+X64:Environment_Initialize ()
  at ImageMagick.Environment+NativeEnvironment.Initialize () [0x00000] in <7f27e771335e47caa9dc7771c4a2704e>:0 
  at ImageMagick.Environment.Initialize () [0x00019] in <7f27e771335e47caa9dc7771c4a2704e>:0 
  at ImageMagick.MagickSettings+NativeMagickSettings..cctor () [0x00000] in <7f27e771335e47caa9dc7771c4a2704e>:0 
   --- End of inner exception stack trace ---
  at <0x00000 + 0x00000> <unknown method>
  at ImageMagick.MagickSettings..ctor () [0x00011] in <7f27e771335e47caa9dc7771c4a2704e>:0 
  at ImageMagick.MagickImage..ctor () [0x00006] in <7f27e771335e47caa9dc7771c4a2704e>:0 
  at ImageMagick.MagickImage..ctor (System.IO.Stream stream) [0x00000] in <7f27e771335e47caa9dc7771c4a2704e>:0 
  at SolidCore.Converter.Image.ResizeTo (System.IO.Stream& InputImage, System.IO.Stream& OutputImage, SolidCore.Converter.Image+ImageSize& OutputSize, SolidCore.Converter.Image+ResizeModes ResizeMode, SolidCore.Converter.Image+ImageFormats OutputFormat, SolidCore.Converter.Image+QualityTypes Quality) [0x000ce] in <d7a6ff530d524c9f8991fcb70dc64a8d>:0 
  at Xeora.Domain.HelpersController.ProduceImageStream (System.String MusicTrackID, System.String Size, System.Int32 Recache) [0x001f7] in <43b3396493ff4fc89d00bcda09ed37c8>:0 `

it is super annoying. 

I have these files in my project folder;

Magick.NET-Q16-HDRI-x64.dll
Magick.NET-Q16-HDRI-x64.Native.dll.so
Magick.NET-Q16-HDRI-x64.xml

these files are using Magick.NET as referance
SolidCore.dll
SolidCore.pdb

these files are using SolidCore as referance.
imagemagicktry.dll
imagemagicktry.pdb

in imagemagicktry.dll, a function calling a resize function in SolidCore.dll. SolidCore.dll is doing image resize using Magick.NET.

that's all, it is so simple.
according to error, this Magick.NET-Q16-HDRI-x64.Native.dll file should be there. I'm also putting but no luck.

Any idea?

**Comment by dlemstra** [comment]
Would it be possible to create a docker image that reproduces this issue?

**Comment by freakmaxi** [comment]
Hi,

I put it to github

https://github.com/freakmaxi/ImageMagickTry.git

it is enough to run

./docker_run.sh --build

then visit

http://localhost:8080

**Comment by freakmaxi** [comment]
I didn't try strace but now, I'll try...

**Comment by dlemstra** [comment]
I get an exception when I try to access the page:

```
System.Web.HttpException
Failed to load httpHandler type `Xeora.Web.Handler.RequestHandlerFactory'

Description: HTTP 500.Error processing request.
```

**Comment by freakmaxi** [comment]
do you use my dockerfile and docker_run.sh script to run the environment or you are trying to make a custom environment to run the application? you may take this error if you set up something wrong in framework.

**Comment by dlemstra** [comment]
I just ran `sudo ./docker_run.sh --build` in the root of your repo.

**Comment by freakmaxi** [comment]
okay wait :) I saw that, I forget to push bin folder... I'm pushing now

**Comment by freakmaxi** [comment]
Okay, I added, can you check again please.

**Comment by dlemstra** [comment]
I can reproduce the issue in my temporary machine on azure: `http://40.68.121.127:8080/`

**Comment by freakmaxi** [comment]
ok, so control is on you. If you catch something, I'll be happy to know the reason. I'm checking Magick.NET and Native source codes since yesterday if I can find something but It is hard for me to understand in a day :)

**Comment by dlemstra** [comment]
Well I am a step closer and with `strace` I was able to figure out why it failed. You can view what I have done to make this work in the fork I made of your project. One really important thing is that you will need to attach the `strace -p [PID] -f 2>log.txt` before you request the page. And `[PID]` should be the process id of `/usr/bin/mono`.

It turns out that you should call the native library `libMagick.NET-Q16-HDRI-x64.Native.dll.so` and then it can find it. But that will lead you to a new issue:

```
ImageMagick.MagickMissingDelegateErrorException:
NoDecodeDelegateForThisImageFormat `JPEG' @ error/blob.c/CustomStreamToImage/5084
```

It looks like you linked the ImageMagick library without jpeg support. I am passing this back to you now :)

**Comment by freakmaxi** [comment]
unbelievable! yesterday I also used strace after your message I became squint to read all those strace logs but I didn't reach anywhere :) At least, I have something in my hands now. 

thanks for you help. I'll not close this issue until I have a successful processed image :)

**Comment by freakmaxi** [comment]
Dude! It worked when I recompiled ImageMagick with all modules. 
Thanks for your help. You were so responsive really.

**Comment by dlemstra** [comment]
I never hurts to help. I am happy we could resolve this issue together. Thanks for helping me with this. And this will probably also help other users who want to run Magick.NET with Mono.

**Comment by treasure0010** [comment]
Can I use this with Xamarin forms?
