### ISSUE TITLE
SVG to JPEG, for some svg the embedded image are not rendered during the conversion.

### ISSUE THREAD

**Issue by florentinGo** [dlemstra/Magick.NET#1211]
### Magick.NET version

7.18.0 AND 11.2.1

### Environment (Operating system, version and so on)

Magick.NET-Q8-AnyCPU, VisualStudio 2022, Windows 10

### Description

When converting SVG with embedded image in base64, into JPEG. The image is not rendered only on certain cases.
Image not rendered seems to be image that are bigger than 1Mo.

I tried with ImageMagick-7.1.0-39-Q16-HDRI-x64-dll.exe and had the same issue. Even image magick display can not read properly the input svg.

Should I open an issue on their side instead ?

### Steps to Reproduce

Convert the following images to jpeg using the following code :
![image](https://user-images.githubusercontent.com/15957187/176911735-e8c34010-8395-4391-85d3-9c5918c57b32.png)

Here is an image that won't be properly rendered:
![brokenImage](https://user-images.githubusercontent.com/15957187/176911528-d80387fa-cd7f-4ff8-abbd-69bb3047a00c.svg)
The result after getting the image from the stream, with a background set to white:
![Planning-X-Ray_24062022 jpg_01072022](https://user-images.githubusercontent.com/15957187/176917364-144a1a0f-eacb-456f-8e1d-f0b75ba3ee31.jpeg)

An image that will be properly rendered.
![workingImage](https://user-images.githubusercontent.com/15957187/176911537-71dea238-914f-41a4-ab8e-9534506774ff.svg)
The result after getting the image from the stream:
![workingImageOutput](https://user-images.githubusercontent.com/15957187/176915608-a380603a-c92d-4e44-8128-01357f4e542e.jpeg)

**Comment by dlemstra** [comment]
This seems to be an issue inside an external dependency that we use in ImageMagick. Not sure yet where the exact problem is or how we could solve this.

**Comment by florentinGo** [comment]
I find the difference between these two svg and maybe it can help you.
The ones that do not work has a filter applied to the image:
On the image we have the following attribute : `filter="url(#filterSl4s3jujd1vl)"`
An the filter is specified like this : 
`<filter id="filterSl4s3jujd1vl" filterUnits="userSpaceOnUse" x="0" y="0" width="1764" height="8836">undefined<feComponentTransfer color-interpolation-filters="sRGB">\n                                    <feFuncR type="table" tableValues="0.005 0.009736470588235294 0.014472941176470588 0.01920941176470588 0.023945882352941174 0.02868235294117647 0.033418823529411765 0.03815529411764706 0.042891764705882345 0.04762823529411764 0.05236470588235294 0.05710117647058823 0.061837647058823525 0.06657411764705883 0.07131058823529413 0.07604705882352941 0.0807835294117647 0.08552 0.09025647058823529 0.0949929411764706 0.09972941176470589 0.10446588235294119 0.10920235294117647 0.11393882352941176 0.11867529411764706 0.12341176470588235 0.12814823529411765 0.13288470588235293 0.13762117647058825 0.1423576470588235 0.14709411764705882 0.15183058823529413 0.1565670588235294 0.1613035294117647 0.16604 0.1707764705882353 0.17551294117647057 0.1802494117647059 0.1849858823529412 0.18972235294117648 0.19445882352941177 0.19919529411764708 0.20393176470588237 0.20866823529411765 0.21340470588235294 0.21814117647058825 0.2228776470588235 0.22761411764705883 0.23235058823529411 0.2370870588235294 0.2418235294117647 0.24656 0.2512964705882353 0.25603294117647063 0.26076941176470586 0.26550588235294115 0.2702423529411765 0.2749788235294118 0.279715294117647 0.2844517647058824 0.28918823529411763 0.2939247058823529 0.29866117647058826 0.30339764705882355 0.3081341176470588 0.3128705882352941 0.3176070588235294 0.32234352941176475 0.32708 0.33181647058823527 0.3365529411764706 0.3412894117647059 0.3460258823529411 0.35076235294117647 0.3554988235294118 0.36023529411764704 0.3649717647058824 0.3697082352941176 0.37444470588235296 0.37918117647058824 0.38391764705882353 0.38865411764705876 0.39339058823529416 0.3981270588235294 0.40286352941176473 0.40759999999999996 0.4123364705882353 0.4170729411764706 0.4218094117647059 0.4265458823529411 0.4312823529411765 0.4360188235294118 0.440755294117647 0.44549176470588236 0.45022823529411765 0.45496470588235294 0.4597011764705882 0.4644376470588235 0.4691741176470588 0.47391058823529414 0.47864705882352937 0.48338352941176466 0.48812 0.4928564705882353 0.49759294117647057 0.5023294117647058 0.5070658823529413 0.5118023529411765 0.5165388235294117 0.5212752941176471 0.5260117647058823 0.5307482352941176 0.535484705882353 0.5402211764705882 0.5449576470588235 0.5496941176470588 0.554430588235294 0.5591670588235295 0.5639035294117648 0.56864 0.5733764705882353 0.5781129411764705 0.5828494117647058 0.5875858823529412 0.5923223529411765 0.5970588235294118 0.6017952941176471 0.6065317647058823 0.6112682352941176 0.6160047058823529 0.6207411764705882 0.6254776470588235 0.6302141176470588 0.6349505882352942 0.6396870588235295 0.6444235294117647 0.64916 0.6538964705882352 0.6586329411764705 0.6633694117647058 0.6681058823529412 0.6728423529411766 0.6775788235294118 0.682315294117647 0.6870517647058823 0.6917882352941176 0.6965247058823529 0.7012611764705882 0.7059976470588236 0.7107341176470588 0.7154705882352941 0.7202070588235294 0.7249435294117648 0.72968 0.7344164705882352 0.7391529411764705 0.7438894117647059 0.7486258823529413 0.7533623529411765 0.7580988235294117 0.7628352941176471 0.7675717647058823 0.7723082352941175 0.7770447058823529 0.7817811764705883 0.7865176470588235 0.7912541176470588 0.7959905882352941 0.8007270588235295 0.8054635294117647 0.8101999999999999 0.8149364705882352 0.8196729411764706 0.8244094117647058 0.8291458823529412 0.8338823529411765 0.8386188235294117 0.843355294117647 0.8480917647058822 0.8528282352941176 0.857564705882353 0.8623011764705882 0.8670376470588236 0.8717741176470588 0.876510588235294 0.8812470588235294 0.8859835294117647 0.89072 0.8954564705882353 0.9001929411764705 0.9049294117647059 0.9096658823529412 0.9144023529411764 0.9191388235294117 0.923875294117647 0.9286117647058822 0.9333482352941176 0.938084705882353 0.9428211764705883 0.9475576470588235 0.9522941176470587 0.9570305882352941 0.9617670588235293 0.9665035294117647 0.97124 0.9759764705882353 0.9807129411764706 0.9854494117647058 0.9901858823529411 0.9949223529411765 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995"></feFuncR>\n                                    <feFuncG type="table" tableValues="0.005 0.009736470588235294 0.014472941176470588 0.01920941176470588 0.023945882352941174 0.02868235294117647 0.033418823529411765 0.03815529411764706 0.042891764705882345 0.04762823529411764 0.05236470588235294 0.05710117647058823 0.061837647058823525 0.06657411764705883 0.07131058823529413 0.07604705882352941 0.0807835294117647 0.08552 0.09025647058823529 0.0949929411764706 0.09972941176470589 0.10446588235294119 0.10920235294117647 0.11393882352941176 0.11867529411764706 0.12341176470588235 0.12814823529411765 0.13288470588235293 0.13762117647058825 0.1423576470588235 0.14709411764705882 0.15183058823529413 0.1565670588235294 0.1613035294117647 0.16604 0.1707764705882353 0.17551294117647057 0.1802494117647059 0.1849858823529412 0.18972235294117648 0.19445882352941177 0.19919529411764708 0.20393176470588237 0.20866823529411765 0.21340470588235294 0.21814117647058825 0.2228776470588235 0.22761411764705883 0.23235058823529411 0.2370870588235294 0.2418235294117647 0.24656 0.2512964705882353 0.25603294117647063 0.26076941176470586 0.26550588235294115 0.2702423529411765 0.2749788235294118 0.279715294117647 0.2844517647058824 0.28918823529411763 0.2939247058823529 0.29866117647058826 0.30339764705882355 0.3081341176470588 0.3128705882352941 0.3176070588235294 0.32234352941176475 0.32708 0.33181647058823527 0.3365529411764706 0.3412894117647059 0.3460258823529411 0.35076235294117647 0.3554988235294118 0.36023529411764704 0.3649717647058824 0.3697082352941176 0.37444470588235296 0.37918117647058824 0.38391764705882353 0.38865411764705876 0.39339058823529416 0.3981270588235294 0.40286352941176473 0.40759999999999996 0.4123364705882353 0.4170729411764706 0.4218094117647059 0.4265458823529411 0.4312823529411765 0.4360188235294118 0.440755294117647 0.44549176470588236 0.45022823529411765 0.45496470588235294 0.4597011764705882 0.4644376470588235 0.4691741176470588 0.47391058823529414 0.47864705882352937 0.48338352941176466 0.48812 0.4928564705882353 0.49759294117647057 0.5023294117647058 0.5070658823529413 0.5118023529411765 0.5165388235294117 0.5212752941176471 0.5260117647058823 0.5307482352941176 0.535484705882353 0.5402211764705882 0.5449576470588235 0.5496941176470588 0.554430588235294 0.5591670588235295 0.5639035294117648 0.56864 0.5733764705882353 0.5781129411764705 0.5828494117647058 0.5875858823529412 0.5923223529411765 0.5970588235294118 0.6017952941176471 0.6065317647058823 0.6112682352941176 0.6160047058823529 0.6207411764705882 0.6254776470588235 0.6302141176470588 0.6349505882352942 0.6396870588235295 0.6444235294117647 0.64916 0.6538964705882352 0.6586329411764705 0.6633694117647058 0.6681058823529412 0.6728423529411766 0.6775788235294118 0.682315294117647 0.6870517647058823 0.6917882352941176 0.6965247058823529 0.7012611764705882 0.7059976470588236 0.7107341176470588 0.7154705882352941 0.7202070588235294 0.7249435294117648 0.72968 0.7344164705882352 0.7391529411764705 0.7438894117647059 0.7486258823529413 0.7533623529411765 0.7580988235294117 0.7628352941176471 0.7675717647058823 0.7723082352941175 0.7770447058823529 0.7817811764705883 0.7865176470588235 0.7912541176470588 0.7959905882352941 0.8007270588235295 0.8054635294117647 0.8101999999999999 0.8149364705882352 0.8196729411764706 0.8244094117647058 0.8291458823529412 0.8338823529411765 0.8386188235294117 0.843355294117647 0.8480917647058822 0.8528282352941176 0.857564705882353 0.8623011764705882 0.8670376470588236 0.8717741176470588 0.876510588235294 0.8812470588235294 0.8859835294117647 0.89072 0.8954564705882353 0.9001929411764705 0.9049294117647059 0.9096658823529412 0.9144023529411764 0.9191388235294117 0.923875294117647 0.9286117647058822 0.9333482352941176 0.938084705882353 0.9428211764705883 0.9475576470588235 0.9522941176470587 0.9570305882352941 0.9617670588235293 0.9665035294117647 0.97124 0.9759764705882353 0.9807129411764706 0.9854494117647058 0.9901858823529411 0.9949223529411765 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995"></feFuncG>\n                                    <feFuncB type="table" tableValues="0.005 0.009736470588235294 0.014472941176470588 0.01920941176470588 0.023945882352941174 0.02868235294117647 0.033418823529411765 0.03815529411764706 0.042891764705882345 0.04762823529411764 0.05236470588235294 0.05710117647058823 0.061837647058823525 0.06657411764705883 0.07131058823529413 0.07604705882352941 0.0807835294117647 0.08552 0.09025647058823529 0.0949929411764706 0.09972941176470589 0.10446588235294119 0.10920235294117647 0.11393882352941176 0.11867529411764706 0.12341176470588235 0.12814823529411765 0.13288470588235293 0.13762117647058825 0.1423576470588235 0.14709411764705882 0.15183058823529413 0.1565670588235294 0.1613035294117647 0.16604 0.1707764705882353 0.17551294117647057 0.1802494117647059 0.1849858823529412 0.18972235294117648 0.19445882352941177 0.19919529411764708 0.20393176470588237 0.20866823529411765 0.21340470588235294 0.21814117647058825 0.2228776470588235 0.22761411764705883 0.23235058823529411 0.2370870588235294 0.2418235294117647 0.24656 0.2512964705882353 0.25603294117647063 0.26076941176470586 0.26550588235294115 0.2702423529411765 0.2749788235294118 0.279715294117647 0.2844517647058824 0.28918823529411763 0.2939247058823529 0.29866117647058826 0.30339764705882355 0.3081341176470588 0.3128705882352941 0.3176070588235294 0.32234352941176475 0.32708 0.33181647058823527 0.3365529411764706 0.3412894117647059 0.3460258823529411 0.35076235294117647 0.3554988235294118 0.36023529411764704 0.3649717647058824 0.3697082352941176 0.37444470588235296 0.37918117647058824 0.38391764705882353 0.38865411764705876 0.39339058823529416 0.3981270588235294 0.40286352941176473 0.40759999999999996 0.4123364705882353 0.4170729411764706 0.4218094117647059 0.4265458823529411 0.4312823529411765 0.4360188235294118 0.440755294117647 0.44549176470588236 0.45022823529411765 0.45496470588235294 0.4597011764705882 0.4644376470588235 0.4691741176470588 0.47391058823529414 0.47864705882352937 0.48338352941176466 0.48812 0.4928564705882353 0.49759294117647057 0.5023294117647058 0.5070658823529413 0.5118023529411765 0.5165388235294117 0.5212752941176471 0.5260117647058823 0.5307482352941176 0.535484705882353 0.5402211764705882 0.5449576470588235 0.5496941176470588 0.554430588235294 0.5591670588235295 0.5639035294117648 0.56864 0.5733764705882353 0.5781129411764705 0.5828494117647058 0.5875858823529412 0.5923223529411765 0.5970588235294118 0.6017952941176471 0.6065317647058823 0.6112682352941176 0.6160047058823529 0.6207411764705882 0.6254776470588235 0.6302141176470588 0.6349505882352942 0.6396870588235295 0.6444235294117647 0.64916 0.6538964705882352 0.6586329411764705 0.6633694117647058 0.6681058823529412 0.6728423529411766 0.6775788235294118 0.682315294117647 0.6870517647058823 0.6917882352941176 0.6965247058823529 0.7012611764705882 0.7059976470588236 0.7107341176470588 0.7154705882352941 0.7202070588235294 0.7249435294117648 0.72968 0.7344164705882352 0.7391529411764705 0.7438894117647059 0.7486258823529413 0.7533623529411765 0.7580988235294117 0.7628352941176471 0.7675717647058823 0.7723082352941175 0.7770447058823529 0.7817811764705883 0.7865176470588235 0.7912541176470588 0.7959905882352941 0.8007270588235295 0.8054635294117647 0.8101999999999999 0.8149364705882352 0.8196729411764706 0.8244094117647058 0.8291458823529412 0.8338823529411765 0.8386188235294117 0.843355294117647 0.8480917647058822 0.8528282352941176 0.857564705882353 0.8623011764705882 0.8670376470588236 0.8717741176470588 0.876510588235294 0.8812470588235294 0.8859835294117647 0.89072 0.8954564705882353 0.9001929411764705 0.9049294117647059 0.9096658823529412 0.9144023529411764 0.9191388235294117 0.923875294117647 0.9286117647058822 0.9333482352941176 0.938084705882353 0.9428211764705883 0.9475576470588235 0.9522941176470587 0.9570305882352941 0.9617670588235293 0.9665035294117647 0.97124 0.9759764705882353 0.9807129411764706 0.9854494117647058 0.9901858823529411 0.9949223529411765 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995"></feFuncB>\n                                    </feComponentTransfer><feConvolveMatrix order="3 3" preserveAlpha="true" kernelMatrix="0 -1 0 -1 5 -1 0 -1 0"></feConvolveMatrix></filter>`

Do you know if the filter attribute is handled by the library?

**Comment by florentinGo** [comment]
@dlemstra for information I found a workaround. I need to remove the feConvolveMatrix markup in the svg and apply it after on the image with the method Convolve of MagickImage class.
