### ISSUE TITLE
.net5 使用Magick.NET-Q16-AnyCPU部署到Centos7 pdf转图片报错

### ISSUE THREAD

**Issue by zhanghaomars** [dlemstra/Magick.NET#1214]
### Magick.NET version

11.2.1

### Environment (Operating system, version and so on)

Linux Centos7

### Description

.net core 5 web api 项目引入 Magick.NET-Q16-AnyCPU库进行pdf转图片 window环境没有问题，可发布到Centos7 转换的时候报如下错误：
FailedToExecuteCommand `'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pngalpha' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r72x72' -dPrinted=false  '-sOutputFile=/tmp/magick-smuyz1_7cJ8HDOaQqd1jX8pASJR3Z0m6%d' '-f/tmp/magick-9d25vV3eni2eNnRttH_1OFxaIbxD3spq' '-f/tmp/magick-MBzK-t1kgiAW-IijW285M_5Z5KAqLjsK'' (32512) @ error/ghostscript-private.h/ExecuteGhostscriptCommand/74
可Centos已安装了 libgdiplus 
已加载插件：fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: hkg.mirror.rackspace.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
软件包 libgdiplus-2.10-10.el7.x86_64 已安装并且是最新版本
无须任何处理
请问这个要如何解决？

### Steps to Reproduce

string path = @"D:\\**.pdf";
            MagickReadSettings settings = new();
            settings.Density = new Density(72, 72); //设置质量
            using (MagickImageCollection images = new())
            {
                try
                {
                    images.Read(path, settings);
                    for (int i = 0; i < images.Count; i++)
                    {
                        MagickImage image = (MagickImage)images[i];
                        image.Format = MagickFormat.Jpg;
                        image.Write(path.Replace("**.pdf", "") + (i + 1) + ".jpg");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
服务器通过yum install -y libgdiplus 命令安装了libgdiplus

**Comment by dlemstra** [comment]
What are you trying to ask/tell me?
