### ISSUE TITLE
Unable to constrain memory usage when loading large GeoTIFF

### ISSUE THREAD

**Issue by kirk-marple** [dlemstra/Magick.NET#1215]
### Magick.NET version

Magick.NET-Q8-AnyCPU, 11.2.1

### Environment (Operating system, version and so on)

Win11, x64 (and Azure Function, x64)

### Description

When loading a large GeoTIFF, I'm seeing memory usage on the process peak up to 12.3GB used, and then comes down to ~4GB.

I calculated the bytes used by subtracting the before/after working set, and it says it used 4680851456 bytes from loading the image.

It's a large TIFF, 39691x28720, 24bit, so I'm expecting it to use ~4GB, but I'm wondering why it's peaking up to 12GB used before coming back down.

This is causing an issue trying to load this image within a 64-bit Azure Function (Windows), where I only have access to 14GB RAM for the app service plan.

### Steps to Reproduce

I've played around with the ResourceLimits.Memory and ResourceLimits.LimitMemory methods, but still can't get the image to load in the Azure Function.  It just hangs after the first "Attempting to load..." log message.

The code is as simple as this, and running it in debugger gives these logs:

Attempting to load image collection from file [G:\\Data\\Image\\GeoTIFF\\9c75cb72-e13a-4862-abe4-62058d5e108c.tif], working set [420810752] bytes.
Successfully loaded image collection from file [G:\\Data\\Image\\GeoTIFF\\9c75cb72-e13a-4862-abe4-62058d5e108c.tif], working set [5095530496] bytes, used [4674719744] bytes, took [00:00:16.6502789].

If I open Task Manager, while this is running, I can see the testhost.exe process jump up above 12GB, before settling back down to this 4.6GB number.

Any suggestions on how to better constrain the memory usage?  ResourceLimits.Memory seems to have no effect.

```
                const ulong DEFAULT_MEMORY = Common.FileHelpers.BYTES_PER_GIGABYTE * 4L; // 4GB

                ResourceLimits.Memory = DEFAULT_MEMORY;

                long workingSet = Environment.WorkingSet;

                logger.LogDebug($"Attempting to load image collection from file [{filePath}], working set [{workingSet}] bytes.");

                var collection = new MagickImageCollection();

                await collection.ReadAsync(filePath);

                long bytesUsed = Environment.WorkingSet - workingSet;

                logger.LogDebug($"Successfully loaded image collection from file [{filePath}], working set [{Environment.WorkingSet}] bytes, used [{bytesUsed}] bytes, took [{sw.Elapsed}].");
```

**Comment by dlemstra** [comment]
Can you share your image? I suspect something else in the image is taking up a lot of memory but without the image I cannot give proper advice. The memory limits can limit a lot but not everything because in some external dependencies we cannot limit the amount of memory that is being used.

**Comment by kirk-marple** [comment]
Sure thing, it's 100MB, so here's a G-Drive link:
https://drive.google.com/file/d/1JcsesrXa12B-XVMD7lGrL6JY4UkBy6jc/view?usp=sharing

It's not confidential or anything; found it online.

**Comment by dlemstra** [comment]
In the next version of Magick.NET you will be able to use `ResourceLimits.MaxMemoryRequest`. ImageMagick maintains a separate memory pool for large resource requests. If the limit that was specified is exceeded, the allocation is instead memory-mapped on disk.
