### ISSUE TITLE
Problem with reading certain BMP images. 

### ISSUE THREAD

**Issue by nielsbosma** [dlemstra/Magick.NET#1216]
### Magick.NET version

7.1.0-41

### Environment (Operating system, version and so on)

Win10

### Description

I have some bmp images that when I try to convert them I get:

```
PS C:\Concierge> magick identify .\example.BMP
.\example.BMP BMP3 800x600 800x600+0+0 8-bit sRGB 1.37334MiB 0.016u 0:00.011
identify: length and filesize do not match `.\74877697_Pleasant_20211207_111018_0001.BMP' @ error/bmp.c/ReadBMPImage/847
```

I found this thread that seems to be the same issue? Was it ever released?

https://github.com/dlemstra/Magick.NET/issues/528

Example BMP: 

[example.zip](https://github.com/dlemstra/Magick.NET/files/9078729/example.zip)

(The windows image viewer can open and also ImageSharp.)

### Steps to Reproduce

> magick identify .\example.BMP

**Comment by dlemstra** [comment]
Are you reporting a Magick.NET or an ImageMagick issue?

**Comment by nielsbosma** [comment]
Sorry this might be a ImageMagick issue.

**Comment by dlemstra** [comment]
You can use `BmpReadDefines.IgnoreFileSize` to disable this check.

**Comment by nielsbosma** [comment]
Thanks!

**Comment by nielsbosma** [comment]
Thanks!

**Comment by fmotion1** [comment]
> You can use `BmpReadDefines.IgnoreFileSize` to disable this check.

Hi, I have come across this problem as well and I don't know where to place the solution code above. Is there a particular configuration file I need to add it to? If so, what/where is it?
