### ISSUE TITLE
Get IntPtr?!

### ISSUE THREAD

**Issue by stefanak-michal** [dlemstra/Magick.NET#122]
Hi. It's possible to receive IntPtr from MagickImage instance?

**Comment by dlemstra** [comment]
Why would you want to get the IntPtr? What kind of use case do you have that you need the pointer?

**Comment by stefanak-michal** [comment]
I want to use it in unity3D to pass loaded picture with Magick.NET to Texture2D. Maybe I'm thinking wrong how it's works.

**Comment by dlemstra** [comment]
It looks like Textute2D requires you to translate an image to a `Color[]`. A `MagickImage` has `GetPixels()` or `GetPixelsUnsafe()` that will give you access to the pixels which you could convert to a `Color[]`.

**Comment by stefanak-michal** [comment]
Yeah, that was my first shot. But after different tries and founded a pointer and was seeking for a option, how to use it for my solution. Okay, thanks for answer, i will use pixel colors. Thanks
