### ISSUE TITLE
Image Crop doesn't respect the dimensions passed

### ISSUE THREAD

**Issue by Jinu1994** [dlemstra/Magick.NET#1221]
### Magick.NET version

v11.3.0

### Environment (Operating system, version and so on)

Windows 10 OS

### Description

The image Crop method is using the wrong dimensions for cropping i.e., width is used instead of height and vice versa. 
I'm trying to crop an image of 1000x1000 size to the dimensions of 850x700. However, the cropped image has incorrect dimensions i.e., 700x850.  We noticed this issue first on v7.22.0 of the library, and tried updating it to the latest version but the same behavior was observed.

I'm not sure if I'm missing something, can you help me understand what I'm doing wrong?

### Steps to Reproduce

I've tried this on the Magick.NET.Samples project which is available within the repo using the below code: 
```
public static void CropImage()
{
            // Read from file
            using (var collection = new MagickImageCollection(SampleFiles.ResizeTest))
            {
                // This will remove the optimization and change the image to how it looks at that point
                // during the animation. More info here: http://www.imagemagick.org/Usage/anim_basics/#coalesce
                collection.Coalesce();

                // Resize each image in the collection to a width of 200. When zero is specified for the height
                // the height will be calculated with the aspect ratio.
                foreach (var image in collection)
                {
                    image.Crop(850, 700, Gravity.Center);
                }

                // Save the result
                collection.Write(SampleFiles.OutputDirectory + "Resize_Test-resized.jpg");
            }
       }
```

Input image ![Resize_Image_Test](https://user-images.githubusercontent.com/27882619/181769128-7ae2d4ce-96f0-48c5-b9ff-d99305162b1d.jpg)

Output Image: ![Resize_Test-resized](https://user-images.githubusercontent.com/27882619/181769231-19adc25f-f6d4-4aeb-bba2-4a1b80bf4939.jpg)

P.S: What I've noticed is that after executing the 'Crop' function, the 'image' object has the width and height properties set correctly. However, when the new image is written to the output folder using 'collection.Write' the output image has the incorrect dimentions i.e,. 700x850

**Comment by dlemstra** [comment]
What happens when you call `image.Repage()` after you `Crop` it?

**Comment by dlemstra** [comment]
Your image is actually `850x700` but most programs that show the image automatically change the image orientation. This are the real dimensions of tour image:

```
identify output.jpg
output.jpg JPEG 850x700 850x700+0+0 8-bit sRGB 436047B 0.000u 0:00.001
```

**Comment by Jinu1994** [comment]
Hey Dirk, 

Thanks for the prompt response. 
I didn't quite understand the orientation bit though, I've tried checking the dimensions of the image using different tools, including some online sites and all of them show the dimensions as 700x850.  

Regardless, the crop I'm expecting is not what I'm getting. I'm using the option Gravity.Center, i.e,. `image.Crop(850,700, Gravity.Center)` so I'm expecting the image to be cropped as shown below. 
Expected Crop: For Gravity _Centre_ => x: 75, y: 150
![Expected_Crop](https://user-images.githubusercontent.com/27882619/182074791-3ec561c0-b50b-407a-8f87-e4561787b02e.png)


However, the cropped image I'm getting is this
Actual Crop:  For Gravity _Center_ => x: 150, y: 75
![Actual_Crop](https://user-images.githubusercontent.com/27882619/182074785-022aace3-19a9-4590-89f1-3d86284ad593.png)

I'm assuming that I'm calling the crop method correctly? Is there anything else I need to consider?

**Comment by dlemstra** [comment]
When you are viewing the image you are seeing it being auto rotated to the `TopLeft` orientation. Your image normally would look like this:
![afbeelding](https://user-images.githubusercontent.com/10426229/182212045-f0bb0d01-ce6b-4c40-9913-a537f4263fb9.png)

So when you cut out an area your are cutting out the image that is not yet rotated to how you are viewing it there. When you call `image.AutoOrient()` the image will be rotated and it will be shown as you are viewing it.

**Comment by Jinu1994** [comment]
Hi Dirk,

I wasn't aware of the auto orientation of the input image. Understood it now. 
And yes, using `image.AutoOrient()` I was able to get the right result.  

Thanks a lot for explaining this!
