### ISSUE TITLE
Converting APNG to GIF loses animation

### ISSUE THREAD

**Issue by kirk-marple** [dlemstra/Magick.NET#1224]
### Magick.NET version

Magick.NET-Q8-AnyCPU 11.3.0

### Environment (Operating system, version and so on)

Windows 11, .NET 6.0, C#

### Description

I can successfully read an APNG (attached), but when simply saving as a GIF, it has no animation.

[elephant.zip](https://github.com/dlemstra/Magick.NET/files/9237887/elephant.zip)
![elephant](https://user-images.githubusercontent.com/13594550/182260706-a0bf5dc8-b075-4fd8-b280-a46c1d4948f4.gif)

I'm assuming I'm doing something dumb here, but I can't figure out what's wrong.  Saving a GIF to GIF works fine and keeps the animation.

### Steps to Reproduce

Stripped out the relevant sample code:

```
var collection = new MagickImageCollection();

await collection.ReadAsync(filePath);

collection.Coalesce();

using var coll = new MagickImageCollection();

foreach (MagickImage source in collection)
{
    // helper to do crop/scale in place
    ImageMagickHelpers.ScaleImage(this.Logger, source, width, height, scalingType, cropType);

    source.Quantize(new QuantizeSettings
    {
        Colors = source.TotalColors,
        DitherMethod = DitherMethod.No
    });

    coll.Add(source);
}

coll.Optimize();

using var stream = System.IO.File.Create(filePath);

await coll.WriteAsync(stream, MagickFormat.Gif);

```

**Comment by dlemstra** [comment]
ImageMagick doesn't seem to detect that the format is an animated PNG. When you tell it to read the file as an animated PNG you will get an animated GIF as the output: `await collection.ReadAsync(filePath, MagickFormat.APng);`.

**Comment by kirk-marple** [comment]
Ah that makes sense.  Thanks for the quick answer.  That's an easy fix; I was actually inferring the ImageMagickFormat from MIME type, and just wasn't passing it into my image collection version of ReadAsync.
