### ISSUE TITLE
Magick.NET not finding FFMPEG.EXE in Azure Function, but it's in same bin folder

### ISSUE THREAD

**Issue by kirk-marple** [dlemstra/Magick.NET#1226]
### Magick.NET version

Magick.NET-Q8-AnyCPU, 12.0.0

### Environment (Operating system, version and so on)

Win 11, .NET 6, C#

### Description

When trying to fix [this](https://github.com/dlemstra/Magick.NET/issues/1224) issue, I needed to get FFMPEG in the path.

But I'm running in an Azure Function, and I can see I've copied ffmpeg.exe into the same folder as Magick*.dll: D:\home\site\wwwroot\bin

I don't think I can add anything to the system %PATH% on an Azure Function, so is there any other way to specify where Magick.NET should find FFMPEG?

### Steps to Reproduce

Try and convert APNG to GIF, like described in the issue above.

But get error:

Failed to load image collection from file [D:\local\Temp\24c8e28b-0362-4d27-807c-2d9fa8d3a014\file.apng].
FailedToExecuteCommand `"ffmpeg.exe" -nostdin -loglevel error -i "D:/local/Temp/magick-RcYhMoSD-uSrZ53WLPy_aXeIEF8xEYhZ" -an -f rawvideo -y  -pix_fmt rgba -vcodec webp "D:/local/Temp/magick-LEWgxnRf5-gwllazKD6eIbsJlYAEUyEm"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/516

**Comment by dlemstra** [comment]
I ran some test in an azure function and it does look like you will need to add the the folder that contains the `ffmpeg.exe` binary to your path. In the next version of Magick.NET I will add two new methods to the `MagickNET` class that can be used to get or set an environment variable. You will be able to this then:

```C#
var path = MagickNET.GetEnvironmentVariable("Path");
MagickNET.SetEnvironmentVariable("Path", @$"{path};C:\home\site\wwwroot");
```
