### ISSUE TITLE
inizialinging exception

### ISSUE THREAD

**Issue by RoyDJ84** [dlemstra/Magick.NET#123]
i get "NativeMagickSettings" error:

sample code i used:

Imports ImageMagick
Public Class Form1
    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
              Dim info As New MagickImageInfo("E:\D&D rpg\images\tirion vs arthas.jpg")
            Me.Text = String.Format("{0}x{1}", info.Height, info.Width)
      End Sub
End Class

**Comment by dlemstra** [comment]
It looks like you specified an incorrect file path? You should start either with an `@` or escape the `\`'s.

**Comment by RoyDJ84** [comment]
solved without change anythings in code, unistalled package from nuget and reinstalled new one. works like a charm. thanks ;)
