### ISSUE TITLE
Compression not lossless in one case

### ISSUE THREAD

**Issue by dabutvin** [dlemstra/Magick.NET#124]
Have been running the `LosslessCompression()` routine on tons of images and it has been working great.

Came across one that didn't come out completely lossless. 

see https://github.com/facebook/react/pull/10677/files

Was wondering if you had any insight into why?

Thanks

**Comment by dabutvin** [comment]
I have another example if that's any help

https://github.com/datenstrom/yellow/pull/290/files

see the first image with the desk

**Comment by dlemstra** [comment]
It looks like the profiles of the image are lost in the lossless compression. I will need to figure out how to read and write them in the optimizer. I hope I will have some time this week to figure that out. Will get back to this issue when I have a solution.

**Comment by dabutvin** [comment]
Thanks 🥇 

Appreciate the response. Let me know if there is anything I can do to help.

**Comment by dlemstra** [comment]
I had some time tonight :) Think I figured out how to resolve the issue but I will do some more testing to make sure my fix works.

I am still wondering if only preserving the ICC (color) profile should be sufficient or if all profiles should be copied with lossless compression. The lossless part is only about how the image looks but maybe you have a different view? I could introduce a new option to preserve all the profiles if you think that would be better.

**Comment by dabutvin** [comment]
Awesome!

From my view, lossless means it looks the same before and after.

Introducing more options to preserve more/ or less might be worthwhile if it's not too much overhead.

What info is in these other profiles besides the color profile?

**Comment by dlemstra** [comment]
One of the profiles could be the exif profile or the iptc profile. These profiles don't affect the appearance of the image. I could add the option but I think I will wait until I get a request from someone who has a proper use case for that situation.
