### ISSUE TITLE
Markup exported PDF looks skewed and some letters are missing

### ISSUE THREAD

**Issue by aashish317** [dlemstra/Magick.NET#1242]
### Magick.NET version

11.2.1

### Environment (Operating system, version and so on)

Windows 11, Windows server 2016

### Description

I'm exporting a svg file with some markup's on top of it. It displays correctly in the UI but when exported the texts in the svg document are overlapped in each other. 

### Steps to Reproduce

Export the SVG attached with a mark-up on it.
OR 
Export the stream below

UEsDBAoAAAAIADpVIlWWGdFLtQMAADcLAAAIAAAAY29udGVudHOtVtuO2zYQfe9XTNWXDRBdLdmSYy+QoGjQogHysOjrgpZoiViJFEjashP03zukJF83F6M2FlqJHM45c2Y0I4CF2pbQsUJXSydM0tCBirKy0vgUJIEDW0a7D2K3dAIIwBhAv75raq6WTqV1O/f9ruu8buIJWfpREAQ+Oh1M5hte0DXjtPgZ412lm/o1wzDLMt/uOqD0vqZLR4tNXrkk10zwOXDB6TvYKCpdRWua63HJ7ejqhWnXbhWSlJcbmrRuhSHXJmw3F7WQc5DlijwEb2H4e/POgS9CNO958ZnwpdOQkrP13tKeq5bkyKeVFCG2FDWjUiEplNALncdfAGBRAkMBjJitkLpfhIVEnrBmNYb82x/2dyn/WWb2mAWEtFfj7p8+N38Wjj84RKlVfwuLmvEXkBR9W8FURal2QO9box3daT9XCuEkXS8d/33b+gVT2idbuiUep9oriKpWgsjCaxj3jLE/urYOL109egcVaQFfMU1SvFAr5UOUJIOQ8CtrjASEa/gXvD5XV/Zo2h85t1/4FnkI1j9Gi/oOMgb254xMy+EGFobnhRGsBdeuYl+oSVU0iaM0mYX9ddhck4bVqDtTYhJk6ertE6lEQ5yB7dIxtYSqSsLVWsjGlIaWbPeQeFGcxsE0SsC8OSePYRB4UZTBNIu9OEvfjFwNRywlPtZ3VzFNXVtccwCsrrMCePy0B04aCkzBX6Li8LvoFr51cAjZNzGPSvjlKFt50MwU0SciXzbt32SPRfszr/UryjKNObEeIERQ+zhu2hI3OHj2+bS7hKk3m0aTLAgn01mYzpJjsacTL53MkjSJ4yzqtzDyJEq9KMnSaDqdBmEyjawScTrzZkGWZPEsmuIi2gqUjGk8YZKICXdPF/q8vbY0oCfH3J5XrjNUj20Ndvl4wV3/R0L3pS7kZyIp1x+l2LRHMQFfvrYm+6GgDvLlTOb4qrWCcY39i27xKOaH1PUl7+jQGPONVNjDeOdiR8LidkCiTg7kNVHqyOOjZO1zb/HMuwP//4d5A+SdEOkNkPQ+mDdA3glR3QCp7oV5A+SdEG+oWHWnir0B8hQRhyu9cB1+47DQRNNccG7XrllfEfwOEevr+63mquOdDrm4/3DQpHwSoj60H9ukL9XrJ9v5nOs7oJ1MyNOMIy+iDd7uDreHBt8/DmEFtoW7oVk6fsAMPJ5Y+6E8RmUn9etszBYmDD8pJeMlZnijxRVHE283sFiJuhhpr2qSv1x/RR1JHPQ4GZyjtMP/hZmBj/8BUEsBAhQACgAAAAgAOlUiVZYZ0Uu1AwAANwsAAAgAAAAAAAAAAAAAAAAAAAAAAGNvbnRlbnRzUEsFBgAAAAABAAEANgAAANsDAAAAAA==

**Comment by dlemstra** [comment]
I don't have enough information to help you. What are you trying to do and how are you doing that? This library has no UI so I don't understand the problem that you are experiencing.
