### ISSUE TITLE
Magick.Native-Q8-x64.dll in use indefinitely (IIS)

### ISSUE THREAD

**Issue by jav-mut** [dlemstra/Magick.NET#1249]
### Magick.NET version

11+

### Environment (Operating system, version and so on)

Windows Server, IIS

### Description

I am using ImageMagick as a NuGet package in a web project. This website is running on IIS.

After executing the code part of ImageMagick, the Magick.Native-Q8-x64.dll file stays in use indefinitely and cannot be deleted or overwritten, so I can't update the web normally (I'm forced to recycle the application pool before).

This has started to happen with the latest versions of the NuGet package (Magick.NET 11.0.0 and later), before it didn't.

Do you know what could be happening?

Regards,

### Steps to Reproduce

Steps:

1. Upload web version
2. Execute the code part of ImageMagick
3. Try to re-upload web version

The part of code that is executed is simple:

```
Dim image As MagickImage = New MagickImage()
image.Read(url)
image.Resize(0, dim)
image.Quality = quality
image.Depth = depth
image.Write(url)
```

**Comment by dlemstra** [comment]
Earlier version of Magick.NET would write the Native library to a temporary folder and have a locked file there. This behavior has changed in recent versions and the native library is no longer saved to a temporary folder. What you can do is use the `MagickNET.SetNativeLibraryDirectory(yourFolder)` method and copy the native library to the specified folder. But that file will still be locked and cannot be overwritten. I am also a bit surprised that you don't do an application recycle when you update your IIS application.

**Comment by jav-mut** [comment]
Hi Dirk,

Thank you very much for your attention.

I don't recycle the app pool because it would affect all the websites in the app pool. To update a website I use the "app_offline.htm" file.

I have created the directory "C:\Test\", I have copied the library Magick.Native-Q8-x64.dll to this directory and I have placed the statement `MagickNET.SetNativeLibraryDirectory("C:\Test\")` before the part of ImageMagick code, but the issue continues.

```
MagickNET.SetNativeLibraryDirectory("C:\Test\")
Dim image As MagickImage = New MagickImage()
image.Read(url)
image.Resize(0, dim)
image.Quality = quality
image.Depth = depth
image.Write(url)
```

I have also tried copying the rest of the ImageMagick DLLs generated by the NuGet package (Magick.NET-Q8-AnyCPU.dll, Magick.NET.Core.dll and Magick.Native-Q8-x86.dll), with the same result.

Regards,

**Comment by dlemstra** [comment]
Is it possible that when you copy the `app_offline.htm` file that some files remain locked for a while and that you need to wait for the lock to be released. I don't know how native libraries are handled when you create the `app_offline.htm` it might be possible that this requires an app pool restart because IIS puts a lock on this file? I don't have a lot of experience with `app_offline.htm` so I don't think I can help you a lot with this.

**Comment by jav-mut** [comment]
Hi Dirk,

But I understand that if I use MagickNET.SetNativeLibraryDirectory I shouldn't have any problem, am I doing something wrong with this?

Even though I use this method, it seems to still be using the Magick.Native-Q8-x64.dll library in the bin directory instead of the "C:\Test\" directory (I keep getting the error when trying to delete the Magick.Native-Q8-x64.dll library from the bin directory).

Regards,

**Comment by dlemstra** [comment]
You should not keep the `.dll` in the `bin` folder when you use `C:\test` as the directory specified by `SetNativeLibraryDirectory`.

**Comment by jav-mut** [comment]
Hi Dirk,

Thank you very much, if I delete the library from the bin directory it works perfectly.

Thank you very much for your attention.
