### ISSUE TITLE
ImageMagick.MagickCoderErrorException: Read Exception `' @ error/png.c/MagickPNGErrorHandler/1711 

### ISSUE THREAD

**Issue by Contejious** [dlemstra/Magick.NET#125]
Getting this error when trying to trim a png and read it back using Magick.NET here are the source and output images. Using latest version of Magick.NET nuget package (7.0.7.900)
ouput

![output](https://user-images.githubusercontent.com/715447/32621387-a4b625ec-c54d-11e7-9346-1942e29afe73.png)

input

![input](https://user-images.githubusercontent.com/715447/32621388-a4c4dc9a-c54d-11e7-8d9e-e843cb6735f2.png)

ImageMagick.MagickCoderErrorException: Read Exception `' @ error/png.c/MagickPNGErrorHandler/1711

**Comment by dlemstra** [comment]
Could you add a code sample so I can try to reproduce your issue?

**Comment by Contejious** [comment]
Input image uploaded above is read as a byte array and sent as the first arg, the returned byte array is the output image uploaded image converted to a file. When imagemagick tries to read this output image above error is thrown

` public byte[] ConvertImage(byte[] imageDataBytes, string sourceFileExtension, string targetFileExtension) {
      byte[] destinationImage;

      using (var sourceImageStream = new MemoryStream(imageDataBytes)) {
        using (var sourceImage = new MagickImage()) {
          var magickReadSettings = new MagickReadSettings{
            Format = GetMagickImageFormat(sourceFileExtension),
            BackgroundColor = MagickColors.Transparent,
            ColorSpace = ColorSpace.sRGB
          };
          sourceImage.Read(sourceImageStream, magickReadSettings);
          sourceImage.Alpha(AlphaOption.On);

          sourceImage.ColorFuzz = new Percentage(1);
          sourceImage.Trim();

          using (var outputImageStream = new MemoryStream()) {
            sourceImage.Format = GetMagickImageFormat(targetFileExtension);
            sourceImage.ColorSpace = ColorSpace.sRGB;
            sourceImage.Write(outputImageStream);
            destinationImage = outputImageStream.ToArray();
          }
        }
      }

      return destinationImage;
    }`

**Comment by Contejious** [comment]
//srcStream is the byte array of the output image (above) 


var readSettings = new MagickReadSettings {
              ColorSpace = ColorSpace.sRGB,
            };

var inputImg = new MagickImage(srcStream, readSettings);  <-- error thrown here

using (inputImg) {
     ...... more code....
}

**Comment by Contejious** [comment]
Stack trace 
............
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
   at ImageMagick.MagickImage..ctor(Stream stream, MagickReadSettings readSettings)
.........

**Comment by Contejious** [comment]
on digging deeper we found out that its Mongo GridFs that is corrupting the byte steam. Not an Magick.NET issue

**Comment by dlemstra** [comment]
Happy to hear that your issue is resolved. Was about to investigate it.

**Comment by Contejious** [comment]
Thank you for your immediate attention into this issue even though it was a red herring. Much appreciated.
