### ISSUE TITLE
No EXIF for jp2

### ISSUE THREAD

**Issue by GeronimoSuneco** [dlemstra/Magick.NET#1254]
### Magick.NET version

12.1.0

### Environment (Operating system, version and so on)

Windows 10, VSC, Azure Functions

### Description

I am unable to retrieve the EXIF data from my jp2 images. The ExifProfile is always null.

### Steps to Reproduce

Load an image from BinaryData into MagickImage and get the exif profile

**Comment by dlemstra** [comment]
There is no support for reading exif data in the library that is being used by ImageMagick so that is why you don't get that data.
