### ISSUE TITLE
IsMultiFrame return TRUE for non multiframe webp

### ISSUE THREAD

**Issue by Bxaa** [dlemstra/Magick.NET#1255]
### Magick.NET version

Magick.NET-Q16-HDRI-OpenMP-x64 (12.1.0)

### Environment (Operating system, version and so on)

Net6.0\Win10x64

### Description

FormatInfo.IsMultiFrame return TRUE for static\non multiframe webp format (wrong header parsing?)
(Possible need addition check for frames)
Samples webp for test:
https://drive.google.com/file/d/1FSPsJxRkHWzimmr-VwqnTDE9fMaf8gUd/view?usp=sharing

### Steps to Reproduce

`\\...New MagickImage(stream).FormatInfo.IsMultiFrame...\\`

**Comment by dlemstra** [comment]
Attaching file as zip: [IM_Webp_Bug_Report_Samples.zip](https://github.com/dlemstra/Magick.NET/files/9586198/IM_Webp_Bug_Report_Samples.zip)

**Comment by dlemstra** [comment]
You are misunderstanding how the `FormatInfo` property of an image works. This is information about the format. And it returns `true` because the format supports reading multiple frames. How can I improve the intellisense  documentation to make this more clear?

**Comment by Bxaa** [comment]
Maybe IsMultiFrame --> WithMultiFrameSupport :))
Oh, my bad :)
Thx, sorry

**Comment by dlemstra** [comment]
That would be a breaking change but I will make sure to change the property names in the next major release.

**Comment by Bxaa** [comment]
Thx for your work
