### ISSUE TITLE
refactor the SetLowLightColor method

### ISSUE THREAD

**Issue by bruno211439** [dlemstra/Magick.NET#126]
Please refactor the SetLowLightColor method.

imgDiff.SetLowlightColor(new MagickColor(Color.Blue));

tks.

**Comment by dlemstra** [comment]
Currently the  `SetLowLightColor` and `SetHighlightColor` methods are no longer working and they are only used inside the compare method. That is why I decided to add a new `CompareSettings` class to contain these settings. I will reply to your [stackoverflow](https://stackoverflow.com/questions/47221821/how-to-use-highlight-color-in-magickimage) post with an example when I have published the new release that will resolve your issue.
