### ISSUE TITLE
Reading Image 8MB, Getting Error Invalid JPEG file structure

### ISSUE THREAD

**Issue by shafaqat-ali-cms365** [dlemstra/Magick.NET#1263]
### Magick.NET version

Magick.NET-Q16-AnyCPU and 

### Environment (Operating system, version and so on)

Windows

### Description

I am trying to resize an image but getting this error.
Invalid JPEG file structure: two SOI markers `[Imagepath]20211201_e38fb75f8f8525fc05abc1396a7cde02.jpg' @ error/jpeg.c/JPEGErrorHandler/348

`           
               using (var image = new MagickImage(path)) //Error on this line
               {
                var size = new MagickGeometry(100, 100);
                size.IgnoreAspectRatio = true;

                image.Resize(size);

                image.Write(path);
            }`

### Steps to Reproduce

You can download image from https://www.dropbox.com/s/5ubul4r6n2yit2e/20211201_e38fb75f8f8525fc05abc1396a7cde02.jpg?dl=1 and execute locally.

**Comment by dlemstra** [comment]
I cannot reproduce your issue. Which version are you using? And are you running this in 32 or 64 bit?

**Comment by shafaqat-ali-cms365** [comment]
Running in 64 bit. Attached is the screenshot of the error

![image](https://user-images.githubusercontent.com/60454784/192710261-1a8c3c15-2c31-4640-800c-cc230062209c.png)

**Comment by dlemstra** [comment]
Your exception dialog looks a bit weird. Are you sure the exception is being raised here?

**Comment by shafaqat-ali-cms365** [comment]
Yeah, it is raised in the MagicImage load function, Are you able to re product it by downloading the image locally?

**Comment by dlemstra** [comment]
I can load the image without any issues on my machine with that versoon.
