### ISSUE TITLE
Compositing or extending a 32-bit magickImage caps the pixel values to 16-bit (65535)

### ISSUE THREAD

**Issue by CFekkes** [dlemstra/Magick.NET#1265]
### Magick.NET version

12.1.0.0

### Environment (Operating system, version and so on)

Windows 10 x64 - Visual Studio 2019 v16.11.9

### Description

Goal: merge two 32-bit images.

After extending a 32-bit image, all pixel values are capped to a value of 65535.
After compositing a 32-bit image, the pixel values of the original image are correct (can be higher than 65535), but the pixel values of the new/added image are also capped at a value of 65535.

### Steps to Reproduce

[images.zip](https://github.com/dlemstra/Magick.NET/files/9665416/images.zip)

1. Download test images added as attachment
2. Set path1 and path2 to the location of those images
3. Call the functions below:

Example 1: Extent
------
```
static void ExtentImage(string path1, string path2)
{
            IMagickImage<float> image1 = new MagickImage(path1);
            IMagickImage<float> image2 = new MagickImage(path2);

            IMagickImage<float> result = new MagickImage(path1);
            result.Depth = 32; // already has a depth of 32, but added it just to be sure
            var pixels = result.GetPixelsUnsafe().GetValues(); // has pixel values above 65535

            result.Extent(image1.Width + image2.Width, image1.Height);
            var pixels_extent = result.GetPixelsUnsafe().GetValues(); // pixel values are not higher than 65535
}
```

Example 2: Composite
------

```
static void CompositeImage(string path1, string path2)
{
            IMagickImage<float> image1 = new MagickImage(path1);
            IMagickImage<float> image2 = new MagickImage(path2);

            IMagickImage<float> result = new MagickImage(path1);
            result.Depth = 32;
            var pixels = result.GetPixelsUnsafe().GetValues(); // has pixel values above 65535

            result.Composite(image2, image1.Width/2, 0, CompositeOperator.In);
            var pixels_comp = result.GetPixelsUnsafe().GetValues(); // old part of the image still has values above 65535, but new (added) image is capped at 65535
}
```

**Comment by CFekkes** [comment]
> What is the exact version of Magick.NET that you are using?

Magick.NET-Q16-HDRI-x64 v12.1.0.0

**Comment by CFekkes** [comment]
Just out of curiosity (and not to rush or anything), is it reproducible for you?

**Comment by dlemstra** [comment]
I haven't made time to investigate this yet.

**Comment by dlemstra** [comment]
Turns out that you need to do the following:

```C#
result.SetArtifact("compose:clamp", false); // Extent uses compose
result.Extent(image1.Width + image2.Width, image1.Height);
```

It looks like this option was added because the `Composite` method would always clamp the pixels. I do wonder if we should have disabled this by default for the HDRI build. Will ask the team if we should prevent clamping by default for the HDRI build.

**Comment by CFekkes** [comment]
Works like a charm, thanks a lot Dirk!
Personally would disable the clamping for HDRI by default. It's a bit confusing that this happens automatically.
