### ISSUE TITLE
“unable to create temporary file '': No such file or directory @ error/pdf.c/ReadPDFImage/476”

### ISSUE THREAD

**Issue by jorgemrsantos** [dlemstra/Magick.NET#127]
I'm trying to use Magick.net in a console application to render images from a PDFs and can't seem to get around this problem.

Upon calling "MagickImageCollection.Read(byte[], settings)" I always get a

"unable to create temporary file '': No such file or directory @ error/pdf.c/ReadPDFImage/476"
exception.

I have tried:
- Placing both x86 and 64bit Ghostscript dlls in the bin folder.
- Using combinations of AnyCPU, x86, 64 versions of Magick.net, with versions of GS
- Setting MagickNET.SetGhostscriptDirectory to the program files GS bin folder
- Setting MagickNET.SetTempDirectory to a folder in c:/temp and confirmed that my application can access by programatically moving a file in there.
- Setting the MagickAnyCPU.CacheDirectory to a folder in c:/temp

I'm out of ideas of what I could be doing wrong

**Comment by jorgemrsantos** [comment]
I finally managed to overcome this problem, I was passing the wrong read settings to MagickImageCollection.Read(byte[], settings). I was telling Magick to read the PDF with the PNG format.
I suggest improving the error message as it is very misleading

**Comment by dlemstra** [comment]
Could you share a small code sample that I can use to reproduce your issue? I really wonder why you were getting that odd exception.

**Comment by jorgemrsantos** [comment]
Of course, here goes my exact code

MagickReadSettings settings = new MagickReadSettings();
settings.Density = new Density(96);
settings.Format = MagickFormat.Png;

using (MagickImageCollection images = new MagickImageCollection())
    {
        images.Read(file, settings);

        switch (orientation)
        {
            case Orientation.Horizontal:
                using (MagickImage image = (MagickImage)images.AppendHorizontally())
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        image.Write(ms);

                        return ms.ToArray();
                    }

                }
            case Orientation.Vertical:
                using (MagickImage image = (MagickImage)images.AppendHorizontally())
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        image.Write(ms);

                        return ms.ToArray();
                    }
                }
        }
    }

**Comment by dlemstra** [comment]
I just rebuild Magick.NET with the latest version of ImageMagick. This includes a fix for the issue that you reported and you will not get a much better error message:

```
ImageMagick.MagickCorruptImageErrorException:
improper image header `' @ error/png.c/ReadPNGImage/4214
```

Thanks for reporting this!
