### ISSUE TITLE
ImageMagick.MagickCorruptImageErrorException

### ISSUE THREAD

**Issue by Augus** [dlemstra/Magick.NET#128]
When read this psd file, ImageMagick throw below exception:
ImageMagick.MagickCorruptImageErrorException: improper image header `E:\test.psd' @ error/psd.c/ReadPSDImage/2025

.psd file link: 
[https://drive.google.com/file/d/0B2L42wEcBlEMbmNBQkFZejk5QXc/view?usp=sharing](https://drive.google.com/file/d/0B2L42wEcBlEMbmNBQkFZejk5QXc/view?usp=sharing)

**Comment by dlemstra** [comment]
Your PSD file is 32 bit per channel and that is currently not supported by ImageMagick: https://github.com/ImageMagick/ImageMagick/issues/455. Once that feature has been added you will be able to read your file. Thanks for sharing your file so we can use that to implement this feature.
