### ISSUE TITLE
Three Image Alpha Mask Composition - inconsistencies around edges

### ISSUE THREAD

**Issue by avisra** [dlemstra/Magick.NET#1285]
### Magick.NET version

12.2.0

### Environment (Operating system, version and so on)

Windows 10

### Description

Given the following source images:
[artboard-overlay.png](https://shovelblobs.blob.core.windows.net/test/artboard-overlay.png)
[artboard.png](https://shovelblobs.blob.core.windows.net/test/artboard.png)
[artboard-mask.png](https://shovelblobs.blob.core.windows.net/test/artboard-mask.png)

If I run this command in ImageMagick 7.1.0-30 Q8 x64
`magick composite artboard-overlay.png artboard.png artboard-mask.png artboard-result-cmp.png`

I get the expected output:
[artboard-result-cmp.png](https://shovelblobs.blob.core.windows.net/test/artboard-result-cmp.png)

Which is similar to what Photoshop outputs for me.

But... when my server attempts to process this through Magick.NET, I get the following output:
[artboard-im-result6.png](https://shovelblobs.blob.core.windows.net/test/artboard-im-result6.png)

My goal is to get the exact same image as the imagemagick CLI generates. The problem with the image generated by Magick.NET is that its adding grey edges around the output image - and this doesn't work for our use case.

This is the code I'm using on Magick.NET to replicate this test

```
    using (var overlayImage = new MagickImage(assets["test-artboard-overlay"]))
    {
        using (var artboardImage = new MagickImage(assets["test-artboard"]))
        using (var arboardMask = new MagickImage(assets["test-artboard-mask"]))
        {
            arboardMask.Negate();

            artboardImage.SetWriteMask(arboardMask);
            artboardImage.Composite(overlayImage, CompositeOperator.SrcOver);

            var writeStream2 = new MemoryStream();
            artboardImage.Write(writeStream2, MagickFormat.Png);
            writeStream2.Position = 0;
            using (var fileStream = File.Create($"C:\\Users\\test\\OneDrive\\Desktop\\artboard-im-result6.png"))
            {
                writeStream2.Seek(0, SeekOrigin.Begin);
                writeStream2.CopyTo(fileStream);
            }

        }
    }
```

I'm hoping this isn't a bug, and maybe just a missing flag/argument.

### Steps to Reproduce

See description

**Comment by dlemstra** [comment]
You will need to change your code to this:

```C#
using (var overlayImage = new MagickImage(assets["test-artboard-overlay"]))
{
    using (var artboardImage = new MagickImage(assets["test-artboard"]))
    using (var arboardMask = new MagickImage(assets["test-artboard-mask"]))
    {
        using var result = artboardImage.Clone();
        artboardImage.Composite(overlayImage, CompositeOperator.SrcOver);
        artboardImage.Composite(arboardMask, CompositeOperator.CopyAlpha);
        result.Composite(artboardImage, CompositeOperator.Over);

        var writeStream2 = new MemoryStream();
        result.Write(writeStream2, MagickFormat.Png);
        writeStream2.Position = 0;
        using (var fileStream = File.Create($"C:\\Users\\test\\OneDrive\\Desktop\\artboard-im-result6.png"))
        {
            writeStream2.Seek(0, SeekOrigin.Begin);
            writeStream2.CopyTo(fileStream);
        }

    }
}
```

**Comment by avisra** [comment]
That did it :) man I could swear I tried just about every combination - but must have missed that one. thank you!
