### ISSUE TITLE
LosslessCompress on PNG creates different byte sequence on each run

### ISSUE THREAD

**Issue by nikolai-mb** [dlemstra/Magick.NET#1289]
### Magick.NET version

Magick.NET-Q8-x64 12.2.0

### Environment (Operating system, version and so on)

Windows 11

### Description

Hello,

I wanted to ask if it's by-design that the ImageOptimizer.LosslessCompress produces a different byte sequence for PNG files on each run?

Example code:

```c#
var pngBase64 = "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAn1BMVEVkjK9ljbBli69kja11mbm3zdvp7vT8/v25zNueuc75+vzy9vm+0N6hutCguc+90N76+/1kjLBija/////C0uFqkLVqkLSduc53mritw9hokLOsw9X7/P6EpsGrwtSGpcFji69ji65ylrhzl7eatMvr8PT+//+iu9HM2OSTr8f///2CpL+pv9SEo79sj7Wft8/x9fjz9/qeuM+6zdxljq4m+hBZAAAAAWJLR0QTDLtclgAAAAd0SU1FB+YKHRIYI9vUW+kAAAC2SURBVBjTLZDbWsIwGATH/CFpTKI5UbGAWAUBxbPv/2xetHuxl/vNLMCVEkCYGkAvjLWm08xx1z7Em1ufXC6AuNqWKOhbvRNAp7a6HyjDetU2GqTz/bpuYVsfet8BJjDsAHYDwcCjjWSgjJQxWsBGBJ6eM0K0ICbA/lBfDnsIBuj88lhP5/Pp9TiN6tTeLhnF5b1tNIziavuYwT6BIrj0FWIM3+lnUlHoX2OtWWjybCeI4m864B+AlQt50tjUuAAAACV0RVh0ZGF0ZTpjcmVhdGUAMjAyMi0xMC0yOVQxODoyNDozNSswMDowMATQCckAAAAldEVYdGRhdGU6bW9kaWZ5ADIwMjItMTAtMjlUMTg6MjQ6MzUrMDA6MDB1jbF1AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAABJRU5ErkJggttN3ddsferyLUc2vAF1+fCigtL/6310n6nMQRLFkDCO40v+T4ABAIisLjh60Dh/AAAAAElFTkSuQmCC";

ImageOptimizer optimizer = new() {OptimalCompression = true};

var fileBytes = Convert.FromBase64String(pngBase64);
Console.WriteLine("Original file hash: " + Convert.ToBase64String(SHA256.HashData(fileBytes)));

MemoryStream stream = new(Convert.FromBase64String(pngBase64));
if (!optimizer.LosslessCompress(stream))
{
    throw new InvalidOperationException("Could not compress");
}

Console.WriteLine("Compressed file hash: " + Convert.ToBase64String(SHA256.HashData(stream.ToArray())));
```
If i run the code above three times, i get the following output:

1:
Original file hash: Y/2tU6/b/KIYVWI33e9qlB+JPtiqOWsIC4DljpQ+pXs=
Compressed file hash: jXpmGpSCetHbzZM69+fJj6tfSokP/TwwbbpYO51kYAg=

2:
Original file hash: Y/2tU6/b/KIYVWI33e9qlB+JPtiqOWsIC4DljpQ+pXs=
Compressed file hash: /d/YAr3dbSZL/88Jwy9m8WgjTI02BNecKOnl6dsQxC0=

3:
Original file hash: Y/2tU6/b/KIYVWI33e9qlB+JPtiqOWsIC4DljpQ+pXs=
Compressed file hash: Xc1+7hlol/btKybAJn2KxKL4NXXV6c2lHz0vumxI5s8=

Is this the expected behavior? I would expect to see the same output each time, since the input is the same.

This does not seem to affect JPEG files using LosslessCompress. I'm also unable to reproduce on PNG if i use Compress instead of LosslessCompress. But the compress method seems to return a different, smaller image, which i assume is because it removes some additional information from the image? Using PngOptimizer instead seems to result in same behaviour.

I encountered this since i'm hashing compressed files in order to find duplicates. But since two identical PNG files create a different hash each time, this does not work. I could of course generate the hash before running the compression, just wanted to check if this was intended behavior.

### Steps to Reproduce

See provided code example

**Comment by dlemstra** [comment]
The intended behavior is that the pixels of the image are not changed. It is possible that some metadata will be changed. Some metadata fields of the PNG format use a timestamp and that is why you are getting a different hash each time.
