### ISSUE TITLE
MagickImage.Quality reports incorrect values in some cases.

### ISSUE THREAD

**Issue by ToofDerling** [dlemstra/Magick.NET#1297]
### Magick.NET version

Magick.NET-Q16-AnyCPU 12.2.1

### Environment (Operating system, version and so on)

Windows 10 22H2 x64 

### Description

As part of a larger project that compares image quality of comics books I found a couple of instances where MagickImage reports the wrong Quality. 

In both cases Irfanview reports the quality of the "hd" images as 82 which is in line with the slightly larger file sizes of the "hd" versions.

### Steps to Reproduce

Download the images from this location https://drive.google.com/drive/folders/1ZYsjJh5fJb_O2R22_qaBiEPkQy7R797j?usp=sharing (download size 566 KB). Run the following snippet and note that hdimage and hdping lists the quality for both images as 63 instead of the expected 82.

```
private static string[] books = new[]
        {
            "Analysis\\[Avery Hill] A City Inside",
            "Analysis\\[Avery Hill] I Love This Part"
        };

        static void Main(string[] args)
        {
            foreach (var book in books)
            {
                Console.WriteLine(book);
                var sd = Path.Combine(book, "sd", "cover.jpg");
                Analyse(sd, nameof(sd));
                var hd = Path.Combine(book, "hd", "cover.jpg");
                Analyse(hd, nameof(hd));

                static void Analyse(string path, string id)
                {
                    using var image = new MagickImage(path);
                    Console.WriteLine($"  {id}image: {image.Height} {image.Quality}");
                    using var ping = new MagickImage();
                    ping.Ping(path);
                    Console.WriteLine($"  {id}ping: {ping.Height} {ping.Quality}");
                }
            }
        }

**Comment by dlemstra** [comment]
[[Avery Hill] A City Inside-20221114T162533Z-001.zip](https://github.com/dlemstra/Magick.NET/files/10004990/Avery.Hill.A.City.Inside-20221114T162533Z-001.zip)
[[Avery Hill] I Love This Part-20221114T162257Z-001.zip](https://github.com/dlemstra/Magick.NET/files/10004991/Avery.Hill.I.Love.This.Part-20221114T162257Z-001.zip)

Attaching zip files here instead.

**Comment by dlemstra** [comment]
It looks like irfanview uses a different calculation that we do. And the reason that your hd version is bigger is because it contains a color profile and this is not inside your sd file. When I remove this profile the size of the file is reduced to 98 kb.

**Comment by ToofDerling** [comment]
GraphicsMagick (gm identify -verbose) says the quality is 81 ;) 

Maybe the higher numbers of gm and iv are because they think the color profile is part of the image? (I'm guessing here, I'm far from an expert on jpeg compression). Is it possible to strip the color profile from a jpeg without changing the actual image? 

Anyway, I was hoping ImageMagick was wrong here, because in this comics book context the HD images are supposed to be "better than" the SD images. But out of ~2000 books only these two had any images where SD > HD, so unless you find any compelling reason to look at the Quality algorithm you can close this.
