### ISSUE TITLE
Throw exception "length and filesize do not match" when convert bmp to jpg

### ISSUE THREAD

**Issue by xucongli1989** [dlemstra/Magick.NET#1305]
### Magick.NET version

12.2.1

### Environment (Operating system, version and so on)

Windows 10 22H2 19045.2311, .NET Framework 4.7

### Description

Convert bmp to jpg throw exception `length and filesize do not match C:\Users\XCL\Desktop\test.bmp @ error/bmp.c/ReadBMPImage/853`.

# Code 

```c#
void Main()
{
	using (var image = new MagickImage(@"C:\Users\XCL\Desktop\test.bmp"))
	{
		image.Write(@"C:\Users\XCL\Desktop\test.jpg", MagickFormat.Jpg);
	}
}
```
When I change it to this below, no exception but  the converted file color is abnormal.

```c#
void Main()
{
	var settings = new MagickReadSettings(new BmpReadDefines
	{
		IgnoreFileSize = true,
	});
	using (var image = new MagickImage(@"C:\Users\XCL\Desktop\test.bmp", settings))
	{
		image.Write(@"C:\Users\XCL\Desktop\test.jpg", MagickFormat.Jpg);
	}
}
```
# Preview

![image](https://user-images.githubusercontent.com/9961428/203926552-70e219e0-7fac-462f-a639-393b5ca33d5b.png)

![image](https://user-images.githubusercontent.com/9961428/203926620-ea72a5ba-756f-4e89-9880-838cf307f8a7.png)

# Test files
[test.zip](https://github.com/dlemstra/Magick.NET/files/10089560/test.zip)

### Steps to Reproduce

More details see Description above. Thanks a lot!

**Comment by dlemstra** [comment]
It looks like your bmp file contains an invalid offset. Will need see if we can work around that and make it possible to read this file.
