### ISSUE TITLE
DrawableTextDecoration can't have multiple TextDecorations (ImageMagick.TextDecoration)

### ISSUE THREAD

**Issue by Kojimo** [dlemstra/Magick.NET#1312]
### Magick.NET version

12.0.0.0

### Environment (Operating system, version and so on)

Windows 10

### Description

Searching online seems that ImageMagick allows to use multiple Text Decorations on drawables, allowing for example text with underline AND line-through.

In Magick.NET you can specify only one type of TextDecoration, or at least I can't find how to use two of them.

### Steps to Reproduce

//You can do the following
new DrawableTextDecoration(TextDecoration.Underline);

//But you cannot do the following
new DrawableTextDecoration(TextDecoration.UnderlineAndLineThrough);

**Comment by dlemstra** [comment]
Do you have an example that demonstrates this is possible on the command line? Because it looks like this is not possible when I take a look at the code?

**Comment by Kojimo** [comment]
I had misunderstood this thread [https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=36255](https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=36255)
Sorry, I'll close the issue.
