### ISSUE TITLE
Unable to load DLL 'Magick.Native-Q16-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by DenisCampara** [dlemstra/Magick.NET#1313]
### Magick.NET version

Magick.NET-Q16-AnyCPU 12.2.1

### Environment (Operating system, version and so on)

Windows 10

### Description

WEB Application developed in asp.NET:

- .dll folder were downloaded via Nuget.
- .dll folders they are all in the bin:
1. > Magic.Native-q16-arm64.dll 
2. >    Magick.Native-q16-x64.dll
3. >    Magick.Native-q16-x86.dll
4. >    Magick.NET-Core.dll
5. >    Magick.NET-Q16-AnyCPU.dll

    
- I noticed that an error appears when the site is in production, and only for external users (users whose IP is not within our organization).

**Exception**:  The type initializer for 'NativeMagickSettings' threw an exception.
**Exception-InnerMessage**: Unable to load DLL 'Magick.Native-Q16-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
**Exception-InnerStackTrace** : 
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 22
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 321
**Exception-StackTrace** :
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor()
   at ImageMagick.MagickSettings..ctor() in /_/src/Magick.NET/Settings/MagickSettings.cs:line 33
   at ImageMagick.MagickImage..ctor() in /_/src/Magick.NET/MagickImage.cs:line 41
**Exception-Type**: TypeInitializationException

- when this error first appeared we set it up MagickNET.SetNativeLibraryDirectory(Server.MapPath("~/bin")), just in case, and this worked for a while without error, but over and over again this error appears.
- the error last time was removed by re-publishing the site.
- **question**: how to solve this?
Thank you

### Steps to Reproduce

It does not work only when it is in the production phase. It's hard to reproduce it during development

**Comment by dlemstra** [comment]
What are you using to run the application? I suspect it has to do with your production setup and there is not much I can do for you. If this cannot be reproduced locally it must be something on the machine/os you are running this on.

**Comment by meirkr** [comment]
Hi
I get similar results but on linux x64 docker environment.
I think the Production mode mentioned above is related to the dotnet publish process.
(in docker we also use donet publish command).

Suppose I have a project "MyProj.csproj" which references:
`<PackageReference Include="Magick.NET-Q16-x64" Version="12.2.0" />`

When I used in dockerfile:
`RUN dotnet publish -c Release -o out "MyProj.csproj"`
Everything worked well.

But when I saw the output image size was very big, I noticed that all the native assets were copied into a sub folder "runtimes/ {type}/native", including windows, arm...

So I changed the publish command to:
`RUN dotnet publish -c Release -r linux-x64 --sc false -o out "MyProj.csproj"`
and saw the output image size was really reduced and there was no "runtimes" subfolder anymore.
Instead, the .so file was placed in the app directory, together with the Macick .NET DLLs:
```
-rwxr--r--    1 root     root      80392248 Oct  5 01:20 Magick.Native-Q16-x64.dll.so
-rwxr--r--    1 root     root       1478888 Oct  6 21:37 Magick.NET.Core.dll
-rwxr--r--    1 root     root        709864 Oct  6 21:40 Magick.NET-Q16-x64.dll
```

But unfortunately found in runtime the DLL not found exception:
```
System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libMagick.Native-Q16-x64.dll: No such file or directory
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize() in /_/src/Magick.NET/Native/Helpers/Environment.cs:line 65
   at ImageMagick.Environment.Initialize() in /_/src/Magick.NET/Helpers/Environment.cs:line 21
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 321
   --- End of inner exception stack trace ---
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor() in /_/src/Magick.NET/Native/Settings/MagickSettings.cs:line 343
   at ImageMagick.MagickSettings..ctor() in /_/src/Magick.NET/Settings/MagickSettings.cs:line 33
   at ImageMagick.MagickImage..ctor() in /_/src/Magick.NET/MagickImage.cs:line 41

```

I hope that new info might assist understanding the problem.

Tx,
Meir.

**Comment by dlemstra** [comment]
Can you create a small Dockerfile that demonstrates this issue and I can use to reproduce the issue?

**Comment by meirkr** [comment]
I made a new project to investigate it:
https://github.com/meirkr/MagickImageInvestigation

The last commit replacing the publish "-r linux-x64" by "-r **alpine**-x64" has fixed that issue.
Before that commit it complaint about missing libresolv.so.2.
Now everything is ok. Tx.

Besides,
I have no clue what could be the solution for the original complaint in this thread.

**Comment by dlemstra** [comment]
Thanks for coming back to this issue @meirkr and telling us how you got this working. Will close this issue now because I got no response from @DenisCampara.
