### ISSUE TITLE
Corrupted JPEG loaded without making exception

### ISSUE THREAD

**Issue by avengerfr** [dlemstra/Magick.NET#1320]
### Magick.NET version

12.2.2

### Environment (Operating system, version and so on)

Windows

### Description

Hi !
I have two corrupted JPEG where well loaded by Magick.NET.Core without exception, but I need of exception's on it !
(I try JPEGSnoop who log me some error :
*** ERROR: @ 0x00360024.1, nNumCoeffs>64 [65]
*** ERROR: Bad scan data in MCU(39,239): Lum CSS(1,0) @ Offset 0x00360025.0
           MCU located at pixel=(632,1912)
*** ERROR: @ 0x0010A02C.2, nNumCoeffs>64 [67]
*** ERROR: Bad scan data in MCU(265,80): Lum CSS(1,0) @ Offset 0x0010A02D.2
           MCU located at pixel=(4248,640)
)
![IMG_9841](https://user-images.githubusercontent.com/121096520/208647200-79f6d8b2-baf7-4728-bf60-1a51ce26d85f.JPG)
![IMG_9901](https://user-images.githubusercontent.com/121096520/208647212-7879e1f4-9269-4456-bc7b-fb45edb1fe30.JPG)

Thanks,

### Steps to Reproduce

only load without produce any exception ...
the two JPEG are really corrupted !

**Comment by dlemstra** [comment]
The library that we are using is not reporting an error and there is nothing I can do to change that behavior. You will probably need to find something else that can check this for you.
