### ISSUE TITLE
Unable to use animated JPEG XL with third part programs

### ISSUE THREAD

**Issue by superbonaci** [dlemstra/Magick.NET#1322]
### Magick.NET version

latest

### Environment (Operating system, version and so on)

any

### Description

ImageGlass can't open animated JPEG XL due to this software.
Full link and samples:
https://github.com/d2phap/ImageGlass/issues/1464

### Steps to Reproduce

Follow link,

**Comment by dlemstra** [comment]
Support for reading this will become available in the next release.
