### ISSUE TITLE
Unable to use animated AVIF with third part programs

### ISSUE THREAD

**Issue by superbonaci** [dlemstra/Magick.NET#1323]
### Magick.NET version

latest

### Environment (Operating system, version and so on)

any

### Description

Unable to open animated AVIF with third party programs due to this software limitations.
Issue link and sample:
https://github.com/d2phap/ImageGlass/issues/1465

### Steps to Reproduce

Follow the link.

**Comment by dlemstra** [comment]
Magick.NET has support for reading animated AVIF files but this file appears to be Duck_IVF (https://wiki.multimedia.cx/index.php/Duck_IVF) instead of AVIF.
