### ISSUE TITLE
Exception when converting to TIFF from stream

### ISSUE THREAD

**Issue by Asbjoedt** [dlemstra/Magick.NET#1332]
### Magick.NET version

12.2.2

### Environment (Operating system, version and so on)

Win 11

### Description

Thrown exception on image.Write()

```
ImageMagick.MagickCoderErrorException: 'Computed scanline size is zero. `TIFFScanlineSize64' @ error/tiff.c/TIFFErrors/598'
```

I am trying to convert either a JPG or PNG file to TIFF. The data is fed via stream. The data is streamed from embedded images in a spreadsheet using Open XML SDK. I have tested the images are good, by streaming them out of the spreadsheet into independent image files, and they show no issues in native file PNG/JPG format. When I try to convert using ImageMagick from the same stream, the above exception is thrown.

Changing MagickFormat to anything else also throws exceptions.

The stream does however come from data type ```System.IO.Packaging.ZipWrappingStream``` and this cannot be cast to a memorystream. All Office Open XML are zip compressed, this is hidden from the user in the extension. How can I do I/O on a streamed embedded object from an OOXML file using ImageMagick?

**My code for ImageMagick. The code for getting the stream is too much to share here. The issue should still be reproducible.**
```
    // Convert embedded object to TIFF
    public Stream Convert_to_TIFF(Stream stream)
    {
        using (var memStream = new MemoryStream())
        {
            // Change stream to memorystream
            stream.CopyTo(memStream);
            memStream.Position = 0;

            using (var image = new MagickImage())
            {
                // Set output format
                image.Format = MagickFormat.Tiff;

                // Write the image
                image.Write(memStream); // Exception is thrown on this line

                // Return the stream
                return memStream;
            }
        }
    }
```

PS. The idea behind what I am doing is to convert embedded images in a spreadsheet to TIFF for archival purposes.

### Steps to Reproduce

Test the code from Description.

**Comment by dlemstra** [comment]
Your sample code makes no sense to me? You are not reading an image and you are returning the input stream?

**Comment by Asbjoedt** [comment]
I am reading the image by copying the input stream to memStream ```stream.CopyTo(memStream);```.

I forgot to write memStream in the text above, thx for the observation.

Does it make more sense now?

**Comment by dlemstra** [comment]
Still doesn't make sense because you are not reading the image with the `MagickImage` class. I would suspect something like this:

```C#
    public Stream Convert_to_TIFF(Stream stream)
    {
        using (var image = new MagickImage(stream)) // This reads the image
        {
            // No using because otherwise you cannot use the result in the method that calls this method
            var memStream = new MemoryStream();

            // Write the image
            image.Write(memStream, MagickFormat.Tiff);

            // Return the stream
            return memStream;
        }
    }
```

**Comment by Asbjoedt** [comment]
Thank you for responding greatly helping fix my issues.

I only nedded to add ```stream.Position = 0;``` and code is working now from your code.

If I may give feedback, I tried to implement from the example in this doc:
https://github.com/dlemstra/Magick.NET/blob/main/docs/ConvertImage.md

```
// Write to stream
var settings = new MagickReadSettings();
// Tells the xc: reader the image to create should be 800x600
settings.Width = 800;
settings.Height = 600;

using (var memStream = new MemoryStream())
{
    // Create image that is completely purple and 800x600
    using (var image = new MagickImage("xc:purple", settings))
    {
        // Sets the output format to png
        image.Format = MagickFormat.Png;

        // Write the image to the memorystream
        image.Write(memStream);
    }
}
```

I cannot see anywhere an image is being read.

PS. Feel free to close this issue, the issue was only my own errors, but maybe someone else can get help from it.

**Comment by dlemstra** [comment]
This is where the image is being read: `using (var image = new MagickImage("xc:purple", settings))` It creates a purple image that is `800x600`.
