### ISSUE TITLE
NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4504

### ISSUE THREAD

**Issue by vitvitskyi** [dlemstra/Magick.NET#1334]
### Magick.NET version

Magick.NET-Q8-x64 (12.2.2)

### Environment (Operating system, version and so on)

Heroku, Docker

### Description

Hello

I'm trying to add a watermark to the image using Magick.NET
It works perfectly on Windows, but when I try to deploy it to Heroku in the Docker container I'm receiving the error: "NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4504"

The issue is only with the watermark. Image compression/transformation is working fine.

Thank you

### Steps to Reproduce

My Docker file is
```Dockerfile
FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out
RUN apt-get update && apt-get install -y libgdiplus libc6-dev
RUN apk add --no-cache msttcorefonts-installer && update-ms-fonts && fc-cache -f

RUN apt install libfreetype6-dev
RUN apt install libfontconfig1-dev
RUN apt install ghostscript

RUN apt-get update; apt-get install -y fontconfig

RUN fc-cache -f -v

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /app
COPY --from=build /src/out .
ENTRYPOINT [ "dotnet", "/app/DockerNetExample.dll" ]
```
c# code:
```C#
[HttpPost]
[Route("create")]
public async Task Create([FromForm] IFormFile file)
{
try
{
var oFileName = $"{DateTimeHelper.GetUniqFileName()}.webp";

using (var memStream = new MemoryStream())
            {
                file.CopyTo(memStream);
                memStream.Position = 0;

                using (var copyright = new MagickImage("xc:none", 350, 150))
                {
                    copyright.Draw(new Drawables()
                        .FillColor(new MagickColor("grey"))
                        .Gravity(Gravity.Center)
                        .Rotation(-45)
                        .FontPointSize(15)
                        .Text(10, 10, "Watermark"));

                    using (var image = new MagickImage())
                    {
                        image.Read(memStream);
                        image.Format = MagickFormat.WebP;
                        image.Quality = 30;
                        image.Tile(copyright, CompositeOperator.Over);
                        image.Write(memStream);

                        return File(image.ToByteArray(), "application/octet-stream", oFileName);
                    }
                }
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine(ex.Message);
            return StatusCode(500, ex.Message);
        }
    }
```

**Comment by dlemstra** [comment]
It looks like you are installing ghostscript and fontconfig in your build container instead of your runtime container?

**Comment by vitvitskyi** [comment]
@dlemstra I changed the file to:
`FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish -c Release -o out
RUN apt-get update && apt-get install -y libgdiplus libc6-dev
RUN apk add --no-cache msttcorefonts-installer && update-ms-fonts && fc-cache -f

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /app

COPY --from=build /src/out .

RUN apt-get update && apt-get install -y fontconfig
RUN apt install libfreetype6-dev
RUN apt install libfontconfig1-dev
RUN apt install ghostscript

RUN fc-cache -f -v

ENTRYPOINT [ "dotnet", "/app/DockerNetExample.dll" ]`

If I followed you correctly. But still getting the issue

**Comment by dlemstra** [comment]
Do you have any fonts installed in your container? You should be able to see that with `fc-cache -v`.

**Comment by vitvitskyi** [comment]
Hello @dlemstra this is what I got https://prnt.sc/2sbU_bd9pp3P
I have troubles when I try to install msttcorefonts-installer
It says "Unable to locate package msttcorefonts-installer"
I also tried:
`apt install -y msttcorefonts-installer fontconfig && \
    update-ms-fonts && \
    fc-cache -f`

and `apt-get install --reinstall ttf-mscorefonts-installer`
it says "Package 'ttf-mscorefonts-installer' has no installation candidate"

**Comment by vitvitskyi** [comment]
![image](https://user-images.githubusercontent.com/61783015/212886258-5ef53cd5-f969-4fa6-80b1-0cd3c31c2c25.png)
thank you for the quick response @dlemstra

**Comment by vitvitskyi** [comment]
@dlemstra I added the following commands to the end of the dockerfile 
`RUN git clone https://github.com/ImageMagick/msttcorefonts msttcorefonts
RUN msttcorefonts/install.sh`

whole file looks now:

`FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /
COPY . .
RUN apt-get update && dotnet restore
RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /

COPY --from=build /out .

RUN apt-get update && apt-get install -y libgdiplus libc6-dev
RUN rm /bin/sh && ln -s /bin/bash /bin/sh
# install fontconfig

#Add these two lines for fonts-liberation instead
RUN apt-get update; apt-get install -y fontconfig fonts-liberation
RUN apt install -y libfreetype6-dev
RUN apt install -y libfontconfig1-dev
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

#RUN apt install -y msttcorefonts-installer && update-ms-fonts && fc-cache -f

RUN git clone https://github.com/ImageMagick/msttcorefonts msttcorefonts
RUN msttcorefonts/install.sh


# refresh system font cache
RUN fc-cache -f -v

CMD ASPNETCORE_URLS=http://*:$PORT dotnet web-api.dll`

But still having problems when I try to install 
![image](https://user-images.githubusercontent.com/61783015/212896088-bf6792c6-5eb2-4fe2-acde-2c8adfb9500b.png)

**Comment by dlemstra** [comment]
The `install.sh` script only works when you are running this from the `msttcorefonts` folder.

**Comment by vitvitskyi** [comment]
Thank you @dlemstra 
Now, it works fine and the watermark is creating
The final docker file looks like this:

`FROM mcr.microsoft.com/dotnet/sdk:7.0 as build
WORKDIR /
COPY . .
RUN apt-get update && dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0 as runtime
WORKDIR /

COPY --from=build /out .

RUN apt-get update && apt-get install -y libgdiplus libc6-dev
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

RUN apt-get update; apt-get install -y fontconfig fonts-liberation
RUN apt install -y libfreetype6-dev
RUN apt install -y libfontconfig1-dev
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git

#RUN apt install -y msttcorefonts-installer && update-ms-fonts && fc-cache -f

RUN git clone https://github.com/ImageMagick/msttcorefonts msttcorefonts
WORKDIR /msttcorefonts
RUN chmod +x install.sh
RUN ./install.sh
WORKDIR "../"

RUN fc-cache -f -v

CMD ASPNETCORE_URLS=http://*:$PORT dotnet web-api.dll`
