### ISSUE TITLE
Unable to load DLL 'Magick.Native-Q16-HDRI-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by kothavishal1** [dlemstra/Magick.NET#1335]
### Magick.NET version

12.2.0.0

### Environment (Operating system, version and so on)

Windows

### Description

I tried adding Magick.Net-Q16-HDRI-x64 package from nuget for a .net project. 
When using the pre-compiled dlls from Nuget (magick.net-q16-hdri-x64.7.23.3 and magick.net.core.6.1.3) an error is thrown and complains about Magick.Native-Q16-HDRI-x64.dll missing.

Magick.Native-Q16-HDRI-x64.dll is not getting generated in bin folder in production app. It works fine when we are working in our local system.

![image](https://user-images.githubusercontent.com/17621181/212864462-e545df15-97ff-4f28-b98d-43394431beb5.png)

### Steps to Reproduce

Added Magick.NET-Q16-HDRI-x64.dll as reference to solution (version v12.2.0)
Added Magick.NET.Core.dll as reference to solution (version 12.2.0)

**Comment by kothavishal1** [comment]
![image](https://user-images.githubusercontent.com/17621181/213128991-3afbe6b6-89d5-49d5-893a-3177376bf373.png)

.Net Framework 4.8

**Comment by dlemstra** [comment]
Are you running this on IIS? And did you check that your application pool is set to 64-bit mode?

**Comment by kothavishal1** [comment]
Yes, its 64-bit mode only.
Can you help me out to get rid of this error.
