### ISSUE TITLE
MagickResourceLimitErrorException: pixel cache allocation failed

### ISSUE THREAD

**Issue by phil000** [dlemstra/Magick.NET#1337]
### Magick.NET version

12.2.2

### Environment (Operating system, version and so on)

Windows 10.0.14393

### Description

ImageMagick.MagickResourceLimitErrorException: pixel cache allocation failed `[0]' @ error/cache.c/AcquireCacheNexusPixels/5000

Getting this exception on our server in Azure, but when I try scaling the image locally in a unit test it works fine.

I guess you'll say we're probably running out of memory, but the server has 8GB and is usually only 30% utilized. There was no spike in memory usage at the time.

```
Exception: ImageMagick.MagickResourceLimitErrorException: pixel cache allocation failed `[0]' @ error/cache.c/AcquireCacheNexusPixels/5000
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in /_/src/Magick.NET/Native/NativeInstance.cs:line 63
   at ImageMagick.MagickImage.NativeMagickImage.AutoOrient() in /_/src/Magick.NET/Native/MagickImage.cs:line 4190
   at Onsend.Lib.Core.Drawing.ImageMagickResizer.CoreResizeImage(MagickImage image, Int32 maxWidth, Int32 maxHeight, Int32 quality) in /_/Onsend.Lib/Core/Drawing/ImageMagickResizer.cs:line 196
```

### Steps to Reproduce

Resize image (with a file that's too big for me to upload here). Seems to happen on the initial 'AutoOrient' we perform.

Original Image: 
64MP (6936 x 9248)
11.2 MB (11,770,438 bytes)

I can provide the image, it's just too big to upload here.

**Comment by phil000** [comment]
I've resubmitted a request to create a thumbnail from the image in question, and it's worked this time.

There seems plenty of memory on the server in general, 8GB, that also sits at about 30-35% utilization.

What memory\resource limit is being challenged here - .NET managed memory, unmanaged process memory? It's a large *image*, but still only 11MB

**Comment by dlemstra** [comment]
Your image is `11 MB` but when you load the image you will need `6936 * 9248 * (8 or 16 or 32) * ChannelCount` bits of memory because all the pixels will need to be loaded in memory.

And what is the name of the NuGet package that you are using? And is your application running in 32 or 64-bit mode?

**Comment by phil000** [comment]
We're using Magick.NET-Q8-AnyCPU, and the server would run 32-bit mode.

There's typically ~5GB of available memory on the server, so unless the allocation was utterly massive the server memory should be sufficient. 

The issue suggests a resource limit getting space in a pixel cache - AcquireCacheNexusPixels - which we know nothing about - but seems to be its own internally managed pool.

**Comment by dlemstra** [comment]
When you run your application in 32-bit mode your memory will be limited to `1` or `2` Gb per process. So you are probably running out of memory depending on the operation that you are executing. The `AcquireCacheNexusPixels` method tries to allocate memory but fails to do so because the operating system is not giving the amount of memory that it is requesting. I would advise you to switch to `64-bit` mode instead.

**Comment by phil000** [comment]
Thank you. We will shift to x64 and wait to see if the issue happens again.
