### ISSUE TITLE
Icon creation is slow

### ISSUE THREAD

**Issue by fahminlb33** [dlemstra/Magick.NET#134]
Hi, I'm just trying using Magick.NET instead of calling `magick convert` to make development easier, but I think it is not that easy.

I'm trying to convert square JPG to multi-size ICO, and it worked, but... it really slow and takes up much memory. I tried using code below in resulting over 300MB memory and 70~90% CPU usage as long as 2 minute processing.

```
using (MagickImage image = new MagickImage(@"E:\output_square.jpg"))
{
        image.Settings.SetDefine(MagickFormat.Icon, "auto-resize", "256,128");
        image.Write(@"E:\testIcon3.ico");
}
```

I've used Magick.NET to create a square JPG file and it took only ~10MB of memory and ~10% CPU usage. That being said, the ICO was successfully created. How do I improve the speed of above code?

**Comment by dlemstra** [comment]
Can you share your input image and tell me which version of Magick.NET you are using?

**Comment by fahminlb33** [comment]
I'm using Magick.NET-Q16-AnyCPU version 7.2.1.0 and the input image is 256x256 square JPG file [here](https://image.ibb.co/nk7zUm/converted.jpg).

But now I'm using single ICO file (256x256) instead of multi-size ICO. It reduces the time it needs and the resulting ICO is pretty good too. So, I'm removing the `SetDefine` line and now it works.
