### ISSUE TITLE
.SVG images rendering problem

### ISSUE THREAD

**Issue by Csumidex** [dlemstra/Magick.NET#1343]
### Magick.NET version

???

### Environment (Operating system, version and so on)

Win 7 Ultimate X86

### Description

Having problem converting some .svg images to .png with Image Glass viewer that is using your code but the developer sending me here
Please follow this link to see the full description of bug and some screenshots

https://github.com/d2phap/ImageGlass/issues/1489

Have a Nice Day

### Steps to Reproduce

https://github.com/d2phap/ImageGlass/issues/1489

**Comment by dlemstra** [comment]
Next time you create an issue please include a sample file that can be used to reproduce this issue. Magick.NET uses librsvg for svg rendering but this library is not as good as inkscape. My advice would be to install inkscape on your system. This will then be used when reading a svg file with Image Glass.

**Comment by Csumidex** [comment]
![ad](https://user-images.githubusercontent.com/105267095/216818672-e51152e0-6779-4ef7-90cc-16b12e4d8d37.svg)
.svg flags , some rendering in Image Glass others no .... Irfan View is OK
![ao](https://user-images.githubusercontent.com/105267095/216818698-1dafe772-4778-4695-85ec-274cacd623d2.svg)
![ar](https://user-images.githubusercontent.com/105267095/216818717-da562df1-c28e-41a1-ad74-38225a5a0c55.svg)
