### ISSUE TITLE
Drawing Text on .NET7 on MACOS crashes

### ISSUE THREAD

**Issue by algorni** [dlemstra/Magick.NET#1347]
### Magick.NET version

"Magick.NET.Core" Version="12.2.2" + "Magick.NET-Q16-x64" Version="12.2.2" 

### Environment (Operating system, version and so on)

MacOS .NET7

### Description

Tried this sample:

https://github.com/dlemstra/Magick.NET/blob/main/docs/Drawing.md

But gettingall the time:

An exception of type 'ImageMagick.MagickDrawErrorException' occurred in Magick.NET-Q16-x64.dll but was not handled in user code: 'NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4504'

### Steps to Reproduce

https://github.com/dlemstra/Magick.NET/blob/main/docs/Drawing.md  on .NET7 and MACOS

**Comment by dlemstra** [comment]
Did you try setting your `fontconfig` directory as mentioned in this issue: #696?
