### ISSUE TITLE
.NETCore and Linux error

### ISSUE THREAD

**Issue by CGKajm** [dlemstra/Magick.NET#135]
Hey, I installed Magick.NET-Q16-AnyCPU through nuget on .NETCore console app and made a simple app to try it out if it's gonna work on Linux. Published as a self contained app, upload to a linux environment tried to  run it, but I get this error https://gyazo.com/6e5949a7aba13d58e09ccfd36433d43c and I am pretty clueless, pack reference is looking fine, I did ldd Magick.NET-Q8-x64.Native.dll.so but it didnt find anything. I guess I missed something, do you have any idea? Thanks :) 

edit: I can't find the Native.dll anywhere it looks like it's not being created at all, I compile as dotnet publish -r linux-arm

**Comment by dlemstra** [comment]
The command `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/ImageMagick/libraries` is just an example. You will need to find the `libMagickCore` library on your machine and add the path to the folder that contains this file. For my machine this is in `/usr/local/lib` so I need to do `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`. And did you install ImageMagick 7 on your machine?

**Comment by CGKajm** [comment]
I installed it, but I dont see any libraries folder 
https://gyazo.com/444f7c88d6a1419ae3d344bc793c1e12

**Comment by dlemstra** [comment]
You will need to find the folder where the libraries were copied to when you did make install with ImageMagick.

**Comment by CGKajm** [comment]
I only found this https://gyazo.com/681216bd9faf9b81b02a2c728d479f6f

**Comment by dlemstra** [comment]
Do you do a `make install`?
