### ISSUE TITLE
MagickImage.GetHashCode throws exception when image is disposed

### ISSUE THREAD

**Issue by compujuckel** [dlemstra/Magick.NET#1350]
### Magick.NET version

Magick.NET-Q8-x64 12.3.0

### Environment (Operating system, version and so on)

.NET 7 on Windows 10, Ubuntu 20.04

### Description

I'm using Magick.NET in conjunction with NLua.
When creating a MagickImage from Lua code, it seems that NLua stores an internal reference to this image in a Dictionary. This will sometimes lead to an ObjectDisposedException when GetHashCode is called on the MagickImage:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'MagickImage'.
   at ImageMagick.MagickImage.GetHashCode() in /_/src/Magick.NET/MagickImage.cs:line 3145
   at System.Collections.Generic.Dictionary`2.Remove(TKey key)
   at NLua.ObjectTranslator.CollectObject(Object o, Int32 udata)
   at NLua.ObjectTranslator.CollectObject(Int32 udata)
   at NLua.MetaFunctions.CollectObject(Lua luaState, ObjectTranslator translator)
   at NLua.MetaFunctions.CollectObject(IntPtr state)
```

According to: https://learn.microsoft.com/en-us/dotnet/api/system.object.gethashcode?view=net-7.0
> The GetHashCode() method should not throw exceptions.

Could this method be adapted to not throw even when the image is already disposed?

### Steps to Reproduce

```csharp
var img = new MagickImage();
img.GetHashCode();
img.Dispose();
await Task.Delay(1000);
img.GetHashCode();
```

**Comment by dlemstra** [comment]
I think I will need to remove this implementation in the next major release. Overriding `GetHashCode()` no longer makes sense to me. But I don't have a plan for when to make these breaking changes.
