### ISSUE TITLE
[Regression] Native libraries not copied to ClickOnce publish

### ISSUE THREAD

**Issue by OronDF343** [dlemstra/Magick.NET#1356]
### Magick.NET version

12.3.0

### Environment (Operating system, version and so on)

Windows 10 x64

### Description

As of version 12.3.0, native DLLs are no longer copied when publishing with ClickOnce. Downgrading to version 12.2.2 fixes this issue.

Probably caused by the fix to #1336 based on [this issue in another project](https://github.com/shimat/opencvsharp/issues/737)

### Steps to Reproduce

* Create .NET Framework console app or VSTO add-in
* Add any Magick.NET package such as `Magick.NET-Q8-OpenMP-x64` version 12.3
* Add properties to csproj as outlined [here](https://github.com/dlemstra/Magick.NET/blob/main/docs/CrossPlatform.md#native-library-is-not-copied-to-the-bin-folder)
* Publish with ClickOnce
* Observe that the native library is not copied to the Application Files version directory

**Comment by dlemstra** [comment]
Is it possible to create a small sample project that demonstrates this issue?

**Comment by OronDF343** [comment]
https://github.com/OronDF343/MagickClickOnce

To get it running:
* First make sure that it works standalone (NuGet restore success)
* Right-click on the project -> properties -> Signing -> Create Test Certificate -> Ok
* Publish the project

**Comment by dlemstra** [comment]
Thanks for reporting this and giving me a sample project that I could use for testing. I think I got it fixed by the patch that is referenced in this issue. You can test this locally by making the same changes to the file `packages\Magick.NET-Q8-OpenMP-x64.12.3.0\build\netstandard20\Magick.NET-Q8-OpenMP-x64.targets`.

**Comment by OronDF343** [comment]
Confirmed, after changing the `.targets` file and restarting Visual Studio (required) it appears to be fixed. Thanks!
