### ISSUE TITLE
Image FileSize is always Zero

### ISSUE THREAD

**Issue by ch-adnan** [dlemstra/Magick.NET#136]
I am working on requirement where during upload image from user on ASP.net form, I need to check if user provided image is greater than 500kb then I don't need to reduce the size of the image if it is above the size then reduce the size of the image but when I tried to use FileSize property it always show 0 value. I am using below code.
  
          using (MagickImageCollection collection = new MagickImageCollection(txtInput.Text))
            {
                collection.Coalesce();

                foreach (MagickImage image in collection)
                {
                    if (image.FileSize >= 500)
                    {
                        image.Quality = 50;
                        image.Sample(image.Width / 2, image.Height / 2);
                    }
                }
                collection.Write(txtOutput.Text);
            }

**Comment by dlemstra** [comment]
You might get the correct value when you do collection.FileSize but I wonder if Magick.NET is the right tool to do this. You could save the uploaded image and then check if the size is 500kb or less.

**Comment by ch-adnan** [comment]
Thanks dlemstra for your reply. I didn't find FileSize property/method on MagickImageCollection object and checking filesize after image save is not appropriate for me it is because based on FileSize I need to decide weather need to reduce the size of image before save.

**Comment by dlemstra** [comment]
You can get the size based on the size of the `byte array / stream` that was uploaded?

**Comment by ch-adnan** [comment]
Yes, that can be a way but I am more inclined to use Magick.NET feature i.e. FileSize Property.

**Comment by dlemstra** [comment]
You are getting a fileSize of zero because you are reading frames from an image. These frames don't have the fileSize of the combined image. I think i might want to remove the `FileSize` property of the MagickImage class to avoid this kind of confusion. Using the standard `System.IO` library should be sufficient to get the file size of an image.

**Comment by dlemstra** [comment]
You are getting 0 for the file size because the frames of the image are not aware of the size of the complete image. I have also decided to remove the FileSize property. This will be gone in the next release.
