### ISSUE TITLE
Thumbnail is not copied from exifData when using SetProfile

### ISSUE THREAD

**Issue by Kjelldor** [dlemstra/Magick.NET#1365]
### Magick.NET version

Magick.NET-Q8-AnyCPU v13.0.0.0

### Environment (Operating system, version and so on)

Windows 11 version 22H2, x64 based AMD processor

### Description

I noticed that the SetProfile function doesn't actually copy all the values to the new object correctly.

For one, the thumbnailValue is left behind, as are the values for the thumbnailLength and thumbnailOffset.
However, when looking a bit deeper, I found that my IExifProfile has 36 values, while my new ExifProfile after:
`img.SetProfile(profile);
var profile2 = img2.GetExifProfile();`
It suddenly only has 29 values and the thumbnailLength and offset are set to 0.
As you can see in the following screenshots when I debug, the value clearly changes after being set to a magickImage:
Profile before:
![example1](https://user-images.githubusercontent.com/64008787/227532346-8f8d5be1-e47a-46fc-a927-e60b34a296fd.png)
Profile after:
![example2](https://user-images.githubusercontent.com/64008787/227532390-0b396665-f016-4791-97db-91f618a62cd2.png)

### Steps to Reproduce

To reproduce this, you can use any two .jpg images. I have not yet tried this with other imageTypes, nor have I very extensively tested it. I have used a couple of .jpg images to see if it was something on my side, two of which you can download here to try for yourself: https://github.com/ianare/exif-samples I used the 'Canon_40D.jpg' and 'Kodak_CX7530.jpg' images from there. They did copy all other data from each other, except the information about the thumbnails.

If I have some time tomorrow I'll make sure to post an update concerning .png, .tiff and .bmp images.

**Comment by Kjelldor** [comment]
I just noticed this issue has been brought up before in issue #605 I will therefore close this issue, as duplicates seem unnecessary.

My apologies for the doubled information.

**Comment by dlemstra** [comment]
Thanks for closing this duplicate issue.
