### ISSUE TITLE
Bug: Error occured "negative image positions unsupported" when opening some TIFF images

### ISSUE THREAD

**Issue by Hiryshi** [dlemstra/Magick.NET#1367]
### Magick.NET version

12.2.0

### Environment (Operating system, version and so on)

Windows 10 21H2 (Build 19044.1288)

### Description

I am using [ImageGlass](https://github.com/d2phap/ImageGlass) as my image browser, but it throws errors on some TIFF images saying "negative image positions unsupported @ error/tiff.c/WhiteTIFFImage/3829".
The similar problem is reported in https://github.com/d2phap/ImageGlass/issues/1446 but the error code is not the same.

![image](https://user-images.githubusercontent.com/114552949/227679856-2c8e8a98-45d6-4e8b-bcfc-569e82572adb.png)

(Translation: *ImageGlass cannot open this image, because this file is likely broken or unsupported*)

And this is the image file I am using: 
[image.zip](https://github.com/dlemstra/Magick.NET/files/11067758/image.zip)

### Steps to Reproduce

1. Install ImageGlass
2. Open the image file
3. Bugged!

**Comment by dlemstra** [comment]
I cannot reproduce your issue with the latest version of Magick.NET so this library should probably be upgraded in ImageGlass. But @d2phap should probably wait for the `13.0.1` release that includes a fix for a font rendering issue. This will probably be release this weekend/early next week.

**Comment by Hiryshi** [comment]
Alright，I appreciate it，THX！
&nbsp;


Hiryshi
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dirk ***@***.***&gt;; 
发送时间: 2023年3月25日(星期六) 下午4:02
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dlemstra/Magick.NET] Bug: Error occured &quot;negative image positions unsupported&quot; when opening some TIFF images (Issue #1367)





 
I cannot reproduce your issue with the latest version of Magick.NET so this library should probably be upgraded in ImageGlass. But @d2phap should probably wait for the 13.0.1 release that includes a fix for a font rendering issue. This will probably be release this weekend/early next week.

**Comment by dlemstra** [comment]
This turned out to be a bit different. I did not notice the `WriteTIFFImage` earlier. Going to check if we can auto correct this in ImageMagick and change negative offsets to `0` and only raise a warning that will not be shown in ImageGlass.

**Comment by Hiryshi** [comment]
I look forward to the results of your processing.

**Comment by d2phap** [comment]
Okay I will update ImageGlass once the new version of MagickNET is released!

**Comment by d2phap** [comment]
ImageGlass 8.8.4.4 is released with MagickNET 13.0.1: https://github.com/d2phap/ImageGlass/releases/tag/8.8.4.4

**Comment by Hiryshi** [comment]
Problem solved，thank you！！
