### ISSUE TITLE
IsImage

### ISSUE THREAD

**Issue by MoeHamdan** [dlemstra/Magick.NET#1371]
### Is your feature request related to a problem? Please describe

Hello 

Thanks for this awesome library! 

I just wonder if it is possible to add a method that allows to check if the loaded file is image. This will help a lot, specifically when loading file/stream. Otherwise if the loaded file is not an image the resize method will throw an exception. It would be better to have the ability to check if the loaded content is an image.

Thanks

### Describe the solution you'd like

A  new method to MagickImage called IsImage().

**Comment by dlemstra** [comment]
I think you can already do this with `MagickFormatInfo.Create(byte[])`?

**Comment by jenokizm** [comment]
hi, good idea. I would also like to be able to call the validator before saving user images to the server. This would prevent getting of a malicious file instead of an image. perhaps `MagickFormatInfo.Create(byte[])` internally already validates the image. but now it's not clear.

**Comment by dlemstra** [comment]
You can do that? By first writing your stream to a byte array (or span) and call this method. You will then need to check if the result is a null or a format that you support?

**Comment by jenokizm** [comment]
@dlemstra, thanks for the answer. i think you mean something like this:
```
public async Task<IActionResult> SetAvatar(string userName, IFormFile formFile)
{
    try
    {
        if (formFile != null)
        {
            var image = new MagickImage(formFile.OpenReadStream());
            var info = image?.FormatInfo;
            if (info != null &&
                info.Format == MagickFormat.Png || info.Format == MagickFormat.Jpg || info.Format == MagickFormat.Jpeg)
            {
                var to = Path.Combine(_configuration.GetValue<string>("ImagesFolder"), userName + ".jpg");
                await SaveAvatarAsJpg128x128(image, to);
            }
        }
    }
    catch (Exception ex)
    {
        return View("Error", ex.Message);
    }

    return View();
}
```
in this approach, the downside is that I have to understand the image formats and enumerate them. I would like to just accept any image that is supported for saving to jpg

**Comment by dlemstra** [comment]
Yeah this directly loads the image. As I said before you should use `MagickFormatInfo.Create` and do something like this:

```C#
public async Task<IActionResult> SetAvatar(string userName, IFormFile formFile)
{
    try
    {
        if (formFile != null)
        {
            using var stream = formFile.OpenReadStream();
            var bytes = stream.ToArray();
            var info = MagickFormatInfo.Create(bytes);
            if (info != null &&
                (info.ModuleFormat == MagickFormat.Png || info.ModuleFormat == MagickFormat.Jpeg))
            {
                var to = Path.Combine(_configuration.GetValue<string>("ImagesFolder"), userName + ".jpg");
                using var image = new MagickImage(bytes);
                await SaveAvatarAsJpg128x128(image, to);
            }
        }
    }
    catch (Exception ex)
    {
        return View("Error", ex.Message);
    }

    return View();
}
```
