### ISSUE TITLE
Reading and saving out tiff image gets stretched

### ISSUE THREAD

**Issue by josbalcaen** [dlemstra/Magick.NET#1376]
### Magick.NET version

13.0.1

### Environment (Operating system, version and so on)

Windows 10. 

### Description

When reading the attached image and saving it back out to a tif image, the image gets stretched horizontally. When saving out to a png file the file is correct. Any idea?

### Steps to Reproduce

```
<PackageReference Update="Magick.NET-Q16-x64"  Version="13.0.1" />
```
```
using (MagickImage outputImage = new MagickImage("C:/input.tif"))
{
    outputImage.Write("C:/output.tif"); // Stretched result
    outputImage.Write("C:/output.png"); // Works
}
```
[input.zip](https://github.com/dlemstra/Magick.NET/files/11250587/input.zip)

**Comment by dlemstra** [comment]
That looks like a bug in the tif encoder. Not sure if this is an ImageMagick or a libtiff issue. I will need to investigate this and I will get back to you at a later moment.

I am pretty close to a new release and I don't think I will have time to investigate this before the release so it might take a while before a fix for this will become available.

**Comment by dlemstra** [comment]
Well you might be lucky. I found something that would delay the current release so that will give me some time to try and fix this in the next release.

**Comment by josbalcaen** [comment]
Great!
________________________________
