### ISSUE TITLE
MagickImage constructor consistently causing SIGSEGV (exit code 139) for SVG image

### ISSUE THREAD

**Issue by acidus99** [dlemstra/Magick.NET#1379]
### Magick.NET version

Magick.NET-Q8-AnyCPU

### Environment (Operating system, version and so on)

macOS 13.3.1. .NET SDK 7.0.202. M1 Apple Silicon

### Description

My .NET program is exiting with an exit code of 139 (Indicating a SIGSEGV signal) when calling the `new MagickImage(string)` constructor. This consistently happens with a specific SVG. Other images load fine. ImageMagick command line tools such as `convert` and `identify` can properly operate with this SVG image.

There is no exception to catch. Upon getting to the `new MagickImage()` the program immediately exits. I can reproduce this with the most basic program, as shown below: 

Example program and output:
```shell
$ cat Program.cs 
Console.WriteLine("Loading PNG");
ImageMagick.MagickImage image = new ImageMagick.MagickImage("512.png");
Console.WriteLine($"Complete: {image.Format}");

Console.WriteLine("Loading SVG");
image = new ImageMagick.MagickImage("inventory.svg");
Console.WriteLine($"Complete: {image.Format}");


$ dotnet run
Loading PNG
Complete: Png
Loading SVG
$ echo $?
139
$ 
```
The `echo $?` shows that exit code of the `dotnet` command is 139. The first PNG image successfully loads, which shows the Magick.NET is properly configured, the dynamic library is loaded, and is functioning. However when attempting to load the SVG, the SIGSEGV occurs.

### Steps to Reproduce

I'm including the source code for .NET console app in a ZIP file which reproduces the issue. The  `.csproj` file shows the Magick.Net nuget packages I'm importing (`Magick.NET.Core` and `Magick.NET-Q8-AnyCPU` both version 13.1.0). Also included is the `Program.cs` file and the 2 images (a PNG that loads file, and the SVG that causes the SIGSEGV). 

[Test Case.zip](https://github.com/dlemstra/Magick.NET/files/11355369/Test.Case.zip)

1. Unzip Test Case file
2. Ensure `TestIM.csproj` `Program.cs` `512.png` and `inventory.svg` are in a directory 
3. `cd` into that directory
4. run `dotnet run`

Expected result: program should print the following and exit with an exit code of 0.
```
Loading PNG
Complete: Png
Loading SVG
Complete: Svg
```
Actual result: program fails to progress to final `Console.WriteLine()`, exits with an exit code of 139.

**Comment by dlemstra** [comment]
I cannot reproduce this locally and I also cannot reproduce this inside a GitHub actions build on macOS. Maybe this is related to arm64? I don't own a mac so I cannot reproduce this so locally. I will need you to debug the issue and find what is causing this so we can resolve this. It might also be possible that inkscape is being used here and that this is causing a segfault.  You will get more information when you add this:

```C#
MagickNET.Log += (object sender, LogEventArgs arguments) =>
{
    Console.WriteLine(arguments.Message);
};
MagickNET.SetLogEvents(LogEvents.All);
```

**Comment by acidus99** [comment]
Hmmm. I just tried on an Intel Mac and didn't get an error. Thanks for the logging snippet. Let me dig in a bit more and get back to you

**Comment by acidus99** [comment]
Can't consistently reproduce, so closing for now
