### ISSUE TITLE
Convert jbig2 image to jpg

### ISSUE THREAD

**Issue by TonyWoo** [dlemstra/Magick.NET#138]
Hi, just try to convert a jbig2 image to a jpg, it throws below error message:
no decode delegate for this image format `JBIG2' @ error/constitute.c/ReadImage/509

how to add the decode delegate for the format JBIG2? thanks in advance.

**Comment by dlemstra** [comment]
There is no support for JBIG2 in ImageMagick and we are not aware of any libraries that we could use to read jbig2 files.
