### ISSUE TITLE
🐞 Reading .tiff files on alpine throws exception

### ISSUE THREAD

**Issue by seruss** [dlemstra/Magick.NET#1385]
### Magick.NET version

13.1.0

### Environment (Operating system, version and so on)

.net 6.0, linux alpine 3.17.3

### Description

Using Magick.NET-Q16-AnyCPU 13.1.0 to read .tiff files on windows works flawlessly, but when inside a docker container based on mcr.microsoft.com/dotnet/runtime-deps:6.0-alpine running linux alpine 3.17.3 on image.Read(stream) method  throws this exception:

> ImageMagick.MagickCoderErrorException: JPEG compression support is not configured. ' @ error/tiff.c/TIFFErrors/599
>    at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result) in  /_/src/Magick.NET/Native/NativeInstance.cs:line 57
>    at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(IMagickSettings1 settings, Byte[] data, Int32 offset, Int32 length) in /_/src/Magick.NET/Native/MagickImage.cs:line 6944
>    at ImageMagick.MagickImage.Read(Byte[] data, Int32 offset, Int32 length, IMagickReadSettings`1 readSettings, Boolean ping, String fileName) in /_/src/Magick.NET/MagickImage.cs:line 7570
>    at ImageMagick.MagickImage.Read(Byte[] data, IMagickReadSettings1 readSettings) in /_/src/Magick.NET/MagickImage.cs:line 4766

The last working version for this case is 12.3.0 after which tiff and other libs were updated. 

### Steps to Reproduce

using MagickImage read a .tiff file in alpine linux environment

**Comment by dlemstra** [comment]
Thanks for reporting this. This seems to be related to jpeg compression in the tiff coder. I just added a unit test that uses jpeg compression when writing tiff images and I am now seeing a failure in the unit tests. Not sure what is causing this but I will take a look at this later this week/weekend.

**Comment by dlemstra** [comment]
Made a fix in the build of Magick.Native and the unit test seems to be fixed. It no longer crashes the test run. This should be resolved in the next release.

**Comment by dlemstra** [comment]
A new release that includes a fix for this has been published. Can you give it another try with the latest release?
