### ISSUE TITLE
MagickImage FillColor, Font & FontPointsize Deprecated?

### ISSUE THREAD

**Issue by gitbrook** [dlemstra/Magick.NET#139]
Hi I just upgraded to Magick.NET 7.2.x from 7.0.x. However MagickImage FillColor, Font & FontPointsize show errors now are they Deprecated? What I use instead?

Thanks

**Comment by dlemstra** [comment]
Those properties have been moved to `MagickImage.Settings`

**Comment by gitbrook** [comment]
That works perfectly, Thanks.
