### ISSUE TITLE
DNG Grayscale file not supported. (only single color channel?) [error/dng.c/ReadDNGImage/572]

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#1391]
### Magick.NET version

13.1.2

### Environment (Operating system, version and so on)

Windows 11 22H2

### Description

Reported at https://github.com/d2phap/ImageGlass/issues/1575 with [sample files](https://github.com/d2phap/ImageGlass/files/11565227/Auto.Grayscale.DNG.ImageGlass.Issue.zip).

I also tried opening with MagickViewer, it shows the same issue:
![image](https://github.com/dlemstra/Magick.NET/assets/3154213/ff5e9f7f-8349-4152-b1df-a5defb8d116e)

### Steps to Reproduce

Copied from https://github.com/d2phap/ImageGlass/issues/1575:
1. (Scan file in vuescan using: Make Gray from: Auto)
2. Open DNG file (In my case scanned image from vuescan. Please read "Additional context")

### Actual behavior:
I've scanned images in auto grayscale in the raw DNG format (seemingly only giving one color channel) and when I try to open it in ImageGlass it gives this Error:
Magick.NET-Q16-HDRI-OpenMP-x64: No error '...' @ error/dng.c/ReadDNGImage/572
![image](https://github.com/d2phap/ImageGlass/assets/79905337/ace5e8ca-a299-44fd-8949-9ad11b9c118b)

At first I suspected the scanning software generating broken files, but they seem to open perfectly fine in Photoshop or Lightroom.
Color images in the same format from the same scanning software open fine. (Including grayscale from the r/g/b/infrared channels)

### Additional context:
Halfway into writing this issue, I found out the cause for this error was the Auto setting. Grayscale from manually selected color channels works fine. So it's probably a rather niche problem and low priority.
 
I've investigated this to some extend beforehand and there seem to be some differences in the Metadata. Namely the Auto settings one seemingly only having one color channel:
Auto Grayscale:
![Screenshot_62](https://github.com/d2phap/ImageGlass/assets/79905337/db984d2f-f332-48e5-a664-03fd3fb71a6f)
![image](https://github.com/d2phap/ImageGlass/assets/79905337/4e0fdb99-6213-4e63-8290-afd71deb85c8)

Grayscale from blue:
![Screenshot_63](https://github.com/d2phap/ImageGlass/assets/79905337/41c3a55d-15fc-4002-a569-4c12630506b8)
![image](https://github.com/d2phap/ImageGlass/assets/79905337/93452f88-2f31-4575-9d69-346de9e5b3e4)

**Comment by dlemstra** [comment]
Turns out it was quite easy to add support for this. You will be able to read those images with the next release.
