### ISSUE TITLE
CZI file not support

### ISSUE THREAD

**Issue by SinnoSong** [dlemstra/Magick.NET#1396]
### Magick.NET version

13.1.2

### Environment (Operating system, version and so on)

Windows 11 22H2

### Description

CZI file is not support.

### Steps to Reproduce

Use this code to convert `CZI` file to `jpg` 
```csharp
using (var magickImage= new MagickImage("C:\\Users\\sinno\\Downloads\\4-40-1.czi"))
{
	//magickImage.Quality = 100;
	magickImage.Write("C:\\Users\\sinno\\Downloads\\4-40-1.jpg");
}
```
But report:`no decode delegate for this image format `CZI' @ error/constitute.c/ReadImage/746`

**Comment by dlemstra** [comment]
There is no support for this format in ImageMagick and that is why this is not working. We will also probably not add support for this format.
