### ISSUE TITLE
How to use MagickImage in C# Azure Function? Reference errors related with Magick.Native-Q16-x**.dll

### ISSUE THREAD

**Issue by Gennady-G** [dlemstra/Magick.NET#1398]
**Update**: Resolved: used VS 2022 to build/pack/deploy to Azure and it worked (Installed Nuget Q16-AnyCPU)

----
### Magick.NET version

Magick.NET-Q16-AnyCPU

### Environment (Operating system, version and so on)

Magick.NET-Q16-AnyCPU, Azure Function App

### Description

Greetings!

Want to add Azure function that converts images. I successfully created it on my Win Server 2019 x64/Visual Studio 2022 Console App (.NET 6).  But I cannot compile it in Azure function: if I use these references ("Q16-AnyCPU"):
```
#r "Magick.NET.Core.dll"
#r "Magick.NET-Q16-AnyCPU.dll"  
```
then I get errors like 

> "Unable to load DLL 'Magick.Native-Q16-**x64**.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)"

or

> "Unable to load DLL 'Magick.Native-Q16-**x86**.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)"

![err-1-any-cpu-2023-06-07_200835](https://github.com/dlemstra/Magick.NET/assets/5569346/ef4022d8-0e84-4029-a83f-0176428bd625)

I found [how to upload custom DLLs to Azure](https://stackoverflow.com/questions/36559509/how-do-i-use-external-assemblies-with-microsoft-azure-function-apps)  (I found them in "runtimes" folder in my desktop project) and added these libraries to bin folder:

![folders-2023-06-07_205254](https://github.com/dlemstra/Magick.NET/assets/5569346/aa0ef240-6111-441c-adb4-6be478ac90b1)

![folder-2-2023-06-07_205500](https://github.com/dlemstra/Magick.NET/assets/5569346/2bb8e307-1fc5-4fa1-a499-252f5f3760ea)

and now here they are in Azure:

![err-7-2023-06-07_211710](https://github.com/dlemstra/Magick.NET/assets/5569346/30c9ac34-3e9e-4659-800e-208cbee96f2a)

 but when I reference them I get different error:

> \bin\Magick.NET-Q16-x86.Native.dll' could not be opened -- PE image doesn't contain managed metadata.

![err-5-2023-06-07_210456](https://github.com/dlemstra/Magick.NET/assets/5569346/298fff31-fd66-42a8-8917-7991403b1461)

I also tried to rebuild and replace DLLs for x86/x64 architecture, and tried to change x64/x86 in Azure Platform settings..

Here is a simplified code-snippet from my Azure Function (compilation fails when it meets MagickImage object ):

```
#r "Magick.NET.Core.dll"           
#r "Magick.NET-Q16-AnyCPU.dll"

//#r "Magick.Native-Q16-x86.dll"    // \bin\Magick.NET-Q16-x86.Native.dll' could not be opened -- PE image doesn't contain managed metadata.
//#r "Magick.Native-Q16-x64.dll"    // Unable to load DLL 'Magick.Native-Q16-x64.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
//#r "Magick.NET-Q8-x64.Native.dll" // \bin\Magick.NET-Q8-x64.Native.dll' could not be opened -- PE image doesn't contain managed metadata.
#r "Newtonsoft.Json"

using ImageMagick;
using System.Net;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;

public static async Task<IActionResult> Run(HttpRequest req, ILogger log)
{
    log.LogInformation("C# HTTP trigger function processed a request.");

    try{
        using (MagickImage image = new MagickImage())    // <--------  here is compilation error in Azure Function
        {
        }
    } catch(Exception ex) {
        log.LogWarning(ex.InnerException.Message);
    }

    return new OkObjectResult("sample");
}
```

How to reference MagickImage  and use it in C# project in Azure Function?..

### Steps to Reproduce

Created .NET 6 Azure Function, paste code-snippet there and try to Test/Run

**Comment by Gennady-G** [comment]
Greetings @dlemstra Dirk!
I edited my post in header but You are right - it is not clearly visible..

I used Visual Studio 2022 to build and publish to Azure and it worked (installed "Magick.NET-Q16-AnyCPU" as Nuget package there).

Best regards, Gennady

**Comment by dlemstra** [comment]
Oh sorry I missed that part :) Thanks for adding this for the next reader.

**Comment by Gennady-G** [comment]
> Oh sorry I missed that part :) Thanks for adding this for the next reader.

Thank You much for ImageMagick! :)
