### ISSUE TITLE
Issues with GrantEveryoneReadAndExecuteAccess()

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#14]
I ran into a weird issue with the GrantEveryoneReadAndExecuteAccess().

I deployed my application on a cloud service instance (web role) in Azure (Windows Server 2012 R2) with Magick.NET 7.0.1.101 (AnyCPU).
Magick.NET was unable to write the dll Magick.NET-Q16-x64.dll into the "Magick.NET.net40-client.7.0.1.101" directory because it throwed a System.UnauthorizedAccessException.

When checking the permissions, Read and Execute rights were granted for Everyone on the "Magick.NET.net40-client.7.0.1.101" directory and nothing else.

Do you need the Magick.NET.AnyCPU.NativeLibraryLoader.cs/GrantEveryoneReadAndExecuteAccess() method ? It seems the CreateDirectory() method automatically inherits permissions from the parent directory.
Or could you use this kind of logic, instead of granting rights for everyone ? http://stackoverflow.com/a/3626554

```
DirectoryInfo dInfo = new DirectoryInfo(strFullPath);

DirectorySecurity dSecurity = dInfo.GetAccessControl();

//check off & copy inherited security setting 
dSecurity.SetAccessRuleProtection(true, true); 

dInfo.SetAccessControl(dSecurity);
```

**Comment by dlemstra** [comment]
The reason that I added this was because the file is always written to the same location. When multiple application pools need the library they can run into permission problems. If you have a better idea to resolve this issue then please let me know. I don't know if inheriting permissions from the parent folder would resolve this.

You can avoid this behavior by setting `MagickAnyCPU.CacheDirectory`.

**Comment by DavidRouyer** [comment]
In my opinion, you shouldn't do that:

1. You don't give any write permissions to the user who executes the application, which can cause an UnauthorizedAccessException on some constrained environment like Azure.

2. You're giving Read and Execute permissions to Everyone (it includes the Guest account, and for example, an account with no rights at all). It seems dangerous.

3. You're setting permissions and developers don't know it, and without their consent.

What you can do:

- Remove the GrantEveryoneReadAndExecuteAccess() method. If you do a CreateDirectory(), I think the new directory inherits the permissions of the parent folder automatically, and it's fine. If a developer or a sysadmin don't like the permissions granted on the Temp directory, he can add or remove permissions himself.

- If you want to keep the current behavior, remove GrantEveryoneReadAndExecuteAccess() by default and add a parameter on MagickAnyCPU. Something like: MagickAnyCPU.GrantPermissions = true; (false by default).

**Comment by dlemstra** [comment]
I will need to keep the current behavior because I know of at least one company that uses this. I do agree with you that it will be better to add a property like `GrantPermissions` to the `MagickAnyCPU` class. I will make sure this will be changed in the next release.

**Comment by dlemstra** [comment]
Your issue has been resolved with the following commit: https://github.com/dlemstra/Magick.NET/commit/f1d2e7236dd3ccf99df48d49a5b4126e52b50d99
