### ISSUE TITLE
psd new blank layer missing

### ISSUE THREAD

**Issue by zongminshen** [dlemstra/Magick.NET#140]
I would like to export layers of psd file into pictures.
Usually it’s work fine.
However,when the psd file exists a new blank layer,it will go wrong.
I'm using the following code (C#):
using(MagickImageCollection collection = new MagickImageCollection(path))
{
//do something I want,such as export picture
}
MagickImageCollection don‘t contains the new blank layer.
Is there a way to slove it.
thanks in advance.

**Comment by dlemstra** [comment]
Could you share the PSD that has this issue?

**Comment by zongminshen** [comment]
[psd_file.zip](https://github.com/dlemstra/Magick.NET/files/1605249/psd_file.zip)
It contains two psd file.
①New.psd:it contains two layers,one is new blank layer————it has this problem.
②New-change.psd:do something on New.psd——————it works fine.
The Photoshop i used is Adobe Photoshop cs5(64bit)

**Comment by dlemstra** [comment]
Your new.psd contains two layers but one of the layers has a width and height that are both zero. I guess this is the blank layer that you are missing. ImageMagick does not support images that are 0x0 so we skip/ignore that layer.

**Comment by zongminshen** [comment]
Thanks a lot for helping me solve this problem.
