### ISSUE TITLE
Reading PDF from HttpRequest.Body

### ISSUE THREAD

**Issue by dmitriyett** [dlemstra/Magick.NET#141]
Hello, I'm trying to write simple web API using ASP Net Core to convert files from one format to another. It is pretty simple, you post multipart request with all the files to convert and it returns all of them converted.

The problem is that I always receive `MagickDelegateErrorException` when I'm trying to read pdf file from the multipart stream (I can't remember exact class name, I can provide it a bit later if needed). Code:
```C#
using (var images = new MagickImageCollection(multipartStream, new MagickReadSettings { Format = MagickFormat.Pdf }))
```
throws exception with following details:
```
MagickDelegateErrorException: PDFDelegateFailed `[ghostscript library 9.22] -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" "-s 1000 OutputFile=D:/Users/Dmitriy.Ett/AppData/Local/Temp/1/magick-12128-AaWZzv4D9mP%d" "-fD:/Users/Dmitriy.Ett/AppData/Local/Temp/1/magick-12128XqApAx6AXuoE" "-fD:/Users/Dmitriy.Ett/AppData/Local/Temp/1/magick-12128HFzDAuJODiYj": (null)' @ error/pdf.c/ReadPDFImage/794
```

Stack trace:
```
ImageMagick.MagickDelegateErrorException: PDFDelegateFailed `[ghostscript library 9.22] -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72"  "-sOutputFile=D:/Users/Dmitriy.Ett/AppData/Local/Temp/1/magick-12128-AaWZzv4D9mP%d" "-fD:/Users/Dmitriy.Ett/AppData/Local/Temp/1/magick-12128XqApAx6AXuoE" "-fD:/Users/Dmitriy.Ett/AppData/Local/Temp/1/magick-12128HFzDAuJODiYj": (null)' @ error/pdf.c/ReadPDFImage/794
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImageCollection.AddImages(Stream stream, MagickReadSettings readSettings, Boolean ping)
```

But If I try to open same file on the server side via
```C#
using (var images = new MagickImageCollection(File.Open(fileName), new MagickReadSettings { Format = MagickFormat.Pdf }))
```

everything works ok.

Unfortunately I do not have a sample for now, but I will prepare it in several hours.

Could you please assist me with that?

**Comment by dlemstra** [comment]
I will wait till you have your sample ready. I can use that and a debugger to quickly figure out what is going on. Are you using the latest version of Magick.NET?

**Comment by dmitriyett** [comment]
[sample repo](https://github.com/dmitriyett/PdfConversionIssueSample)
I'm using Magick.NET q16 any CPU v7.2.1
Ghostscript (added in the sample) v9.22
Test pdf is also in sample.

To run it, run API first, then start debugging session for client proj.

**Comment by dlemstra** [comment]
Thanks for the repo 👍 I can reproduce your issue. Will now need to figure out what causes this. Will get back to you when I know more.

**Comment by dmitriyett** [comment]
@dlemstra thx for the help!
I've also tried different file formats (tiff and jpg). They worked fine. And then I tried to copy request stream to memory stream and use it instead:
```C#
var memoryStream = new MemoryStream();
await section.Body.CopyToAsync(memoryStream);
memoryStream.Seek(0, SeekOrigin.Begin);
using (var images = new MagickImageCollection(memoryStream))
{
    Console.WriteLine("I work!");
}
```
and it worked
So it seems the problem is with `Microsoft.AspNetCore.WebUtilities.MultipartReaderStream` specifically

Would be glad if it helps.
Thanks.

**Comment by dlemstra** [comment]
The problem is that your stream is a not a memorystream and is not seekable. There was a check for this inside ImageMagick but I broke it at some point during my refactoring. I just pushed a patch for this to the ImageMagick repository. Will try to publish a new release later today or tomorrow to resolve your issue.

**Comment by dlemstra** [comment]
Just published the new release. Please let me know if this resolves your issue.

**Comment by zongminshen** [comment]
Thanks a lot,the problem has been solved

**Comment by dmitriyett** [comment]
Thanks a lot, it works now.
PS: sorry for late reply.
