### ISSUE TITLE
PerceptualHash Performance

### ISSUE THREAD

**Issue by HEIC-to-JPEG-Dev** [dlemstra/Magick.NET#1413]
### Magick.NET version

13.1.3

### Environment (Operating system, version and so on)

Windows 11 x64

### Description

There seems to be a performance issue constructing 

I have the hash of 4,000 files, from MagickImage.PerceptualHash().ToString();

I then itterate through them and compare the hash distances, distance = pHash1.SumSquaredDistance(pHash2);

I found that to be incredibly slow - over 30 seconds. This is on very modern hardware.

I thought it was originally the "distance = pHash1.SumSquaredDistance(pHash2);" that was the performanc issue, but it turns out to be this code :-

var pHash1 = new PerceptualHash(hash1);
var pHash2 = new PerceptualHash(hash2);

Those two lines, itterated 4,000 times, using a has string generated by the PerceptualHash itself takes 31s.

I wouldn't expect this as it's a basic constructor

### Steps to Reproduce

generate a hash string using hash = MagickImage.PerceptualHash().ToString();

loop 4,000 times and generate two perceptualHash classes using the string from above.
var pHash = new PerceptualHash(hash);

The constructor code looks simple enough:
```
    /// <summary>
    /// Initializes a new instance of the <see cref="PerceptualHash"/> class.
    /// </summary>
    /// <param name="hash">The hash.</param>
    public PerceptualHash(string hash)
      : this()
    {
        Throw.IfNullOrEmpty(nameof(hash), hash);
        Throw.IfFalse(nameof(hash), hash.Length == 210, "Invalid hash size.");

        _channels[PixelChannel.Red] = new ChannelPerceptualHash(PixelChannel.Red, hash.Substring(0, 70));
        _channels[PixelChannel.Green] = new ChannelPerceptualHash(PixelChannel.Green, hash.Substring(70, 70));
        _channels[PixelChannel.Blue] = new ChannelPerceptualHash(PixelChannel.Blue, hash.Substring(140, 70));
    }
```

**Comment by dlemstra** [comment]
That "basic constructor" needs to parse the specified hash and that uses `Math.Pow` what is probably causing this delay, not sure what could be done to improve this.
