### ISSUE TITLE
PNG Read Exception

### ISSUE THREAD

**Issue by zaocaoer** [dlemstra/Magick.NET#1416]
### Magick.NET version

Magick.NET.Core 13.1.3

### Environment (Operating system, version and so on)

Windows 11, Linux

### Description

Read Exception: [https://gd1.alicdn.com/imgextra/i2/2950008834/O1CN01TlE3QX2F81Ta5AeeN_!!2950008834.png](url)

ImageMagick.MagickCoderErrorException:“Read Exception `C:/Users/zaoca/AppData/Local/Temp/magick-D4l7Z2MOhlD_KxU6uCJI2_wszmyo16f4' @ error/png.c/MagickPNGErrorHandler/1492”

![O1CN01TlE3QX2F81Ta5AeeN_!!2950008834](https://github.com/dlemstra/Magick.NET/assets/121427967/ab76ffeb-e520-4c5c-9851-b159b531b711)

### Steps to Reproduce

var url = "https://gd1.alicdn.com/imgextra/i2/2950008834/O1CN01TlE3QX2F81Ta5AeeN_!!2950008834.png";
using var image = new MagickImage(url);

**Comment by dlemstra** [comment]
Your PNG file is missing a CRC and that is why the library that we use to read PNG fails to read the image and throws this exception. You will need to fix your file.

**Comment by zaocaoer** [comment]
Others tools can read this file normally.
Is there any setting to ignore this CRC issue?

**Comment by dlemstra** [comment]
There is an option to ignore the value of the CRC but the problem with this file is that it does not contain a CRC so you cannot read it with ImageMagick.

**Comment by zaocaoer** [comment]
Got it. Thanks.
