### ISSUE TITLE
`MagickImage.ToBitmapWithDensity()` throws `Parameter is not valid` exception

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#1419]
### Magick.NET version

13.2.0

### Environment (Operating system, version and so on)

Windows 11 22H2

### Description

Reported from https://github.com/d2phap/ImageGlass/issues/1622

When reading this file with `.ToBitmapWithDensity()`
![](https://user-images.githubusercontent.com/50766353/256815987-31008961-f200-4f85-b250-3e54e8d747ed.jpg)

It throws exception on the `bitmap.SetResolution`:
![image](https://github.com/dlemstra/Magick.NET/assets/3154213/59b8ff25-edbf-4145-af7d-b425893bca7c)

```log
   at System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi)
   at ImageMagick.IMagickImageExtentions.SetBitmapDensity[TQuantumType](IMagickImage`1 image, Bitmap bitmap)
   at ImageMagick.IMagickImageExtentions.ToBitmap[TQuantumType](IMagickImage`1 self, Boolean withDensity)
   at ImageMagick.IMagickImageExtentions.ToBitmapWithDensity[TQuantumType](IMagickImage`1 self)
```

I would be nice if MagickNET can ignore the error!

### Steps to Reproduce

```cs
using var imgM = new MagickImage();
imgM.Read(@"256815987-31008961-f200-4f85-b250-3e54e8d747ed.jpg", new MagickReadSettings());

var aaa = imgM.ToBitmapWithDensity(); // 🫠
```

![image](https://github.com/dlemstra/Magick.NET/assets/3154213/916dbeda-3feb-45a1-adb1-f73544a1065e)

**Comment by dlemstra** [comment]
Thanks for reporting this. This will be fixed in the next release.

**Comment by dlemstra** [comment]
A new release that includes a fix for this has been published.
