### ISSUE TITLE
JpegOptimizer failing when using a memorystream

### ISSUE THREAD

**Issue by allensanborn** [dlemstra/Magick.NET#142]
I'm having issues when I try to use the JpegOptimzer with a MemoryStream. 

I have a CMS that stores all the images in database so I'd prefer not having to deal with the file system unless I need to. 

At this moment it looks like the MemoryStream parameter doesn't work. I either get "Unable to decompress the jpeg file." or the file size remains unmodified. It is possible that when the file is unmodified that it is already 'optimal' but that seems a bit unlikely. 

I've created a little test console program with three of the images that exhibit this behavior. I was hoping to do more digging into this before reaching out but I ran into some issues and time constraints trying to get the Magick.NET solution to a point where I could troubleshoot this. 

Please let me know if I can provide you with any more information. 
[MemoryStreamTest.zip](https://github.com/dlemstra/Magick.NET/files/1616970/MemoryStreamTest.zip)

**Comment by dlemstra** [comment]
Sorry for the lat reply but it seems there is a mistake in your code:

```C#
using (var i = new MagickImage(ms))
{
    var jpegOptimizer = new JpegOptimizer();
    try
    {
        var before = ms.Length;
        jpegOptimizer.Compress(ms);
        var after = ms.Length;
        var diff = before - after;
    }
    catch (Exception ex)
    {
    }
}
```

You are first reading the `MemoryStream` in a `MagickImage` and that will move the `Position` to the end of the stream. Then you try to `Compress` but there are no more bytes to be read. Your issue will be resolved when you remove the construction of the `MagickImage`. Not sure why you added that though, you don't need it.

**Comment by AllenSanbornBroadridge** [comment]
It is a trimmed down chunk of code. I take the byte array, create a memorystream, create the MagickImage object and then I strip metadata, resize, adjust quality, potentially grayscale it and so on. The last step is through all that logic is that I compress the image. I was trying to remove all unnecessary code but that seemed to have possibly made it more confusing. 
I didn't want to have to do all that manipulation muddying up the sample. 
I'm glad it is my error. That is a rather simple problem to solve ;)
