### ISSUE TITLE
Universal Nuget package

### ISSUE THREAD

**Issue by michaelakin** [dlemstra/Magick.NET#1422]
### Is your feature request related to a problem? Please describe

Please create a universal Nuget package.  This will help when developing on one type of machine, but deploying to another type of machine.  

For Example:  I use a Windows PC, with a 64 Bit Windows 11 operating system.  But I need to deploy my code to an AWS Linux 64 bit machine.

  

### Describe the solution you'd like

A universal Nuget package that will handle everything for a certain bit depth.

Also, for an image newbie, why would I want Q8 vs Q16 ? 

### Describe alternatives you've considered

I looked into a pre-build option to change out the nuget packages, but not sure that would work.

**Comment by michaelakin** [comment]
Sorry for any confusion.   I see you do have some AnyCpu Nuget packages and I am sure that will work for the scenario above.

**Comment by dlemstra** [comment]
No worries, I understand this can be confusing. Do you have any suggestions for documentation improvements to make this more clear? 

And the 64-bit version of the package should also work for your situation. That should run on 64-bit windows, mac and linux.

**Comment by michaelakin** [comment]
I reviewed the documentation and now that I have some familiarity with this, I think you have everything there.  I need to slow down, read the documentation and not just skip to the downloads and then get overwhelmed with the options.
