### ISSUE TITLE
MagickImageCollection.WriteAsync() blocks the parent thread.

### ISSUE THREAD

**Issue by Jeric-X** [dlemstra/Magick.NET#1426]
### Magick.NET version

Magick.NET-Q16-AnyCPU Version="13.2.0"

### Environment (Operating system, version and so on)

Windows 11 22H2

### Description

![image](https://github.com/dlemstra/Magick.NET/assets/10058586/bf9adb3f-37b0-4df9-87ca-77ba87146763)
button1_Click makes GUI irresponsible.

### Steps to Reproduce

[WinFormsApp1.zip](https://github.com/dlemstra/Magick.NET/files/12326990/WinFormsApp1.zip)
Here is the sample sln

**Comment by dlemstra** [comment]
You should add `.ConfigureAwait(false)` to avoid blocking the main thread.

**Comment by Jeric-X** [comment]
I changed code to this, still blocking main thread.
![image](https://github.com/dlemstra/Magick.NET/assets/10058586/6d222a81-e1fb-4c2f-97f4-70d76bc82c12)

**Comment by dlemstra** [comment]
I don't think you can make the `button1_click` async. The method was no longer blocking before you moved the read inside that method. Your questions are related to how .NET works and are not specific to this library.

p.s. Don't post screenshots of code but create a code block in mark down instead.

**Comment by Jeric-X** [comment]
Sorry for posting pictures.
It's not about whether button1_Click is async.
Go back to the problem. I expect the following code never blocks the main thread, The four `Trace.WriteLine()` calling will output string immediately. Async tasks should do real works in backgound.
When I exactly run the program,  `WriteAsync before` immediately printed. Waiting a few seconds(with GUI irresponsible), `WriteAsync after`, `Delay before`, `Delay after` printed nearly the same time. 
So is this the right performance? shouldn't `WriteAsync` the same as `Task.Delay`?

```
        private void button1_Click(object sender, EventArgs e)
        {
            using var image = new MagickImageCollection("test-animetedImage.webp");
            image.Coalesce();

            Trace.WriteLine("WriteAsync before");
            image.WriteAsync("test-animetedImageOut.gif", MagickFormat.Gif);
            Trace.WriteLine("WriteAsync after");

            Trace.WriteLine("Delay before");
            Task.Delay(5000);
            Trace.WriteLine("Delay after");
        }
```

**Comment by Jeric-X** [comment]
Line 2162 should be wrapped in a task as well.
Line 2163 writes byteArray to a file. I think the time-consuming converting work must be done in line 2162 but it is not async.
https://github.com/dlemstra/Magick.NET/blob/733b2be754487435e763953638e73d728f1437d3/src/Magick.NET/MagickImageCollection.cs#L2145-L2170

**Comment by dlemstra** [comment]
Your code example is not doing `async` calls correctly and that is why you are seeing that behavior. I don't want to wrap line `2162` in a `Task` to run this in a separate thread. But maybe I should add a remark to make it more clear that only the IO part is done asynchronous.

**Comment by Jeric-X** [comment]
My code example is to show that part of the `MagickImageCollection.WriteAsync()` is time-consuming and synchronous. 
It seems you designed this. Issue is done
If it is designed this issue can be closed. It is necessery

**Comment by Jeric-X** [comment]
My code example is to show that part of the MagickImageCollection.WriteAsync() is time-consuming and synchronous.
It seems you designed this. Issue is done.
