### ISSUE TITLE
Magick.Settings.Compression.Get throws EntryPointNotFoundException

### ISSUE THREAD

**Issue by b9chris** [dlemstra/Magick.NET#143]
The latest version of ImageMagick is giving me the following exception, and only in Production. Previous versions worked fine:

EntryPointNotFoundException: Unable to find an entry point named 'MagickSettings_Compression_Get' in DLL 'Magick.NET-Q8-x64.Native.dll'. at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_Compression_Get(IntPtr instance) at ImageMagick.MagickSettings.NativeMagickSettings.get_Compression() at ImageMagick.MagickSettings..ctor() at ImageMagick.MagickImage..ctor() 

On this line of code:

Magick.Settings.Compression = Compression.JPEG;

Prior code set Compression more directly, but, that seems to have changed in the latest version. But it's strange this only throws in Production.

As a workaround, I've stopped setting Compression entirely; setting Format to MagickFormat.Jpeg seems to be enough to ensure a properly compressed JPEG file is emitted without it.

**Comment by dlemstra** [comment]
Is it possible that you have an incorrect version `Magick.NET-Q8-x64.Native.dll` in your production environment? The file version should be `7.3.0.0`.

**Comment by b9chris** [comment]
A fine question. I honestly don't know where I'd look for this. It certainly isn't in the GAC, and it's not in my Bin folder - the only related file there is what I'd expect: Magick.NET-Q8-AnyCPU.dll

Where would you expect that file to appear?

**Comment by dlemstra** [comment]
I don't understand which version of `Magick.NET-Q8-x64.Native.dll` is being used. I downloaded the library from NuGet and checked the exports and they seem to be correct. Maybe something like FileMon can tell you where it tries to load the library from? The library should be in the temporary directory or in the folder that you specified with `MagickAnyCPU.CacheDirectory`.

**Comment by b9chris** [comment]
OK perfect thank you. Dug into our temp dir, and the file in use is:

Magick.NET-Q8-x64.Native.dll
1/9/2018 5:24pm
7.3.0.0

**Comment by dlemstra** [comment]
What happens when you run `dumpbin /exports Magick.NET-Q8-x64.Native.dll` on that file. Do you see a line that contains `MagickSettings_Compression_Get`

**Comment by robisoft** [comment]
I have the same error with the 7.4.0.0 version:

Unable to find the entry point 'MagickSettings_Compression_Get' nella DLL 'Magick.NET-Q16-x64.Native.dll'. in ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_Compression_Get(IntPtr instance) in ImageMagick.MagickSettings.NativeMagickSettings.get_Compression() in ImageMagick.MagickSettings..ctor() in ImageMagick.MagickImage..ctor()

Have you found the mistake?

**Comment by dlemstra** [comment]
I cannot reproduce this issue. Maybe it is related to your environment? Would it be possible for either of you to create a Docker image that I can use to reproduce the issue?

@robisoft Is this also a production only issue for you?

**Comment by dlemstra** [comment]
@robisoft and @b9chris Can you give it another try with version 7.4.4.0?

**Comment by medokin** [comment]
I had a similar issue with `EntryPointNotFoundException` and also only in production.
Restarting the Azure instance resolved it.

**Comment by dlemstra** [comment]
@robisoft, @b9chris and @medokin Have you tried the latest version to test if that resolves your issue?
