### ISSUE TITLE
Slowdown in MagickImage.ToByteArray on arm64 Mac

### ISSUE THREAD

**Issue by schnoberts1** [dlemstra/Magick.NET#1447]
### Magick.NET version

Magick.NET-Q8-arm64 13.1.2

### Environment (Operating system, version and so on)

arm64, Mac M1, .NET 7.0.11/7.0.401

### Description

```
            using var image = new MagickImage(stream, new MagickReadSettings { Format = MagickFormat.Psd });
            image.ToByteArray();
```

takes minutes in 13.1.2 when it used to take seconds for a 3k/4k file of reasonable image complexity. All the additional time is in ToByteArray. In 13.1.2 there's an overflow exception and in 13.1.0 the speed is as I expect.  

I scaled the image down so I can attach it (if I can work out how to do that) and the perforce is 25ms for 13.1.0 and 4123ms for 13.1.2. Note: the slow down is less extreme when there is less detail in the image.

### Steps to Reproduce

Create a PSD (RGB/8 is fine), make it say 1000 x 1000 and ensure it has some detail in it. Time the code above. Increase the image size and complexity to make the timing difference larger. My Mac has 64GB of RAM and an Apple M1 Max processor.

**Comment by dlemstra** [comment]
Have you tested this with the most recent version?

**Comment by schnoberts1** [comment]
Yes, same issue. On 4 Oct 2023, at 06:49, Dirk Lemstra ***@***.***> wrote:﻿
Have you tested this with the most recent version?

**Comment by dlemstra** [comment]
Do you get the "old" performance when you do this instead:

```C#
using var stream = new MemoryStream();
image.Write(stream);
var bytes = stream.ToArray();
```

**Comment by schnoberts1** [comment]
Writing the image into a MemoryStream and then getting the array takes < 1ms on both new and old version.

**Comment by dlemstra** [comment]
I really wonder what kind of measurements you are using. This is what was happening inside the old version of `ToByteArray` and that should not be less than 1ms when you are writing a PSD image. Can you create a small project with an image on GitHub that reproduces what you are seeing?

**Comment by schnoberts1** [comment]
```
namespace Ezen.Uploader.Tests;

using ImageMagick;
using System.IO;
using System.Diagnostics;
public class Tests
{
    [SetUp]
    public void Setup()
    {
    }

    [Test]
    public void Test1()
    {
        FileStream stream = File.OpenRead("/Users/andy/code/ezen/ezen-uploader/JPN485.psd");
        using var image = new MagickImage(stream, new MagickReadSettings { Format = MagickFormat.Psd });

        var s = Stopwatch.StartNew();
        var ba = image.ToByteArray();        
        Console.WriteLine($"ToByteArray {s.ElapsedMilliseconds}ms {ba.Length} bytes");

        s = Stopwatch.StartNew();
        using var mstream = new MemoryStream();
        image.Write(mstream);
        var bytes = mstream.ToArray();
        Console.WriteLine($"ToArray {s.ElapsedMilliseconds}ms {bytes.Length} bytes");

        Assert.Pass();
    }
}
```
csproj snippet:
```
  <Choose>
    <When Condition="'$(Platform)' == 'x64'">
      <ItemGroup>
        <PackageReference Include="Magick.NET-Q8-x64" Version="13.3.0"/>
      </ItemGroup>
    </When>
  </Choose>
  <Choose>
    <When Condition="'$(Platform)' == 'arm64'">
      <ItemGroup>
        <PackageReference Include="Magick.NET-Q8-arm64" Version="13.3.0"/>
      </ItemGroup>
    </When>
  </Choose>
```
Run test with 13.3.0
```
(base) andy@ice ezen-uploader % dotnet test -c release Ezen.Uploader.Tests  -p:Platform=arm64 -l console
  Determining projects to restore...
  All projects are up-to-date for restore.
  Ezen.Uploader -> /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader/bin/arm64/release/net7.0/Ezen.Uploader.dll
  Ezen.Uploader.Tests -> /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader.Tests/bin/arm64/release/net7.0/Ezen.Uploader.Tests.dll
Test run for /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader.Tests/bin/arm64/release/net7.0/Ezen.Uploader.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.1 (arm64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
ToByteArray 4167ms 7842052 bytes
ToArray 22ms 7842052 bytes
```

Run test with 13.1.0
```
(base) andy@ice ezen-uploader % dotnet test -c release Ezen.Uploader.Tests  -p:Platform=arm64 -l console
  Determining projects to restore...
  Restored /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader.Tests/Ezen.Uploader.Tests.csproj (in 148 ms).
  Restored /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader/Ezen.Uploader.csproj (in 148 ms).
  Ezen.Uploader -> /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader/bin/arm64/release/net7.0/Ezen.Uploader.dll
  Ezen.Uploader.Tests -> /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader.Tests/bin/arm64/release/net7.0/Ezen.Uploader.Tests.dll
Test run for /Users/andy/code/ezen/ezen-uploader/Ezen.Uploader.Tests/bin/arm64/release/net7.0/Ezen.Uploader.Tests.dll (.NETCoreApp,Version=v7.0)
Microsoft (R) Test Execution Command Line Tool Version 17.7.1 (arm64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
ToByteArray 27ms 7842052 bytes
ToArray 23ms 7842052 bytes
```

The output of ```file``` on the DLLs is ```PE32+ executable (console) Aarch64 Mono/.Net assembly, for MS Windows```

I'll pull this into a project if this isn't enough, let me know. I'll send you the image.

**Comment by schnoberts1** [comment]
My mistake, not 1ms, 23ish

**Comment by schnoberts1** [comment]
... just so I can follow on at home:

So versions that perform differently are post a change where ToByteArray was changed to look a lot like the Stream writer: 
```
   public byte[] ToByteArray()
    {
        _settings.FileName = null;

        using var wrapper = new ByteArrayWrapper();
        var writer = new ReadWriteStreamDelegate(wrapper.Write);
        var seeker = new SeekStreamDelegate(wrapper.Seek);
        var teller = new TellStreamDelegate(wrapper.Tell);
        var reader = new ReadWriteStreamDelegate(wrapper.Read);

        _nativeInstance.WriteStream(_settings, writer, seeker, teller, reader);

        return wrapper.GetBytes();
    }
```
... what you are alluding to is the memory stream is how ToByteArray used to look:
```
            using var stream = new MemoryStream();
            Write(stream);
            return stream.ToArray();
```

and Write looks a lot like what ToByteArray was changed to:
```
            Throw.IfNull(nameof(stream), stream);

            _settings.FileName = null;

            using var wrapper = StreamWrapper.CreateForWriting(stream);
            var writer = new ReadWriteStreamDelegate(wrapper.Write);
            ReadWriteStreamDelegate? reader = null;
            SeekStreamDelegate? seeker = null;
            TellStreamDelegate? teller = null;

            if (stream.CanSeek)
            {
                seeker = new SeekStreamDelegate(wrapper.Seek);
                teller = new TellStreamDelegate(wrapper.Tell);
            }

            if (stream.CanRead)
                reader = new ReadWriteStreamDelegate(wrapper.Read);

            _nativeInstance.WriteStream(_settings, writer, seeker, teller, reader);
```

I have to agree, these are very very similar things.

**Comment by schnoberts1** [comment]
I ran both versions through a profiler. In version 13.3.0 for my test code it's spending a lot of time in Seek because Seek is spending its time calling System.Array.Resize 7269 times. I can't find any calls to Resize in the profile for 13.1.0.

**Comment by schnoberts1** [comment]
... this also explains why the slow down is related to the complexity of the image (something I noticed yesterday). If the image is entirely white (one of my test cases that didn't exhibit as bad a slowdown) then perhaps it's uncompressed in a very small number of chunks as the information content is low, so the array size is grown to size in a small number of chunks. 

Do you have full instructions on how to setup the entire environment to build the native and .NET wrapper and run functional and performance tests? If so, I can always take a run at fixing this behaviour in the next few week. Warning:  I've only been programming .NET C# for 4 weeks now part time. :)

**Comment by schnoberts1** [comment]
I thought I had shared an image but didn’t so I will do that ASAP. On 5 Oct 2023, at 20:31, Dirk Lemstra ***@***.***> wrote:﻿
Thanks for all the research. I was suspecting this was the issue but I was not sure about it. Would it be possible to share an image that I can use to reproduce the issue? I might be able to find a workaround for this myself then. Maybe this would work ResizeBytes(newOffset + BufferSize);?

**Comment by schnoberts1** [comment]
I would imagine so. It'd likely reduce the number of Resize calls which would also have the handy feature of reducing the chances of heap fragmentation requiring the whole array is moved in memory as part of resizing so it can maintain a contiguous chunk of memory (assuming that's how C# arrays work, I've only been coding in C# for less than a month part time so I know very little.

I guess given the Resize is currently exact you'll be breaking an assumption (I imagine) that _bytes is always the right size at the end of Seek(). 

Another option would be to not resize the array at all at that point. You only need the array resized when something happens, e.g. someone reads from the Seek'd position or writes from the Seek'd position. In this model you check _bytes length vs _offset when you read or write and not in Seek. Since Write is writing from a buffer you then get the nice feature that Resizes happen in _buffer length jumps. In Read I guess you would have to resize by ```count``` but reading un-written memory seems like an odd use-case anyway.

**Comment by schnoberts1** [comment]
I've just checked the C# Memory Stream implementation and it takes the approach I describe above, which is why that performs in a more consistent fashion. Look at Seek() in https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/memorystream.cs.

**Comment by dlemstra** [comment]
Could you please share a test file I could use for this? I would like to investigate this but having no test file is blocking me.

**Comment by schnoberts1** [comment]
I’ve been replying to these emails with an attachment and it clearly doesn’t seem to be getting through so I’ve put it on google drive here: https://drive.google.com/file/d/1zInJmMzMJwTZRNwubyyrhynvgFo5ucWP/view?usp=share_link

Please let me know when you have this so I can take it down.

**Comment by schnoberts1** [comment]
...sent to the email address on your githib profile

**Comment by dlemstra** [comment]
Thanks for the file and I can see what is happening. I really think I should simplify the implementation of the `ByteArrayWrapper`.

**Comment by dlemstra** [comment]
I made some changes to the implementation and this should fix the performance again in the next release.

**Comment by schnoberts1** [comment]
That’s great, it’ll let me upgrade :) thank you. On 16 Oct 2023, at 19:41, Dirk Lemstra ***@***.***> wrote:﻿
I made some changes to the implementation and this should fix the performance again in the next release.
