### ISSUE TITLE
Access Violation when using Magick inside Task.Run()

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#145]
When I try to use Magick inside await/async scenario using `Task.Run()`, everything proceeds normally, and no exceptions are thrown. However, when I close the application, it throws an Access Violation - one that I can't seem to catch anywhere in my C# code (including `DispatcherUnhandledException`).

This is specifically with 7.3.0.0 - as soon as I rolled back to 7.2.1 (and also 7.1.0), the error does **not** occur.

Here is what the Event Viewer says:

```
Faulting application name: Redacted.exe, version: 1.0.1.752, time stamp: 0x5a61e254
Faulting module name: ntdll.dll, version: 10.0.16299.192, time stamp: 0x6dead514
Exception code: 0xc0000005
Fault offset: 0x00000000000287e0
Faulting process id: 0x30b4
Faulting application start time: 0x01d39120085ddf1c
Faulting application path: Z:\WORKSPACES\DISTRIBUTION\Debug\Redacted.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: da3bbb6c-9964-4c1a-8688-60b2c33dbe2a
Faulting package full name: 
Faulting package-relative application ID: 
```

If I take out the `Task.Run()` and run the code directly, then it runs normally without problems.

Any ideas? Not urgent - I've rolled back to 7.2.1 and will stay there for a while.

**Comment by daxpandhi** [comment]
I will create a sample application to reproduce the issue this weekend.

**Comment by daxpandhi** [comment]
Also, don't have proof yet, but looks like this may be restricted to the use of Composite operator.
For example,
```
mm.Composite(m2, CompositeOperator.Displace, $"{s}x{s}");
```

Also, I forgot to mention, that this is in the OpenMP version. Haven't checked it against the others yet, but will do so for the test app.

**Comment by dlemstra** [comment]
Would love to get a program that I can use to reproduce and debug the issue 👍 Please let me know when you have created that.

**Comment by dlemstra** [comment]
@daxpandhi Any news regarding this issue?

**Comment by daxpandhi** [comment]
Sorry - I keep forgetting about this - been busy with a software launch. Will try it again and make the sample app this week when I get a chance.

**Comment by daxpandhi** [comment]
I just tried 7.4.2 it worked perfectly. I went back and tried the same code 7.3.0 and I can't seem to recreate it. Not sure what combination set it off. Hopefully it was something stupid I did in my code, and not in Magick. Will close the issue for now. Sorry for the false alarm.
