### ISSUE TITLE
Vulnerability scan flags win target architectures is built with libpng 1.0.11 with High vulnerabilities

### ISSUE THREAD

**Issue by Hyldahl** [dlemstra/Magick.NET#1457]
### Magick.NET version

Magick.NET-Q16-AnyCPU, 13.3.0

### Environment (Operating system, version and so on)

Multiple

### Description

Apologies if this is a red-herring and is problem with Blackduck or my app publishing process.

I am using Magick.NET-Q16-AnyCPU, 13.3.0 in a net6 project.

Blackduck vulnerability scans flags several Magick.NET files as using libpng 1.0.11, which has several High security vulnerabilities.

This will prevent me from moving my application into production.

Here is screenshots from the vulnerability scan of my app:

![image](https://github.com/dlemstra/Magick.NET/assets/1294824/0c7c738e-4497-447d-9e62-dbe2f0234e03)

![image](https://github.com/dlemstra/Magick.NET/assets/1294824/c7f537a6-fae7-45f2-b4db-d1c747fe1ee7)

Here is the files matched to libpng:

**libpng 1.0.11:**

/runtimes/win-arm64/native/Magick.Native-Q16-arm64.dll
/runtimes/win-x64/native/Magick.Native-Q16-x64.dll
/runtimes/win-x86/native/Magick.Native-Q16-x86.dll

Oddly enough the same files is also flagged as using libpngv1.6.39

**libpngv1.6.39:**

/runtimes/win-arm64/native/Magick.Native-Q16-arm64.dll
/runtimes/win-x64/native/Magick.Native-Q16-x64.dll
/runtimes/win-x86/native/Magick.Native-Q16-x86.dll

/runtimes/osx-arm64/native/Magick.Native-Q16-arm64.dll.dylib
/runtimes/osx-x64/native/Magick.Native-Q16-x64.dll.dylib
/runtimes/linux-arm64/native/Magick.Native-Q16-arm64.dll.so
/runtimes/linux-musl-x64/native/Magick.Native-Q16-x64.dll.so
/runtimes/linux-x64/native/Magick.Native-Q16-x64.dll.so

Any input to if this actually is a issue in Magick.NET or the issue is elsewhere would be highly appreciated.

### Steps to Reproduce

Create new project target net6 / AnyCPU
Reference Magick.NET-Q16-AnyCPU, 13.3.0 
Build & Publish

Scan published output files using Blackduck vulnerability scan.

Result: Use of libpng 1.0.11 is being flagged.

**Comment by dlemstra** [comment]
You should contact Blackduck instead. This project is using version `1.6.40` of the library as you can see here: https://github.com/dlemstra/Magick.NET/releases. Their tooling seems to have a bug.

**Comment by Hyldahl** [comment]
@dlemstra Sorry, I completely missed the version mentioned in the release notes.
Thank you for confirming
