### ISSUE TITLE
SetWriteMask & SetReadMask XML docs incorrectly state 'only contains the colors black and white'

### ISSUE THREAD

**Issue by kmgallahan** [dlemstra/Magick.NET#1458]
### Magick.NET version

13.3.0

### Environment (Operating system, version and so on)

n/a

### Description

The XML docs for SetWriteMask & SetReadMask state:

> The mask must be the same dimensions as the image and only contains the colors black and white.

However, the masks may be grayscale:

https://imagemagick.org/script/command-line-options.php#write-mask

> This the same as using a mask used for composite masking operations, with grayscale values causing blended updates of the image the mask is attached to.

So the docs should be updated to roughly:

> The mask must be the same dimensions as the image and contain a single grayscale channel.  // (no alpha? haven't tested)

*Note that currently setting a grayscale mask does produce the documented blending operation

### Steps to Reproduce

n/a

**Comment by dlemstra** [comment]
Thanks for mentioning this. I have updated the documentation.
