### ISSUE TITLE
"length and filesize do not match `' @ error/bmp.c/ReadBMPImage/934

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1461]
### Magick.NET version

13.3.3

### Environment (Operating system, version and so on)

windows 10

### Description

open my bmp file,it report "length and filesize do not match `' @ error/bmp.c/ReadBMPImage/934

[length and filesize do not match.zip](https://github.com/dlemstra/Magick.NET/files/12908969/length.and.filesize.do.not.match.zip)

### Steps to Reproduce

MagickImageInfo info = null;
try
{
    info = new MagickImageInfo(picbyte);
}
catch (Exception ex)
{
    errormsg = ex.Message;    
    //"length and filesize do not match `' @ error/bmp.c/ReadBMPImage/934"
}

**Comment by dlemstra** [comment]
Next time please use the search functionality:
- https://github.com/dlemstra/Magick.NET/issues/1216
- https://github.com/dlemstra/Magick.NET/discussions/1402
- https://github.com/dlemstra/Magick.NET/discussions/1455

You will find your answer there.

**Comment by Charltsing** [comment]
> Next time please use the search functionality:
> 
> * [Problem with reading certain BMP images.  #1216](https://github.com/dlemstra/Magick.NET/issues/1216)
> * [Fail to open bmp file with Magick.NET.Core 13.1.3 #1402](https://github.com/dlemstra/Magick.NET/discussions/1402)
> * [Convert - Ignore Error "length and filesize do not match" #1455](https://github.com/dlemstra/Magick.NET/discussions/1455)
> 
> You will find your answer there.

i do not know how to use BmpReadDefines in MagickImageInfo 
do you have any sample code?

**Comment by dlemstra** [comment]
I missed that you were using `MagickImageInfo` instead. The `MagickImageInfo` class is a wrapper around the `Ping` method of `MagickImage` and currently doesn't support defines. I am also not sure if I should add that. Why are you using `MagickImageInfo`?

**Comment by Charltsing** [comment]
> I missed that you were using `MagickImageInfo` instead. The `MagickImageInfo` class is a wrapper around the `Ping` method of `MagickImage` and currently doesn't support defines. I am also not sure if I should add that. Why are you using `MagickImageInfo`?

just test MagickImageInfo, i find this bug. I think maybe this feature should be added

**Comment by dlemstra** [comment]
I have made some changes today that will allow you to pass the read settings in the next release.
