### ISSUE TITLE
Feature Request: Provide a convenience method to get a `ReadOnlySpan<TQuantumType>` from a MagickImage

### ISSUE THREAD

**Issue by kmgallahan** [dlemstra/Magick.NET#1463]
### Is your feature request related to a problem? Please describe

I want a simple solution to pass `MagickImage` data into `System.IO.Steam.Write(ReadOnlySpan<Byte>)`.

### Describe the solution you'd like

A method on `MagickImage` with overloads similar to those found on `ToByteArray(...)` that would directly return a `ReadOnlySpan<TQuantumType>`.

Alternatively, the method could live on `UnsafePixelCollection`, which may be more appropriate.

### Describe alternatives you've considered

I'm aware `GetPixelsUnsafe()` will return an `IUnsafePixelCollection<TQuantumType>`, from which `GetAreaPointer(...)` can return an `IntPtr`, from which a `ReadOnlySpan<TQuantumType>` can be created. Although the bounds still need to be manually determined here.

### Additional context

I see `PixelCollection` is close to already doing this via:

https://github.com/dlemstra/Magick.NET/blob/cd07e1e2faea03f0bd34916e511a2a2c1a4aad6f/src/Magick.NET/Netstandard21/Pixels/PixelCollection.cs#L22-L23

but it's an internal class.

**Comment by dlemstra** [comment]
In the next version you will be able to use `IPixelCollection<TQuantumType>.GetReadOnlyArea` that will be available for both the `GetPixels()` and `GetPixelsUnsafe()` method. But this means you will get the pixels. When you use `ToByteArray` you will get the encoded data of the image and not just the pixels.

Can you explain in more detail what you want with:
> I want a simple solution to pass MagickImage data into System.IO.Steam.Write(ReadOnlySpan<Byte>).

A small code sample would make it more clear to me what you would want to do.

**Comment by kmgallahan** [comment]
I saw that `System.IO.Steam` has both:

[Write(Byte[], Int32, Int32)](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.write?view=net-7.0#system-io-stream-write(system-byte()-system-int32-system-int32))

and

[Write(ReadOnlySpan<Byte>)](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.write?view=net-7.0#system-io-stream-write(system-readonlyspan((system-byte))))

I'm currently using the former and passing a managed buffer using BGRA mapping.

I was hoping there would be a way to pass a ReadOnlySpan over native memory using BGRA mapping to avoid the extra allocation.

These bytes don't need any image encoding as the final destination (a `Microsoft.UI.Xaml.Media.Imaging.WriteableBitmap.PixelBuffer`) just wants raw samples.

So current options:

``` .cs
buffer = someImage.ToByteArray(MagickFormat.Bgra);

// or

someImage.Format = MagickFormat.Bgra;
buffer = someImage.ToByteArray();

// or

using var upc = someImage.GetPixelsUnsafe();
var buffer = upc.ToByteArray("BGRA")

```

Future options?

``` cs

var span = someImage.ToReadOnlySpan(MagickFormat.Bgra);

// or

someImage.Format = MagickFormat.Bgra;
var span = someImage.ToReadOnlySpan();

/// or

using var upc = someImage.GetPixelsUnsafe();
var span = upc.ToReadOnlySpan("BGRA")

```

I realize though this might not be possible depending on how the bytes are stored natively.

**Comment by dlemstra** [comment]
If you don't want the extra allocation I would advise you to use `image.Write(stream)` instead.

**Comment by kmgallahan** [comment]
Well that makes things easier ... 😅
