### ISSUE TITLE
Bug: All API calls where a `TemporaryMagickFormat` is used will modify `MagickImage.HasAlpha`

### ISSUE THREAD

**Issue by kmgallahan** [dlemstra/Magick.NET#1468]
### Magick.NET version

13.4.0

### Environment (Operating system, version and so on)

Windows 10 19045.3570

### Description

Calling any API method that uses a `TemporaryMagickFormat` will modify the `MagickImage.HasAlpha` value, whereas I would expect it not to change.

Looks like setting up the `TemporaryMagickFormat` and then restoring the prior format doesn't revert this change:

https://github.com/dlemstra/Magick.NET/blob/3ca8e97d2828838536601338ac7ae80d4474876e/src/Magick.NET/Helpers/TemporaryMagickFormat.cs#L61

### Steps to Reproduce

1. Take an image with `HasAlpha = false` (in my case a TIF)
2. Call any API method that creates a `TemporaryMagickFormat` with a format that has an alpha channel (in my case `Write(Stream stream, MagickFormat format)` with `MagickFormat.Bgra`)

Result: observe that after the call the image now `HasAlpha = true`

---

Note: This caused me some headaches trying to figure out why some drawing operations were behaving erratically, as the images have no alpha channel, but HasAlpha still changes how ImageMagick calls behave. 

Another issue was it increasing the size of TIF files written to disk to account for the alpha channel that doesn't show up when inspecting the file's image formats.

**Comment by dlemstra** [comment]
The `TemporaryMagickFormat` class only reverts the `Format` of the image. But this does not revert any changes to the images. Not only the `Bgra` has side effects but other formats also have that. This is something in inside ImageMagick that we cannot change. I would advise you to check `HasAlpha` and then decide if you want to use `MagickFormat.Bgr` instead of `MagickFormat.Bgra`.

**Comment by kmgallahan** [comment]
I don't have a choice in the format since `WriteableBitmap` requires bgra.

Is there a more efficient way to write to different formats without worrying about mutation of the original image than this:

```.cs
using tempImage = originalImage.Clone();
tempImage.Write(...)
```

I was just flipping `HasAlpha` back to false, but now I'm unsure what else gets modified.

---

In any case, the docs for these functions should probably mention that the internals of the image might be changed, as this looks innocent:

``` cs
/// <summary>
/// Writes the image to the specified stream.
/// </summary>
/// <param name="stream">The stream to write the image data to.</param>
/// <param name="format">The format to use.</param>
/// <exception cref="MagickException">Thrown when an error is raised by ImageMagick.</exception>
public void Write(Stream stream, MagickFormat format)
{
    using var tempFormat = new TemporaryMagickFormat(this, format);
    Write(stream);
}
```

**Comment by dlemstra** [comment]
If you need `BGRA` pixels I would advise you to use this instead:

```C#
using var pixels = image.GetPixelsUnsafe();
var bytes = pixels.ToByteArray("BGRA");
```

And do you have a suggestion of what we should add to the documentation to make it more clear that the `format` overloads might need to change the pixels of the image?

**Comment by kmgallahan** [comment]
That is where I started which prompted #1463, where you suggested using `Write(stream)`, which resulted in the issue of format swapping side effects I brought up here.

This leads back to the question, given an existing `MagickImage`, is there a more performant (allocation free) way to write the image to a stream/file/buffer in a different format without mutating the original? Or could there be?

**Comment by dlemstra** [comment]
As I said before I cannot avoid side effects when the image is written. It looks like you don't want to change the format of the image but that you want the pixels as bytes for a `WriteableBitmap`. And when you only need the pixels of the image you should use the method that I suggested earlier.

**Comment by kmgallahan** [comment]
I want to push ImageMagick data from native memory into a `System.IO.Stream`, which `Microsoft.UI.Xaml.Media.Imaging.WriteableBitmap` (C++) owns. In doing so I want to avoid any unnecessary large managed memory allocations while meeting the BGRA requirement.

It looks like using `MagickImage.Write.Stream` and either flipping `HasAlpha` or using `MagickImage.Clone()` first will be the most performant way to do this. I just need to be on the lookout for other format-swapping side effects in the future if I go that route.

---

Regarding updating the documentation for the API calls that use a `TemporaryMagickFormat`, can you clarify if:

```cs
public byte[] ToByteArray(MagickFormat format)
```

will result in the same side effects?

Also, did the aforementioned XML doc summary look acceptable? If so, I can submit a PR for the doc updates if you'd like.

**Comment by dlemstra** [comment]
You will always require a copy because the pixel channels are ordered differently in the internals. In theory I could reorder the pixels to BGRA but if you would to change them (`WriteableBitmap`) I would advise you to export and use a copy of the pixels.

**Comment by kmgallahan** [comment]
After reviewing the source I see a `StreamWrapper` is used that creates a full-sized buffer on the managed heap.

I'll return to my other question though. Would it be possible to either:

- Provide a method to get a ReadOnlySpan<byte> over the image's native heap memory to pass to `Stream.Write(ReadOnlySpan<Byte>)`
- Try out an implementation of MagickImage.Write(Stream) that uses such a span internally instead of the `StreamWrapper` implementation?

Thanks for being patient with me here. I should have looked deeper into the source earlier.

**Comment by kmgallahan** [comment]
## Method A, peak memory: 325 MB

``` cs
using var image = new MagickImage(@"C:\Dev\Tests\01HDP06GS6T8HKF9JHC95JK6Z0.tif");
var writeableBitmap = new WriteableBitmap(image.Width, image.Height);
using var stream = writeableBitmap.PixelBuffer.AsStream();

using var pixels = image.GetPixelsUnsafe();
var buffer = pixels.ToByteArray(PixelMapping.BGRA)!;
stream.Write(buffer, 0, buffer.Length);

ImageSource = writeableBitmap;
```
![Stream Write ByteArray](https://github.com/dlemstra/Magick.NET/assets/5379488/282c6b93-4c69-44d9-ab0b-079b36bda6f4)

## Method B, Peak memory: 234 MB

``` cs
using var image = new MagickImage(@"C:\Dev\Tests\01HDP06GS6T8HKF9JHC95JK6Z0.tif");
var writeableBitmap = new WriteableBitmap(image.Width, image.Height);
using var stream = writeableBitmap.PixelBuffer.AsStream();

using var tempClone = image.Clone();
tempClone.Write(stream, MagickFormat.Bgra);

ImageSource = writeableBitmap;
```
![MagickImage Write Stream](https://github.com/dlemstra/Magick.NET/assets/5379488/26f2e2ee-9969-4c79-8432-6bbd84880b19)

---

Method B using a clone and `MagickImage.Write(Stream)` creates a `StreamWrapper` that allocates a small byte[] of size 8192, keeping the image data on the native heap.

Method A creates a byte[] that stores all the data on the managed heap.

Would it be possible to try out an implementation of `MagickImage.Write(Stream)` that internally creates a `ReadOnlySpan<byte>` over the native heap memory and passes that to `Stream.Write(ReadOnlySpan<byte>)`, instead of the `StreamWrapper`? 

That would probably be even more performant and have a bit less complexity. I'm unsure about that native memory layout though.

**Comment by dlemstra** [comment]
What happens when you use `WriteableBitmap.Create` instead?

**Comment by kmgallahan** [comment]
That's a method on [`System.Windows.Media.Imaging.BitmapSource`](https://learn.microsoft.com/dotnet/api/system.windows.media.imaging.bitmapsource). 

I'm working with [`Microsoft.UI.Xaml.Media.Imaging.BitmapSource`](https://learn.microsoft.com/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.imaging.bitmapsource).

It has [`SetSource(IRandomAccessStream)`](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.imaging.bitmapsource.setsource?view=windows-app-sdk-1.4#microsoft-ui-xaml-media-imaging-bitmapsource-setsource(windows-storage-streams-irandomaccessstream)), but no implementation of IRandomAccessStream helps with performance here. Keep in mind that the original MagickImage created from the file is long-lived and has further operations performed on it, unlike the small bit of sample code in the benchmark. That is why mutating it with the BGRA format is a pain point.

The most performant would be `Stream.Write(ReadOnlySpan<byte>)`.

**Comment by dlemstra** [comment]
Sorry for the late reply but I had this on my todo list because I wanted to take some time to determine if I would want to create an extra library for this. I have decided to not do that at this time. But I do have something for future readers of this issue. You could write all the pixels of the image like this with minimal memory allocation:

```C#
using var image = new MagickImage(@"C:\Dev\Tests\01HDP06GS6T8HKF9JHC95JK6Z0.tif");
var writeableBitmap = new WriteableBitmap(image.Width, image.Height);
using var stream = writeableBitmap.PixelBuffer.AsStream();

using var pixels = image.GetPixelsUnsafe();
var blueIndex = pixels.GetIndex(PixelChannel.Blue);
var greenIndex = pixels.GetIndex(PixelChannel.Green);
var redIndex = pixels.GetIndex(PixelChannel.Red);
var alphaIndex = pixels.GetIndex(PixelChannel.Alpha);

var pixel = new byte[4];
for (var y = 0; y < image.Height; y++)
{
    var row = pixels.GetAreaPointer(0, y, image.Width, 1);
    pixel[0] = (byte)(row + blueIndex);
    pixel[1] = (byte)(row + greenIndex);
    pixel[2] = (byte)(row + redIndex);
    pixel[3] = alphaIndex == -1 ? Quantum.Max : (byte)(row + redIndex);
    stream.Write(pixel, 0, pixel.Length);

    row += pixels.Channels;
}
```
