### ISSUE TITLE
CompressionMethod does not exist in version 7.3.0

### ISSUE THREAD

**Issue by briankitt** [dlemstra/Magick.NET#147]
I just upgraded to 7.3.0, and CompressionMethod is no longer supported.  This is something I have used for years.

In the documentation, I can't find anything related to the replacement method for this?  What do I replace this with?

**Comment by IanYates** [comment]
See commit

https://github.com/dlemstra/Magick.NET/commit/6bf8544ddedb1cf30dbfe3f9b8186134f13c0dcc

It's literally titled `Renamed CompressionMethod to Compression`

Also, to set compression, you need to set it on the `Settings` object.  See release notes for 7.2.0 - https://github.com/dlemstra/Magick.NET/releases/tag/7.2.0.0

I'm pretty new to this library so I have no background to offer as to why the name was changed sorry.  I just like to keep on top of issues & commits in projects / libraries that I choose to depend on so I remember reading about this at the time :)

**Comment by briankitt** [comment]
Thank you so much.  That fixed it.

**Comment by dlemstra** [comment]
Thanks for help @IanYates 👍 The property was indeed renamed, the `Method` part was removed because it didn't really make sense to me anymore.
