### ISSUE TITLE
Crash with glib

### ISSUE THREAD

**Issue by ccremer** [dlemstra/Magick.NET#1471]
### Magick.NET version

"Magick.NET-Q8-x64" Version="13.4.0"

### Environment (Operating system, version and so on)

Linux (Mint 21.2 (Ubuntu-Based))

### Description

When running in multi-threaded context (e.g. ASPNET Core), using MagickNET is hard crashing when another process is depending on glib (I think).

As described in https://rachelbythebay.com/w/2017/01/30/env/ and in glib manual:
> Modifications of environment variables are not allowed in multi-threaded programs. 

The app crashes particularly when reaching `Environment.SetEnv("MAGICK_TEMPORARY_PATH", TemporaryDirectory);`.

Here's a log excerpt:

```console
info: WebApplication1.MagicNetInitialization[0]
      Initializing MagickNet /home/chris/source/scratchpad/TestProject1/WebApplication1
**
GLib-GObject:ERROR:../gobject/gvaluetypes.c:455:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
Bail out! GLib-GObject:ERROR:../gobject/gvaluetypes.c:455:_g_value_types_init: assertion failed: (type == G_TYPE_CHAR)
```

### Steps to Reproduce

https://gist.github.com/ccremer/ced17eb8c177003bd81ba727c2f5bda7

Included in the gist is IronPDF, a library to render PDFs. Without this library, MagickNET doesn't crash, but since IronPDF depends on Chrome, and Chrome itself on glib as well, the program will crash when you start it up.

However, if you swap the order of the boot from
```cs
builder.Services.AddHostedService<IronPdfInitialization>();
builder.Services.AddHostedService<MagicNetInitialization>();
```
to
```cs
builder.Services.AddHostedService<MagicNetInitialization>();
builder.Services.AddHostedService<IronPdfInitialization>();
```
then it works.

Still, calling `setenv` is forbidden in this context.
Is it possible we can skip this and setup the required environment variables by ourselves, without MagickNET trying to do it again?

**Comment by dlemstra** [comment]
Your error message looks like this one: #1126. And I really don't understand how you can to the conclusion that this is caused by `setenv`?

**Comment by ccremer** [comment]
Apologies for not being detailed enough.
The error pops when the code (in the gist) runs to `MagickNET.SetTempDirectory(tmpPath);` and then `Environment.SetEnv("MAGICK_TEMPORARY_PATH", TemporaryDirectory);`.

It also isn't a race condition. You can set a breakpoint or delay and it still crashes when calling `Environment.SetEnv("MAGICK_TEMPORARY_PATH", TemporaryDirectory);` after IronPDF has loaded the chrome libraries.

Swapping the order of MagickNET and IronPDF initialization only partially solves the problem. While the crash might be avoided, it still fails as described in #1472 .

I'll try to figure out my options...

**Comment by ccremer** [comment]
If I exclude the call to `MagickNET.SetTemporaryDirectory`, then later the crash happens in constructor `new MagickImage()`, particularly this line: https://github.com/dlemstra/Magick.NET/blob/937d36647784faa521f68a9553bd8ed8136a7986/src/Magick.NET/Native/Settings/MagickSettings.cs#L355

**Comment by ccremer** [comment]
Maybe related to this, I've noticed that IronPDF comes with a number of other dependencies besides Chrome:

```
BitMiracle.LibTiff.NET.dll
SixLabors.Fonts.dll
SixLabors.ImageSharp.dll
SixLabors.ImageSharp.Drawing.dll
```

Could there be any incompatibilities?

**Comment by dlemstra** [comment]
Could we close one of the two issues because this all seems to be related to IronPDF?

p.s. Would you be willing to share the versions of the SixLabors libraries?

**Comment by ccremer** [comment]
Yeah, it seems so, but I'm going to close both as it's not reproducible in Docker, as mentioned in #1472
