### ISSUE TITLE
WriteBlob Failed `1_Im1.png' @ error/png.c/MagickPNGErrorHandler/1492

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1474]
### Magick.NET version

13.3.3

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2

### Description

MagickImage report :
WriteBlob Failed `1_Im1.png' @ error/png.c/MagickPNGErrorHandler/1492

Occasionally encountering this error, it is difficult to reproduce

What may be the cause of this problem?

### Steps to Reproduce

not  reproduce

**Comment by dlemstra** [comment]
This seems to be related to not being able to write image data. How are you writing the output?

**Comment by Charltsing** [comment]
thanks for your replay

Possible conflict caused by concurrent operation of two MagickImage on the same image file

it is my problem
