### ISSUE TITLE
System.IO.FileNotFoundException:  assembly Magick.NET-Q16-AnyCPU, Version=7.2.1.0

### ISSUE THREAD

**Issue by chiccomotta** [dlemstra/Magick.NET#148]
HI,

I receive the following error:

**System.IO.FileNotFoundException: 'Non è stato possibile caricare il file o l'assembly 'Magick.NET-Q16-AnyCPU, Version=7.2.1.0, Culture=neutral, PublicKeyToken=null' o una delle relative dipendenze. Impossibile trovare il file specificato.'**

I have the following configuration:

Console application (.NET Framework 4.7.1) that references  Class Library (.NET standard 2.0).
Class library references Magick.NET-Q16-AnyCPU v 7.3.0.

In attachment the sample program. Could you help me, please?

Cristiano Motta
Italy

[MyConsole.zip](https://github.com/dlemstra/Magick.NET/files/1653506/MyConsole.zip)

**Comment by chiccomotta** [comment]
Hey is there anybody here?

**Comment by dlemstra** [comment]
It took me a while but I finally tracked down the issue. It appears to be some weird binding issue. The `netstandard` library links with the `netstandard` version of Magick.NET that does no strong naming. Then when you use that in a `net471` project  it will try to load the library without a strong name. But the `net471` build will use the `net40` dll and that is strong named and then it is unable to load the library.

I just pushed a patch to fix this in the next release. The next release will also strong name the `netstandard1.3` library and that should fix the issue. I will try it in this a test repo (https://github.com/dlemstra/MyConsole) before I push the new release to make sure it works.

**Comment by chiccomotta** [comment]
Thank you for your support, and thanks for the Magick.NET library, is awesome.

Cristiano

**Comment by dlemstra** [comment]
Will try to push out a new release this weekend.

**Comment by dlemstra** [comment]
It appears that the MyConsole application needs NuGet a reference to Magick.NET to find the library. The project with the new csproj does not need a reference. You can find my commits to test this here: https://github.com/dlemstra/MyConsole/commits/master

**Comment by chiccomotta** [comment]
Ok, thank you. I think now it's the right behaviour: no references between MyConsole app and magick.net but only the library project references Magick.net.
