### ISSUE TITLE
error/png.c/MagickPNGErrorHandler/1492

### ISSUE THREAD

**Issue by sujing910206** [dlemstra/Magick.NET#1494]
### Magick.NET version

13.5

### Environment (Operating system, version and so on)

Windows 11

### Description

Error when loading png images using Magick.NET `Read Exception C:\Users\54390\Downloads\11.png' @ error/png.c/MagickPNGErrorHandler/1492`

## Code
```C#
void Main()
{
	var imageFactory = new MagickImage(@"C:\Users\54390\Downloads\11.png");
}
```

## Png file
![11](https://github.com/dlemstra/Magick.NET/assets/11872459/d6da64aa-ca97-427b-bab9-8700821e3d2f)
Note: This png image is fully transparent

## Screenshot
![20231223215452](https://github.com/dlemstra/Magick.NET/assets/11872459/27bfb01f-5b16-451b-9856-736ab0919896)

**Comment by dlemstra** [comment]
This is happening because your image is not a valid png file. The ImageMagick library that is used by this project contains a very strict png decoder that doesn't accept invalid png files.
