### ISSUE TITLE
Why CannelCount=2, but Cannels.Count=1 when load a gray jpg ?

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1496]
### Magick.NET version

13.3.3

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2

### Description

 CannelCount=2, but Cannels.Count=1 when load a gray jpg ?

![1](https://github.com/dlemstra/Magick.NET/assets/19963715/63e8646b-57a4-40da-ab64-981f516f4706)

it is jpg image
[img.zip](https://github.com/dlemstra/Magick.NET/files/13765173/img.zip)

### Steps to Reproduce

byte[] picbyte = File.ReadAllBytes(fullpath);
using (MagickImage magickimage = new MagickImage(picbyte, settings))

settings as follow :

var settings = new MagickReadSettings
{
    // https://github.com/dlemstra/Magick.NET/issues/1077
    SyncImageWithExifProfile = true,
    SyncImageWithTiffProperties = true,
};
if (extname.Equals(".SVG", StringComparison.OrdinalIgnoreCase))
{
    settings.BackgroundColor = MagickColors.Transparent;
    settings.SetDefine("svg:xml-parse-huge", "true");
}
else if (extname.Equals(".HEIC", StringComparison.OrdinalIgnoreCase) || 
         extname.Equals(".HEIF", StringComparison.OrdinalIgnoreCase))
{
    settings.SetDefines(new HeicReadDefines
    {
        PreserveOrientation = true,
        DepthImage = true,
    });
}
else if (extname.Equals(".JP2", StringComparison.OrdinalIgnoreCase))
{
    settings.SetDefines(new Jp2ReadDefines
    {
        QualityLayers = 100,
    });
}
else if (extname.Equals(".TIF", StringComparison.OrdinalIgnoreCase) ||
         extname.Equals(".TIFF", StringComparison.OrdinalIgnoreCase))
{
    settings.SetDefines(new TiffReadDefines
    {
        IgnoreTags = new[] {
    // Issue https://github.com/d2phap/ImageGlass/issues/1454
    "34022", // ColorTable
    "34025", // ImageColorValue
    "34026", // BackgroundColorValue

    // Issue https://github.com/d2phap/ImageGlass/issues/1181
    "32928",

    // Issue https://github.com/d2phap/ImageGlass/issues/1583
    "32932", // Wang Annotation
    // Issue https://github.com/d2phap/ImageGlass/issues/1617
    "34031", // TrapIndicator
},
    });
}

// Fixed #708: length and filesize do not match
settings.SetDefines(new BmpReadDefines
{
    IgnoreFileSize = true,
});

// Fix RAW color
settings.SetDefines(new DngReadDefines()
{
    UseCameraWhitebalance = true,
    OutputColor = DngOutputColor.SRGB,
    ReadThumbnail = true,
});

**Comment by dlemstra** [comment]
That is happening because `ChannelCount` includes the index channel but the `Channels` property doesn't. I don't know why I did that but I just pushed a patch to also include the `Index` channel.
