### ISSUE TITLE
Bug with Evaluate when using EvaluateOperator.Set

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#15]
I have successfully reproduced a problem I have in my application with your Watermark sample.
When I use another operator than Set, it's working but when you try to use:
`watermark.Evaluate(Channels.Alpha, EvaluateOperator.Set, new Percentage(25));`
you obtain
![fujifilmfinepixs1pro watermark](https://cloud.githubusercontent.com/assets/1556750/16083623/ede47ca8-3315-11e6-99fa-842fd14f0b6b.jpg)
instead of:
![fujifilmfinepixs1pro watermark](https://cloud.githubusercontent.com/assets/1556750/16083640/0859e3f2-3316-11e6-9fde-f39f12b870cc.jpg)

**Comment by dlemstra** [comment]
What you are seeing is the correct behavior and that is why I used divide in my example. With Set you will changed the transparency of every pixel even the ones that are full transparent.

**Comment by DavidRouyer** [comment]
Thanks for the clarification!
