### ISSUE TITLE
can not open png, but is shown in windows (relying on WIC codec) and browsers (that uses libpng)

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1500]
### Magick.NET version

13.3.3

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2

### Description

none

### Steps to Reproduce

image is here
[png.zip](https://github.com/dlemstra/Magick.NET/files/13791815/png.zip)

![捕获](https://github.com/dlemstra/Magick.NET/assets/19963715/551540a0-6fdf-4931-a4d4-19e12abb71c1)

you can see it:
https://github.com/saucecontrol/PhotoSauce/issues/139#issuecomment-1806421745

**Comment by dlemstra** [comment]
Your png file contains an invalid value for the adaptive filter and that is why libpng refuses to read the image, Other libraries or modified versions of libpng might accept it but ImageMagick doesn't. That file also contains other issues.
