### ISSUE TITLE
Could not open a PSD file

### ISSUE THREAD

**Issue by kukuro-kt** [dlemstra/Magick.NET#1507]
### Magick.NET version

ImageMagick version 7.1.1-10 Q16 HDR

### Environment (Operating system, version and so on)

Win11: 10.0.22621.2861

### Description

This image:
https://drive.google.com/file/d/1kQFRPe7RpZ4Yic42zb8J9-Thcm3YCVeE/view?usp=sharing

It can be opened by Photoshop or online image viewers(for example: https://www.photopea.com),
but it cannot be opened by MagickViewer/IMDisplay/ImageGlass

Related Issue: https://github.com/d2phap/ImageGlass/issues/1806#issuecomment-1877343542

### Steps to Reproduce

Download the image file from above and open it with MagickViewer/IMDisplay/ImageGlass.

**Comment by dlemstra** [comment]
Thanks for reporting this. It looks like we had an incorrect check in the PSD coder. This issue will be resolved in the next release of ImageMagick
