### ISSUE TITLE
ArgumentNullException from ImageOptimizer.IsSupported(string) if string refers to .pub file

### ISSUE THREAD

**Issue by InfernumDeus** [dlemstra/Magick.NET#151]
Every time I call `ImageOptimizer.IsSupported()` with a string referring to `.pub` file (Microsoft Publisher document) I get `ArgumentNullException`.

StackTrace:
```
   in ImageMagick.ImageOptimizer.IsSupported(MagickFormatInfo formatInfo)
   in ImageMagick.ImageOptimizer.IsSupported(String fileName)
```

I'm using Magick.NET-Q16-AnyCPU 7.3.0.

**Comment by dlemstra** [comment]
Thanks for reporting this, will push a patch for this later today.

**Comment by InfernumDeus** [comment]
Strange.
I tried to debug it but can't find `FileHelper.CheckForBaseDirectory()`
https://github.com/dlemstra/Magick.NET/blob/master/Source/Magick.NET/Shared/Helpers/FileHelper.cs

**Comment by dlemstra** [comment]
You can find that method in the file in the framework folder. It's a partial class. The bug that you reported is in an other file. It throws an exception instead of checking if the argument is null and return false.

**Comment by InfernumDeus** [comment]
I see. Looking forward to get updated version through NuGet.

**Comment by dlemstra** [comment]
Will try to publish a new version this weekend.

**Comment by InfernumDeus** [comment]
Ok. Thank you for fast fix and great library.
