### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#152]
Hi @dlemstra

I am using `Magick.NET-Q16-AnyCPU 7.3.0` in my little application. 
There are some image files encounter memory leak. The app consumes up to 78% CPU and 8.3 GB of RAM: https://imgur.com/iD1z7Hv

Sample files:

- https://github.com/d2phap/ImageGlass/issues/120
- https://github.com/d2phap/ImageGlass/issues/121

You can find my code here:
https://github.com/d2phap/ImageGlass/blob/develop/Source/Components/ImageGlass.Core/Interpreter.cs#L60

Hope it can be fixed in the next release.
Thank you.

**Comment by dlemstra** [comment]
Did you confirm that this is not an issue in your application and can you reproduce the issue with a simple sample?

**Comment by d2phap** [comment]
I tried to debug and track the code. I think Magick.Net is working fine. 

The leak happened after Magick.Net completes loading image, then the memory went up crazily.

Thanks and sorry for your time
