### ISSUE TITLE
Most likely unintended fetch-depth: 0 in GitHub Actions workflow wastes resources

### ISSUE THREAD

**Issue by sschultze** [dlemstra/Magick.NET#1528]
### Is your feature request related to a problem? Please describe

Some checkout steps in `.github/workflows/main.yml` use the setting `fetch-depth: 1`, which fetches all history for all branches and tags. This is most likely unintended and wastes resources.

### Describe the solution you'd like

The `actions/checkout@v4` documentation says that "only a single commit is fetched by default, for the ref/SHA that triggered the workflow".

So I think the best solution would be to just remove the `fetch-depth: 1`.

**Comment by dlemstra** [comment]
I suspect that you mean the `fetch-depth: 0` value instead as you mention in your title? In earlier versions I had to do that to make sure tags were fetched. But it looks like they introduced a new option called `fetch-tags` that will make sure the tags are always fetched. And it also seems that the default is `1` so I canremove it. Thanks for pointing this out. I will update the workflow.

**Comment by sschultze** [comment]
You are right. Sorry, of course I meant `fetch-depth: 0`, like in my title. I wasn't aware of the need to fetch tags. Thank you!
