### ISSUE TITLE
Picture scales are wrong

### ISSUE THREAD

**Issue by HakanKaraoglu** [dlemstra/Magick.NET#1529]
### Magick.NET version

13.5.0

### Environment (Operating system, version and so on)

Macos, Sonoma 14.2.1

### Description

I'm trying to get the properties of an image like the one below, but as seen in the image, the width and height units are interchanged. What could be the reason for this and how can I solve it?

Simple Image: 
![testimage](https://github.com/dlemstra/Magick.NET/assets/12962730/d80bf1c2-8e03-44d0-b356-f12c6d1582d1)

<img width="563" alt="Screenshot 2024-01-25 at 23 28 39" src="https://github.com/dlemstra/Magick.NET/assets/12962730/d002a9a8-a11e-4e32-8cf8-36d60893b39c">

### Steps to Reproduce

```
using System.Net.Mime;
using ImageMagick;

var applicationPath = AppDomain.CurrentDomain.BaseDirectory;
var imageName1 = "testimage1.jpeg";

var image1Path = Path.Combine(applicationPath, imageName1);

var fileInfo = File.ReadAllBytes(image1Path);

using var image = new MagickImage(fileInfo);
// Exif data
var exifProfile = (ExifProfile)image.GetExifProfile();

if (exifProfile != null)
{
    foreach (var exifValue in exifProfile.Values)
    {
        Console.WriteLine($"{exifValue.Tag}: {exifValue.ToString()}");
    }
}

var width = image.Width;
var height = image.Height;

Console.WriteLine($"Width: {width}, Height: {height}");
```

**Comment by dlemstra** [comment]
It's not wrong. Your image viewer is calling `image.AutoOrient()` before showing the image.

**Comment by HakanKaraoglu** [comment]
@dlemstra thanks for fast response, yes now is correct
