### ISSUE TITLE
Support for HEIF/HEIC?

### ISSUE THREAD

**Issue by davediff** [dlemstra/Magick.NET#153]
It looks like support for this was added to ImageMagick in 7.0.7.22 according to this issue: [https://github.com/ImageMagick/ImageMagick/issues/507](url). Does this mean we'll have support when that build makes its way into Magick.NET? My understanding is that the support requires libde265 but I'm not sure how that affects support in Magick.NET. Any clarity on this would be appreciated.

**Comment by dlemstra** [comment]
There is no support for that format in the Windows build of ImageMagick yet. Once that has been added we will have support for this in Magick.NET. I cannot give you an eta when that will happen.

**Comment by davediff** [comment]
Thanks for the response. Do you know if that is because the support is platform specific and we'll have to wait for someone to port the changes or is this a build issue and we are waiting for the change to get picked up somewhere?

**Comment by dlemstra** [comment]
The Windows build of ImageMagick will need to include a build of `libde265`. And we are waiting till someone adds that build to the ImageMagick project. And that someone is most likely me 😄. I cannot give you an eta when I will make time for that.

**Comment by davediff** [comment]
I have familiarity with building libde265 on windows but not at all with how that fits into the ImageMagick build process. I could take a look at lending a hand with this if you could point me to a commit for some other decoder library that was added. Searching that repo didn't turn up anything obvious but I'll look again. For example I was looking for webp, but maybe that isn't built for windows also?

**Comment by dlemstra** [comment]
We use our own logic to create the VisualStudio solutions. The configuration for each library is located in this repository: https://github.com/ImageMagick/VisualMagick. And we keep a copy of each library, for example: https://github.com/ImageMagick/webp/. The config that belongs to this library can be found here: https://github.com/ImageMagick/VisualMagick/blob/master/webp/Config.txt. You can create the solution files with this executable: https://github.com/ImageMagick/VisualMagick/tree/master/configure

**Comment by dlemstra** [comment]
Did a quick test to see if I could compile the source in ImageMagick and I got it working. Only problem now is that I need a good file to test it with. Some of the files that I use show the following error message:

```
convert: Bad image: "only base_offset_size=0 and index_size=0 are supported" 'ParseIlocAtom': No such file or directory @ error/heic.c/ParseIlocAtom/569.
```

**Comment by davediff** [comment]
I know nokia has published some test files here that might help: http://nokiatech.github.io/heif/examples.html

**Comment by davediff** [comment]
Let me know if you'd like some additional testing. So you got it building in Windows? I started to look at the VisualMagick project that you pointed me towards and forked that, but as I understand we'd need to also create a new repo under ImageMagick which is a copy of libde265

**Comment by dlemstra** [comment]
We need to create a repo with a copy of libde265 under the ImageMagick repository. I created one locally and I got ImageMagick building with libde265 1.0.2. Will continue to work on this later this week.

**Comment by davediff** [comment]
That's not something I can do under ImageMagick correct? I can only fork existing repos. We are currently using Magick.NET in our service for thumbnail generation on many formats. We've had a lot of customer requests for HEIF support and are looking at a couple possibilities. Magick.NET is our best bet as it's already in place. Thank you for the effort so far and any updates will be appreciated!

**Comment by dlemstra** [comment]
I pushed some patches to ImageMagick last night to add support for HEIF. The next release of ImageMagick and Magick.NET will have support for HEIF.

**Comment by dlemstra** [comment]
I just published Magick.NET 7.4.1.0 that includes support for HEIF.

**Comment by d2phap** [comment]
Hi @dlemstra 
I just tried the version 7.4.1.0 to open the samples from here: https://github.com/nokiatech/heif/tree/gh-pages/content/images with your MagickViewer for testing but it doesn't work:
https://github.com/dlemstra/MagickViewer

![image](https://user-images.githubusercontent.com/3154213/36385113-314bd1f2-15c4-11e8-94d2-05a992f7cd52.png)

Then I tried with my own HEIC files, it works but the color is not correct. 

![image](https://user-images.githubusercontent.com/3154213/36385225-8aa43294-15c4-11e8-9388-b41f96a5c642.png)

Any extra configurations?
Thanks

**Comment by dlemstra** [comment]
Not all files are supported. Can you share one of your own files that is showing incorrect colors?

**Comment by d2phap** [comment]
Yes, here you go
[IMG_0378.zip](https://github.com/dlemstra/Magick.NET/files/1737624/IMG_0378.zip)

**Comment by dlemstra** [comment]
It looks like the `ToBitmapSource` method that is being used only supports images in the `sRGB` colorspace. HEIC images are in the `YCbCr` colorspace and are displayed incorrectly. Just pushed a patch to resolve this.

**Comment by d2phap** [comment]
Hi! I just upgraded to the latest version 7.4.4.5
If I use `ToBitmap()` instead of `ToBitmapSource()`, the wrong colorspace issue will happen again.

**Comment by dlemstra** [comment]
@d2phap Thanks for reporting this. Just pushed a patch to make sure that `ToBitmap()` also changes the colorspace to sRGB.

**Comment by d2phap** [comment]
Thanks @dlemstra 
Await for the nudget release

**Comment by jberke** [comment]
Has this been rolled into nuget I updated to what I thought was latest version using Magick.Net-Q16-AnyCpu version 7.19.0 I am getting:

no encode delegate for this image format `HEIC' @ error/constitute.c/WriteImage/1240
