### ISSUE TITLE
[Font read for non-standard formats is causing lot of file reads]

### ISSUE THREAD

**Issue by tariqgitspace** [dlemstra/Magick.NET#1538]
### Magick.NET version

13.5.0

### Environment (Operating system, version and so on)

Windows Server 2019

### Description

For various non-standard images formats (not jpeg and png), we are seeing a lot of file disk read for Arial Font as in below image. For our traffic, the read count is in 1000s per minute

Our use case is just converting these non-standard formats to standard formats like jpeg, png.
Is it possible to disable or skip these reads? If not, is it possible to increase the default readLength to reduce number of IO operations

![image](https://github.com/dlemstra/Magick.NET/assets/6762447/7b2185ec-4c42-4562-a180-10e2e76169c4)

### Steps to Reproduce

1. Since, its happening for our customers in our deployment, we dont have access to customer content.
2. Rasterize non-standard image to standard format

**Comment by dlemstra** [comment]
Don't send me these kind of message. It moves you to the bottom of my list of things that I will take a look at. And this was the next thing I was going to check but now you need to wait longer.

**Comment by dlemstra** [comment]
Would it be possible for you to figure out how you can reproduce this? I suspect this is happening inside an external dependency but if I don't know what is doing this where I cannot check if we can tweak this.

**Comment by tariqgitspace** [comment]
Hello,
We are unable to repro issue with sample images (and we dont have access to client images). I will close the issue for now and will open back once able to repro it.

Thanks
