### ISSUE TITLE
ImageMagick.MagickDelegateErrorException: PDFDelegateFailed `Could not find the specified file.' @ error/pdf.c/ReadPDFImage/794

### ISSUE THREAD

**Issue by d4nyel** [dlemstra/Magick.NET#154]
Hello there,
i get the following exception from ImageMagick:

```
`ImageMagick.MagickDelegateErrorException: PDFDelegateFailed `Das System kann die angegebene Datei nicht finden.
' @ error/pdf.c/ReadPDFImage/794
   bei ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadFile(MagickSettings settings)
   bei ImageMagick.MagickImageCollection.AddImages(String fileName, MagickReadSettings readSettings, Boolean ping)
   bei ImageMagick.MagickImageCollection.Read(String fileName, MagickReadSettings readSettings)
   bei Converter.ConvertPDFBMP.PdfToBmp.Convert(Parameter Parameter) in C:\dev\ConvertPdfBmp\Converter.cs:Zeile 97.`
```

Line 97 in Convert.cs is the following:
`var magickReadSettings = new MagickReadSettings()`

I've developed the application / tool on a Windows 7 System.
It runs perfectly developed VS 2008.
However, when I deploy the converter to a "Windows Embedded Standard" system I always get the above mentioned exception. 

How can I solve this?
I assume that it has something to do with the "Windows Embedded Standard" system but I need to get the conversion running on that system.

**Comment by dlemstra** [comment]
Did you install Ghostscript on that machine?

**Comment by d4nyel** [comment]
Not directly installed,
I provide the ghostscript assemblys in code:
```
  PdfToBmp.ghostscriptLibaryPath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ghostscript");
            PdfToBmp.ghostscriptAssemblyFile = "gsdll32.lib";
            PdfToBmp.ghostscriptAssemblyFilePath = Path.Combine(PdfToBmp.ghostscriptLibaryPath, PdfToBmp.ghostscriptAssemblyFile);
```
`MagickNET.SetGhostscriptDirectory(PdfToBmp.ghostscriptLibaryPath);`

Before setting the directory I check if the file exists. If not, I throw an exception. But the FileNotFound exception for the ghostscript libary does not throw so I assume this works and intended.

**Comment by dlemstra** [comment]
I think you need to change `gsdll32.lib` to `gsdll32.dll`. It is possible that your application runs in 64-bit mode and tries to load a 32-bit library.

**Comment by d4nyel** [comment]
The application is explicit compiled with platform x86.
Further, the ghostscript directory contains both files `gsdll32.lib` and `gsdll32.dll`

`MagickNET.SetGhostscriptDirectory(PdfToBmp.ghostscriptLibaryPath);`
Just sets the path of the folder witch contains the `lib `and dll `file`.

**Comment by d4nyel** [comment]
As the exception says that MagickNET is not able to finde a specific file I assume that a necessary file for Magick.NET is missing on the  "Windows Embedded Standard" system and / or in the folder.
The only difference is the difference OS.
Are there any other dependencies which MagickNET uses besides the ghostscript files?

**Comment by dlemstra** [comment]
Maybe you could try to use `http://www.dependencywalker.com/` and check if there is something `Magick.NET` or `Ghostscript` depends on?

**Comment by d4nyel** [comment]
My fault.
Its the Read operation which throws the error:

```
var x = File.ReadAllBytes(pdfToBmpParameter.PdfFilePath);
pdfImages.Read(x);
```
and

` pdfImages.Read(pdfToBmpParameter.PdfFilePath);`

Both calls run the same error.
As you can see: `ReadAllBytes `can access the file so it should not be an file access problem.

**Comment by dlemstra** [comment]
Did the dependencywalker tell you anything?

**Comment by d4nyel** [comment]
Yes, the `Magick.NET-Q16-x86.dll `dependencies are all included in the Windows XP Embeded system. I've looked them up in the corresponding folder.

`Magick.NET-Q16-x86.Native.dll ` needs `GDIPLUS.DLL` and `ADVAPI32.DLL` which are not included the in the Windows XP Embeded system in the corresponding system32 folder.

**Comment by d4nyel** [comment]
I've just copied the missing files over but still not working. :/

**Comment by dlemstra** [comment]
That probably won't work and you probably need a patched version of ImageMagick to get this working. One of the encoder uses GDI to read EMF files so you could probably disable that to get rid of the `GDIPLUS.DLL` dependency. And it looks like ` ADVAPI32.DLL` is used to read the registry. If you want to get this working on `Windows XP Embeded` it will be a lot of trail and error and patching ImageMagick.

**Comment by dlemstra** [comment]
@d4nyel Can we close this issue? Have you found another solution or are you trying to build the ImageMagick project with some patches to get rid of those dlls

**Comment by d4nyel** [comment]
Sorry for my late reply.
Was kinda busy the last days.

As the ImageMagick project contains much more than I / we need I decided to write an own wrapper for the ghostscript libary. This, in the case of time effort, makes more sense to me then patching the whole ImageMagick project.  So far the wrapper libary works without problems on the Windows XP embedded system.

Thanks for your support so far :). 👍
