### ISSUE TITLE
Long time to read Heic Image

### ISSUE THREAD

**Issue by tariqgitspace** [dlemstra/Magick.NET#1542]
### Magick.NET version

13.5.0

### Environment (Operating system, version and so on)

Desktop, Windows Server

### Description

It takes a long time (~10 seconds) to read large Heic and Dng files.
Please find Heic Image here: https://drive.google.com/file/d/1e-6d2Ds0W-X8TRykDyAYUdNgCP4glttR/view?usp=sharing

Is there a faster way to read it ? Again, my requirement is to rasterize it in Jpeg or Png.

Thanks

### Steps to Reproduce

Read shared Image using below code.

using (MagickImage image = new MagickImage(inputStream, new MagickReadSettings()))
 { }

**Comment by dlemstra** [comment]
Buy faster hardware or try if the `OpenMP` version makes it better for you. Your image is `12240x16320` and that is really huge so yes it will take time.

**Comment by tariqgitspace** [comment]
Thank you @dlemstra for looking into it.
And thanks for this wonderful library !!
