### ISSUE TITLE
Some GIF cannot save as Webp.

### ISSUE THREAD

**Issue by suyangzuo** [dlemstra/Magick.NET#1548]
### Magick.NET version

Q16-HDRI-OpenMP-x64

### Environment (Operating system, version and so on)

Win11-23H2

### Description

Some GIF cannot save as Webp.

### Steps to Reproduce

Example GIF:

![303896572-9ab43167-1221-4589-983c-197ca1ed7190](https://github.com/dlemstra/Magick.NET/assets/50766353/9e4a5ce1-a6bd-4ab3-9e4a-cb2994ca5974)

**Comment by dlemstra** [comment]
And why can it not be saved as a webp? What happens?

**Comment by suyangzuo** [comment]
> And why can it not be saved as a webp? What happens?
It popup a error dialog:
<img width="377" alt="PixPin_2024-02-14_10-56-27" src="https://github.com/dlemstra/Magick.NET/assets/50766353/52af7ff7-7e37-4fa0-991f-78a1c1b273da">

**Comment by dlemstra** [comment]
You will need to run on the `.Coalesce()` method on the collection to make sure all the images have the same dimensions. We might be able to automate this inside ImageMagick but I will need to investigate if that is possible.

**Comment by d2phap** [comment]
@dlemstra Cannot reproduce this issue in Magick.NET v13.7.0 (the original posted at https://github.com/d2phap/ImageGlass/issues/1849)

**Comment by dlemstra** [comment]
We now do the `.Coalesce()` call when possible in the `webp` coder and that is why you cannot reproduce that issue anymore.
