### ISSUE TITLE
Write text on top of image with WordWrap

### ISSUE THREAD

**Issue by Menighin** [dlemstra/Magick.NET#156]
Hi there,

I would like to know how to Draw a `string `on top of a background image I have.
This is a variable lenght string so it would be nice if I could define the "text area" that it could be written and the text would be wrapped into this area.
Furthermore I would like to calculate this text size and, if the text height is more than the image background, I would shrink its font size until it fits the background.

Is all of this possible? How? I couldnt manage to do it :/

Thanks!

**Comment by dlemstra** [comment]
You can use the `label:` decoder to accomplish this:

```C#
using (var image = new MagickImage("logo:"))
{
    var readSettings = new MagickReadSettings
    {
        FillColor = MagickColors.Magenta,
        BackgroundColor = MagickColors.Transparent,
        TextGravity = Gravity.Center,
        // This determines the size of the area where the text will be drawn in
        Width = 100,
        Height = 50
    };

    // Only need this with a transparent background in the readSettings
    image.Alpha(AlphaOption.Opaque);

    using (var label = new MagickImage("label:test", readSettings))
    {
        image.Composite(label, 200, 300, CompositeOperator.Over);

        image.Write("test.png");
    }
}
```

This example probably needs some tweaking for your use case but it I hope this will help you. Feel free to ask more questions in this issue if you need more help.

**Comment by Menighin** [comment]
Hi @dlemstra, thanks for the answer!

I think I'm almost there:

           `_magickImage = new MagickImage($"background.jpg");
            
            var readSettings = new MagickReadSettings
            {
                FillColor = MagickColors.White,
                BackgroundColor = MagickColors.Transparent,
                TextGravity = Gravity.Center,
                Width = 940,
                Height = 492 - 30,
                StrokeColor = MagickColors.Black,
                FontPointsize = 40
            };
            _magickImage.Alpha(AlphaOption.Opaque);

            using (var label = new MagickImage($"label:{drawable.Message}", readSettings))
            {
                _magickImage.Composite(label, 40, 40, CompositeOperator.Over);

            }`

Theres just two things I am missing now:

- The text is not being wraped. It is being croped from the image
- How can I calculate, after I manage to wrap the text, if the height of the wraped text fits the background so I can shrink the font size and write it again, if needed?

Thank you so much!

**Comment by dlemstra** [comment]
It appears you will need to use `caption:` (http://www.imagemagick.org/Usage/text/#caption) if you want word wrapping. If you don't specify the `FontPointSize` it will be determined automatically.

**Comment by dlemstra** [comment]
@Menighin Can we close this issue?

**Comment by Menighin** [comment]
Hi @dlemstra!
Yes! We can close! I actually wont have time to test it for a couple of months now, but I do believe it will be fine!

Thanks once again!
