### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by justdan23** [dlemstra/Magick.NET#157]
Hi Dirk,

Do you have any tips for down converting the projects to support Visual Studio 2015?

We can't yet move to Visual Studio 2017 and my customer wants us to build everything before we use it to have a warm fuzzy with security on all binaries.

Thoughts?
Dan

**Comment by dlemstra** [comment]
Not sure if you are now creating those binaries on a build machine or on your own machine. I would advise you to create a VM on your local machine or in Azure and install VS 2017 there. Then you know you will have a clean installation and you can just use VS 2017. Magick.NET can be build with the community edition and I think that is much easier than converting the project.

**Comment by dlemstra** [comment]
@justdan23 Can we close this issue Dan?
