### ISSUE TITLE
Color issue for a file after processing with Magick.NET

### ISSUE THREAD

**Issue by Sabari2810** [dlemstra/Magick.NET#1570]
### Magick.NET version

Magick.Net Q-16 Any CPU 13.0.1

### Environment (Operating system, version and so on)

Windows server 2016, 64 bit

### Description

After generating a thumbnail for a file with Magick.NET, there is a huge difference in color when compared with the actual file
![image](https://github.com/dlemstra/Magick.NET/assets/76817070/e6d0bc2d-9050-4f13-a8e2-87a39e6ba832)

Please find the attached file in the drive for your reference https://drive.google.com/file/d/1lkLcKJA__10d1IYwxhaQaivoPKP1J4Dp/view?usp=drive_link

### Steps to Reproduce

var settings = new MagickReadSettings()
{
    AntiAlias = true,
    Defines = new DngReadDefines
    {
        ReadThumbnail = true,
        UseCameraWhitebalance = true,
    }
};

using (var image = new MagickImage(sourceFile, settings))
{
    image.Thumbnail(1400, 1400);
    image.Write(previewPath);
    //await image.WriteAsync(previewPath);
}

**Comment by dlemstra** [comment]
It looks like the application that you are using to view the original image is displaying it incorrectly? When I view the image in Chrome I get the colors that you are seeing in the thumbnail. Maybe there is something specific in your image that this viewer finds and uses?

**Comment by Sabari2810** [comment]
Thanks for the response, Did you generate a thumbnail for the file provided?

**Comment by Sabari2810** [comment]
The image I shared is the original image, please generate a thumbnail to recreate the issue

**Comment by dlemstra** [comment]
If you open both images in the browser there is no color difference so it looks like your image viewer is doing something special with your input image. It will be up to you to figure out why this is happening with your viewer.

**Comment by Sabari2810** [comment]
Thanks for the response, They do look the same when opened in the browser, but when opened in Photoshop they look different. Is there any reason why the bright original image looks dull in the browser?

**Comment by Sabari2810** [comment]
Sure, Thanks for the response
