### ISSUE TITLE
Density Information Unable to Be Read

### ISSUE THREAD

**Issue by matthew-t-smith** [dlemstra/Magick.NET#1575]
### Magick.NET version

13.6.0

### Environment (Operating system, version and so on)

Windows 10, Visual Studio Professional Preview 17.10.0 Preview 1.0, .NET 8.0

### Description

I have an image file (attached below) that has DPI information available (also shown below), but I cannot seem to get it read via ImageMagick.

I've attempted reading it strictly via ImageMagick and with NExifTools, but no luck:
```
var path = @"C:\Users\MatthewSmith\Downloads\Test_DPI_Original.jpg";
var image = new MagickImage();
image.Read(path);
```
`image.Density.X = 0`, `image.Density.Y = 0` and `image.Density.Units = Undefined`

![Proof of DPI](https://github.com/dlemstra/Magick.NET/assets/15874467/e711f3a8-0a5f-41d0-add1-16921482d231)

![Test_DPI_Original](https://github.com/dlemstra/Magick.NET/assets/15874467/18c52141-6ab4-4d24-948f-c52f2436faac)

### Steps to Reproduce

- Create a new `MagickImage()` and `.Read()` the file provided 
    - Note, I've also tried the `using` syntax: `using image = new MagickImage(source)` where `source` is both the direct file path and an HTTP request body `Stream` to no avail
- Check to see if any `.Density` information is present.

**Comment by dlemstra** [comment]
This is happening because your file does not contain any density information. The viewer you are using is just showing a arbitrary default value of 96 dpi.

**Comment by matthew-t-smith** [comment]
I was entirely unaware of the AppliedDPI default of 96. That would certainly explain it - thanks for the clarification.
