### ISSUE TITLE
Magick makes the text faint

### ISSUE THREAD

**Issue by alexeygritsenko** [dlemstra/Magick.NET#1593]
### Magick.NET version

Magick.NET-Q8-x64 v13.6.0

### Environment (Operating system, version and so on)

Windows 10

### Description

![image](https://github.com/dlemstra/Magick.NET/assets/10233486/ca714b23-bfe5-4d04-8ed5-02825c8f1ead)
To me, it looks worse than libavif
```
 public static async Task SaveAsAvif(MagickImage image, string path)
 {
     image.Quality = 85;
     image.Format = MagickFormat.Avif;

     using (var output = new MemoryStream())
     {
         await image.WriteAsync(output);
         output.Position = 0;

         using (var fileStream = File.Create(path))
         {
             await output.CopyToAsync(fileStream);
         }
     }
 }
```
vs
`avifenc -q 85 slider8.jpg slider8.avif`

libavif v1.0.4 windows https://github.com/AOMediaCodec/libavif/releases/download/v1.0.4/libavif-v1.0.4-avifenc-avifdec-windows.zip

Increasing the quality did not correct the color. Have you thought about switching Magick.NET to libavif? Or will the colors be corrected in a future version?
[slide8.zip](https://github.com/dlemstra/Magick.NET/files/14722957/slide8.zip)

### Steps to Reproduce

Im convert jpg with Magick.NET and libavif, and comparing it in paint.net

**Comment by alexeygritsenko** [comment]
> Can you share your input image?

Yes, it is already in the archive of the 1st message 

> It might be related to your input image and how the image is decoded. You are using the Q8 version and I am not sure what avifenc is using.

Xm

**Comment by alexeygritsenko** [comment]
If this could be useful, the output from libavif:
```
C:\Users\admin\Downloads\libavif-v1.0.4-avifenc-avifdec-windows>avifenc -q 85 slider8.jpg slider8.avif
Directly copied JPEG pixel data (no YUV conversion): slider8.jpg
Successfully loaded: slider8.jpg
AVIF to be written: (Lossy)
 * Resolution     : 1340x500
 * Bit Depth      : 8
 * Format         : YUV444
 * Alpha          : Absent
 * Range          : Full
 * Color Primaries: 2
 * Transfer Char. : 2
 * Matrix Coeffs. : 6
 * ICC Profile    : Present (560 bytes)
 * XMP Metadata   : Present (5276 bytes)
 * Exif Metadata  : Present (3237 bytes)
 * Transformations: None
 * Progressive    : Unavailable
Encoding with AV1 codec 'aom' speed [6], color quality [85 (High)], alpha quality [100 (Lossless)], tileRowsLog2 [0], tileColsLog2 [0], 1 worker thread(s), please wait...
Encoded successfully.
 * Color AV1 total size: 42766 bytes
 * Alpha AV1 total size: 0 bytes
Wrote AVIF: slider8.avif
```

**Comment by dlemstra** [comment]
I don't see a difference when I view the images that you gave me in chrome? The difference between those images is `0.00917113%`. Maybe there is an issue with your viewer and how we save the image?

**Comment by alexeygritsenko** [comment]
> The difference between those images is 0.00917113%

Xm
> Maybe there is an issue with your viewer and how we save the image?

As I said in 1st message, viewer - it is paint.net (latest version). Okay, I checked it in the browser, it looks a little better here, but I still see that the libavif gives a more original color

**Comment by dlemstra** [comment]
I really don't see a difference in the browser. This library uses `libheif` and that also uses the `aom` library that is used by `libavif`. It might be possible that paint.net has an issue with the images created with `libheif` and not with the `libavif` library. There is not much I can do for you anymore.

And I am probably getting old but what do you mean when you respond with `Xm`?

**Comment by alexeygritsenko** [comment]
Xm - 🤔 (Thinking Face)
Okay, since this cannot be reproduced, I agree to close the question. But I still hold the opinion that the libavif's work is more realistic
