### ISSUE TITLE
MagickImageFactory.CreateAsync() throws exception on non-seekable Streams (MD5Stream/HashStream)

### ISSUE THREAD

**Issue by trnelson** [dlemstra/Magick.NET#1594]
### Magick.NET version

Magick.NET-Q8-AnyCPU 13.6.0

### Environment (Operating system, version and so on)

Linux (AWS Lambda, but others possibly)

### Description

When using the official AWS SDK, calls to `IAmazonS3.GetObjectAsync()` return an instance of `MD5Stream` which inherits from `HashStream` ([Source, line 451](https://github.com/aws/aws-sdk-net/blob/2c3dc520545845cd8ec2da9f7548b4f617efab64/sdk/src/Core/Amazon.Runtime/Internal/Util/HashStream.cs#L451))

When directly creating a MagickImage from this stream, everything works fine:
```csharp
// Works
using var image = new MagickImage(inputStream);
```

However when trying to create a MagickImage from this stream via an instance of `MagickImageFactory`, an exception is thrown due to an attempt to rewind or seek within the stream:

```csharp
// Throws exception
using var image = await magickImageFactory.CreateAsync(inputStream);
```

---

Here is a snippet from the call stack:

```
"HashStream does not support seeking"
...
at Amazon.Runtime.Internal.Util.HashStream.get_Position()
   at ImageMagick.Bytes.<CreateAsync>d__0.MoveNext()
   at ImageMagick.MagickImage.<ReadAsync>d__537.MoveNext()
   at ImageMagick.MagickImageFactory.<CreateAsync>d__20.MoveNext()
```

### Steps to Reproduce

Noted in description above. I imagine any `Stream` type that doesn't allow seek/set position will reproduce a similar issue. If not, a reference to AWS Libraries and usage of `HashStream` should suffice.

**Comment by dlemstra** [comment]
This is a bug in the `HashStream` implementation. The getter of that property should still work. But that is probably not going to be fixed anytime soon. I have removed the check for the position that caused this issues.

**Comment by trnelson** [comment]
Awesome, thanks Dirk.

As a workaround, I’m running the data through another `MemoryStream` before passing into the factory and that works well. Any better recommendations?

This approach does trigger the BMP file size/stream length exception for some reason, but using the ignore length define that you recommended on another issue does the trick.
