### ISSUE TITLE
Support for additional RAW formats

### ISSUE THREAD

**Issue by manfromarce** [dlemstra/Magick.NET#1595]
### Describe the solution you'd like

These RAW image formats are already loaded properly if the input is explicitly set to Raw or Dng, otherwise they are detected as TIFF or other formats and the load could fail:
- FFF (Hasselblad)
- MDC (Minolta)
- MOS (Leaf / Aptos)
- ORI (Olympus)
- RWL (Leica)
- SRW (Samsung)
- STI (Sinar CaptureShop)
File samples can be be found online (they would be quite large to upload), e.g. on https://raw.pixls.us or https://www.rawsamples.ch/index.php/en looking for the manufacturer name.
They are also supported by the Windows Photos app (except for MDC and STI) and other software using libraw.
It would be nice if they were automatically recognized as raw images and were added to the MagickFormat enum so that the format and its properties can be checked at runtime.

**Comment by dlemstra** [comment]
Thanks for request this. The formats will become available in the next release. The only one that I did not add was `ORI` because I think that should be `ORF` and that is already supported?

**Comment by manfromarce** [comment]
Thank you for considering. .ORI is a different extension used by some cameras for the first frame and is produced along with ORF files, it's likely the same format as ImageMagick from command line and other software recognize it when it's renamed to .orf.

**Comment by dlemstra** [comment]
For the `ORF` format we can detect the image type from the header of the file. Do you think we should also add the `.ORI` format to make it more clear this is also supported?

**Comment by manfromarce** [comment]
You can avoid adding Ori explicitly if you don't want to, as I see it is automatically detected as ORF in Magick.NET and it's not very common.
