### ISSUE TITLE
Is here any build in way to prevent potential file corruption by ImageOptimizer.LosslessCompress()?

### ISSUE THREAD

**Issue by InfernumDeus** [dlemstra/Magick.NET#160]
I want to apply `ImageOptimizer.LosslessCompress()` to a big number of files from hard drive.

I've tested it over around 8000 of images and at this point corrupted 1 or 2 files (in different circumstances).

All I do is basically:

```
ImageOptimizer optimizer = new ImageOptimizer();
file.CopyTo(filepath + "_backup", true);
optimizer.LosslessCompress(file);
file.Refresh();
backupFile.CopyTo(filepath, true);
```

I actually handle an exceptions but this is not the point.

First case. There was correct file for sure and after just applying `LosslessCompress()` I got some Exception (can't recall) and found this file corrupted (can't see the image).

Then I decided to implement backup.

Second case. I processed about 7000 images and suddenly got IOException (from `CopyTo()`) referring to data error (message was translated so it may be little different). Looking to the current file I found out that it's corrupted (lower part of image is just gray color).  I wasn't able to track down the exact line of code that led to exception so it's actually possible that file was already corrupted before I used `LosslessCompress()`. I'm also can't copy this file manually.

Now I'm thinking on how to properly handle this part of code. Maybe there is some build in way to prevent such situation? I can use backup file for this but not sure how.

**Comment by dlemstra** [comment]
The `LosslessCompress` method should not overwrite the file if an exception was thrown. Have you seen that your original file was overwritten?

**Comment by InfernumDeus** [comment]
In first case it was for sure. I did nothing else to this file besides `LosslessCompress`. It's also possible that exception was thrown by `file.Refresh()` called after.

Also that happened somewhere in november-december so this is not about last library version.

**Comment by InfernumDeus** [comment]
Also. I think you should specify at some point list of possible exceptions of each public method. Because now I have to catch general `Exception` from this method.

**Comment by dlemstra** [comment]
The method itself will only throw a `MagickException`. But it is possible that the system operations will throw `IOExceptions`.
