### ISSUE TITLE
New NEF Version Not Supported

### ISSUE THREAD

**Issue by tenderlovingzulu** [dlemstra/Magick.NET#1609]
### Magick.NET version

Magick.NET-Q16-AnyCPU 13.6.0

### Environment (Operating system, version and so on)

Windows 11 Home V 10.0.22631 Build 22631

### Description

When new NEF files are scaled and converted to JPG, I get a grainy/corrupted image effect. The newer NEF version is named NIKON Z 8 Ver.02.00. Older NEF versions are supported and process correctly, for example, NIKON D730 Ver.01.01. The program in Steps to Reproduce will run with zero errors or warnings, but the resulting JPG images are corrupted-looking.
![corrupted jpg rendering windows photo viewer](https://github.com/dlemstra/Magick.NET/assets/56776572/63864a39-2bab-41d7-8c72-f9c5475958a7)
![ps cs6 error message trying to open NEF file](https://github.com/dlemstra/Magick.NET/assets/56776572/ceac8a35-5511-48e6-8c5f-32d5dce33476)

### Steps to Reproduce

using ImageMagick;
using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;

namespace TestMagickNET
{
	class Program
	{
		#region Variables

		static string warning;

		#endregion

		static void Main(string[] args)
		{
			var files = new string[] {
				@"[path/to/NEF]"
			};

			foreach (var file in files)
			{
				try
				{
					using (var img = new MagickImage())
					{
						// try opening image, detecting warning.

						img.Warning += MagickImageCollection_Warning;
						warning = "false";
						img.Read(file);

						if (warning != "")
						{
							// opened image with no warning.

							Console.WriteLine("Success: " + file);

							// resize and save as web jpg.

							img.Scale(0, 640);
							img.Density = new Density(96);
							img.Quality = 90;
							img.SetProfile(ColorProfile.SRGB);
							img.ColorSpace = ColorSpace.sRGB;
							img.Write(Path.ChangeExtension(file, "jpg"));
						}
					}
				}
				catch (System.Exception e)
				{
					Console.WriteLine("Error opening " + file + ".");
					Console.WriteLine("Error: " + e.Message);
				}
			}
		}

		private static void MagickImageCollection_Warning(object sender, WarningEventArgs e)
		{
			warning = "MagickImage Warning opening file " + ((MagickImage)sender).FileName + ".\nMessage: " + e.Message;
		}
	}
}

**Comment by dlemstra** [comment]
You will need to wait for [libraw](https://github.com/LibRaw/LibRaw) to add support for this and publish a new release. We are using that library to read raw files. If you ask for support there it would probably also be a good idea to include a sample image.

**Comment by tenderlovingzulu** [comment]
Thank you! I will do that.

**Comment by tenderlovingzulu** [comment]
I posted the same support request on the libraw developer's github account.
They asked me two questions. I tried to find these answers in Magick.NET
documentation but was unable to find it.

Which version of LibRaw library is used in the process?
What is the list of supported cameras and raw types ("formats")?

**Comment by dlemstra** [comment]
Version `0.21.2` of libraw is being used. I have no idea what they mean by formats. We support all the formats that are available in their library. Make sure you also add a sample image they can use to test?

**Comment by tenderlovingzulu** [comment]
Thanks for the tip!  I'll do that.

**Comment by tenderlovingzulu** [comment]
I get the following response back from the LibRaw developer: " You're using
an outdated LibRaw version, please consider upgrade to the latest snapshot"

**Comment by tenderlovingzulu** [comment]
I got more information from the LibRaw developer. He says the Nikon Z8
format is not implemented in LibRaw yet. Thanks for helping figure this
out. Always appreciate your help!

**Comment by tenderlovingzulu** [comment]
Additional note from LibRaw developer: "Nikon Z8 standard/lossless
compression is supported in 202403 snapshot"

**Comment by dlemstra** [comment]
I just gave the snapshot a try and it turns out your image file is a `HE/HE*` format and that doesn't seem to be supported yet. No idea why that isn't supported yet but they might add this in a future release.
