### ISSUE TITLE
Compression not lossless in this case

### ISSUE THREAD

**Issue by dabutvin** [dlemstra/Magick.NET#161]
Came across a case that didn't come out completely lossless when running `LosslessCompress()`

see https://github.com/mochajs/mocha/pull/3175#issuecomment-354375240

![image](https://user-images.githubusercontent.com/5168796/36066457-c2908c88-0e5e-11e8-9289-1a1695416ef5.png)

**Comment by dlemstra** [comment]
Just did a compare of a before and after compress of the image and I have no idea which colors have been lost. The alpha channel has been removed but there were no transparent pixels so that should not be an issue. I think that project was just not happy that we removed the unnecessary information.

**Comment by dabutvin** [comment]
Thanks for looking into it @dlemstra

That's what I thought!

I showed it to a few people and they said they could see the difference. Like the richness of the color is different somehow.

I can't see it myself, but they say everyone perceives colors differently.

**Comment by dabutvin** [comment]
Okay so I dug a little more into this - it was bugging me that so many people believed they could see the color difference even though you found out there was none :)

Turns out, the green vs red borders around the images for added/removed indication was causing some people to perceive the browns as darker in one of the images.

Not that it matters much, but I thought it was pretty interesting.

Thanks again for checking it out.

**Comment by dlemstra** [comment]
I was also wondering if the border could cause that. Thanks for checking that out, interesting side story :)
