### ISSUE TITLE
Hope to support converting ESP files to PNG format

### ISSUE THREAD

**Issue by Sunsh4j** [dlemstra/Magick.NET#1613]
### Describe the solution you'd like

I have imagemagick on one computer, which can convert esp files to png format, but when I try to do the conversion operation on another computer using Magick.NET, the conversion fails!

**Comment by dlemstra** [comment]
It is using Ghostscript and you probably have installed that on one of the computers. Please be aware you will need a license for that software if you use it commercially.

**Comment by dlemstra** [comment]
The Magick.NET library uses Ghostscript to read the pdf files.
