### ISSUE TITLE
Image quality and transparency issues when moving from windows to linux

### ISSUE THREAD

**Issue by Anu6is** [dlemstra/Magick.NET#162]
Are there additional files that need to be installed on Linux for things to work 100%.
Using the same code, when on [Windows](https://cdn.discordapp.com/attachments/379592187664400397/412434730026401792/412434726570295306_1F575.png) everything is perfect, however, once deployed on [Linux](https://cdn.discordapp.com/attachments/379592187664400397/412430626210185217/412430620451667968_1F575.png) quality is reduced and I am unable to get a transparent background.  

Any thoughts?  
```vb  
Dim inputStream = Await client.GetStreamAsync(url)
        Dim settings As New MagickReadSettings With {
                .Width = 300,
                .Height = 300,
                .BackgroundColor = MagickColors.Transparent
        }
        Using outputStream As New MemoryStream
                Using image As New MagickImage(inputStream, settings)
                        image.Format = MagickFormat.Png
                        image.Write(outputStream)
                        outputStream.Position = 0
                        Await Context.Channel.SendFileAsync(outputStream, $"test.png")
                 End Using
        End Using
End Using
```

**Comment by dlemstra** [comment]
What is your input image? And which version of Magick.NET / ImageMagick are you using?

**Comment by Anu6is** [comment]
[SVG Input](https://raw.githubusercontent.com/twitter/twemoji/gh-pages/2/svg/1f575.svg)  
I'm using the latest versions of Magick.NET and ImageMagick (i.e. 7.4.x)

**Comment by dlemstra** [comment]
Did you compile ImageMagick with libsrvg support?

**Comment by Anu6is** [comment]
Is there an easy way to confirm that?

**Comment by dlemstra** [comment]
ldd should show a link with librsvg. If that is missing you will need to recompile ImageMagick with `--with-rsvg`. And if that is `no` in the configure output you will need to install librsvg.

@superstator Can you also add librsvg to the statically linked projects?

**Comment by Anu6is** [comment]
Alright, thanks. Will recompile when I can.
