### ISSUE TITLE
colors.xml missing?

### ISSUE THREAD

**Issue by flytzen** [dlemstra/Magick.NET#1628]
### Magick.NET version

13.7.0

### Environment (Operating system, version and so on)

Any

### Description

When trying to build from source, I get this error:
`Could not find a part of the path 'C:\CodeMagick.NET\src\Magick.Native\resources\ReleaseQ8\colors.xml`

### Steps to Reproduce

1. Do a clean checkout from GitHub into Windows
2. Open in VS 2022
3. Try to build 
I have tried with a few different build configurations.

This may be user error - apologies in advance.
I was trying to do this to hopefully contribute a PR for #1627 - although I can see you have already fixed it :D

**Comment by dlemstra** [comment]
There is a document that describes the steps for contributing and building this repository but it might not have the best name. I just pushed a patch to rename the document to `CONTRIBUTING.md`.
