### ISSUE TITLE
Possible bug with forced casting on IChannelPerceptualHash

### ISSUE THREAD

**Issue by Gounlaf** [dlemstra/Magick.NET#1629]
### Magick.NET version

13.6.0 (since 0fcf386b)

### Environment (Operating system, version and so on)

All

### Description

Since commit 0fcf386b, `ChannelPerceptualHash.SumSquaredDistance` force casting of parameter `IChannelPerceptualHash` to implementation `ChannelPerceptualHash` :

https://github.com/dlemstra/Magick.NET/blob/0fcf386b4a0ae831e6799e9b4b31e34c5ad72cb5/src/Magick.NET/Statistics/ChannelPerceptualHash.cs#L97-L104

It breaks interface contract.

I don't have a solution to suggest =/

Regards. 

### Steps to Reproduce

N/A

**Comment by dlemstra** [comment]
Not doing the cast would force me to expose the `HuPhashList` that nobody will want to use. So I took this shortcut. Creating an interface for the `HuPhashList` is probably a better solution. I will take a look at this next week.

**Comment by dlemstra** [comment]
I just pushed a commit that uses a different approach to avoid the typecast.

**Comment by Gounlaf** [comment]
Your solution is elegant :+1:
