### ISSUE TITLE
Can't  thumbnail pic.

### ISSUE THREAD

**Issue by Ruikuan** [dlemstra/Magick.NET#163]
Hi all.
It's my first time using Magick.NET. I create a new .NET Framework 4.6.2 console project, install Magick.NET-Q8-AnyCPU using Nuget. My code is like this:
```cs
static void Main(string[] args)
{
    using (MagickImage image = new MagickImage(@"F:\Temp\20170627205900.jpg"))
    {
        int width = image.Width < 120 ? image.Width : 120;
        int height = image.Height < 120 ? image.Height : 120;
        image.Thumbnail(width, height);
        string outpuPath = @"F:\Temp\20170627205900_s.jpg";
        image.Write(outpuPath);
    }
}
```
Then I press F5 to run the application. It is stuck on this line, with cpu usage always 100%, and memory usage increasing.
```cs
image.Thumbnail(width, height);
```
![image](https://user-images.githubusercontent.com/7594271/36083000-708552ca-0fe9-11e8-818c-d77fccf31983.png)

I have tried version 7.40/7.30/7.21, and also try Magick.NET-Q8-x64, but they all perform the same. I don't know how to solve this.

My OS is Win10 x64 1709. My example picture is this:
![20170627205900](https://user-images.githubusercontent.com/7594271/36083226-61fe2ba8-0feb-11e8-9546-6492367bbc92.jpg)

Thanks to reply.

**Comment by Ruikuan** [comment]
And then I create a dotnet core 2.0 console project, It's the same as above-mentioned.

**Comment by Ruikuan** [comment]
Finally I solve this. 
I just let it run. After about a minute of CPU 100% usage, it finally has the work done.
And then all the thumbnail after finish very fast! So the problem is not existed any more.
But I still don't know what happen...

**Comment by dlemstra** [comment]
Some methods can use OpenCL (GPU) and this is happening because the first time your run the application it will benchmark your GPU and CPU to determine if it is faster to use the GPU or the CPU. This will happen the first time you use a Magick.NET on a machine. You can avoid this by setting `OpenCL.IsEnabled` to false.
