### ISSUE TITLE
Probable bug with TemporaryMagickFormat?

### ISSUE THREAD

**Issue by Gounlaf** [dlemstra/Magick.NET#1641]
### Magick.NET version

N/A

### Environment (Operating system, version and so on)

N/A

### Description

_(sorry still don't know if a Discussion or an issue is more suitable for this kind of questions...)_

:wave: 

I'm wondering why only `image.Format` is set, but not `image.Settings.Format`; but both are reset to original value.

https://github.com/dlemstra/Magick.NET/blob/007bf2278cfdd9c06cd4928df04459edbbe50254/src/Magick.NET/Helpers/TemporaryMagickFormat.cs#L42-L46

https://github.com/dlemstra/Magick.NET/blob/007bf2278cfdd9c06cd4928df04459edbbe50254/src/Magick.NET/Helpers/TemporaryMagickFormat.cs#L61-L65

Regards.

### Steps to Reproduce

N/A

**Comment by dlemstra** [comment]
This should be done because it is possible that the `image.Settings` had a different value. When `image.Format` is set this also sets the format of the settings. This make sure that both have their original value. I have added a comment to the code to make this more clear.
