### ISSUE TITLE
Setting ResourceLimits.Thread does not work. Value stays the same

### ISSUE THREAD

**Issue by IamMartinPeek** [dlemstra/Magick.NET#1643]
### Magick.NET version

13.8.0

### Environment (Operating system, version and so on)

Windows/MacOs

### Description

Hi!

When i want to set the Thread limit with ResourceLimits.Thread = 2 (or something else) it does not change anything. When I check the value afterwards it stays on 1 no matter what I am setting.

### Steps to Reproduce

Set ResourceLimits.Thread to a differen value than 1.
Check if it changed.

**Comment by dlemstra** [comment]
On MacOS OpenMP is not supported and that is why the value will always return `1`. And you also cannot increment the value. The initial value that is returned is the maximum number of threads.

**Comment by IamMartinPeek** [comment]
Hey thanks for the fast reponse. Does this also apply to running into a docker linux container ? :)

**Comment by dlemstra** [comment]
Linux has OpenMP support but you will need to target the version with OpenMP support.
