### ISSUE TITLE
Writing WebP-Files on ARM-Container with auto orient fails

### ISSUE THREAD

**Issue by IamMartinPeek** [dlemstra/Magick.NET#1648]
### Magick.NET version

Magick.NET-Q8-AnyCPU-13.8.0

### Environment (Operating system, version and so on)

MacOS Docker

### Description

Hello!

On some images an Exception is thrown when image is written to a stream (await image.WriteAsync(fileStream)).
It seems like this only happens when running it on Mac/Arm as on Windows this runs without any issue. The application runs within docker as well.

I also found out that the issue only happens, when i am using image.AutoOrient() so it has to be related with that. 

Following stacktrace is printed:

```
ImageMagick.MagickCorruptImageErrorException:  `' @ error/webp.c/WriteSingleWEBPImage/889
2024-05-31T09:22:08.938040347Z          at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:line 18
2024-05-31T09:22:08.938041388Z          at ImageMagick.NativeHelper.CheckException(IntPtr exception) in /_/src/Magick.NET/Native/NativeHelper.cs:line 27
2024-05-31T09:22:08.938042847Z          at ImageMagick.MagickImage.NativeMagickImage.WriteStream(IMagickSettings`1 settings, ReadWriteStreamDelegate writer, SeekStreamDelegate seeker, TellStreamDelegate teller, ReadWriteStreamDelegate reader, Void* data) in /_/src/Magick.NET/Native/MagickImage.cs:line 8746
2024-05-31T09:22:08.938044263Z          at ImageMagick.MagickImage.NativeMagickImage.WriteStream(IMagickSettings`1 settings, ReadWriteStreamDelegate writer, SeekStreamDelegate seeker, TellStreamDelegate teller, ReadWriteStreamDelegate reader) in /_/src/Magick.NET/MagickImage.cs:line 7688
2024-05-31T09:22:08.938045472Z          at ImageMagick.MagickImage.ToByteArray() in /_/src/Magick.NET/MagickImage.cs:line 6550
2024-05-31T09:22:08.938046347Z          at ImageMagick.MagickImage.WriteAsync(Stream stream, CancellationToken cancellationToken) in /_/src/Magick.NET/MagickImage.cs:line 7145
2024-05-31T09:22:08.938047263Z          at ImageMagick.MagickImage.WriteAsync(Stream stream) in /_/src/Magick.NET/MagickImage.cs:line 7132
```

### Steps to Reproduce

- Use ARM Container
- Use image with orientation exif tag (.jpg)
- Use image.AutoOrient()
- Convert it to webp
- Use image.WriteAsync()

**Comment by dlemstra** [comment]
This project has unit tests that run on the GitHub hosted runners and all of them are passing 

Is it possible that you are using the Native binaries of the previous release? The signature of the native `WriteStream` method has changed and now includes an extra argument. Calling the old native library with the new arguments could result in unexpected behavior.

Is it possible to share a project with a Dockerfile that can reproduce this?

**Comment by IamMartinPeek** [comment]
@dlemstra Thanks for your fast answer! I will prepare a project for you to reproduce. Will come back to you in a few hours.

**Comment by IamMartinPeek** [comment]
@dlemstra Hey so I could reproduce it here: https://github.com/IamMartinPeek/net-image-magick-auto-orient-bug

I also figured out, that the behaviour only appears when i am not activly setting a specific height. I also commented this: 
https://github.com/IamMartinPeek/net-image-magick-auto-orient-bug/commit/d8ec724464ce99e1e810285fff49f41c5d04a5c0

So it seems to be a combination of AMD + Not setting the Height + AutoOrientation

**Comment by dlemstra** [comment]
I am able to reproduce this bug inside a GitHub MacOS arm64 runner. The problem here is that the issue looks like something inside the webp encoder. I did not notice this earlier:

> Unhandled exception. ImageMagick.MagickCorruptImageErrorException:  `' @ error/webp.c/WriteSingleWEBPImage/889

It means that the call to `WebPEncode` of the `webp` library failed. I suspect it has to do with the dimensions of the image. It cannot handle the size `1920x2880` but has no problem when the size of the image is `1080x1620`. So there might be a bug somewhere but I also wonder why we are not getting a good error message so I will need to investigate that. And it might also be interesting to check if this is bug can be reproduced on an x64 MacOS runner. That will probably make it easier for the webp team to figure out what is going on.

Maybe you can play around with the webp encoder binaries and try to reproduce the same issue there?

**Comment by IamMartinPeek** [comment]
@dlemstra Thanks again for the fast response. Thats interesting. Does this anyhow make sense with the 2 fixes that I had ? Like passing a height activly or switching the order of the resize/autoOrient call ?

**Comment by IamMartinPeek** [comment]
Yeah of course they are not fixes but its interesting, that the behaviour changes it seems like its either the width or the height that cause the bug and depending on when i use autoorient the image is fine or not

**Comment by dlemstra** [comment]
I figured out what was causing this and you were sending me in the wrong direction 😉 The issue is this statement:

```C#
ResourceLimits.MaxMemoryRequest = 20000000;//20 Megabyte
```

Because of the size of the image the memory allocation fails. And on arm64 macOS the memory isn't swapped to disk. I just pushed a patch to ImageMagick that should have made that error a lot more clear. And the reason that you need a lot of memory is because all the pixels of the images are copied to the webp encoder at once instead of per row.

**Comment by IamMartinPeek** [comment]
@dlemstra Hey! Thanks a lot for the investigation. I guess this will be fixes somehow ? So at the moment this means, that every image that i want to convert is loaded completly into the memory ?

I am currently working on a server application that needs to convert a lot of images simultaniously so performance at resource management is crucial for me... Do you have any suggestions on some best practices regarding this ?

**Comment by dlemstra** [comment]
The `ResourceLimits` are globals so my advise would be to not set this value and leave it at the default. Or set it to a higher value that would work for you output images.

**Comment by IamMartinPeek** [comment]
@dlemstra Yeah but you said it does not work on Mac/Arm. The reason to set this value is to reduce the pressure on the Ram and read from disk isnt it ? If I would set it to 100 MB for example, I would load Images which are 100 MB big in to memory right ? So how to keep the memory usage low then ?

**Comment by dlemstra** [comment]
Normally you can limit the amount of memory that can be allocated and Imagemagick will swap to disk. But this doesn't seem to happen with arm64 MacOS. I just check through the build logs and it seems that `mmap` is not found. And when asking GitHub copilot why this happens it tells me to use `vm_map` instead but that will probably require some change to ImageMagick.

It might also be a good idea to limit the width/height of the image to prevent images with large dimensions being loaded instead.

**Comment by dlemstra** [comment]
I meant `ResourceLimits.Height` and `ResourceLimits.Width` and I cannot give you an advise for the value. That all depends on how many pixels you want in your input images?

**Comment by IamMartinPeek** [comment]
@dlemstra Well I am using them for high resolution images from photographers which can be anywhere between 2000-20000x2000-20000 pixels, but the idea of this values would be to align them with the memory that i have available in my system. So can i not actually calculate this somehow based on my system resources ?

**Comment by dlemstra** [comment]
I don't understand why you would want to set those values? ImageMagick should set them to reasonable default values.

**Comment by IamMartinPeek** [comment]
@dlemstra I want to set them to control the resource use of the library. So your approach is that the library sets the default values in a good way? Does the library actually calculate Ram and Cpu of the system ?

**Comment by dlemstra** [comment]
It does make some system calls to get information about the operating system. And the includes the available ram and cpu.
