### ISSUE TITLE
Error 504 when convert ARW to jpg

### ISSUE THREAD

**Issue by akks504** [dlemstra/Magick.NET#1651]
### Magick.NET version

13.9.0

### Environment (Operating system, version and so on)

windows 10 x64

### Description

When attempting to convert an ARM file to jpg format, an error message may appear stating: "Unsupported file format or not RAW file 'C:/Downloads/DSC00401.ARW'@ error/dng.c/ReadDNGImage/504".

Note : This error message pertains to a single file rather than all files. While certain online tools can successfully convert the file, Magick.NET encounters difficulties with it.

### Steps to Reproduce

Just convert ARW to JPG

**Comment by dlemstra** [comment]
It looks like there is no support for this format in libraw (https://github.com/LibRaw/LibRaw). This project uses version `0.21.2` of that library. I think you should report this upstream.

**Comment by akks504** [comment]
Hello 

Hope you doing well

This project uses version **0.21.2** of that library

LibRaw says this issue is fixed but Magick.NET encounters difficulties 

LibRaw mention in below comment

https://github.com/LibRaw/LibRaw/issues/653#issuecomment-2167211401

**Comment by dlemstra** [comment]
I have updated libraw to that snapshot and this file can now be read. With the next release you will be able to read this file. But it might take a while before that will be released.

**Comment by akks504** [comment]
when should we expect the release

**Comment by dlemstra** [comment]
There is no planned release so I don't know.

**Comment by akks504** [comment]
issue verified working properly
