### ISSUE TITLE
PCX support fails between 7.3 and 7.4

### ISSUE THREAD

**Issue by jimdurrell** [dlemstra/Magick.NET#166]
When reading any of several PCX files in 7.4, they appear as most black images with perhaps some of the image on the edge.  The same files read properly in 7.3.  The issue was reproduced in MagickViewer as well.  A sample PCX file is attached.

[HG-828.zip](https://github.com/dlemstra/Magick.NET/files/1720376/HG-828.zip)

**Comment by dlemstra** [comment]
MagickViewer is using 7.2.1 and can read your file without any issues. We made some security patches in PCX so maybe we broke something there. Will take a look if I can reproduce this.

**Comment by jimdurrell** [comment]
Wow, thanks for the fast response.  I recompiled MagickViewer and my own code with 7.3, and that seemed to work.  Hopefully that helps narrow your search.

**Comment by dlemstra** [comment]
Found and fixed the issue. Will try to publish a new release as soon as possible.

**Comment by dlemstra** [comment]
I just published a new release (7.4.1.0) that includes a fix for this issue.
