### ISSUE TITLE
AutoOrient does not work for Heic images

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1662]
### Magick.NET version

13.9.1

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2

### Description

AutoOrient() not work

### Steps to Reproduce

[HEIC_rotation.zip](https://github.com/user-attachments/files/16023277/HEIC_rotation.zip)

![1](https://github.com/dlemstra/Magick.NET/assets/19963715/c37ac17a-a8d8-4746-9384-92d526551dd5)

**Comment by dlemstra** [comment]
Thanks for sharing the images but I have no idea what your issue is?

**Comment by Charltsing** [comment]
> Thanks for sharing the images but I have no idea what your issue is?

AutoOrient()，The image should automatically rotate in the direction of the arrow, with the arrow pointing upwards

i test jpg , it work fine.  but heic it not work fine

**Comment by dlemstra** [comment]
Heic images should automatically be orientated to the right direction? Please provide a small code sample that demonstrates your issue?

**Comment by Charltsing** [comment]
I don't quite understand the definition of the orientation tag in the heic image format.

90.heic as an example, the default rotation of this image is 270 degrees
My understanding is that after using AutoOrient or not using AutoOrient, the image should be displayed in different directions. Either the arrow direction of the image after using AutoOrient is left, or the arrow direction of the image without AutoOrient is left. 
But the arrow direction should not be left in both cases.

Maybe there is something wrong with my understanding of AutoOrient?

**Comment by dlemstra** [comment]
Heic images are automatically "auto oriented" when they are being read.

**Comment by Charltsing** [comment]
This question comes from [here](https://github.com/d2phap/ImageGlass/issues/1928)

**Comment by Charltsing** [comment]
i set PreserveOrientation = false, The orientation of the images is correct
settings.SetDefines(new HeicReadDefines
{
    PreserveOrientation = false,
});

so, AutoOrient is invalid for heic ? 

BaseWidth is always the same as Width ( PreserveOrientation = false or true ), I think there should be at least one case where BaseWidth should not be the same as Width,  (  Openize.HEIC---- ispeWidth not same as Width )

**Comment by dlemstra** [comment]
`BaseWidth` and `BaseHeight` will return the original `Width` or `Height` that was read. The library that we are using to read heic files will automatically read the image in `TopLeft` orientation and has a special flag to disable this behavior (`PreserveOrientation`).  And then you might need to use `AutoOrient `. But it is recommended to just let the heic coder decide this.

**Comment by Charltsing** [comment]
AutoOrient() does not work (PreserveOrientation = false), MagickImage.Orientation  is always TopLeft

So I cannot know if the direction of 90.heic is rotating 270 degrees

PreserveOrientation = false will lost hiec Original orientation information ?

**Comment by dlemstra** [comment]
I finally had some time to take a deeper look at what you were asking. The `Orientation` should not be `Undefined` when you set the `PreserveOrientation` option but it looks like we never implemented something in ImageMagick to read that information. I just pushed a patch to the ImageMagick repository to add support for this. You will get the correct orientation in the next release when you specify `PreserveOrientation`.
