### ISSUE TITLE
How to convert huge image to Bmp format ?

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1671]
### Magick.NET version

13.8.0

### Environment (Operating system, version and so on)

Windows10 64bit,  netframework 4.7.2, 
x64,  8G memory
Magick.NET-Q16-AnyCPU.dll, Magick.Native-Q16-x64.dll, 13.8.0
ImageMagick.ResourceLimits.LimitMemory = 85%

I have a huge jpg file w26493x h37200, 279M    [37200.JPG](https://pan.baidu.com/s/1DabRBsWBNW_qlrfX-n_KCQ?pwd=x1gq)

```
MemoryStream outstream = new MemoryStream();
byte[] picbyte = File.ReadAllBytes("37200.jpg");
using (MagickImage magickimage = new MagickImage())
{
      magickimage.Read(picbyte);
      magickimage.Write(outstream, MagickFormat.Bmp);  
      // outstream.Length = 2,147,475,594 , 
      // Perhaps the length of outstream is incorrect. 26493 x 37200 x 3 = 2,956,618,800。
      // Is there a 2G limit for out stream ?

      Bitmap bmp = new Bitmap(outstream);   // it report invalid parameter error
}
```
![11](https://github.com/dlemstra/Magick.NET/assets/19963715/31e0088b-d7f6-4f76-acbe-0ec05aab8f8b)

![2](https://github.com/dlemstra/Magick.NET/assets/19963715/bf8d6929-5b4a-48df-9ecc-22191d5c7b04)

I try add gcAllowVeryLargeObjects in App.Config, but  it didn't work
<gcAllowVeryLargeObjects enabled="true" />

try  Bitmap.FromFile("37200.jpg");
it report error : System.OverflowException.

----

then  I try net8, x64, Magick.Native-Q16-HDRI-OpenMP-x64.dll, 13.9.1  
```
MagickImage imageM = new ();
byte[] raw = File.ReadAllBytes("37200.jpg");
imageM.Read(raw); 
```
it report error : 
ImageMagick.MagickCacheErrorException:“unable to extend cache '': Invalid argument @ error/cache.c/OpenPixelCache/3925”
![31](https://github.com/dlemstra/Magick.NET/assets/19963715/55e5fda3-5145-46f7-bd32-38acddc177a9)

Did I do something wrong ? Is this error related to memory size ?

**Comment by dlemstra** [comment]
You are running into the memory limits of a `MemoryStream`. The length of a `MemoryStream` can not be larger than `int.MaxValue`.

**Comment by Charltsing** [comment]
so, How to convert huge image to Bmp format?

**Comment by dlemstra** [comment]
You are running into limitations of .NET. There is not much I can do about that. There might be custom implementations of `MemoryStream` that support more than 2GB but you will need to find that yourself.
