### ISSUE TITLE
Does 13.8.0 no longer create cache files to process images?

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1672]
### Magick.NET version

13.8.0

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2, 8G Memory

### Description

i test huge image

```
byte[] picbyte = File.ReadAllBytes("37200.jpg");
using (MagickImage magickimage = new MagickImage())
{
    magickimage.Read(picbyte);
//Magick.NET-Q16-HDRI-OpenMP-x64 13.9.1 report errors quickly: ImageMagick.MagickCacheErrorException:“unable to extend cache '': Invalid argument @ error/cache.c/
// Q16-OpenMP-x64 13.9.1 and Q16-x64 13.8.0 and Q16-x64 13.7.0 work fine

    magickimage.Resize(new Percentage(50));
// Magick.NET-Q16-x64 13.8.0 report errors quickly: unable to extend cache '': Invalid argument @ error/cache.c/OpenPixelCache/3925

// Magick.NET-Q16-x64 13.7.0 creat chahe files in TEMP folder (magick-bEXGydxxQn5LsZgmdyXV8gP0UvrUA7JF  2887433kb, magick-IZ3tpGQWhF0Ry2OY6nKf2IQI_Naq00bY  1443717kb) and finish resizing after 15 minutes
}
```

How to make 13.8.0  create cache files and execute resizing ?

**Comment by dlemstra** [comment]
Can you share your input image that can be used to reproduce this?

**Comment by Charltsing** [comment]
https://pan.baidu.com/s/1DabRBsWBNW_qlrfX-n_KCQ?pwd=x1gq

**Comment by dlemstra** [comment]
Thanks for sharing the files here. I think you can also upload the files by renaming `37200.z02` to `37200.z02.zip`. But maybe GitHub changed that behaviour.

**Comment by Charltsing** [comment]
[37200.z02.zip](https://github.com/user-attachments/files/16139216/37200.z02.zip)
This is a good idea. 
It's just that some other cloud disk don't support this approach, so I'm used to compressing them into zip files again

**Comment by dlemstra** [comment]
It will take a lot of time when memory is swapped to disk. This is much slower than using the memory of your machine. I don't think your idea/feature request is going to work due to the current architecture of ImageMagick. It will need to read the whole image before something can be done with the image and that will still require a lot of memory for large images.

**Comment by Charltsing** [comment]
The current test results show that using cache files  to process large images has no practical value.

Maybe ImageMagick can write a special project in the future specifically for splitting large images, implementing the function of reading images and splitting and saving using less memory. Of course, this will take a long time and more effort.

Thank you for your excellent work.

**Comment by dlemstra** [comment]
Use cache files has value and is used for systems with a low amount of memory. The only downside is that it slow because of all the IO that is happening. And a lot of forwards don't support decoding an area of an image so it is very unlikely that this will be added to ImageMagick.
