### ISSUE TITLE
ExtractArea with x and y = 0 returns the entire image instead of the extracted part

### ISSUE THREAD

**Issue by zenoxs** [dlemstra/Magick.NET#1674]
### Magick.NET version

13.9.1, Magick.NET-Q8-AnyCPU

### Environment (Operating system, version and so on)

WSL Debian

### Description
When using the `MagickReadSettings` with the `ExtractArea`  set to x and y = 0, the created image is the entire image resized by the specified width and height instead of the extracted part. This issue only occurs when x and y are both set to 0. If x is set to 1, the output image is correct.

I also tried with the Magick CLI directly, and everything works as expected.
`magick -extract 256x256+0+0 ./demo.png extracted.jpg`

### Steps to Reproduce

`demo.png`
![demo.png](https://github.com/dlemstra/Magick.NET/assets/12350021/31ba992b-58ba-495c-87bc-b16a81e7cce7)

```csharp
MagickReadSettings settings = new MagickReadSettings
{
    // ExtractArea = new MagickGeometry("256x256+0+0")
    ExtractArea = new MagickGeometry(
        x: 0,
        y: 0,
        width: 256,
        height: 256
    )
};

using var image = new MagickImage("demo.png", settings);

await image.WriteAsync("extracted.jpg");
```
Result:
![extracted.jpg](https://github.com/dlemstra/Magick.NET/assets/12350021/4250b5f9-68a8-49a3-9832-a617d1f1e4aa)

Expected:
![expected output](https://github.com/dlemstra/Magick.NET/assets/12350021/840253e5-1946-4605-b881-9749b59eee33)

**Comment by dlemstra** [comment]
It looks like there is a difference for ImageMagick between `256x256+0+0` and `256x256` for `ExtractArea`. And when calling ImageMagick the `+0+0` is only added when those values are set. I suspect I will need to refactor the `MagickGeometry` to make this work. And always send the `+0+0` when it has been specified by the users and otherwise I shouldn't. But this could be a breaking change for someone who has been doing this "by accident". I will need some time to think about this but I think I can only make this change in a major release. Or we need to add a "magic boolean" for this behavior.

**Comment by dlemstra** [comment]
Another option would be to only do this when a constructor overload with both `x` and `y` is used. This will probably reduce the impact this change will have on other users.

**Comment by zenoxs** [comment]
> Another option would be to only do this when a constructor overload with both `x` and `y` is used. This will probably reduce the impact this change will have on other users.

Thanks for the quick reply!

This solution sounds good to me. For now, I do not have any workaround to deal with this issue other than setting the x value to 1 when it is equal to 0. I understand that this could be a breaking change for some users, but the current behavior is more likely to cause errors. 
(In my case I am using the `MagickReadSettings` to split a very large image into several tiles for tile map layer)

**Comment by dlemstra** [comment]
I decided to include `x` and `y` when it's zero in `toString()` when it is specified in one of the constructors. This will become available in the next release.

**Comment by zenoxs** [comment]
Amazing, thanks for the support 👏
