### ISSUE TITLE
read a avif  error ,use  MagickImage.Read(rawbytes);

### ISSUE THREAD

**Issue by Charltsing** [dlemstra/Magick.NET#1690]
### Magick.NET version

13.10.0

### Environment (Operating system, version and so on)

Windows10, net framework 4.7.2

### Description

read a avif as bytes data  report error,  use  MagickImage.Read(rawbytes);
read it as file work fine

[avif-error.zip](https://github.com/user-attachments/files/16504600/avif-error.zip)

ImageMagick.MagickMissingDelegateErrorException
  HResult=0x80131500
  Message=no decode delegate for this image format `' @ error/blob.c/BlobToImage/481
  Source=Magick.NET-Q16-OpenMP-x64
  StackTrace:
   在 ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   在 ImageMagick.MagickImage.NativeMagickImage.ReadBlob(IMagickSettings`1 settings, Byte[] data, UIntPtr offset, UIntPtr length)
   在 ImageMagick.MagickImage.Read(Byte[] data, UIntPtr offset, UIntPtr length, IMagickReadSettings`1 readSettings, Boolean ping, String fileName)
   在 ImageMagick.MagickImage.Read(Byte[] data, IMagickReadSettings`1 readSettings)
   在 ImageMagick.MagickImage.Read(Byte[] data)

### Steps to Reproduce

..

**Comment by dlemstra** [comment]
That is because ImageMagick cannot detect the format from the header and uses the file extension to guess the format. You will need to specify the format.

**Comment by Charltsing** [comment]
ImageMagick can recognize the other sample.avif and sample2.avif, but cannot recognize sample3.avif. Is it possible to enhance the read function?

[avifs.zip](https://github.com/user-attachments/files/16507292/avifs.zip)

![1](https://github.com/user-attachments/assets/a6ca3b95-0199-4266-aa42-a54889114655)
![2](https://github.com/user-attachments/assets/058d63b4-2072-4144-a4ad-1d7b56528628)
![3](https://github.com/user-attachments/assets/c61d672f-0dfb-403a-bc3b-aa064e557239)

**Comment by dlemstra** [comment]
I will need to investigate if that is possible. I already made other enhancements earlier.

**Comment by dlemstra** [comment]
And it turned out that it was easy to add support for this. In the next release you can read this file from a byte array:

```
sample HEIC 123x456 123x456+0+0 8-bit sRGB 13159B 0.001u 0:00.001
sample2 AVIF 800x533 800x533+0+0 8-bit sRGB 113604B 0.001u 0:00.000
sample3 AVIF 1280x720 1280x720+0+0 8-bit sRGB 409566B 0.001u 0:00.000
```
