### ISSUE TITLE
Slow AVIF performance

### ISSUE THREAD

**Issue by vanillajonathan** [dlemstra/Magick.NET#1696]
### Magick.NET version

Magick.NET-Q8-AnyCPU 13.10.0

### Environment (Operating system, version and so on)

Windows 11, 23H2

### Description

The performance of transcoding to AVIF is very poor. When I call `Write` with `MagickFormat.Avif` the performance is very poor, it takes seconds for each image, but when I use `MagickFormat.Png` or `MagickFormat.Jpeg` then it is much faster.

### Steps to Reproduce

```csharp
using (var collection = new MagickImageCollection("example.tiff"))
{
    foreach (var image in collection)
    {
        var ms = new MemoryStream();
        image.Write(ms, MagickFormat.Avif);
    }
}
```

**Comment by dlemstra** [comment]
That is the expected behavior. The AVIF coder takes a lot of time to encode images. This is done by an external library used by ImageMagick and there is not much we can do to improve the performance for that.
