### ISSUE TITLE
Issues with circle cropped images & resize

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#17]
I have updated my code with the latest version of Magick.NET (7.0.2.100).
I'm trying to crop an image with a circle and resize it. I made a sample reproduction code:

```
static void Main(string[] args)
{
    MagickImage image;
    using (image = new MagickImage(SampleFiles.FujiFilmFinePixS1ProJpg))
    {
        image = GenerateCircleImage(image);
                
        image.Resize(300, 0);

        image.Write(SampleFiles.OutputDirectory + "FujiFilmFinePixS1Pro.resized.jpg");
    }
}
public static MagickImage GenerateCircleImage(MagickImage image)
{
	using (var maskImage = new MagickImage(MagickColors.Black, image.Width, image.Height))
	{
		maskImage.Draw(new IDrawable[]{ 
			new DrawableFillColor(MagickColors.White),
			new DrawableCircle(300, 200, 100, 200)
		});

		image.VirtualPixelMethod = VirtualPixelMethod.Transparent;
		image.Composite(maskImage, CompositeOperator.CopyAlpha);
	}

	return image;
}
```

I have two problems:
- When I remove the Resize method, the result is not a circle cropped image on a black background (it's the original image)
- When I use the Resize method, noise appears as black and white pixels, and my circle is pixellated

![fujifilmfinepixs1pro resized](https://cloud.githubusercontent.com/assets/1556750/16655573/3e9de804-445b-11e6-970f-9c8453f1e4cf.jpg)

**Comment by dlemstra** [comment]
You are getting this result because your output format is JPEG. When the output is written the Alpha channel will be discarded. You can resolve this by executing the following code after you resize the image:

```C#
image.Alpha(AlphaOption.Associate);
```

**Comment by dlemstra** [comment]
Does that answer your question @DavidRouyer and can I close this issue?

**Comment by DavidRouyer** [comment]
Yes, thanks for the answer!
When you are not a imagemagick expert, it's quite complicated to use...

**Comment by dlemstra** [comment]
It probably helps that I work on this library on a daily basis but I have also had a lot of help from the documentation on this page: https://www.imagemagick.org/Usage/. I could use some help with writing proper documentation for Magick.NET though.

**Comment by DavidRouyer** [comment]
The documentation looks great, but the layout is kinda old and it should be properly updated (and  Magick.NET should have its own documentation). You could use something like https://readthedocs.com/ who provides a better navigation (look at the new ASP.NET documentation for example https://docs.asp.net/en/latest/), you can host the code on GitHub and it is automatically updated when you commit.
