### ISSUE TITLE
Quick question about byte order

### ISSUE THREAD

**Issue by primem0ver** [dlemstra/Magick.NET#170]
Thank you so much for this utility.  It saved my current project when I realized I needed to work with 16 bit grayscale images which MS doesn't support in .NET.

That said... my project is a heightmap editor for terrain imports.  I need to be able to import 16 bit greyscale images, manipulate the values of individual pixels and export them to final result image.  I am assuming that I can get access to the pixel data by using image.ToByteArray().  (Please let me know if this is incorrect).

However, I need to know the basic layout of the picture.  Does the format follow the traditional format for .NET?  To find the correct location in the byte array for .NET Image I use:

int index = ((y * Width) + x) * (Depth / 8);

**Comment by dlemstra** [comment]
The `image.ToByteArray()` method will just re-encode the image and that is not what you want. You will need the method `image.GetPixels()` to access the individual pixels.

**Comment by primem0ver** [comment]
Is accessing the pixels that way slow like it is with .NET?  (.SetPixel() takes forever)? I.E.  Is there a lockbits approach to accessing the pixel data?  or is that unnecessary?  I noticed there is an unsafe method...

**Comment by dlemstra** [comment]
The unsafe method does not do any bounds checking so you should use that one if performance is an issue. You can use the `GetArea` and `SetArea` methods to modify a set of pixels.

**Comment by primem0ver** [comment]
That is not going to be helpful in this situation as I am not dealing with areas (which seem to be rectangular in nature here... that won't work at all).  It must be with individual pixels because pixel values are calculated and changed individually based on processes occurring on the "terrain" (think erosion) and choices the user makes (changing the depth of a body of water for example).  This is why I need be able to change pixel values very quickly like I can with Lockbits in regular .NET images.  **Is this going to be a problem?**  If so I will probably need to convert the image to a regular .NET image in 48 bits per pixel format.  (I will need to do that for display purposes anyway but manipulating the Magick Image directly pixel by pixel would save some coding time).

**Comment by primem0ver** [comment]
Just as an FYI... I am not sure if this is supposed to be this way or not but the K value on pixels doesn't appear to work properly... or at least not as I assume it should.  I assumed this would be the "gray" value of that the color of the pixel would be transformed to if a picture is black and white.  Since I am using a grayscale picture I was using this to get the "gray" value (or height since I am importing height maps).  However, doing this resulted in an entirely black picture. All K's for all pixels were zero.  I am having to use one of the color channels to get the gray value.

**Comment by primem0ver** [comment]
Unfortunately, as is, editing pixel by pixel with this library does not work for me.  SetPixel is way too slow.  I could probably write my own code to make it work more like the original .NET code but unfortunately, your source code is written for Visual Studio 2017 and I could not get it to compile on Visual Studio 2012, partly because of missing library files.  So I will either need to find another solution or import the pixel data byte array by brute force using GetPixel (which isn't fast, but not nearly as slow as SetPixel) and then create an entirely new MagickImage from the resulting modified byte arrays when the editing is complete.  Perhaps you could tell me where to get the lib files and I can add this feature for you?
