### ISSUE TITLE
OKLab missing as colorspace

### ISSUE THREAD

**Issue by Miepee** [dlemstra/Magick.NET#1700]
### Magick.NET version

Magick.NET-Q8-AnyCPU 13.10.0

### Environment (Operating system, version and so on)

Arch Linux

### Description

The [ImageMagick documentation](https://imagemagick.org/script/command-line-options.php?#colorspace) shows that OkLab is a viable colorspace to be used, however it does not seem to exist in Magick.NET

### Steps to Reproduce

```cs
using MagickImage image = new MagickImage(new FileInfo("myImage.png"));
image.ColorSpace = ColorSpace.OkLab;
```

**Comment by dlemstra** [comment]
Thanks for noticing this. There seem to be missing a lot of color spaces. I just pushed a patch to add them and they will become available in the next release.

**Comment by Miepee** [comment]
Since its fixed in the repo already, do you want me to close the issue now or only when the release is out? Don't know how the policy is here.

**Comment by dlemstra** [comment]
I will close the issues once the release is done.
