### ISSUE TITLE
Error: no decode delegate for this image format `' @ error/blob.c/CustomStreamToImage/765

### ISSUE THREAD

**Issue by Anu6is** [dlemstra/Magick.NET#171]
This error occurs after updating from 7.4.0 to 7.4.1. 
Are there any additional steps required for updates?
The code is attempting to read svg from a url, and output an enlarged version of the image in .png format.

Code Snippet:
```vb  
Using client As New HttpClient()
    Dim fileStream = Await client.GetStreamAsync(url)
    Dim settings As New MagickReadSettings With {
        .Width = 300,
        .Height = 300,
        .BackgroundColor = MagickColors.Transparent
    }
    Using outputStream As New MemoryStream
        Using image As New MagickImage(fileStream, settings) 'ERROR OCCURS HERE
            image.Format = MagickFormat.Png
            image.Write(outputStream)
            outputStream.Position = 0
            ------
        End Using
    End Using
End Using
```  
   
Stack Trace:  
```
at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
```

**Comment by dlemstra** [comment]
Is it possible to create a small repository that I can use to reproduce this issue?

**Comment by Anu6is** [comment]
I will push something when I get a chance. Code is only local right now.

**Comment by Anu6is** [comment]
[Link to my repo](https://github.com/Anu6is/React/blob/master/React/Commands/3FunCommands.vb#L69)

**Comment by Anu6is** [comment]
Here's a [gist](https://gist.github.com/Anu6is/9059866fba2b56856d2e9918242ccf3d#file-magicktest-vs) that can be loaded into an empty project.

**Comment by dlemstra** [comment]
Thanks for the sample will try to take a look at it this weekend.

**Comment by dlemstra** [comment]
Not sure why this changed between versions (maybe a bug fix?) but I can explain why you get this error. Magick.NET cannot detect the format from your fileStream. You will need to specify this in the `settings.Format` so ImageMagick knows how to read the file.

**Comment by Anu6is** [comment]
No problem. 
Thanks for looking into it
