### ISSUE TITLE
AdaptiveThreshold Bias cannot be negative sinds version 13.10

### ISSUE THREAD

**Issue by iMoppel** [dlemstra/Magick.NET#1717]
### Magick.NET version

Magick.NET-Q8-OpenMP-x64 13.10.0

### Environment (Operating system, version and so on)

Windows 11 23H2 

### Description

A negative bias in AdaptiveThreshold throws an exception.
File MagickImage.cs line 1144:

 public void AdaptiveThreshold(int width, int height, double bias, Channels channels)
 {
     Throw.IfNegative(nameof(width), width);
     Throw.IfNegative(nameof(height), height);
     **_Throw.IfNegative(nameof(bias), bias);_**

     _nativeInstance.AdaptiveThreshold((nuint)width, (nuint)height, bias, channels);
 }
Line Throw.IfNegative(nameof(bias), bias); is not correct and should be removed. This line was not present in previous versions. 

### Steps to Reproduce

  var readSettings = new MagickReadSettings  {  };

  TiffWriteDefines tiffWriteDefines = new TiffWriteDefines()  {      PreserveCompression =true,  };
 using (var image = new MagickImage(input, readSettings))
 {
     image.AdaptiveThreshold(21,21,-4);  
     image.Depth = 1;
     image.Format = MagickFormat.Tiff;
     image.SetCompression(CompressionMethod.Group4);
     image.ColorType = ColorType.Bilevel;
     image.Write(output, tiffWriteDefines);
 }

**Comment by dlemstra** [comment]
It looks like you found a mistake in my refactoring changes. Negative values for the `bias` should be allowed and I will make sure that this will be fixed in the next release.
