### ISSUE TITLE
Compare fuzz parameter missing

### ISSUE THREAD

**Issue by jankcat** [dlemstra/Magick.NET#172]
Hey there, 
I have tried digging through code to see if the parameter exists and is just not obvious, but I cannot seem to find it. The MagickImage.Compare method seems to be missing some parameters vs the [command line version](https://www.imagemagick.org/script/compare.php). I see ColorFuzz listed in a few places in code but do not know if this is the same parameter or how to set it...

There is an example [here](https://www.imagemagick.org/Usage/compare/) I am trying to utilize:
```
compare -metric AE -fuzz 5% \
          bag_frame1.gif bag_frame1.jpg   compare_fuzz.gif
```
I can recreate most of the example with `originalImage.Compare(otherImage, compareSettings, diff);` but cannot figure out how to get that fuzz parameter in there!
Any help is appreciated.
Thanks.

**Comment by dlemstra** [comment]
You can use `originalImage.ColorFuzz` to set the fuzz parameter. You just need to do `originalImage.ColorFuzz = new Percentage(5)`.

**Comment by jankcat** [comment]
Ohhhh you’re a life saver, thank you kindly.
