### ISSUE TITLE
Converting PDF with large page dimensions to TIFF results in "Bad value 1536 for "Orientation" tag. `_TIFFVSetField' @ error/tiff.c/TIFFErrors/592"

### ISSUE THREAD

**Issue by 36PopTarts** [dlemstra/Magick.NET#1727]
### Magick.NET version

Magick.NET-Q16-AnyCPU 14.0.0

### Environment (Operating system, version and so on)

Ubuntu 22.04.4, .NET 6

### Description

Hello, I work at a company that processes documents from school districts. These documents usually come in PDF format, but pages can sometimes vary in resolution and format. We have an OCR pipeline in which documents are split into individual page files, and then converted to TIFF. We've received quite a few documents recently that cannot get converted to TIFF because of the error I mentioned in the title. 

I wish I could provide a sample document, but unfortunately, it is all confidential production data. We deal with highly sensitive documents like medical records, student disciplinary records, etc. I do not have a test document that reproduces this issue. I have tried to redact information using Irfanview, but unfortunately, editing it and saving the PDF makes the issue go away when I put it through the OCR pipeline again.

I can give you some information about the file. The page size is 42 by 56 inches. It is PDF format version 1.4. The other pages in these documents get processed just fine. I would think that the page size has something to do with it, but as I said, somehow editing the document just to black out sensitive information in Irfanview causes it to go through just fine. For some reason, saving the file after editing by Irfanview reduced the dimensions sightly to 42 by 54.73 inches, but I'm not sure if this is what caused it to work or not.

### Steps to Reproduce

Erroring code:
```
if (readDensity == null)
                readDensity = _config.ResolutionDpi; // 300 DPI

            using (var images = _reader.ReadImageAtDensity(imagePath, readDensity))
            {
                foreach (var image in images)
                {
                    image.Format = format;
                }

                images.Write(outputFilePath); // exception thrown
            }
```
ReadImageAtDensity (after going through an overload that creates MagickImageInfo from input file path)
```
var readSettings = PrepareReadSettings(info, format, density);
            if (string.IsNullOrEmpty(info.FileName))
                throw new ArgumentException($"IMagickImageInfo parameter needs a valid FileName.");

            var result = new MagickImageCollection(info.FileName, readSettings);
            // Set output resolution because it is not always the same as input resolution
            if (density != null)
                foreach (var image in result)
                    image.Density = density;

            return result;
```
Finally, PrepareReadSettings:
```
Density readDensity;
            if (density == null)
                readDensity = info.Density;
            else
                readDensity = density;

            // Check for print size too large (aka image dimensions too large for resolution)
            if (_config.MaximumPrintSizeInches != 0) // This is always 15 inches
            {
                // Take the print size of the largest dimension
                var printSize = Math.Max(info.Height, info.Width) / Math.Max(info.Density.X, info.Density.Y);
                if (printSize > _config.MaximumPrintSizeInches) // This is always 15 inches
                {
                    // The size of the image is large enough to produce decent quality without upping resolution
                    // Plus, we do not want to make the image overly large by reading it at a higher resolution
                    readDensity = info.Density;
                }
            }

            return new MagickReadSettings()
            {
                Density = readDensity,
                Format = format
            };
```

**Comment by dlemstra** [comment]
It looks like you are looking in the wrong direction. The error message that you are receiving seems to be caused by an issue with the orientation of the image. What is the value of image.Orientation?

**Comment by 36PopTarts** [comment]
So it's possible for the PDF to be created with an embedded image that has an invalid orientation tag value? I had not considered this, I'd assumed that it would not be possible to create in the first place and so the value must have been changed during the Write call. I will do some more testing on this.
