### ISSUE TITLE
bad adaptive filter value

### ISSUE THREAD

**Issue by TheCGDF** [dlemstra/Magick.NET#1731]
### Magick.NET version

13.10.0

### Environment (Operating system, version and so on)

Win 10.0.22631.4169

### Description

reference:
https://github.com/d2phap/ImageGlass/issues/2022
I'm using ImageGlass which based on Magick.Net.
When open a image I got an error.
I guess it is a Magick.NET bug.

![image](https://github.com/user-attachments/assets/ff1c2f7f-23f9-48a3-9ebf-a4883fa8eeac)

### Steps to Reproduce

[IMG_0397.zip](https://github.com/user-attachments/files/17339972/IMG_0397.zip)
Please try this image.

**Comment by dlemstra** [comment]
You are getting this error message because the image is corrupt. ImageMagick uses the libpng library that reports an error and we are reporting that error to our users. When you open this image in another viewer only part of the image will be read because the image is corrupt.
