### ISSUE TITLE
Should GetPixel take uint parameters?

### ISSUE THREAD

**Issue by romainf-ubi** [dlemstra/Magick.NET#1734]
### Magick.NET version

14.0.0

### Environment (Operating system, version and so on)

Windows

### Description

When upgarding to v14.0.0, there's been some changes from `int` to `uint`. Especially [`MagickImage.Width`](https://github.com/dlemstra/Magick.NET/blob/main/src/Magick.NET.Core/IMagickImage.cs#L254) and [`MagickImage.Height`](https://github.com/dlemstra/Magick.NET/blob/main/src/Magick.NET.Core/IMagickImage.cs#L182). But [`IPixelCollection.GetPixel()`](https://github.com/dlemstra/Magick.NET/blob/main/src/Magick.NET.Core/Pixels/IPixelCollection%7BTQuantumType%7D.cs#L58) still takes two `int` parameters.

So I get casting errors.

### Steps to Reproduce

```cs
using var image = new MagickImage(MagickColors.Black, 100, 100);
var endPixel = image.GetPixels().GetPixel(image.Width - 1, image.Height - 1);
```

Compiler output:
```
error CS1503: Argument 1: cannot convert from 'uint' to 'int'
error CS1503: Argument 2: cannot convert from 'uint' to 'int'
```

**Comment by dlemstra** [comment]
You are allowed to access pixels at a negative index and that is why the argument is `int` instead of `uint`.

**Comment by romainf-ubi** [comment]
Oh I see! I didn't know that.

So what's the expected behavior when you give negative values in `GetPixel()`? (I couldn't see that in the code)

**Comment by dlemstra** [comment]
It should get the virtual pixels and I think that uses the `VirtualPixelMethod` setting of the image. I don't have a lot of experience with virtual pixels though.

**Comment by romainf-ubi** [comment]
Alright! Thanks for the explanations!

I'll close this issue as it's not a bug 😉
