### ISSUE TITLE
Can't load animated PNG files

### ISSUE THREAD

**Issue by michalleptuch** [dlemstra/Magick.NET#1737]
### Magick.NET version

Magick.NET-Q16-HDRI-AnyCPU 14.0.0

### Environment (Operating system, version and so on)

Windows 11 24H2, .NET 8

### Description

I can't load animated PNG files to MagickImageCollection because I get this error during `MagickImageCollection` initialization:
```VideoDelegateFailed `The system cannot find the file specified.' @ error/video.c/ReadVIDEOImage/273```
Am I missing something?

### Steps to Reproduce

Load file using this code:

```cs
using (var fileStream = await destinationFile.OpenStreamForWriteAsync())
{
  using (var images = new MagickImageCollection(paths[0], MagickFormat.APng))
  {
    await images.WriteAsync(fileStream, MagickFormat.Gif);
  }
}
```

**Comment by dlemstra** [comment]
To load `APNG` files you will need make sure that the `ffmpeg` executable is in your `%PATH%` because that is used to read the image.
