### ISSUE TITLE
Removing background color of an image

### ISSUE THREAD

**Issue by vRamCh** [dlemstra/Magick.NET#174]
Hi,

I have the command line to remove background color from any solid color background color images and i need .NET equivalent of this command.
Thanks in advance ! 

convert Alligator.jpg -alpha set -channel RGBA -fuzz 50% -fill none -floodfill +0+0 white Alligator_Transparent.png

**Comment by dlemstra** [comment]
Each of these commands translate to a property/method on the `MagickImage` class or a `Settings` property of that class.

```C#
using (var image = new MagickImage("Alligator.jpg"))
{
    // -alpha set
    image.Alpha(AlphaOption.Set);
    // -channel RGBA (don't think you need this)
    // -fuzz 50% 
    image.ColorFuzz = new Percentage(50);
    // -fill none
    image.Settings.FillColor = MagickColors.None;
    // -floodfill +0+0 white 
    image.FloodFill(MagickColors.White, 0, 0);

    image.Write("Alligator_Transparent.png");
}
```
