### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by alvinbriones232** [dlemstra/Magick.NET#175]
Hi,
Good day i have encounter this error, even if i have already added the package reference into my csproj

 System.IO.FileNotFoundException: Could not load file or assembly 'Magick.NET-Q16-AnyCPU, Version=7.4.2.0, Culture=neutral, PublicKeyToken=2004825badfa91ec'. The system cannot find the file specified.
File name: 'Magick.NET-Q16-AnyCPU, Version=7.4.2.0, Culture=neutral, PublicKeyToken=2004825badfa91ec'

**Comment by dlemstra** [comment]
Can you create a project and share that in a Github repo so I can reproduce the issue? Your description does not contain enough information.

**Comment by alvinbriones232** [comment]
I'm sorry but I cant create same project as I have mentioned above.

This are the steps in reproducing this issue
1.) After adding Magick.Net using nuget through cli
    dotnet add package Magick.NET-Q16-AnyCPU --version 7.4.2
2.) Run the project
3.) Initializing MagickImageCollection images = new MagickImageCollection() will trigger the error above in console.
  P.S. i have already included ImageMagick in the class


***do i need to put the Magick.Net.dll ?

**Comment by dlemstra** [comment]
Can you create a small sample project that has the same issue and share it on Github? I don't need your original code but I do need something to reproduce it.

**Comment by alvinbriones232** [comment]
Hi,

Good day! We have finally figure out the reason of this error. The reason why this issue occurs is because our deps.json file is not auto generated therefore, if we need to add new library we need to modify the deps.json file manually. You can close this issue since. 

Thank you for your awesome library!

**Comment by dlemstra** [comment]
Thanks for coming back to this issue and telling why it did not work. Will close this issue now.
