### ISSUE TITLE
MagickCorruptImageErrorException with iOS 18 HEIC

### ISSUE THREAD

**Issue by DustyTools** [dlemstra/Magick.NET#1753]
### Magick.NET version

14.1.0

### Environment (Operating system, version and so on)

Windows 11, Visual Studio

### Description

I'm getting the following error when trying to convert a HEIC to a JPEG. This worked perfectly for years but broke with iOS 18 photos. I read somewhere that this was related to libheif but I am not sure if that's linux related because I can't figure out how to update the dll on windows.

Error I get is:

ImageMagick.MagickCorruptImageErrorException: 'Decoder plugin generated an error: Unexpected end of file (7.100) `******\IMG_3233.HEIC' @ error/heic.c/IsHEIFSuccess/141'

### Steps to Reproduce

Error occurs here:

MagickImage image = new MagickImage("a ios HEIC file");

**Comment by dlemstra** [comment]
Are you going to buy me an Iphone so I can create an image that reproduces this error?

**Comment by DustyTools** [comment]
Here's an example:

https://1drv.ms/i/s!AuTYurMRVJKXy_xZFGwWcEv3GxGa2w

**Comment by dlemstra** [comment]
Attaching the file here for future reference: [20241111_041204483_iOS.zip](https://github.com/user-attachments/files/17771842/20241111_041204483_iOS.zip)

**Comment by DustyTools** [comment]
Thank you!
