### ISSUE TITLE
How to combine two images with arbitrary X,Y offset?

### ISSUE THREAD

**Issue by xaviershay** [dlemstra/Magick.NET#176]
Hello! Thank you for this library, it's fantastic and I've already done so much with it.

I'm trying to replicate the following command:

```
convert "$img1" -page "+$x+$y" "$img2" \
        -background none -layers merge +repage "$output_image"
```

Assuming the x,y coordinates and images result in non-overlapping shapes, this should produce a new images that's large enough to contain both input images, with transparent background to fill the gaps.

The [https://github.com/dlemstra/Magick.NET/blob/master/Documentation/CombiningImages.md](Combing Images) documentation uses a `MagickImageCollection`, but that doesn't seem to have sufficient options to change the anchor points at which the images are combined.

`MagickImage` has a `Page` property and a `Composite` method, but I can't figure out a way of using the two to get the desired effect. I guess I could manually create a new `MagickImage` with the required larger dimensions and then compose both images on to that. This would work I think, but is it the best way?

Thank you for any pointers!

**Comment by xaviershay** [comment]
```
MagickReadSettings settings = new MagickReadSettings();
settings.Width = 8000;
settings.Height = 6000;
MagickImage canvas = new MagickImage("xc:yellow", settings);
canvas.Format = MagickFormat.Png32;
canvas.Composite(image1, 100, 100);
canvas.Composite(image2, 5000, 1000);
```

This basically works, though I need to do more math by hand. For some reason `xc:none` doesn't appear to work for a transparent background though - it just creates an entire large transparent image.

**Comment by xaviershay** [comment]
I want to "blend" the images together.

If I want to use compositing modes, I can use `Extent` on the original image which is a similar solution to making a completely new canvas.

Compositing modes don't quite work right though, because they don't interact correctly with both the source image and the new transparent background.

Another option would be to feather the border of the images and then do a simple composite. I tried, the following, copying from http://www.imagemagick.org/Usage/thumbnails/#soft_edges but it doesn't appear to have any effect on the output image:

```
var canvas = image1.Clone();
var settings = new MorphologySettings();
settings.Channels = Channels.Alpha;
settings.Method = MorphologyMethod.Distance;
settings.Kernel = Kernel.Euclidean;
settings.KernelArguments = "1,100!";

canvas.Alpha(AlphaOption.Set);
canvas.VirtualPixelMethod = VirtualPixelMethod.Transparent;

canvas.Morphology(settings);
```

**Comment by dlemstra** [comment]
Have you tried using the `MagickImageCollection` and setting the `Page` property of the `MagickImage`? Or are you no longer trying to use the original command of your first post?

**Comment by xaviershay** [comment]
I'm trying all things, still don't quite have what I want :)

I will try your suggestion today and report back, thank you!

(Any suggestions for the morphology command welcome as well since I think I'll need that regardless)

**Comment by dlemstra** [comment]
@xaviershay It looks there is some kind of bug in the `Morphology` code. It will take some time to investigate and fix tha.

**Comment by xaviershay** [comment]
Confirming that your suggestion for `MagickImageCollection` does indeed work, thank you!

```
var canvas = image1.Clone();
canvas.Page = new MagickGeometry("+10+20")

var images = new MagickImageCollection();
images.Add(canvas);
images.Add(image2);
var result = images.Merge();
```

Looking forward to the next release to play around with `Morphology` more :)
