### ISSUE TITLE
AddNoise() does not use RandomSeed

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#178]
Hi Dirk.

I have tried setting the RandomSeed:
```
MagickNET.SetRandomSeed(Environment.TickCount / 1024);
```
And then use `AddNoise()` (any noise type), and the noise remains the same. It may be ignoring the random seed it seems.

Sample code:
```
MagickNET.SetRandomSeed(Environment.TickCount / 1024);
var mm = new MagickImage(MagickColors.Black, 512, 512);
mm.AddNoise(NoiseType.Random);
```

Seems to be affecting all 7.x versions, including the current one (7.4.2)

**Comment by dlemstra** [comment]
Just found out that the OpenCL random number generator is using a fixed seed. This means you will get the same image each time you run `AddNoise`. Just pushed a patch to fix this issue. Thanks for reporting this!

**Comment by dlemstra** [comment]
@daxpandhi Can you give it another try with the latest release?

**Comment by daxpandhi** [comment]
Works like a charm! Thanks :)
