### ISSUE TITLE
Resize() is broken.

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#179]
Resize may be broken.

```
            var mm = new MagickImage(MagickColors.Black, 512, 1);
            Console.WriteLine(mm.Height); // result: 1
            mm.Resize(512,512);
            Console.WriteLine(mm.Height); // result: 1
            mm.AdaptiveResize(512,512);
            Console.WriteLine(mm.Height); // result: 512
```

When resizing from 512x1 to 512x512, `Resize()` returns the same result, but `AdaptiveResize()` works (but takes much longer, as expected).

Same for any resolution, not just 512x1. Seems to be affecting all builds 7.2 and above. Not tested on older builds.

**Comment by dlemstra** [comment]
The `AdaptiveResize` method is actually doing it incorrectly. The image should not be expanded. You will need to set the `IgnoreAspectRatio` property of a `MagickGeometry` to true if you want that behavior (see my unit test in: 5f0e6028f6cb5fc76577b5a0e66ed8e3222acd5c). In the next release `AdaptiveResize` will also make the `Height` 1 instead.

**Comment by daxpandhi** [comment]
Ah, I didn't know that. Maybe it might be useful to add a note to the Summary of the (width, height) overload of those methods saying the same.

**Comment by dlemstra** [comment]
Do you have any suggestions for what I should write there? Do you think this should be sufficient?
```xml
<remarks>Resize will no nothing at all if the resized image is the same size.</remarks>
```

Its take from this page: http://www.imagemagick.org/Usage/resize/#resize

**Comment by daxpandhi** [comment]
Maybe this:
```
<remarks>Requires MagickGeometry's IgnoreAspectRatio to be set to True.</remarks>
```

This way, it is an instruction rather than just a warning.

Alternately, how about adding a third optional parameter `bool IgnoreAspectRatio` to the overload and have the method do it for the user?

**Comment by dlemstra** [comment]
I would prefer not to have an `IgnoreAspectRatio` overload because there are a lot more options:

> Ignore Aspect Ratio ('!' flag)
Only Shrink Larger Images ('>' flag)
Only Enlarge Smaller Images ('<' flag)
Fill Area Flag ('^' flag)

And I don't think it makes sense to add a remark that states that you need to set `IgnoreAspectRatio` when you use the `(width,height)` overload because it works perfectly without setting that option. It just didn't do what you would expect it to do. Maybe the following remark would be better?

```xml
<remarks>Resize will fit the image into the requested size. It does NOT fill, the requested
box size. Use the MagickGeometry overload for more control over the resulting size.</remarks>
```

**Comment by daxpandhi** [comment]
Ah, I didn't know these options. You've spoiled me with MagickNET so much I have forgotten most of the original ImageMagick stuff. :P 

Would it make sense to add all those options as an enum parameter? If not, then the remarks you wrote there look fine to me. :)

**Comment by dlemstra** [comment]
I don't think it would be a good idea to add the extra enumeration overload. The API already has a method for what you want. I think it would just clutter the overloads.

I added the documentation to the summary block so it will show up in intellisense. When this is added to the remarks it will not appear during typing. This will appear in the next release.

**Comment by daxpandhi** [comment]
Sounds good. Thanks! 🙂
