### ISSUE TITLE
Image degradation with resize

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#18]
I encountered a very annoying bug with the Resize() method.
I need to call multiple times Resize() on a image, but the degradation is amplified on every call.
I've managed to make a simple reproduction:
```
MagickImage image;
using (image = new MagickImage(SampleFiles.FujiFilmFinePixS1ProJpg))
{
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));
    image.Resize(new Percentage(99));

    image.Write(SampleFiles.OutputDirectory + "FujiFilmFinePixS1Pro.resized.jpg");
}
```
You can make fewer calls but the degradation will be less visible.
The result:
![fujifilmfinepixs1pro resized](https://cloud.githubusercontent.com/assets/1556750/17027068/ba9de46a-4f62-11e6-8735-218452bd05ac.jpg)

**Comment by dlemstra** [comment]
I can reproduce your issue but I have no clue why this happens. I will investigate this and get back to you when I know more.

**Comment by dlemstra** [comment]
This appears to be a bug in the OpenCL resize code. I will publish a new release this weekend.

**Comment by dlemstra** [comment]
Magick.NET 7.0.2.600 has been published and resolves this issue.

**Comment by DavidRouyer** [comment]
Thanks for your reactivity!
