### ISSUE TITLE
Morphology commands not working

### ISSUE THREAD

**Issue by xaviershay** [dlemstra/Magick.NET#183]
This is a follow-on issues from https://github.com/dlemstra/Magick.NET/issues/176#issuecomment-370182461 which claims that morphology is fixed. In my testing I couldn't get a morphology command to actually change an image. E.g.:

```
IMagickImage image = new MagickImage("test-image.png"));
image = image.Clone();
var settings = new MorphologySettings();
settings.Channels = Channels.Alpha;
settings.Method = MorphologyMethod.Distance;
settings.Kernel = Kernel.Euclidean;
settings.KernelArguments = "1,100!";

image.Alpha(AlphaOption.Set);
image.VirtualPixelMethod = VirtualPixelMethod.White;
image.Morphology(settings);
image.Write("feathered.png");
```

Results in a no-op using v7.4.3 Q8-AnyCPU. I would expect the edges to be feathered per the command at http://www.imagemagick.org/Usage/thumbnails/#soft_edges

I couldn't identify any commits around the time of this comment that would have fixed any issues, unless https://github.com/dlemstra/Magick.NET/commit/aaaec103fa4c952be25fb38e27ba7748c3273632 does it somehow.

Thank you for your continued assistance!

**Comment by dlemstra** [comment]
Looks like you made two mistakes in the translation:

`settings.KernelArguments = "1,100!";`
should be
`settings.KernelArguments = "1,10!";`

`image.VirtualPixelMethod = VirtualPixelMethod.White;`
should be
`image.VirtualPixelMethod = VirtualPixelMethod.Transparent;`

I also didn't notice the first one in the other issue.

**Comment by xaviershay** [comment]
sorry, that was me testing different values. Either way, it should do something.

**Comment by xaviershay** [comment]
uhm sorry PEBKAC going on over here, it appears to work. I'm not sure what was wrong with my test harness :/

**Comment by xaviershay** [comment]
Figured out my issue: morphology is working on a single image, but is then subsequently lost when adding to a collection and `Merge`ing. Am still investigating what's going on there, it may be me misunderstanding how `Merge` and transparency is supposed to work.

**Comment by xaviershay** [comment]
Ok here is a better repro. The following code works as expected when `reloadIntermediaryFromDisk = true`, but I would expect it to also work when it is `false`. Instead, the two images are merged without any morphology applied.

```
// I would expect this code to behave the same regardless of whether this is true/false.
var reloadIntermediaryFromDisk = false;
var subDir = "C:\\Users\\Xavier\\Source\\MagickRepro";
IMagickImage image1 = new MagickImage($"{subDir}\\image-1.png");
IMagickImage image2 = new MagickImage($"{subDir}\\image-2.png");
var settings = new MorphologySettings
{
    Channels = Channels.Alpha,
    Method = MorphologyMethod.Distance,
    Kernel = Kernel.Euclidean,
    KernelArguments = "1,10!"
};

image1.Alpha(AlphaOption.Set);
image1.VirtualPixelMethod = VirtualPixelMethod.Transparent;
image1.Morphology(settings);

image2.Alpha(AlphaOption.Set);
image2.VirtualPixelMethod = VirtualPixelMethod.Transparent;
image2.Morphology(settings);

image1.Write($"{subDir}/image1-feathered.png");
image2.Write($"{subDir}/image2-feathered.png");

if (reloadIntermediaryFromDisk)
{
    image1 = new MagickImage($"{subDir}/image1-feathered.png");
    image2 = new MagickImage($"{subDir}/image2-feathered.png");
}

var images = new MagickImageCollection();

image2.Page = new MagickGeometry("+0-500");
images.Add(image1);
images.Add(image2);
var result = images.Merge();

result.Write($"{subDir}/result.png");
```

Working result (note smooth join):
![result-works](https://user-images.githubusercontent.com/1714/37628176-8fd32bf8-2b95-11e8-9243-b39543c31348.png)

Non-working result (note hard join):
![result-fail](https://user-images.githubusercontent.com/1714/37628181-955a3378-2b95-11e8-9c93-a84f77c46079.png)

**Comment by xaviershay** [comment]
HYPOTHESIS: You only need to reload the first image in the collection to get a working result. Merging an image collection takes its image settings from the settings of the first element. This implies that the first image probably doesn't have an alpha channel, and reloading from disk adds one. Need to figure out how to verify/fix this.
