### ISSUE TITLE
Magick.NET-Q16-x64.Native.dll has failed the AppContainerCheck check.

### ISSUE THREAD

**Issue by kareemsulthan07** [dlemstra/Magick.NET#186]
Hi., I'm building a UWP app with C# with an intention of submitting it to the Windows Store by using Visual Studio. It uses Magick.NET-Q16-AnyCPU and everything works as expected while debugging. Later, I decided to test it on other computers by side loading it. So, I created app packages for only side loading it on other computers and then as usual Visual Studio started Windows App Certification Kit Tests. In those tests the app filed in Windows security features test and Supported API tests as follows.

`File C:\Program Files\windowsapps\83c39297-4a6c-486b-995d-7f75296cbf54_1.0.0.0_x64__24yr1j80r71jt\Magick.NET-Q16-x64.Native.dll has failed the AppContainerCheck check.
`

![windows security features test failure](https://user-images.githubusercontent.com/10881118/38036960-81904f76-32c5-11e8-8124-5b31b22f41b6.png)

![supported api test](https://user-images.githubusercontent.com/10881118/38036992-9246e7da-32c5-11e8-9015-d0d5dfefb153.png)

and the list follows.,

```
API ScriptIsComplex in usp10.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ScriptItemize in usp10.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ScriptPlace in usp10.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ScriptShape in usp10.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API BitBlt in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateBitmapIndirect in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateCompatibleBitmap in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateCompatibleDC in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateDCA in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateDIBSection in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateFontIndirectW in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateRectRgn in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateSolidBrush in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API DeleteDC in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API DeleteObject in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API EnumFontFamiliesExW in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ExtCreateRegion in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ExtSelectClipRgn in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ExtTextOutW in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdiFlush in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetCharWidth32A in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetClipBox in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetClipRgn in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetDeviceCaps in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetFontData in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetFontUnicodeRanges in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetGlyphIndicesW in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetGlyphOutlineA in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetGlyphOutlineW in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetGraphicsMode in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetObjectA in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetOutlineTextMetricsA in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetTextMetricsA in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetWorldTransform in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API IntersectClipRect in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ModifyWorldTransform in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RealizePalette in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RestoreDC in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SaveDC in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SelectClipRgn in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SelectObject in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SelectPalette in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetBkMode in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetGraphicsMode in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetMapMode in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetTextAlign in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetTextColor in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetWorldTransform in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API StretchDIBits in gdi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CryptGenRandom in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API DeregisterEventSource in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetFileSecurityW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetUserNameW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegCloseKey in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegCreateKeyExW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegDeleteValueW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegEnumKeyA in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegEnumKeyExW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegEnumValueA in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegEnumValueW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegNotifyChangeKeyValue in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegOpenKeyExA in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegOpenKeyExW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegQueryValueExA in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegQueryValueExW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegSetValueExW in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RegisterEventSourceA in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ReportEventA in advapi32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CompareStringW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateFileMappingA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateFileW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CreateToolhelp32Snapshot in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API DebugBreak in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API EnumSystemLocalesW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ExitProcess in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API FindResourceA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API FreeResource in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetDateFormatW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetModuleHandleA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetModuleHandleExW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetNumberOfConsoleInputEvents in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetOEMCP in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetShortPathNameW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetStartupInfoA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetThreadLocale in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetTimeFormatW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetUserDefaultLCID in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetVersion in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetVolumePathNameW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetWindowsDirectoryW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GlobalMemoryStatus in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API IsValidLocale in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API LCMapStringW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API LoadLibraryA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API LoadLibraryExW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API LoadLibraryW in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API LoadResource in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API LockResource in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API MapViewOfFile in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API Module32First in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API Module32Next in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API PeekConsoleInputA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ReadConsoleInputA in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetHandleInformation in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SizeofResource in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SHFileOperationW in shell32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SHGetFileInfoW in shell32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SHGetPathFromIDListW in shell32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SHGetSpecialFolderLocation in shell32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API CloseClipboard in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API EmptyClipboard in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API EnumDisplayDevicesA in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API FillRect in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetClipboardData in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GetDC in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API MessageBoxA in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API MsgWaitForMultipleObjectsEx in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API OpenClipboard in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API PeekMessageA in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API PostMessageA in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API ReleaseDC in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SetClipboardData in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API SystemParametersInfoA in user32.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API DnsFree in dnsapi.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API DnsQuery_A in dnsapi.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API URLDownloadToFileA in urlmon.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipAlloc in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipBitmapLockBits in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipBitmapUnlockBits in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipCloneImage in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipCreateBitmapFromScan0 in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipDeleteGraphics in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipDisposeImage in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipDrawImageRectI in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipFree in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipGetImageGraphicsContext in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipGetImageHeight in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipGetImageHorizontalResolution in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipGetImageVerticalResolution in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipGetImageWidth in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipGraphicsClear in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipLoadImageFromFile in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipSetInterpolationMode in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipSetSmoothingMode in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdipSetTextRenderingHint in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdiplusShutdown in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
API GdiplusStartup in gdiplus.dll is not supported for this application type. Magick.NET-Q16-x64.Native.dll calls this API.
```

I googled for the issue but not found any clue, so i'm here. My app targets both min and target version to 10.0.16299.91.

**Comment by dlemstra** [comment]
What is your question? Magick.NET needs to call those methods because the native library needs them. There is nothing that I can do about this. Your app will not pass he Windows Store Certification - and there's sadly nothing you can do about that.

**Comment by kareemsulthan07** [comment]
Thank you., @dlemstra. If my app doesn't pass the mock tests then it'll not pass the actual Windows Store Certification. I think I should go for alternatives.

**Comment by TheShihan** [comment]
> What is your question? Magick.NET needs to call those methods because the native library needs them. Your app will not pass the Windows Store Certification - and there's sadly nothing you can do about that.

@dlemstra Will there ever be away to use this library inside a full UWP app or is this impossible as there seems to be the native ImageMagick library which cannot be converted to be UWP compatible as it uses native Win32 API?

**Comment by dlemstra** [comment]
There is a special OpenMP version of the library and I would be open to a special version with UWP support. It looks like one of the major problems is GDI++ and it should be possible to disable that. You will loose some of the features but that should not be a problem. But I don't know what else would need to be disabled. Are there any instructions on how to make a native library UWP compatible and is there any tooling available to check this?

**Comment by TheShihan** [comment]
Well, I'm not really sure how such a thing must be done. I found: https://docs.microsoft.com/en-us/cpp/porting/how-to-use-existing-cpp-code-in-a-universal-windows-platform-app?view=vs-2019 but to be honest, most of it I don't quite understand. Will try to disable GDI++ and see if that works for my case.

**Comment by mclouvem** [comment]
HI @dlemstra is there any progress on this problem? Or could you give me some direction about how to disable GDI+ to pass the certification check?

**Comment by dlemstra** [comment]
I have not made time for this issue @mclouvem so I cannot really answer your question. Will need to do some research to figure out what needs to be changed.

**Comment by jjouppi** [comment]
Hey there!

Just wanted to check on this to see if there is now a work around for using Magick.net with UWP applications on the Microsoft store? Can't get my app to pass certification for the store currently with the following errors:

`    API BitBlt in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateCompatibleBitmap in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateCompatibleDC in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateDCA in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateDIBSection in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateFontIndirectA in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateFontIndirectW in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreatePen in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateRectRgn in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CreateSolidBrush in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API DeleteDC in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API DeleteObject in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API EnumFontFamiliesExW in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API ExtCreateRegion in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API ExtSelectClipRgn in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API ExtTextOutW in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdiFlush in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetCharWidth32A in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetClipBox in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetClipRgn in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetDeviceCaps in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetFontData in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetFontUnicodeRanges in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetGlyphIndicesW in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetGlyphOutlineA in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetGlyphOutlineW in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetGraphicsMode in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetOutlineTextMetricsA in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetStockObject in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetTextMetricsA in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetWorldTransform in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API IntersectClipRect in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API ModifyWorldTransform in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API Polyline in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API Rectangle in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API RestoreDC in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SaveDC in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SelectClipRgn in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SelectObject in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetBkMode in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetGraphicsMode in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetMapMode in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetTextAlign in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetTextColor in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetWorldTransform in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API StretchDIBits in gdi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetUserNameW in advapi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API RegisterEventSourceA in advapi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API ReportEventA in advapi32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SHFileOperationW in shell32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SHGetFileInfoW in shell32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SHGetPathFromIDListW in shell32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SHGetSpecialFolderLocation in shell32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API CloseClipboard in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API EmptyClipboard in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API EnumDisplayDevicesA in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API FillRect in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetClipboardData in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetDC in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API IsClipboardFormatAvailable in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API MessageBoxA in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API MsgWaitForMultipleObjectsEx in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API OpenClipboard in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API PeekMessageA in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API PostMessageA in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API ReleaseDC in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SetClipboardData in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API SystemParametersInfoA in user32.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GetIpForwardTable2 in iphlpapi.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API NotifyRouteChange2 in iphlpapi.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API DnsQuery_A in dnsapi.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API URLDownloadToFileA in urlmon.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipAlloc in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipBitmapLockBits in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipBitmapUnlockBits in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipCloneImage in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipCreateBitmapFromScan0 in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipDeleteGraphics in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipDisposeImage in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipDrawImageRectI in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipFree in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipGetImageGraphicsContext in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipGetImageHeight in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipGetImageHorizontalResolution in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipGetImageVerticalResolution in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipGetImageWidth in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipGraphicsClear in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipLoadImageFromFile in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipSetInterpolationMode in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipSetSmoothingMode in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdipSetTextRenderingHint in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdiplusShutdown in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.
    API GdiplusStartup in gdiplus.dll is not supported for this application type. Magick.Native-Q16-HDRI-x64.dll calls this API.`

**Comment by edsonmata** [comment]
Any solution?

**Comment by howdydewdy** [comment]
@edsonmata Hey! My workaround for this was creating a desktop extension for Image Magick. I followed this process here: https://stefanwick.com/2018/04/06/uwp-with-desktop-extension-part-1/

This allowed me to get my app into the store while retaining all functionality. Only downside is that enabling full-trust makes app certification take longer and some tasks are a bit slower due to the back and forth between the UWP app and the desktop extension.

**Comment by jjouppi** [comment]
@edsonmata Hey! My workaround for this was creating a desktop extension for Image Magick. I followed this process here: https://stefanwick.com/2018/04/06/uwp-with-desktop-extension-part-1/

This allowed me to get my app into the store while retaining all functionality. Only downside is that enabling full-trust makes app certification take longer and some tasks are a bit slower due to the back and forth between the UWP app and the desktop extension.
