### ISSUE TITLE
Server has two application having Two different Magick.net versions

### ISSUE THREAD

**Issue by KhwahishBatra** [dlemstra/Magick.NET#187]
Server has two application having Two different Magick.net versions. One is running with Magick.net 7.0 version and one new application deployed with version Magick.net 7.4.3.
New is giving error of entry point.
Is it possible that new application will have access to new version only and no conflict with other. Problem is that Old version is present in GAC and new version is present in Bin folder of my application. It si still giving error.
![error](https://user-images.githubusercontent.com/9670575/38128728-61cd404a-3419-11e8-9f01-f96f4c7855c9.png)

**Comment by dlemstra** [comment]
It looks like your new application is using an incorrect version of the native dll. What happens when you remove the library from the gac and only load it from the bin directory. If you are running on a really old version it might be wise to upgrade due to a big security issues that was detected in 2016.

**Comment by KhwahishBatra** [comment]
You mean on one server we can have all websites running on same image magick version? I have upgraded my application to latest version but there are other applications on server which are using old version. Should we need to upgrade all applications to latest Image magick?

**Comment by dlemstra** [comment]
You can run different versions of Magick.NET on the same server. I think your issue is that you installed one version in the GAC and when Magick.NET tries to load its Native dll I suspect it finds the one in the GAC instead of the bin folder. Is your issue resolved when you no longer use the GAC?

**Comment by KhwahishBatra** [comment]
i have uninstalled installed version and clears GAC as well. after clearing gac it starts working but then all other apps stop working. When i run one application, Dlls again start appearing in temporary location then other application having different version stop working and start giving same error.

**Comment by KhwahishBatra** [comment]
I have added Latest version Imagemagick Q16 anycpu using Nuget package. is there way that new application always load dll from bin?

**Comment by KhwahishBatra** [comment]
if i change cache location of image magick in one application, it change cache location aor all other apps also.

**Comment by KhwahishBatra** [comment]
Any CPU version is not restricted to bin folder?

**Comment by dlemstra** [comment]
The AnyCPU version has the native code embedded as a resource and will copy that to a temporary folder the first time your application starts. You can control the location of the folder with: `MagickAnyCPU.CacheDirectory`.

**Comment by KhwahishBatra** [comment]
on Application start i am using MagickAnyCPU.CacheDirectory = @"C:\magick\MyTempDir"; But it still giving same error

**Comment by KhwahishBatra** [comment]
its is only loading native dll to new cache location

**Comment by dlemstra** [comment]
Are you using the same application pool between all your applications?

**Comment by KhwahishBatra** [comment]
yes.. should i change application pool?

**Comment by dlemstra** [comment]
Each application should have it's own application pool

**Comment by KhwahishBatra** [comment]
Yes please. Got the fix. Thanks a lot for Help.
