### ISSUE TITLE
Crop to Aspect Ratio

### ISSUE THREAD

**Issue by medokin** [dlemstra/Magick.NET#189]
Trying to express this:

`convert barn.jpg -gravity center -crop 3:2 barn_crop_3to2.png`
See: https://stackoverflow.com/a/49561441/1768955

with:
```c#
image.Crop(new MagickGeometry("3:2"), Gravity.Center)
```
returns a 1x1px Square

**Comment by dlemstra** [comment]
It looks like you found a missing feature. Working on a patch to make this possible.

**Comment by dlemstra** [comment]
I published version 7.4.4.0 and this should now work. Can you give it another try?

**Comment by medokin** [comment]
Thanks! Sure, will do.

**Comment by medokin** [comment]
Works as expected. Thanks!
