### ISSUE TITLE
Since 7.1.0 - Converting Lab Colorspace in working incorrect

### ISSUE THREAD

**Issue by ykSneerG** [dlemstra/Magick.NET#190]
Hello,

in the past i used the following code to convert to LAB or to RGB (swap line 3/4):

scrImg.RenderingIntent = RenderingIntent.Absolute;
scrImg.BlackPointCompensation = false;
scrImg.AddProfile(new ColorProfile(_rgbICC), true);
scrImg.AddProfile(new ColorProfile(_labICC), true);

The output was exactly the same like Photoshop. I updated to 7.4.3 but it is not working anymore.
I tried scrImg.TransformColorSpace(...), but the result is not as Photoshop or in 7.1.0.

How can I transform an Image to LAB in absolute colorimetric without blackpoint compensation?
I rolled back to 7.1.0 for the moment, because here it is working perfect. I asked this question time ago on codeplex, you suggest to use TransformColorspace, but is not working.

**Comment by dlemstra** [comment]
Would it be possible to create a small repo that contains two sample projects and an image that clearly demonstrates the difference?

**Comment by ykSneerG** [comment]
I will create two projects during the next week. Thanks, so far for the quick response.

**Comment by ykSneerG** [comment]
This is the output in three different ways and the RGB source image.

Build 7.1.0

![bildschirmfoto 2018-04-05 um 22 21 20 kopie](https://user-images.githubusercontent.com/27743804/38390616-1ecbb278-3922-11e8-9427-f4a2c68c8dfc.jpg)

Top/Left = Source RGB
Down/Left = V1 (converting with two icc-profiles) - OK

Build 7.4.3

![bildschirmfoto 2018-04-05 um 22 32 39 kopie](https://user-images.githubusercontent.com/27743804/38390744-7c426ac8-3922-11e8-9f46-959236b37d7e.jpg)

Down/Left = Source RGB
Down/Right = V1 (converting with two icc-profiles) - NOT OK

Can you send me contact, where i can upload a compressed file with both solutions?

**Comment by ykSneerG** [comment]
V2 and V3 are two different tests to transform RGB to LAB.
V2: srcImg.TransformColorSpace(... / stays RGB
V3: srcImg.ColorSpace = ColorSpace.Lab; / converts to LAB, but with a color shift, loosing chroma.

**Comment by dlemstra** [comment]
You could put the images on something like DropBox. And can you confirm if this is broken in 7.2.0.0? I suspect this is related to this change: Support HDRI color profile management.

**Comment by ykSneerG** [comment]
https://we.tl/EgcFi9C5Ga

Maybe, not the best way, this is a wetransfer link, will be deleted in two day. I checked all version and 7.1, was the last one. But if you need this information i can check it.
Just replacing the nugget package. I uses the Magick.NET-Q16-AnyCPU.7.1.0 in different versions.

**Comment by dlemstra** [comment]
I can confirm this issue is caused by using hdri color transformation. I just pushed a patch to ImageMagick to go back to non-hdri color transformation for non-hdri builds and that solves your issue. A new release will be available soon.
