### ISSUE TITLE
Using Magick.NET to extract list of colors found in .JPG files

### ISSUE THREAD

**Issue by aawtw** [dlemstra/Magick.NET#193]
I have been researching how to go about accomplishing this, and it looks like Magick.NET is the exact tool I need.  My project is in VB.NET using Visual Studio 2017, and I have downloaded and installed the Q16-HDRI-AnyCPU version, and have successfully opened a JPG image and displayed its "info" using the code you provided in the ReadImage.vb sample.  

I found an example of the exact output I want in your documentation section "Color Quantization and Dithering" and "Extracting Image Colors -- Extracting the color table" (see screen shot), but I have no clue how to adapt the Linux command line into the corresponding .NET code, and capture the text output of the color list.  Can you please help with some examples or point me to some additional documentation that I can work with?

Thanks in advance!

![image](https://user-images.githubusercontent.com/38192350/38473236-8a63c324-3b5a-11e8-9436-82433b881eb9.png)

**Comment by dlemstra** [comment]
Most command line arguments are available as methods on the `MagickImage` class. `-unique-colors` is called `UniqueColors` and that is probably what you are looking for.

**Comment by aawtw** [comment]
I seem to be having trouble finding the property in UniqueColors where the enumeration exists.  For the example JPG I am working with, I can run the convert program stand-alone with this script:

**convert   %1   -unique-colors   -depth   8   txt:- > %2**

and get lots of output, actually 6274 lines of it.  When I strip out all the lines that have no "color name", I am left with 60 lines::

_
# ImageMagick pixel enumeration: 6274,1,65535,srgb
2,0: (0,0,0)  #000000  black
19,0: (771,771,771)  #030303  grey1
77,0: (1285,1285,1285)  #050505  grey2
245,0: (2056,2056,2056)  #080808  grey3
251,0: (2570,2570,2570)  #0A0A0A  grey4
269,0: (3855,3855,3855)  #0F0F0F  grey6
569,0: (5140,5140,5140)  #141414  grey8
623,0: (6682,6682,6682)  #1A1A1A  grey10
629,0: (7196,7196,7196)  #1C1C1C  grey11
633,0: (7967,7967,7967)  #1F1F1F  grey12
1240,0: (8481,8481,8481)  #212121  grey13
1253,0: (9252,9252,9252)  #242424  grey14
1256,0: (9766,9766,9766)  #262626  grey15
1305,0: (11051,11051,11051)  #2B2B2B  grey17
1582,0: (13878,13878,13878)  #363636  grey21
1599,0: (14392,14392,14392)  #383838  grey22
2389,0: (16448,16448,16448)  #404040  grey25
2392,0: (18247,18247,18247)  #474747  grey28
2460,0: (21074,21074,21074)  #525252  grey32
2476,0: (22873,22873,22873)  #595959  grey35
2603,0: (25443,25443,25443)  #636363  grey39
2621,0: (26985,26985,26985)  #696969  DimGray
2667,0: (30069,30069,30069)  #757575  grey46
2687,0: (32125,32125,32125)  #7D7D7D  grey49
4169,0: (32896,32896,32896)  #808080  fractal
4171,0: (33410,33410,33410)  #828282  grey51
4177,0: (34181,34181,34181)  #858585  grey52
4223,0: (37265,37265,37265)  #919191  grey57
4227,0: (38036,38036,38036)  #949494  grey58
4295,0: (41891,41891,41891)  #A3A3A3  grey64
4296,0: (42662,42662,42662)  #A6A6A6  grey65
4339,0: (45232,45232,45232)  #B0B0B0  grey69
4341,0: (46003,46003,46003)  #B3B3B3  grey70
4343,0: (46517,46517,46517)  #B5B5B5  grey71
4737,0: (50372,50372,50372)  #C4C4C4  grey77
4739,0: (51143,51143,51143)  #C7C7C7  grey78
4756,0: (51657,51657,51657)  #C9C9C9  grey79
4767,0: (52428,52428,52428)  #CCCCCC  grey80
4855,0: (54484,54484,54484)  #D4D4D4  grey83
4923,0: (55769,55769,55769)  #D9D9D9  grey85
4928,0: (56283,56283,56283)  #DBDBDB  grey86
4946,0: (56540,56540,56540)  #DCDCDC  gainsboro
4951,0: (57054,57054,57054)  #DEDEDE  grey87
5320,0: (58339,58339,58339)  #E3E3E3  grey89
5333,0: (58853,58853,58853)  #E5E5E5  grey90
5383,0: (59624,59624,59624)  #E8E8E8  grey91
5386,0: (60395,60395,60395)  #EBEBEB  grey92
5408,0: (60909,60909,60909)  #EDEDED  grey93
5497,0: (65535,62965,61166)  #FFF5EE  seashell
5777,0: (61680,61680,61680)  #F0F0F0  grey94
5787,0: (62194,62194,62194)  #F2F2F2  grey95
5832,0: (62965,62965,62965)  #F5F5F5  grey96
5844,0: (63479,63479,63479)  #F7F7F7  grey97
6054,0: (61680,63736,65535)  #F0F8FF  AliceBlue
6084,0: (61680,65535,65535)  #F0FFFF  azure
6117,0: (64250,64250,64250)  #FAFAFA  grey98
6240,0: (64764,64764,64764)  #FCFCFC  grey99
6269,0: (65535,65535,65535)  #FFFFFF  white
_

When I run the same JPG through VB.NET, I have debug stopped and displayed every property in the image and in its unique colors and for the life of me I can't see where this detailed info lives in the .NET world.  Can you please give me a coding example or point me to where this is documented?  

Also, to home in on the most prevalent colors in the image, is that stored somewhere or do I have to analyze the 6274 lines and count how many times each color code appears?

Last question -- the example I am using is a small image (<200kb), but the images I am planning to work with are very high resolution (750mb to 1.5gb) in size -- For example, I looked at the properties of one image and it showed 13619 x 13619 pixels.  Are images this big too large for IM?

Thanks for your patience with what I know are noobie questions for you.  Your product seems very robust and capable, and I'm anxious to get some meaningful output from it, starting with the color list.  I would eventually like to replace some Adobe Bridge scripts with it.  I appreciate your help!

**Comment by dlemstra** [comment]
The `UniqueColors` method returns an image that contains all the colors in the image. You could also use the `Histogram` method. This will return a dictionary with all the colors as key and the value is the number of times that color exists in the image.

ImageMagick can handle jpeg files of any size. At some point your image will use too much memory and ImageMagick will swap to disk when you run out of memory. This will not be fast but you will still be able to get the result that you want.

**Comment by aawtw** [comment]
Thanks for your help.  I'll work on the UniqueColors method.
