### ISSUE TITLE
中文怎么显示呢？

### ISSUE THREAD

**Issue by azkoss** [dlemstra/Magick.NET#195]
using (MagickImage image = new MagickImage(new MagickColor(Color.White) , 300, 3000))
                                {
                                    image.Draw(new Drawables().Font("宋体").FontPointSize(21.75).Text(150, 20, "中文汉字").TextEncoding(Encoding.UTF8));

but show ????

**Comment by dlemstra** [comment]
This is probably happening because your font cannot be loaded or because the font has no support for Chinese characters. You should probably use `Times New Roman` instead of `宋体`.

**Comment by azkoss** [comment]
Thank you very mach!!!!!
