### ISSUE TITLE
MagickImage blank PNG when writing to disk

### ISSUE THREAD

**Issue by sqrMin1** [dlemstra/Magick.NET#196]
**Input**: [This PNG image](https://www.dropbox.com/s/mxa440plr9npxbm/test.png?dl=1)
**Output/Result**: The same image but completly blank

I simply tried to load the above mentioned PNG as a MagickImage and write it (untouched) to disk. But the resulting image is completly blank.

```
using (IMagickImage image = new MagickImage(path))
{
    image.Write(Path.Combine(path, "testResult.png"));
}
```

- When I save the same image as a JPG, then everything works as expected.
- When I use different PNGs it also works as expected. 

I'm just having this issue with the PNG image from the link above.

Would be great to know why this happens on this particular image and what can one do to avoid a blank output / result.

Thanks in advance!

**Comment by dlemstra** [comment]
This looks like a bug. Will need to investigate why this is happening.

**Comment by gdicristofaro** [comment]
I had a similar issue.  For me, I traced it down to paths being too small to render.  I removed svg path nodes whose area was smaller than 5, and then render the svg without issue.  When I have some time, I can see if I can create a test.

**Comment by sqrMin1** [comment]
Thanks for your fast reply.

I'm using **v7.4.3**

**Comment by dlemstra** [comment]
What is the full version? Q8/Q16 HDRI?

**Comment by sqrMin1** [comment]
Sorry, it's **Magick.NET-Q16-AnyCPU v7.4.3**

**Comment by dlemstra** [comment]
Found and fixed it. Was planning to publish a new release tonight but your bug kept me busy. Will give it another try tomorrow.

**Comment by sqrMin1** [comment]
Thank you very much for your effort!

I will try it again with the next release.

**Comment by sqrMin1** [comment]
I just tried the **Magick.Net 7.4.4.0** release and I can confirm that this bug was fixed.

Thanks again!
