### ISSUE TITLE
The continuous reduction of the picture will be very slow

### ISSUE THREAD

**Issue by Blackcat156** [dlemstra/Magick.NET#198]
Hello, I have a question.
If I decrease any percentage continuously, I will run continuously in the loop.
The program will be stuck at a certain point, and it will take a long time to go to the next step.
Hello, I have a question.
If I decrease any percentage continuously, I will run continuously in the loop.
The program will be stuck at a certain point, and it will take a long time to go to the next step.
If the operation starts at 90%, in 84%, the program starts slowly.
I close the program, set the compression from 84%, minus 1 every time.
The first few times were very fast until 79%.
> 
            int Percentage = 74;
            FileStream Filestream = new FileInfo(SelectHelper.SelectFile()).OpenRead();
            byte[] Filebytes = new byte[Filestream.Length];

            Filestream.Read(Filebytes, 0, Filebytes.Length);

            Filestream.Close();
            while (true) {
                using (MagickImage image = new MagickImage(Filebytes))
                {

               
                    MagickGeometry size = new MagickGeometry(new Percentage(Percentage), new Percentage(Percentage));
                    image.Resize(size);
                    Console.WriteLine("Compression ratio ：{0}%,Img Height({1}),Img Width({2})", Percentage--, image.Height,image.Width);
                }
            }

>

**Comment by Blackcat156** [comment]
I use this picture to test it
https://user-images.githubusercontent.com/34151464/38848641-bd37bdd2-423a-11e8-84cd-cf5824b5bab6.jpg

**Comment by dlemstra** [comment]
This looks like a duplicate of #194. Will try to publish a new release this week.

**Comment by Blackcat156** [comment]
Thank you very much, looking forward to the new version
