### ISSUE TITLE
Regression in Composite using CompositeOperator.CopyAlpha

### ISSUE THREAD

**Issue by DavidRouyer** [dlemstra/Magick.NET#20]
I was using this piece of code to circle crop an image using a mask:
```
MagickImage image;
using (image = new MagickImage(SampleFiles.FujiFilmFinePixS1ProJpg))
{
    image.VirtualPixelMethod = VirtualPixelMethod.Transparent;
    image.Format = MagickFormat.Png;
    using (var maskImage = new MagickImage(MagickColors.Black, image.Width, image.Height))
    {
        var diameter = maskImage.Width < maskImage.Height ? maskImage.Width : maskImage.Height;
        int originY = (maskImage.Height - diameter) / 2 + diameter / 2;
        int originX = (maskImage.Width - diameter) / 2 + diameter / 2;

        maskImage.Draw(new IDrawable[]{ 
            new DrawableFillColor(MagickColors.White),
            new DrawableCircle(originX, originY, 0, originY)
        });

        image.Composite(maskImage, CompositeOperator.CopyAlpha);
}

image.Write(SampleFiles.OutputDirectory + "FujiFilmFinePixS1Pro.cropped.png");
```

Since Magick.NET 7.0.2.900 (Same result with 7.0.3.1, the version I'm trying to use), my image isn't cropped anymore:
![fujifilmfinepixs1pro cropped](https://cloud.githubusercontent.com/assets/1556750/18273805/7a726594-743f-11e6-977a-e6f143cda8cf.png)
Instead of:
![fujifilmfinepixs1pro cropped](https://cloud.githubusercontent.com/assets/1556750/18273816/8dcc4a2e-743f-11e6-8701-09e288a0eaef.png)

**Comment by dlemstra** [comment]
You are seeing this behavior because we corrected a bug in ImageMagick. The maskImage should not have an alpha channel. Setting maskImage.HasAlpha to off resolves your issue.

**Comment by DavidRouyer** [comment]
Thanks! Can you please report any breaking changes in the Changes.md file? It's very helpful!

**Comment by dlemstra** [comment]
Might be better if I add a link to the ChangeLog of ImageMagick (http://www.imagemagick.org/script/changelog.php) Just realized that I did not add this fix to the ChangeLogh though.
