### ISSUE TITLE
Unable to write PSD with alpha channel

### ISSUE THREAD

**Issue by FuzzyTrace** [dlemstra/Magick.NET#200]
I'm using Magick.NET 7.4.3 to convert a TGA image with alpha into a PSD with the same alpha channel but the resulting image always has the alpha blended and the actual alpha channel lost. I've even tried using a source PSD with alpha and writing it back out as PSD and the same issue occurs. Here are few issues I've noticed:
 - Setting AlphaUnblended has no impact on the resulting image whether it's set true or false in the MagickReadSettings.
 - Regardless of write setting saved PSD image never has alpha channel.
 - Using MagickImageCollection when reading source PSD keeps the color channels intact but still looses alpha channel
 - Using MagickImage when reading source PSD always blends in the alpha into color and still looses alpha channel itself.
Here is a sample code:
```csharp
MagickReadSettings readSettings = new MagickReadSettings()
{
    Defines = new PsdReadDefines()
    {
        AlphaUnblend = false
    }
};
using (MagickImageCollection image = new MagickImageCollection())
{
    image.Read(inPsdFilePath, readSettings);
    image.Write(outPsdFilePath); // results in PSD with good color channels but no alpha channel
}
using (MagickImage image = new MagickImage())
{
    image.Read(inPsdFilePath, readSettings);
    image.Write(outPsdFilePath); // results in PSD with blended alpha and no alpha channel
}
```

(source psd is a simple single layer red flood with single alpha channel)

**Comment by dlemstra** [comment]
Can you also share an image that demonstrates the issue?

**Comment by FuzzyTrace** [comment]
Sure.
[https://drive.google.com/file/d/19pA-AesdeZsn-C0VSGCwMtn7NNiqcbz0/view?usp=sharing](url)

**Comment by dlemstra** [comment]
When I check the output image (with ImageMagick) I see an alpha channel in both situations. I am using the latest version of Magick.NET so that might explain the output difference. Or maybe I don't understand your issue. Can you explain in more detail the issue that you are experiencing?

**Comment by FuzzyTrace** [comment]
That's my bad I should have been more specific. Let me try this:

This input **psd** has only background and an alpha channel:
Input image: [BackgroundOnlyWithAlpha](https://drive.google.com/open?id=1b3MXUapA3kHqLN1n5Hyt2KeYNDkXvCN4)
Output converted using MagickImage: [BackgroundOnlyWithAlpha_converted](https://drive.google.com/open?id=1XswqzoOK1LAoFgBCUr_Rs56KM_tsZVKz)
Output converted using MagickImageCollection: [BackgroundOnlyWithAlpha_convertedFromCollection](url)

This input **psd** has only one layer and an alpha channel (background 'layer' was deleted):
Input image: [LayerOnlyWithAlpha](https://drive.google.com/open?id=1dfqHolfUq4PKiB9d9IxLIYBbH3Xk1Kvv)
Output converted using MagickImage: [LayerOnlyWithAlpha_converted](https://drive.google.com/open?id=109Oeng4rY9U5ppkC9SVjDYVSeDFFFJUZ)
Output converted using MagickImageCollection: [LayerOnlyWithAlpha_convertedFromCollection](https://drive.google.com/open?id=1arQXeIK7pBZ0Dmmx-Jf6AFT4nDZJsoA8)

This input **psd** has background + one layer and an alpha channel:
Input image: [OneLayerWithAlpha](https://drive.google.com/open?id=1DqLzieSVTd2LS2j5S5pupZgRV15tPV75)
Output converted using MagickImage: [OneLayerWithAlpha_converted](https://drive.google.com/open?id=1cW6e-0AINL17pFe-4Xi9PR7dTg6PUUAT)
Output converted using MagickImageCollection: [OneLayerWithAlpha_convertedFromCollection](https://drive.google.com/open?id=1p6CgZXPJGqKdVXLjs1JW_TzfPitnYKWL)

This input **tga** with alpha is the original image I attempted to convert:
Input image: [WithAlpha](https://drive.google.com/open?id=1ob0xlfNHRAv67vTUarwd44ulNDZ7P2P-)
Output converted using MagickImage: [WithAlpha_converted](https://drive.google.com/open?id=1F67HiA21TZwnG1NHrvsNgCgKAuW3CUPj)

Hope that's a little bit clearer. You'll notice that none of the output images have alpha in a separate channel and when converted using MagicImage alpha will be blended into the color regardless of the AlphaUnblended read define value. When using MagickImageCollection however, input images with 'layers' (be it single or multiple) will lose alpha altogether.

Thanks for looking into this. Much appreciated.

**Comment by dlemstra** [comment]
I still don't understand what is wrong. I stepped through the decoder with a debugger and the output image `WithAlpha_converted` has a separate alpha channel. The alpha channel is not blended in the other channels. I have no other way that to use Magick.NET/ImageMagick to inspect your output images so I don't understand why you came to this conclusion.

**Comment by FuzzyTrace** [comment]
Interesting. Some formatting discrepancy in the converted image is causing Photoshop to merge alpha channel on load.
Here is what I see in Photoshop:

Original:
![original](https://user-images.githubusercontent.com/12448150/39150401-1f32494c-46f7-11e8-9535-3737600e879b.png)

Converted:
![converted](https://user-images.githubusercontent.com/12448150/39150448-3950d38e-46f7-11e8-9b58-f1edf296280e.png)

**Comment by dlemstra** [comment]
@FuzzyTrace It is still a bit unclear to mean what the bug is that you are trying to report. Can you reproduce your issue with the latest release and can you try to explain again what is incorrect?
