### ISSUE TITLE
Unable to call Identify and get image properties

### ISSUE THREAD

**Issue by nauticalcoder** [dlemstra/Magick.NET#201]
For the project I am working on, I need to call the _identify_ command from ImageMagick and access the list of returned properties.  So far I haven't found a way using Magick.NET to do this.   The ImageMagick command is this:
_identify -verbose filename_

And the properties I need to access are under a header of _Properties:_.
Orientation: Undefined
  Properties:
    date:create: 2018-04-17T15:28:06-04:00
    date:modify: 2018-04-17T15:28:06-04:00
    dc:format: application/pdf
    illustrator:Type: Document
    pdf:HiResBoundingBox: 2369.53x875.825+0+0
    pdf:SpotColor-0: PANTONE 368 U
    pdf:SpotColor-1: PANTONE 490 U
    pdf:SpotColor-2: PANTONE 7421 U
    pdf:SpotColor-3: PANTONE Strong Red U
    pdf:SpotColor-4: PANTONE 155 U
    pdf:Version: PDF-1.5
    signature: 6aff100b0bc6a5ee4468a88f2d617edf5a60a7df685e009a774a4012209ee028
    xmp:CreateDate: 2018-03-28T14:38:06-04:00
    xmp:CreatorTool: Adobe Illustrator CC 22.0 (Macintosh)
    xmp:MetadataDate: 2018-03-28T14:48:07-04:00
    xmp:ModifyDate: 2018-03-28T14:48:07-04:00
    xmpMM:DerivedFrom: proof:pdf
    xmpMM:DocumentID: xmp.did:55bd59a2-a57f-451d-967a-67e82d4faebb
    xmpMM:InstanceID: uuid:d46b80c2-8f0d-7b42-a7c4-5bd05636d401
    xmpMM:OriginalDocumentID: uuid:004458bc-83a7-5e49-9803-47a61d22d7fd
    xmpMM:RenditionClass: proof:pdf
    xmpTPg:HasVisibleOverprint: False
    xmpTPg:HasVisibleTransparency: False
    xmpTPg:MaxPageSize: Pixels
    xmpTPg:NPages: 1
  Profiles:
    Profile-xmp: 35457 bytes

Is there a way to do this with Magick.NET or am I going to need to call the ImageMagick command directly?

**Comment by nauticalcoder** [comment]
I reviewing this further, it looks like these properties are actually embedded  XMP metadata.  I see that EXIF data is supported but unsure of XMP.

**Comment by dlemstra** [comment]
You can use the `GetXmpProfile()` method of `MagickImage` to get the xmp profile.

**Comment by nauticalcoder** [comment]
Thanks.  That does point me in the right direction although in experimenting with different metadata on images, even though I have added XMP metadata, the only way I can see it with ImageMagick is with _GetExifProfile_.   I am still trying to sort through just where that pdf:SpotColor is coming from and how to retrieve it in a useful way.

**Comment by nauticalcoder** [comment]
It looks like the information I need (the pdf: SpotColors shown in the _identify_ results above) is not stored in the XMP profile but rather is coming from the _Separation_ information in the PDF/AI file.   Is there way to access this information using Magick.NET?

**Comment by nauticalcoder** [comment]
I will answer my own question here as I dug into the ImageMagick code as well as the Magick.NET code and discovered how to retrieve those Spot Colors.  ImageMagick adds the the spot colors from PDF's as Properties named pdf:SpotColor-x.  There is a GetAttribute function on MagickImage which can be used to retrieve those Properties.    For now, this is exactly what I need.
