### ISSUE TITLE
Issue with svg path rendering

### ISSUE THREAD

**Issue by gdicristofaro** [dlemstra/Magick.NET#202]
Hi,

Thanks for all your work on this library.  It has been quite useful.  I noticed a small issue when rendering svg's to png's.  I am having an issue where path nodes whose size is zero (and possibly have a linear gradient fill or are partially transparent) cause a failure in rendering.  I created a small program to test the rendering on an svg with which I was having trouble.  In it, I commented out the problematic node.  I also attached a copy of the rendered output - one without the problematic path that does display "Some Text" and one with the problematic path.  I suspect that this might be an issue with another library.  Is this something I should take to another project?  Thanks for your time and thank you once again for maintaining this project,

Greg

```
using System;
using ImageMagick;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Text;
using System.Xml;

namespace Test
{
    public class ImageMagickTest
    {
        private static string PATH = @"C:\output\testppt.png";

        private static int DENSITY = 200;

        private static MagickReadSettings readSettings = new MagickReadSettings()
        {
            Format = MagickFormat.Svg,
            TextAntiAlias = true,
            StrokeAntiAlias = true,
            Density = new Density(DENSITY)
        };

        public static string SVG =
@"<?xml version='1.0' ?>
<svg style='width: 100%; height: 100%; overflow: hidden;' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' version='1.1'>
  <defs>
    <clipPath id='kdef11'>
      <path    d='M54 46 L 609 46 609 249.323 54 249.323Z'   stroke='#000'  stroke-linejoin='miter'   fill='none'   ></path>
    </clipPath>
    <linearGradient id='kdef12'  x1='0'  y1='0'  x2='1'  y2='0'  gradientUnits='objectBoundingBox' >
      <stop  offset='0'   style='stop-color:#fff;stop-opacity:0;'  />
      <stop  offset='0.25'   style='stop-color:#fff;stop-opacity:0.3;'  />
      <stop  offset='1'   style='stop-color:#fff;stop-opacity:0;'  />
    </linearGradient>
  </defs>
  <g transform='matrix(1,0,0,1,0,0)' >
    <g>
      <g>
        <path    d='M0 0 L 797 0 797 300 0 300Z'   stroke='none'   fill='none'   ></path>
        <path    d='M54 46 L 609 46 609 249.323 54 249.323Z'   stroke='none'   fill='none'   ></path>
        <g>
          <g clip-path='url(#kdef11)' >
            <g>
              <path    d='M335.5 235.5 L 351.5 235.5 351.5 235.5 335.5 235.5Z'   stroke='#cc5200'  stroke-width='1'  stroke-opacity='1'   fill='#ff6600'  fill-opacity='1'   ></path>
              <!--<path    d='M335.5 235.5 L 351.5 235.5 351.5 235.5 335.5 235.5Z'   stroke='none'    fill='url(#kdef12)'  ></path>-->
            </g>
          </g>
        </g>
        <g>
          <g>
            <text  style='font:bold 12px Arial,Helvetica,sans-serif;'   x='337' y='26'  stroke='none'     fill='#4c607a'  fill-opacity='1' >Some Text</text>
          </g>
        </g>
      </g>
    </g>
  </g>
</svg>";

        public static void main(String[] args)
        {
            SaveChart(SVG);
        }

        public static void MagickNET_Log(object sender, LogEventArgs arguments)
        {
            // Write log message
            Console.WriteLine(arguments.Message);
        }

        public static void SaveChart(string svgText)
        {
            bool nodeRemove = false;
            // Log all events
            MagickNET.SetLogEvents(LogEvents.Exception);
            // Set the log handler (all threads use the same handler)
            MagickNET.Log += MagickNET_Log;
                        
            byte[] SvgBytes = Encoding.ASCII.GetBytes(svgText);
            using (MagickImage image = new MagickImage(SvgBytes, readSettings))
            {
                image.Format = MagickFormat.Png;
                image.Write(PATH);
            }
        }
    }
}
```

![withouterror](https://user-images.githubusercontent.com/3300960/39005355-ffbca296-43cd-11e8-9bac-a9c2bc72e330.png)
![witherror](https://user-images.githubusercontent.com/3300960/39005363-04a0663a-43ce-11e8-8d10-b81240e1383a.png)

**Comment by dlemstra** [comment]
I don't really understand what your issue is. When I convert your image I get an image that contains `Some Text` and a red line. I am getting the same result when I view your svg file in a browser (tried both Chrome and Firefox). 

Can you clarify what you want fixed?

**Comment by gdicristofaro** [comment]
Sorry for the lack of clarity.

In the SVG string, I commented out the problematic line:
`<!--<path    d='M335.5 235.5 L 351.5 235.5 351.5 235.5 335.5 235.5Z'   stroke='none'    fill='url(#kdef12)'  ></path>-->`

When I uncomment that line, it causes the svg rendering to fail.

**Comment by dlemstra** [comment]
This looks like a bug in the librsvg library. I just upgraded to the latest version of that library that still works without the need of a rust compiler. But that upgrade did not resolve your issue. I have no idea why this fails and I don't think it will be fixed in this library anymore according to the remark in the news file (https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.20.news):

>- Except for emergencies, this will be the LAST RELEASE of the
  librsvg-2.40.x series

**Comment by gdicristofaro** [comment]
Ok.  I did create a workaround in the code where I needed this.  It removed path nodes whose area was less than some value.  However, I designed it for my particular use case so it might take some work to make it truly robust.
