### ISSUE TITLE
Could not load file or assembly 'Magick.NET-x64.DLL' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by imran2489** [dlemstra/Magick.NET#203]
Hi All,

I am using Magick.Net in one of my application. If i try to use the code in another PC i get above mentioned error. 

"Could not load file or assembly 'Magick.NET-x64.DLL' or one of its dependencies. The specified module could not be found."

Only difference between both PCs are VS versions. In VS 2015 its working whereas in VS 2017 it is not. I tried in 2 more PC. In both cases it works with VS 2015 and not in VS 2017. 

Any help is appreciated. 

Note: C++ redistributable already installed.

**Comment by dlemstra** [comment]
Which version of Magick.NET are you using?

**Comment by imran2489** [comment]
6.8.8.501

**Comment by dlemstra** [comment]
That version is ancient an no longer supported. Are you going to upgrade to the latest version?

**Comment by imran2489** [comment]
Yes I am currently upgrading MagickImage from Version 6.0 to 7.0.7

While doing that i noticed that FillPattern property has been removed. So can you kindly let me know what is the new property called as ?

Example :
MagickImage image = new MagickImage("xc:none", settings);
image.Format = imageToProcess.Format;
MagickImage fill = imageToProcess;
image.FillPattern = fill;
