### ISSUE TITLE
How to draw a image of string in multiple fonts

### ISSUE THREAD

**Issue by ogis-nomura-hiroyuki** [dlemstra/Magick.NET#205]
Hi.
Thanks for all your work on this library. It has been quite useful.

By the way, Could you tell me to draw a image of string in multiple fonts?
My project is in need of multiple language such as English, Chinese, Japanese.
[For example](http://www.adelphi.edu/wp-content/blogs.dir/41/files/2016/07/gmail-profile-pic-before-generic.jpg?t=1468442305-41058-a)

This is my code.
```
using (var image = new MagickImage(new MagickColor( "#e6535a"), 80, 80))
{
	image.Format = MagickFormat.Jpeg;
	image.Draw(
		new DrawableText(0, 0, "Image String"),
		new DrawableGravity(Gravity.South),
		new DrawableFont(""),
		new DrawableFontPointSize(MagickNET.FontFamilies.FirstOrDefault(fontName => fontName.Contains("Meiryo"))),
		new DrawableFillColor(MagickColors.White),
		new DrawableTextEncoding(Encoding.UTF8));
	new MemoryStream(image.ToByteArray());
}
```

"Meiryo" font can draw Japanese and English, but It can't draw Chinese or another language.
If I specify multiple fonts, Everything goes well.

Best regards.

**Comment by dlemstra** [comment]
If you want to use the same font to draw all those languages you should use a font that has characters for all those languages. No idea what kind of font you could use for that though. You probably need to buy a font for that.

**Comment by ogis-nomura-hiroyuki** [comment]
It's no problem a kind of font is not same. However, We are having a problem for garbled characters.
Even though I use different fonts, I'm looking for ways to not garbled characters. Do you have a idea?

If there is no way, I will make my own algorithm in my system.

**Comment by ogis-nomura-hiroyuki** [comment]
It's no problem a kind of font is not same. However, We are having a problem for garbled characters.
Even though I use different fonts, I'm looking for ways to not garbled characters. Do you have a idea?

If there is no way, I will make my own algorithm in my system.
