### ISSUE TITLE
Use of LocalContrast on specific channel

### ISSUE THREAD

**Issue by zomeo** [dlemstra/Magick.NET#206]
Hello,

I'm doing some tests with LocalContrast method and it works very well for my needs.

It would be great if this method could be applied on per channel basis.

Is it possible to implement a new method that let the command work on a specified channel? For example it would be great to apply it on the L* channel of the Lab colorspace.

Thank you very much.

**Comment by dlemstra** [comment]
The ImageMagick code that does the LocalContrast will always set all channels: https://github.com/ImageMagick/ImageMagick/blob/38b42e1dd1ab4cd58cfe6cd0460d14c642379d08/MagickCore/effect.c#L1909. We will need to investigate if we could change this in ImageMagick. Will get back to you when I have more information.

**Comment by zomeo** [comment]
I understand Dirk, thank you.
My request comes from an article that suggests tu use the LocalConstrast on the L* channel to avoid unexpected color saturations:
https://www.cambridgeincolour.com/tutorials/local-contrast-enhancement.htm

**Comment by dlemstra** [comment]
@zomeo I am so sorry but I just pushed a new release and I forgot to add this. This has been added to ImageMagick but I forgot to include it in the current release. Just pushed some changes to make this available in the next release.

**Comment by zomeo** [comment]
@dlemstra really no problem. Thank you for your efforts on this project. Really much appreciated.
