### ISSUE TITLE
How to read password Protected PDF

### ISSUE THREAD

**Issue by chebude** [dlemstra/Magick.NET#209]
Hi, 

When I try to open a password protected PDF it fails... I wasn't able to find any options to set the password in MagickReadSettings.
I was also wondering if there is a way to check if the PDF is password protected before opening in with Magick.

Thanks

**Comment by dlemstra** [comment]
This appears to be a missing feature. I just pushed a patch to make this easier in the next release (will try to publish it soon). I have created a unit test that shows how you can read the file: https://github.com/dlemstra/Magick.NET/blob/717fc7fbc55606f2216768d428a0b77dfd2e89da/Tests/Magick.NET.Tests/Windows/Defines/Pdf/PdfReadDefinesTests/ThePasswordProperty.cs. The second unit test explains how you can test if your file needs a password. You should check if the message of the exception contains `This file requires a password for access.`.

**Comment by chebude** [comment]
Great. Thanks ;)
