### ISSUE TITLE
Resize  broken in the latest release "Magick.NET.Core-Q8": "7.0.3.300"?

### ISSUE THREAD

**Issue by describeme** [dlemstra/Magick.NET#21]
Hello, the Resize function seems to have broken in the latest release "Magick.NET.Core-Q8": "7.0.3.300",
the program just gets stuck, i tried instantiating the geometry and sending it as a parameter and also just sending the sizes.

var geometry = new MagickGeometry(width, height);
image.Resize(geometry);
//image.Resize(width, height);

I dont get an exception at all, it just stops.
AdaptiveResize is working fine and I am using that in the mean time...

**Comment by dlemstra** [comment]
Have you tried to wait for a while? I am guessing that an OpenCL benchmark is running to determine if it is better to use your CPU or GPU for the resize algorithm.

**Comment by describeme** [comment]
Yes, I have, it eventually times out. I updated that package this week and that was not happening before, let me know if there is any extra data I can provide to help diagnose.

**Comment by dlemstra** [comment]
How long is your time out? You might want to disable OpenCL on your machine if you are running this in a website that does not have a powerful GPU. You can disable it with the following code:

```C#
OpenCL.IsEnabled = false;
```

**Comment by describeme** [comment]
The timeout is the standard iis express timeout, i'd have to check it eventually just throws a 502 error (i think), i will confirm as soon as possible, this is happening on local development on a pretty decent machine, i will try disabling OpenCL to see what happens

**Comment by describeme** [comment]
It was around 1:30 seconds, before the 502.3 error showed up, disabling OpenCL made Resize() work. Since it was working before without disabling OpenCL, is this a bug?

**Comment by dlemstra** [comment]
It might be related to the brand of your video card. Would you mind installing the latest version of ImageMagick on your test machine and run the command `magick convert logo: -type truecolor -resize 100x null:` and leave that running for a while?

**Comment by describeme** [comment]
![magicktest](https://cloud.githubusercontent.com/assets/8006738/19367659/13229aba-916a-11e6-8437-3b33fa304719.png)

it finished in less than 1 sec, I installed this version: **ImageMagick-7.0.3-4-Q8-x64-dll.exe**

**Comment by dlemstra** [comment]
I forgot that our public binaries don't have OpenCL support build in by default. Would you mind creating a console application in .NET Core on your machine that uses Magick.NET and resizes an image and leave that running?

**Comment by dlemstra** [comment]
@describeme Can you help me out?

**Comment by describeme** [comment]
Hey, sorry I haven't had a chance to test it yet i had to work on other projects, I will test asap and let you know

**Comment by describeme** [comment]
@dlemstra sorry about the wait, i did what you asked but still didn't work the console window just hangs, if i set the  OpenCL to false then it works....
![magicktest2](https://cloud.githubusercontent.com/assets/8006738/20106843/7728f8ee-a5a4-11e6-9d54-355fd4116617.png)
 this time im running   **"Magick.NET.Core-Q8": "7.0.3.502"**

**Comment by dlemstra** [comment]
I tried the same code as you and it turns without any issues. I think we can only figure out why it hangs if we go through it with a debugger but that will probably take us a couple hours. Please let me know if you are open to spending some time on this together.

**Comment by dlemstra** [comment]
@describeme  Can you still reproduce this issue with the latest code?

**Comment by dlemstra** [comment]
Closing this now due to lack of response.
