### ISSUE TITLE
Bitmap lower version images(BMP3, BMP2,..) reading issues on Magick.NET-Q8 7.4.5

### ISSUE THREAD

**Issue by deepakkjose** [dlemstra/Magick.NET#210]
@dlemstra Hi,
I have the issue with Bitmap lower version images(BMP3, BMP2,..) they are throwing the exception. The BMP4 and BMP5 images are loading correctly.

Please look on the attached image for the exception

![bmp3_issue](https://user-images.githubusercontent.com/14124155/39614292-6100acd6-4f8c-11e8-9d6d-b8ca1c6f62b7.JPG)

**Comment by dlemstra** [comment]
Can you share one of your input images so I can try to reproduce the issue?

**Comment by deepakkjose** [comment]
Hi @dlemstra, 
I Appreciate your quick reply to my query.

Could you please download the image from below link. I am unable to attach here

https://drive.google.com/file/d/18Pc5B_yOhBwFF0o-88W9RXZja7sw2xSe/view?usp=sharing.

**Comment by deepakkjose** [comment]
Thanks a lot for your response. Actually, we did not set the format BMP3 explicitly its created by MS paint application.
waiting for your bug fix release.

Thank you

**Comment by dlemstra** [comment]
What is the format you use in your `readsettings`? Did you specify `MagickFormat.Bmp3` there?

**Comment by deepakkjose** [comment]
We are using new MagickImageInfo(stream) to get the image info. The Format from MagickImageInfo is set as Format in MagickReadSettings. We are not explicitly set it to MagickFormat.Bmp3

**Comment by Insire** [comment]
Hi,

why was this issue closed? Is it being resolved with the most recent version of Magick.net?

**Comment by dlemstra** [comment]
This issue has been resolved for a while. And I just pushed a unit test to make sure this will stay fixed.

**Comment by Insire** [comment]
Thanks for the update!
