### ISSUE TITLE
How to set Image Collection file format?

### ISSUE THREAD

**Issue by Zwolf8** [dlemstra/Magick.NET#212]
So I ran into a little problem while using Magick .net I need to set a image collection to a file format for the thing I coding it for. Is this possible or is there a stupidly easy way to do this?

**Comment by dlemstra** [comment]
Do you want to set the image format when you create the output file? It will use the extension of your file to determine the format. Or are you using a stream?

**Comment by Zwolf8** [comment]
I am using it in a stream and I need the final output to have a certain extension.

**Comment by Zwolf8** [comment]
Okay thanks!
