### ISSUE TITLE
EPS to PNG with transparency

### ISSUE THREAD

**Issue by MartinTiemens** [dlemstra/Magick.NET#213]
We’re using the next code example to save images as PNG, it works except for EPS files which looses it’s transparency so the background becomes white. Is there an example how to implement the EPS to PNG conversion without the loss of transparency? Thanks!

            var readSettings = new MagickReadSettings()
            {
                Density = new Density(300, DensityUnit.PixelsPerInch)
            };

            using (var image = new MagickImage(imageStream, readSettings))
            {
                image.ColorSpace = ColorSpace.RGB;                 
                image.Format = MagickFormat.Png;

                return new ImageResult(image.ToByteArray(), image.FormatInfo.MimeType);
            }

**Comment by dlemstra** [comment]
Can you share your input file?

**Comment by MartinTiemens** [comment]
Thanks for the uberfast reply!

[Uploading logo-handhake.zip…]()

**Comment by dlemstra** [comment]
Thanks for your uberfast reply. Will take a look at this during my lunch break.

**Comment by MartinTiemens** [comment]
Thanks

**Comment by dlemstra** [comment]
The problem with your image is that you it is CMYK and Ghostscript does not support reading CMYKA images. You can however force Ghostscript to use another colorspace when reading the image. If you set the `Colorspace` of your `MagickReadSettings` to `sRGB` you will get an image with a transparent background.

**Comment by MartinTiemens** [comment]
Thanks that solved the issue.
