### ISSUE TITLE
Clarifcation on using .net core dll's on windows/linux

### ISSUE THREAD

**Issue by SepiaGroup** [dlemstra/Magick.NET#215]
@dlemstra I am slightly confused on how to build/deploy Magick.net using .net core running on linux and referencing the correct dll's.

i have a .net core web app that i develop on windows and then i build and deploy it to a Docker container running Ubuntu using Jenkins.

I have Magic.net working correctly on windows and now want to build and deploy it, but this is where i am confused.

1) do i need to build Magick.net on Ubuntu and then reference these dll's in my web app? And since I am using Jenkins can I do all this via a command line.

2)  or can i use the dll's you have in the release folder ( https://github.com/dlemstra/Magick.NET/releases ) and just reference net40\Magick.NET\Magick.NET-Q16-x64.Native.dll when i do my build via Jenkins on my linux box? It is not clear to me if this dll has the linux version of imagemagick statically linked or the windows version.

**Comment by superstator** [comment]
Are you referencing Magick.NET via nuget? If so, it should all just happen automatically - nuget package restore will put the right binaries in the right places for both Linux and Windows. 

A custom cross platform build is much more involved and probably unnecessary unless there's some specific functionality you're missing in Magick.NET.

**Comment by dlemstra** [comment]
You can add `-r linux-x64` when you do a `dotnet publish` and that should make sure that you get the correct binaries in your output folder. I have not tried that myself but you should get a `Magick.NET-Q8-x64.Native.dll.so` file in your output folder.

**Comment by dlemstra** [comment]
Linux support has been added a while back. When you reference my library with NuGet (make sure you use the x64 version) you can just build the source on Windows and get everything what you need when you publish the project. It might be possible that you will need to do a `dotnet publish` of your project on a Linux machine but it might also work on Windows.

**Comment by SepiaGroup** [comment]
@dlemstra Thank you. i understand now. was confused by the comment referenced above, which seems to be outdated now.

I will let you know how this works out for me. 
thanks again.
