### ISSUE TITLE
ExifProfile not restored

### ISSUE THREAD

**Issue by jackbond** [dlemstra/Magick.NET#218]
In the following code, GetExifProfile returns null. Thanks again!

```
MagickImage image = new MagickImage(MagickColor.FromRgb(255, 0,0), 100, 100);

ExifProfile exifProfile = new ExifProfile();

exifProfile.SetValue(ExifTag.ImageUniqueID, "Have a nice day");

image.AddProfile(exifProfile);

string fileName = @"c:\temp\exiflost.png";

using(FileStream fs = new FileStream(fileName, FileMode.Create))
{
	image.Write(fs, MagickFormat.Png);
}

image = new MagickImage(fileName);

exifProfile = image.GetExifProfile();

if(exifProfile == null)
{
	Debug.WriteLine("ExifProfile is null");
}
```

**Comment by dlemstra** [comment]
It looks like the PNG reader of ImageMagick is not reading the eXIf chunk yet. Working on a patch to make this possible. This should be available in the next version of Magick.NET.

And thanks for providing that code sample. I can use that in a unit test.

**Comment by jackbond** [comment]
Cool thanks. Thinking about this a bit more, having...

public static ExifProfile GetExifProfile(Stream stream);

on the MagickImage class would be useful for times when you just need the metadata for an image, and won't be working with the image itself. Just a thought. :)

**Comment by dlemstra** [comment]
@jackbond Your `GetExifProfile` profile method would be nothing more than hiding a call the `new MagickImage`. It might be better to add support for getting the `ExifProfile` to `MagickImageInfo` class so you will not need to decode the image pixels.

**Comment by jackbond** [comment]
Yah, the idea was just to avoid decoding the pixels. I didn't know about MagickImageInfo, but given the context, that definitely sounds more appropriate.

**Comment by dlemstra** [comment]
Create a new issue for that: #219 219

**Comment by dlemstra** [comment]
@jackbond I just pushed a new release and you should be able to get the ExifProfile in your unit test.

**Comment by jackbond** [comment]
Awe, that's beautiful. Thanks. Pouring through exif specs was not something I was looking forward to.
