### ISSUE TITLE
Evaluate Red channel without affecting white

### ISSUE THREAD

**Issue by Brubning** [dlemstra/Magick.NET#220]
I am having an issue removing red from an image without affecting the colour balance of white. Removing red turns the image blue/green, including white. Is there a way to change a specific channel without affecting white in the image?

See https://stackoverflow.com/questions/50365154/magick-net-evaluate-red-channel for more info.

Thanks

**Comment by dlemstra** [comment]
It might be better to ask your question here: https://www.imagemagick.org/discourse-server/. I don't understand the issue that you are trying to solve. Maybe you can include some images to explain what you want to do. If you change the value of the red channel then your image will have different colors. Is there another image manipulation tool that can do this?

**Comment by Brubning** [comment]
Thanks, I'll join the image magick group and see if I can elicit a response from the infamous Fred.

Essentially what I'm trying to do is apply a change to a channel, but at the same time isolate white. Similar to the colour balance in GIMP. Photoshop also does this. I'll try and get some better information from the image lab guys I'm working with tomorrow.

**Comment by Brubning** [comment]
I've done some digging, and had a look at a colour balance script that FMW pulled together to see what was happening. Effectively the script masks any area of the image which falls outside the acceptable bounds for colour correction i.e. anything which is white is masked. I've used the statistics of the image to work out low and highlight values, then set a white/black threshold which I use to build a mask. Now images can have their individual colour channels amended with Evaluate but the pure white won't be affected.
