### ISSUE TITLE
Grayscale output is inaccurate

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#221]
I'm using SetPixels (in the HDR/OpenMP version of ImageMagick) to load up a sequence of ushorts into an image. The image is grayscale. When I save it using ImageMagick.Write(), the grayscale values are off. Almost as if a curve is applied. It did not match up to any Gamma modifications I tried to detected.

It appears in both Gray and LinearGray, as well as in PNG, TIFF, EXR, and other formats.

Here is the difference. The first image is the IM output, the second is the same in Photoshop.
![im_gray16](https://user-images.githubusercontent.com/6795809/40389531-5635b6fe-5e30-11e8-9339-a5c84d531a77.png)
![ps_gray16](https://user-images.githubusercontent.com/6795809/40389533-56629336-5e30-11e8-9c79-82bb094d6d3f.png)
You can see the histograms are different with a heavier bias in the IM output.

The practical problem is that in 3D, the lower heights are visualized differently. The first one is the IM output, and the second is Photoshop. The IM output stretches the bias towards the taller areas.
![im_output](https://user-images.githubusercontent.com/6795809/40389547-5c9f88d0-5e30-11e8-8d3e-e2b27a6969dc.png)
![ps_output](https://user-images.githubusercontent.com/6795809/40389551-5e5d0c1a-5e30-11e8-952b-01db7c564965.png)

Also, when PNG is saved - even with grayscale color type and color space, the resulting PNG is 16-bit color. The bias exists there too - but if I convert it in PS from 16-bit RGB to 16-bit grayscale, the bias goes away.

I've saved the raw data as a grid of floats and loaded that in 3D and it does not have the bias.

Any idea what it could be?

**Comment by dlemstra** [comment]
Can you share the actual images?

**Comment by daxpandhi** [comment]
http://earthspine.blob.core.windows.net/ultralisk/temp_accurate.png
http://earthspine.blob.core.windows.net/ultralisk/temp_inaccurate.png

I'll create a sample app to demonstrate. Will upload shortly.

**Comment by daxpandhi** [comment]
Btw, here's a linear gradient. http://earthspine.blob.core.windows.net/ultralisk/gradient.png --- straight out of ImageMagick. If you take this RGB file and convert it to Grayscale in Photoshop, the histogram shifts. Unless I'm missing something super obvious, shouldn't the gray channel match the R, G, and B channels when converting to grayscale? Again, the ushorts that make the gradient are perfectly linear, as you will see in the sample app.

**Comment by daxpandhi** [comment]
```
using ImageMagick;

namespace IMBug
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            MagickImage m = new MagickImage(MagickColors.Black, 2048, 2048);

            float[] values = new float[2048 * 2048];

            for (int y = 0; y < 2048; y++)
            {
                float v = y / 2048f * ushort.MaxValue;
                for (int x = 0; x < 2048; x++)
                {
                    values[y * 2048 + x] = v;
                }
            }

            m.ColorSpace = ColorSpace.LinearGRAY;
            m.ColorType = ColorType.Grayscale;
            m.Alpha(AlphaOption.Off);

            m.GetPixelsUnsafe().SetPixels(values);

            m.Write("Z:\\raw_gradient.png"); // might need to change the path
        }
    }
}
```

Built using last night's OpenMP/HDRI release.

**Comment by dlemstra** [comment]
Have you tried using `ColorSpace.Gray` instead?

**Comment by daxpandhi** [comment]
Yes. Same results in both.

**Comment by dlemstra** [comment]
Is this what you would expect:

![test](https://user-images.githubusercontent.com/10426229/40547536-7b2b887c-6032-11e8-9301-cc6caba0c0fb.png)

I don't see a difference but maybe it is handled different in your software because the type is Grayscale instead of sRGB?

p.s. You are using a `using` for the `new MagickImage` and `GetPixelsUnsafe` in your code right?

**Comment by daxpandhi** [comment]
If you save as PNG, it is always saved as sRGB and not Grayscale no matter the settings. TIF and EXR are saved as Grayscale, but the histogram is off. I'll keep investigating and post more details when I find out more.

Yes, I use `using` and `GetPixelUnsafe` whenever possible, and otherwise make sure to call Dispose. The new unsafe method is a lifesaver!! Superb performance. :)

**Comment by dlemstra** [comment]
This image was saved as grayscale. Maybe github changed it? Was wondering if this image was correct.

**Comment by daxpandhi** [comment]
I was talking about the `Write()` method in general, not that image specifically.

I just installed the new release. Will make a more robust case study and see if I can pinpoint the exact issue and discrepancy between the binary data and the saved version - especially the visual difference.

Again, not urgent, so will keep you posted as I find more.

**Comment by dlemstra** [comment]
I am talking about the image that I added to one of my messages earlier.

**Comment by daxpandhi** [comment]
Same discrepancy.

Original image:
![photoshop_2018-05-25_22-13-18](https://user-images.githubusercontent.com/6795809/40556068-e8e3eb58-6068-11e8-83fa-3d1e7e0c3ab1.png)

Expected:
![photoshop_2018-05-25_22-13-20](https://user-images.githubusercontent.com/6795809/40556071-ea5af274-6068-11e8-95af-b7976b64710b.png)

The visual impact is imperceptible, but the heightmap/displacement map result is significantly off. I'm going to write a series of precise tests this weekend and see if I can pinpoint the exact nature of the difference.

I checked the raw binary data in Unity, 3dsmax, and World Machine. The darkest 5% range seems to be compressing into fewer shades of gray. Like in my 3D example above, if we use the raw data (16-bit floats, binary serialization) and load them in these 3 applications, they look normal. Then we save using ImageMagick (nothing special done - just set color type, pixels, and then write), and then load it into these apps and the result is different.

**Comment by dlemstra** [comment]
I found and fixed the issue with writing a `Grayscale` image inside the ImageMagick library. As a temporary work around you could set the `ColorType` to `Undefined` right before you create the output image. I am wondering if the software that you are using wants the image without a `gAMA` chunk. Is this image better?
![test2](https://user-images.githubusercontent.com/10426229/40574914-6f284a70-60db-11e8-93ea-cbb65436e193.png)

**Comment by dlemstra** [comment]
@daxpandhi Can we close this issue?

**Comment by daxpandhi** [comment]
Yes. Closing this. I think the problem still exists, but I need to investigate more and come up with some better illustrations. If I find anything worthwhile, I'll reopen it. Thanks.
