### ISSUE TITLE
Add PngWriteDefines

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/Magick.NET#225]
The PNG encoder has various options that are used when creating the output image. The following options should be added to the new PgnWriteDefines class:

- png:bit-depth (1,2,4,8,16 (maybe enum?))
- png:color-type (should use ColorType enum for the input)
- png:preserve-colormap
- png:preserve-iCCP
- png:exclude-chunks and png:exclude-chunks (flags enum (also add `all` and `none`))

**Comment by PikminGuts92** [comment]
Found this because I'm trying to save a black & white image as PNG with a bit depth of 8. Write method is defaulting to using bit depth of 1. Is there a workaround to use for now?

**Comment by dlemstra** [comment]
@PikminGuts92 I am not sure but I think you can do this: `image.Settings.SetDefine(MagickFormat.Png, "bit-depth", "8")`.

**Comment by dlemstra** [comment]
The following options should also be included:
- png:compression-level
- png:compression-strategy (enum?)
- png:compression-filter

**Comment by cordeiro-rubens** [comment]
Hi,

I would like to work on this issue to add the PngWriteDefines class. My plan is to implement the following properties as suggested:

png:bit-depth (options: 1, 2, 4, 8, 16) (as enum)
png:color-type (using the existing ColorType enum)
png:preserve-colormap
png:preserve-iCCP
png:exclude-chunks (as a flags enum, including options for all and none)
png:compression-level
png:compression-strategy (as an enum)
png:compression-filter (as an enum)

If there are any additional details or considerations I should be aware of, please let me know. I will start working on this and submit a pull request once the implementation is complete.

Thank you!

**Comment by dlemstra** [comment]
Thanks for offering to help with this. The type of `png:bit-depth` should be `uint` and not an enum. In the next major release I am planning to switch a lot of `int` values to `uint` and because this is new we can already use `uint`. The same should be done for `png:compression-level`. We should also do both `png:exclude-chunks` and `png:include-chunks`. And please also add he boolean `png:ignore-crc`.

Feel free to ask more questions here.

**Comment by cordeiro-rubens** [comment]
Hello dlemstra,

I'm starting testing the PngWriteDefines implementation and encountered an issue when trying to change the ColorType using the Settings.SetDefine method.

Here is the code I used for the test:
```
[Fact]
public void TryChangeColorType()
{
    using var input = new MagickImage("C:/temp/onix.png");
    input.Format = MagickFormat.Png;
    // I tried setting the color type to "grayscale", "0", and "2"
    input.Settings.SetDefine("png:color-type", "2"); 

    using var memStream = new MemoryStream();
    input.Write(memStream);
    memStream.Position = 0;

    using var output = new MagickImage(memStream);
    Assert.Equal(ColorType.Grayscale, output.ColorType);
}
```

I expected that setting png:color-type to "2" would change the color type of the output image, but the test consistently fails with the ColorType remaining unchanged. I also tried setting the value to "grayscale" and "0", but these attempts didn't work either.

Am I missing something?

Thank you for your attention

**Comment by dlemstra** [comment]
I think it will attempt to try to write that color type but I don't think it's guaranteed that it will be written in that color type.
