### ISSUE TITLE
image background transparent problem.

### ISSUE THREAD

**Issue by ngoctuanqt** [dlemstra/Magick.NET#227]
As title, i can't make image fully background transparent . I'm using this code
`using (var image = new MagickImage(filedownload))`
`{`
`image.Alpha(AlphaOption.Set);`
`image.ColorFuzz = new Percentage(20);`
`image.Settings.BackgroundColor = MagickColors.Transparent;`
`image.Settings.FillColor = MagickColors.None;`
`image.FloodFill(MagickColors.White, 0, 0);`
`image.Write(fileremovebg);`
`}`
this is my  [source image](https://ibb.co/m4D9OJ)
and this is  [output image](https://ibb.co/ndyCAy)
it's not fully transparent. And i want its background color is None or Transparent instead of White.
Please help me. Tks

**Comment by ngoctuanqt** [comment]
Yes it working. But background still White not Transparent. Could u show me how to make its background is trans instead of white?

**Comment by dlemstra** [comment]
What is the format of your output image? If the output is JPEG you will not get a transparent background because that format does not support transparency. You should pick a format like PNG instead.

**Comment by ngoctuanqt** [comment]
Do i need any code to setting output format of image or just give the output .png extension?

**Comment by dlemstra** [comment]
Just change the extension and you will get a png image.

**Comment by ngoctuanqt** [comment]
Got it! Thank you very much for supporting me.
