### ISSUE TITLE
Failing to convert MPEG to PNG in ASP.NET application

### ISSUE THREAD

**Issue by daerogami** [dlemstra/Magick.NET#229]
Environment:
OS Name	Microsoft Windows Server 2012 R2 Standard
Version	6.3.9600 Build 9600
System Type	x64-based PC

Exception:
```
2018-05-29T15:48:57-05:00 22:19.051 47.969u 7.0.7 Exception w3wp.exe[3852]: delegate.c/ExternalDelegateCommand/462/Exception
FailedToExecuteCommand `"ffmpeg.exe" -nostdin -v -1 -i "C:/Windows/TEMP/magick-3852N9OmqBWHrVMt" -vframes 1 -vcodec pam -an -f rawvideo -y "C:/Windows/TEMP/magick-3852puQdBTz80m2z.pam"' (-1)
```

I have tested the above ffmpeg command manually and it works; only difference is in code the source file is created by Magick.NET via 'byte[]'. Relevant code segment:

```
using (var image = new MagickImage(fileData, new MagickReadSettings { Format = format }))
{
    image.Resize(200, 0);
    image.Format = _defaultOutputFormat;
    generatedThumbnail = image.ToByteArray();
}
```

I am fairly certain the web app has permissions to write to the temp folder (otherwise I think I would be seeing an error earlier than this)

Other Notes:
I have installed Ghostscript and confirmed conversion works for TIFF to PNG, PDF to PNG and EPS to PNG. I am trying to convert videos to a single PNG thumbnail.

Let me know if I have forgotten anything and I will try to respond as quickly as I can.

**Comment by dlemstra** [comment]
I wonder if you have the `ffmpeg.exe` executable in the folder that runs ImageMagick.

**Comment by daerogami** [comment]
It is a global path variable. Using `runas` for the app pool user and calling `echo %PATH%` shows the ffmpeg bin directory is listed. Just tested it after I enabled the user profile and its working now ...
