### ISSUE TITLE
Is it possible to specify a different location to load the .Native.dll file from?

### ISSUE THREAD

**Issue by schubboy** [dlemstra/Magick.NET#230]
I have an issue in a plugin I'm writing, using ImageMagick within.  Due to issues outside my control, I cannot have the .Native.DLL file located in the same directory as the other ImageMagick dlls.  Is there a setting / procedure / something to allow me to do this? 

I attempted to add the .Native dll to the GAC but I get the error: "Failure adding assembly to the cache:   The module was expected to contain an assembly manifest.", which I'm assuming is because the .native dll isn't your standard type of .NET dll.  

Anyone have suggestions / pointers that could help?

**Comment by dlemstra** [comment]
I have a trick for this in the AnyCPU build of Magick.NET. You can use the following code block:

```C#
private static class NativeMethods
{
    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    [return: MarshalAs(UnmanagedType.Bool)]
    public static extern bool SetDllDirectory(string lpPathName);
}
```

You should call this method before you do any calls to the Magick.NET library. And `lpPathName` should be the folder where you place the native dll.

**Comment by schubboy** [comment]
this is great, exactly what I needed, thanks!

I'll switch to using AnyCpu - I was trying to save some space using the x64 build, but I can make this work.  Any chance of getting it merged into the x64 -only build?

**Comment by dlemstra** [comment]
How/where do you think we should merge this in?

**Comment by schubboy** [comment]
sorry i didn't take time fully look through the source code - i'm assuming from your response that native loader is the same for both the anycpu and x64-only builds?

**Comment by schubboy** [comment]
So I just double checked the nuget binary - only the anycpu build has this very useful method.  I have been using the HDRI-x64 build which doesn't appear to have it.  Thats what I was wondering - can we get this in other the build flavors as well?

**Comment by dlemstra** [comment]
For the x64 build it assumes that the library is in the folder where the managed library is located. For the AnyCPU build the native library is an embedded resource. That will be copied to a temporary directory and that is why there needs to be a call to this method so it can be loaded from the temporary directory.

I don't mind adding an extra method/property somewhere to make it possible to also set the directory in the x64 or x86 build. Just not sure where to put it.

**Comment by dlemstra** [comment]
@schubboy Do you have any ideas where we should put this? I wonder if it should be a method on the `MagickNET` class called `SetNativeLibraryDirectory`. But that method should not be available in the AnyCPU library to avoid confusion with `MagickAnyCPU.CacheDirectory`.

**Comment by dlemstra** [comment]
I just published Magick.NET 7.6.0.0 where I added an extra method called `SetNativeLibraryDirectory` to the `MagickNET` class.
