### ISSUE TITLE
image load

### ISSUE THREAD

**Issue by prasanthpbvr** [dlemstra/Magick.NET#231]
I tried to load a cdr file and getting this error. Can you please help me with this
Failed to load embedded x86 assembly: unable to load file "C:\Users\prasanth\AppData\Local\Temp\GraphicsMagick.NET.1.3.26.1\GraphicsMagick.NET-Q16-x86.dll"

**Comment by dlemstra** [comment]
It looks like you are asking the question in the wrong repository? And when you open the issue at the correct spot you might want to include a bit more information.
