### ISSUE TITLE
How can I draw text with spaces?

### ISSUE THREAD

**Issue by cleetus** [dlemstra/Magick.NET#232]
I can't seem to find an answer to this anywhere on the web:

I need to draw text with spaces like this:

```C#
using (MagickImage image2 = new MagickImage("background64x800_blank.PNG"))
{
    new Drawables()
     // // Draw text on the image
    .FontPointSize(36)
    .Font("Impact", FontStyleType.Italic, FontWeight.Bold, FontStretch.ExtraExpanded)
    .StrokeColor(MagickColors.White)
    .FillColor(MagickColors.White)
    .TextAlignment(TextAlignment.Center)
    .Text(400, 45, "**need to draw text with spaces**")
    .Draw(image2);
}
```

I get an error:

ImageMagick.MagickDrawErrorException: 'non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/3601'

ImageMagick.MagickDrawErrorException
  HResult=0x80131500
  Message=non-conforming drawing primitive definition `path' @ error/draw.c/DrawImage/3601
  Source=Magick.NET-Q16-AnyCPU
  StackTrace:
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
   at ImageMagick.DrawingWand.Draw(IEnumerable`1 drawables)
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
   at ImageMagick.MagickImage.Draw(Drawables drawables)
   at ImageMagick.Drawables.Draw(IMagickImage image)
   at TredwearAPI.Controllers.ImageController.Get() in C:\Users\info\source\repos\TredwearAPI\TredwearAPI\Controllers\ImageController.cs:line 37
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by dlemstra** [comment]
This looks like a bug to me. Are you using the latest version?

**Comment by cleetus** [comment]
Yes, I'm using latest version.  I got it to work by removing StrokeColor setting from the call to new Drawable()...

**Comment by dlemstra** [comment]
I cannot reproduce your issue with Magick.NET 7.4.6.0. I changed your code to this:

```C#
using (MagickImage image2 = new MagickImage(MagickColors.Black, 64, 800))
{
    new Drawables()
    .FontPointSize(36)
    .Font("Impact", FontStyleType.Italic, FontWeight.Bold, FontStretch.ExtraExpanded)
    .StrokeColor(MagickColors.White)
    .FillColor(MagickColors.White)
    .TextAlignment(TextAlignment.Center)
    .Text(400, 45, "**need to draw text with spaces**")
    .Draw(image2);
}
```

Would it be possible to create a small test application here on Github that I can use to reproduce the issue?

**Comment by Zwolf8** [comment]
I also once had this issue before... so I had to separate words but for some reason I can't seem to reproduce the issue anymore either. I still had the code that failed to put text on a image with spaces but when I ran it again it worked fine.

**Comment by johnnyasantoss** [comment]
Hello! I'm receiving the same exception when trying to write text (even without spaces).

Here's a working repro https://gist.github.com/johnnyasantoss/e50b58c549c0a095d36cb8735e6ae934

The weird thing is that in the console output I receive this message: `Fontconfig error: Cannot load default config file` even thought there's no configuration files being loaded

I'm using Ubuntu 18.04.3 LTS

**Comment by dlemstra** [comment]
Can you reproduce this issue with `7.14.2`? And do you have fontconfig install on your server (container?).

**Comment by johnnyasantoss** [comment]
@dlemstra It stills fails with the same exception after hanging for a few seconds on the `Fontconfig error:`
btw I have `fontconfig` installed already

output from apt:
`fontconfig is already the newest version (2.12.6-0ubuntu2).`

**Comment by dlemstra** [comment]
I suspect that you don't have the font on your system. You can install this with `apt-get install msttcorefonts`?

**Comment by johnnyasantoss** [comment]
Installed the `msttcorefonts` and it still fails, also, I tried other (existing) fonts and it failed :(

**Comment by richardlalancette** [comment]
Same issue for me on mac with the Impact font which is installed.
I suspect MagickNet has trouble finding the font.
