### ISSUE TITLE
ImageMagick.MagickImage.ConnectedComponents(ConnectedComponentsSettings settings)

### ISSUE THREAD

**Issue by Jivec** [dlemstra/Magick.NET#234]
## ERROR ENCOUNTERED

```
Exception thrown: 'ImageMagick.MagickResourceLimitErrorException' in Magick.NET-Q16-AnyCPU.dll
StackTrace : �� ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   �� ImageMagick.MagickImage.NativeMagickImage.ConnectedComponents(Int32 connectivity, IntPtr& objects)
   �� ImageMagick.MagickImage.ConnectedComponents(ConnectedComponentsSettings settings)
   �� Skc.ProcessFile(String filePath, String outputPath)
   �� Skc.<>c__DisplayClass1_1.<Main>b__0(Object x) | | |  Document-page-001 (1).jpg
Finished:>Document-page-001 (1).jpg

```
## THE PROBLEM

> The images are Scanned documents with 300 DPI

The original problem is that i have an image https://imgur.com/a/U4GLbDK

and as you can see i have a bit of noise at random spots outside of the area of interest. I tried many ways to  clean the noise and after some searching i found out about the `connectedComponents ` method. It looks like its not working they way i thought or maybe there is a bug there but I'm not sure about it.

## A BIT OF WHAT TRIED

I also tried to create a mask of the image above but i'm not so sure if i'm applying it the correct way,  because it doesn't seem to work. https://imgur.com/a/V3PuK1G

`mgImgModified.Composite(origImg, CompositeOperator.CopyAlpha);`

and i also tried this.

`origImg.ReadMask = mgImgModified;`

The last one seems to have an effect on the image but not the desired one.

## END GOAL

My end goal is to dynamically clean the noise around the area of interest in order to be able to auto crop the image, to only the part i want in every instance. 

If anyone can think of a better way please by any means inform me, thank you :)
jivecc@gmail.com!!

**Comment by dlemstra** [comment]
What is the exception that is being thrown?

**Comment by Jivec** [comment]
`too many objects `' @ error/vision.c/ConnectedComponentsImage/434`

**Comment by Jivec** [comment]
Im trying to translate this [http://www.imagemagick.org/discourse-server/viewtopic.php?t=26571](http://www.imagemagick.org/discourse-server/viewtopic.php?t=26571) in magick.NET

**Comment by dlemstra** [comment]
Are you uisng the Q8 or Q16 version of Magick.NET?

**Comment by Jivec** [comment]
The Q16 version

**Comment by dlemstra** [comment]
Did you add the red lines yourself or is that part of the original image. There might be a different way to approach this. Is the color of the piece of paper always that color?

**Comment by Jivec** [comment]
No i added the red lines to make it easier to see the original problem that is the noise i want to remove or replace with the background.No its not the same color always.

**Comment by dlemstra** [comment]
Can you share an image without the lines and do you ever have a white piece of paper?

**Comment by Jivec** [comment]
[https://imgur.com/a/6tNQJAZ](https://imgur.com/a/6tNQJAZ) ,  [https://imgur.com/a/JPtcecP](https://imgur.com/a/JPtcecP) The white ones are not so much of a problem , the actual problem is when an image have extra space because it didn't got scanned well. I want to auto crop the image but the problem is that its not working if there is any kind of noise in the space i want to  auto crop/trim

**Comment by dlemstra** [comment]
I tried some options but I also could not get it working. Have you tried running those commands on the command line with the post from the ImageMagick forum? Maybe you should ask a new question there? I think there should be a different solution for your issue.

**Comment by Jivec** [comment]
The connectedComponents command didn't worked or it crashed for you too ? I didn't used command line so far , did you tried to apply the mask that i provide in the first comment because i'm not sure i'm doing this the proper way or the commands to apply a mask on an image.

**Comment by dlemstra** [comment]
I have not yet tried your mask because it is not really a mask that you can use for your situation. The connection components also did not work for me. But this is probably because your image is not suited for this operation. I could get it to work when I did a `Threshold` of the image: `image.Threshold(new Percentage(60));`. But I think your best option would be to ask for some help on the ImageMagick forum.

**Comment by Jivec** [comment]
Thank you very much i will try to ask for some help in imageMagick forums.
