### ISSUE TITLE
Magick.NET-Q16-x64.Native.dll not found

### ISSUE THREAD

**Issue by uniquestring** [dlemstra/Magick.NET#235]
I use this library (version 7.4.6.0) for an desktop application. I installed the Magick.NET-Q16-x64.dll from the zip file, as described in the documentation.

When I start my application and create an new image, I get an DllNotFoundException. Magick.NET-Q16-x64.Native.dll could not be found. If I add it manually to my debug directory it works fine.

This is similar but no duplicate of #119, since I'm not using an custom temp dir. When using the Q16-AnyCPU instead, it works, I can even see the temp dir created by Magick.NET.

**Comment by dlemstra** [comment]
I am not sure what you are expecting? You should copy both the `Magick.NET-Q16-x64.dll` and the ` Magick.NET-Q16-x64.Native.dll` to the bin directory of your project.

**Comment by uniquestring** [comment]
I did follow the documentation. My project looks like this (simplified):
```.
├── app
│   └── bin
│       ├── Debug
│       │   └── app.exe
│       ├── Magick.NET-Q16-x64.dll
│       └── Magick.NET-Q16-x64.Native.dll
└── app.sln
```
When I build and start my app during development, I get the exception. I can fix it by copying `Magick.NET-Q16-x64.Native.dll` next to `app.exe`.

When I use the AnyCPU version, I follow the same steps. My project then looks like:
```.
├── app
│   └── bin
│       ├── Debug
│       │   └── app.exe
│       └── Magick.NET-Q16-AnyCPU.dll
└── app.sln
```
When I build this, it works without an exception.

**Comment by uniquestring** [comment]
Ok, now I got it right. The application needs to find the `*.Native.dll` during runtime.

It's looking for it in different places like the application directory (and any path added to the `PATH` environment variable I guess). It's my job to install this dll, when deploying the application.

---

The only reason why this worked for me the first time was, that I used the AnyCPU version. This one comes with both dlls and copies the appropriate one to `%TEMP%\<MagickDir>`. When using the library, Magick.NET searches for the dll in the TEMP dir and finds it.

**Comment by dlemstra** [comment]
A file will be created in the AnyCPU build because in that version the native dll is embedded inside the library and written to the temporary directory when you use the library for the first time. And yes your conclusion about the fact that the native library needs to be found during runtime is correct.

p.s. You might also want to take a look at NuGet that gives you a much easier method to get the binaries in your application.

**Comment by vbpAlex** [comment]
please let me know if *.Native.dll is required if I use Magick.NET-Q8-AnyCPU.

Thanks

**Comment by dlemstra** [comment]
The native dll is included as an embedded resource in the Magick.NET-Q8-AnyCPU dll.

**Comment by vbpAlex** [comment]
which means ONLY Magick.NET-Q8-AnyCPU dll should be on server? Correct?

Also, i've sent you email and post error we getting ONLY on server , please help

error at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_Create()

**Comment by vbpAlex** [comment]
bin/


gsdll32

Magick.NET.Web-Q8-AnyCPU

Magick.NET-Q8-AnyCPU



 My Code:


  Using images As New MagickImageCollection()

                    ' Add all the pages of the pdf file to the collection

                    Dim image As New MagickImage(ConvertedImage)



                    If image.Width > "850" Then

                        Dim sGeometry As New MagickGeometry()



                        With sGeometry

                            .Width = "1150"

                            .Height = "900"

                            .IgnoreAspectRatio = True

                        End With



                        image.Scale(sGeometry)

                        image.Write(ConvertedImage)

                    End If

                End Using


getting error ONLY on server win 2012

The type initializer for 'X64' threw an exception.







at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_Create()

   at ImageMagick.MagickSettings.NativeMagickSettings..ctor()

   at ImageMagick.MagickSettings..ctor()

   at ImageMagick.MagickImage..ctor()

   at …… MyPage


Thanks

:
