### ISSUE TITLE
iTXt: chunk data is too large after removing XMP data using Adobe XMP Toolkit

### ISSUE THREAD

**Issue by ashkandaie** [dlemstra/Magick.NET#236]
Hi,

I have a PNG with a lot of of XMP metadata (8MB+). After removing some of the metadata using [Adobe XMP Toolkit](https://www.adobe.com/devnet/xmp.html) I get the following exception:

**Unhandled Exception: ImageMagick.MagickCoderErrorException: iTXt: chunk data is too large `E:\images\blank_after.png' @ error/png.c/MagickPNGErrorHandler/1711**

Here is a [link](https://drive.google.com/open?id=1DBHStmY_ZsxXzHQiWrU8lzxGekg9Yy-i) to the file that is used prior to removing XMP metadata:

And a [link](https://drive.google.com/open?id=1kvCPxNa6OHovfRSnEdCvHbwvOUIO-jAz) to the file after the removing the XMP metadata.

I am able to open the file using Adobe Photoshop and other image editors.

Adobe XMP Toolkit does not reduce the file size after removing metadata, I wanted to open / save using Magick.NET to reduce the file size.

Looks like a dup of #105.

I am using Magick.NET-Q16-HDRI-AnyCPU 7.4.6.0

**Comment by dlemstra** [comment]
Sorry for the late response but I completely forgot about this issue.

It looks like you are running into a limit inside the libpng library. The size of your iTXt chunk is larger than that limit. At this moment we have no method to change/remove this limit but I will try to add that later this week. I was about to publish a new release but I will wait with that and add this feature to ImageMagick (and Magick.NET) first.

**Comment by dlemstra** [comment]
The feature has been added and you can read the file in the next release with the following code:

```C#
var settings = new MagickReadSettings()
{
    Defines = new PngReadDefines()
    {
        ChunkMallocMax = 0, // Unlimited
    },
};

using (var image = new MagickImage("YourFile.png", settings))
{
    image.Read(Files.SnakewarePNG, settings);
}
```

**Comment by dlemstra** [comment]
The new release has been published, can you give it another try @ashkandaie?

**Comment by ashkandaie** [comment]
@dlemstra 

Thanks for the fix. I am able to read PNGs w/ large XMP payloads.

Keep up the good work!
