### ISSUE TITLE
What is the equivalent of the strip command line option ?

### ISSUE THREAD

**Issue by gelambert** [dlemstra/Magick.NET#237]
Hi,

I would like to know what is the equivalent of the strip command line option :
`magick convert lolcat.png -strip lolcat.png`

I tried to find it in the [documentation](https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Readme.md) but I could not see it :<

Thanks for your answer !

**Comment by dlemstra** [comment]
Most command line options are methods of the `MagickImage` class. Your command would translate to this:

```C#
using(var image = new MagickImage("lolcat.png"))
{
  image.Strip();
  image.Write("lolcat.png");
}
```

If you are trying to reduce the size of the image you could also take a look at the `ImageOptimizer` class.

**Comment by gelambert** [comment]
Perfect, thank you sir !
