### ISSUE TITLE
crossplatform documentation seems corrupted

### ISSUE THREAD

**Issue by istimaldar** [dlemstra/Magick.NET#239]
Hey. I'm trying to build Magick.NET to run under Linux. In your docs you say there is `Dockerfile` in `ImageMagick/Sources` but there is no any. Could you please update docs. Thanks.

**Comment by dlemstra** [comment]
I am in the middle of rewriting the way this is build. I am moving away from docker and I will be using a VSTS build server for this. I will try to updating the documentation later this week/weekend.

Why are you building it under Linux yourself and are you not using the provided binary? Are you missing some features?

**Comment by ivankarpey** [comment]
@dlemstra We do use Magick.NET in our project since 7.3 version. In the appropriate documentation for this tag, there was an instruction on how to deal with libs under Linux. So @istimaldar just trying to operate according to the docs provided. Is there a way to avoid building libs on the server and used some already precompiled libs?

**Comment by dlemstra** [comment]
@ivankarpey Magick.NET comes with precompiled native libraries on Linux. You should not need to build them yourself.

**Comment by ivankarpey** [comment]
@dlemstra I believe there is some misunderstanding. Surely Magick.NET available as a precompiled packet via the nuget, but to work with it it's required to build ImageMagick and an initial request was mostly around building ImageMagick docs

**Comment by dlemstra** [comment]
You don't need to compile ImageMagick yourself. Magick.NET comes with a native `.so` file that statically links ImageMagick.

**Comment by ivankarpey** [comment]
ok, thanks. That's true, seems like current releases do not require external deps. Probably something changed since the earliest versions I tried.

**Comment by dlemstra** [comment]
Starting with version [7.4.2.0])https://github.com/dlemstra/Magick.NET/releases/tag/7.4.2.0) the native library statically links ImageMagick.

**Comment by dlemstra** [comment]
The documentation has been updated.
