### ISSUE TITLE
Constant CPU usage after MagickImage.Blur

### ISSUE THREAD

**Issue by truyb** [dlemstra/Magick.NET#240]
When I use the `Blur` method on a `MagickImage` object, the CPU jumps to 25% usage and stays there, even after disposing the MagickImage.

I am using Magick.NET-Q8-AnyCPU v7.4.6

In my example, `musicImageRaw` is a byte array.

```
using (var musicImage = new MagickImage(musicImageRaw))
{
    // Make sure the picture fits on the slide, that it does not leave 'empty space'.
    double width = slideshowWidth + Math.Abs(artistPictureX);
    double height = musicImage.Height * (width / musicImage.Width);

    if (height < slideshowHeight)
    {
        height = slideshowHeight;
        width = musicImage.Width * (height / musicImage.Height);
    }

    musicImage.Blur(0, 2); // Causes a CPU jump
    musicImage.Scale((int)width, (int)height);

    image.Composite(musicImage, artistPictureX, 0, CompositeOperator.Dissolve, "100");
} // Disposing doesn't make the CPU drop
```

Images show CPU usage with and without the `Blur` method used.

![withblur](https://user-images.githubusercontent.com/10419291/41715695-8c447d30-7554-11e8-9f1f-1771492fee3f.PNG)

![withoutblur](https://user-images.githubusercontent.com/10419291/41715701-9657214c-7554-11e8-941c-f59f6e4fda40.PNG)

**Comment by dlemstra** [comment]
Can you create a complete example in a C# file that I can use to reproduce the issue? And can you also include the image that you are using?

**Comment by truyb** [comment]
I've written a small program that makes an image and composes it on another while blurring it, ran it, and it doesn't spike anymore.

I tried running the main application on another computer and it doesn't spike at all.

Must be an issue on my end, my apologies.

**Comment by dlemstra** [comment]
No problem thanks for reporting this anyway 👍

**Comment by truyb** [comment]
I'm going to reopen this issue because now I do have a working example.

```
using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using ImageMagick;

namespace TestBlur
{
    class Program
    {
        static void Main(string[] args)
        {
            Start();
            Console.ReadLine();
        }

        public static void Start()
        {
            Task x = Task.Run(async () =>
            {
                while (true)
                {
                    byte[] jpeg = null;

                    using (var ms = new MemoryStream())
                    using (var image = new MagickImage(MagickColors.Gray, 320, 240))
                    {
                        JpegWriteDefines settings = new JpegWriteDefines()
                        {
                            Extent = 16
                        };

                        image.Settings.SetDefines(settings);
                        image.Format = MagickFormat.Jpeg;

                        byte[] newImageRaw = null;

                        using (var webClient = new WebClient())
                        {
                            webClient.Proxy = WebRequest.DefaultWebProxy;
                            webClient.Proxy.Credentials = CredentialCache.DefaultCredentials;
                            newImageRaw = webClient.DownloadData("https://upload.wikimedia.org/wikipedia/en/0/0d/Humanafterall.jpg");
                        }

                        using (var test = new MagickImage(newImageRaw))
                        {
                            test.Blur(0, 2); // No constant CPU usage when commented out.
                            image.Composite(test, 0, 0);
                        }

                        image.Write(ms);

                        jpeg = ms.ToArray();
                    }

                    File.WriteAllBytes(@"D:\temp\test.jpeg", jpeg);

                    Console.WriteLine("OK");

                    await Task.Delay(5000).ConfigureAwait(false);
                }
            });
        }
    }
}
```

This program gets the cover art from Wikipedia and composites it on an empty MagickImage picture, then saves it to a memorystream which saves it to the D: drive.

I'm getting the same spikes as previous, I have updated my NuGet package to 7.5.0 but I don't think that will be the problem.

With blur:
![withblur](https://user-images.githubusercontent.com/10419291/41839199-dbf4b410-7862-11e8-8377-e288efd2dfa6.PNG)

Without blur:
![withoutblur](https://user-images.githubusercontent.com/10419291/41839210-e72a60e6-7862-11e8-861b-a85e9221e426.PNG)

**Comment by dlemstra** [comment]
I cannot reproduce your issue. I am getting a different memory usage though but I guess you are testing with a different image. Have you tried running something like process explorer at the same time to double check the CPU usage?

**Comment by truyb** [comment]
The image I've used is in the code snippet (https://upload.wikimedia.org/wikipedia/en/0/0d/Humanafterall.jpg).

I've checked with Process Explorer as well, it shows the same result.
![proexp](https://user-images.githubusercontent.com/10419291/42155756-85778536-7de9-11e8-992e-a023fae3be96.PNG)

**Comment by dlemstra** [comment]
Thanks for the info. I will give it another try when I get home. I am wondering if the is related to OpenCL. Can you experiment with setting `OpenCL.IsEnabled` to `false` and `true` to test if you get different results.

**Comment by truyb** [comment]
Yep! That's the issue indeed! When I turn OpenCL off the CPU stops spiking.
![cpu](https://user-images.githubusercontent.com/10419291/42160030-170d8fde-7df6-11e8-8f78-834d26d4836a.PNG)

I'll turn it off for now, will there be any side effects (slower performance or so) if it's turned off?

Thanks again for finding the issue.

**Comment by dlemstra** [comment]
When Magick.NET runs for the first time it will benchmark your devices to determine what to do with OpenCL accelerated functions. You can find the result in `%LOCALAPPDATA%\ImageMagick\ImagemagickOpenCLDeviceProfile.xml`:

```xml
<devices>
  <device name="CPU" score="4.914"/>
  <device platform="AMD Accelerated Parallel Processing" score="0.165" vendor="Advanced Micro Devices, Inc." name="Ellesmere" version="2117.14 (VM)" maxClockFrequency="1266" maxComputeUnits="36" />
  <device platform="AMD Accelerated Parallel Processing" score="1.326" vendor="Advanced Micro Devices, Inc." name="Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz" version="2117.14 (sse2,avx)" maxClockFrequency="3998" maxComputeUnits="8" />
</devices>
```

A lower score is better and I am guessing that it has determined that it should use the GPU part of your CPU. It might be a bug in your OpenCL driver that it claims one CPU core (do you have 4?) and that is why it stays stuck at 25%.

The difference in performance depends on the system you are running on. The good part about this is that it runs asynchronous on the GPU.

**Comment by truyb** [comment]
I'll check it out further (reinstall drivers and the likes), but at least now we know the problem is OpenCL related, and has nothing to do with Magick.NET.

Thanks for the help, closing this issue for real now :+1: .
