### ISSUE TITLE
WriteMask appears to be inverted in 7.5.0

### ISSUE THREAD

**Issue by Brubning** [dlemstra/Magick.NET#242]
I have an application which uses Magick.NET to apply colour corrections to images via .Evaluate. We noticed that white areas of the images were taking the colour, so photos with white backgrounds look weird after correction. To fix this I apply a WriteMask to the image, anything which is very close to white is masked so that the colour correction is not applied.

With v7.4.4 this works brilliantly, upgrading to v7.5.0 this ask is inverted so that now the background is the only part of the image which takes the colour correction. See screen shot below of comparable images. The only difference is I change the installed version of Magick .NET (Q16, Any CPU) via NuGet.

The code to apply the write mask is:

        private void ApplyWriteMask(IMagickImage image)
        {
            var newImage = image.Clone();
            var whiteThreshold = new Percentage(99);
            var blackThreshold = new Percentage(1);

            newImage.ColorFuzz = new Percentage(3);
            newImage.WhiteThreshold(whiteThreshold);
            newImage.BlackThreshold(blackThreshold);

            newImage.Opaque(MagickColors.Black, MagickColors.Green);
            newImage.Opaque(MagickColors.White, MagickColors.Black);
            newImage.InverseOpaque(MagickColors.Black, MagickColors.White);

            image.WriteMask = newImage;
        }

I've attached the VS code project as well as a compiled version.

![image](https://user-images.githubusercontent.com/28068804/42017009-831f628c-7aa5-11e8-8a7c-e1c91fc8cde4.png)

[Noodle.MagickMemory.zip](https://github.com/dlemstra/Magick.NET/files/2144066/Noodle.MagickMemory.zip)

[Release.zip](https://github.com/dlemstra/Magick.NET/files/2144061/Release.zip)

**Comment by Brubning** [comment]
I should also say, the test application basically processes all image files in one folder and saves the processed image to another folder. It was written to try and fix the problem described in issue #241 .

You'll need a source folder with a lot of images in, and an empty destination folder (it does overwrite, though). I've been running it with large numbers of files (100-1000) but this colour issue is obvious immediately.

Thanks

**Comment by Brubning** [comment]
The WriteMask has changed in 7.5.0 so that transparency is used instead of white. 

In v7.4.4, my WriteMask was defined by:

            newImage.Opaque(MagickColors.Black, MagickColors.Green);
            newImage.Opaque(MagickColors.White, MagickColors.Black);
            newImage.InverseOpaque(MagickColors.Black, MagickColors.White);

In 7.5.0 this inverts the effect that .Evalute has on the image. Instead I am now defining my WriteMask with:

            newImage.Opaque(MagickColors.White, MagickColors.Transparent);
            newImage.InverseOpaque(MagickColors.Transparent, MagickColors.Black);

I'm not sure if that's a bug or not, but it's different.

**Comment by dlemstra** [comment]
I just added a new unit test 7d00207 to check if there was an issue with the `WriteMask` and it looks like it works correctly in 7.5.0.0. Not sure why it did not work for you though. Maybe my unit test can help you further?
