### ISSUE TITLE
System.BadImageFormatException: Bad IL format with Asp.net Core 2.1.1 on Azure

### ISSUE THREAD

**Issue by FanrayMedia** [dlemstra/Magick.NET#244]
I have an Asp.net Core 2.1.1 web app using `Magick.NET-Q16-AnyCPU` version `7.5.0`, when I deployed to Azure I kept getting `System.BadImageFormatException: Bad IL format`, basically it is unable to load dll D:\home\site\wwwroot\runtimes\win7-x64\native\Magick.NET-Q16-x64.Native.dll.

Any idea on how to fix this issue?  Thank you.

**Comment by dlemstra** [comment]
@FanrayMedia Did you resolve your issue?

**Comment by FanrayMedia** [comment]
I found the issue, basically I was loading all the dlls on app start and this wasn't a regular .net dll.  I got around it doing a [try and catch on this exception](https://github.com/FanrayMedia/Fanray/blob/dev/src/Fan/Helpers/TypeFinder.cs#L50-L57).  Thank you @dlemstra
