### ISSUE TITLE
Preserving transparency when converting EPS to PNG

### ISSUE THREAD

**Issue by BenGiroux** [dlemstra/Magick.NET#246]
Hi Dirk,

I am attempting to convert an EPS to PNG file (which I've managed to do with GhostScript) but can't seem to figure out how to preserve the transparency. I've tried a number of things already and instead get a white background. Any thoughts? Thank you for your support.

        /// <summary>
        /// Used to convert a file to another format
        /// </summary>
        /// <param name="sourcePath">Source path of the file</param>
        /// <param name="destinationPath">Destination path of the file</param>
        public void ConvertToFormat(string sourcePath, string destinationPath)
        {
            // Get file extension
            string extension = destinationPath.Substring(destinationPath.LastIndexOf('.') + 1, destinationPath.Length - (destinationPath.LastIndexOf('.') + 1));

            // Ensure that we are converting to a supported file format
            MagickFormat format;
            if (Enum.TryParse(extension, true, out format))
            {
                // Create a new image file.
                MagickImage image = new MagickImage(sourcePath);
                // Keep transparency if PNG
                if (format == MagickFormat.Png)
                {
                    image.BackgroundColor = MagickColors.Transparent;
                    image.Transparent(MagickColors.White);
                }
                
                image.Write(destinationPath);
            }
        }

**Comment by dlemstra** [comment]
Can you share your input image?

**Comment by BenGiroux** [comment]
Hi Dirk,

Here is the PNG output I get: https://ibb.co/g0Lm7J
This is the PNG output I would like from ImageMagick (which was originally retrieved from Photoshop): https://ibb.co/nfvEuy

Thank you,
Ben

**Comment by dlemstra** [comment]
Thanks for the response @BenGiroux but could you add the input image instead?

**Comment by BenGiroux** [comment]
Sure,
This is the original EPS: https://www.dropbox.com/s/cow9pvdj0z8kyvh/Aurora%20Authorized%204C%2012x20.eps?dl=0

**Comment by dlemstra** [comment]
Ghostscript will try to read the file in the CMYK colorspace and Ghostscript has no support for reading CMYKA. You can however tell it to read the file in the sRGB colorspace that has support for reading the alpha channel. You should do something like this:

```C#
var readSettings = new MagickReadSettings()
{
    ColorSpace = ColorSpace.sRGB
};

// Create a new image file.
using (var image = new MagickImage(sourcePath, readSettings))
{
    image.Write(destinationPath);
}
```

**Comment by BenGiroux** [comment]
Worked like a charm - thank you Dirk!

**Comment by kaya18** [comment]
For anyone else who stumbles upon this =)

`MagickImage image = new MagickImage(sourcePath);
                image.ColorSpace = ColorSpace.sRGB;`
