### ISSUE TITLE
NonconformingDrawingPrimitiveDefinition when trying to draw text on Linux

### ISSUE THREAD

**Issue by Sirush** [dlemstra/Magick.NET#247]
Hello,

I've been trying to port my code that runs perfectly well on Windows to **Linux** (**Ubuntu 16.04**) but I keep being blocked by errors when trying to ****draw** text**.
After setting _FONTCONFIG_PATH_ with `export FONTCONFIG_PATH=/usr/share/fonts` I managed to get rid of a `Fontconfig error: Cannot load default config file` error but now I'm stuck with the following error 
```
ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4287
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
   at ImageMagick.Drawables.Draw(IMagickImage image)
   at DiscordBot.Services.UserService.<GenerateProfileCard>d__41.MoveNext() in /home/discordbot/Services/UserService.cs:line 421
```

I tried everything I could think of, published with linux-x64 like talked about here #215, manually built a version of fontconfig, but nothing seems to work.

Thanks in advance if you have any idea how to fix this issue !

**Comment by dlemstra** [comment]
Have you tried to run `fc-cache`? I do this in the Travis build: https://github.com/dlemstra/Magick.NET/blob/master/Tools/Travis/Build.sh

**Comment by Sirush** [comment]
Wow, thanks a lot !
Doing this and installing ttf-mscorefonts-installer fixed it, can't believe it was this easy ahah !

**Comment by idchlife** [comment]
@dlemstra it seems your link not working. Could you please elaborate about fc-cache solution? Having the same error on CentOS with linux-x64 build.

**Comment by dlemstra** [comment]
Will update the link to that file later tonight. With the current build I now do this: https://github.com/dlemstra/Magick.NET/blob/cf5c133f92818f0dabe63397db08a23fe6275b9c/build/linux/install.dependencies.sh.

**Comment by idchlife** [comment]
@dlemstra you're a life saver! Thanks!

For anyone coming here from CentOS, you need to install this: https://centos.pkgs.org/7/nux-dextop-x86_64/msttcore-fonts-installer-2.6-1.noarch.rpm.html

Basically:

```bash
cd /usr/src

wget http://li.nux.ro/download/nux/dextop/el7/x86_64//msttcore-fonts-installer-2.6-1.noarch.rpm

sudo yum install msttcore-fonts-installer-2.6-1.noarch.rpm
```

**Comment by dlemstra** [comment]
The link has been fixed and I am happy to hear that you figured out how to resolve this. And thanks for adding the explanation for future visitors.

**Comment by msx752** [comment]
i had same issue today on `ubuntu 18.04` and _i found more general way to fix it_, because ubuntu using `deb` **not** `yum and rpm` so i found this.

**here is the additional Dockerfile Configuration to fix this issue:**

```
RUN apt-get update \
        && echo 'msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true' | debconf-set-selections \
        && apt-get install -y --allow-unauthenticated \
        ttf-mscorefonts-installer*
```
@dlemstra this configuration should be mentioned at documentation as well, thanks for your work 👍

**Comment by kakaby13** [comment]
@msx752 did any way to avoid all of this? So I mean if I understand correct, we have this issue because tool use Microsoft fonts, so, anyway to simply use any common font from host system? It it even possible? Sorry for noob question, I'm just learning

**Comment by kakaby13** [comment]
If my experience helps anyone. I was making a **_deb package_** and it was not very suitable for me to use _**docker**_, but what worked for me was to add a dependency on **_ttf-mscorefonts-installer_**. Fortunately it is on the default list of apt packages.
