### ISSUE TITLE
How Can I Annotate Like in This Example ?

### ISSUE THREAD

**Issue by GlennIM** [dlemstra/Magick.NET#248]
How can I write this in C# as shown here... https://www.imagemagick.org/Usage/annotating

Command:
convert dragon.gif   -background Khaki  label:'Faerie Dragon' \
          -gravity Center -append    anno_label.jpg

Thanks, Glenn

**Comment by GlennIM** [comment]
Thank you SO much dlemstra...

This works great. I changed the font and font size using Font and FontPointsize in the readSettings but for different size images that are narrow in size the text in the label gets cut off. How can I change the code so the FontPointsize is in proportion to the image size so the text appears ok ?

Also, for the label, what can I change so that there is essentially 2 labels, one below the other with a new line separating them like so ?

**Faerie Dragon

Tooth Fairy**

Also, if I wanted to put label at the top of image instead of the bottom, do I just reorder the adding of the images to the collection?

**Comment by dlemstra** [comment]
When you specify the `Width` and `Height` in the `readSettings` the size of the font fill be automatically determined. Below is another example that does this. I also changed the order in it and added newlines.

```C#
using (var images = new MagickImageCollection())
{
    var dragon = new MagickImage("dragon.gif");

    var readSettings = new MagickReadSettings()
    {
        Width = dragon.Width,
        Height = 100,
        BackgroundColor = MagickColors.Khaki,
        TextGravity = Gravity.Center // This will center the text
    };

    var label = new MagickImage("label:**Faerie Dragon\n\nTooth Fairy**", readSettings);

    images.Add(label);
    images.Add(dragon);

    using (var result = images.AppendVertically())
    {
        result.Write("anno_label.jpg");
    }
}
```

**Comment by GlennIM** [comment]
Thanks Again dlemstra...

Do you have a library of "code snippets" in C# I can view? I have searched the web and found only a few based upon the command line Image Magick commands.

I am most interested now in "Creating Thumbnails and Framing" at https://www.imagemagick.org/Usage/thumbnails like "Simple Frame", Montage Framing, Raised Button and Fancy Corner Overlay.

Thanks,
- Glenn

**Comment by dlemstra** [comment]
I don't have a library with "code snippets" available at this point. This has also been requested in #238 but I will first need to figure out how I will set this up.

The best tip that I can give you at the moment is that most methods on the `MagickImage` class have the same name as one of the command line options. And if you cannot find it there you it is very likely that you can find it on the `MagickImageCollection` class.

**Comment by GlennIM** [comment]
Thanks... Because of how complex it is for me to try and figure out .NET code for ImageMagik commands, I decided to execute the CMD.exe command from C#. I tried a few of them like the one below and works great. When you have a "code snippets" library made I would love it immensely! 

           System.Diagnostics.Process process = new System.Diagnostics.Process();
           System.Diagnostics.ProcessStartInfo startInfo = new System.Diagnostics.ProcessStartInfo();
            startInfo.WindowStyle = System.Diagnostics.ProcessWindowStyle.Hidden;
            startInfo.FileName = "cmd.exe";

            // FRAME
            startInfo.Arguments = "/C magick " + img + " -mattecolor peru -frame 9x9+3+3 " + imgFrame;
            process.StartInfo = startInfo;
            process.Start();
