### ISSUE TITLE
Missing Magick.NET-Q16-HDRI-x64.Native.dll

### ISSUE THREAD

**Issue by stefanneculai** [dlemstra/Magick.NET#25]
When initializing an ImageMagick object, the following error is being thrown on MacOS:

```bash
System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x64.Native.dll': The specified module could not be found.
``` 

I am including `"Magick.NET.Core-Q16": "7.0.3.502"` as a dependency.

**Comment by dlemstra** [comment]
Running this library on Mac is currently not supported. And to add support I would need to buy/receive a Mac so I don't think this will happen anytime soon. I do hope that I will be able to add support for Linux next year.

**Comment by stefanneculai** [comment]
To me it looks like an incorrect reference. It is installing `Magick.NET-Q16.Native`, but then looking to reference `Magick.NET-Q16-x64.Native`.

**Comment by dlemstra** [comment]
You are getting this message because the Magick.NET.Core library has determined that you are running the application in a 64-bit environment. It will then try to load the library that contains the native code. This library is called `Magick.NET-Q16-x64.Native.dll` on Windows. But there is no native library available on Mac and that is why it fails.

**Comment by darkguy2008** [comment]
It's 2017 and I'm still getting the same error. Any alternatives to this lib for macOS ? final target is Windows/Linux but I need to develop this on a Mac. Also @dlemstra you could just get OSX in a VM and build the library, it's not that hard :P

**Comment by jayantsingh304** [comment]
solution: copy missing dll into project root (not inside Assets/, but below it)

**Comment by dapoulin** [comment]
Getting the same issue today too...

**Comment by dlemstra** [comment]
@dapoulin Are you running on Mac? I might be able to build on a Mac this weekend with the help of VSTS. Will try to get a binary for mac then.

**Comment by dapoulin** [comment]
Yes, I am running on Mac only. I tried also to build on mac without success... So if you are able to provide a binary for mac, it would be great (Thank you so much in advance!). Currently we are using the imagemagick libs with sh scripts but are migrating to your port (Magick.Net ) solution. In that way, it would be possible for use to provide solutions running on mac too :-)

**Comment by winiciuscota** [comment]
Getting this same error on linux.

**Comment by marchanddesable** [comment]
same for me... 
.net core 2.0, visualstudio windows => docker linux
that's the 2nd lib that I try.... I will have to find something else... ):

**Comment by dlemstra** [comment]
@marchanddesable Can you give the latest release another try?

**Comment by marchanddesable** [comment]
@dlemstra I have installed Magick.NET-Q8-x64 from nugets.
It works, and the quality is better than ImageSharp, so I will use your library.

Thank you.

**Comment by winiciuscota** [comment]
Magick.NET-Q8-x64 7.4.2 is working for me as well. (developing on archlinux and deploying to ubuntu).

Thank you.

**Comment by Hlautameki** [comment]
Hi, it still doesn't work on mac os:
"Unable to load DLL 'Magick.NET-Q16-x64.Native.dll': The specified module or one of its dependencies could not be found.\n (Exception from HRESULT: 0x8007007E)"

**Comment by dlemstra** [comment]
Still working on adding support for macos. No idea when it will be available .

**Comment by gimlichael** [comment]
Same error when setting deployment mode to Self-Contained. I think you should look more into .NET Core and the various ways of deploying. Otherwise, keep up the good work.

**Comment by dlemstra** [comment]
@gimlichael Which OS are you working on, and with which version did you experience this issue?

**Comment by gimlichael** [comment]
@dlemstra my developer machine is a Windows 8.1 with Visual Studio 2017 Enterprise version.

The version of your fine product is 7.6.0 (latest).

The scenario I am experiencing the issue with, is a self-contained deployment to Windows Azure Web App. Behind the scene, Web App uses either Windows 2016 or a Linux variant. Server is Kestrel and application is a ASP.NET Core 2.1 project.

**Comment by roduman** [comment]
Unable to load DLL 'Magick.Native-Q16-x64.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) - in last version 7.14.0

**Comment by hermanho** [comment]
> Unable to load DLL 'Magick.Native-Q16-x64.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) - in last version 7.14.0

Are you install with Magick.NET-Q16-AnyCPU? I have same error and it is caused by the dll is missing in nuget package (#467). It should works when you install with Magick.NET-Q16-x64 nuget package.

**Comment by dlemstra** [comment]
@roduman You are probably experiencing the same issue as reported in #467. A new release will be published soon.

**Comment by jlankitus** [comment]
Hello! What is the status on the OSX support? I see that the .dylib is available, but I still get errors including it '.dll not found exception' (I'm attempting to use it within Unity 3D 2019.3)

**Comment by Kingtem** [comment]
Hi, any news about OSX support?

**Comment by dlemstra** [comment]
Support for macOS should be available. Have you tried this @Kingtem?

**Comment by Kingtem** [comment]
@dlemstra  I use it in Unity 2019.2 and 2019.3. Everything is ok on Windows, but on Mac I got these error:
DllNotFoundException: Magick.Native-Q8-x64.dll
ImageMagick.Environment+NativeEnvironment.Initialize () (at <45da00cce4a742bfa949fe9dfd56ed5d>:0)
ImageMagick.Environment.Initialize () (at <45da00cce4a742bfa949fe9dfd56ed5d>:0)
ImageMagick.MagickSettings+NativeMagickSettings..cctor () (at <45da00cce4a742bfa949fe9dfd56ed5d>:0)
Rethrow as TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception.
ImageMagick.MagickSettings..ctor () (at <45da00cce4a742bfa949fe9dfd56ed5d>:0)
ImageMagick.MagickImage..ctor () (at <45da00cce4a742bfa949fe9dfd56ed5d>:0)

**Comment by dlemstra** [comment]
You might want to chat with @jlankitus. He reported something similar in #570.

**Comment by jlankitus** [comment]
@Kingtem hello! I haven't resolved this yet, but I'd appreciate if you upvote my issue on the Unity bug tracker. I've spent alot of time trying to fix this bug, and it seems to be specific to Unity's handling of .dylib files. Let's chat more on this, I need to figure this out as soon :)

**Comment by jlankitus** [comment]
@Kingtem https://issuetracker.unity3d.com/issues/dllnotfoundexception-is-thrown-in-console-window-when-entering-the-play-mode here is the bug report

**Comment by Kingtem** [comment]
@jlankitus Sure! I've voted. That's a really weird problem. Now I try to use Unity 2019 but still dosent work, could you share some experience about the older Unity solution.
