### ISSUE TITLE
Failed detecting svg format after upgrading from 7.4.6 to 7.5.0

### ISSUE THREAD

**Issue by guylando** [dlemstra/Magick.NET#250]
We have a method which uses Magick.NET to detect image format from its binary header
byte[] image = ...;
MagickImageInfo info = new MagickImageInfo(image);
return info.Format;

This used to work while using version 7.4.6 but it fails in version 7.5.0 when image byte array is an svg image.
There is an error "no decode delegate for this image format `' @ error/blob.c/BlobToImage/456".

I saw that a solution is to pass to MagickImageInfo constructor settings with svg format set but that ruins the whole point of detecting the image format.

How can image format be detected in 7.5.0 from an image stored in a byte array?

And another issue:
Same thing but getting format from a stream instead of a byte array now returns "Value cannot be empty.
Parameter name: stream" exception while worked fine in 7.4.6.

**Comment by dlemstra** [comment]
Can you share the first few bytes of your byte array?

**Comment by guylando** [comment]
60,115,118,103,32,120,109,108,110,115,61,34,104,116,116,112,58,47,47,119,119,119,46,119,51,46

**Comment by dlemstra** [comment]
Your second issue is most likely due to a check that has been recently added. I suspect that you are writing to the stream and not setting the `Position` back to `0` before you pass it to the constructor.

And I gave your byte array a test with older versions (including 7.4.6) of Magick.NET but they all throw an exception. Are you sure that you used 7.4.6.

**Comment by guylando** [comment]
I am aware of stream position and setting it to 0 before and after call to magicknet (done it before update and still doing it now).

Yes I am sure, probably you have exception because you dont use the full byte array, I gave you only the first few bytes.

Note that I currently solved the problem by passing MagickReadSettings with Format = svg and catching exception and then MagickReadSettings Format = jpeg and catching exception and then MagickReadSettings Format  = png and this way I discover what is the correct format. But thats an ugly hack to overcome magicknet lack of "identify" imagemagick functionality.

**Comment by guylando** [comment]
Could it be because the svg file does not start with
`<?xml version="1.0" encoding="UTF-8"?>`
? I recently removed it as part of svg optimizations so that also might be related.
If so then why the constructor with MagickReadSettings with Format = svg works?
Can you maybe make the svg identification code work if the first tag is an svg tag without the xml tag?

**Comment by dlemstra** [comment]
This library does not lack the "identify" functionality the `MagickImageInfo` class represents that functionality.

I was just about to respond that I check the logs of ImageMagick and that I could not find anything in the logs that this ever worked with your byte array. And I was going to ask if you recently changed anything yourself 😄.

It works when you specify the `Format` in the `MagickReadSettings` because you are telling ImageMagick that the byte array is an SVG file and it won't try to detect the format itself.

I just pushed a patch to the ImageMagick repository to also detect SVG as a format when the file starts with and `<svg` tag. And I was able to read your byte array successfully with that and detect the format as SVG.

**Comment by guylando** [comment]
@dlemstra great! how can I get that? I will check regarding the stream bug after I get this patch first

**Comment by dlemstra** [comment]
@guylando The new release has been publish. It should now be able to also detect the svg from just the svg tag.

**Comment by guylando** [comment]
@dlemstra 
getting error "no decode delegate for this image format `' @ error/blob.c/CustomStreamToImage/770"
when calling 

byte[] image = ...
MemoryStream stream = new MemoryStream(image);
stream.Position = 0;
new MagickImageInfo(stream);

where original image byte array is:

60,115,118,103,32,120,109,108,110,115,61,34,104,116,116,112,58,47,47,119,119,119,46,119,51,46,111,114,103,47,50,48,48,48,47,115,118,103,34,32,120,109,108,110,115,58,120,108,105,110,107,61,34,104,116,116,112,58,47,47,119,119,119,46,119,51,46,111,114,103,47,49,57,57,57,47,120,108,105,110,107,34,32,118,105,101,119,66,111,120,61,34,48,32,48,32,49,54,48,32,49,54,48,34,62,60,100,101,102,115,62,60,99,105,114,99,108,101,32,105,100,61,34,97,34,32,99,120,61,34,56,48,34,32,99,121,61,34,56,48,34,32,114,61,34,56,48,34,47,62,60,108,105,110,101,97,114,71,114,97,100,105,101,110,116,32,120,49,61,34,53,48,37,34,32,121,49,61,34,49,48,52,46,51,37,34,32,120,50,61,34,53,48,37,34,32,121,50,61,34,48,37,34,32,105,100,61,34,100,34,62,60,115,116,111,112,32,115,116,111,112,45,99,111,108,111,114,61,34,35,51,48,50,51,65,69,34,32,111,102,102,115,101,116,61,34,48,37,34,47,62,60,115,116,111,112,32,115,116,111,112,45,99,111,108,111,114,61,34,35,53,51,65,48,70,68,34,32,111,102,102,115,101,116,61,34,52,55,46,53,37,34,47,62,60,115,116,111,112,32,115,116,111,112,45,99,111,108,111,114,61,34,35,66,52,69,67,53,49,34,32,111,102,102,115,101,116,61,34,49,48,48,37,34,47,62,60,47,108,105,110,101,97,114,71,114,97,100,105,101,110,116,62,60,112,97,116,104,32,100,61,34,77,49,50,51,32,48,99,48,32,49,54,46,51,45,49,52,46,55,32,53,50,46,55,45,50,52,46,51,32,54,49,46,53,86,55,48,99,48,32,53,46,51,32,50,46,54,32,49,51,46,54,32,50,57,46,51,32,49,56,46,55,97,52,49,46,51,32,52,49,46,51,32,48,32,48,32,49,32,51,50,32,50,57,46,51,72,48,97,51,53,46,55,32,51,53,46,55,32,48,32,48,32,49,32,50,57,46,51,45,50,57,46,51,99,50,54,46,55,45,52,46,56,32,51,50,45,49,51,46,52,32,51,50,45,49,56,46,55,118,45,56,46,53,67,53,49,46,55,32,53,50,46,55,32,51,54,32,49,54,46,53,32,51,54,32,48,104,56,55,122,34,32,105,100,61,34,99,34,47,62,60,47,100,101,102,115,62,60,103,32,102,105,108,108,61,34,110,111,110,101,34,32,102,105,108,108,45,114,117,108,101,61,34,101,118,101,110,111,100,100,34,62,60,109,97,115,107,32,105,100,61,34,98,34,32,102,105,108,108,61,34,35,102,102,102,34,62,60,117,115,101,32,120,108,105,110,107,58,104,114,101,102,61,34,35,97,34,47,62,60,47,109,97,115,107,62,60,117,115,101,32,102,105,108,108,61,34,35,52,52,52,69,53,55,34,32,120,108,105,110,107,58,104,114,101,102,61,34,35,97,34,47,62,60,103,32,109,97,115,107,61,34,117,114,108,40,35,98,41,34,62,60,103,32,116,114,97,110,115,102,111,114,109,61,34,116,114,97,110,115,108,97,116,101,40,48,32,52,50,41,34,62,60,117,115,101,32,102,105,108,108,61,34,35,53,55,54,52,54,70,34,32,120,108,105,110,107,58,104,114,101,102,61,34,35,99,34,47,62,60,117,115,101,32,102,105,108,108,45,111,112,97,99,105,116,121,61,34,46,53,34,32,102,105,108,108,61,34,117,114,108,40,35,100,41,34,32,120,108,105,110,107,58,104,114,101,102,61,34,35,99,34,47,62,60,47,103,62,60,112,97,116,104,32,100,61,34,77,52,56,32,57,50,76,50,48,32,54,56,86,52,50,46,54,76,53,48,32,49,55,108,50,54,46,50,32,50,50,46,51,97,54,32,54,32,48,32,48,32,48,32,55,46,54,32,48,76,49,49,48,32,49,55,108,51,48,32,50,53,46,54,86,54,56,108,45,50,56,32,50,52,97,54,32,54,32,48,32,48,32,48,45,50,32,52,46,53,118,50,50,46,57,108,45,50,54,46,50,32,50,50,46,51,97,54,32,54,32,48,32,48,32,49,45,55,46,54,32,48,76,53,48,32,49,49,57,46,51,86,57,54,46,52,97,54,32,54,32,48,32,48,32,48,45,50,45,52,46,53,122,109,53,50,46,52,45,51,55,46,50,97,49,51,32,49,51,32,48,32,48,32,48,45,49,51,32,49,51,104,49,51,97,49,51,32,49,51,32,48,32,48,32,48,32,49,51,45,49,51,104,45,49,51,122,109,45,49,52,46,57,32,51,56,104,57,46,51,99,48,45,54,46,49,45,53,45,49,49,46,49,45,49,49,46,49,45,49,49,46,49,104,45,54,46,53,99,45,50,46,53,32,48,45,52,46,54,45,50,45,52,46,54,45,52,46,54,118,45,57,46,51,97,49,51,32,49,51,32,48,32,48,32,48,45,49,51,45,49,51,104,45,49,51,97,49,51,32,49,51,32,48,32,48,32,48,32,49,51,32,49,51,72,54,57,118,50,48,46,52,99,48,32,50,46,53,32,50,32,52,46,54,32,52,46,54,32,52,46,54,104,52,46,54,99,49,46,56,32,50,46,51,45,50,46,49,32,54,45,49,49,46,57,32,49,49,46,51,97,50,32,50,32,48,32,48,32,48,32,49,46,51,32,51,46,54,108,55,46,49,45,49,46,52,99,52,46,56,45,49,32,57,46,55,45,49,32,49,52,46,52,32,48,108,55,46,50,32,49,46,52,97,50,32,50,32,48,32,48,32,48,32,49,46,51,45,51,46,54,99,45,57,46,56,45,53,46,50,45,49,51,46,56,45,57,45,49,50,45,49,49,46,51,122,34,32,102,105,108,108,61,34,35,50,68,51,56,52,49,34,47,62,60,47,103,62,60,47,103,62,60,47,115,118,103,62

**Comment by dlemstra** [comment]
I just created the following unit tests:

```C#
[TestMethod]
public void TestStream()
{
    var bytes = new byte[]
    {
        60, 115, 118, 103, 32, 120, 109, 108, 110, 115, 61, 34, 104, 116, 116, 112, 58, 47, 47,
        119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 50, 48, 48, 48, 47, 115, 118, 103, 34,
        32, 120, 109, 108, 110, 115, 58, 120, 108, 105, 110, 107, 61, 34, 104, 116, 116, 112, 58,
        47, 47, 119, 119, 119, 46, 119, 51, 46, 111, 114, 103, 47, 49, 57, 57, 57, 47, 120, 108,
        105, 110, 107, 34, 32, 118, 105, 101, 119, 66, 111, 120, 61, 34, 48, 32, 48, 32, 49, 54,
        48, 32, 49, 54, 48, 34, 62, 60, 100, 101, 102, 115, 62, 60, 99, 105, 114, 99, 108, 101,
        32, 105, 100, 61, 34, 97, 34, 32, 99, 120, 61, 34, 56, 48, 34, 32, 99, 121, 61, 34, 56,
        48, 34, 32, 114, 61, 34, 56, 48, 34, 47, 62, 60, 108, 105, 110, 101, 97, 114, 71, 114, 97,
        100, 105, 101, 110, 116, 32, 120, 49, 61, 34, 53, 48, 37, 34, 32, 121, 49, 61, 34, 49, 48,
        52, 46, 51, 37, 34, 32, 120, 50, 61, 34, 53, 48, 37, 34, 32, 121, 50, 61, 34, 48, 37, 34, 32,
        105, 100, 61, 34, 100, 34, 62, 60, 115, 116, 111, 112, 32, 115, 116, 111, 112, 45, 99, 111,
        108, 111, 114, 61, 34, 35, 51, 48, 50, 51, 65, 69, 34, 32, 111, 102, 102, 115, 101, 116, 61,
        34, 48, 37, 34, 47, 62, 60, 115, 116, 111, 112, 32, 115, 116, 111, 112, 45, 99, 111, 108, 111,
        114, 61, 34, 35, 53, 51, 65, 48, 70, 68, 34, 32, 111, 102, 102, 115, 101, 116, 61, 34, 52, 55,
        46, 53, 37, 34, 47, 62, 60, 115, 116, 111, 112, 32, 115, 116, 111, 112, 45, 99, 111, 108, 111,
        114, 61, 34, 35, 66, 52, 69, 67, 53, 49, 34, 32, 111, 102, 102, 115, 101, 116, 61, 34, 49, 48,
        48, 37, 34, 47, 62, 60, 47, 108, 105, 110, 101, 97, 114, 71, 114, 97, 100, 105, 101, 110, 116,
        62, 60, 112, 97, 116, 104, 32, 100, 61, 34, 77, 49, 50, 51, 32, 48, 99, 48, 32, 49, 54, 46, 51,
        45, 49, 52, 46, 55, 32, 53, 50, 46, 55, 45, 50, 52, 46, 51, 32, 54, 49, 46, 53, 86, 55, 48, 99,
        48, 32, 53, 46, 51, 32, 50, 46, 54, 32, 49, 51, 46, 54, 32, 50, 57, 46, 51, 32, 49, 56, 46, 55,
        97, 52, 49, 46, 51, 32, 52, 49, 46, 51, 32, 48, 32, 48, 32, 49, 32, 51, 50, 32, 50, 57, 46, 51,
        72, 48, 97, 51, 53, 46, 55, 32, 51, 53, 46, 55, 32, 48, 32, 48, 32, 49, 32, 50, 57, 46, 51, 45,
        50, 57, 46, 51, 99, 50, 54, 46, 55, 45, 52, 46, 56, 32, 51, 50, 45, 49, 51, 46, 52, 32, 51, 50,
        45, 49, 56, 46, 55, 118, 45, 56, 46, 53, 67, 53, 49, 46, 55, 32, 53, 50, 46, 55, 32, 51, 54, 32,
        49, 54, 46, 53, 32, 51, 54, 32, 48, 104, 56, 55, 122, 34, 32, 105, 100, 61, 34, 99, 34, 47, 62,
        60, 47, 100, 101, 102, 115, 62, 60, 103, 32, 102, 105, 108, 108, 61, 34, 110, 111, 110, 101, 34,
        32, 102, 105, 108, 108, 45, 114, 117, 108, 101, 61, 34, 101, 118, 101, 110, 111, 100, 100, 34, 62,
        60, 109, 97, 115, 107, 32, 105, 100, 61, 34, 98, 34, 32, 102, 105, 108, 108, 61, 34, 35, 102, 102,
        102, 34, 62, 60, 117, 115, 101, 32, 120, 108, 105, 110, 107, 58, 104, 114, 101, 102, 61, 34, 35,
        97, 34, 47, 62, 60, 47, 109, 97, 115, 107, 62, 60, 117, 115, 101, 32, 102, 105, 108, 108, 61, 34,
        35, 52, 52, 52, 69, 53, 55, 34, 32, 120, 108, 105, 110, 107, 58, 104, 114, 101, 102, 61, 34, 35,
        97, 34, 47, 62, 60, 103, 32, 109, 97, 115, 107, 61, 34, 117, 114, 108, 40, 35, 98, 41, 34, 62, 60,
        103, 32, 116, 114, 97, 110, 115, 102, 111, 114, 109, 61, 34, 116, 114, 97, 110, 115, 108, 97, 116,
        101, 40, 48, 32, 52, 50, 41, 34, 62, 60, 117, 115, 101, 32, 102, 105, 108, 108, 61, 34, 35, 53, 55,
        54, 52, 54, 70, 34, 32, 120, 108, 105, 110, 107, 58, 104, 114, 101, 102, 61, 34, 35, 99, 34, 47, 62,
        60, 117, 115, 101, 32, 102, 105, 108, 108, 45, 111, 112, 97, 99, 105, 116, 121, 61, 34, 46, 53, 34,
        32, 102, 105, 108, 108, 61, 34, 117, 114, 108, 40, 35, 100, 41, 34, 32, 120, 108, 105, 110, 107, 58,
        104, 114, 101, 102, 61, 34, 35, 99, 34, 47, 62, 60, 47, 103, 62, 60, 112, 97, 116, 104, 32, 100, 61,
        34, 77, 52, 56, 32, 57, 50, 76, 50, 48, 32, 54, 56, 86, 52, 50, 46, 54, 76, 53, 48, 32, 49, 55, 108,
        50, 54, 46, 50, 32, 50, 50, 46, 51, 97, 54, 32, 54, 32, 48, 32, 48, 32, 48, 32, 55, 46, 54, 32, 48,
        76, 49, 49, 48, 32, 49, 55, 108, 51, 48, 32, 50, 53, 46, 54, 86, 54, 56, 108, 45, 50, 56, 32, 50,
        52, 97, 54, 32, 54, 32, 48, 32, 48, 32, 48, 45, 50, 32, 52, 46, 53, 118, 50, 50, 46, 57, 108, 45,
        50, 54, 46, 50, 32, 50, 50, 46, 51, 97, 54, 32, 54, 32, 48, 32, 48, 32, 49, 45, 55, 46, 54, 32, 48,
        76, 53, 48, 32, 49, 49, 57, 46, 51, 86, 57, 54, 46, 52, 97, 54, 32, 54, 32, 48, 32, 48, 32, 48, 45,
        50, 45, 52, 46, 53, 122, 109, 53, 50, 46, 52, 45, 51, 55, 46, 50, 97, 49, 51, 32, 49, 51, 32, 48,
        32, 48, 32, 48, 45, 49, 51, 32, 49, 51, 104, 49, 51, 97, 49, 51, 32, 49, 51, 32, 48, 32, 48, 32, 48,
        32, 49, 51, 45, 49, 51, 104, 45, 49, 51, 122, 109, 45, 49, 52, 46, 57, 32, 51, 56, 104, 57, 46, 51,
        99, 48, 45, 54, 46, 49, 45, 53, 45, 49, 49, 46, 49, 45, 49, 49, 46, 49, 45, 49, 49, 46, 49, 104, 45,
        54, 46, 53, 99, 45, 50, 46, 53, 32, 48, 45, 52, 46, 54, 45, 50, 45, 52, 46, 54, 45, 52, 46, 54, 118,
        45, 57, 46, 51, 97, 49, 51, 32, 49, 51, 32, 48, 32, 48, 32, 48, 45, 49, 51, 45, 49, 51, 104, 45, 49,
        51, 97, 49, 51, 32, 49, 51, 32, 48, 32, 48, 32, 48, 32, 49, 51, 32, 49, 51, 72, 54, 57, 118, 50, 48,
        46, 52, 99, 48, 32, 50, 46, 53, 32, 50, 32, 52, 46, 54, 32, 52, 46, 54, 32, 52, 46, 54, 104, 52, 46,
        54, 99, 49, 46, 56, 32, 50, 46, 51, 45, 50, 46, 49, 32, 54, 45, 49, 49, 46, 57, 32, 49, 49, 46, 51,
        97, 50, 32, 50, 32, 48, 32, 48, 32, 48, 32, 49, 46, 51, 32, 51, 46, 54, 108, 55, 46, 49, 45, 49, 46,
        52, 99, 52, 46, 56, 45, 49, 32, 57, 46, 55, 45, 49, 32, 49, 52, 46, 52, 32, 48, 108, 55, 46, 50, 32,
        49, 46, 52, 97, 50, 32, 50, 32, 48, 32, 48, 32, 48, 32, 49, 46, 51, 45, 51, 46, 54, 99, 45, 57, 46,
        56, 45, 53, 46, 50, 45, 49, 51, 46, 56, 45, 57, 45, 49, 50, 45, 49, 49, 46, 51, 122, 34, 32, 102, 105,
        108, 108, 61, 34, 35, 50, 68, 51, 56, 52, 49, 34, 47, 62, 60, 47, 103, 62, 60, 47, 103, 62, 60, 47,
        115, 118, 103, 62
    };

    using (var memStream = new MemoryStream(bytes))
    {
        var info = new MagickImageInfo(memStream);

        Assert.AreEqual(MagickFormat.Svg, info.Format);
    }
}
```

And this passes without any issues.

**Comment by guylando** [comment]
Seems those exceptions happened while testing in debug mode because of side effects of the watch window. We will do further tests and I will close this if nothing comes up.
Thanks
