### ISSUE TITLE
Compress Image ?

### ISSUE THREAD

**Issue by GlennIM** [dlemstra/Magick.NET#251]
I'm creating a lot of "enhanced" images and uploading them to my shared host account.

What is the code for compressing an image so it is a smaller size but maintains the original image size?

Thanks so much,
Glenn

**Comment by dlemstra** [comment]
You can use the `ImageOptimizer` class for that.

**Comment by GlennIM** [comment]
Thanks again... I used the ImageOptimizer class using the code below and it works. Is there any further optimizations that can be done to images to reduce the size?

Also, just for my understanding... can you tell me what this code does?
optimizer.LosslessCompress(snakewareLogo);
snakewareLogo.Refresh();

FileInfo snakewareLogo = new FileInfo("Snakeware.jpg");
Console.WriteLine("Bytes before: " + snakewareLogo.Length);
ImageOptimizer optimizer = new ImageOptimizer();
optimizer.LosslessCompress(snakewareLogo);
snakewareLogo.Refresh();
Console.WriteLine("Bytes after:  " + snakewareLogo.Length);

**Comment by dlemstra** [comment]
That line compresses the image and refreshed the `FileInfo` to update the size.

To get more compression you could try using `optimizer.Compress` instead of `optimizer.LosslessCompress`

**Comment by jericyuen** [comment]
Hi Dirk,

I've started using it for an image formatting that I need to do. Do you have an example on how this can be used with Stream?

The example from the sample have only got it from a filePath into FileInfo()

The **image** property from below are of type **System.Drawing.Image**
The **stream** property from below are of type **System.IO.Stream**

`using (var magickImage = new MagickImage((Bitmap)image))
			{
				magickImage.Format = MagickFormat.J2k;
				magickImage.Quality = 90;
				magickImage.Strip();
				magickImage.Write(stream);
			}`

Thanks

**Comment by dlemstra** [comment]
You should use the stream overload of the `Compress` or `LosslessCompress` method. But the image optimizer won't work with the `J2k` format. Only `Jpeg`, `Png` and `Gif` are supported.

**Comment by jericyuen** [comment]
Ic. Thanks for the fast reply. No wonder. Is the only way to reduce the size is to reduce the quality then?

**Comment by dlemstra** [comment]
I think that you are correct that the quality is the only way to reduce the file size. I don't know if there are other tricks possible with this file format.

**Comment by diazometan** [comment]
Hello!
I know that it’s damn late, but nevertheless, the problem is that when you write to a strem magickImage.Write(stream);
you need to move the bracket in the stream back
stream.Position = 0;

and then you can use optimizer.LosslessCompress(stream); without exception

**Comment by cmorche** [comment]
You a real one @diazometan ! 💋
