### ISSUE TITLE
The type initializer for 'X64' threw an exception

### ISSUE THREAD

**Issue by vbpAlex** [dlemstra/Magick.NET#252]
Trying to modify existing .NET code by adding few lines to change the size, modify image. tested on local machine without any issues, but on server getting error, Please help ASAP. 

Really appreciated any help.

in bin folder i have:

gsdll32
Magick.NET-Q8-AnyCPU
Magick.NET.Web-Q8-AnyCPU

New Code:

```vb.net
 ' VALIDATE AND MODIFY IMAGE ****
                Using images As New MagickImageCollection()
                    ' Add all the pages of the pdf file to the collection
                    Dim image As New MagickImage(ConvertedImage)

                    If image.Width > "850" Then
                        Dim sGeometry As New MagickGeometry()

                        With sGeometry
                            .Width = "1150"
                            .Height = "900"
                            .IgnoreAspectRatio = True
                        End With

                        image.Scale(sGeometry)
                        image.Write(ConvertedImage)
                    End If
                End Using
' VALIDATE AND MODIFY IMAGE 
```

at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_Create()
   at ImageMagick.MagickSettings.NativeMagickSettings..ctor()
   at ImageMagick.MagickSettings..ctor()
   at ImageMagick.MagickImage..ctor()
   at nomination.loadfileHandler.convert_pdf_to_image_nominee(String fn, String NomineeGEID)

**Comment by dlemstra** [comment]
What kind of exception is being raised? Can you share the details of the exception?

**Comment by vbpAlex** [comment]
The type initializer for 'X64' threw an exception.

**Comment by vbpAlex** [comment]
I've rebuild package and couldn't re produce the issue. I'll try more and
let you know, thanks a lot for quick response.

Thanks

**Comment by blackn1ght** [comment]
Got the same issue.

We've got the AnyCPU package installed, but the exception is giving:

`System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x64.Native.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))`

**Comment by dlemstra** [comment]
It is possible that your application has no access to the temporary directory @blackn1ght, see: https://github.com/dlemstra/Magick.NET/tree/master/Documentation#anycpu

**Comment by dlemstra** [comment]
@vbpAlex or @blackn1ght Can I close this issue?

**Comment by vbpAlex** [comment]
we still getting exception, but decide just to handle it locally since
looks like ddl does what it suppose to do just throw error at the end.

You may close the issue and thanks for support.

Thanks Alex.
