### ISSUE TITLE
Code For Rounded Images ?

### ISSUE THREAD

**Issue by GlennIM** [dlemstra/Magick.NET#253]
Hi again,

Do you what the code would be to achieve rounded corners on images like this one... https://sociallysorted.com.au/wp-content/uploads/2012/11/rounded-corner-example.jpg

Thanks, Glenn

**Comment by dlemstra** [comment]
Based on the commands in this example: http://www.imagemagick.org/Usage/thumbnails/#rounded I was able to create this:

```C#
using (var image = new MagickImage(MagickColors.Red, 600, 600))
{
    using (var mask = new MagickImage(MagickColors.White, image.Width, image.Height))
    {
        var size = 150;

        new ImageMagick.Drawables()
            .FillColor(MagickColors.Black)
            .StrokeColor(MagickColors.Black)
            .Polygon(new PointD(0, 0), new PointD(0, size), new PointD(size, 0))
            .Polygon(new PointD(mask.Width, 0), new PointD(mask.Width, size), new PointD(mask.Width - size, 0))
            .Polygon(new PointD(0, mask.Height), new PointD(0, mask.Height - size), new PointD(size, mask.Height))
            .Polygon(new PointD(mask.Width, mask.Height), new PointD(mask.Width, mask.Height - size), new PointD(mask.Width - size, mask.Height))
            .FillColor(MagickColors.White)
            .StrokeColor(MagickColors.White)
            .Circle(size, size, size, 0)
            .Circle(mask.Width - size, size, mask.Width - size, 0)
            .Circle(size, mask.Height - size, 0, mask.Height - size)
            .Circle(mask.Width - size, mask.Height - size, mask.Width - size, mask.Height)
            .Draw(mask);

        // This copies the pixels that were already transparent on the mask.
        using (var imageAlpha = image.Clone())
        {
            imageAlpha.Alpha(AlphaOption.Extract);
            imageAlpha.Opaque(MagickColors.White, MagickColors.None);
            mask.Composite(imageAlpha, CompositeOperator.Over);
        }

        mask.HasAlpha = false;
        image.HasAlpha = false;
        image.Composite(mask, CompositeOperator.CopyAlpha);
        image.Write("rounded-corners.png");
    }
}
```

**Comment by GlennIM** [comment]
FANTASTIC dlemstra... Your code works perfectly...

I wish there was a "central" Magick-NET library of C# code snippets like this. It would really help a lot of people out.

-Glenn

**Comment by dlemstra** [comment]
At some point in time that library will be created and I will go through the issues and copy them there. No idea when that will happen though.

**Comment by GlennIM** [comment]
Thanks dlemstra...

In that code example above would it be possible to draw a colored border or colored frame around the whole rounded corner image? Could you show me the code snippet with that code in it?

Thanks, Glenn

**Comment by GlennIM** [comment]
Hi Dirk,

Would it be possible to show the rounded corner example but cutting a simple drawn triangular shape from each corner like https://www.imagemagick.org/Usage/thumbnails/corner_cutoff.png at the page https://www.imagemagick.org/Usage/thumbnails ?

Thanks so much, Glenn

**Comment by NovemberDev** [comment]
Sorry for commenting on this old thread, but this was the better approach for me (especially for smaller images)

```cs
            using (var mask = new MagickImage(MagickColors.Black, 76, 76))
            {
                new ImageMagick.Drawables()
                    .FillColor(MagickColors.White)
                    .StrokeColor(MagickColors.White)
                    .Circle(38, 38, 38, 0)
                    .Draw(mask);

                using (var imageAlpha = second.Clone())
                {
                    imageAlpha.Alpha(AlphaOption.Extract);
                    imageAlpha.Opaque(MagickColors.White, MagickColors.None);
                    mask.Composite(imageAlpha, CompositeOperator.Over);
                }

                mask.HasAlpha = false;
                second.HasAlpha = false;
                second.Composite(mask, CompositeOperator.CopyAlpha);
                background.Composite(second, 37, 75, CompositeOperator.Over);
            }
```

**Comment by fbarbare** [comment]
Hello @dlemstra & @NovemberDev ,

I can't seem to make it work with either of your example :(

@dlemstra
With your example I only get a red square

@NovemberDev 
Where are `second` and `background` coming from? Could you post a full example?

I also tried to follow the ImageMagic site and did something like that (presumably I would get 1 rounded corner only):
```csharp
using var image = new MagickImage(imageAsBytes);

var mask = image.Clone();
mask.Alpha(AlphaOption.Extract);
mask.Draw(new List<IDrawable>()
{
    new DrawableFillColor(MagickColors.Black),
    new DrawablePolygon(new List<PointD>() {
        new PointD(0,0),
        new PointD(0,15),
        new PointD(15,0)
    }),
    new DrawableFillColor(MagickColors.Transparent),
    new DrawableCircle(15, 15, 15, 0)
});

image.Alpha(AlphaOption.Off);
image.Compose = CompositeOperator.CopyAlpha;
image.Composite(mask, CompositeOperator.CopyAlpha);

return image.ToByteArray();
```

Thanks

P.S. I'm using `Magick.NET-Q8-x64`:`7.22.2.2`

**Comment by pchandoria** [comment]
We are in 2025 and still there is no simple working solution to get rounded corner using MagicImage. Shouldn't it be a simple API using drawable?

I tested above solution, it does nothing actually. 
The only thing works incorrectly is 
**new Drawables().RoundRectangle(0, 0, finalSize.Width, finalSize.Height, 25, 25).Draw(magicImage);**
but it generates output in unexpected way

![Image](https://github.com/user-attachments/assets/6d406921-6aa9-47e9-be0f-ed96548437d6)

for the original image something like this

![Image](https://github.com/user-attachments/assets/3b76d59a-5478-42a1-aa5c-c73a8aa27273)

**Comment by dlemstra** [comment]
It's 2025 and my answer still produces a image with rounded corners:

![Image](https://github.com/user-attachments/assets/c0f5d28d-edd5-4568-9815-dd098866a1cd)
