### ISSUE TITLE
Magick.Net on Raspberry Pi - no go

### ISSUE THREAD

**Issue by heyandy1st** [dlemstra/Magick.NET#254]
I thought in all my reading, it felt like Magick.Net was up and running in .Net Core, is that correct?

I am compiling a test program on VS 2017 OS X using .Netcore 2.1.  I add NUGet Package 7.5.0.1 of Magick.NET-Q8-AnyCPU with no issues.  Write a quick sample program to go through Exif data on a single file.  Run:
dotnet publish -c Release -r linux-arm --self-contained true

Move the whole release directory to my Pi and run the program.  As soon as the line files to use Magick.Net it throws the error that it can't find the x86 version of the DLL.
Well of course it can't, it was built and linked against the AnyCPU version that is in the directory.

What am I missing?

Oh, I did just for giggles, try using the x86 NuGet package, and as expected the dotnet publish command above gave me a nice warning that I had an incompatible DLL in the publish.  But I went ahead and copied it over anyway to the Pi, and as soon as the executable is run it blows up with a BadImageFormat exception (as expected).

**Comment by dlemstra** [comment]
Magick.NET uses a native library that is compiled for the various platforms. There is support for macOS and Linux. But that is only x64 and there is no support for ARM. You will need to build the native library yourself if you want ARM support.

**Comment by heyandy1st** [comment]
I am a little confused.  What is the difference between the x86 and AnyCPU package if they aren't a full package?

**Comment by dlemstra** [comment]
No idea what you are asking? The Magick.NET library (C#) uses a native library (C) to call the various methods of ImageMagick. That native library needs to be compiled for your target platform. At this moment there is no ARM build available for Linux. Only an x64 build is available.

**Comment by gpiffaretti** [comment]
Hi, I need an ARM compatible build so that I can integrate it into Unity projects for mobile platforms.
What's the way to go? Just opened the Magick.NET.Native project in Visual Studio Community for Mac and can't change anything because it's not compatible. Is there a reason it's not being built for ARM architectures?

**Comment by dlemstra** [comment]
@gpiffaretti The binaries are build with Azure DevOps: https://dev.azure.com/dlemstra/Magick.NET/_build/results?buildId=631&view=logs. An ARM build needs to be added to add support for this.

**Comment by jonmiller1** [comment]
I believe it is possible to run the azure devops agent on your own raspberry pi.  This agent would show up in your pool in devops and you would be able to run your build pipeline on it.  I'd really like to see this happen.  I can provide the hardware or even host a pi/devops agent to get this going.

**Comment by Seabizkit** [comment]
super confused... so no ARM Support!!!! yet says anycpu, when what they mean is x86 and x64 on linux and windows.
