### ISSUE TITLE
clean up an image for tesseract OCR

### ISSUE THREAD

**Issue by plsft** [dlemstra/Magick.NET#258]
I'm trying to clean up an image for OCR processing with the TESSERACT library. I'm trying to clean the image to remove noise, and make it black and white.  I've tried .Negate() , Threshold(60) .ColorFuzz and Alpha options to no avail as the output just appears a blank white page. 

Any Ideas?

![rd-new doc 2018-07-23 12 39 35_1](https://user-images.githubusercontent.com/13736152/43097286-99a4a060-8e89-11e8-8887-6b0e153ef31e.jpg)

**Comment by dlemstra** [comment]
Maybe you can use the TextCleaner script for this: https://www.nuget.org/packages/FredsImageMagickScripts.TextCleaner? This script has commercial license, you need to contact Fred Weinhaus if you want to use it in a commercial project.
