### ISSUE TITLE
Sampling factor

### ISSUE THREAD

**Issue by julienVoltzenlogel** [dlemstra/Magick.NET#261]
Hello,

I want to follow the google recommandation for jpeg compression : https://developers.google.com/speed/docs/insights/OptimizeImages

They provide the command : 
convert puzzle.jpg -sampling-factor 4:2:0 -strip -quality 85 -interlace JPEG -colorspace sRGB puzzle_converted.jpg

I have found method to apply this configuration, but for the sampling factor, I don't found how to apply it. Can you help me ?

```
using (MagickImage image = new MagickImage(fileInfo))
{
	image.Strip();
	image.Quality = 85;
	image.ColorSpace = ColorSpace.sRGB;
	image.Interlace = Interlace.Jpeg;

	image.Write(fileInfo);
}
```

**Comment by dlemstra** [comment]
You can set the sampling-factor with `image.Settings.SetDefine(MagickFormat.Jpeg, "sampling-factor", "4:2:0")`.

But you might also want to take a look at the `ImageOptimizer` class. With the `Compress` method you probably get something similar.
