### ISSUE TITLE
Support multiple instances of tags in IPTC Profile

### ISSUE THREAD

**Issue by SpooRancher** [dlemstra/Magick.NET#262]
Currently the **IptcProfile** class supports only one occurrence of any IPTC tag. Thus, code like this using the **SetValue()** method:

`IptcProfile profile = new IptcProfile();
profile.SetValue(IptcTag.Keyword, "First");
profile.SetValue(IptcTag.Keyword, "Second");
`

will result in the profile containing only one instance the Keyword tag (25) with value "Second".

The **IptcProfile.GetValue()** method similarly will return only the first occurrence of any tag.

The get case has a workround in that the application can traverse the IptcProfile.Values IEnumerator itself. There is no workround for the set case, as the underlying collection field is not publicly exposed.

Tag handling for the IPTC profile follows that of the Exif profile, where multiple use of tags is not permitted. However, IPTC tags _are_ usable multiple times; in particular, as in the example code here, to set multiple keywords.

**Comment by flemingm** [comment]
IPTC  keyword is sting not an array. in XMP it's an array.

 The general way to add two keywords is append to the existing string via IptcProfile.GetValue(IptcTag.Keyword).


**Checking IPTC specs.**

https://iptc.org/std/photometadata/specification/IPTC-PhotoMetadata#keywords

- Data type: free-text / Cardinality: 0..unbounded
- XMP Specs :  dc:subject [Bag Text <External>]
- IIM Specs :  2:25 Keywords
- JSON Specs :  keywords [string//array]

Also:
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/IPTC.html

25	Keywords	string[0,64]+

Mapping between IPTC And XMP:
https://iptc.org/std/photometadata/specification/mapping/iptc-pmd-newsmlg2.html


IptcCore	Keywords	2:25 Keywords	dc	subject	PMD <--> NMLG2:
contentMeta/keyword {recommended}
OR
contentMeta/subject/name
