### ISSUE TITLE
Defines set via MagickReadSettings seems to be ignored on image loading.

### ISSUE THREAD

**Issue by A-KL** [dlemstra/Magick.NET#263]
Hi, 

I'm trying to load, resize and save an image using `MagickImage` and `MagickReadSettings`.
The tricky part is to completely ignore EXIF metadata and don't save to output image as well.

My code looks like:
```
var settings = new MagickReadSettings();

settings.SetDefine("profile:skip", "exif");

using (var image = new MagickImage(fileName, settings))
{

    image.Resize(image.Width - 100, image.Height - 100);

    using (var outputSteram = new FileStream(output, FileMode.Create))
    {
        image.Write(outputSteram, MagickFormat.Jpeg);
    }

    return output;
}
```
The source image is album orientation (and I want to keep it this way) but the result gets rotated 90CW (beacuse of `Orientation` in EXIF). 

I tried `RemoveProfile("exif")`, but `image` seems to "remember" that the picture supposed to be portrait already. So my guess - it should be done when the image gets loaded. However, from the source code of  `MagickImage` I can't find any traces that `Defines` are being used or passed somewhere.

Is it a library issue or it should be done in a different way?

**Comment by dlemstra** [comment]
You did not supply your image and tell me what kind of format your are reading. Have you tried using the `AutoOrient` method to fix the orientation and then calling `Strip` or `RemoveProfile("exif")` to remove the profile?

**Comment by A-KL** [comment]
@dlemstra thanks for the help. Indeed the image format was an issue - HEIC decoder for ImageMagick has some problems with image orientation. Working towards getting it fixed https://github.com/ImageMagick/ImageMagick/issues/1232
