### ISSUE TITLE
Move samples to a separate project

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/Magick.NET#264]
The samples are now part of this project and should be moved out of this project and probably also from NuGet. The current NuGet library does not work on .NET Core and it will probably be easier if someone could clone the samples project and play around with it.

It could also be an option to make the move of the samples part of the idea raised in #238 to create a website/project that contains commands that have been translated into C# code. Feel free to post any comments/ideas below.

**Comment by dlemstra** [comment]
Also add sample for: #272

**Comment by Ibrahim-Islam** [comment]
@dlemstra I can work on detaching samples into another solution. Let me know if its ok.

**Comment by dlemstra** [comment]
Thanks for your message. Could you give me a day to think about this @Ibrahim-Islam? Not sure if and how I would like to do this.

**Comment by dlemstra** [comment]
And it seems it now has been six days. I would like to keep the samples in the same project for now. Will close this issue now. Thanks for offering to help @Ibrahim-Islam.
