### ISSUE TITLE
Problems when upgrading from older version 

### ISSUE THREAD

**Issue by lokatz** [dlemstra/Magick.NET#265]
Hi,

I just upgraded an older project from a 2016 version and noticed that several functions must have changed.  I looked in the documentation but could not find examples using these functions, so I'm hoping someone here will be able to help me with the following questions:

MagickImage image = otherMagickImage.Clone() now gives me an error that it cannot implicitly convert from MagickImage.IMagickImage to MagickImage.MagickImage.  Both are of the same type, though.  How do I avoid this?

WPFimage.source = image.ToBitmapSource() no longer seems to exists.  How else can I set a WPF image from a MagickImage?

PixelCollection p = image.GetPixels()  and thisPixel = p.GetPixel(x,y).ToColor() used to give me a way to directly access the RGB values of a pixel within an image.  How can I do this now?

Appreciate any suggestions.  Thank you in advance!

**Comment by dlemstra** [comment]
`IMagickImage` and `MagickImage` are not both the same type. `MagickImage` implements the `IMagickImage` interface. Changing `MagickImage image` to `IMagickImage image` or `var image` should resolve your issue.

The `ToBitmapSource` method is still available but I am guessing that you are linking with the `netstandard` version of the library. You can resolve this by adding `targetFramework="net40"` in your packages.config.

`PixelCollection p` should be changed to `IPixelCollection p` or `var p` to fix the build.

**Comment by lokatz** [comment]
Hi Dirk,

 

Thank you very much – really appreciate your speedy reply!  

 

Best greetings,

Lothar

**Comment by dlemstra** [comment]
This has been reported in one of the other issues also but you should reset the `Position` of your `stream` back to zero. It is now at the end of the stream.

**Comment by lokatz** [comment]
stream.Position = 0;   took care of it.  Great - thanks!

**Comment by dlemstra** [comment]
@lokatz Can I close this issue now?

**Comment by lokatz** [comment]
Unless I run into another incompatibility.  :-)  Again, thanks!

**Comment by dlemstra** [comment]
Feel free to reply here if you have any more questions. Will close it for now.
