### ISSUE TITLE
Huge temporary image magick files are generated on disk

### ISSUE THREAD

**Issue by mgurjarimagemagick** [dlemstra/Magick.NET#267]
Hello,

Current IM version: Magick.NET-7.4.6.0-Q8-AnyCPU
OS on Production: Windows Server 2012 R2
.Net class used: ImageMagick.MagicImage

We have used .Net class in web application hosted on IIS 8.5.
-----------------------.Net code used for IM-----------
   using ImageMagick;

            try
            {
                using (MagickImage image = new MagickImage(filePath))
                {
                    // Valid file
                }
            }
            catch (Exception ex)
            {
                    //log message
             }

To fetch image from file share and convert into PNG format before displaying,

                           using ImageMagick;
                            try
                            {
                                MagickReadSettings settings = new MagickReadSettings();
                                settings.Density = new Density(300, 300);
                                //we need to convert when a processed image is requested.
                                using (MagickImage image = new MagickImage(imageFilePath, settings))
                                {
                                    image.Format = MagickFormat.Png;
                                    image.Write(Response.OutputStream);
                                    Response.ContentType = "image/png";
                                }
                            }
                           catch (Exception ex)
                            {
                                     //log message
                            }
--------------------------------------------------------------------------
We have upgraded version of ImageMagick from "7.0.3.1-Q8-AnyCPU" to "7.4.6.0-AnyCPU" for .Net, but is it still generating huge temporary files on disk on production and causing image functionality stopped. We are using this component to covert images of multiple formats into PNG format.

We have found following errors from log.

-> not a jpeg file: starts with 0x00 0x05 `<jpg file path>’ @ error/jpeg.c/jpegerrorhandler/332

-> insufficient image data in file `<jpg file path>’ @ error/jpeg.c/readjpegimage/1106

-> improper image header `<png file path>' @ error/png.c/readpngimage/4255

-> not a jpeg file: starts with 0x3c 0x21 `<jpg file path>' @ error/jpeg.c/jpegerrorhandler/332

-> no decode delegate for this image format `MSG' @ error/constitute.c/ReadImage/512

-> Failed to read custom directory at offset 366668. `TIFFReadCustomDirectory' @ error/tiff.c/TIFFErrors/652

Some forums suggested delegate libraries need to be installed or any patch. Please let us know what are delegate libraries or patch need to be installed in our case or any other possible solution. also, if huge temporary files are created because of these errors?

Delegate libraries:https://www.imagemagick.org/download/delegates/
Patches:https://www.imagemagick.org/download/beta/

Thanks & Regards,
Manish

**Comment by dlemstra** [comment]
Have you inspected the content of the temporary files that are created? This will probably tell you more than the exceptions that are being raised.
