### ISSUE TITLE
Getting page count for pdfs

### ISSUE THREAD

**Issue by madjufra** [dlemstra/Magick.NET#268]
Hi,

First of all, thanks for creating and maintaining this awesome framework!

I'm working on a project where we are using this framework to work with images and pdfs. The pdf operations in it self seems pretty easy, following your documentation:

https://github.com/dlemstra/Magick.NET/blob/master/Documentation/ConvertPDF.md

The problem or question I have to this, is that for pdfs with alot of pages in it, this operation takes forever.

So if I use the following code:
```
MagickReadSettings settings = new MagickReadSettings();
settings.Density = new Density(300);
using (MagickImageCollection i = new MagickImageCollection())
{
    i.Read(file, settings);
}
```
The read operation takes forever. 60 pages takes around 50 seconds.

What I am really interested in is actually just the page count and not so much all the extra information that I get for each page in the pdf. 

If I run a similar query on the Imagemagick exe:

magick.exe indentify -verbose -ping file.pdf

then it takes only 5-6 seconds, which is a significant difference.

Is there a way or a trick with which I can speed this up? 

Thanks in advance!

/Magnus

**Comment by madjufra** [comment]
Just following up, since I investigated further.

This can be speeded up by doing the following

````
using (MagickImageCollection images = new MagickImageCollection())
{
     images.Ping(file);
}
````
However, with the before mentioned file, this still takes 11.5 seconds.

So if there are any tricks for getting the page count quicker, I am all ears.

**Comment by madjufra** [comment]
As I now, I just went with the MagickImageCollection. 

If that could somehow be optimized, that would be awesome!

That does give me the result, however, each page info seems to always be the same. I do not know if this is the case for all pdfs though.

alternatively, using this small code is also really fast.

````
public int getNumberOfPdfPages(string fileName)
{
    using (StreamReader sr = new StreamReader(File.OpenRead(fileName)))
    {
        Regex regex = new Regex(@"/Type\s*/Page[^s]");
        MatchCollection matches = regex.Matches(sr.ReadToEnd());

        return matches.Count;
    }
}
````

**Comment by IanSC** [comment]
I used iTextSharp to get the number of pages.
```
var its = new iTextSharp.text.pdf.PdfReader( pdfFile );
var numberOfPages = its.NumberOfPages;
```

**Comment by huzhiguan** [comment]
> As I now, I just went with the MagickImageCollection.
> 
> If that could somehow be optimized, that would be awesome!
> 
> That does give me the result, however, each page info seems to always be the same. I do not know if this is the case for all pdfs though.
> 
> alternatively, using this small code is also really fast.
> 
> ```
> public int getNumberOfPdfPages(string fileName)
> {
>     using (StreamReader sr = new StreamReader(File.OpenRead(fileName)))
>     {
>         Regex regex = new Regex(@"/Type\s*/Page[^s]");
>         MatchCollection matches = regex.Matches(sr.ReadToEnd());
> 
>         return matches.Count;
>     }
> }
> ```

Just FYI, the regex doesn't always work. We need to be careful of using it.

**Comment by asadsahi** [comment]
@dlemstra have to say, this is library is amazing for .net devs. However for large pdf files, I am having the same issue which takes a very very long time, especially with 300dpi settings, it kind of never proceed after calling images.Read. If there is a possible way of incrementally loading the pdf or an optimised way of loading large pdf files, it would really make this library usable for plenty of production scenarios.

I highly appreciate any sort of help or pointers to improve the process.

**Comment by martinkoch-geniebelt** [comment]
@asadsahi I had this problem as well (which brought me here :) ). It is possible to load a particular page from a PDF instead of reading the whole thing. I've found that I need to force a garbage collection to keep memory consumption down when processing many pages. This processes a PDF page-by-page:

```csharp
static void Test(string filename)
{
    var magickReadSettings = new MagickReadSettings();
    int page = 0;
    while (true)
    {
        magickReadSettings.FrameIndex = page;
        using (var mic = new MagickImageCollection())
        {
            using (var f = File.Open(filename, FileMode.Open))
            {
                mic.Read(f, magickReadSettings);
                if (0 == mic.Count)
                    break;
            }
            foreach(var img in mic) // There should be only one
            {
                // do stuff
            }
        }
        System.GC.Collect(); // keeps memory consumption low(er)
        page++;
    }
}
```

**Comment by tomasr78** [comment]
> You could execute a ghostscript command yourself like this:
> 
> ```
> "c:\Program Files\gs\gs9.23\bin\gswin64c.exe" -q -dNODISPLAY -c "(YOURFILENAME.pdf) (r) file runpdfbegin pdfpagecount = quit"
> ```
> 
> This gets the results in less then a second.
> 
> But I am wonder if we could not improve ImageMagick to do something like this also. I might have time to take a look at that this weekend.

I would like to know the status of a pdf page count? Would be really cool to have the option to know page count in a quick way from MagicImage directly.

**Comment by dlemstra** [comment]
In the next version of Magick.NET you will be able to do this:

```C#
using ImageMagick.Formats.Pdf;

var pdfInfo = PdfInfo.Create(@"C:\YourFile.pdf");
for (var i = 0; i < pdfInfo.PageCount; i++)
{
}
```

**Comment by tomasr78** [comment]
Great! Do you have ETA for the new version?

**Comment by dlemstra** [comment]
I don't have an ETA for releases. Most of the time there is a month between releases and the previous release was last week. So you probably need to wait a while before this becomes available.

**Comment by dlemstra** [comment]
The new release has been published.

**Comment by tomasr78** [comment]
It works fine for unprotected PDF but how about a protected PDF? I do not find a way to pass a password for `PdfInfo.Create` method.

**Comment by dlemstra** [comment]
Could you open a new issue to request support for that? And feel free to include an suggestion of how the API should look like.
