### ISSUE TITLE
Add option to ImageOptimizer to disable throwing exception for unsupported formats.

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/Magick.NET#269]
An option to disable throwing exceptions when a format is unsupported should be added. With this option enabled unsupported files will just be skipped instead. Feel free to suggest a name for the property in this issue.

**Comment by zachesposito** [comment]
Hello how about `IgnoreUnsupportedFormats`, which if set to true makes the two GetOptimizer methods return `null` instead of throwing if a supported optimizer can't be found?

**Comment by dlemstra** [comment]
Sounds like a good plan. Could you make sure that you also add some unit tests?

**Comment by zachesposito** [comment]
Yes PR has been added with supporting unit tests
