### ISSUE TITLE
Can't make it run in multithreading mode.

### ISSUE THREAD

**Issue by kfomichev** [dlemstra/Magick.NET#270]
I try to process several images in multithreading mode. I use Vb.net (VS 2017), Magick.NET 7.5.0.0 Q16 AnyCPU
Actually I use SubImage Search. I have a single big image and an array of several subimages. My code has to find similarity metric for each subimage.
The sample code is below,
```
Public FullImage As MagickImage
Public SubImage(4) As MagickImage
Public Result(4) As Double

Sub Main(args As String())
	Dim Tasks As New List(Of Task)

        FullImage = New MagickImage("Full1.png")
        For i As Integer = 1 To 4
            SubImage(i) = New MagickImage("Sub1.png")
        Next

        Console.WriteLine("== single task")
        DoWork(1)

        Console.WriteLine("== try task list")
        For i As Integer = 1 To 4
            Dim t As Task = Task.Factory.StartNew(Sub(n) DoWork(n), i)
            Tasks.Add(t)
        Next
        Task.WaitAll(Tasks.ToArray)

        Console.WriteLine("== try parallel.for")
        Parallel.For(1, 4 + 1, Sub(n) DoWork(n))

        Console.WriteLine("== end")

 Public Sub DoWork(num As Integer)
        Dim s As New Stopwatch
        Console.WriteLine("Worker {0} started", num)
        s.Restart()
        Result(num) = FullImage.SubImageSearch(SubImage(num)).SimilarityMetric
        Console.WriteLine("Worker {0} stopped, elapsed milliseconds {1}", num, s.ElapsedMilliseconds)
    End Sub

```
The output is following:
```
== single task
Worker 1 started
Worker 1 stopped, elapsed milliseconds 3331
== try task list
Worker 4 started
Worker 1 started
Worker 3 started
Worker 2 started
Worker 3 stopped, elapsed milliseconds 10618
Worker 4 stopped, elapsed milliseconds 10656
Worker 2 stopped, elapsed milliseconds 10681
Worker 1 stopped, elapsed milliseconds 10931
== try parallel.for
Worker 1 started
Worker 3 started
Worker 4 started
Worker 2 started
Worker 4 stopped, elapsed milliseconds 10711
Worker 3 stopped, elapsed milliseconds 10732
Worker 2 stopped, elapsed milliseconds 11105
Worker 1 stopped, elapsed milliseconds 11110
== end
```

It shows that there is little to no performance gain. The CPU load doesn't show differense between 1 task and 4 tasks.
Is there an explanation for this or a solution?
Regards,
Kyrill.

**Comment by dlemstra** [comment]
Would it be possible to add a link to your images on something like dropbox or onedrive?

**Comment by kfomichev** [comment]
I suggest better to change images to just gray fills. The result is the same.
        ```
        Dim col As New MagickColor(Drawing.Color.Gray)
        FullImage = New MagickImage(col, 235, 290)
        For i As Integer = 1 To 4
            SubImage(i) = New MagickImage(col, 37, 38)
        Next
```

**Comment by kfomichev** [comment]
To isolate it to ImageMagick, I tried different workload:
```
Public Sub DoWork(num As Integer)
        Dim s As New Stopwatch
        Console.WriteLine("Worker {0} started", num)
        s.Restart()
        Dim r As Long
        For i As Integer = 1 To 200000000
            r += Math.Sqrt(i)
        Next
        Console.WriteLine("Worker {0} stopped, elapsed milliseconds {1}", num, s.ElapsedMilliseconds)
    End Sub
```
It works ok in multitasking mode, as expected (CPU load, scalability).

**Comment by dlemstra** [comment]
If you are running this on your own machine instead of a multi-threaded web application you might want to give the OpenMP version a try.

**Comment by kfomichev** [comment]
Thanks for the tip.
Yes, I run on the app on desktop.
I have tried Q8-OpenMP version.
```
== single task
Worker 1 started
Worker 1 stopped, elapsed milliseconds 1394
== try task list
Worker 2 started
Worker 1 started
Worker 4 started
Worker 3 started
Worker 4 stopped, elapsed milliseconds 2781
Worker 2 stopped, elapsed milliseconds 2897
Worker 1 stopped, elapsed milliseconds 3048
Worker 3 stopped, elapsed milliseconds 3063
== try parallel.for
Worker 1 started
Worker 2 started
Worker 3 started
Worker 4 started
Worker 1 stopped, elapsed milliseconds 2979
Worker 4 stopped, elapsed milliseconds 3008
Worker 3 stopped, elapsed milliseconds 3036
Worker 2 stopped, elapsed milliseconds 3038
== try task list with 6 tasks
Worker 2 started
Worker 5 started
Worker 6 started
Worker 3 started
Worker 4 started
Worker 1 started
Worker 6 stopped, elapsed milliseconds 4290
Worker 1 stopped, elapsed milliseconds 4486
Worker 3 stopped, elapsed milliseconds 4534
Worker 2 stopped, elapsed milliseconds 4557
Worker 5 stopped, elapsed milliseconds 4583
Worker 4 stopped, elapsed milliseconds 4678
== try task list with 8 tasks
Worker 5 started
Worker 7 started
Worker 3 started
Worker 2 started
Worker 6 started
Worker 4 started
Worker 8 started
Worker 1 started
Worker 8 stopped, elapsed milliseconds 5857
Worker 6 stopped, elapsed milliseconds 5908
Worker 4 stopped, elapsed milliseconds 5933
Worker 3 stopped, elapsed milliseconds 5946
Worker 2 stopped, elapsed milliseconds 5956
Worker 5 stopped, elapsed milliseconds 5954
Worker 7 stopped, elapsed milliseconds 6115
Worker 1 stopped, elapsed milliseconds 6130
== end
```
This version runs twice as fast, as non-OpenMP version in single task mode. So I think all multithreading magic is already inside (like it is in binary ImageMagick package). CPU load also reaches near 100%
The scalability is positive, 8 tasks run only 4 times longer, than single task. (On my 4-core+HT i7 CPU)
I think I could stick with this.
The only problem is that there is no 32-bit version with OpenMP, only 64-bit.
And I'd like to run my app on any CPU.
Do you have any further ideas?

**Comment by dlemstra** [comment]
Why do you need to run in on AnyCPU? For OpenMP there will only by an x64 build. This build is only available on Windows at the moment and requires you to install the C++ redistributable. I will at some point when I completely moved the build to Azure DevOps also create an OpenMP version for Linux and Mac. But that will only be x64.

**Comment by kfomichev** [comment]
Yes, AnyCPU would be better. 
Actualy I still can't understand, why non-OpenMP version can't benefit from running multiple tasks in parallel.
Anyway thank you for your great efforts.

**Comment by dlemstra** [comment]
The OpenMP version will use multiple cores at the pixel modification layer. I suspect that a better optimization can be achieved at that level instead of the .NET layer. I have tried to see if .NET would decide to run it in a single thread when the native code is PInvoked but I could not find any proof of that. I am sorry but I don't have a better answer for you.

**Comment by kfomichev** [comment]
Ok, thanks a lot.
