### ISSUE TITLE
Attached BMP doesn't display correctly

### ISSUE THREAD

**Issue by fire-eggs** [dlemstra/Magick.NET#271]
We use Magick.NET in our project, [ImageGlass](imageglass.org). A user has submitted an issue complaining that some BMP files do not display correctly. When loaded by Paint/Photos/WIC the image shows correctly.

The following is a sample image (rename by dropping the .log extension) which shows the problem:
[33A3F6D37FE162E4.bmp.log](https://github.com/dlemstra/Magick.NET/files/2257710/33A3F6D37FE162E4.bmp.log)

This is how it displays in ImageGlass:

[issue 386.PNG.log](https://github.com/dlemstra/Magick.NET/files/2257746/issue.386.PNG.log)

The code we use to load is essentially:
```
                var settings = new MagickReadSettings();
                using (var magicImg = new MagickImage(path, settings))
                {
                    magicImg.Quality = 100;
                    var profile = magicImg.GetExifProfile();
                    magicImg.AddProfile(ColorProfile.SRGB);
                    bmp = magicImg.ToBitmap();
                }
```

1. Is there something problematic about this image, yet ImageMagick appears not to fail?
1. Is there a 'tweak' we should make that fixes this scenario, yet doesn't break all other images?

Any advice appreciated.
Thank you, and our thanks for an excellent project!
Kevin

**Comment by dlemstra** [comment]
This image is a 32 bit BMP3 image. This means that 4 channels can be stored per pixel. When the 4th channel are not all zero ImageMagick will treat the 4th channel as an alpha channel. It might be possible to add an option to disable this behavior but that would mean you would lose alpha channel support for 32 bit BMP3 images.

**Comment by fire-eggs** [comment]
Ah, informative!

So I interpret this as a limitation of Paint/Photos, that they don't support the Alpha channel for BMP3. OR, the app creating the images is the problem, using BMP3 format without properly setting the Alpha channel.

I'll dig into the mechanics to disable Alpha channel for BMP3, for my own understanding. My inclination is to treat the original report as "functions as designed".

Dank je!
