### ISSUE TITLE
.Net Code for Cut Off Corners?

### ISSUE THREAD

**Issue by GlennIM** [dlemstra/Magick.NET#272]
Hi Dirk,

I'm trying to implement this example with "cut off" corners in C# but not doing so good. Would you have a look and see what code I could use to make this work in C#?

convert thumbnail.gif -alpha set -compose DstOut \
\( -size 20x15 xc:none -draw "polygon 0,0 0,14 19,0" \
-write mpr:triangle +delete \) \
\( mpr:triangle \) -gravity northwest -composite \
\( mpr:triangle -flip \) -gravity southwest -composite \
\( mpr:triangle -flop \) -gravity northeast -composite \
\( mpr:triangle -rotate 180 \) -gravity southeast -composite \
corner_cutoff.png

References:
https://www.imagemagick.org/Usage/thumb ... cutoff.png - https://www.imagemagick.org/Usage/thumbnails

Thanks, Glenn

**Comment by dlemstra** [comment]
Closing this because I already answered a couple of questions on how to translate your commands. I am planning to create a new project where I will answer these kind of questions and add the examples to the repository. Don't know when I will have/make time for that.
