### ISSUE TITLE
A couple of questions.

### ISSUE THREAD

**Issue by Tylertron1998** [dlemstra/Magick.NET#274]
1 - Is it possible to achieve a [point focus blur effect](http://www.adobepress.com/content/images/art_moughamian_fp/elementLinks/moughamian_fig02.jpg) with ImageMagick/Magick.NET? If there isn't a built in method - is there any ""hacky"" way to achieve this?

2 - What can I do to optimize image editing/creation - in general. I am currently writing a HTTP API for this in ASP.NET core, so anyone in any library can send an array of "commands" and get back an image. Wondering if you guys have any tips on making the process faster/more efficient.

3 - Is Magick.NET multithreaded?

I LOVE this package. I've been looking for a good replacement of System.Drawing - because of the fact I am using ASP.NET. Any help here would be very much appreciated 👍

**Comment by dlemstra** [comment]
1. There is no built in method for this and there are probably various ways to do this but the first thing that comes to mind is a using a mask. Below is a simple example of how you could do that. You could ask for more help in the ImageMagick forum.

```C#
using (var image = new MagickImage("logo:"))
{
    using (var mask = new MagickImage(MagickColors.Black, image.Width, image.Height))
    {
        var centerWidth = image.Width / 2;
        var centerHeight = image.Height / 2;

        // Circle in the center of the image.
        new Drawables()
            .FillColor(MagickColors.White)
            .Circle(centerWidth, centerHeight, centerWidth + 100, centerHeight+ 100)
            .Draw(mask);

        image.SetWriteMask(mask);

        image.Blur(0, 5); // You can tweak the blur here.

        image.Write("test.png");
    }
}
```

2. I have no idea what you are trying to ask. You might want to consider using the MagickScript api to script the actions with an xml (json for old people) syntax to modify an image. You can find some examples in the unit tests of this project.

3. Yes and no. The library can be used in a multithreaded environment but the operations on an image are not multithreaded. There is an OpenMP version of the library that does this but I would not advise you to use that in web environment. That version would be more suited for a desktop environment.

**Comment by Tylertron1998** [comment]
- Okay, so.

1 - from what I understand, what you made would be a distinct "line" between the circle (mask/focal point) and the rest of the image- I was more looking for a gradual blur. However, I could also be completely wrong with my understanding here. Is that correct? If so - how could I have a more gradual blur between focus point and the rest of the image?

2 - My apologies - I probably should have been more clear. In general, using this library, are there any "options" so to speak to make this more performance friendly - not that it isn't, but as specified I'm writing a HTTP API for anyone to use, and it would be nice to give them an option - if it exists.

3 - Ah, this wouldn't be a "web" api so to speak. The idea of this was to have a local http server you could access (via localhost) to generate and return images - essentially so any programming language could take advantage of this, via a POST request with "Commands", the server executes said commands, and returns an image. So would using the OpenMP version still be good for this?

Thanks for the quick reply!

**Comment by dlemstra** [comment]
1. You might want to ask that question here: https://www.imagemagick.org/discourse-server/viewforum.php?f=1 to get a better answer. I can then help you convert the command line here in this topic.

2. You could improve the performance and the memory that is used by picking a Q8 version instead of a Q16 version of Magick.NET. But that also means you will get a lower quality image. You probably need two versions of your API running to support both Q8 and Q16 at the same time. You cannot use both in the same project.

3. That is indeed a situation where you could use the OpenMP version instead of the normal version. Only downside is that you will need to have the VS2017 C++ redistributable installed.

**Comment by Tylertron1998** [comment]
Again -thank you for your replies. I have a few more questions - if that's quite alright?

Firstly, what is the difference between these two code snippets:

```csharp
using(var image = new MagickImage(MagickColors.Black, 100, 100)
{
    var circle = new DrawableCircle(10, 10, 20, 20);
    circle.Draw(image);
}
``` and
```csharp
using(var image = new MagickImage(MagickColors.Black, 100, 100)
{
    new Drawables()
        .addCircle(10, 10, 20, 20)
        .Draw(image);
}
``` ? The DrawableCircle class doesn't seem to do anything - not sure if I am doing anything wrong here.

Secondly, because of the fact that the MagickImage class implements IDisposable (and therefore, requires disposing) I am currently writing the bytes to a new byte[] - and then disposing it, returning the byte array. Is this a good way of doing it? If not, is there a better way?

Lastly - from what I understand, you may use any font installed on Windows (i.e. in the Fonts folder) how about other OS's - Linux based distros and MacOS, mainly?

**Comment by dlemstra** [comment]
I am assuming that your first snippet does `image.Draw(circle)` instead. There is no difference between the snippets. The second one just allows you to use a fluent interface to stack multiple draw actions.

You don't see anything happening because you are drawing a black circle on top of a black image. The default fill color for a circle is black and that is why I set that to white in my example.

I don't understand what you are doing with the `byte[]`. But you can reuse it with the same image. The ImageMagick just reads it to decode the image and it will allocate it's own memory for the image.

Fonts on Linux and MacOS should be registered with font-config because that is being used for the Linux/MacOS builds.

**Comment by Tylertron1998** [comment]
Ah, that explains a lot haha. Thank you!

The idea of the byte[] is that I grab the bytes of the image, dispose of it, and return the bytes.

font-config - just to double check, that's an OS thing, right?

Wonderful - I think that's about everything, for now. Thank you so much again for taking your time here to help!

**Comment by Tylertron1998** [comment]
Also, I'll put this here as to not open a new issue. Was playing about with opening images from a directory, and using them, but I kept getting back (via my api) a black image. So I tried using .save and got this error:
```cs
ImageMagick.MagickCoderErrorException: WriteBlob Failed `C:\Users\sirbr\Documents\Coding\Projects\C#\Canvas.NET\Canvas' @ error/png.c/MagickPNGErrorHandler/1711
```
What does this mean?

**Comment by dlemstra** [comment]
There is some documentation about how you can read images here: https://github.com/dlemstra/Magick.NET/blob/master/Documentation/ReadingImages.md. If that doesn't give you enough information it might be better to open a new issue instead and include a small code sample that I can use to reproduce your issue.
