### ISSUE TITLE
Seperate Masking Image in C# with ImageMagick.Net

### ISSUE THREAD

**Issue by newETA** [dlemstra/Magick.NET#275]
Hello there,

I am new to ImageMagick and I tried to play here and there found several interesting things I work for something but I stop at a point please help me to figure it out. 

I need extract the only masking portion from the transparent image basically this one is going to use in one pdf having with spot color+White Over Print.  For details please find https://github.com/dlemstra/Magick.NET/files/2268703/PDF.Example.pdf which contain all the stuff I am looking to solve using ImageMagick. 

So far I was able to make Grayscale but wasn't able to extract that mask portion from the https://user-images.githubusercontent.com/42071761/43812622-bc9c6878-9a87-11e8-971c-2d590342ae47.png image and output I am looking something like. 
https://user-images.githubusercontent.com/42071761/43812690-0a762c6e-9a88-11e8-8cf3-a25ecb130109.PNG

FYI I really don't know how to use IM I am using Magick C# Library. 

Need convert from
![46c5e01e3adbffe11eca9d3b04b3c767](https://user-images.githubusercontent.com/42071761/43812622-bc9c6878-9a87-11e8-971c-2d590342ae47.png)

Like to :
![mask](https://user-images.githubusercontent.com/42071761/43812690-0a762c6e-9a88-11e8-8cf3-a25ecb130109.PNG)

[PDF Example.pdf](https://github.com/dlemstra/Magick.NET/files/2268703/PDF.Example.pdf)

**Comment by newETA** [comment]
Fantastic, Magick.net is awesome. 
Thank you so much for helping me out.

Another one question how to know if the image is transparent or not?

**Comment by dlemstra** [comment]
You can check if has a transparent channel with the `HasAlpha` property of the `MagickImage` class.

**Comment by newETA** [comment]
Nice.

**Comment by Swathi-Reddy-amla** [comment]
> You could use the following trick (not sure if it works for all your images):
> 
> ```cs
> using (var image = new MagickImage("43812622-bc9c6878-9a87-11e8-971c-2d590342ae47.png"))
> {
>     // Fill the image with a transparent background
>     image.FloodFill(MagickColors.None, 0, 0);
> 
>     // Change all the pixels that are not transparent to yellow.
>     image.InverseOpaque(MagickColors.None, MagickColors.Yellow);
> 
>     // Change the transparent pixels to white.
>     image.ColorAlpha(MagickColors.White);
> 
>     image.Write("test.png");
> }
> ```

Thank you
