### ISSUE TITLE
Magick.NET error asp.net

### ISSUE THREAD

**Issue by rizwanali98601** [dlemstra/Magick.NET#277]
using (MagickImageCollection images = new MagickImageCollection())
        {
            // Add all the pages of the pdf file to the collection
            images.Read(pdffilePath, settings);
        }

Error : 
PDFDelegateFailed `The system cannot find the file specified.\r\n' @ error/pdf.c/ReadPDFImage/796

**Comment by dlemstra** [comment]
You probably did not install Ghostscript as described in the documentation.
