### ISSUE TITLE
Hi, how can i read each channel as byte[] in Magick.net ?

### ISSUE THREAD

**Issue by saeed213** [dlemstra/Magick.NET#285]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

**Comment by dlemstra** [comment]
Next time it might be better to include some more information in the question instead of only putting that in the title.

Do you want to convert a channel of an image to a byte array or do you want to create an image from a couple byte arrays that contain the data of the channel?

**Comment by saeed213** [comment]
> Next time it might be better to include some more information in the question instead of only putting that in the title.

It was first time that i leave a message in Github and i didn't knew how.

I want to convert each channel of an CMYK image to a byte array and then get an average.

**Comment by dlemstra** [comment]
@saeed213 No worries it's just some advice for when you ask another question on GitHub in the future.

You could do this:

```C#
using (var image = new MagickImage("YourFile.jpg"))
{
    using (var pixels = image.GetPixelsUnsafe())
    {
        var cyan = pixels.ToByteArray("C");
        var magenta = pixels.ToByteArray("M");
        var yellow = pixels.ToByteArray("Y");
        var key = pixels.ToByteArray("K");
    }
}
```

**Comment by saeed213** [comment]
@dlemstra  Thanks
