### ISSUE TITLE
Why resizing animated GIF ends up with larger file size?

### ISSUE THREAD

**Issue by FanrayMedia** [dlemstra/Magick.NET#287]
I'm resizing down the dimension of an animated GIF, but the smaller dimension file ends up with larger file size.  I also tried resizing to same dimension, the file size is also larger.

Original file: 500 x 225, 443KB
Resize to smaller dimension: 400 x 180, 488KB
Resize to same dimension: 500 x 225, 494KB

Here is my code

```c#
    using (var imageColl = new MagickImageCollection(source))
    {
	  widthOrig = imageColl[0].Width;
	  heightOrig = imageColl[0].Height;
	  imageColl.Coalesce();
          imageColl.Optimize();
          imageColl.OptimizeTransparency();

	  foreach (MagickImage image in imageColl)
	  {
		var (width, height) = GetNewSize(widthOrig, heightOrig, 400);

		image.Resize(width, height);
	  }

	  // saving file omitted
    }
```
Could someone point out what I'm missing to get smaller file size after resizing?  Thank you.

**Comment by dlemstra** [comment]
You should `Optimize` the images after you have resized them. Doing that before the resize has no effect.

**Comment by FanrayMedia** [comment]
@dlemstra Thank you for your input.  I tried to put `imageColl.Optimize()` statement after the foreach image.Resize, the file size is still large, I'm still missing something?

```c#
    using (var imageColl = new MagickImageCollection(source))
    {
	  widthOrig = imageColl[0].Width;
	  heightOrig = imageColl[0].Height;
	  imageColl.Coalesce();

	  foreach (MagickImage image in imageColl)
	  {
		var (width, height) = GetNewSize(widthOrig, heightOrig, 400);
		image.Resize(width, height);
	  }

          imageColl.Optimize();

	  // saving file omitted
    }
```

**Comment by dlemstra** [comment]
Can you share your input image? That might explain why it is bigger.

**Comment by FanrayMedia** [comment]
This is the gif I used to test.

![leo](https://user-images.githubusercontent.com/633119/44635340-33bce100-a959-11e8-98cf-d7022b1d495c.gif)

**Comment by dlemstra** [comment]
When the image gets resized the number of colors in the image becomes higher. When you quantize each individual frame you can reduce the number of colors. The following code sample demonstrates this:

```C#
using (var images = new MagickImageCollection("i:/gif/leo.gif"))
{
    foreach (var image in images)
    {
        var colors = image.TotalColors;
        Console.WriteLine(image.TotalColors);

        image.Resize(400, 0);
        Console.WriteLine(image.TotalColors);

        image.Quantize(new QuantizeSettings
        {
            Colors = colors,
            DitherMethod = DitherMethod.No
        });
        Console.WriteLine(image.TotalColors);

        Console.WriteLine();
    }

    images.Optimize();

    images.Write(@"i:/test.gif");
}
```

With the latest Q8 version I get the following output:

```
57
255
36

57
254
35

54
254
33

57
255
35

57
256
34

57
256
33

57
256
33

57
256
35

57
252
34

57
251
34

57
253
34

56
254
34
```

And the following output image (266KB):

![test](https://user-images.githubusercontent.com/10426229/44743696-80442000-ab03-11e8-8ca9-887302af74fb.gif)

**Comment by FanrayMedia** [comment]
@dlemstra Thank you for the sample code, very helpful.  Though I notice when I resize the file to the same dimension as the input file, the output file size is not decreased but becomes slightly larger. 

In this case the input file is 500 x 225, 443k; when I resized it to same 500 x 225 I was hoping to reduce the file size somewhat but the output file was 451k.

This happens on both **.gif** and **.png** files when I resize but keep same dimension, .jpg files are much better in reducing file size.  Do you know why this is the case?

**Comment by dlemstra** [comment]
Can you explain why you are "resizing" the image to the same dimensions? If you want to reduce the size of an existing image you might want to take a look at `ImageOptimizer` instead.

**Comment by FanrayMedia** [comment]
@dlemstra Yeah to reduce file size is my intention, I just tried it like below but it didn't reduce file size.  Would you have a code sample for ImageOptimizer?  Thanks!

```c#
       using (var memStream = new MemoryStream())
       {
                ImageOptimizer opt = new ImageOptimizer();
                image.Write(memStream);
                memStream.Position = 0;
                opt.Compress(memStream);

                // .. save stream to file
        }
```

**Comment by dlemstra** [comment]
It just tried to reduce the file. That does not mean it will happen.

**Comment by FanrayMedia** [comment]
@dlemstra I see.  One more question on gif, when I used the same leo.gif and resize to 500 x 225, the output image went totally dark.  Would you know what is wrong?

**Comment by NarekMayilyan** [comment]
@dlemstra ,Hi,i do as you say with image.Quantize, but my file size is still larger than the original
This is my test gif, can you help me?
`

            using (MemoryStream stream = new MemoryStream())
            {
                await origImage.CopyToAsync(stream);
                using (var collection = new MagickImageCollection(stream.ToArray()))
                {
                    collection.Coalesce();
                    foreach (var image in collection)
                    {
                        var colors = image.TotalColors;
                        image.Resize(400, 0);
                        image.Quantize(new QuantizeSettings
                        {
                            Colors = colors,
                            DitherMethod = DitherMethod.FloydSteinberg
                        });
                    }
                    collection.Optimize();
                    collection.Combine();
                    return collection.ToByteArray();
                }
            }
`
 #
![giphy](https://user-images.githubusercontent.com/43807419/49077044-d6844480-f253-11e8-8ee2-b71ee2fbc50d.gif)

**Comment by dlemstra** [comment]
@NarekMayilyan You don't need to do `collection.Combine();`? And it is still possible that you get a larger image.

**Comment by NarekMayilyan** [comment]
@dlemstra , without collection.Combine() I still have the same problem

**Comment by NarekMayilyan** [comment]
@dlemstra , after updating to the latest version, can my problem be solved?

**Comment by dlemstra** [comment]
@NarekMayilyan It appears that for your image it is better to not do the quantization and call `collection.OptimizeTransparency()` instead of `collection.Optimize()`.

**Comment by NarekMayilyan** [comment]
the size of the smaller version (1,41 MB) is still larger than the original (765 KB)
How to understand what operations should be used so that when gif is reduced, be sure that the size also decreases
