### ISSUE TITLE
Missing Magick.NET-Q16-x64.Native.dll

### ISSUE THREAD

**Issue by ANavakahtsky** [dlemstra/Magick.NET#291]
Hi there!

I'm trying to use your lib in .Net Core 2.0 project. I'm using Nuget for installing Magick.NET-Q16-AnyCPU 7.6.0. Unfortunately, my code fails on creating new MagickImage instance

`MagickImage image = new MagickImage(ms);`

with 'Missing Magick.NET-Q16-x64.Native.dll' error. This issue is similar to [235](https://github.com/dlemstra/Magick.NET/issues/235) and [25](https://github.com/dlemstra/Magick.NET/issues/25), but not identical. After the nuget package installation only  Magick.NET-Q16-AnyCPU.dll is appeared in referencing project directory and output directory. However, downloaded and unzipped 'magick.net-q16-anycpu.7.6.0.nupkg' contains Magick.NET-Q16-x64.Native.dll in 'runtimes' folder.

My question is - what am I missing and where could I find this native dll? Thanks.

**Comment by dlemstra** [comment]
If you delete the issue template and don't tell me where you are running this and what the exact error is that you are receiving I am not sure If I can really help you.

**Comment by ANavakahtsky** [comment]
Solved. Magick.NET-Q16-x64.Native.dll was found in obj folder (not copied to bin when project is built). 

Also if you use visual studio OneClick Publish tool, be sure that you set correct RuntimeIdentifier in settings. In my case default list of options contained only 'win-x64', but magick.net awaits for one of the following: linux-x64, osx-64, win7-x64, win7-x86. You could find it in deps.json for referencing project.

`"Magick.NET-Q16-AnyCPU/7.5.0": {
        "runtime": {
          "lib/netstandard20/Magick.NET-Q16-AnyCPU.dll": {}
        },
        "runtimeTargets": {
          "runtimes/linux-x64/native/Magick.NET-Q16-x64.Native.dll.so": {
            "rid": "linux-x64",
            "assetType": "native"
          },
          "runtimes/osx-x64/native/Magick.NET-Q16-x64.Native.dll.dylib": {
            "rid": "osx-x64",
            "assetType": "native"
          },
          "runtimes/win7-x64/native/Magick.NET-Q16-x64.Native.dll": {
            "rid": "win7-x64",
            "assetType": "native"
          },
          "runtimes/win7-x86/native/Magick.NET-Q16-x86.Native.dll": {
            "rid": "win7-x86",
            "assetType": "native"
          }
        }
      }`

So, you need to add appropriate value manually to your PublishProfile.pubxml. After doing that, you could see Magick.NET-Q16-x64.Native.dll in publish directory. Hope this will help someone.

**Comment by JedatKinports** [comment]
You are a life saver @ANavakahtsky thanks!

All I had to do was add the:

 <PropertyGroup>
    <RuntimeIdentifiers>win7-x64</RuntimeIdentifiers>
  </PropertyGroup>

into my csproj file, change the runtimeidentifier in the publishing profile and now it works.

Don't know why the "win-x64" is not supported. Will this get added in the coming versions maybe? Any plans on this?

**Comment by dlemstra** [comment]
The new version of Magick.NET will use `win-x64` and `win-x86` instead.

**Comment by drewlsvern** [comment]
Has this issue actually been fixed? Experiencing the same issue and none of the suggested solutions have solved it. I tried different nuget package versions Q8 and Q16 (x86, x64 and Any CPU) and the issue still exists.

The package works fine locally in development but when deployed to Azure I receive the following error upon application startup:
Error:
  An assembly specified in the application dependencies manifest (Web.deps.json) was not found:
    package: 'Magick.NET-Q8-x86', version: '7.11.0'
    path: 'runtimes/win-x86/native/Magick.NET-Q8-x86.Native.dll'
Error:
  An assembly specified in the application dependencies manifest (Web.deps.json) was not found:
    package: 'Magick.NET-Q8-x86', version: '7.11.0'
    path: 'runtimes/win-x86/native/Magick.NET-Q8-x86.Native.dll'

Current Environment:
-VS 2017
-ASP.NET Core 2.2

**Comment by dlemstra** [comment]
The file is in that folder inside the NuGet package. I have no idea why it cannot be found in Azure. Maybe the native file is not deployed?

**Comment by drewlsvern** [comment]
I guess I forgot to mention. The file and path it's looking for exists, so I don't understand why the error is happening.

**Comment by dlemstra** [comment]
Could you create a public project in azure devops that demonstrates this issue? I will be occupied for the next 25 days so take your time.

**Comment by drewlsvern** [comment]
Yeah ok, I can do that. I'm quite busy myself, so I won't be fast either.

**Comment by drewlsvern** [comment]
Turns out the issue was completely unrelated to your package, even though that's the error that kept coming up. It's related to the section 'Availability in Azure App Service' in [this](https://devblogs.microsoft.com/aspnet/asp-net-core-2-2-available-today/) blog.

**Comment by justdan23** [comment]
Try using the SysInternals Suite app "ProcMon.exe" to watch the hosting process.

When I had this issue and used IIS to host my web app, it failed because of missing CORE_ dependency libraries missing which my Magick.NET-Q16-HDRI-x64.Native.DLL required. 

ImageMagick returns the wrong message that it failed to find the DLL, but really it failed to load a dependency library.  ProcMon.exe shows you which one when running it on the Server hosting IIS or Azure.

**Comment by b10-dslappendel** [comment]
@drewlsvern Did you manage to get it working? And if so, how? I'm currently running into it myself as well when deploying to Azure Functions:

The function runtime is unable to start. Magick.NET-Q16-AnyCPU: Unable to load DLL 'Magick.Native-Q16-x86.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E).

**Comment by b10-dslappendel** [comment]
Never mind, I've solved it myself.
Apparently it cannot find the above mentioned directory in Azure on its own. I had to explicitly use `MagickNET.SetNativeLibraryDirectory` to set it to that directory.
