### ISSUE TITLE
Image compositions: different result from v7.6.0 to v7.6.0.1

### ISSUE THREAD

**Issue by truyb** [dlemstra/Magick.NET#292]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I have a small program that puts a text with a fade out to 'nothing' on a gradient, this worked perfectly in 7.6.0 , but after updating to 7.6.0.1 the result changed completely.

### Steps to Reproduce
Run the following code in 7.6.0 and 7.6.0.1 . The results will be different.
```
static void Main(string[] args)
{
    using (var image = new MagickImage(MagickColors.White, 320, 240))
    {
        image.Density = new Density(300);
        image.Format = MagickFormat.Png;

        using (var gradient = new MagickImage(@"D:\gradient.png", 320, 240))
            image.Composite(gradient, 0, 0, CompositeOperator.Over);

        using (var completeMask = new MagickImage(MagickColors.Transparent, 310, 30))
        {
            var gradientSettings = new MagickReadSettings()
            {
                Width = 60,
                Height = 30
            };

            gradientSettings.SetDefine("gradient:direction", "east");

            using (var filledMask = new MagickImage(MagickColors.White, 160, 30))
            using (var gradientMask = new MagickImage("gradient:white-none", gradientSettings))
            {
                completeMask.Composite(filledMask, 0, 0, CompositeOperator.Over);
                completeMask.Composite(gradientMask, 160, 0, CompositeOperator.Over);
            }

            using (var mText = new MagickImage(MagickColors.White, 310, 30))
            {
                var textSettings = new MagickReadSettings
                {
                    BackgroundColor = MagickColors.Transparent,
                    FillColor = MagickColors.White,
                    Width = 310,
                    Height = 30,
                    TextGravity = Gravity.North
                };

                mText.Read($"caption:Hello World!", textSettings);

                using (var completeTextBox = new MagickImage(MagickColors.Transparent, 310, 30))
                {
                    completeTextBox.Composite(mText, 0, 0, CompositeOperator.Over);
                    completeTextBox.Composite(completeMask, 0, 0, CompositeOperator.Multiply);

                    image.Composite(completeTextBox, 5, 60, CompositeOperator.Over);
                }
            }
        }

        image.Write(@"D:\test.png");
    }
}
```

the gradient.png image I've used is below:
[Gradient](https://i.imgur.com/zcMYCHM.png)

The result I get in 7.6.0 (OK)
[Click here](https://i.imgur.com/CnJLo1m.png)

The result I get in 7.6.0.1 (NOK)
[Click here](https://i.imgur.com/ceuQeek.png)

### System Configuration

- Magick.NET version: 7.6.0, 7.6.0.1 (Q8 AnyCPU)
- Environment (Operating system, version and so on): Windows 7, Visual Studio 2017
- Additional information: /

**Comment by dlemstra** [comment]
Thanks for reporting this bug. This has been fixed inside the ImageMagick library and I will try to publish a new release very soon to resolve your issue.

**Comment by dlemstra** [comment]
I just publish Magick.NET 7.7.0.0 that includes a fix for your issue.
