### ISSUE TITLE
Crop shows strange behavior

### ISSUE THREAD

**Issue by lokatz** [dlemstra/Magick.NET#294]
I'm cropping a (JPEG black&white) MagickImage in C# that I already cropped before.  I verified that the crop command is something like this:

   `image.Crop(214, 190, 553, 554);`

with a verified image size of 910x910px.  However, the resulting cropped image has a size of 1x1px.  Anybody got an idea why, and how to prevent this?

Thanks in advance for your help.

**Comment by dlemstra** [comment]
Have you tried adding `image.RePage()` in between the operations?

**Comment by lokatz** [comment]
I did now, and it solves the issue.  Thanks!
