### ISSUE TITLE
Writing a MagickImageCollection to a .gif file seems to hang (not sure why - it's a very strange edge case, as shown)

### ISSUE THREAD

**Issue by Tylertron1998** [dlemstra/Magick.NET#295]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm not quite sure how to describe the issue - but if you see the following code in reproduction steps - the last method was hanging on the collection.write() method - I was benchmarking, to find out what is a faster method of re-using the same image in a collection, and come across this. The method that hangs up is the SameImage() method.

### Steps to Reproduce

```cs
using BenchmarkDotNet.Attributes;
using ImageMagick;
using System.IO;

namespace MagickTesting
{
	public class BenchMark
	{

		private string testString = "Hello, world!";
		[Benchmark]
		public bool NewInstance()
		{
			using (var collection = new MagickImageCollection())
			{
				for (var i = 1; i < 10; i++)
				{
					var sub = testString.Substring(0, i);
					var image = new MagickImage(File.ReadAllBytes(@"C:\Users\sirbr\Documents\Coding\Projects\C#\MagickTesting\MagickTesting\adi.png"));
					image.Draw(new Drawables()
						.Text(128, 128, sub)
					);
					collection.Add(image);
					collection[i - 1].AnimationDelay = 10;
				}
				collection.Write("speedtest1.gif");
			}

			return true;
		}
		[Benchmark]
		public bool Clone()
		{
			var baseImage = new MagickImage(File.ReadAllBytes(@"C:\Users\sirbr\Documents\Coding\Projects\C#\MagickTesting\MagickTesting\adi.png"));
			using (var collection = new MagickImageCollection())
			{
				for (var i = 1; i < 10; i++)
				{
					var sub = testString.Substring(0, i);
					var image = baseImage.Clone();
					image.Draw(new Drawables()
						.Text(128, 128, sub)
					);
					collection.Add(image);
					collection[i - 1].AnimationDelay = 10;
				}
				collection.Write("speedtest2.gif");
			}

			return true;
		}
		[Benchmark]
		public bool SameImage()
		{
			using (var collection = new MagickImageCollection())
			{
				var image = new MagickImage(File.ReadAllBytes(@"C:\Users\sirbr\Documents\Coding\Projects\C#\MagickTesting\MagickTesting\adi.png"));
				
				for (var i = 1; i < 10; i++)
				{
					var sub = testString.Substring(0, i);
					image.Draw(new Drawables()
						.Text(128, 128, sub)
					);
					collection.Add(image);
					collection[i - 1].AnimationDelay = 10;
				}
				collection.Write("speedtest3.gif");
			}

			return true;
		}
	}
}
```

### System Configuration

Windows 10, 64bit, standard .net core console application.

- Magick.NET version: Q8-OpenMPx64
- Environment (Operating system, version and so on): Windows
- Additional information: (I also tried this without benchmarking, calling the methods directly. Same issue)

**Comment by Tylertron1998** [comment]
very much unsure on what is causing this, sorry for the lack of description in the issue. No exception was thrown, so. The only difference between the first and last method (last being the one that hangs) is im using the same instance of MagickImage, where as in the first method I am creating a new instance.

**Comment by dlemstra** [comment]
It looks like you found something that I don't handle properly. You are not supposed to add the same image to the collection. This will create a loop of doom internally. I will need to add some checks and make sure you cannot add the same image to the collection twice. Thanks for reporting this

**Comment by Tylertron1998** [comment]
Ah- I thought this might have been the case, but imagined it was handled internally. Glad to help!

**Comment by dlemstra** [comment]
I just publish Magick.NET 7.7.0.0 that includes a fix for your issue.
