### ISSUE TITLE
Writing Pyramid Tiff to stream produces wrong and/or corrupt output

### ISSUE THREAD

**Issue by Christoph-Wagner** [dlemstra/Magick.NET#296]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Writing a LZW-compressed Pyramid tiff to a FileInfo object works without a problem. Writing it to a Stream results in `ImageMagick.MagickCoderErrorException: 'Compression algorithm does not support random access. ' @ error/tiff.c/TIFFErrors/652'` and writes a non-pyramid tiff.

Removing the LZW compression changes the error (again, only for the stream) to: 
`ImageMagick.MagickCoderErrorException: 'Error fetching directory count. 'TIFFLinkDirectory' @ error/tiff.c/TIFFErrors/652'` and writes a broken tiff file with the following `identify` output:
```
identify-im6.q16: Sanity check on directory count failed, this is probably not a valid IFD offset. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/564.
identify-im6.q16: Failed to read directory at offset 2843114. `TIFFReadDirectory' @ error/tiff.c/TIFFErrors/564.
```

### Steps to Reproduce
```C#
using ImageMagick;
using System;
using System.IO;
using System.Linq;

class Program
    {
        private const string SrcPath = "H:\\erez.jpg";
        private const string DestPath = "H:\\converted.tif";
        private const string DestPath2 = "H:\\converted2.tif";
        static void Main(string[] args)
        {
            try
            {
                Fails();
            }
            catch (Exception){}
            Works();
        }

        public static void Fails()
        {
            using (var image = new MagickImage(SrcPath))
            {
                image.Settings.Compression = CompressionMethod.LZW;
                using (var fStream = File.Create(DestPath))
                {
                    image.Write(fStream, MagickFormat.Ptif);
                }
            }
        }
        public static void Works()
        {
            using (var image = new MagickImage(SrcPath))
            {
                image.Settings.Compression = CompressionMethod.LZW;
                var file = File.Create(DestPath2);
                file.Flush(true);
                file.Dispose();
                var fInfo = new FileInfo(DestPath2);
                image.Write(fInfo, MagickFormat.Ptif);
            }
        }
}
```

### System Configuration

- Magick.NET version: 7.6.0.1
- Environment: Windows 10, Windows Server 2012
- Additional information: dotnetcore 2.1.3

**Comment by Christoph-Wagner** [comment]
Argh, failed with the title. As I see no way to change it, I'm leaving it as is.

**Comment by dlemstra** [comment]
Thanks for reporting this bug. It looks like you found a bug in ImageMagick and a bug in the stream writing code inside Magick.NET. I will push a fix to resolve this issue very soon.

**Comment by dlemstra** [comment]
I just publish Magick.NET 7.7.0.0 that includes a fix for your issue.
