### ISSUE TITLE
Issue in extending HEIC image format

### ISSUE THREAD

**Issue by BhushanShah** [dlemstra/Magick.NET#297]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am resizing an image which is in HEIC format and using extent to extend the image to satisfy height-width. I am also setting up a background color to white so that whenever image is not the specified height, it will fill the rest of the space with white color. This is working fine for JPG, PNG etc but not working properly for HEIC format. Instead of white, it is filling the pink color which is starnge.

### Steps to Reproduce

I have used below code:
```
using (MagickImage image = new MagickImage(filePath))
{
         image.Resize(250, 250);
         image.Extent(250, 250, Gravity.Center);
         image.BackgroundColor = MagickColors.ForestGreen;                    
         image.Write(outputFilePath);
}
```

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 7.6.0.1
- Environment (Operating system, version and so on): Windows 10
- Additional information:

**Comment by dlemstra** [comment]
It looks like you are not specifying the background color you want to use when extending the image. If you don't specify it the default background color of the image will be used. You should do this instead:
```C#
image.Extent(250, 250, Gravity.Center, MagickColors.White);
```

**Comment by BhushanShah** [comment]
Thanks for the quick response.  
I have tried that also and it did not work.You can find the image which got created [here](https://imgur.com/WSXfUec).

**Comment by dlemstra** [comment]
At this moment all the HEIC image have the YCbCr colorspace. You will need to change it to the sRGB colorspace first: `image.ColorSpace = ColorSpace.sRGB;`

**Comment by BhushanShah** [comment]
Yes, this works. 
Thank you very much for the help.
