### ISSUE TITLE
Run in docker throw an  exception 

### ISSUE THREAD

**Issue by wawa0210** [dlemstra/Magick.NET#298]
### Environment

- net core 2.1
- docker 18.06.1
- centos 7.3

### Description

Running in Centos not docker is perfect,But in docker support that

```
ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4307
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
   at ImageMagick.Drawables.Draw(IMagickImage image)
   at ImageService.MomentImageService.GenerateMomentShareImages(RequestProduct request, ServerCallContext context) in /src/ImageService/MomentImageService.cs:line 36
NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4307
```
@dlemstra

**Comment by dlemstra** [comment]
What is the contents of your Dockerfile? Do you also use centos as the base image? You probably need to install freetype in your container.

**Comment by wawa0210** [comment]
![image](https://user-images.githubusercontent.com/7907809/44759732-46f4ca00-ab6e-11e8-90d5-28423622e031.png)

This is my Dockerfile

**Comment by wawa0210** [comment]
I don't know how to change my Dockerfile so it can work well @dlemstra

**Comment by dlemstra** [comment]
The `Dockerfile` is using `microsoft/dotnet:2.1-runtime-deps-stretch-slim` that has `debian:stretch-slim` as the base image. This image probably does not contain freetype. You will need to install `freetype`. I will leave that as an exercise for the reader.

**Comment by wawa0210** [comment]
![image](https://user-images.githubusercontent.com/7907809/45728626-51e5cc00-bbfb-11e8-8c6a-875b3d37b733.png)

This is my new Dockerfile,but it's report the same exception as before 
![image](https://user-images.githubusercontent.com/7907809/45728656-793c9900-bbfb-11e8-9a99-7892f0f19b41.png)

**Comment by dlemstra** [comment]
Next time you could use code blocks in your post instead of screenshots: https://help.github.com/articles/creating-and-highlighting-code-blocks/ to improve the readability.

I am not a docker expert but should you not move the `RUN apt-get` line after the `FROM ... AS base`?

**Comment by wawa0210** [comment]
`FROM debian:stretch-slim`
`FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base`
`ENV DEBIAN_FRONTEND noninteractive`
`ENV DEBCONF_NOWARNINGS yes`
`RUN apt-get update `
`RUN DEBIAN_FRONTEND=noninteractive  apt-get install -y --no-install-recommends apt-utils &&  apt-get install libfreetype6  -y`
`WORKDIR /app`
`EXPOSE 80`
`FROM microsoft/dotnet:2.1-sdk AS build`
`WORKDIR /src`
`COPY ImageService /src/ImageService`
`COPY ImageService/nuget.config /root/.nuget/NuGet/`
`COPY ImageService.Base /src/ImageService.Base/`
`WORKDIR /src/ImageService`
`RUN dotnet restore`
`RUN dotnet build -c Release -o /app`
`FROM build AS publish`
`RUN dotnet publish -c Release -o /app`
`FROM base AS final`
`WORKDIR /app`
`COPY --from=publish /app .`
`ENTRYPOINT ["dotnet", "ImageService.dll"]`


This is my new Dockerfile,but it's not work well not yeat.and report the same exception as before

`Fontconfig error: Cannot load default config file`
`ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4307`
`   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)`
`   at ImageMagick.DrawingWand.NativeDrawingWand.Render()`
`   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)`
`   at ImageMagick.Drawables.Draw(IMagickImage image)`
`   at ImageService.MomentImageService.GenerateMomentShareImages(RequestProduct request, ServerCallContext context) in /src/ImageService/MomentImageService.cs:line 36`
`NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4307`

**Comment by dlemstra** [comment]
You can do multi line code blocks with [```].

This looks incorrect to me:

```
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends apt-utils && apt-get install libfreetype6 -y
```
Should this not be:
```
RUN apt-get install -y --no-install-recommends apt-utils && apt-get install libfreetype6 -y
```

And why do you have the `FROM debian:stretch-slim`?

I also wonder if you need to install FontConfig. This is now giving you an error:
`Fontconfig error: Cannot load default config file`

**Comment by wawa0210** [comment]
Sorry, I don't use markdown for long. I change my Dockerfile again, like this:

```
FROM debian:stretch-slim
FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
RUN apt-get update
RUN apt-get install -y --no-install-recommends apt-utils && apt-get install libfreetype6 -y && apt-get install fontconfig -y                      
WORKDIR /app
EXPOSE 80
FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ImageService /src/ImageService
COPY ImageService/nuget.config /root/.nuget/NuGet/
COPY ImageService.Base /src/ImageService.Base/
WORKDIR /src/ImageService
RUN dotnet restore
RUN dotnet build -c Release -o /app
FROM build AS publish
RUN dotnet publish -c Release -o /app
FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ImageService.dll"]
```

Building well ,But when I call the imageservice and it report the same exception . 

```
Fontconfig error: Cannot load default config file
ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4307
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
   at ImageMagick.Drawables.Draw(IMagickImage image)
   at ImageService.MomentImageService.GenerateMomentShareImages(RequestProduct request, ServerCallContext context) in /src/ImageService/MomentImageService.cs:line 36
NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/DrawImage/4307
```

Have you ever tried using Magick.Net on docker? Can you give me a proper Dockerfile reference

**Comment by wawa0210** [comment]
@dlemstra  Hello,Can you help me to slove this problem ?

**Comment by dlemstra** [comment]
@wawa0210 It looks like an issue with font config: `Fontconfig error: Cannot load default config file`. I don't know how to fix this. Did you manage to resolve this yourself?

**Comment by dmelendez35** [comment]
@wawa0210, I have the same issue, Did you manage to resolve this yourself?
