### ISSUE TITLE
How to get Ticks Per Second of MNG file?

### ISSUE THREAD

**Issue by OronDF343** [dlemstra/Magick.NET#299]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question

I need to get the "ticks per second" value from a MNG file. Unlike GIF, in which the delay is always in 1/100ths of a second, the delay in MNG uses a "ticks" unit, and the number of ticks per second is defined in the header.

[MNG-LC 1.0 Header](http://www.libpng.org/pub/mng/spec/mng-lc.html#mng-MHDR)

[ImageMagick delay command-line option](https://imagemagick.org/script/command-line-options.php#delay)

**Comment by dlemstra** [comment]
There appears to be a variable called `ticks_per_second` on the image struct inside ImageMagick that I don't expose yet. The name of the delay property is called `AnimationDelay`. Do you have any suggestion for the name of the new property that exposes `ticks_per_second`?

**Comment by OronDF343** [comment]
Not entirely sure of the naming conventions used in this project but the main difficulty here is to keep the name reasonably short while still being descriptive.
Here are some ideas:
`AnimationTicksPerSecond`
`AnimationDelayDenominator`
`AnimationDelayTps`

**Comment by dlemstra** [comment]
I just publish Magick.NET 7.7.0.0 that includes the new `AnimationTicksPerSecond` property.
