### ISSUE TITLE
Image orientation exif value change is not saved.

### ISSUE THREAD

**Issue by rxelizondo** [dlemstra/Magick.NET#302]
Helllo,

I am trying to change the exif orientation value of an image by using the following code:

```
using (var image = new MagickImage("OriginalImage.jpg"))
{
    var exif = image.GetExifProfile();
    exif.SetValue(ExifTag.Orientation, (ushort)1);  // Change from 6 to 1.
    image.AddProfile(exif);
    image.Write("OutputImage.jpg");
}
```

If I then pull up the exif information of the new file ("OutputImage.jpg"), the orientation value remains the same as the original file (it does not get updated).

Is there a problem with the code above? Or is the orientation value read-only? By the way, other exif values such as copyright are updated just fine.

Thanks.

**Comment by dlemstra** [comment]
The `image.Orientation` property overrules the `ExifTag.Orientation`. If you need to change the Exif orientation you should change the `image.Orientation` instead.

**Comment by rxelizondo** [comment]
@dlemstra, thank you very much for answering my question and thank you very much for this incredibly useful library.

I tried your suggestion and it worked perfectly, however, it raises a different question regarding why do we need to use the `image.Orientation` property instead of just using the exif profile? In other words, whats is wrong with using the exif profile?

Thanks.

**Comment by rxelizondo** [comment]
@dlemstra, My question had more to do with consistency rather than technical issues. In other words, if exif is the standard way to keep track of orientation then why not just remove the `image.Orientation` property and just rely on the exif profile, or if you want to use `image.Orientation` that is fine buy why not then remove the `ExifTag.Orientation` tag? In other words, it seems that having two ways of doing the same thing is somewhat confusing.

Also, as a suggestion, if you need to keep things the way the are right now (perhaps because you need to maintain backwards compatibility), perhaps you should consider throwing an exception when someone tries to set the orientation using the exif profile.This way, at least, someone making that same mistake will know right away that is not the way to go.

Thanks.

**Comment by rxelizondo** [comment]
@dlemstra, Thank you, one last question if you don't mind me asking. Just to confirm, are you saying that there are two orientation properties saved in an image file? An orientation property saved in the image itself and another orientation property saved in the exif profile?

Thanks.

**Comment by dlemstra** [comment]
That depends on the image format. Some formats have both and some only have the orientation from the exif profile.
