### ISSUE TITLE
Is it possible to create an image from a pixels collection?

### ISSUE THREAD

**Issue by adriapa5** [dlemstra/Magick.NET#303]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question
Hi there, 
I need to create an image given an array of bytes. I consider to create a pixels collection from the array of bytes and then create the image using the collection. Is it possible? Is there a better way of doing it?

I'm using Magick.NET-Q8-AnyCPU package version 7.7.0 in a ASP.NET Core Application.

Thanks in advance!

Adri

**Comment by dlemstra** [comment]
What is the contents of your array of bytes? If the array only contains pixel information you can use the `MagickImage.ReadPixels` to read the pixels.

**Comment by adriapa5** [comment]
Hi Dirk,
Thanks for replying. 
Actually the array contains array of bytes (byte[] []), but they are pixel information. So if I can use ReadPixels method I can convert it to a simple array of bytes. Should this array have a specific order related to pixels?
Thanks in advance
Adri

**Comment by dlemstra** [comment]
You will need to convert it to a single array for now but it might also be a good idea to support multidimensional arrays. When you create the `PixelStorageSettings` one of the arguments is the mapping (in other words the order of the pixels).

**Comment by adriapa5** [comment]
It works! Thanks
