### ISSUE TITLE
Can I get a pixel width of the text applied on an image?

### ISSUE THREAD

**Issue by kasradzenika** [dlemstra/Magick.NET#304]
Here is my code:

            Drawable drawable
            .TextEncoding(System.Text.Encoding.UTF8)
            .FontPointSize(28)
            .Font("Arial");

            drawable.Text(0, 0, "Word");

How can I know in advance the pixel width of the "Word" string on the final image output? Is it possible?

**Comment by dlemstra** [comment]
At this moment this is not possible but I could probably make this possible. I will need to make something similar to `MagickQueryFontMetrics` in the Magick.NET library.

**Comment by dlemstra** [comment]
This feature has been added in Magick.NET 7.8.0.0
