### ISSUE TITLE
`_TIFFVSetField' @ error/tiff.c/TIFFErrors/650

### ISSUE THREAD

**Issue by adriapa5** [dlemstra/Magick.NET#305]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi,

I'm using magick net library to read images from several image formats. 
For most of images it works just well, but for some of them it throws error like:
: Null count for "Tag 34026" (type 1, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/650

This is the StackTrace:   "at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
   at Alexandria.Aira.ImageProcessor.API.Services.ImageProcessor.ProcessImage(DownloadedImage downloadedImage, MagickGeometry& resizedSize)"

### Steps to Reproduce
This is a Console Application (.NET Core). At this moment, I would like to send you the image but I should ask if I can do it, due to copyright reasons.

```
class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (FileStream stream = File.Open("test.TIF", FileMode.Open))
                {
                    using (MagickImage image = new MagickImage(stream))
                    {
                        image.Resize(500, 500);
                    }
                }
            }
            catch (Exception ex)
            {
                 Console.WriteLine("{0} {1}",ex.Message, ex.StackTrace);
            }
            Console.ReadLine();
        }
    }

```
Besides, I install the ImageMagick library in a Linux machine and execute the "identify" command to get more information. You can find attached the output of that file (identify.txt).
It seems to be a problem when ImageMagick library try to read the image. Is able to do it but throw several exceptions. I find that info here: http://www.imagemagick.org/discourse-server/viewtopic.php?t=32547

### System Configuration
I'm using Magick.NET-Q8-AnyCPU package version 7.7.0 in a ASP.NET Core Application.

Thanks in advance

Adri

[identify.txt](https://github.com/dlemstra/Magick.NET/files/2357274/identify.txt)

**Comment by dlemstra** [comment]
The ImageMagick and tiff library are very strict when reading files. It appears that your input image is corrupt.

**Comment by adriapa5** [comment]
Hi,

I don't think that image is corrupt, because I managed to open it using Bitmap (Drawing library). Also, I tried to open it a corrupt image and the error message is very different.

Thanks for replying

**Comment by dlemstra** [comment]
The drawing library is not as strict as ImageMagick and that is why it fails to read your image. 

Another posibility is that there is a bug inside libtiff but that is not very likely.

**Comment by Halofreak1990** [comment]
> Another posibility is that there is a bug inside libtiff but that is not very likely.

http://www.imagemagick.org/discourse-server/viewtopic.php?t=27173 would indicate otherwise.

I find it curious, however, that the command-line ImageMagick tools treat this situation as a warning, as opposed to Magick.NET, which throws an exception.

**Comment by dlemstra** [comment]
Are you sure you are getting a warning instead of an error? The post you linked also shows an error. And if you think this is a libtiff bug you should report an error there.
