### ISSUE TITLE
Error: Methods must be security critical or security safe-critical to call native code

### ISSUE THREAD

**Issue by asyncerror** [dlemstra/Magick.NET#306]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET 

### Question
Hello friend! I'm getting a error:

`Attempt by security transparent method 'ImageMagick.MagickSettings+NativeMagickSettings..ctor()' to call native code through method 'ImageMagick.MagickSettings+NativeMethods+X86.MagickSettings_Create()' failed. Methods must be security critical or security safe-critical to call native code.`
``

Seems that occur on this call:
`Dim settings As New MagickReadSettings()`

Any ideas? Occurred after a server migration, was working, you know any configuration to set on server to fix this?

**Comment by dlemstra** [comment]
I have no idea in what kind of environment you are running this but I am guessing that is is IIS. Running your application in full trust might solve the issue.

**Comment by asyncerror** [comment]
Thanks! Cloud Host is saying is in full trust. I'll double check!

**Comment by asyncerror** [comment]
@dlemstra Was fulltrust! Now is working. Thank you for point this.
