### ISSUE TITLE
Compression Group4 and Fax has no effect for tiff.

### ISSUE THREAD

**Issue by t246246** [dlemstra/Magick.NET#307]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using ImageMagick, it is easy to create Group4/Fax compressed tiff:
```% magick logo: -compress Group4 tmp.tif```
```% magick logo: -compress Fax tmp.tif```
But the following Magick.NET program (in Steps to Reproduce) does not compress the file:
It prints:
LZW
Zip
RLE
NoCompression
NoCompression
NoCompression

### Steps to Reproduce
```
using System;
using System.IO;
using ImageMagick;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string outFile = "./tmp.tif";
            foreach (var c in new CompressionMethod[]
            {
                CompressionMethod.LZW,
                CompressionMethod.Zip,
                CompressionMethod.RLE,
                CompressionMethod.Group4,
                CompressionMethod.Fax,
                CompressionMethod.NoCompression
            }) {
                MagickReadSettings settings = new MagickReadSettings();
                using (var image = new MagickImage("logo:", settings))
                {
                    image.Format = MagickFormat.Tiff;
                    image.Settings.Compression = c;
                    image.Write(outFile);
                }
                using (var image = new MagickImage(outFile))
                {
                    Console.WriteLine(image.Compression);
                }
                File.Delete(outFile);
            }
        }
    }
}
```
### System Configuration

- Magick.NET version: 7.7.0 Q16 AnyCPU
- Environment (Operating system, version and so on): Windows 7 64bit
- Additional information:

**Comment by dlemstra** [comment]
It looks like you found the same bug that has been reported here: https://github.com/ImageMagick/ImageMagick/issues/1297. Will publish a new release soon to resolve this issue. Thanks for the detailed report. I will make sure I use that in a unit test.

**Comment by dlemstra** [comment]
I just published Magick.NET 7.8.0.0 that includes a fix for your issue.

**Comment by Jmuccigr** [comment]
This will show up in IM 7.0.8-12, I hope?

**Comment by dlemstra** [comment]
@Jmuccigr Yes it will.

**Comment by t246246** [comment]
Thank you. I works. But if I add  image.SetAttribute("colorspace:auto-grayscale", "false");
[code]
using (var image = new MagickImage("logo:", settings))
                {
                    image.SetAttribute("colorspace:auto-grayscale", "false");
                    image.Format = MagickFormat.Tiff;
                    image.Settings.Compression = c;
                    image.Write(outFile);
                }
[/code]
it still outputs NoCompression for Fax and Group4.

**Comment by t246246** [comment]
Thank you. I had thought both -define and -set are valid syntax: https://www.imagemagick.org/discourse-server/viewtopic.php?t=28453#p126332 , but guessing from current document, https://www.imagemagick.org/script/command-line-options.php#define , using -define for this purpose for tiff is not proper.
