### ISSUE TITLE
caption: number on new line

### ISSUE THREAD

**Issue by truyb** [dlemstra/Magick.NET#308]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I create an image with a caption text on it which contains a number, starting from the number a new line will always be made, unless the number with all the text after it WILL fit on the line beforehand.

### Steps to Reproduce

Run the following code:

```
using ImageMagick;

namespace NumberCaption
{
    class Test
    {
        static void Main(string[] args)
        {
            using (var text = new MagickImage(MagickColors.Transparent, 180, 65))
            {
                var textSettings = new MagickReadSettings()
                {
                    FillColor = MagickColors.Blue,
                    FontPointsize = 23,
                    Width = 180,
                    Height = 85,
                    TextInterlineSpacing = -2
                };

                text.Read("caption:Text text 2 Verylongtextwithoutspaces", textSettings);
                text.Write(@"D:\example1.png");

                text.Read("caption:Text 2 Verylongtext", textSettings);
                text.Write(@"D:\example2.png");

                text.Read("caption:Text text 2 Normal text", textSettings);
                text.Write(@"D:\example3.png");

                text.Read("caption:Text Text 2 Normal text", textSettings);
                text.Write(@"D:\example4.png");

                text.Read("caption:a 2 Normal text", textSettings);
                text.Write(@"D:\example5.png");
            }
        }
    }
}
```

Here are the results:
[Example 1](https://i.imgur.com/3pzBFy1.png)
[Example 2](https://i.imgur.com/Dn0MPMX.png)
[Example 3](https://i.imgur.com/Z48SNnk.png)
[Example 4](https://i.imgur.com/wefvUhs.png)
[Example 5](https://i.imgur.com/xKl4Nyu.png)

As you can see, in examples 1 to 4 the '2' should easily fit on the top line. In example 5, since the text after '2' fits on the first line together with the '2', it works as intended.

### System Configuration

- Magick.NET version: v7.7.0 Q8 AnyCPU
- Environment (Operating system, version and so on): Windows 7, Visual Studio 2017, .NET Version 4.6.1
- Additional information: /

**Comment by dlemstra** [comment]
Thanks for reporting this. I just pushed a patch to resolve this issue inside ImageMagick. Will also add some unit tests to make sure this stays fixed.

**Comment by dlemstra** [comment]
I just published Magick.NET 7.8.0.0 that includes a fix for your issue.
