### ISSUE TITLE
ImageOptimizer locks on file after failing to optimize the file

### ISSUE THREAD

**Issue by whatohyou** [dlemstra/Magick.NET#309]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Image optimizer locks the image when it throws 'invalid image' exception.
It will not let go until the program is terminated.

### Steps to Reproduce

```
private void img_optimize(string file2)
        {
            try
            {
                ImageOptimizer optimizer = new ImageOptimizer();
                optimizer.Compress(file2);//Error Invalid image. Then it will not let go of the image file.
                //I can't delete the image file because file is in use...

                return; //return will not run.
            }
            catch
            {
                return; //return will not run.
            }
          
        }


```

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

Is there anyway you can make this class, idisposable friendly so we can use it with using{} ?

**Comment by dlemstra** [comment]
Can you also share the file so I can test this? And would it be possible to create a small sample that also tries to delete the file so I can reproduce it better?

**Comment by dlemstra** [comment]
@whatohyou Could you please share a file or at least tell me which type of file you used to reproduce the issue? Working on a new release and I would love to know if this is something inside the Magick.NET library.
