### ISSUE TITLE
.NET Core Server Nano - Unable to load DLL 'Magick.NET-Q8-x64.Native.dll': The specified module could not be found

### ISSUE THREAD

**Issue by Exocomp** [dlemstra/Magick.NET#311]
I'm getting the following error with .NET Core on Server Nano x64:

System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q8-x64.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ImageMagick.Environment.NativeMethods.X64.Environment_SetEnv(IntPtr name, IntPtr value)
   at ImageMagick.Environment.NativeEnvironment.SetEnv(String name, String value)

File Magick.NET-Q8-x64.Native.dll is in the published directory so is in the correct location.

**Comment by dlemstra** [comment]
I have never tried to use Magick.NET on a Nano Server but I suspect I might be using some libraries inside Magick.NET-Q8-x64.Native.dll that are not available on a Nano Server. Are you using the docker images?

**Comment by Exocomp** [comment]
Hi @dlemstra,

I'm not using a docker image. I tried your library because Nano server doesn't have GDI+ support so using the built in System.Drawing functionality doesn't work, does your library rely on GDI+?

**Comment by dlemstra** [comment]
The EMF coder uses GDI+ and that is probably one of the reasons that it doesn't work. And it looks like I cannot make a nano server only version of the library because the Windows RIDs does not contain a specific one for nano server: https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

**Comment by Exocomp** [comment]
Gotcha, no worries, I'll dig into it some more and see if I can remove the GDI dependencies on my side when I get some time.
