### ISSUE TITLE
MagickImageInfo throwing an error for HEIC image format.

### ISSUE THREAD

**Issue by BhushanShah** [dlemstra/Magick.NET#313]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am using a MagickImageInfo to get the properties of an image like height and width but it doesn't work for all the image format(HEIC is not working). It throws an error like below:
`Exception Message: no decode delegate for this image format ' @ error/blob.c/CustomStreamToImage/769`

```
Exception:   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
   at ImageMagick.MagickImageInfo.Read(Stream stream)
```

### Steps to Reproduce

Below is the code snippet:

`MagickImageInfo image = new MagickImageInfo(Stream);`

Just for your information,I have IFormFile file as a parameter and than I am reading the stream with IFormFile.OpenReadStream().

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 7.6.0.1
- Environment (Operating system, version and so on): Windows 10
- Additional information:

Let me know if any additional information required.

**Comment by BhushanShah** [comment]
Hi,
I have uploaded the sample image on google drive. You can find at below link:
https://drive.google.com/file/d/1rTHjMWerr95vVJKbpK411Q0YUdH1QmlL/view?usp=sharing

Thanks,
Bhushan Shah

**Comment by dlemstra** [comment]
Thanks for your file. I just pushed a patch to the ImageMagick repository to improve the format detection in the heic coder. But I don't think these changes will make it into the next release of Magick.NET. I will try to publish a new release after the release very soon though.

**Comment by BhushanShah** [comment]
Thanks, Dirk for fixing the issue.  I appreciate your help.
By any chance, do you know when the fix will be available to use?

**Comment by dlemstra** [comment]
The best answer that I can give you is "it depends". I hope I can finally publish the new release that I was planning tomorrow. But that won't include the patch I just made for you. It will probably take a couple weeks until your fix is available. But I might be able to work on it earlier. It depends...

**Comment by BhushanShah** [comment]
Thanks for the update. I will keep an eye on the new releases.

**Comment by dlemstra** [comment]
Will let you know if this issue when that release has been published.

**Comment by BhushanShah** [comment]
That would be great. 

Thanks.
