### ISSUE TITLE
Saving EXIF profile with empty values removes the empty ExifTag

### ISSUE THREAD

**Issue by Brubning** [dlemstra/Magick.NET#316]
I have an image with an EXIF profile where the OwnerName ExifTag is "". If I amend any other values in the profile, and then write it back to the image, the OwnerName ExifTag (along with any other empty tags) is removed from the profile.

I'm using Magick.NET Q16 Any CPU, v7.5.0.

            using (var image = new MagickImage(SourceFilename))
            {
                var profile = image.GetExifProfile();

                var pixelX = profile.GetValue(ExifTag.PixelXDimension);
                if (pixelX.DataType == ExifDataType.Short)
                    profile.SetValue(ExifTag.PixelXDimension, (ushort)image.Width);
                else
                    profile.SetValue(ExifTag.PixelXDimension, (uint)image.Width);

                var pixelY = profile.GetValue(ExifTag.PixelYDimension);
                if (pixelY.DataType == ExifDataType.Short)
                    profile.SetValue(ExifTag.PixelYDimension, (ushort)image.Height);
                else
                    profile.SetValue(ExifTag.PixelYDimension, (uint)image.Height);
                
                var filename = Path.Combine(
                    Path.GetDirectoryName(image.FileName),
                    "Fixed.jpg");

                image.AddProfile(profile);
                image.Write(filename);
            }

Adobe Bridge seems to require a complete, "correctly" sequenced EXIF profile for labelling to work, so images processed can't be updated in Bridge.

**Comment by Brubning** [comment]
This has to be a bug with Bridge. I've just tried saving a file from Bridge and the meta data is all over the place, so it isn't what I thought. I'll close this and carry on investigating, unless you have any ideas on what might cause Bridge to be unable to save meta data?

**Comment by dlemstra** [comment]
I have never heard of Bridge but maybe it only support either `ushort` or `uint`? You can call `RemoveValue` to remove the value and overwrite it with a new value?

**Comment by Brubning** [comment]
Bridge is an Adobe product which provides a quick way into a folder of images so that you can tag them with quality ratings or label them to help smooth out your downstream image workflow. We use a Bridge Label to show if an image is the selected image in a batch, or not, and then only those that are labelled are processed in our rendering function.

The issue I'm having is that labelling in Bridge isn't working if I make a change to the EXIF in Magick.NET. Before I make the change, it's fine. If I make a change in Photoshop and save, then it's fine. If I remove the EXIF Profile using Magick.NET it's also fine.

I'm trying to work out why, because this is a critical part of the workflow process. I notice when I read the EXIF Profile that there is an InteroperabilityOffset which Magick.NET can't read. I don't know if the offset needs to be recalculated when profile values change?

I tried a really simple example, removed the EXIF profile, then created a new one, added PixelXDimension and PixelYDimension and saved it. Even this small profile didn't work with Bridge.

The error in Bridge is "Could not save meta data to image ***.jpg" (helpfully vague and non-specific).

I can see online that there are a lot of people who have had this issue with Bridge in the past, but there doesn't seem to be a good answer, so I'm still trying to qualify where the problem is.

I have noticed that some EXIF values can be one of two types e.g. PixelXDimension is listed in the specification as SHORT OR LONG. It could be useful to add ExifDataType.ShortOrLong and use TryParse to determined which type to save.

I've had an idea for a feature request which I'll list separately that relates to this.

Thanks
