### ISSUE TITLE
nVidia drivers + OpenCL issue

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#317]
Apparently the recent nVidia drivers (version 410+) have an OpenCL update that seems to be causing Magick to fail.

I've tried it with 7.7 and 7.6.0.1 on several computers (including end-users) and the common factor in all of them is the nvidia driver update.

In code, it hangs the thread as soon as we get to any OpenCL-friendly method. If no OpenCL methods have been used, it gets stuck on `Dispose()` or at the end of the `using` statement. It happens in `using` statements for `GetPixelsUnsafe()` as well. Same pattern - dead on dispose.

Please let me know if I can provide any additional info.

Am using `Magick.NET-Q16-HDRI-x64-OpenMP`.

**Comment by dlemstra** [comment]
Earlier this year we disabled NVIDIA devices by default for OpenCL due to a lot of reports about access violations: https://github.com/ImageMagick/ImageMagick/commit/506256cdb5e48435570bbcae81eb8d17de1f7b9f. But it looks like I made a mistake. Just pushed a patch to resolve this: https://github.com/ImageMagick/ImageMagick/commit/9c43e2af2a9ce851afdd27577282838c34bbc6c1. Working on a new release right now so a fix should be available very soon.

**Comment by daxpandhi** [comment]
I bet nvidia is rushing too quickly for the RTX boards and making mistakes. :(

Thanks!! :) Not urgent. I just pushed out an update where I just disable OpenCL on startup.

**Comment by daxpandhi** [comment]
Also, many users have reported that if they let it run for 5 minutes or so, it will suddenly start and then no longer have problems starting up later. Weird!

**Comment by dlemstra** [comment]
ImageMagick is waiting for a response for the OpenCL device. I have no idea why it needs to take five 5 minutes the first time though. But we had other issues with nVidia so we disabled it by default.

**Comment by dlemstra** [comment]
While writing the release notes for Magick.NET 7.8.0.0 that I just published I realized that it probably works later on because the old patch disabled OpenCL for the second operation. I hope this new release resolves your issue.

**Comment by daxpandhi** [comment]
Thank you!! I'll test it in the morning and confirm.

**Comment by daxpandhi** [comment]
It is working perfectly for me, and for several others. Just deployed it to 700 users so will get you a proper sample in a day or two. So far only 1 person said it still behaved the same way. When he used an option I had added to disable all OpenCL devices, then it worked.

**Comment by dlemstra** [comment]
@daxpandhi Feel free to close this issue if you think we can close it.

**Comment by daxpandhi** [comment]
@dlemstra - closing the issue. Some people have reported the same problem even with the new version, but I don't have enough data on it yet. If I find anything substantial, will reopen. Thanks!

**Comment by daxpandhi** [comment]
@dlemstra - a few people have reported that even with the latest update, the application freezes - same as in the older versions. If they use the option to disable OpenCL completely, then it works.

I'm gathering hardware and other stats from them and will email them to you in case they're useful.

I can't reproduce the error on my hardware. But if needed, we can run any tests you like on their hardware. I'll get more info from them and update my notes here.

Also, with the new Magick, it takes a very long time (up to 15 seconds sometimes) for the first operation of any kind. I'm guessing that's because it is going through all the nvidia devices and turning OpenCL off for them. Can this be done asynchronously, or if not, what if OpenCL is turned off completely and then it would skip the querying and turning off? For CLI apps where it starts anew very frequently, this adds a long noticeable load time. Not a priority, but thought I'd mention in case there was an easy solution.

**Comment by dlemstra** [comment]
Please email me the hardware details. I don't understand why you would get a 15 secs startup that should only happen the first time when the devices are benchmarked. Can you reproduce it locally with debug logging enabled?

**Comment by daxpandhi** [comment]
Will do. Thanks!

**Comment by daxpandhi** [comment]
Okay, stupid question: how do I turn on debug logging? `MagickSettings.Debug` is available through `MagickImage`only, right?

I used the `Log` event in `MagickNET` to get the attached log. Please let me know if I need to do it differently.
[magicklog-001.zip](https://github.com/dlemstra/Magick.NET/files/2465135/magicklog-001.zip)

I checked on two different systems with a clean reboot. Can confirm a hang for about 4 seconds on both when the first Magick operation (loading a file and calling `GetPixelsUnsafe`) happens.

Hardware for this one:
- Intel Core i7-8700 @ 3.7Ghz
- nVidia GeForce 1080 GTX
- Intel UHD Graphics 630 (on-board)

**Comment by dlemstra** [comment]
This is one of the few things I actually have some documentation about: https://github.com/dlemstra/Magick.NET/blob/master/Documentation/DetailedDebugInformation.md :) Haven't check your logs yet, will take a look at it tomorrow if you used the same method. And you might need to put it on something like dropbox in case the file gets larger.

**Comment by daxpandhi** [comment]
Great! I'm so glad I did it that same way. :D

I'll upload additional logs and hardware stats in the meantime and send you an email digest instead. Easier for you, hopefully.

In the meantime, I've forcefully disabled OpenCL entirely. OpenMP is fast enough, so I can do fine without OpenCL for now. :)

Thanks!

**Comment by dlemstra** [comment]
Any news regarding this issue @daxpandhi?

**Comment by daxpandhi** [comment]
Haven't been able to get any new useful info on this as we had to freeze the code for release soon. For safety's sake, we now force OpenCL off on initialization. I'll close this issue. If I find meaningful data in the future will reopen it. Thanks!
