### ISSUE TITLE
Add ExifValue.TrySetValue to make adding values to EXIF profiles easier

### ISSUE THREAD

**Issue by Brubning** [dlemstra/Magick.NET#319]
When building an EXIF profile programatically you need to know the data type etc. of every ExifTag, which means maintaining a lot of relevant EXIF information outside of the EXIF classes in Magick.NET. I think it would be useful to maintain an internal list of ExifDefinition which describes the ExifTag and allows a TrySetValue (similar to TryParse) so you can add values more easily to the profile.

This could also simplify some of the existing code in ExifValue (perhaps simplifying the large switch statements in create etc.)

ExifDefinition could look like this, with an internal hashtable containing the value descriptors for supported ExifTags.

    public class ExifDefinition
    {
        public ExifDefinition(ExifTag tag, ExifDataType dataType, bool isArray, bool isReadonly)
        {
            Tag = tag;
            DataType = dataType;
            IsArray = isArray;
            IsReadOnly = isReadonly;
        }

        public ExifTag Tag { get; set; }
        public ExifDataType DataType { get; set; }
        public bool IsArray { get; set; }
        public bool IsReadOnly { get; set; }

        public static Hashtable ExifDefinitions { get; } = new Hashtable
        {
            {ExifTag.ImageDescription, new ExifDefinition(ExifTag.ImageDescription, ExifDataType.Ascii, false, false)},
            {ExifTag.Make, new ExifDefinition(ExifTag.Make, ExifDataType.Ascii, false, false)}
        }
    }

Then ExifValue could be extended to have a TrySetValue, or TryParse method which could look like:

        public static bool TrySetValue(ExifTag exifTag, string value, out ImageMagick.ExifValue result)
        {
            var profile = new ImageMagick.ExifProfile();
            ImageMagick.ExifValue internalResult = null;
            var exifDefinition = (ExifDefinition)ExifDefinition.ExifDefinitions[exifTag];

            switch (exifDefinition.DataType)
            {
                case(ExifDataType.Ascii):
                    profile.SetValue(exifTag, value);
                    internalResult = profile.GetValue(exifTag);
                    break;
                case(ExifDataType.SignedShort):
                    if (short.TryParse(value, out var shortResult))
                    {
                        profile.SetValue(exifTag, shortResult);
                        internalResult = profile.GetValue(exifTag);
                    }
                    break;
                case(ExifDataType.Short):
                    if (ushort.TryParse(value, out var ushortResult))
                    {
                        profile.SetValue(exifTag, ushortResult);
                        internalResult = profile.GetValue(exifTag);
                    }
                    break;
                case(ExifDataType.SignedLong):
                    if (long.TryParse(value, out var longResult))
                    {
                        profile.SetValue(exifTag, longResult);
                        internalResult = profile.GetValue(exifTag);
                    }
                    break;
                case(ExifDataType.Long):
                    if (ulong.TryParse(value, out var ulongResult))
                    {
                        profile.SetValue(exifTag, ulongResult);
                        internalResult = profile.GetValue(exifTag);
                    }
                    break;
            }

            result = internalResult;

            return internalResult != null;
        }

Usage:

            if (ExifProfile.ExifValue.TrySetValue(exifTag, value, out var result))
            {
                profile.SetValue(exifTag, result.Value);
                image.AddProfile(profile);
                image.Write(sourceFilename);
            }

Just an idea.

**Comment by dlemstra** [comment]
I like the idea of having an `ExifDefinition` class. This could also simplify some of the code inside the `ExifWriter` class.

What would be the goal of the `TrySetValue` method and why is the input a string? Do you want a method that will not throw an exception when the value is invalid?

**Comment by Brubning** [comment]
The aim of TrySetValue is to provide a safe way to add EXIF values to a profile (like *int.TryParse*).

I can do it outside of the ExifValue class, but that means maintaining a data type list in the calling code. It also helps simplify EXIF values like PixelXDimension where the type could be ushort or ulong depending on the existing value. I thought it would be handy to put a method of the ExifValue class to help, and to internalise the type checking etc. The added benefit is that you then have an internal type checking list which can be used in other ways.

The reason the input is a string is because I was pulling together a lazy example (sorry) and didn't want to think about array values. It should be *object* to be consistent with the current ExifValue methods.

**Comment by dlemstra** [comment]
A lazy example is always better than no example :). The signature of your method confused me a bit. Should this not be `TrySetValue(exifTag, value)` instead? Maybe we could even allow overwriting the value with a value of an other type if that is valid for the existing value. And a string input could also be possible and then convert it inside the method to the correct type as you suggested.

**Comment by Brubning** [comment]
The method signature borrows from Convert.TryParse where the return value is a boolean that tells you whether the conversion was successful, and the out parameter is the successfully converted parameter.

**Comment by Brubning** [comment]
I'm happy to have a go at this, if I get time. Do you have coding guidelines etc?

**Comment by dlemstra** [comment]
Thanks for offering to help me out 👍  I have automated code style guides but no real code guidelines. 

Maybe we could start with adding the internal ExifDefinition class. Why do we need the `IsReadOnly` property in the class? And maybe we should make an array of `public ExifDataType DataType`? Feel free to start a proposal for this in a PR and we can discuss it further there?

I don't think we need the out variable because it will try to set the exif value and tell you if it succeeded to do that. You don't need to use the value afterwards. The could would be this:

```
if (ExifProfile.ExifValue.TrySetValue(exifTag, value))
{
    // profile.SetValue(exifTag, result.Value);
    image.AddProfile(profile);
    image.Write(sourceFilename);
}
```

**Comment by Brubning** [comment]
Hi, I've started to look at this, but can't push changes to a new branch in order to create a pull request. Permission denied.

**Comment by dlemstra** [comment]
You will need to fork the repository first and then push the branch to your own repository.

**Comment by dlemstra** [comment]
The Exif API has been completely changed in release 7.15.0.0 and that solves the issue that was raised here so I will close this issue now.
