### ISSUE TITLE
Magic.Net.Web support for streams (or something else)

### ISSUE THREAD

**Issue by kristofdegrave** [dlemstra/Magick.NET#32]
I'm currently using Magic.Net.Web for resizing my images when requested. Currently we are fetching the images we want to resize from a share. So far, no issues.

Currently we are investigating to move to the cloud and in this case we would like to make use of Blobstorage. This issue with this is inside the ImageOptimizerHandler. In this you need a fileName that is used to copy the image. So an url is not allowed here. So an extension that you are able to provide a stream instead of a file name would be great. You could check for a stream first and write this to your tempfolder if present. If not provided you can take the way it is currently working.

Let me know what you think.

**Comment by dlemstra** [comment]
I could add a Stream property to the IUrlResolver for this. And do something inside the MagickHandler to determine if the FileName or the Stream should be used. This should not be that difficult to add. I'll try to add it this week.

**Comment by kristofdegrave** [comment]
Thanks,

I'm trying to create a pull request for this, but it seems the impact is a bit bigger than expected. There are more dependencies on the fileName than I expected.

Also the creation of an `MagickImage` depends on this. Didn't found out yet what the impact of this is.

**Comment by dlemstra** [comment]
Cool that you are trying to create a pull request for this. I did a bunch of refactoring last night and it appears that I did a forced push so the git sync (from codeplex to github) did not go perfectly. I am planning to add some unit tests first and for this I will probably need to refactor some of the code. The current code is not written with testing in mind. Then I will try to add this feature. MagickImage has support for reading images from a stream.

**Comment by dlemstra** [comment]
The unit test have been added so I can start working on adding this feature. I think I will need to add something to the IUrlResolver for this. I am considering to add this:
```C#
public interface IUrlResolver
{
  IStreamInfo StreamInfo { get; }
}  

public interface IStreamInfo : IDisposable
{
  DateTime ModifiedDateUtc { get; }

  Stream Stream { get; }
}
```

I need to know the modification date to check if I can use the cache. I also think the class should be IDisposable to make it possible to clean up the stream. Not 100% sure about the name `ModifiedDateUtc` but I also don't know what would be a better name 😕 any suggestions @kristofdegrave?

**Comment by kristofdegrave** [comment]
Can't think on a better name for now. It makes clear what the value should be so I think it's a good name.

Making it disposible will be a good idea. Otherwise it will be hard to determine on how to clean up the resources.

If I can make a suggestion:
Instead of putting it into the stream into the `IUrlResolver`, it's maybe better to use an new interface that inherits from `IUrlResolver`. This way it will be easier to detect if someone uses a stream.

An other suggestion is to add a property containing the stream (and even better the streamInfo) in your handler. In this you can turn the file into a stream. This way you can work on a uniform way using the stream.

Greetings,

Kristof

**Comment by dlemstra** [comment]
My idea was that it if you don't set the FileName in the Resolve method I will check if the StreamInfo is set. If that is set I will read from the stream. But it might be better to add an IFileUrlResolver and an IStreamUrlResolver.  Reading from the stream all the time would not be the best option. At this moment the performance when reading from file is better than reading from a stream. I already have an idea to resolve this, just need some time to do it :smile:

**Comment by kristofdegrave** [comment]
Fine for me, I think you are better placed to judge on performance :)

**Comment by dlemstra** [comment]
Hmm... it would be easier if I could always dispose the stream. What do you think about the following design:

```C#
public interface IUrlResolver
{
  MagickFormat Format { get; }

  bool Resolve(Uri url);
}

public interface IStreamUrlResolver : IUrlResolver
{
  string ImageId { get; }

  DateTime ModifiedTimeUtc { get; }

  Stream OpenStream();
}
```
And in the code I will do a using around the OpenStream part.

I will also move the stuff for the MagikScript to a separate interface called IScriptResolver. Then you won't need to implement this stuff if you don't want to use it.

```C#
public interface IScriptResolver
{
  MagickFormat OutputFormat { get; }

  IXPathNavigable Script { get; }
}
```

**Comment by kristofdegrave** [comment]
Sounds good.

Maybe let IScriptData inherit from IUrlResolver too. This because you can't use the IScriptData functionality without implementing the IUrlResolver.

**Comment by dlemstra** [comment]
I just made the first steps in 10d4511. Instead of implementing IUrlResolver you will now need to implement IFileUrlResolver (or IStreamUrlResolver later this week) and if you want the extra script functionality you will need to add IScriptData to your resolver. Does not really make sense to me to inherit from the IUrlResolver.

**Comment by dlemstra** [comment]
IStreamUrlResolver has been added an will be available in the next version of Magick.NET

**Comment by dlemstra** [comment]
@kristofdegrave The new release with the new features has been published. Please let me know if this works for you so I can close this issue.

**Comment by kristofdegrave** [comment]
Hi, Thanks. Sorry I didn't had time to look at this yet, but the last few weeks we were busy getting the release ready. You may close this issue for now. If I run into issue i'll let you know by opening this issue again or a new one.
