### ISSUE TITLE
Compress Image

### ISSUE THREAD

**Issue by AdwardNguyen** [dlemstra/Magick.NET#320]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question
 I just install Magick.net from nuget and I have a problem when I want to compress and resize image from IFormFile (Net Core 2.1)

Here my sample code 
`var stream = file.OpenReadStream();
                        using (MemoryStream ms = new MemoryStream())
                        {
                            stream.CopyTo(ms);
                            ImageOptimizer optimizer = new ImageOptimizer();
                            optimizer.LosslessCompress(ms); //error here: Value cannot be empty - Params: Stream
                        }`

If I load file from physical path, it's working fine, but I need compress and resize before upload image. Please help me!!!

**Comment by dlemstra** [comment]
You need to set the `Position` of the memory stream back to `0` before you pass it to the `LosslessCompress` method. I will see if I can give a better error message when this happens.

**Comment by AdwardNguyen** [comment]
Wow, it's working fine. I think you need give a better error message ^^! 
Thank you dlemstra!

**Comment by dlemstra** [comment]
I created an issue for that: https://github.com/dlemstra/Magick.NET/issues/321. Feel free to help 👍

**Comment by franva** [comment]
Hi @dlemstra  thanks for your great work! I tried and it works.
But my question is the same, I want to compress the image before it gets uploaded.
But the code I wrote is after uploading happened.

```
  var fileName = Path.Combine(filePath, $"{nameOnly}{ext}");
                    using (var stream = new FileStream(fileName, FileMode.Create))
                    {
                        await formFile.CopyToAsync(stream);
                        stream.Position = 0;
                        ImageOptimizer optimizer = new ImageOptimizer() {
                            OptimalCompression = true
                        };
                        optimizer.Compress(stream);
                    }
```

Can you please help?

Thanks

**Comment by dlemstra** [comment]
@franva This is probably something that should have been asked in a separate issue but I will answer it here. You cannot compress the image before it gets uploaded unless you have an application running on the user their machine.

**Comment by franva** [comment]
@dlemstra  agreed. thanks for your reply.
