### ISSUE TITLE
Improve error message when stream position is probably incorrect.

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/Magick.NET#321]
When a stream is at the end of the stream a better exception should be thrown. The current implementation is this:

```
 public static void IfNullOrEmpty(string paramName, Stream value)
{
    IfNull(paramName, value);

    if (value.CanSeek && value.Position == value.Length)
        throw new ArgumentException("Value cannot be empty.", paramName);
}
```

When the `Position` is higher than `0` a hint should be give to the developer that they probably forgot to reset the `Position` back to zero.

**Comment by dlemstra** [comment]
That assertion makes sure that the compression also works when the stream starts at position 42 so you should not change that. Testing if the position is at .Length is probably a better test for your patch.

**Comment by zachesposito** [comment]
OK thanks @dlemstra, PR incoming
