### ISSUE TITLE
Unable to read svg file format

### ISSUE THREAD

**Issue by BhushanShah** [dlemstra/Magick.NET#322]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am using magick.net libreary to read the image and it is throwing an exception while reading svg file format. Few svg file works but it doesn't work with the specifc image. You can find the image at below link:

[Sample SVG Image](https://drive.google.com/file/d/1PQsqKxv-6-2G1PJ3ut2rLaI6hTpPGNjj/view?usp=sharing)

Code snippet:

```
MagickReadSettings readSettings = new MagickReadSettings{Format = MagickFormat.Svg};
MagickImage objImage = new MagickImage(Bytes, readSettings);
```

Below is the exception detail:
`Exception Message: NonconformingDrawingPrimitiveDefinition `path' @ error/draw.c/DrawImage/4274`
```
Exception Stacktrace: at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(MagickSettings settings, Byte[] data, Int32 length)
   at ImageMagick.MagickImage.Read(Byte[] data, Int32 length, MagickReadSettings readSettings, Boolean ping)
```

### System Configuration

- Magick.NET version: 7.8.0
- Environment (Operating system, version and so on): Linux (docker)
- Additional information: microsoft/aspnetcore-build (docker base image)

**Comment by dlemstra** [comment]
I suspect that you uploaded an incorrect image because I can read the image with the MSVG coder without any problems. Under Windows librsvg will be used and that is a lot better than the default build in MSVG coder. On Linux the MSVG coder will be used unless you install inkscape.

**Comment by BhushanShah** [comment]
Sorry, I couldn't follow you. Can you please explain?

**Comment by dlemstra** [comment]
Inside the SVG coder there is a decision tree to decide which decoder will be used. If librsvg is linked that will be used. This is done on Windows, the macOS and Linux build don't use the librsvg coder. On those platforms either the command line tool inkscape or the internal MSVG coder will be used. When you install inkscape on your docker image you can probably read your image. I also tested your test image and I could read it without any issues on Linux so I suspect that you uploaded the wrong image to this post.

**Comment by dlemstra** [comment]
@BhushanShah Can we close this issue or do you need more help?

**Comment by BhushanShah** [comment]
Yes, you can close the issue. It started working after installing inkscape in docker image.
Thank you for your help.

**Comment by BhushanShah** [comment]
Hi @dlemstra ,

Even after adding inkscape in the docker image, I am still seeing a same issue in docker/linux. It works well in windows machine. Can you please provide some suggestion here?

You can find sample image [here](https://drive.google.com/file/d/1PQsqKxv-6-2G1PJ3ut2rLaI6hTpPGNjj/view?usp=sharing).

Also, when I try to use large images (~20-30MB), it is throwing below error.

```
Exception message: internal error: Huge input lookup
 `No such file or directory` @ error/svg.c/SVGError/2923
```
```
Stacktrace: at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(MagickSettings settings, Byte[] data, Int32 length)
   at ImageMagick.MagickImage.Read(Byte[] data, Int32 length, MagickReadSettings readSettings, Boolean ping)
```
You can find the sample image [here](https://drive.google.com/file/d/1hL3bXKl5l5a388ezPBfZsKuTlj1Pn8BF/view?usp=sharing).

**Comment by BhushanShah** [comment]
Hi @dlemstra,

Any suggestions on the above issue?

**Comment by dlemstra** [comment]
It looks like you are not using inkscape when you get that error message. Maybe the user does not have inkscape in it's path?

**Comment by BhushanShah** [comment]
HI @dlemstra ,

I have added below in my dockerfile which installs the Inkscape while creating the image of .net core service.

`RUN apt-get install -y inkscape`

Please let me know if anything else needs to be done. 
Appreciate your help.

**Comment by BhushanShah** [comment]
Hi @dlemstra,

Let me know if you need any more information.

Thanks,
Bhushan Shah

**Comment by dlemstra** [comment]
@BhushanShah This looks like an installation issue. Maybe you can get some more information with debug logging enabled? See the docs for an example.

**Comment by dlemstra** [comment]
@BhushanShah Were you able to resolve this issue?
