### ISSUE TITLE
Is it possible to invoke the "runtime" dll load with AnyCPU package ?

### ISSUE THREAD

**Issue by cannehag** [dlemstra/Magick.NET#323]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question
Hi, is it possible to, by code invoke the copy of the runtime dll's and load the correct architecture?
I would like to do this in an application warmup request instead of the first time the library is used.

**Comment by dlemstra** [comment]
The first time that you call a method of Magick.NET that needs a native method the initialization will happen. It might be a good idea to add an `Initialize` method that has no arguments to the `MagickNET` class.

**Comment by cannehag** [comment]
Until that method is added, can i call Initialize myself and with what argument ?

**Comment by dlemstra** [comment]
It might be better to just get the value of `MagickNET.Delegates` for now. You might also need to run some useless check on it to make sure the compiler does not optimize it away, not sure if it will do that though.

**Comment by dlemstra** [comment]
This feature has been added.
