### ISSUE TITLE
Disable TGA Compression

### ISSUE THREAD

**Issue by Lugiia** [dlemstra/Magick.NET#325]
I'm having an issue of disabling compression for TGA format.

Whenever I use image,Write, I want the image to be written without compression. I've already tried using CompressionMethod.NoCompression but that didn't seem to work.

```
Using image As New MagickImage(input)
    image.Format = MagickFormat.Tga
    image.Depth = bitDepth
    image.Settings.Compression = CompressionMethod.NoCompression
    image.Write(output)
End Using
```

Also my bad if the code looks awful, I'm not very used to it yet.

**Comment by dlemstra** [comment]
I just tried your code with the latest version of Magick.NET and I cannot reproduce your issue. How are you testing that the file is compressed?

**Comment by dlemstra** [comment]
@Lugiia Could your respond to my question?
