### ISSUE TITLE
Error: PDFDelegateFailed `The system cannot find the file specified. ' @error/pdf.c/ReadPDFImage/796

### ISSUE THREAD

**Issue by julpalt** [dlemstra/Magick.NET#326]
Hello
I am getting error PDFDelegateFailed `The system cannot find the file specified. ' @error/pdf.c/ReadPDFImage/796 after deploying codes to the web

1.	Created ASP.NET Core Razor Pages web site
2.	Added nuget: Install-Package Magick.NET-Q16-AnyCPU -Version 7.8.0
3.	Added Index page with simple functionality:
a.	Upload attached pdf file to web server
b.	Process pdf file with ImageMagick:
            Stream stream = Request.Form.Files[0].OpenReadStream();

            MagickReadSettings settings = new MagickReadSettings();
            settings.Density = new Density(300, 300);
            MagickImageCollection images = new MagickImageCollection();

            try
            {
                images = new MagickImageCollection(stream);
                ErrorMsg = "Program is working!";
            }
            catch (Exception ex)
            {
                ErrorMsg = ex.Message;
            }

4.	Tested it on my computer - it runs without any problem
5.	Web Deployed project to www.pdf.zyvion.net 
6.	Got error 
PDFDelegateFailed `The system cannot find the file specified. ' @error/pdf.c/ReadPDFImage/796

Thank you!
Julia
[PrintedBillsWithPOM_201809081624337867.pdf](https://github.com/dlemstra/Magick.NET/files/2425242/PrintedBillsWithPOM_201809081624337867.pdf)

**Comment by dlemstra** [comment]
Did you install Ghostscript on your server? You need this to read PDF files there. It is also possible that you will require a commercial license to use it there but I don't know for sure.

**Comment by julpalt** [comment]
Dirk;
I am using SmarterASP Web hosting provider. I don't have physical access to
the server.  How can I check or install Ghostscript with hosting provider?

**Comment by dlemstra** [comment]
If it doesn't work it is very likely that it is not installed. In the documentation you can find an explanation on how to use Ghostscript without installing it on the server.

**Comment by julpalt** [comment]
thanks!

**Comment by dlemstra** [comment]
Feel free to ask more questions in the issue if you need more help but I will close it for now.
