### ISSUE TITLE
Distorted Image when resizing PNG with transparency

### ISSUE THREAD

**Issue by whereiskyleb** [dlemstra/Magick.NET#327]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question
Hi, 
Here's the following snippet of code that I'm using to resize my images.

```
using (var resizedImage = new MagickImage(originalImage))
{
    resizedImage.Strip();
    resizedImage.Format = resizedImageFormat;

    var resizedGeometry = new MagickGeometry()
                            {
                                Width = resizedImageWidth,
                                Height = resizedImageHeight,
                                IgnoreAspectRatio = !maintainAspect
                            };
                                
    if (resizedImage.Format.IsPng())
    {
        resizedImage.BitDepth(resizedImageBitDepthQual);
    }
    else
    {
        resizedImage.Quality = resizedImageBitDepthQual;
    }

    resizedImage.Resize(resizedGeometry);
    resizedImage.Write(resizedImageStream);
}
```

This code works great for every other image that has been requested through my image api, but when we've started putting PNG with transparency through this code the image comes out all distorted and pixelated.  We are passing IgnoreAspectRatio = false, so the resize operation would respect the aspect ratio of the original image.

I'm kinda scratching my head wondering what i'm missing.   Any ideas?

Thanks,

Kyle

**Comment by dlemstra** [comment]
Are you using the latest version of Magick.NET and which operating system are you running this on? Thanks for following the issue template and I just updated that to include the Magick.NET version and environment you are running Magick.NET on.

Would it be possible to create a complete sample that demonstrates your issue? I suspect your output is pixelated because you are reducing the bit depth.

**Comment by whereiskyleb** [comment]
Your suspicion was dead on.  Part of the API's input was assuming that the bit depth for a PNG would be between 8 and 24 bit, but the source was 32 so no matter what you put in it would alter the bit depth.  Once I refactored my code to remove the assumption the image cleaned up.  

Thanks for your help!

Kyle
