### ISSUE TITLE
Win Server 2012, .NET Core 2.1, Q8-x64:  The specified module could not be found.

### ISSUE THREAD

**Issue by imukai** [dlemstra/Magick.NET#328]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
Windows Server 2012 Standard (x64) w/ .Net Core 2.1 installed

- Magick.NET version:
- Magick.NET-Q8-x64 and -AnyCPU

### Question
I apologize if this turns out to be something stupid but I've exhausted my stupidity on this one.

After developing locally (Win 10, VS 2017) and successfully, I'm now trying to get Magick to work on my server.  This is the first DLL component to fail on the server.  I first used the Q8-x64 nuget package and once I got this error, I switched to the -AnyCPU version to see if it made a difference.  It did not.

I'm logging this exception.  I've read a few similar issues posted here but they seem to be for other platforms.  From reading the docs it suggests regular old boring Windows should work as it sits.

```
The type initializer for 'NativeMagickSettings' threw an exception. System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q8-x64.Native.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.NativeEnvironment.Initialize()
   at ImageMagick.Environment.Initialize()
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor()
```

Note that the DLL it can't seem to find is sitting in the root directory of the web space along with the rest of the other components.

**Comment by dlemstra** [comment]
Are the Magick.NET-Q8-x64.dll and Magick.NET-Q8-x64.Native.dll in the same folder?

**Comment by imukai** [comment]
I misrepresented my final sentence in my sleep deprived state.  Magick.NET-Q8-x64.dll was there, but .Native was not there.  It's also not on my local anywhere (except inside the Nuget packages) and my local runs ok.  Odd.

After reading your comment and realizing the .Native one was not there, I extracted the .Native from Nuget and dropped it on the server and that error is now gone.  Any idea why it didn't make it there?

Anyway, that error gone, I'm now getting a new one when trying to save a file:

```
WriteBlob Failed `E:\Images\GhYoIKQlz0aopPBFOSK1Ag.Png' @ error/png.c/MagickPNGErrorHandler/1713
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.MagickImage.NativeMagickImage.WriteFile(MagickSettings settings)
```

That folder has Everyone / Full Control on it so I'll have to do some research now.  I suppose you can close this issue and I can open a new one if I can't resolve it.

**Comment by imukai** [comment]
Nevermind - there was a configuration issue.  Server has no E:\ drive.  Corrected that and things seem to be working fine now.

Sorry for any hassle.   I'll close this now.  :)
