### ISSUE TITLE
Add Stream support to the ImageOptimizers

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/Magick.NET#33]
The ImageOptimizers now only support optimizing a file on disk. A new overload should be added that allows the optimization of a stream. The stream should support reading, writing and seeking because the original stream should be overwritten with the new optimized image. Because we only optimize JPG/PNG and GIF we don't need to pass in the format because we can determine that from reading the first few bytes.

**Comment by VladimirRybalko** [comment]
Hi @dlemstra . I'd like to start with it. The Stream supporting is a very critical for my project.
However, I don't know how could I check an image format by reading a few first bytes.
Do you have a solution in project or may be you know some algorithms?

**Comment by dlemstra** [comment]
You could use the MagickImageInfo to determine the image format. The tricky part is the jpeg optimization because you will need to take a step into unmanaged code (read c code) You could help my by doing the first steps and get it to work with the PngOptimizer. I have a couple days off next week so I might be able to do the jpeg part myself.

**Comment by VladimirRybalko** [comment]
Great. I think I add as maximum code as I could. After that I create a draft PR. So you'll have ability to add complicated C code later. Thanks for your help.

**Comment by stefanb** [comment]
Please note that even working with streams will still require whole image in the memory at once (or even multiple copies, if `ImageOptimizer.OptimalCompression = true`)

An overload `ImageOptimizer.LosslessCompress(MagickImage)` could also be useful in the context of imagemagick image manuipulation

**Comment by dlemstra** [comment]
An overload with MagickImage does not make sense to me. The optimizer tries to reduce the size of an existing image on disc or in blob storage. For a JPEG image it reduces the size without decoding the pixels. The image is not loaded as a MagickImage and the optimization is done with some tricks inside the jpeg library. Could you clarify why that overload would be useful?

**Comment by dlemstra** [comment]
@VladimirRybalko I have made the first steps. You could still help with the PngOptimizer and ImageOptimizer. I will do the JpegOptimizer myself.

**Comment by VladimirRybalko** [comment]
@dlemstra thanks you.
However I have some problems with build a solution. I can't install Windows 8 SDK on my machine. So I'm not be able to build a project. 
I could commit Png and Gif optimizer without any testing, but I think it's not a good idea.
What do you think?

**Comment by dlemstra** [comment]
@VladimirRybalko Have you followed these instructions: https://github.com/dlemstra/Magick.NET/blob/master/Building.md? I would advise you to use the precompiled .lib files instead of building ImageMagick 7 yourself. I need to make that more clear in the documentation.

**Comment by dlemstra** [comment]
@VladimirRybalko I wonder if it might be easier to optimize the JPEG file by first writing the stream to disk for now. Do you think that would be an option? I can always fix that in the future.

**Comment by dlemstra** [comment]
@VladimirRybalko Figured out how I could implement the optimization in the JPEG optimizer :) Turned out to be easier than I though. Do you still want to help out with the PNG optimizer?

**Comment by VladimirRybalko** [comment]
@dlemstra I still want to help you with the PNG optimizers.
However I'm too busy now. There are so many works and so less time.
I will try to have a look at PNG soon.

**Comment by dlemstra** [comment]
I had some time today to work on this again and I already implemented this. Feel free to help me with one of the other issues when you have time 👍 

I will try to publish a new release that includes support for compressing streams this weekend.

**Comment by VladimirRybalko** [comment]
Oh. Thanks you so much.
