### ISSUE TITLE
Magick.Net font recognition when convert SVG to PNG

### ISSUE THREAD

**Issue by NarekMayilyan** [dlemstra/Magick.NET#330]
### System Configuration
I'm using c# .net core 2.1

- Magick.NET version Magick.NET-Q16-AnyCPU 7.6:
- Windows 10 OS:

### Question
When converting an SVG file to PNG, the text font is not recognized. How can I make Magick.NET recognize the fonts installed on my PC
`           

            byte[] pngBytes;
            
            var settings = new MagickReadSettings

            {

                Format = format,

                BackgroundColor = MagickColors.Transparent,

                Width = width,

                Height = height

            };

            var bytes = //some bytes

            using (var magickImage = new MagickImage(bytes, settings))

            {

                pngBytes = magickImage.ToByteArray(MagickFormat.Png32);

            }
`

**Comment by dlemstra** [comment]
Can you share a sample image so I can get a bit more info?

**Comment by NarekMayilyan** [comment]
https://files.fm/f/waetshxu

**Comment by dlemstra** [comment]
It looks like an issue with the font in your css:

```css
.st0{font-family:'Algerian';}
```

It works when I change it to this:
```css
.st0{font-family:Algeria;}
```

I could only find a free font called Algerian so besides removing the `'` I also had to remove the last `n` from the font name. But I think you just need to remove the `'`.

**Comment by NarekMayilyan** [comment]
thanks for the help. I have one more question, does the package recognize all the fonts on my computers or only those listed in Magick.Net?

**Comment by NarekMayilyan** [comment]
and is it possible in the future to recognize the font from the signs of '?

**Comment by dlemstra** [comment]
The font listed in Magick.NET are the fonts that are installed on your system. And I don't know if using `'` instead of `"` should be officially supported. We use a third party library called librsvg to read the svg images and I don't know if they will add support for this in a future release.

p.s. There is an edit button so you can edit a comment instead of posting a new one.

**Comment by NarekMayilyan** [comment]
Thank you very mush for help
