### ISSUE TITLE
How to translate "-define filter:sigma=2.5" into magick.net?

### ISSUE THREAD

**Issue by TJYSunset** [dlemstra/Magick.NET#332]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Q8-AnyCPU 7.8.0
- Environment (Operating system, version and so on): Windows 10, .NET Framework 4.7.2

### Question

https://www.imagemagick.org/Usage/blur/ *Large Blur using Resize* mentioned the following snippet:
```cmd
convert rose: -filter Gaussian -resize 50% \
        -define filter:sigma=2.5 -resize 200%  rose_resize_5.png
```

So according to [the docs](https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Defines.md), I tried the following code (sigma = 48 so it should be easy to judge with human eye):

```c#
image.Settings.SetDefine(/* ??? */, "sigma", $"{sigma / 2}");
image.Resize(new Percentage(200));
```
no such `MagickFormat` exist, at least none beginning with letter f.

```c#
image.Settings.SetDefine("filter:sigma", $"{sigma / 2}");
image.Resize(new Percentage(200));
```
not working

```c#
image.Settings.SetDefine("filter", $"sigma={sigma / 2}");
image.Resize(new Percentage(200));
```
neither does this

```c#
image.Settings.SetDefine("sigma", $"{sigma / 2}");
image.Resize(new Percentage(200));
```
not working just as expected

What is the correct way to define `filter:sigma`?
Thanks in advance.

**Comment by dlemstra** [comment]
You will need to set the `FilterType` of the image to `FilterType.Gaussian`. And the value should be stored as an artifact on the image: `image.SetArtifact("filter:sigma", yourValue);`

**Comment by TJYSunset** [comment]
That worked! Thanks.
This should be documented somewhere though.
