### ISSUE TITLE
Unable to change delegate command for ghostscript on the fly

### ISSUE THREAD

**Issue by nauticalcoder** [dlemstra/Magick.NET#337]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.4.2
- Environment (Operating system, version and so on): Windows Azure function

### Question
In order to change how ghostscript is performing CMYK color conversions, it is necessary to change the delegate for **ps:cmyk**.  Is there a way to change the delegate being used without modifying the delegates.xml file in the solution and then rebuilding and deploying our own version of Magick.NET?  We are currently pulling it into the project via Nuget.

**Comment by dlemstra** [comment]
There is some documentation on how you can do that here: https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Initialization.md. Using the `ConfigurationFiles` class is probably the easiest method but there are other options.

**Comment by nauticalcoder** [comment]
Even after following the information there, Imagemagick seemed to be completely ignoring my delegates.xml changes.  I even altered the ghostscript command to be completely invalid, but it still executed flawlessly so I don't think my delegates were even being used.

It turns out I don't need to change the delegates, so I haven't pursued this even further.

I am however still struggling to figure out a way to reproduce a specific Imagemagick sequence.  I need to be able to set the colorspace as the first step prior to opening the source file.  Example:
This works: convert -verbose -colorspace sRGB summerstime.ai  summersTime.png 
This does not worK: convert -verbose summerstime.ai -colorspace sRGB summersTime.png 
I have tried the following with Magick.Net:
        `  var originalImage = new MagickImage();
            originalImage.ColorSpace = ColorSpace.sRGB;
            originalImage.Read(assetStream);
            var thumbnailImage = new MagickImage(originalImage);
            thumbnailImage.Format = MagickFormat.Png;
            var thumbnailGeometry = new MagickGeometry(45);
            thumbnailImage.Thumbnail(thumbnailGeometry);`
This does not have the desired effect and seems to be mirroring the behavior of specifying the colorspace after the source file name.  Is there a way to reproduce the working Imagemagick command with Magick.Net?

**Comment by dlemstra** [comment]
Are you sure that your delegates.xml changes are ignored? 

And to answer your other question. You will need to set the `ColorSpace` of the `MagickReadSettings` to use that setting when you read the image.

**Comment by nauticalcoder** [comment]
Thanks,
Passing in an instance of MagickReadSettings did the trick.  I hadn't noticed before that it inherited from MagicSettings and included all of those properties.

In regards to the delegates, I can't be 100% sure they were ignored, but to test I did changed the device to something totally invalid which caused an error when run from the command line, and it performed the conversion without complaining.  Even though I don't actually need to do this anymore, I'll try to whip up a test to confirm what is and is not happening.

**Comment by dlemstra** [comment]
Can we close this issue @nauticalcoder?

**Comment by nauticalcoder** [comment]
Yes.  I haven't gotten back to trying out your suggestions, as I ended up not needing override the delegates.
