### ISSUE TITLE
System.Drawing requirements?

### ISSUE THREAD

**Issue by stefanak-michal** [dlemstra/Magick.NET#339]
Hi.
I wanted to use your solution but I have problem problem. Because on my runtime system is not available System.Drawing.Bitmap and you are using it. How can I avoid that? Do you have version without calling this requirement?

I can't add System.Drawing.dll to application, because there is already some special shorten version of it and it's impossible to override it.

**Comment by dlemstra** [comment]
Which version of .NET are you using? And on what kind of platform are you deploying this?

**Comment by stefanak-michal** [comment]
Runtime 4.x and API compatibility level .Net 2.0. Deploy target platform is Windows, but I'm trying to implement it into Unity engine.

**Comment by stefanak-michal** [comment]
You are right. The problem was about this setup. I changed it and it works. Thank you so much.
