### ISSUE TITLE
Getting Could not load file or assembly 'Magick.NET-Q16-AnyCPU for Release DLL

### ISSUE THREAD

**Issue by DeveBj** [dlemstra/Magick.NET#343]
Hi All,
Am having a windows Service which run locally without any issues, I made a release build, and I got all the Release dll for that service, I tried deploying it in AWS's IIS server running there am facing a issue and it is been recorded in my log file, which is shown below I don't know what is the reason and what causes is i have tested the dll's in my own system which is working fine but in AWS server IIS it does not, please do help me to resolve this issue.

**Log**

Timestamp: 10/19/2018 4:09:40 AM
 Message: HandlingInstanceID: fsajdh388-e7ewr-4sd32-aewr63e-ewrsf234433
An exception of type 'System.Exception' occurred and was caught.
----------------------------------------------------------------
10/19/2018 04:09:40
Type : System.Exception, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Could not load file or assembly 'Magick.NET-Q16-AnyCPU, Version=7.9.0.0, Culture=neutral, PublicKeyToken=456582udfu6ertfa91ec' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 
Source : MyBaseService
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Boolean ProcessMyService(IntellaLend.Model.CustomConfig, Int64, Int64, System.String, System.String, System.String)
HResult : -2146233088
Stack Trace :    at MyBaseService.MyImportServicecs.ProcessMyService(CustomConfig CustomConfigObj, Int64 _CustomConfigID, Int64 _dealID, String _vinID, String _loanType, String _serviceType)
   at MyProject.ImportAPI.Controllers.ImportController.ProcessMyService(Import _ImportData, String tenantschema)

Additional Info:

MachineName : WIN-ajjhd8436743
TimeStamp : 10/19/2018 8:09:40 AM
FullName : Microsoft.Practices.EnterpriseLibrary.ExceptionHandling, Version=6.0.0.0, Culture=neutral, PublicKeyToken=null
AppDomainName : /LM/W3SVC/4/ROOT/ImportAPI-2-1318441014358734080
ThreadIdentity : APIResponse
WindowsIdentity : IIS APPPOOL\trialinit
	Inner Exception
	---------------
	Type : System.IO.FileLoadException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b7345788354hf34e089
	Message : Could not load file or assembly 'Magick.NET-Q16-AnyCPU, Version=7.9.0.0, Culture=neutral, PublicKeyToken=20048dsf433989sc' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
	Source : CustomEntBlocks.UtilsBlock
	Help link : 
	FileName : Magick.NET-Q16-AnyCPU, Version=7.9.0.0, Culture=neutral, PublicKeyToken=200327ukjsdfjkg1ec
	FusionLog : WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

	Data : System.Collections.ListDictionaryInternal
	TargetSite : Byte[] GetJpegFromPDF(Byte[], Int32)
	HResult : -2146234304
	Stack Trace :    at CustomEntBlocks.UtilsBlock.ImageUtilities.GetJpegFromPDF(Byte[] fileContents, Int32 pageNumber)
	   at MyProject.LoanData.ImportDataAccess.InsertImagesToDB(CustomConfig CustomConfigObj, DBConnect db, String ImageMaxHeight, String ImageMaxWidth, Int64 loanID)
	   at MyProject.LoanData.ImportDataAccess.InsertDDetails(CustomConfig CustomConfigObj, String ImageMaxHeight, String ImageMaxWidth, Int64 loanID)
	   at MyBaseService.ImportServicecs.ProcessMyService(CustomConfig CustomConfigObj, Int64 _CustomConfigID, Int64 _dealID, String _vinID, String _loanType, String _serviceType)

**Comment by DeveBj** [comment]
@dlemstra could you please help me in this regard what version actually i need ?

**Comment by DeveBj** [comment]
am using 'Magick.NET-Q16-AnyCPU" Dll which I installed from Nuget

**Comment by dlemstra** [comment]
Did you check if the version on your server is the same one as the version on your machine?

p.s. There is an edit button that you can use to edit your message.

**Comment by DeveBj** [comment]
@dlemstra  sorry I forget about the edit button, the same dll was deployed in the server which is currently deployed and working in my local machine

**Comment by dlemstra** [comment]
Can you clarify when you closed this issue @DeveBj?
