### ISSUE TITLE
Is it Possible to get Deskew angle

### ISSUE THREAD

**Issue by M4nju** [dlemstra/Magick.NET#344]
Hi there,

i am rigth now playing around with the deskew function of the MagickImage. My Problem is, i want to get the deskew angle which will be used in the Rotation process, to rotate the Image myself. 

In ImageMagick this is possible (See: http://studio.imagemagick.org/discourse-server/viewtopic.php?t=34156&p=156905). Is there any way to use this method also with magick.net? I did not found a way to use defines to get the deskew angle.

Thanks for any help 

Regards

Manju (David)

**Comment by dlemstra** [comment]
You should be able to get the value with `image.GetArtifact("deskew:angle")`.

**Comment by M4nju** [comment]
Oh okay, never would have come to this solution xO. Thanks for the fast help. I will try it tomorrow and than give feedback.

**Comment by M4nju** [comment]
Okay works perfect thanks. Important to know is the thing that is also mentioned in the link i posted. You need to use the Deskew function before acessing the value deskew:angle. Else it will only return null.
