### ISSUE TITLE
MagickDelegateErrorException

### ISSUE THREAD

**Issue by cannehag** [dlemstra/Magick.NET#345]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU 7.9.0
- Environment (Operating system, version and so on): Azure App Services

### Question
We are getting some exceptions when reading image files. What is the reason for these ?
ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result):39
ImageMagick.MagickImage+NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller):58
ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping):143

FailedToExecuteCommand `"gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dFirstPage=1 -dLastPage=1 "-sOutputFile=D:/local/Temp/magick-26016pxioqiWejlUr%d" "-fD:/local/Temp/magick-26016rVz2rnbG3Aqg" "-fD:/local/Temp/magick-26016y0dQz6G1SWiT"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/475

**Comment by dlemstra** [comment]
It appears that you are trying to read a PDF file. You need to also copy Ghostscript to your application. Documentation on how to configure Magick.NET for that can be found here: https://github.com/dlemstra/Magick.NET/tree/master/Documentation

**Comment by cannehag** [comment]
Wow, just found a bug in our system where we have a user who uploaded a pdf as his profile image :D

Thank you!
