### ISSUE TITLE
Convert Image to PDF

### ISSUE THREAD

**Issue by dania-vera** [dlemstra/Magick.NET#348]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm working on a project and I need to convert PDF to image, and then convert the image to PDF. I'm using your code. The first part works good --- PDF to Image, but the second doesn't work when the image just has text. The PDF is created but when you open it, you  get an error and says --- Insufficient data for an image. 
### Steps to Reproduce

I'm attaching you the test.
### System Configuration

I'm working on C# and I have all the packages necessary for the process --- I was able to convert the PDF in an image.  
- Magick.NET version: Q8 64bits
- Environment (Operating system, version and so on): Windows 10
![sample page2](https://user-images.githubusercontent.com/44672523/47853678-440c9480-ddbe-11e8-8691-56d8478bf61b.png)
![sample page3](https://user-images.githubusercontent.com/44672523/47853685-48d14880-ddbe-11e8-87eb-61ba0af679aa.png)
[TwoPage.pdf](https://github.com/dlemstra/Magick.NET/files/2538610/TwoPage.pdf)

- Additional information:

**Comment by dlemstra** [comment]
How are you converting the image? And are you aware that you are creating a HUGE pdf when you convert text to image and then put that image in the PDF file? This might not be the right tool for what you are trying to do. And are you aware that you need a commercial license when you use Ghostscript?

**Comment by dania-vera** [comment]
I'm using the code that you provide as example. I convert a PDF to an image and then the convert the same image to PDF. If the original PDF has images your code works perfectly but If the original PDF has just text, it doesn't work. Something interesting, if you draw a pixel blue in your image, then you will succeed and you will get the PDF. 
I'm aware about the license, but thanks.

**Comment by dlemstra** [comment]
Is `TwoPage.pdf` your input or output?

**Comment by dania-vera** [comment]
TwoPage.pdf is the output. I took a PDF, I converted it to images. The two images above is the result and then I tried to convert the images to PDF (reverse process), and I got as result the TwoPage.pdf

**Comment by dlemstra** [comment]
Could you share the input image so I can try to reproduce your issue?

**Comment by dania-vera** [comment]
![sample page2](https://user-images.githubusercontent.com/44672523/47913097-9a8ad900-de79-11e8-995a-29d2e1af7686.png)
![sample page3](https://user-images.githubusercontent.com/44672523/47913101-9e1e6000-de79-11e8-9302-e39f29054221.png)

**Comment by dlemstra** [comment]
I mean the input PDF file.

**Comment by dania-vera** [comment]
My mistake, this was something that I downloaded just to prove the examples.
[Sample.pdf](https://github.com/dlemstra/Magick.NET/files/2542305/Sample.pdf)

**Comment by dlemstra** [comment]
I get the correct output image with this code:

```C#
using (var images = new MagickImageCollection("Sample.pdf"))
{
    images.Write("Output.pdf");
}
```

And your TwoPage.pdf file looks correct. Can you clarify what doesn't work?

**Comment by dania-vera** [comment]
Yes, you got three images as result. Now using the image2 and image3 that you got, do this:
using (MagickImageCollection collection = new MagickImageCollection())
{
    collection.Add(new MagickImage("Image2.jpg"));
    collection.Add(new MagickImage("Image3.jpg"));
    collection.Write("Output.pdf");
}

**Comment by dlemstra** [comment]
When I open the TwoPage.pdf file I see the text and it works perfectly for me. I use Chrome to view it, maybe your PDF viewer has some issues?

**Comment by dania-vera** [comment]
I'm using the last version of Adobe Acrobat and I can't see the Pdf. And, it's true, I  tried with Chrome and I was able to see it, but why Adobe Acrobat can't open the Pdf. Have you tried with Adobe? Anyway, I think you can close this issue. Thanks

**Comment by dlemstra** [comment]
I don't have Adobe installed but it looks like the PDF is created correctly. Maybe the problem is the transparent background? Do you see a completely black image? Setting the background color to white in the `MagickReadSettings` might resolve your issue.

**Comment by dania-vera** [comment]
Yes, I believe the same, this is why, when I draw something red in the image, I could see the Pdf with Adobe. Ok, Thanks for all your help. If this works, I believe I can use it.

**Comment by okonca** [comment]
Hi  dania-vera
Have you solved the issue? I have exactly the same problem. Color page are created successfully but all grayscale page are created with pink background and I am having the same error when I open the file with acrobat reader. 

Thanks

**Comment by dania-vera** [comment]
@okonca  Could be the Adobe's version? I used long time ago and haven't used this library again but this works for me at the moment.  

		private void SaveImageAsPdf( string filename, string outputPath)
		{
			using (MagickImageCollection imagesToPdf = new MagickImageCollection())
			{
                             imagesToPdf.Add(new MagickImage(filename));
			     imagesToPdf.Write(outputPath);
		      }
                    imagesToPdf.Dispose();
	      } 

Hope this helps you !

**Comment by okonca** [comment]
Thank you dania-vera, I noticed that the problem occurs when extracting binary and grayscale image from original document as rgb image
