### ISSUE TITLE
when deal with png image in latest version, throw exception : can not find entry point MagickColor_IsCMYK_Set 

### ISSUE THREAD

**Issue by runtop** [dlemstra/Magick.NET#349]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

using latest version 7.9.0.1( also with version 7.70 ), when deal with png image, it will throw exception : can not find entry point MagickColor_IsCMYK_Set ,
but the code that below will do work  in version 7.4.2

is there change somethen in new version?

### Steps to Reproduce

` Stream stream1 = Utility.HttpGet1(avatar); `
` using (MagickImage img_avatar = new MagickImage(stream1)) {`
`                        img_avatar.Resize(270, 270);`
`                        using (MagickImage img_mask = new MagickImage(MagickColors.Transparent, 270, 270)) {`
`                            new Drawables()`
`                               .FillColor(MagickColors.Black)`
`                               .Circle(135, 135, 135, 0)`
`                               .Draw(img_mask);`
`                            img_avatar.Composite(img_mask, CompositeOperator.CopyAlpha);`
`                        }`
`                        img_qr.Composite(img_avatar, 165, 165, CompositeOperator.Over);`
`                    }`

the stream1 is a PNG image ,and it's backgroud color is transparent.

and StackTrace:

 在 ImageMagick.MagickColor.NativeMethods.X64.MagickColor_IsCMYK_Set(IntPtr instance, Boolean value)
   在 ImageMagick.MagickColor.CreateNativeInstance()
   在 ImageMagick.MagickSettings.NativeMagickSettings.set_BackgroundColor(MagickColor value)
   在 ImageMagick.MagickSettings.CreateNativeInstance()
   在 ImageMagick.MagickImage.NativeMagickImage..ctor(MagickSettings settings)
   在 ImageMagick.MagickImage..ctor()
   在 ImageMagick.MagickImage..ctor(Stream stream)
   在 snap.service.QrcodeService.GetQrcode(String root, String scene, String page, Int32 width, Boolean is_hyaline, String avatar) 

### System Configuration

- Magick.NET version:7.9.0.1
- Environment (Operating system, version and so on):window2012  IIS 8.5 .net4.0
- Additional information:

**Comment by dlemstra** [comment]
Are you sure that the correct version of the `.Native.dll` is used on the machine that you are running this on?

**Comment by runtop** [comment]
> Have you checked that the correct version of the `.Native.dll` is used on the machine that you are running this on?

sorry, i do not use .native.dll,  just only use net40's dll

**Comment by dlemstra** [comment]
What is the exact version of Magick.NET that you are using?

**Comment by runtop** [comment]
> What is the exact version of Magick.NET that you are using?

my web api (base on .net4.6) using 7.4.2 and  everything is work fine, today I upgrade magick.net from nuget to version 7.9.0,1, then it throw the exception .

**Comment by runtop** [comment]
> Have you checked that the correct version of the `.Native.dll` is used on the machine that you are running this on?

then I copy both  Magick.NET-Q8-AnyCPU.dll and Magick.NET-Q8-x64.Native.dll to the web's bin directory, and then it is working . thks
