### ISSUE TITLE
Is it possible to keep everything in memory?

### ISSUE THREAD

**Issue by laukotomi** [dlemstra/Magick.NET#354]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU v7.9.0.1
- Environment (Operating system, version and so on): Windows 10

### Question

Hello! I have been searching a lot about this, but couldn't find a proper answer.
I have an app which resizes/crops images and what I experienced is that after running more than 3 requests in parallel processing gets slow, because it starts using temp files on the disk.
However I still have a lot of free memory and the app uses only about 6-700Mb. I checked my code a lot of times and I dispose everything I can, so memory leak is not a problem. (this should be something similar to this: https://www.imagemagick.org/discourse-server/viewtopic.php?t=33811)

I have also tried to set different policy.xml (area, map, memory, etc.) values and set ResourceLimits.Memory to a very big value, but it didn't help.

Can it be a problem that I am running the app is a 32bit application?
Or is there any other option that I should try?

What I would like to achive is something like setting ResourceLimits.Disk to 0 and then try out how many requests I can run in parallel without exceeding the memory resources. But after setting it to 0 I get "cache resources exhausted" error.

**update**
Here are some logs I could manage to catch:

> 2018-11-22T15:08:29+01:00 0:15.403 23.328u 7.0.8 Cache func.exe[29388]: cache.c/OpenPixelCache/3795/Cache
  open [0] (Heap Memory, 4344x2896x3 35.9923MiB)
2018-11-22T15:08:29+01:00 0:15.403 23.328u 7.0.8 Resource func.exe[29388]: resource.c/AcquireMagickResource/250/Resource
  Width: 8688P/10000000P
2018-11-22T15:08:29+01:00 0:15.404 23.328u 7.0.8 Resource func.exe[29388]: resource.c/AcquireMagickResource/250/Resource
  Height: 2896P/10000000P
2018-11-22T15:08:29+01:00 0:15.404 23.328u 7.0.8 Resource func.exe[29388]: resource.c/AcquireMagickResource/250/Resource
  ListLength: 1/18.4467E
2018-11-22T15:08:29+01:00 0:15.404 23.328u 7.0.8 Pixel func.exe[29388]: pixel.c/SetPixelChannelMask/6290/Pixel
  [07ffffff]
2018-11-22T15:08:29+01:00 0:15.405 23.328u 7.0.8 Pixel func.exe[29388]: pixel.c/LogPixelChannels/6174/Pixel
  [07ffffff]
2018-11-22T15:08:29+01:00 0:15.405 23.328u 7.0.8 Pixel func.exe[29388]: pixel.c/LogPixelChannels/6271/Pixel
    0: red (update)
2018-11-22T15:08:29+01:00 0:15.406 23.328u 7.0.8 Pixel func.exe[29388]: pixel.c/LogPixelChannels/6271/Pixel
    1: green (update)
2018-11-22T15:08:29+01:00 0:15.406 23.328u 7.0.8 Pixel func.exe[29388]: pixel.c/LogPixelChannels/6271/Pixel
    2: blue (update)
2018-11-22T15:08:29+01:00 0:15.406 23.328u 7.0.8 Resource func.exe[29388]: resource.c/AcquireMagickResource/250/Resource
  Area: 25.1604MP/18.4467EP
2018-11-22T15:08:29+01:00 0:15.407 23.328u 7.0.8 Resource func.exe[29388]: resource.c/AcquireMagickResource/357/Resource
  Memory: 71.9846MiB/935.8MiB/16EiB
2018-11-22T15:08:29+01:00 0:15.407 23.328u 7.0.8 Resource func.exe[29388]: resource.c/AcquireMagickResource/357/Resource
  Disk: 71.9846MiB/0B/0B
2018-11-22T15:08:29+01:00 0:15.407 23.328u 7.0.8 Exception func.exe[29388]: cache.c/OpenPixelCache/3873/Exception
  cache resources exhausted `'

**Comment by dlemstra** [comment]
You are using `935.8MiB`, are you sure you have disposed all the resources? And it looks like you are hitting the 32bit memory limit. I would advise you to switch to 64-bit.

**Comment by laukotomi** [comment]
Well I am processing 8688x5792 size jpg images which are about 9MB.
My code looks like below. It starts processing an image, it calculates some tiles which should be cropped from the image, then it resizes the image (half of its size) and crops some other tiles and so on. So it resizes the image usually 13 times. Calculations only use image.Width and image.Height, so nothing to dispose there in my opinion. And if I process many-many images, but only 3 in parallel then the app still uses the same amount of memory, so it is stable.

>              var results = new List<byte[]>();

                using (var image = new MagickImage(source))
                {
                    // calculation for level (using only int / float variables)

                    while (level >= 0)
                    {
                        // calculations for tileCountX and tileCountY (only int / float)

                        for (var x = 0; x < tileCountX; x++)
                        {
                            for (var y = 0; y < tileCountY; y++)
                            {
                                // calculations for x1, x2, y1, y2
                                using (var tileImage = image.Clone(x1, y1, x2 - x1, y2 - y1))
                                using (var stream = new MemoryStream())
                                {
                                    tileImage.Format = MagickFormat.Jpeg;
                                    tileImage.Quality = quality;
                                    tileImage.Write(stream);
                                    stream.Position = 0;

                                    results.Add(stream.ToArray());
                                }
                            }
                        }

                        level--;
                        if (level >= 0)
                        {
                            var geometry = new MagickGeometry(levelSizes[level].Width, levelSizes[level].Height);
                            geometry.IgnoreAspectRatio = true;
                            image.Resize(geometry);
                        }
                    }
                }

                return results;

**Comment by laukotomi** [comment]
Thanks, running the app on 64bit worked! ;) It still doesn't use much more memory than the 32bit one (about 1 - 1.5Gb), so I still don't understand what is the problem in 32bit mode, but it's ok for now.
