### ISSUE TITLE
Crop to Aspect Ratio with Offset

### ISSUE THREAD

**Issue by 2ji3150** [dlemstra/Magick.NET#358]
Trying to crop a maximum image with the aspect ratio with offset

which this:

` magick convert intput.jpg -gravity center -crop 1:1+x+y output.png`

with magick.net

`image.Crop(new MagickGeometry("1:1+x+y"), Gravity.Center)`

not work

**Comment by dlemstra** [comment]
What are you using as the value for `x` and `y`?

**Comment by 2ji3150** [comment]
Forexample `0` and `0`  it would be failed.
looks like it only handle `"wxh+x+y"` and `"x(ratio):y(ratio)"` in magick.Net

**Comment by dlemstra** [comment]
Thanks for the bug report @2ji3150. This will be resolved in the next release.

**Comment by 2ji3150** [comment]
You're welcome. Thanks for the wonderful work. @dlemstra 
NOTICE that I have opened another [ralative issue](https://github.com/ImageMagick/ImageMagick/issues/1410#issuecomment-445483115) in mageMagick Project.

Maybe they'll change something. (under discussing)
