### ISSUE TITLE
ImageMagick doesn't use Embedded color profile of image

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#36]
Thanks for the very useful lib.

How to apply automatically embedded color profile of an image?
I have an image, when I use:
```
using (var img = new MagickImage(path))
{
      bmp = img.ToBitmap();
}
```
the color of image displayed incorrectly:
![image](https://cloud.githubusercontent.com/assets/3154213/22180870/94f04554-e0b8-11e6-9ab2-f0ccc188de11.png)

Before that, using .NET Bitmap, I can write:
`bmp = new Bitmap(path, true);`

This is my sample file:
![color_mgn](https://cloud.githubusercontent.com/assets/3154213/22180889/ffbdd072-e0b8-11e6-9693-e5dd40721972.jpg)

Thank you

**Comment by dlemstra** [comment]
I am not sure if what you are seeing in your example file are the correct colors. I get the same "incorrect color" with just the following command:

```C#
using (Bitmap image = new Bitmap("ffbdd072-e0b8-11e6-9693-e5dd40721972.jpg", true))
{
  image.Save("test.png", ImageFormat.Png);
}
```

It does depend where I view it though. In the PhotoViewer of Win10 I get the "correct color" but Chrome shows the "incorrect color". I can however get the result that you want in both apps with the following code:

```C#
using (MagickImage image = new MagickImage("ffbdd072-e0b8-11e6-9693-e5dd40721972.jpg"))
{
  image.AddProfile(ColorProfile.SRGB);
  using (var bitmap = image.ToBitmap())
  {
    bitmap.Save("test.png");
  }
}
```

**Comment by d2phap** [comment]
Thanks, this helped!
