### ISSUE TITLE
Unable to load DLL 'Magick.NET-Q16-x86.Native.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by mphillips2906** [dlemstra/Magick.NET#361]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using Click Once deployment, the Magick.NET-Q16-x86.Native.dll is not included. I added the nuget package and it downloaded this dll to my local folder. However when I publish the solution, the dll is missing. 
If I try to manually add the dll, it throws an exception stating the file is not accessible and that it is not a valid assembly.
### System Configuration

Using Windows 10/Visual Studio 17
- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
I don't have that issue in my own application (https://github.com/dlemstra/MagickViewer) but I don't remember what I did to make it work.

**Comment by mphillips2906** [comment]
I added the package to the main project in my solution and it fixed the issue. Previously, it was only included with a referenced project. Once the package was added to the main startup project, the Magick.NET-Q16-x86.Native.dll was included.

**Comment by dlemstra** [comment]
Thanks for your reply @mphillips2906. I will close this issue now
