### ISSUE TITLE
Unable to load DLL 'Magick.NET-Q16-x86.Native.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by gh658804** [dlemstra/Magick.NET#366]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET-7.9.2.0-Q16-x86
- Environment (Operating system, version and so on): Win2K12R2

### Question
Using VS 2013. I have referenced Magick.NET-Q16-x86.dll in a DLL project (VB.NET 3.5). Seeing that Magick.NET-Q16-x86.Native.dll is also needed, i have added it as content/Copy if newer in the project. I referenced the output of this DLL project in another project (web service), in which i also included Magick.NET-Q16-x86.Native.dll as content/Copy if newer. I then verified that all dlls are copied in the webservice execution folder.

When the web service is executed however, i get the following error:

System.Exception: System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x86.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at ImageMagick.Environment.NativeMethods.X86.Environment_Initialize()
   at ImageMagick.Environment.Initialize()
   at ImageMagick.MagickSettings.NativeMagickSettings..cctor()

Any pointers to what i may be doing wrong?

**Comment by gh658804** [comment]
Also, i have installed all x86 VC runtimes on the server (from 2005 to 2017), no luck though

**Comment by dlemstra** [comment]
Have you checked if your application pool allows running x86 libraries

**Comment by gh658804** [comment]
Yes, it does. The whole project due to certain restrictions is compiled as x86. Also, the account the web service runs as, has all necessary permissions to folders/databases etc. Everything else is called and works fine, except Magick.NET.

**Comment by dlemstra** [comment]
This really feels like an issue with your configuration/installation. I have no idea how I can help you any further.

**Comment by gh658804** [comment]
Thanks for responding. I believe that too, i just don't know if there is a way to produce more descriptive error messages in order to understand what's happening.

Have you ever tried to use it from web (SOAP web service to be specific)? Would it help if i uploaded the web.config file i use?

**Comment by dlemstra** [comment]
This project started inside a web application so it should definitely work there. Don't think it will really help to show the web.config. If you have are able to reproduce the issue in a stripped application shared on github and you got some installation instructions I might be able to help.

**Comment by gh658804** [comment]
OK, i'll try to play around some more to see if i can figure out what's causing the problem. I'll post any findings here, for future reference.

Thanks.

**Comment by gh658804** [comment]
Hi again.

I believe i have found the problem, however i cannot verify it since Windows security will not let me copy files in the WinSXS directory. I used a program to discover possible missing dependencies in Magick.NET. One of the requirements in Magick.NET is GDIPlus.dll. On my PC (Windows 7, in which Magick.NET works fine), this program reports that Magick.NET requires the following file:

C:\Windows\winsxs\amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.24308_none_145557608b95e72f\GdiPlus.dll

The problem is that in the destination server (Win2K12R2), this file does not exist. Instead there are different GDIPlus versions (the latest is amd64_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.9600.19202_none_932a8377475097fb)

I tried copying the file from my PC, just to see what happens (i know it's not the recommended way), but Windows security settings do not let me.

Having in mind that i will eventually try to install Magic.NET on a Win2K16 server (which has GDIPlus 1.1.14393 versions), how can this problem be handled?

**Comment by dlemstra** [comment]
@gh658804 Thanks for doing the research. I wonder if this issue will be resolved if I load the gdi library with `/delayload`. I have created a binary that you can download here: https://www.dropbox.com/s/8j0orhicdv81xqq/Magick.NET-Q8-x86.Native.dll?dl=0 that is the Q8 32 bit version that is linked this way. This library should only load GDI when a call to a method that needs this is made. Not sure when this happens but could you give it a try with this version?

**Comment by gh658804** [comment]
Unfortunately, nothing changed.

To be clear on what i did:

I have added the Magick.NET-Q8-x86 nuget package in a DLL project and referenced it. I then built the DLL and added it as reference in another DLL. I built the 2nd DLL and added it as reference to a SOAP web service. I then built the web service (all these in debug mode) and then copied all its contents to the appropriate folder on the web server. I also manually copied Magick.NET-Q8-x86.dll and Magick.NET-Q8-x86.Native.dll in the same folder since they were not directly referenced in the web project.

**Comment by dlemstra** [comment]
Did you copy the `Magick.NET-Q8-x86.Native.dll` file that you downloaded from DropBox to the target machine?

**Comment by gh658804** [comment]
Yes, however i now tried to find the exact point at which the code crashes and came up with this:

        Dim SrcImage As MagickImage
        SrcImage = New MagickImage(SourceFile)

At the 2nd line, the error is "The type initializer for 'NativeMagickSettings' threw an exception", which is something different than what is reported by the outer DLL. What does that error mean? I'm guessing an unsupported image? The funny thing is that i can open this image normally from image processing programs.

**Comment by dlemstra** [comment]
This might still be the same error message? The type initializer for 'NativeMagickSettings' will try to execute something in the native library and it then fails. Do you get any extra information from the inner exception (if there is one)?

**Comment by gh658804** [comment]
Yes, you're right, it's the same message in the inner exception:

System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q8-x86.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by gh658804** [comment]
Also, here's an image of the program i mentioned that i run on the server and reported the missing references:

https://imgur.com/bsqET9w

**Comment by dlemstra** [comment]
Delay loading is probably not working because something executes gdi code at the startup of the application. 

What happens when you copy the local `gdiplus.dll` from your machine into the `bin` folder of your application?

**Comment by gh658804** [comment]
The same thing. What is puzzling me is that i just tried using the same code from within an EXE on the same server and it's working fine. It seems it has something to do with the web server, it's not a missing dependency...

Is there by any chance a sample somewhere on how to use it from within a web service?

**Comment by gh658804** [comment]
Hi again.

I finally managed to create a test solution. You can find it attached in this post.

The output of this VB.NET 3.5 project runs OK on my PC from within .NET. If i upload the files (service1.asmx, web.config and the BIN dir) on a 2012R2 server and create a new web site on some port (i tried 8888), enabling 32bit apps, it produces the known error. When loaded on the server, click on "TestFunction" link, then "Invoke" button.

There is a single function in the web service (TestFunction) which should return "ALL OK" if everything was executed normally, otherwise it returns "Exception.ToString". The crash seems to occur in the first line of the DLL function, after the Try statement (SrcImage = New MagickImage(SrcPath & SrcFlnm)).

I hope you can discover what's causing this error. I have tried changing several things in web.config without any luck.

**Comment by gh658804** [comment]
Hi dlemstra,

Did you perhaps manage to find some time to take a look at the test project i uploaded? I still haven't found any reason why this is happening.

**Comment by dlemstra** [comment]
I have not yet made time to look at this. And I will be occupied for the next 25 days so it will be a while before I can take a look at it.

**Comment by gh658804** [comment]
OK, no problem. Just have in mind that the file will be on that site for the next 3 weeks, then it will be automatically deleted, so please download it before that time passes and take a look at it whenever you can. Or you can tell me to repost it at a later time. :)

Thanks.

**Comment by dlemstra** [comment]
Can you repost the file?

**Comment by gh658804** [comment]
Hi.

Here you are: https://ufile.io/by8wd

**Comment by gh658804** [comment]
The above test project creates a new instance of a class and calls a single function in it which is supposed to insert a date on a given image. It executes OK from within Visual Studio but when put on a server (tried it under a Win2K12R2 server), it returns the error mentioned in my O.P. It is also executed without errors from within a Forms EXE project.

**Comment by gh658804** [comment]
Hi dlemstra.

Did you perhaps manage to find some time to check this thing?

**Comment by dlemstra** [comment]
I have not found time for this yet. And I am now locked out of my Visual Studio because of an issues with my MSDN license but I hope I can find some time this week.

**Comment by gh658804** [comment]
OK, thanks for your time. I need to perform such tasks in one of my projects and it would be much more convenient (not to mention stable) if i could use Magick.NET instead of having to call ImageMagick,

**Comment by dlemstra** [comment]
I could not build your solution but adding a reference to `System.Drawing` in `MagickNET_TestDLL` solved the issue. I cannot find anything odd in your solution/project that could explain why this is happening. I don't have a 2012R2 server so I cannot test it there but this library has run on that it the past. Have you tried running the application pool in full trust to see if that resolves the issue? And have you tried running something like dependency walker on your 2012R2 machine to check if all the dependencies can be found?

**Comment by gh658804** [comment]
Could not build? Strange. What was the problem?

I'll try adding the reference tomorrow and re-test it. As for dependency walker, yes i did that when i reported about gdiplus.dll, but subsequent tests made me believe that was not the issue.

Thanks for your time. I'll let you know what happens.

**Comment by dlemstra** [comment]
Make sure you also try running the application pool in full trust. That has solves some issues for me in the past, no idea if that will help with this though.

**Comment by gh658804** [comment]
OK, i'll try that too. Thanks.

**Comment by gh658804** [comment]
Hi again.

After recompiling the project and copying the native DLL in both system32 and syswow64 (and the application's bin folder), it finally worked! What puzzles me is that i had tried this in the beginning, without any luck though. I'm not sure yet what changed (perhaps a server restart or some things i changed in IIS's configuration?), but it works wow.

Thanks for your time and ideas on this.

**Comment by dlemstra** [comment]
Happy to hear that you finally managed to get it to work. Now time to have fun with the library 👍

**Comment by nsutariya9393** [comment]
> configuration

Hi I am having same issue, can you mention what did you change in IIS configuration? I know its too late but if you remember, please

**Comment by gh658804** [comment]
Hi. As i had mentioned in my last post:

> copying the native DLL in both system32 and syswow64

Just copy the 32bit DLL in c:\windows\syswow64 and the 64-bit one in c:\windows\system32 and you should be fine.

**Comment by nsutariya9393** [comment]
I already did but doesn't work . and sorry to mention, I am working on 64 so I am using 64 bit dll. looks like some configuration I am missing

**Comment by nsutariya9393** [comment]
you can look at https://github.com/dlemstra/Magick.NET/discussions/874 in detail for my issue

**Comment by Piero-21** [comment]
Tuve el mismo problema hoy sobre que no ejecuta tal dll después de la instalación pero si me ejecutaba en el visual Studio, para solucionarlo copié y pegué los dll que no se llegaron a aplicar en el instalador, los que se encuentran en la carpeta release que se encuentra en al carpeta bin de mi proyecto principal, no es lo óptimo, pero al parecer no se llegó a implementar ciertos dll en el instalador y tuve que insertarlos manualmente.
