### ISSUE TITLE
Need help with Morphology, How do I execute this command in Magick.net ( command in description )

### ISSUE THREAD

**Issue by jayantrajwani** [dlemstra/Magick.NET#367]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.9.2
- Environment (Operating system, version and so on): Windows 10

### Question
I want to remove all horizontal and vertical lines from an image
Below is the command for what i want to do using C#

magick ( image.png -alpha off ) ^
( -clone 0 -morphology close rectangle:1x50 -negate +write tmp1.png ) ^
( -clone 0 -morphology close rectangle:50x1 -negate +write tmp2.png ) ^
( -clone 1 -clone 2 -evaluate-sequence add +write tmp3.png ) ^
-delete 1,2 ^
-compose plus -composite ^
result.png

**Comment by dlemstra** [comment]
What have you tried so far? Most options are a method of the `MagickImage` class and when you work with multiple images you probably want to use the `MagickImageCollection` also.

**Comment by jayantrajwani** [comment]
I have been using AForge to detect quadilateral shapes and replace them with white boxes till now.

**But i also want to remove other vertical and horizontal lines as well.
I dont have much idea of magick.net but i was able to do it via console using image magick using the following command:**

```
magick ( image.png -alpha off ) ^
( -clone 0 -morphology close rectangle:1x50 -negate +write tmp1.png ) ^
( -clone 0 -morphology close rectangle:50x1 -negate +write tmp2.png ) ^
( -clone 1 -clone 2 -evaluate-sequence add +write tmp3.png ) ^
-delete 1,2 ^
-compose plus -composite ^
result.png
```
**I want a equivalent C# code using magick.net**

**Comment by dlemstra** [comment]
Can you share your input image?

**Comment by jayantrajwani** [comment]
Input Image :
![image](https://user-images.githubusercontent.com/11351528/50582300-7f434680-0e87-11e9-86be-a281b82d34b7.jpeg)

This is what i expect as output :
![result](https://user-images.githubusercontent.com/11351528/50582321-adc12180-0e87-11e9-9673-e798a41fd849.png)

**Comment by dlemstra** [comment]
Your command would translate to something like this:

```C#
// magick ( image.png 
using (var image = new MagickImage(@"I:\issues\magick\367\image.png"))
{
    // -alpha off ) ^
    image.Alpha(AlphaOption.Off);

    using (var images = new MagickImageCollection())
    {
        // ( -clone 0
        var tmp1 = image.Clone();

        // -morphology close rectangle:1x50
        tmp1.Morphology(MorphologyMethod.Close, "rectangle:1x50");

        // -negate
        tmp1.Negate();

        // +write tmp1.png ) ^
        tmp1.Write(@"I:\issues\magick\367\tmp1.png");

        images.Add(tmp1);

        // ( -clone 0
        var tmp2 = image.Clone();

        // -morphology close rectangle:50x1
        tmp2.Morphology(MorphologyMethod.Close, "rectangle:50x1");

        // -negate
        tmp2.Negate();

        // +write tmp2.png ) ^
        tmp2.Write(@"I:\issues\magick\367\tmp2.png");

        images.Add(tmp2);

        // -evaluate-sequence add
        using (var tmp3 = images.Evaluate(EvaluateOperator.Add))
        {
            // +write tmp3.png ) ^
            tmp3.Write(@"I:\issues\magick\367\tmp3.png");

            // -compose plus -composite ^
            image.Composite(tmp3, CompositeOperator.Plus);

            // result.png
            image.Write(@"I:\issues\magick\367\result.png");
        }
    }
}
```

**Comment by jayantrajwani** [comment]
It works. Thanks @dlemstra 💯

**Comment by jayantrajwani** [comment]
Hi @dlemstra 
How do i convert the following command to get a list<Image> as output.

```
IFS=" "
OLDIFS=$IFS
IFS=$'\n'
bboxArr=(`convert image.png -alpha off -type bilevel \
-define connected-components:verbose=true \
-define connected-components:area-threshold=500 \
-connected-components 4 \
null: | grep "gray(0)" | awk '{print $2}'`)
num=${#bboxArr[*]}
IFS=$OLDIFS
for ((i=0; i<num; i++)); do
convert image.png -crop ${bboxArr[$i]} +repage image$i.png
```

**Comment by jayantrajwani** [comment]
@dlemstra I have closed this issue as the actual problem statement got solved but would be great if you could provide a solution to the above comment.

**Comment by dlemstra** [comment]
And what have you tried yourself? The `MagickImage` class contains a `ConnectedComponents` method that should give you all the information that you need.

**Comment by kefilwe52** [comment]
Hi @dlemstra ,

Could you please help me crop the document so that it starts and ends at the vertical lines, keeping only the content between them?

Crop the data from the left up to the vertical line and from the right up to the vertical line.


static void CropImageUsingAggressiveCrop(string imagePath)
{
    using (MagickImage image = new MagickImage(imagePath))
    {
       
        image.ColorSpace = ColorSpace.Gray;

        int leftMost = 0;
        int rightMost = image.Width;

        using (var verticalLines = image.Clone() as MagickImage)
        {
           
            verticalLines.Morphology(MorphologyMethod.Close, "rectangle:1x50");

    
            verticalLines.Threshold(new Percentage(50));

![vertical_lines_thresholded_debug_aggressive](https://github.com/user-attachments/assets/f946050c-9d3c-436b-a094-ce1b4d432626)

**Comment by dlemstra** [comment]
Please don't hijack an old topic for a new question. Please start a new discussion with your question.
