### ISSUE TITLE
Support for Azure functions?

### ISSUE THREAD

**Issue by Roesler** [dlemstra/Magick.NET#369]
### Prerequisites

- [x] I have written a descriptive issue title
- [7.9.2] I have verified that I am using the latest version of Magick.NET
### System Configuration

Azure functions, Blob trigger function more exactly
- Magick.NET version: 7.9.2
- Environment (Operating system, version and so on):
.NET Core 2.2 in Azure
### Question
Is there any documentation/tutorial on how to use Magick in a Azure function? The installation said everything is fine, but it shows an error it cant find it? Adding the very short project.json file as a *.txt.
Is there maybe some more dependencies for azure that I need to install?
[project.txt](https://github.com/dlemstra/Magick.NET/files/2727273/project.txt)

**Comment by mario-mestrovic** [comment]
Hi @Roesler, can you provide more info? It should work out of the box if you use Magick.NET nuget package. If you need ghostcript you'll need to point to the ghostscript folder explicitly.

**Comment by Roesler** [comment]
Hi @mario-mestrovic I think I solved the issue by doing all locally instead. Sorry for late response. Do you have any good tips on serverless azure functions with Magick.NET? Trying to understand how touse MagickImage.Write() to a MemStream and then pass the stream to blob-container without losing content/type and all bytes...?

**Comment by Roesler** [comment]
I solved my issue, but the question for for examples or documentation with this kind of info could still be needed.

**Comment by dustynl** [comment]
Hey @Roesler .... I'm very curious to see how you got this working in Azure Functions? 
I get a "FailedToExecuteCommand `"gswin32c.exe"" when trying to read from a stream binding on the function.

**Comment by Roesler** [comment]
@dustynl Everytime im moving my stream to a new instance I creating a new memorystream and then check if the length is bigger than 0, and then set that stream to Position = 0;
Then when I neew to do something with 
MagickImage I convert the latest stream like this: 
`public static void ResizeToCorrectSize(Stream original, string fileName, string contentType)
                {
                        MemoryStream imageStream = new MemoryStream();
                        original.CopyTo(imageStream);

                        string[] folders = new string[] { "image-large", "images-medium", "images-small", "images-thumbnail" };
                        string destinationContainer = "images-thumbnail";
                        using (Stream memStream = new MemoryStream())
                        {
                                MagickGeometry sizeSmall = new MagickGeometry(200, 0);
                                if (imageStream.Length > 0)
                                {
                                        imageStream.Position = 0;
  
                                        if (contentType == "image/gif")
                                        {
                                                Console.WriteLine("ResizeToCorrectSize contentType " + contentType );
                                                return;
                                        }
                                        else
                                        {
                                                using (MagickImage image = new MagickImage(imageStream))
                                                {
                                                        image.Resize(sizeSmall);
                                                        sizeSmall.IgnoreAspectRatio = false;
                                                        image.Write(memStream);
                                                }
                                                
                                        }
                                      
                                        if (memStream.Length > 0)
                                        {
                                                memStream.Position = 0;
                                     UploadFileToStorage(memStream, destinationContainer, fileName, contentType);
                                        }
                                }
                        }

                              // Console.WriteLine("ResizeToCorrectSize memStream.Length " + memStream.Length + " \n memStream.Position" + memStream.Position);
                }`

**Comment by Marcel0024** [comment]
@dustynl Did you solve your issue?

**Comment by dlemstra** [comment]
Can we close this issue @Roesler?

**Comment by Roesler** [comment]
Yes @dlemstra. Thank you.
