### ISSUE TITLE
Issue for Converting Colorspace ( RGB PDF to CMYK)

### ISSUE THREAD

**Issue by deepakkjose** [dlemstra/Magick.NET#370]
We have an issue (ImageMagick version 6.9.3) for converting sRGB PDF file to CMYK.
The output PDF file always "RGB". It is not converting to CMYK
This issue only happening to convert PDF to PDF. 
On PDF to JPG conversion colorspace change to CMYK.

The command we have used is
convert "source.pdf" -colorspace cmyk "output.pdf"

**Comment by dlemstra** [comment]
Are you using ImageMagick or Magick.NET? If you are using ImageMagick then please open an issue here instead: https://github.com/ImageMagick/ImageMagick/issues
