### ISSUE TITLE
Missing dll while using TIFF images.

### ISSUE THREAD

**Issue by Romasz** [dlemstra/Magick.NET#371]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

While using tiff image as a source of MagickImage we can see in debug output that of the dlls seem to be missing:

> Error: ImageCoreBasedDecoder static init failed: System.DllNotFoundException: Unable to load DLL 'WIC.ImgCoreDll.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
>   at ImgCore.ImgCoreDll.IC_StaticInit()
>   at P1.C1.Common.ImageCore.ImageCore.StaticInit(Int32 argHeapSize)
>   at P1.COPE.Core.COPEEnvironment.Initialize(String colorProfileRootPath, String imgCoreLogFile, String copeLogFile, Int32 heapSize)
>   at P1.WICCODEC.CODEC.ImageCoreBasedDecoder.StaticInitialization()
>   at P1.WICCODEC.CODEC.ImageCoreBasedDecoder..cctor()`

The code is simple:

    using (MagickImage image = new MagickImage(source))
        return image.ToByteArray();

Not sure how important is this, hence everything works fine. Just this noise in the output with alerting 'Error'.

### System Configuration

- Magick.NET version: 7.10
- Environment (Operating system, version and so on): W10
- Additional information: ---

**Comment by dlemstra** [comment]
Your exception is complaining about not being able to load a library called `WIC.ImgCoreDll.dll`. This is not a Magick.NET library. It looks like you have a different problem?

**Comment by Romasz** [comment]
You are right. I debugged further and checked some more dependencies - this seem to be a problem on my side with one of the codecs. It appears after the byte array is returned. 

Sorry for leaning out with this.

**Comment by dlemstra** [comment]
No problem and thanks for coming back and closing this issue 👍
