### ISSUE TITLE
TIF Flattening Test Results

### ISSUE THREAD

**Issue by troyzirk2** [dlemstra/Magick.NET#373]
Hi Dirk,

Thank you for implementing the flattening over the weekend (related to my post #372). I upgraded to Magick.NET-Q16-AnyCPU 7.10.1 and then ran a flattening test with additional samples. Please find the results in this weblink:

https://vrxwestus.blob.core.windows.net/vrxstudios-downloads/TIFFlatteningTest.zip

I found 3 issues (separate folders in the weblink):

1. Darker - 2 images are slightly darker after flattening. It may have something to do with the layer groups.

2. Layer Off-Center - 1 image has a layer that is slightly off-center after flattening. It might have something to do with unequal layer widths, but I'm not sure.

3. Files Too Large - 2 images were too large in file size to process. I have specified a local path for temporary files.

My code sample is in the weblink as well, but also included here. (All TIFs contain multiple layers, and so the layers.Flatten() will always be called.)

MagickNET.SetTempDirectory([Local File Path]);
foreach (var file in [TIF File Paths])
{
	// get flattened image file name.

	var flattenedFile = file.Replace(".tif", "-flattened.tif");

	using (ImageMagick.MagickImageCollection layers = new ImageMagick.MagickImageCollection(file))
	{
		if (layers.Count > 1)
		{
			using (ImageMagick.MagickImage image = (ImageMagick.MagickImage)layers.Flatten())
			{
				image.Depth = 8;
				image.Settings.Compression = ImageMagick.CompressionMethod.LZW;
				image.RemoveProfile("8bim");
				image.RemoveProfile("psd:additional-info");
				image.Write(flattenedFile);
			}
		}
	}
}

**Comment by dlemstra** [comment]
I did some research and I came to the following conclusions:

`Darker\0001314041\0001314041.tif`: You are basically just seeing frame 13 with other images on top of it.
`Darker\0001314086\0001314086.tif`: The last frame (nr 6) makes the image darker.
`Layer Off-Center\0001314039`: The last frame (nr 6) contains wider image with a negative offset that causes it to be placed a bit to the left. And it also contains transparent pixels on the right side so you don't notice it is wider.

And I have no problem opening the `Too Large`. Are you running this in 32bit or 64bit?

I am now also wondering if you really need to flatten the image. Can't you just take the first image and use that as the flattened image instead? When you read your file with a `MagickImage` instead of a `MagickImageCollection` you will only read the first image and that is probably the result that you want.

**Comment by troyzirk2** [comment]
Thank you for your research, Dirk. I greatly appreciate it.

I previously had tried opening the files as MagickImage objects, but I got mixed results, presumably because I was using an older version. I've since upgraded to Magick.NET-Q16-AnyCPU 7.10.1, and now I am getting more dependable results. I was also able to open the files that were too large for my development environment.

However, out of the previous set of sample files, there are two files having a masking issue. I have included all sample files in the following ZIP for you to download.

https://vrxwestus.blob.core.windows.net/vrxstudios-downloads/TIFFFlatteningTest2.zip

My solution is x64, so I will assume my development environment doesn't have enough memory to open the larger files. However, this will no longer be an issue, as long as I can open all sample files as a MagickImage object.

My new code is as follows:

using (MagickImage image = new MagickImage(_[FilePath]_))
{
	image.Depth = 8;
	image.Settings.Compression = ImageMagick.CompressionMethod.LZW;
	image.RemoveProfile("8bim");
	image.RemoveProfile("psd:additional-info");
	image.Write(_[FilePath-MagickImage]_);
}

What code adjustments would I need to make, to account for the extra masking layers? Would I still need to open the file as a MagickImageCollection, and somehow delete the extra masking layers first?

**Comment by troyzirk2** [comment]
Hi Dirk,

I was wondering if you had a chance to further research this issue?

Thank you.

**Comment by dlemstra** [comment]
I haven't made time to look at this and I will be occupied to whole next 30 days. So it will be a while before I can take a look at this again.

**Comment by dlemstra** [comment]
When you open the PSD file as a MagickImage you will only get the merged image and I think that is what you want. Can you go in more detail about the masking layers? Those should already be applied to the merged image.
