### ISSUE TITLE
I have an image with a checkbox, how to identify if it is checked or not

### ISSUE THREAD

**Issue by jayantrajwani** [dlemstra/Magick.NET#375]
### Prerequisites

- [x] I have written a descriptive issue title

### System Configuration

- Magick.NET version: 7.9.2
- Environment (Operating system, version and so on): Windows 10

### Question
Below is an image of a checkbox. how to identify if it is checked or not.

![html-checkbox](https://user-images.githubusercontent.com/11351528/51387695-f564d000-1b4c-11e9-817d-5e6280f997d0.png)

**Comment by dlemstra** [comment]
You could probably check the pixels inside and check if it is black. You probably only need to check one pixel if the checkbox is the same dimension every time.

**Comment by jayantrajwani** [comment]
@dlemstra 
The image will always be different can be any checkbox looking image. If it's a perfect square we can remove the box and see if there is any pixel inside but in case it is a box with with curved corners like the one above it'll not work. I'm looking for a more of a generic solution that will work for all images

**Comment by dlemstra** [comment]
There is no method that works for all images because I have no idea what all images will be. In what kind of context are you planning to detect images with a checkbox?
