### ISSUE TITLE
Combining layers creates an image that is not layered

### ISSUE THREAD

**Issue by vionut** [dlemstra/Magick.NET#377]
Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

System Configuration

- Magick.NET version: 7.9.1
- Environment (Operating system, version and so on): Windows 10 x64

Question

I want to change the color in a layer of a layered tiff, and recombine the layers into another tiff file that is also layered so I can repeat the process, is that possible?

So far I've tried this
         
```
            MagickReadSettings settings = new MagickReadSettings();
            MagickImageCollection layers = new MagickImageCollection();
            layers.Read(image, settings);
            layers.RemoveAt(0);

            var thumbStream = new MemoryStream();

            // getting the layer I wanna change
            layers[layerNumber].Write(thumbStream, MagickFormat.Tiff);
            var baseLayer = thumbStream.ToArray();

            // changing the color
            var newLayer = new MagickImage(ChangeColorForLayer(baseLayer, newColor));
            
            // switching the layer
            layers[layerNumber] = newLayer;

            var newColorway = layers.Mosaic();



            newColorway.Write(path);
            var layers2 = new MagickImageCollection();
            layers2.Read(path, settings);
```
But when I read the file again, it only finds one layer, so the result tiff is not layered.

I should mention that I have tried this with methods: collection.Mozaic(), collection.Combine(), collection.Flatten(), collection.Merge(), neither produces a layered file.

Also I've tried saving the collection without calling any method first, but the resulted Tiff looks like the first layer.

Thanks.

**Comment by dlemstra** [comment]
Can you explain why you closed this issue @vionut? This might help someone in the future.

**Comment by vionut** [comment]
Sure, I closed it because I found a way arround ( or maybe this is actually the correct way of doing what I'm trying to do, I don't know since I'm not an expert in layered files ).

So when using MagickCollection.Read on a layered tiff, it gets the layers of the image, and the first layer is always how the image looks after combining all it's layers.
What I'm doing is changing a color in a layer, combine the layers with the Mosaic() method and replace the first layer and the changed layer in the original tiff. This way I get a layered image that looks like the combination of it's layers (including the changed one).

```
            MagickReadSettings settings = new MagickReadSettings();
            settings.Compression = CompressionMethod.Zip;
            MagickImageCollection layers = new MagickImageCollection();
            layers.Read(Print.FileContent, settings);


            // get the base layer (the layer that needs to be changed) 
            // +1 because we disregard first layer
            var thumbStream = new MemoryStream();
            layers[layerNumber + 1].Write(thumbStream, MagickFormat.Tif);
            var baseLayer = thumbStream.ToArray();

            // create the new layer by changing the color of the baseLayer
            var newLayer = new MagickImage(ChangeColorForLayer(baseLayer, newColor));

            // switch the layer with the new layer
            layers[layerNumber + 1] = newLayer;

            // add the image created by combining the layers as the first layer
            // the tiff will always look like the first layer
            layers[0] = layers.Mosaic();


            var newColorway = new MemoryStream();
            layers.Write(newColorway);
```
