### ISSUE TITLE
Seg fault crash with ImageOptimizer.LosslessCompress for a specific jpg

### ISSUE THREAD

**Issue by dabutvin** [dlemstra/Magick.NET#378]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I have a jpg that, when running ImageOptimizer.LosslessCompress() causes a seg fault
```
Segmentation fault: 11
```

This happens every time and has reproduced on windows and mac with the latest Magick.NET 7.10.2
Note: this does not crash when calling `Compress()`. It only crashes when calling `LosslessCompress()`.

I can repro this issue with OptimalCompression on and off, and with IgnoreUnsupportedFormats on and off.

### Steps to Reproduce

I have a simple repro set up here: https://github.com/dabutvin/SaskArtists/tree/debug
This is a fork from the original issue trimmed down to a single image and includes a console app that demonstrates the failure. I could not get any additional logs out even when enabling the debug events.

Here is the console app that points to the troublesome image with a relative path
https://github.com/dabutvin/SaskArtists/blob/debug/magick/Program.cs

This is the image file: https://github.com/dabutvin/SaskArtists/blob/debug/www/artists/rarnott/images/snowy_painting.jpg

### System Configuration

- Magick.NET version: 7.10.2
- Environment (Operating system, version and so on): MacOS Mojave 10.14.2 + Windows running in Azure Functions Consumption environment

**Comment by dlemstra** [comment]
Thanks for finding this. This image contains a huge marker that is split up. The current code cannot handle that. And there is an incorrect buffer check that causes this access violation. Will take a look at it next week.

**Comment by dabutvin** [comment]
Awesome! Let me know how it goes or if you need anything.
