### ISSUE TITLE
Save BMP3 with alpha possible?

### ISSUE THREAD

**Issue by liinko** [dlemstra/Magick.NET#379]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.10.2
- Environment (Operating system, version and so on): Win 10

### Question

Is it possible to save a BMP3 including the alpha channel?

@dlemstra I found a post you made in the forum below, saying that it was going to be added to a version of ImageMagick 

https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=28733&start=15

Saving with MagickFormat.Bmp works fine, and saves with the alpha channel, but MagickFormat.Bmp3 does not. 3ds Max unfortunately does not support the former.

**Comment by dlemstra** [comment]
You will need to use the define to make that possible. This option should probably be added to the BmpWriteDefines to make it easier for you.

**Comment by liinko** [comment]
I was able to save the bmp3 image with alpha using the following

`image.Settings.SetDefine(MagickFormat.Bmp3, "alpha", true);`

But now I'm running into another issue, the bmp header is showing BI_BITFIELDS, instead of BI_RGB for compression.

I compared it with a bmp saved from Photoshop with alpha, the data is identical, but the Photoshop header has BI_RGB as its compression method, and the bmp produced by ImageMagick shows BI_BITFIELDS along with its extra data. 

Here are the files in question

- PS_alpha.bmp was saved from Photoshop with alpha
- Magick_alpha.bmp was saved using the define mentioned above

[Bitmaps.zip](https://github.com/dlemstra/Magick.NET/files/2824820/Bitmaps.zip)

I assume the bitfields just determines the pixel order like RGBA or ARGB since the data does not seem to be compressed, is there a way to change the header so that the compression method is BI_RGB instead? 

I've already tried `image.Settings.Compression = CompressionMethod.NoCompression;` but that did not work.

**Comment by t246246** [comment]
Magkick_alpha.bmp is not BMP3, it has 124 byte BITMAPV5HEADER header.

**Comment by dlemstra** [comment]
Can we close this issue @liinko ?

**Comment by liinko** [comment]
yes, the issue can be closed. 

Thank You @t246246 your solution worked.
