### ISSUE TITLE
[question] Work with text

### ISSUE THREAD

**Issue by denis-shevchenko** [dlemstra/Magick.NET#38]
I know it is possible with ImageMagick create text labels, or add text to images. It seems, that Magick.Net doesn't provide this useful features. Do you will implement this functionality in next versions?

**Comment by dlemstra** [comment]
This feature is available in Magick.NET do you have a command line example of what you think you are missing?

**Comment by denis-shevchenko** [comment]
I couldn't find it in magick.net samples and guess that it hasn't. Actually i need "Caption - Word Wrapped Label", could you post an example, how can it be used.

**Comment by dlemstra** [comment]
You could do the following:

```C#
MagickReadSettings settings = new MagickReadSettings()
{
  BackgroundColor = MagickColors.LightBlue,
  FillColor = MagickColors.Blue,
  Font = "Consolas",
  FontPointsize = 36,
  Width = 320
};

string caption = "caption:This is a very long caption line";

using (MagickImage image = new MagickImage(caption, settings))
{
  image.Write("caption.png");
}
```

**Comment by dlemstra** [comment]
Can I close this @denis-shevchenko ?

**Comment by denis-shevchenko** [comment]
Can you tell me, where should i store the fonts? 
My installed fonts hasn't been taken.
I try it like this

`
Font = "Arial"
`

**Comment by dlemstra** [comment]
Magick.NET can use the Windows fonts. Setting it to `Arial` should work. Are you using the latest version?

**Comment by denis-shevchenko** [comment]
Yes, i use Magick.NET.Core-Q8 v.7.0.4.400

**Comment by dlemstra** [comment]
Do we still need to keep this open @denis-shevchenko? The default Windows fonts should be used.

**Comment by Thom-Sip** [comment]
In case anyone finds this through google. Setting Font in settings didn't work for me either, I needed to set the FontFamily of the settings.

**Comment by GlennIM** [comment]
Is there a way to set the FontFamily through an enumeration like colors (i.e FillColor = MagickColors.Blue) instead of a font text string?

**Comment by dlemstra** [comment]
There is no way to this and I this won't be added to Magick.NET because it totally depends on the operating system/environment that you use the application which fonts are available. 

I would advise you to use a static class in your own project.:

```C#
public static class FontFamilies
{
    public const string Verdana = nameof(Verdana);
}
```

**Comment by Dan1ve** [comment]
For reference, you can call `MagickNET.FontFamilies` and `MagickNET.FontNames` to check which fonts are available.

In my case, not all OS fonts are being listed (I'm using Windows). It might have to do with the fact that the missing font is an OpenType font, but that is just an assumption.
