### ISSUE TITLE
I have an RGBA32 raw image, but I cannot convert it

### ISSUE THREAD

**Issue by TileTurnip** [dlemstra/Magick.NET#381]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.10.2
- Environment (Operating system, version and so on): Windows 10

### Question
The raw image should be 1024x1024.
But the exception happens to me.
![qq 20190203132042](https://user-images.githubusercontent.com/14805065/52173100-d6ef0d80-27b7-11e9-8e46-e2998961d08f.png)

How to deal with it?
Here is my sample.
[sample.zip](https://github.com/dlemstra/Magick.NET/files/2825190/sample.zip)

Thanks for reading it.

**Comment by dlemstra** [comment]
You did not tell me your Magick.NET version so this might be the wrong conclusion but I think you are using a 16 bit version of Magick.NET and you are reading an 8 bit image. What you could do is switch to 8 bit or you could use `PixelStorageSettings` and change your code to this:

```C#
var fileName = "c:/projects/sample.ptx";

var data = new byte[0x400 * 0x400 * 4];

var fs = File.OpenRead(fileName);
fs.Read(data, 0, 0x400 * 0x400 * 4);

var settings = new PixelStorageSettings(0x400, 0x400, StorageType.Char, PixelMapping.RGBA);

using (var image = new MagickImage(data, settings))
{
}
```
