### ISSUE TITLE
MagickCacheErrorException: no pixels defined in cache on TGA Files 

### ISSUE THREAD

**Issue by Stromberg90** [dlemstra/Magick.NET#382]
In my image viewer program, I noticed on the latest version 7.10.2 it fails when loading tga files.
`MagickCacheErrorException: no pixels defined in cache`
So I went back through earlier versions to see at which point it worked, it works on 7.9.2 but not after.

Related code:
```csharp
ImageSettings.ImageCollection = new MagickImageCollection {Path};
```

**Comment by dlemstra** [comment]
This is caused by patch in issue #368. This will be resolved in the next release.
