### ISSUE TITLE
SVG to 32-bit ARGB bitmap (BMP) with transparency

### ISSUE THREAD

**Issue by tsuga** [dlemstra/Magick.NET#386]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 7.11.0
- Environment (Operating system, version and so on): Windows 10

### Question

I tried to convert a svg to a 32-bit ARGB bitmap (BMP) with keeping the transparency.

My code looks like this:

    string inputPath = @"C:\Users\MyAccount\Documents\w3c.svg";
    string outputPath = @"C:\Users\MyAccount\Documents\w3c.bmp";
    using (FileStream fsSource = new FileStream(inputPath, FileMode.Open, FileAccess.Read))
    {
        var magickSettings = new MagickReadSettings() { Format = MagickFormat.Svg };
        magickSettings.Density = new Density(192);
        magickSettings.SetDefine("bmp3:alpha", "true");
        magickSettings.BackgroundColor = MagickColors.Transparent;
        using (var magickImage = new MagickImage(fsSource, magickSettings))
        {
            magickImage.Scale(200, 100);
            magickImage.Format = MagickFormat.Bmp3;
            magickImage.Quality = 100;
            magickImage.Write(outputPath);
        }
    }

For example, [this svg file](https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/w3c.svg) is converted to:
![asis](https://user-images.githubusercontent.com/2888173/52702350-4b4b5d00-2fbf-11e9-9362-5973f4cd3ab0.JPG)
But I expect it to be:
![tobe](https://user-images.githubusercontent.com/2888173/52702414-6e760c80-2fbf-11e9-8333-1713b743e6a3.JPG)

How should I change my code to get the expected result?

**Comment by t246246** [comment]
For this image `w3c.svg`, ImageMagick command `-background transparent` does not work but `-transparent white` works.
So, the following program should work.

```
static void Main(string[] args)
        {
            var configure = ImageMagick.Configuration.ConfigurationFiles.Default;
            configure.Policy.Data = @"
<policymap>
<policy domain=""coder"" rights=""read"" pattern=""MVG"" />
</policymap>
";
            configure.Delegates.Data = @"
<delegatemap>
<delegate decode=""svg"" command=""&quot;rsvg-convert&quot; -o &quot;%o&quot; &quot;%i&quot;"" />
</delegatemap>
";
            MagickNET.Initialize(configure);

            using (var magick = new MagickImage("w3c.svg"))
            {
                magick.Transparent(MagickColors.White);
                magick.Write("w3c.bmp");
            }
        }
```

**Comment by dlemstra** [comment]
Bmp3 with transparency is not supported by all (maybe even most) image viewers. When ImageMagick (Magick.NET) reads this image it will detect that it has an alpha channel. Other image viewers like the photo viewer on Windows will not detect an alpha channel and read those pixels as black instead. I have checked the image that was created and it does contain values for the alpha channel but you will need a different viewer to see this.

**Comment by tsuga** [comment]
Thank you for your replies.
I believe that GIMP support Bmp3 with an alpha channel. However, it displays the background as black...
