### ISSUE TITLE
Distort - Perspective - Very slow

### ISSUE THREAD

**Issue by movedoa** [dlemstra/Magick.NET#387]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET-Q8-x86 - 7.11.0.0
- Environment (Operating system, version and so on): Windows 10 64Bit

### Question
I use Magick.Net to perspective transform an image.
It works but is is extremely slow.
For a 1200 x 908 image the Distort command takes ~760ms.

Is this expected?
Can this be improved somehow?
Currently i don't set any settings, i just load to image from a memstream and run the distort command.
-> Distort(ImageMagick.DistortMethod.Perspective,oDoubleArray)

Here is the Logfile of the Distort command:
[Magick.log](https://github.com/dlemstra/Magick.NET/files/2866134/Magick.log)

**Comment by dlemstra** [comment]
There is quite a lot of math involved for each pixel so that could explain the duration. Can you share an image an the values of `oDoubleArray`?

**Comment by movedoa** [comment]
Yeah i thought so. But your comment gave me an idea. Basically i want to put a transformed image onto a background image. Currently i extend the image, then tranform it and then combine it with the background. I guess the extending adds a lot of wasteful transparent pixels for the transformation. Is it possible to transform the image without extending it first but in the boundaries of the background image (which is always bigger)?

**Comment by movedoa** [comment]
Ok when i don't extend the image it is better but still takes 500ms.
I found a forum entry where someone had the exact same problem (with regular ImageMagick).
And someone posted a script there that takes the time down from 0.6s to 0.1s.

https://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=29495&p=132182#p132141

But this script goes way over my skills here.
Could you please give me a hint on how to convert this?

**Comment by dlemstra** [comment]
You can do `+distort` by setting `Bestfit` to true inside the `DistortSettings`. And with the `VirtualPixelMethod` of the `MagickImage` you can set the virtual pixel method to transparent. The rest of the script is just calculating the values for the double array:

```bash
# tl = TopLeft, br= BottomRight (you can figure out the rest)
tl_bg="494,108"
tr_bg="579,118"
br_bg="579,197"
bl_bg="494,181"

# this gets the dimensions of the image
dim=`convert -ping image.jpg -format "%wx%h" info:`

# width and height
ww=`echo $dim | cut -dx -f1`
hh=`echo $dim | cut -dx -f2`

# right = width - 1 and bottom = height -1
right=$((ww-1))
bottom=$((hh-1))

echo "ww=$ww; hh=$hh; right=$right; bottom=$bottom;"
tl_im="0,0"
tr_im="$right,0"
br_im="$right,$bottom"
bl_im="0,$bottom"
# $tl_im $tl_bg  $tr_im $tr_bg  $br_im $br_bg  $bl_im $bl_bg are the values for the array
time convert bg.png \
\( image.jpg -virtual-pixel transparent +distort perspective \
"$tl_im $tl_bg  $tr_im $tr_bg  $br_im $br_bg  $bl_im $bl_bg" \) \
-layers merge +repage bg_image_result.jpg
```

Feel free to ask for more info if you cannot figure it out yourself.

**Comment by movedoa** [comment]
Thank you for your answer.
Unfortionately this is pretty much what i am doing at the moment. I was hoping there was something more in this. I was looking around some more and i guess i have to live with this. I am using the Q8 x86 version so no multithreading which also won't help i guess. Is there a chance for a Q8 x86 version with openmp?

**Comment by dlemstra** [comment]
There will not be a x86 version of the OpenMP builds. Unless you offer me a milion dollar of course. But jokes aside, this just means more maintance for a very small audience.
