### ISSUE TITLE
png image after rotation has a white filled space

### ISSUE THREAD

**Issue by denis-shevchenko** [dlemstra/Magick.NET#39]
My method look like this:

```
using (MagickImage icon = new MagickImage("temp/icon.png"))
{
     icon.Rotate(-10);
     icon.Write("temp/icon.png");
}
```

I've tried with 
```
    icon.BackgroundColor = MagickColors.Transparent;
    icon.AlphaColor = MagickColors.Transparent;
```
to get white space away, but unsuccessful

**Comment by denis-shevchenko** [comment]
Ok, it solve my problem
```
using (MagickImage icon = new MagickImage("temp/icon.png", new MagickReadSettings { BackgroundColor = MagickColors.Transparent }))
{
     icon.Rotate(-10);
     icon.Write("temp/icon.png");
}
```

**Comment by dlemstra** [comment]
Which version of Magick.NET are you using @denis-shevchenko? The following works for me:

using (MagickImage icon = new MagickImage("logo:"))
{
  icon.BackgroundColor = MagickColors.Transparent;
  icon.Rotate(-10);
  icon.Write("logo.png");
}

**Comment by dlemstra** [comment]
Can you share an image where it does not work? Or has your issue been resolved @denis-shevchenko?

**Comment by denis-shevchenko** [comment]
After update to version "7.0.4.701" the issue has been solved. Thanks a lot.
