### ISSUE TITLE
Background removal: mask to remove antialiasing

### ISSUE THREAD

**Issue by bwaldron** [dlemstra/Magick.NET#391]
- Magick.NET version: 7.0.0.0
- Environment: Windows .NET 4.7

@dlemstra, thanks for this library and your past help.  I am having trouble perfecting a background removal.  I'd like to emulate this command in Magick.NET (instead of white, I'd like to sample background after placing border to reduce error):

convert image \( -clone 0 -fuzz XX% -transparent white -blur 0x1 \) -alpha off -compose copy_opacity -composite resultimage

.NET code:

           using (var image = new MagickImage(pathToImage))
            {
                using (var mask = image.Clone())
                {
                    mask.ColorFuzz = new Percentage(10);
                    mask.BorderColor = MagickColors.White;
                    mask.Border(1);
                    mask.Settings.FillColor = MagickColors.Transparent;
                    mask.FloodFill(MagickColors.Transparent, 1, 1);
                    mask.Shave(1, 1);
                    mask.Blur();
                    image.Alpha(AlphaOption.Off);
                    mask.Composite(image, CompositeOperator.CopyAlpha);
                    mask.Write(pathToOutImage);
                }
            }

**Comment by dlemstra** [comment]
It looks like you need to composite the mask on the image instead of the image on the mask. This also means you will need to write the image instead of the mask.

**Comment by bwaldron** [comment]
Thanks @dlemstra!
