### ISSUE TITLE
Convert Stream to Jpeg

### ISSUE THREAD

**Issue by sonfiree** [dlemstra/Magick.NET#392]
Not work
```
void Test (Stream imageStream)
{
    var magicImage = new MagickImage(imageStream);
    var memoryStream = new MemoryStream();
    magicImage.Format = MagickFormat.Jpeg;
    magicImage.Write(memoryStream);
}
```

**Comment by dlemstra** [comment]
Not enough information.

What kind of error message do you get? And dont forget to add the missing `using` for the image and memory stream.

**Comment by sonfiree** [comment]
There is no message. Just for further work you need the format jpeg.

Here and then there are problems

**Comment by dlemstra** [comment]
I am sorry but I have no clue what your issue is. Can you describe your problem in more detail?

**Comment by sonfiree** [comment]
Ok. 
I need a `jpeg `image. What to get with him some manipulation. 

For example, such:


`Array.ConvertAll (_image.GetPixels (). GetValues (), x => (float) x / 255)`

Not work
```
void Test (Stream imageStream)
{
    using(magicImage = new MagickImage(imageStream))
    {
           var memoryStream = new MemoryStream();
           magicImage.Format = MagickFormat.Jpeg;
           magicImage.Write(memoryStream);
    }
}
```

It`s good
```

 public void Create(Stream imageStreams)
        {
            var magicImage = new MagickImage(StreamToJpeg(imageStreams));

            return new ImageMagic(magicImage);
        }

        private static byte[] StreamToJpeg(Stream imageStream)
        {
            using (var memoryStream = new MemoryStream())
            {
                var imageToStream = System.Drawing.Image.FromStream(imageStream);
                imageToStream.Save(memoryStream, System.Drawing.Imaging.ImageFormat.Jpeg);
                return memoryStream.ToArray();
            }
        }
```

**Comment by dlemstra** [comment]
I am sorry but I have no idea what you are trying to ask me.

**Comment by sonfiree** [comment]
I am trying to tell you that your library does not work correctly with `Stream ``PNG`.
And different results on Linux and Windows

**Comment by dlemstra** [comment]
But I really need more details. Can you describe in more detail why you think that it does not work correctly?
