### ISSUE TITLE
intermittent jpeg distortion while resizing

### ISSUE THREAD

**Issue by JasonIsraelGit** [dlemstra/Magick.NET#393]
### Prerequisites

- [x] I have written a descriptive issue title
- [] I have verified that I am using the latest version of Magick.NET

### System Configuration
ASP.Net Framework and Core
- Magick.NET version: Assembly Magick.NET-Q16-AnyCPU, Version=7.6.0.0
- Environment (Operating system, version and so on):
OS version: Microsoft Windows NT 10.0.14393.0

### Question
We occasionally see JPEG distortion. An example is attached including the original image and a distorted version.

 We can run the same code twice and receive a correctly formatted image in one run and an incorrect the next. But the behavior is not consistent.

Here is our code:
            var insert = GetJpg();

            MagickReadSettings settings = new MagickReadSettings();
            settings.SetDefine("filter:support", "2");
            settings.SetDefine("jpeg:fancy-upsampling", "off");
            settings.SetDefine("png:compression-filter", "5");
            settings.SetDefine("png:compression-level", "9");
            settings.SetDefine("png:compression-strategy", "1");
            settings.SetDefine("png:exclude-chunk", "all");
            settings.Compression = CompressionMethod.LosslessJPEG;

            using (var origImage = new MagickImage(, settings))
            {
                using (var image = origImage.Clone())
                {
                    image.Settings.Compression = CompressionMethod.JPEG;
                    UploadImage($"{insert.gid}_Orig", image.ToByteArray());
                }

                foreach (var size in ImageKeys.Sizes)
                {
                    using (var resize = origImage.Clone())
                    {
                        var resizeW = (int.Parse(size) < resize.BaseWidth) ? int.Parse(size) : resize.BaseWidth;

                        resize.FilterType = FilterType.Triangle;
                        resize.Quality = 92;
                        resize.Settings.Compression = CompressionMethod.JPEG;
                        resize.ColorSpace = ColorSpace.sRGB;
                        resize.Interlace = Interlace.NoInterlace;
                        resize.Thumbnail(resizeW, 2400);
                        resize.UnsharpMask(0.25, 0.08, 8.3, 0.045);
                        resize.Posterize(136);
                        resize.Strip();

                        UploadImage($"{insert.gid}_{size}", resize.ToByteArray());
                    }
                }
            }

**Comment by JasonIsraelGit** [comment]
![6604_orig](https://user-images.githubusercontent.com/38769985/53191879-a2aa8800-35d2-11e9-901b-e80641e175cb.jpg)
![6604_1200_or](https://user-images.githubusercontent.com/38769985/53191883-a50ce200-35d2-11e9-919b-66257fce84d0.jpg)

**Comment by dlemstra** [comment]
Can you reproduce this issue with the latest version?

**Comment by JasonIsraelGit** [comment]
We assumed you would ask that 👍 

So, we upgraded and are in UAT now.

**Comment by JasonIsraelGit** [comment]
Dirk - 

We have upgraded to the latest version and had a case where this occurred again today. Do you have an idea as to what we may me doing wrong?

Thanks for your help!
Jason

**Comment by dlemstra** [comment]
Can you give it another try with the latest version? And would it be possible to create a sample sample function that I can use to reproduce this issue? I have not been able to reproduce your issue.
