### ISSUE TITLE
AnimationIterations returns incorrect value

### ISSUE THREAD

**Issue by skpillai** [dlemstra/Magick.NET#394]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Created 2 gifs on ezgif.com. One set to animate once and then other set to animate unlimited times.
Opened them using a `MagickImageCollection` object. When I retireve the value stored in AnimationIterations property they both return 0 which is unexpected. 

### Steps to Reproduce
        private static int GetAnimationLoopCount(string gifFile)
        {
            using (var collection = new MagickImageCollection(gifFile))
            {
                if (collection.Count > 0)
                {
                    return collection[0].AnimationIterations;
                }
            }

            return -1;
        }

## System Configuration
- Magick.NET version: Magick.NET-Q8-AnyCPU.7.9.0.2
- Magick.NET version: Magick.NET-Q8-AnyCPU.7.11.0.0
Environment (Operating system, version and so on): Windows 10 Pro
- Additional information:

![no loop](https://user-images.githubusercontent.com/3324038/53295326-dab9f280-37ad-11e9-8022-38315324e56e.gif)

![gif loops unlimited times](https://user-images.githubusercontent.com/3324038/53295329-dee61000-37ad-11e9-91b9-57d6eb18369a.gif)

**Comment by dlemstra** [comment]
This appears to be a bug inside ImageMagick and I just pushed a patch to resolve this. In the next version of Magick.NET the image that animates once will return 1 instead of zero.
