### ISSUE TITLE
Flv support

### ISSUE THREAD

**Issue by deckertron9000** [dlemstra/Magick.NET#395]
### Is your feature request related to a problem? Please describe
This library does not currently support decoding/transforming Flv files

### Describe the solution you'd like
I'd like this library to support decoding/transforming Flv files

### Describe alternatives you've considered
I've considered calling into ffmpeg directly, but I would like to use this library if possible.

**Comment by dlemstra** [comment]
What happens when you read your file like this `mpeg:yourFile.flv`? You do need to have ffmpeg in your `%PATH%` for this to work.

**Comment by deckertron9000** [comment]
I'm using the stream based methods. Is there a ways to signal "mpeg" when using those methods?

**Comment by deckertron9000** [comment]
I got this working by passing in a MagickReadSettings format of mpeg. Is there any chance that Flv will have it's own format type in the future?

**Comment by dlemstra** [comment]
I will add the format before the next release.
