### ISSUE TITLE
Convert vector files (eps, ai, pdf) to SVG

### ISSUE THREAD

**Issue by NarekMayilyan** [dlemstra/Magick.NET#396]
### System Configuration
I'm using c# .net core 2.1

* Magick.NET version Magick.NET-Q16-AnyCPU 7.7.0:
* Windows 10 OS:

### Question
Is it possible to convert vector files (like eps, ai, pdf and another) to svg file and how can I do it??

**Comment by dlemstra** [comment]
You can but you shouldn't. ImageMagick will change the image from vector into raster and when you save it as svg you will get a vector image with dots. You should find another tool for that. No idea what you can use though.
