### ISSUE TITLE
undefined symbol: jpeg_mem_src on Linux

### ISSUE THREAD

**Issue by alexisbg** [dlemstra/Magick.NET#397]
### Description
On Ubuntu 18.04, Magick.NET rises the following error while the .so is loaded:
`
Dynamic Linking Error: /..../linux-x64/native/Magick.NET-Q8-x64.Native.dll.so: undefined symbol: jpeg_mem_src
`

### Steps to Reproduce
Everytime Magick.NET is added to a project running on Ubuntu 18.04.

### System Configuration
- Magick.NET version: 7.11.0.0
- Environment (Operating system, version and so on): Ubuntu 18.04 (WSL)
- Additional information:
libjpeg-turbo8 has been installed.
```shell
$ dpkg -l libjpeg*
||/ Name                                      Version                   Architecture
+++-=========================================-=========================-============
ii  libjpeg-dev:amd64                         8c-2ubuntu8               amd64
ii  libjpeg-turbo8:amd64                      1.5.2-0ubuntu5.18.04.1    amd64
ii  libjpeg-turbo8-dev:amd64                  1.5.2-0ubuntu5.18.04.1    amd64
un  libjpeg62-dev                             <none>                    <none>
un  libjpeg7-dev                              <none>                    <none>
ii  libjpeg8:amd64                            8c-2ubuntu8               amd64
ii  libjpeg8-dev:amd64                        8c-2ubuntu8               amd64
```

**Comment by dlemstra** [comment]
All the dependencies are statically linked so you should not get this error. And I have no clue why this is happening. Would it be possible to create a Dockerfile that demonstrates this issue? Currently only got a phone so it will be a while before I can take a look at it.

**Comment by dlemstra** [comment]
It appears the libraw links with jpeg and that doesn't happen under Windows. I disabled this and hope this will resolve your issue. Can you test this again when I published a new release @alexisbg?
