### ISSUE TITLE
Create an image with a specific pixel format and getting an IntPtr to the pixel data

### ISSUE THREAD

**Issue by osre77** [dlemstra/Magick.NET#399]
Is there a way to create an Image with an specific Pixel Format and get an IntPtr to the data?
I want to use ImageMagick to grab and process imeages from an GigE Camera.
For that the data needs to be stored in the correct Pixel Format (like BGR24) and I need an IntPtr so I can tell the Camera API where to store the Image data.
Using PixelSource and doing it pixel by pixel would be a performance nightmare.
Also all our own Image processing algorithms use unsafe code where I need the IntPtr.
I'm using Windows with C# (Q8_AnyCpu)
So is this already possible, or can I add this functionality?

**Comment by dlemstra** [comment]
I don't want to add an `Intptr` to the public API of Magick.NET. And even if this would be added it would conflict with the API of ImageMagick for accessing the pixels. You can copy an area instead of just an individual pixel. But I don't know if that would be possible with the API of your camera.

**Comment by osre77** [comment]
Thank you for the Response. Have to look for a different library then.

**Comment by hhyyrylainen** [comment]
I see there's now an API that gets an IntPtr to the underlying data. Which I was able to use after quite a bit of trouble as it seems like the underlying format is always RGB24 bits or RGBA32 bits as I thought I could control that somehow (and there's no example on how to do this). Luckily the library I'm sending data to can deal with both RGB and RGBA formats with 8-bit channels so I can use an efficient copy.

Just commenting here in case someone in the future also needs this:
```c#
public static unsafe void UpdateFrame(WriteableBitmap target, MagickImage frame)
{
    using (var lockedBitmap = target.Lock())
    {
        var sourcePixels = frame.GetPixelsUnsafe();
        var source = sourcePixels.GetAreaPointer(0, 0, frame.Width, frame.Height);

        // Manual math based on the expected format
        var sourceSize = (int)frame.Width * (int)frame.Height * (frame.HasAlpha ? 4 : 3);
        var destinationSize = lockedBitmap.RowBytes * target.PixelSize.Height;

        if (sourceSize != destinationSize)
            throw new Exception("Invalid bitmap size (logic error in copying)");

        Buffer.MemoryCopy(source.ToPointer(), lockedBitmap.Address.ToPointer(), destinationSize, sourceSize);
    }
}
```
