### ISSUE TITLE
Create lossless WebP

### ISSUE THREAD

**Issue by tompazourek** [dlemstra/Magick.NET#4]
The command line of ImageMagick is able to create lossless WebP images:

http://www.imagemagick.org/script/webp.php

Is it possible to achieve somehow through Magick.NET API?

Thanks!

**Comment by dlemstra** [comment]
You can set the 'defines' with the SetDefine method. The first example on the page from your post translates to this:

```C#
using(MagickImage image = new MagickImage("wizard:"))
{
  image.Quality = 50;
  image.SetDefine(MagickFormat.WebP, "lossless", true);
  image.Write("wizard.webp");
}
```

**Comment by tompazourek** [comment]
Thanks!

I thought there must be a way to define these kind of parameters. Works like a charm. :)

**Comment by ffMathy** [comment]
Shouldn't the "quality" parameter be redundant when it's lossless?

Can someone explain what this means?

**Comment by amar132** [comment]
I do not get SetDefine method on the MagickImage Class. I am using the version Magick.NET-Q16-AnyCPU : 7.4.6.0. Do I need to use someother version?
@dlemstra

**Comment by dlemstra** [comment]
Have you tried to upgrade to the latest version @amar132?

**Comment by amar132** [comment]
Well, found it under Settings like this ->  newImage.Settings.SetDefine(MagickFormat.WebP, "lossless", "false"); So this can be closed.

**Comment by ffMathy** [comment]
Can anyone respond to my question as well? 😅

**Comment by dlemstra** [comment]
Newer versions of Magick.NET contain a `WebPWriteDefines` class that can be used to set all the `WebP` encoding options.

@ffMathy I have no idea if the quality option is redundant when the `WebPWriteDefines.Lossless` value is set to `true`. You will probably need to read through the `WebP` documentation to figure that out.
