### ISSUE TITLE
Move exif code to another library?

### ISSUE THREAD

**Issue by dlemstra** [dlemstra/Magick.NET#40]
I wonder if I should move the code that reads the exif data to another project. On CodePlex the following issue was started: https://magick.codeplex.com/workitem/1424. I think it would be a good idea to add extra classes for the marker notes. And maybe even make parsing the exif data as good as exiftool.  The current code is shared by ImageSharp and Magick.NET and maybe other libraries could also use it. When those classes are added it might be time to move the code. Maybe we could use this: https://github.com/drewnoakes/metadata-extractor-dotnet. But it would be nicer if that library would split parsing the data and reading it from image files into two libraries.

**Comment by 48design** [comment]
In my opinion it is great to have an "all in one" solution. The less dependencies the better.

**Comment by flemingm** [comment]
I agree,  factor out the Maker notes in to extra classes.   
Note: I have not looked at ImageSharp or metadata-extractor-dotnet yet.

Good reference for parsing them is Phil's exiftool site:
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html
 
Examples of using RAW and XMP metadata would be useful.  I can provide sample image file and text file with the data they contain.

**Comment by flemingm** [comment]
We have been experimenting with using metadata-extractor-dotnet for reading Metadata and translating to write with Magick.Net.   

We are finding some good suggest for some formats (JPEG). Some other formats we are not success in writing even if the format support it. 

We will share some findings once we finish testing and investigating.

**Comment by spinningcat** [comment]
That could be nice to use exif tool or something else to get exif information. Some exif information is particularly useful in determining image quality I think.

**Comment by dlemstra** [comment]
The Exif code has been moved to a new library called Magick.NET.Core that can be downloaded here: https://www.nuget.org/packages/Magick.NET.Core/
