### ISSUE TITLE
Can I display a Image in WPF without creating a copy of the data

### ISSUE THREAD

**Issue by osre77** [dlemstra/Magick.NET#400]
I'm using WPF for my UI.
Can I somehow Display the Image without getting a copy?
When I look at the CreateBitmapSource method. it 1st copies the data to an Byte Array from which the BitmapSource is created.
I gues a custom implementation of an ImageSource might do the trick here.
I want to grab a live Image from an GigE Camera into a Image and then just invalidate the ImageSource instead of recopying all the data again and again.
I want to use Q8_AnyCpu on Windows.

**Comment by dlemstra** [comment]
I don't think you can avoid the copy. Otherwise both the MagickImage and the BitmapSource would own the pixel data.

**Comment by osre77** [comment]
Thank you for your response
