### ISSUE TITLE
Load image from byte[] with length

### ISSUE THREAD

**Issue by rotvel** [dlemstra/Magick.NET#401]
Please consider adding a MagickImage constructor / Read overload that takes a byte array plus a length

It seems the length of available bytes is already taken into consideration (private void Read(byte[] data, int length, MagickReadSettings readSettings, bool ping), but right now it's always set to the length of the array.

This would save me a bunch of array conversions in a current project.

**Comment by dlemstra** [comment]
Don't mind adding this but can you explain why you are in this situation in more detail? And I am also wondering if there should be an overload that specifies both the length and offset.

**Comment by rotvel** [comment]
Yeah, length + offset overloads would give the optimal flexibility. No need for just a length overload then.

I read png files from a pipe and send the byte arrays to Magick for conversion/saving. I'd like to have one image buffer from start to end of the process, for performance and to enable buffer reuse.

**Comment by dlemstra** [comment]
Will be back home in two weeks and then add this feature and try to publish a new release as soon as possible.

**Comment by rotvel** [comment]
Excellent, thank you. Enjoy your trip :)
