### ISSUE TITLE
Thumbnail JPG - How to reproduce ImageMagick command line in Magick.Net?

### ISSUE THREAD

**Issue by nauticalcoder** [dlemstra/Magick.NET#404]
### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU/7.4.2
- Environment (Operating system, version and so on):
CSharp Script on Azure Function

### Question
I am using Magick.Net to produce thumbnails and it has been working flawlessly for most of my applications.  I have one case where I am taking a PNG, overlaying another image, converting it to a JPG, then producing 2 thumbnails of the JPG, one at 1000x1000 and the other at 45x45.  The 1000x1000 looks fine, but the 45x45 is either a completely black image or an image that is 50% artifacts.  When I run this command using ImageMagick, the image looks fine, but I can't reproduce these results in Magick.Net:
`convert -quality 95 OriginalImage.png -thumbnail 45x45 OriginalImage-tn.jpg`
Here is an example of the artifacts I am referring to:
![16660-45](https://user-images.githubusercontent.com/8966100/54449958-a50d8700-4725-11e9-9eea-296deaa6d91e.jpg)
` blankImage.Quality = 95;`
`blankImage.Format = MagickFormat.Jpg;`
`var previewImage = new MagickImage(originalImage);`
`var previewGeometry = new MagickGeometry(1000);`
`previewImage.Thumbnail(previewGeometry);`
`var thumbnailImage = new MagickImage(originalImage);`
`var thumbnailGeometry = new MagickGeometry(45);`
`thumbnailImage.Thumbnail(thumbnailGeometry);`

**Comment by nauticalcoder** [comment]
Does anyone have an idea what is going on here and how to correctly replicate my IM command line in code?

**Comment by dlemstra** [comment]
Can you share your input image so I can try to reproduce this?
