### ISSUE TITLE
A few questions for faster exif and image loading

### ISSUE THREAD

**Issue by xupefei** [dlemstra/Magick.NET#405]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
Windows 7 to 10

- Magick.NET version: 7.7.0.0
- Environment (Operating system, version and so on): Windows 7 to 10

### Question
First off, thanks for your wonderful library. I am now working on the QuickLook project (you might still remember it since you have once left a comment there. Thanks!) which provides quick file preview to users. The flow is as follows:

1. Determine the dimension of the target image file (to create a window of proper size)
2. Provide a low-quality preview of the file, e.g. the embedded thumbnail.
3. Decode the full image and render it to `BitmapSource`.

Steps 1 and 2 should be *really* fast since the user sees nothing during Step 1, and sees only a loading icon until a thumbnail is generated in Step 2.

In my old implementation, I use another library for steps 1 and 2, but that library supports only a few formats and hence not good. I am now considering to use Magick.NET for all three steps. Could you tell me

1. Is there a quick way to get image dimensions? As for now, I can only use
```
var image = new MagickImage("img.jpg")) . <-- this step is slow for huge images
var profile = image.GetExifProfile();
```
but the new MagickImage class tries to decode the full image and hence slow.

2. Is there a fast way to get low-resolution thumbnails even for huge files, like `DecodeWidth` provided by .NET Framework ([MSDN link](https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.imaging.bitmapimage.decodepixelwidth?view=netframework-4.7.2))? Something like `new MagickImage("img.jpg", decodeWidth=width)` will be wonderful.

3. When an image has, let's say, Display P3 colour profile, I have to convert it to sRGB (`image.AddProfile(sRGB)`) to make it display better. But `AddProfile` is slow for large images ([one bug report here](https://github.com/QL-Win/QuickLook/issues/188)). Can I do any faster?

Thanks for your work again, and I am looking forward to your comments.

**Comment by dlemstra** [comment]
You can quickly get the dimensions with the `Ping` method. And I am not sure but I think you can get a low res image if you specify the width and height in the read settings when your input is a jpeg file. The image also has a `ToBitmapSource` method, does that work for you?

**Comment by xupefei** [comment]
Thanks for your fast reply!

> You can quickly get the dimensions with the Ping method. 

Wonderful, This method is *really* fast!

> you can get a low res image if you specify the width and height in the read settings when your input is a jpeg file

Unfortunately, this does not work. It works for images with undefined dimension (e.g. `xc:yellow`) but not with normal image files like JPG. Here it the code:
```
var timer = Stopwatch.StartNew();

////// the code below does not work.
//var setting = new MagickReadSettings {Width = 200};

////// this works but slower than without settings. Seems it first decode then resize.
var setting = new MagickReadSettings {ExtractArea = new MagickGeometry(200)};

using (var image = new MagickImage())
{
    image.Read(@"jpg.jpg", setting);
    box.Source = image.ToBitmapSource();
}
timer.Stop();
MessageBox.Show(timer.Elapsed.TotalSeconds.ToString());
```
Any comment on this?

**Comment by dlemstra** [comment]
Yeah you are right I was thinking about something else. Will close this issue for now, feel free to reopen this if you need more help.
