### ISSUE TITLE
Add load image from byte[] with length to Ping method

### ISSUE THREAD

**Issue by rotvel** [dlemstra/Magick.NET#408]
This is a follow up to https://github.com/dlemstra/Magick.NET/issues/401

It would also be useful to add a similar overload to the MagickImage.Ping method 
Ie: Ping(byte[] data, int offset, int count)

**Comment by dlemstra** [comment]
I was already planning to add this after the release. Thanks for opening this PR to remind me 👍

**Comment by rotvel** [comment]
Well your labels were kinda suggestive so I have a feature branch that adds the Ping overload (and reorders the overload calls). I'm used to Github from work, so if you give me access I'll push my branch and open a pull request for you to look at.

**Comment by dlemstra** [comment]
You can create a fork and then push to that fork instead and open a PR from the branch in your fork.

p.s. Thanks for the gift and for working on your first PR ever 👍

**Comment by rotvel** [comment]
https://github.com/dlemstra/Magick.NET/pull/415
