### ISSUE TITLE
Opening and re saving a png image changes the color of the image

### ISSUE THREAD

**Issue by Unavi** [dlemstra/Magick.NET#409]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I open a png image and save it to a new location it changes color: 
![Magick color change](https://user-images.githubusercontent.com/5324745/54888147-cba48e00-4e9a-11e9-9b80-c35d15a4c236.png)
As far as I have gathered it is only happening with pngs. They look the same if I open them with photoshop, but the colors are wrong in Windows and Chrome.

### Steps to Reproduce
`using (var image = new MagickImage(originalPath))
{
                image.Write(newPath);
            }`
### System Configuration
- Magick.NET version: Magick.NET-Q16-AnyCPU_7.11.1
- Environment (Operating system, version and so on): Windows 10
- Additional information: .net core

**Comment by dlemstra** [comment]
It looks like a color profile issue. Can you share your input image?

**Comment by Unavi** [comment]
Yes of course.
![source](https://user-images.githubusercontent.com/5324745/54916812-a5aed600-4efa-11e9-8e0f-452261795874.png)
![target](https://user-images.githubusercontent.com/5324745/54916813-a5aed600-4efa-11e9-83de-f2b5e6a38f99.png)

**Comment by t246246** [comment]
First image has  Gamma: 1, Intensity: Undefined.
Saved image has Gamma: 1, Intensity: Rec709Luminance.

**Comment by Unavi** [comment]
I generated the first image with [Xabe.FFmpeg](https://github.com/tomaszzmuda/Xabe.FFmpeg) out of an mp4 video.
Do you have any ideas what I should do to fix the problem?
Could I just read the values from the input image and copy them to the target image?

**Comment by Unavi** [comment]
Some further information. I tried to create a collage with 
`using (var collage = collection.Mosaic())`
but it hat the same color problem, but with 
`                using (var collage = collection.Montage(new MontageSettings()
                {
                    Geometry = geometry
                })`
it worked.

**Comment by dlemstra** [comment]
We are still investigating why this is happening. What happens when you change the colorspace of the image to `sRGB`?

**Comment by Unavi** [comment]
sRGB doesn't change the result.
`            using (var image = new MagickImage(originalPath))
            {
                image.ColorSpace = ColorSpace.sRGB;
                image.Write(newPath);
            }`

**Comment by Unavi** [comment]
Converting the image to jpg with -gamma 0.454545 returns a jpg with proper colors.
But converting the image to png with -gamma 0.454545 returns a png with wrong colors:
![test](https://user-images.githubusercontent.com/5324745/55013797-2698cb00-4fea-11e9-8414-02fe74ca8feb.png)
If I convert it with -gamma 1 to a png, Windows shows it for a short time with proper colors but then brightens it up. If I open the png version with -gamma 0.454545 it stays dark and doesn't change. 

Converting the proper jpg to a png with the standard gamma 1 results in a proper png.

**Comment by Unavi** [comment]
![Magick](https://user-images.githubusercontent.com/5324745/55015660-8d6bb380-4fed-11e9-97ce-edb6264c1bb3.png)

**Comment by urban-warrior** [comment]
It appears our PNG coder maintainer, who is no longer with us, wanted to identify linear RGB images so that ImageMagick can support both linear (RGB) and non-linear (sRGB) images in the PNG format.  The test appears to be incorrect.  A patch to fix it is in GIT master branch @ https://github.com/ImageMagick/ImageMagick.  The patch will be available in the beta releases of ImageMagick @ https://www.imagemagick.org/download/beta/ by sometime tomorrow.
