### ISSUE TITLE
System.OverflowException when reading density in jpeg image in Magick.NET-Q16-HDRI

### ISSUE THREAD

**Issue by asierad** [dlemstra/Magick.NET#41]
My simplified code goes like this:

```C#
      var imageData = File.ReadAllBytes(@"ffed5e2f-359c-481f-b236-281360a91df7.JPG");
      using (MagickImage image = new MagickImage())
      {
        image.Read(imageData);
        var density = image.Density; //throws System.OverflowException - Arithmetic operation resulted in an overflow.
      }
```

Sample file can be downloaded from [https://cadworxshared.blob.core.windows.net/magicknet/ffed5e2f-359c-481f-b236-281360a91df7.JPG](https://cadworxshared.blob.core.windows.net/magicknet/ffed5e2f-359c-481f-b236-281360a91df7.JPG)

Please note that this happens when using x64 with both Magick.NET-Q16-HDRI-AnyCPU and Magick.NET-Q16-HDRI-x64. It seems to work correctly in x86 but I need to use x64.

Thanks in advance.

**Comment by dlemstra** [comment]
Which version of Magick.NET are you using?

**Comment by asierad** [comment]
I'm using version 7.0.4.701

**Comment by dlemstra** [comment]
I can reproduce your issue, will check if my fix in ImageMagick was correct later this week.

**Comment by dlemstra** [comment]
I will most likely publish a new release in two weeks that will resolve your issue.

**Comment by asierad** [comment]
Thanks!

**Comment by dlemstra** [comment]
The new release has been publish can you give it another try and close this issue if it is resolved @asierad?

**Comment by asierad** [comment]
Seems to be working perfectly in version 7.0.5.500, closing.
