### ISSUE TITLE
Crop throws MagickOptionErrorException when height of Rectangle is 0.

### ISSUE THREAD

**Issue by t246246** [dlemstra/Magick.NET#410]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When the width is 0, i.e. `image.Crop(new ImageMagick.MagickGeometry(1, 2, 0, 3));`, it does not throw exception, however when height is 0 it throws exception:

 ImageMagick.MagickOptionErrorException: invalid geometry `3+1+2' @ error/geometry.c/ParseGravityGeometry/1250  

which I guess is not intended, at least not symmetric to the case width = 0. Although the image with width or height = 0 is probably useless.

Comparison to ImageMagick CLI:
```
P:\>magick logo: -crop 0x1+1+1 NUL

P:\>magick logo: -crop 1x0+1+1 NUL

P:\>magick logo: -crop x0+1+1 NUL

P:\>magick logo: -crop 0x+1+1 NUL

P:\>magick logo: -crop x+1+1 NUL

P:\>magick logo: -crop 0+1+1 NUL
magick: invalid argument for option '-crop' '0+1+1' at CLI arg 2 @ error/operation.c CLISimpleOperatorImage/2134.
```

### Steps to Reproduce
```
using (var image = new ImageMagick.MagickImage("logo:"))
{
    image.Crop(new ImageMagick.MagickGeometry(1, 2, 3, 0));
}
```

### System Configuration
Install Q16 AnyCPU version from Nuget.

- Magick.NET version: 7.1.1.0
- Environment (Operating system, version and so on): Windows 7 and 10 (64 bit)
- Additional information:

**Comment by t246246** [comment]
Just a few result how the latest ImageMagick (ImageMagick-7.0.8-35-Q16-HDRI-x64-dll) behave for the width/height 0.
It looks 0 is regarded as the image width or height.
```
P:\>magick identify -format "%g\n" logo:
640x480+0+0
P:\>magick logo: -crop 10x0+0+0 +repage PNG:- | magick identify -format "%g\n" -
10x480+0+0
P:\>magick logo: -crop 0x10+0+0 +repage PNG:- | magick identify -format "%g\n" -
640x10+0+0
P:\>magick logo: -crop 0x0+2+2 +repage PNG:- | magick identify -format "%g\n" -
638x478+0+0
P:\>magick logo: -crop 0x0+0+0 +repage PNG:- | magick identify -format "%g\n" -
640x480+0+0
```
It's same the target image is other format:
```
P:\>magick logo: -crop 0x0+0+0 +repage TIFF:- | magick identify -format "%g\n" -
640x480+0+0
```

Except SUN that might has some bug.
```
P:\>magick logo: -crop 0x0+0+0 +repage SUN:- | magick identify -format "%g\n" -
640x480+0+0
P:\>magick logo: -crop 0x0+1+0 +repage SUN:- | magick identify -format "%g\n" -
identify: ImproperImageHeader `C:/Users/tozaki/AppData/Local/Temp/magick-16864T4
ZEuil5PHVJ' @ error/sun.c/ReadSUNImage/499.
P:\>magick logo: -crop 0x0+2+0 +repage SUN:- | magick identify -format "%g\n" -
638x480+0+0
```

**Comment by dlemstra** [comment]
Thanks for reporting this issue. It will be resolved in the next release of Magick.NET
