### ISSUE TITLE
Undefined symbols on Linux native library

### ISSUE THREAD

**Issue by Alloc86** [dlemstra/Magick.NET#413]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using the latest Magick.NET release (7.11.1.0 from https://www.nuget.org/packages/Magick.NET-Q8-x64/ ) I get errors on Linux when the .NET library tries to load the native module. This can easily be verified independently of .NET with just running `ld` on the library:

```
# ld Magick.NET-Q8-x64.Native.dll.so 
ld: warning: cannot find entry symbol _start; not setting start address
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_key_create'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_getspecific'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_mutexattr_destroy'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_create'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_mutexattr_init'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `ForwardFourierTransformImage'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_key_delete'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `InverseFourierTransformImage'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `AnimateImages'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_setspecific'
Magick.NET-Q8-x64.Native.dll.so: undefined reference to `pthread_join'
```

PS: Getting this error when Magick.NET is first accessed from code in a Unity application:
```
Plugins: Couldn't open /.../libMagick.so, error: /.../libMagick.so: undefined symbol: ForwardFourierTransformImage
```

The libraries for Win32, Win64 and macOS work just fine though.

### Steps to Reproduce
Download Q8-x64 v7.11.1.0 and run `ld runtimes/linux-x64/native/Magick.NET-Q8-x64.Native.dll.so`

### System Configuration
- Magick.NET version: 7.11.1.0
- Environment: XUbuntu 16.04 x86_64

**Comment by dlemstra** [comment]
Thanks for reporting this. I just pushed some changes to resolve this.

**Comment by Alloc86** [comment]
Wow, this was really fast, thank you :)

**Comment by dlemstra** [comment]
You should be able to download it from this build: https://dev.azure.com/dlemstra/Magick.NET/_build/results?buildId=1056&view=results. The `drop` zip contains the new `.so` files.

**Comment by Alloc86** [comment]
Thanks, it's working fine now :)

**Comment by dlemstra** [comment]
Will try to publish a new release this weekend to resolve this for everyone.
