### ISSUE TITLE
Pixel Cache - Behaviour with lots of smaller images

### ISSUE THREAD

**Issue by EdgarRuizSE** [dlemstra/Magick.NET#416]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:  NuGet Q8 -> 7.11.1
- Environment: Windows 64bit,  64GB Ram

### Question
I am unsure of Pixel's Cache behaviour when there are a lot of smaller images. 

It is my understanding that pixel cache works when larger images are being loaded. But I am unsure on 2 things:

1) Does it take into account the system's available memory? or it just triggers (with its default configuration) depending on the image size?
2) Does it take into account all images created by the application? or the need for pixel cache is evaluated in an individual basis.

### My specific case

I ask this because I have an application that generate a lot of smaller images and I end up merging them all together in a single large image. This has worked well in the past, the merged images have been fairly large, but not as much as a new requirement. And this is why I got this question.

I estimate that this new requirement could create about 40,438 images, of approximately 1500x1500 px each.

This is why I have the question, Obviously each of the smaller images can be stored in memory, but there will be a point where memory will run out with the amount of images being generated. If the pixel cache is able to be triggered by knowing the total number of images being generated OR it simply queries the available RAM memory then I should not have issues. But if it doesn't  then I have to figure out a work around this, maybe start merging the images in smaller batches before merging the full image.  But this will be slower and if I can I'd rather avoid it.

Thanks!

**Comment by dlemstra** [comment]
I am not a 100% sure but I think you are asking when the pixel cache (in other words: store the pixels on disk instead of memory) is being used. This happens automatically and you don't need to worry about it. When ImageMagick runs out of pixel memory it will swap to disk automatically.

**Comment by EdgarRuizSE** [comment]
That's good to know, so I can rest asured that it'll start storing on disk when a critical mass is achieved, no matter if it is one Large image or thousands of smaller ones. Right?

Thanks!

**Comment by dlemstra** [comment]
That is correct and right.
