### ISSUE TITLE
Memory Just Keeps Increasing

### ISSUE THREAD

**Issue by GlennIM** [dlemstra/Magick.NET#417]
### Prerequisites

- [x] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of Magick.NET
- [ x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I run the code below several times in my application and look at the Task Manager the memory just keeps increasing. What can I do to keep the memory usage low.

### Steps to Reproduce
`
        private void applyImageTransformationClean(string imgURL, string FontFamily, string headingStr, string randomHeadlineStr, string imgFileName)
        {
            var image = new MagickImage(imgURL);

            MagickImage imageresult;
            MagickImage modimage;
            Color backgroundColorForTopBottom;
            Color borderColor;
            int ExtentHeight = 70;
            MagickImage mask = null;
            MagickImageCollection images;
            MagickImage branding;
            MagickImage topheading;
            MagickImage heading;
            MagickImage randomHeadline;

            // passing the FontFamily parameter is used for testing fonts to see how they look
            // if nothing is passed in a random font will be found and used
            if (FontFamily == "")
            {
                FontFamily = GetRandomFontFamily();
            }

            try
            {
                KnownColor[] names = (KnownColor[])Enum.GetValues(typeof(KnownColor));

                // START BRANDING/LABEL CODE
                // Start with a collection because multiple images will be combined.
                using (images = new MagickImageCollection())
                {
                    int widthOfImage = GetProperFontSize(image);

                    backgroundColorForTopBottom = GetRandomizedKnownColor();

                    var topheaderSnippetreadSettings = new MagickReadSettings()
                    {
                        BackgroundColor = backgroundColorForTopBottom,

                        FontFamily = FontFamily, // -font Helvetica-Condensed-Light
                                                 // FontFamily = GetRandomFontFamily(), // -font Helvetica-Condensed-Light

                        Width = image.Width - 190,
                        FillColor = IdealTextColor(backgroundColorForTopBottom),
                        FontWeight = FontWeight.Bold
                    };

                    var headerSnippetreadSettings = new MagickReadSettings()
                    {
                        BackgroundColor = backgroundColorForTopBottom,

                        FontFamily = FontFamily, // -font Helvetica-Condensed-Light
                                                 // FontFamily = GetRandomFontFamily(), // -font Helvetica-Condensed-Light

                        Width = image.Width - 60,
                        FillColor = IdealTextColor(backgroundColorForTopBottom),
                        FontWeight = FontWeight.Bold
                    };

                    // This will make the background of the label Khaki.
                    var readSettings = new MagickReadSettings()
                    {
                        BackgroundColor = backgroundColorForTopBottom,
                        FontFamily = "Helvetica-Condensed-Light", // -font Helvetica-Condensed-Light
                        FontPointsize = widthOfImage - 10, // -pointsize 26
                        FillColor = IdealTextColor(backgroundColorForTopBottom),
                        FontWeight = FontWeight.Bold
                    };

                    // Create the label image.
                    branding = new MagickImage("label:" + moneySiteDomainName, readSettings);

                    branding.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100

                    // Create the label image.
                    topheading = new MagickImage("label:" + headingStr, topheaderSnippetreadSettings);
                    heading = new MagickImage("label:" + headingStr, headerSnippetreadSettings);
                    randomHeadline = new MagickImage("label:" + randomHeadlineStr, headerSnippetreadSettings);

                    topheading.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100
                    heading.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100
                    randomHeadline.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100

                    // Bottom
                    if (currentTemplate == Templates.Image_Branding)
                    {
                        images.Add(image);
                        images.Add(branding);
                    }

                    // Top & Bottom
                    if (currentTemplate == Templates.Heading_Image_Branding)
                    {
                        images.Add(topheading);
                        images.Add(image);
                        images.Add(branding);
                    }

                    // Bottom with 2 Snippets
                    if (currentTemplate == Templates.Image_Heading_Branding)
                    {
                        images.Add(image);
                        images.Add(heading);
                        images.Add(branding);
                    }

                    if (currentTemplate == Templates.Heading_Image_RandomHeadline_Branding)
                    {
                        images.Add(topheading);
                        images.Add(image);
                        images.Add(randomHeadline);
                        images.Add(branding);
                    }

                    // Append the images to create the output image.
                    using (var result = images.AppendVertically())
                    {
                        imageresult = new MagickImage(result);

                        // imageresult gets disposed of in the rounding code below, so need to write the imageresult to a new image
                        modimage = new MagickImage(imageresult);
                    }
                }
                // END BRANDING/LABEL CODE

                // using (var image = new MagickImage(imgURL))
                if (specialEffects == SpecialEffects.RoundedCorners || specialEffects == SpecialEffects.RoundedCorners_ColoredBorders || specialEffects == SpecialEffects.RoundedCorners_Frames3D || specialEffects == SpecialEffects.RoundedCorners_Frames3D_Swirl || specialEffects == SpecialEffects.RoundedCorners_Raise)
                {
                    using (imageresult)
                    {
                        using (mask = new MagickImage(MagickColors.White, imageresult.Width, imageresult.Height))
                        {
                            var size = 150;

                            new ImageMagick.Drawables()
                                .FillColor(MagickColors.Black)
                                .StrokeColor(MagickColors.Black)
                                .Polygon(new PointD(0, 0), new PointD(0, size), new PointD(size, 0))
                                .Polygon(new PointD(mask.Width, 0), new PointD(mask.Width, size), new PointD(mask.Width - size, 0))
                                .Polygon(new PointD(0, mask.Height), new PointD(0, mask.Height - size), new PointD(size, mask.Height))
                                .Polygon(new PointD(mask.Width, mask.Height), new PointD(mask.Width, mask.Height - size), new PointD(mask.Width - size, mask.Height))
                                .FillColor(MagickColors.White)
                                .StrokeColor(MagickColors.White)
                                .Circle(size, size, size, 0)
                                .Circle(mask.Width - size, size, mask.Width - size, 0)
                                .Circle(size, mask.Height - size, 0, mask.Height - size)
                                .Circle(mask.Width - size, mask.Height - size, mask.Width - size, mask.Height)
                                // .BorderColor(MagickColors.Red)
                                .Draw(mask);

                            // This copies the pixels that were already transparent on the mask.
                            using (var imageAlpha = imageresult.Clone())
                            {
                                imageAlpha.Alpha(AlphaOption.Extract);
                                imageAlpha.Opaque(MagickColors.White, MagickColors.None);
                                mask.Composite(imageAlpha, CompositeOperator.Over);
                            }

                            mask.HasAlpha = false;
                            imageresult.HasAlpha = false;
                            imageresult.Composite(mask, CompositeOperator.CopyAlpha);

                            // imageresult gets disposed of so need to write the imageresult to a new image
                            modimage = new MagickImage(imageresult);
                        }
                    }
                }

                // Add colored border to the image
                if (specialEffects == SpecialEffects.RoundedCorners_ColoredBorders)
                {
                    borderColor = GetBorderColor(); // get a random reddish color

                    modimage.BorderColor = borderColor;
                    modimage.Border(1);

                    // apply a 3D frame even if the border color is a reddish color
                    modimage = Create3DFramedBorder(modimage);
                }
                else if (specialEffects == SpecialEffects.RoundedCorners_Frames3D)
                {
                    modimage.BorderColor = MagickColors.White;
                    modimage.Border(1);

                    // apply a 3D frame
                    modimage = Create3DFramedBorder(modimage);
                }
                else if (specialEffects == SpecialEffects.RoundedCorners_Frames3D_Swirl)
                {
                    modimage.BorderColor = MagickColors.White;
                    modimage.Border(1);

                    // apply a 3D frame
                    modimage = Create3DFramedBorder(modimage);

                    modimage.Swirl(25.0);
                }
                else if (specialEffects == SpecialEffects.RoundedCorners_Raise)
                {
                    modimage.BorderColor = MagickColors.White;
                    modimage.Border(1);

                    // modimage = Create3DFramedBorder(modimage);

                    modimage.Raise(25);
                }
                else if (specialEffects == SpecialEffects.RoundedCorners)
                {
                    modimage.BorderColor = MagickColors.White;
                    modimage.Border(1);
                }

                // write the image to the appropriate directory
                modimage.Write(pinImagesCSVLocationPathLocal + "\\" + imgFileName);

                // also write the image to the fixed path under output so they all can be viewed
                modimage.Write(allPinImagesLocationPathLocal + "\\" + imgFileName);

                FileInfo imageMod = new FileInfo(pinImagesCSVLocationPathLocal + "\\" + imgFileName);

                optimizer.Compress(imageMod);

                displayStatus("Image Created and Compressed: " + imgFileName);

                // show the image in the picture box
                pinImagePB.Image = Image.FromFile(imageMod.FullName);
                // resize the image to fit the PictureBox size
                pinImagePB.SizeMode = PictureBoxSizeMode.StretchImage;
                pinImagePB.Refresh();

                try
                {
                    image.Dispose();
                    images.Dispose();
                    branding.Dispose();
                    topheading.Dispose();
                    heading.Dispose();
                    randomHeadline.Dispose();
                    mask.Dispose();
                    imageresult.Dispose();
                    modimage.Dispose();
                }
                catch { };
            }
            catch { };
        }
`

### System Configuration
Windows 7 - 4bit

- Magick.NET version: Magick.NET-Q16-AnyCPU
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dalibor-sanzeru** [comment]
Hi,
- Firstly - I hope this code is only demo code and you dont want to use it in production.
- NEVER EVER use empty CATCHES (imagine what will happend if your first image.Dispose() fail e.g null reference exception on 'image.'? -> following Disposes will never be called and you what is even WORST will never know about that - Isnt this happend in your code just now? Who knows?.
- Start to refactor to smaller pieces and use using where possible in shortest live-period as possible.
-in this 3-page-long code from PASCAL 80-ties -> is looking for not called Dispose() night-mare.
- you can try this: 
https://www.codeproject.com/Articles/42721/Best-Practices-No-5-Detecting-NET-application-memo

**Comment by GlennIM** [comment]
Thanks for the help in this. After I call the Dispose() method on ImageMagic objects, do I need to call GC.Collect() to force the garbage collector to run?

**Comment by dalibor-sanzeru** [comment]
If you need to call GC.Collect you are doing something wrong.

Please, Provide some exception you get if you call your routine multiple times. Try to call 100x or 1000x .. and check if you have memory exceptions -> BUT UNCOMMENT EMPTY CATCHES BEFORE to see these excetions.

**Comment by GlennIM** [comment]
Yes. Thanks.

Would it be better to create my image objects using "new MagickImage() only once in the class this method is called and just reuse these objects, and then after the class containing the method ends, Dispose those image objects. That way I'm not constantly creating NEW images object in this method that is called 100's of times.

**Comment by GlennIM** [comment]
Can you tell me how to just create a new MagickImage()  and reuse object instead of "newing" it every-time I want to load an image into the variable?

**Comment by GlennIM** [comment]
I redid some of my code but watching either the Task Manager or Perfmon, running this method numberous times, causes an "Out Of Memory" exception. I looked at the code long and hard but see no potential memory leaks. I have the latest Magick package installed. Can any expert here see any possible code that could be leaking memory?

`        private void ApplyImageTransformationClean(string imgURL, string FontFamily, string headingStr, string randomHeadlineStr, string imgFileName)
        {
            MagickImage imageresult;
            MagickImage modimage;
            Color backgroundColorForTopBottom;
            Color borderColor;
            int ExtentHeight = 70;
            MagickImage mask = null;
            MagickImageCollection images;
            IMagickImage result;
            MagickImage branding;
            MagickImage topheading;
            MagickImage heading;
            MagickImage randomHeadline;
            ImageMagick.Drawables drawables;

            using (var image = new MagickImage(imgURL))
            {
                // passing the FontFamily parameter is used for testing fonts to see how they look
                // if nothing is passed in a random font will be found and used
                if (FontFamily == "")
                {
                    FontFamily = GetRandomFontFamily();
                }

                try
                {
                    KnownColor[] names = (KnownColor[])Enum.GetValues(typeof(KnownColor));

                    // START BRANDING/LABEL CODE
                    // Start with a collection because multiple images will be combined.
                    using (images = new MagickImageCollection())
                    {
                        int widthOfImage = GetProperFontSize(image);

                        backgroundColorForTopBottom = GetRandomizedKnownColor();

                        var topheaderSnippetreadSettings = new MagickReadSettings()
                        {
                            BackgroundColor = backgroundColorForTopBottom,

                            FontFamily = FontFamily, // -font Helvetica-Condensed-Light
                                                     // FontFamily = GetRandomFontFamily(), // -font Helvetica-Condensed-Light

                            Width = image.Width - 190,
                            FillColor = IdealTextColor(backgroundColorForTopBottom),
                            FontWeight = FontWeight.Bold
                        };

                        var headerSnippetreadSettings = new MagickReadSettings()
                        {
                            BackgroundColor = backgroundColorForTopBottom,

                            FontFamily = FontFamily, // -font Helvetica-Condensed-Light
                                                     // FontFamily = GetRandomFontFamily(), // -font Helvetica-Condensed-Light

                            Width = image.Width - 60,
                            FillColor = IdealTextColor(backgroundColorForTopBottom),
                            FontWeight = FontWeight.Bold
                        };

                        // This will make the background of the label Khaki.
                        var readSettings = new MagickReadSettings()
                        {
                            BackgroundColor = backgroundColorForTopBottom,
                            FontFamily = "Helvetica-Condensed-Light", // -font Helvetica-Condensed-Light
                            FontPointsize = widthOfImage - 10, // -pointsize 26
                            FillColor = IdealTextColor(backgroundColorForTopBottom),
                            FontWeight = FontWeight.Bold
                        };

                        // Create the label image.
                        branding = new MagickImage("label:" + moneySiteDomainName, readSettings);

                        branding.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100

                        // Create the label image.
                        topheading = new MagickImage("label:" + headingStr, topheaderSnippetreadSettings);
                        heading = new MagickImage("label:" + headingStr, headerSnippetreadSettings);
                        randomHeadline = new MagickImage("label:" + randomHeadlineStr, headerSnippetreadSettings);

                        topheading.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100
                        heading.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100
                        randomHeadline.Extent(image.Width, ExtentHeight, Gravity.Center); // height was 100

                        // Bottom
                        if (currentTemplate == Templates.Image_Branding)
                        {
                            images.Add(image);
                            images.Add(branding);
                        }

                        // Top & Bottom
                        if (currentTemplate == Templates.Heading_Image_Branding)
                        {
                            images.Add(topheading);
                            images.Add(image);
                            images.Add(branding);
                        }

                        // Bottom with 2 Snippets
                        if (currentTemplate == Templates.Image_Heading_Branding)
                        {
                            images.Add(image);
                            images.Add(heading);
                            images.Add(branding);
                        }

                        if (currentTemplate == Templates.Heading_Image_RandomHeadline_Branding)
                        {
                            images.Add(topheading);
                            images.Add(image);
                            images.Add(randomHeadline);
                            images.Add(branding);
                        }

                        // Append the images to create the output image.
                        using (result = images.AppendVertically())
                        {
                            imageresult = new MagickImage(result);

                            // imageresult gets disposed of in the rounding code below, so need to write the imageresult to a new image
                            modimage = new MagickImage(imageresult);
                        }


                    } // using (images = new MagickImageCollection())

                    // END BRANDING/LABEL CODE

                    // using (var image = new MagickImage(imgURL))
                    if (specialEffects == SpecialEffects.RoundedCorners || specialEffects == SpecialEffects.RoundedCorners_ColoredBorders || specialEffects == SpecialEffects.RoundedCorners_Frames3D || specialEffects == SpecialEffects.RoundedCorners_Frames3D_Swirl || specialEffects == SpecialEffects.RoundedCorners_Raise)
                    {
                        using (imageresult)
                        {
                            using (mask = new MagickImage(MagickColors.White, imageresult.Width, imageresult.Height))
                            {
                                var size = 150;

                                drawables = new ImageMagick.Drawables()
                                    .FillColor(MagickColors.Black)
                                    .StrokeColor(MagickColors.Black)
                                    .Polygon(new PointD(0, 0), new PointD(0, size), new PointD(size, 0))
                                    .Polygon(new PointD(mask.Width, 0), new PointD(mask.Width, size), new PointD(mask.Width - size, 0))
                                    .Polygon(new PointD(0, mask.Height), new PointD(0, mask.Height - size), new PointD(size, mask.Height))
                                    .Polygon(new PointD(mask.Width, mask.Height), new PointD(mask.Width, mask.Height - size), new PointD(mask.Width - size, mask.Height))
                                    .FillColor(MagickColors.White)
                                    .StrokeColor(MagickColors.White)
                                    .Circle(size, size, size, 0)
                                    .Circle(mask.Width - size, size, mask.Width - size, 0)
                                    .Circle(size, mask.Height - size, 0, mask.Height - size)
                                    .Circle(mask.Width - size, mask.Height - size, mask.Width - size, mask.Height)
                                    // .BorderColor(MagickColors.Red)
                                    .Draw(mask);  

                                // This copies the pixels that were already transparent on the mask.
                                using (var imageAlpha = imageresult.Clone())
                                {
                                    imageAlpha.Alpha(AlphaOption.Extract);
                                    imageAlpha.Opaque(MagickColors.White, MagickColors.None);
                                    mask.Composite(imageAlpha, CompositeOperator.Over);
                                }

                                mask.HasAlpha = false;
                                imageresult.HasAlpha = false;
                                imageresult.Composite(mask, CompositeOperator.CopyAlpha);

                                // imageresult gets disposed of so need to write the imageresult to a new image
                                modimage = new MagickImage(imageresult);
                            }
                        }
                    }

                    // Add colored border to the image
                    if (specialEffects == SpecialEffects.RoundedCorners_ColoredBorders)
                    {
                        borderColor = GetBorderColor(); // get a random reddish color

                        modimage.BorderColor = borderColor;
                        modimage.Border(1);

                        // apply a 3D frame even if the border color is a reddish color
                        modimage = Create3DFramedBorder(modimage);
                    }
                    else if (specialEffects == SpecialEffects.RoundedCorners_Frames3D)
                    {
                        modimage.BorderColor = MagickColors.White;
                        modimage.Border(1);

                        // apply a 3D frame
                        modimage = Create3DFramedBorder(modimage);
                    }
                    else if (specialEffects == SpecialEffects.RoundedCorners_Frames3D_Swirl)
                    {
                        modimage.BorderColor = MagickColors.White;
                        modimage.Border(1);

                        // apply a 3D frame
                        modimage = Create3DFramedBorder(modimage);

                        modimage.Swirl(25.0);
                    }
                    else if (specialEffects == SpecialEffects.RoundedCorners_Raise)
                    {
                        modimage.BorderColor = MagickColors.White;
                        modimage.Border(1);

                        // modimage = Create3DFramedBorder(modimage);

                        modimage.Raise(25);
                    }
                    else if (specialEffects == SpecialEffects.RoundedCorners)
                    {
                        modimage.BorderColor = MagickColors.White;
                        modimage.Border(1);
                    }

                    // write the image to the appropriate directory
                    modimage.Write(pinImagesCSVLocationPathLocal + "\\" + imgFileName);

                    // also write the image to the fixed path under output so they all can be viewed
                    modimage.Write(allPinImagesLocationPathLocal + "\\" + imgFileName);

                    FileInfo imageMod = new FileInfo(pinImagesCSVLocationPathLocal + "\\" + imgFileName);

                    optimizer.Compress(imageMod);

                    displayStatus("Image Created and Compressed: " + imgFileName);

                    // show the image in the picture box
                    pinImagePB.Image = Image.FromFile(imageMod.FullName);
                    // resize the image to fit the PictureBox size
                    pinImagePB.SizeMode = PictureBoxSizeMode.StretchImage;
                    pinImagePB.Refresh();

                    try
                    {
                        image.Dispose();
                        images.Dispose();
                        branding.Dispose();
                        topheading.Dispose();
                        heading.Dispose();
                        randomHeadline.Dispose();
                        mask.Dispose();
                        imageresult.Dispose();
                        modimage.Dispose();
                        result.Dispose();

                        displayStatus("In applyImageTransformationClean(): Disposed All Image Objects");
                    }
                    catch (Exception disposeEsc)
                    {
                        displayStatus("In applyImageTransformationClean(): Failed To Dispose Image Objects: " + disposeEsc.Message);
                    };
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Error in Apply applyImageTransformationClean(): " + ex.Message);
                };
            }

        }`

**Comment by dlemstra** [comment]
I am sorry but this is just too much code. That try block with `Dispose` does not make sense to me. You should try to split up your code in different methods (you might want to read this: https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) and use a `using` block where you need it. Then it will be much easier for you to determine where you are using so much memory by commenting out code so you can pint point the problem.
