### ISSUE TITLE
How rotate image without quality loss

### ISSUE THREAD

**Issue by dalibor-sanzeru** [dlemstra/Magick.NET#418]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: latest for 
- Environment (Operating system, version and so on): Windows 10 pro

### Question
How can I rotate image without quality loss? Currently with this code when multiple times rotation is called - quality is degradating with each rotation. When I Set image.Quality = 100, quality isnt degradated, but image has full size -> e.g. from 200kB -> 600kB.

THANKS!

```
protected virtual Size RotateAndSaveImage(double degrees, string imageFullPath)
        {
            Size newSize = null;
            byte[] imageContent = this.osService.ReadFileContent(imageFullPath);

            using (var stream = new MemoryStream(imageContent))
            {
                stream.Position = 0;

                using (MagickImage image = new MagickImage(stream))
                {
                    image.Rotate(degrees);
                    newSize = new Size(image.Width, image.Height);

                    this.osService.SaveFileContent(imageFullPath, image.ToByteArray());
                }
            }

            return newSize;
        }
```

**Comment by dlemstra** [comment]
Do you have some example images that show de degradation? There can be some when you do a rotation at an "odd" angle like 15.7 and I don't think that you can avoid that. And what are your input images?

**Comment by dalibor-sanzeru** [comment]
Hi, 
thanks for fast response.
User is rotating 90 degrees (turn to right) e.g. 10times in a row (because he is user :) ).

Images are attached. The worst one is rotated multiple times.
![notrotated](https://user-images.githubusercontent.com/19836016/55553770-67c36600-56e1-11e9-8ecc-fbf40326c116.jpg)
![rotated](https://user-images.githubusercontent.com/19836016/55553771-67c36600-56e1-11e9-8668-8f981551a8ad.jpg)

**Comment by dlemstra** [comment]
That last image is not rotated? 

If it is possible you should avoid the intermediate rotations when you save the image. When the user has done 10 times a 9 degree rotation you somehow only remember the total rotation (90 degrees) and rotate the original image 90 degrees and then save it.

**Comment by dalibor-sanzeru** [comment]
Scenario:
User on web-UI has button - 'rotate-90-degrees-right'.
I need to rotate each time he clicks. 

- First time on upload I am using quality 80 percent => image.Quality = 80.

- Then I rotate: When then load image from storage and call rotate image.quality is get on image.Quality automatically to 80 again.
- Each time by rotation quality image is decreased to 80 by calling this function above (RotateAndSaveImage)

- Question also is: Can I rotate image without quality loss? Something like use rotation with 100 quality and then save as 80. When i set quality to 100 it has 600KBytes after first rotation.

**Comment by dlemstra** [comment]
When a JPEG image is opened, edited and saved again it results in additional image degradation. It's very important to minimize the number of editing sessions between the initial and final version of a JPEG image. My advise would be to keep a copy of the original image and do your operations on that image and then save the result as a separate image.
