### ISSUE TITLE
Error when loading a TIF file: Wrong length of decoded string

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#42]
Hi,

I got error message when trying to load a TIF file. This only happens on specific file.

**My code:**
```
using (var magicImg = new MagickImage(path)) {
        //
}
```

**Sample file:**
http://netghost.narod.ru/gff/sample/images/tiff/marbles.tif
http://netghost.narod.ru/gff/sample/images/tiff/index.htm

**Error message:**
![image](https://cloud.githubusercontent.com/assets/3154213/24069801/f22948a2-0beb-11e7-8680-a7587715b30c.png)

**Windows Photo Viewer can open it!**
![image](https://cloud.githubusercontent.com/assets/3154213/24069827/6f1af14e-0bec-11e7-8083-7ae97ab1704a.png)

**Comment by dlemstra** [comment]
Your image is corrupt. The Windows Photo Viewer will just show black pixels at the part that is corrupt. ImageMagick will throw an exception instead and stop decoding the image. This is the expected behavior.

**Comment by d2phap** [comment]
Thanks,
I tried saving a copy by Paint. So I works.
