### ISSUE TITLE
Liquid Rescale - extra options?

### ISSUE THREAD

**Issue by Tylertron1998** [dlemstra/Magick.NET#421]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Latest Nuget OpenMP, Q16
- Environment (Operating system, version and so on): Ubuntu 16.04

### Question

Hi there - while browsing the library for python, I came across two extra arguments that I don't seem to find here. 
```
delta_x (numbers.Real) – maximum seam transversal step. 0 means straight seams. default is 0
rigidity (numbers.Real) – introduce a bias for non-straight seams. default is 0
``` 

wondering what these are - and how to pass them via your library - if at all possible. For reference, here is the link: http://docs.wand-py.org/en/0.5.2/wand/image.html#wand.image.BaseImage.liquid_rescale

**Comment by dlemstra** [comment]
You can specify those arguments by setting the offset of the geometry but I should probably make this easier by adding some extra overloads for this. And this would also mean that you can specify a double instead of an integer.

**Comment by Tylertron1998** [comment]
I assume this means using the MagikGeometry class, right? Not sure what properties this would map too - what would be the delta_x and what would be the rigidity? Thank you for your reply.

**Comment by dlemstra** [comment]
Yes you need to use the MagickGeometry class and Delta=x and rigidity is y.

**Comment by Tylertron1998** [comment]
Awesome - thank you for the help (: is it possible to use a double or float instead of an integer at all with the current implementation?

**Comment by dlemstra** [comment]
You can only use integers for now, for float/double a new overload needs to be added.
