### ISSUE TITLE
Load image from Stream

### ISSUE THREAD

**Issue by esmelov** [dlemstra/Magick.NET#422]
Magick.NET-Q16-AnyCPU v7.11.1

I load from net image and try create "MagickImage", but i catch next error:

```
using (var httpResponseStream = await httpResponse.Content.ReadAsStreamAsync())
{
    using (var image = new MagickImage(httpResponseStream))
    {
        var size = new MagickGeometry(width, height);
        image.Resize(size);
        image.Format = MagickFormat.Jpg;
        image.Write(outStream);
     }
}
```
```
ImageMagick.MagickCoderErrorException: TIFF directory is missing required "ImageLength" field. `MissingRequired' @ error/tiff.c/TIFFErrors/656
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImage.Read(Stream stream, MagickReadSettings readSettings, Boolean ping)
```

If I load "MagickImage" from a file then there is no such error:

```
using (var image = new MagickImage(path))
{
    var size = new MagickGeometry(width, height);
    image.Resize(size);
    image.Format = MagickFormat.Jpg;
    image.Write($"{path}_{image.Width}x{image.Height}.jpg");
}
```

I split file on part, please remove "zip" in the end.

[sony_a7_iii_01.001.zip](https://github.com/dlemstra/Magick.NET/files/3062857/sony_a7_iii_01.001.zip)
[sony_a7_iii_01.002.zip](https://github.com/dlemstra/Magick.NET/files/3062858/sony_a7_iii_01.002.zip)
[sony_a7_iii_01.003.zip](https://github.com/dlemstra/Magick.NET/files/3062859/sony_a7_iii_01.003.zip)
[sony_a7_iii_01.004.zip](https://github.com/dlemstra/Magick.NET/files/3062860/sony_a7_iii_01.004.zip)

**Comment by dlemstra** [comment]
It looks like you are not resetting the position of your input stream: `httpResponseStream.Position = 0;`

**Comment by esmelov** [comment]
@dlemstra 
![image](https://user-images.githubusercontent.com/22498629/55867263-d7769c80-5b8a-11e9-9548-45e8702d3bf0.png)

I try also httpResponseStream.Seek(0, SeekOrigin.Begin);

**Comment by dlemstra** [comment]
The `ReadAsStreamAsync` class is apparently doing this already. Have you tried doing a byte wise comparison to check if both streams contain the same data? Maybe something odd is happening in front of this?

**Comment by esmelov** [comment]
@dlemstra I was wrong, I'm sorry. the successful creation "MagickImage" only if loaded from file path on device.
```
using (var image = new MagickImage(path))
{
    var size = new MagickGeometry(width, height);
    image.Resize(size);
    image.Format = MagickFormat.Jpg;
    image.Write($"{path}_{image.Width}x{image.Height}.jpg");
}
```

**Comment by dlemstra** [comment]
ImageMagick will try to guess the file format because you are reading from a stream and guesses that your file is a TIFF file. When reading from file it sees the `.arw` extension and knows your file is a RAW file. If you want to read from a stream you will need to tell Magick.NET the format of the file:

```C#
var settings = new MagickReadSettings { Format = MagickFormat.Raw };
using (var image = new MagickImage(stream, settings))
{
}
```

**Comment by esmelov** [comment]
@dlemstra thank you, it works.
