### ISSUE TITLE
Could not load file or assembly 'Magick.NET-Q16-x64, Version=7.11.1.0

### ISSUE THREAD

**Issue by fhnaseer** [dlemstra/Magick.NET#423]
### Description
I get the following exception when I try to use ImageMagick in my application.

System.BadImageFormatException: 'Could not load file or assembly 'Magick.NET-Q16-x64, Version=7.11.1.0, Culture=neutral, PublicKeyToken=2004825badfa91ec' or one of its dependencies. An attempt was made to load a program with an incorrect format.'

### Steps to Reproduce
1. Create a new console application.
2. Add Magick.NET-Q8-x64-OpenMP nuget package to your application.
3. Create MagickImage object.
4. Run the application.
5. Exception occurs.

### System Configuration
Windows 10 Enterprise 64-bit. Build 17134 .
Intel Xeon CPU E5-2680
64GB RAM

- Magick.NET version:
- Magick.NET-Q8-x64-OpenMP, 7.11.1.0,

**Comment by fhnaseer** [comment]
Exe folder has the following files.

- Console.Framework.exe
- Magick.NET-Q16-x64.dll
- Magick.NET-Q16-x64.Native.dll
- Magick.NET-Q16-x64.xml

**Comment by dlemstra** [comment]
You are trying to load a 64-bit version of Magick.NET in a 32-bit application.

**Comment by fhnaseer** [comment]
Application is Any CPU. I also tried x64 config. But still error is there.

**Comment by dlemstra** [comment]
You should only get that exception when you are mixing 64-bit and 32-bit. Can you create a sample application that demonstrates this issue and share this in a public repo on GitHub?

**Comment by fhnaseer** [comment]
You can try this. I tried x64 and Any CPU. And I always get the error.
https://github.com/fhnaseer/CSharping/tree/master/Console/Console.Framework

**Comment by dlemstra** [comment]
With the following diff applied I have no issues running your Console.Framework application.
```diff
 Console/Console.Framework/Console.Framework.csproj | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/Console/Console.Framework/Console.Framework.csproj b/Console/Console.Framework/Console.Framework.csproj
index c6728ed..97fbcd5 100644
--- a/Console/Console.Framework/Console.Framework.csproj
+++ b/Console/Console.Framework/Console.Framework.csproj
@@ -17,7 +17,7 @@
     </NuGetPackageImportStamp>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
-    <PlatformTarget>AnyCPU</PlatformTarget>
+    <PlatformTarget>x64</PlatformTarget>
     <DebugSymbols>true</DebugSymbols>
     <DebugType>full</DebugType>
     <Optimize>false</Optimize>
@@ -25,6 +25,7 @@
     <DefineConstants>DEBUG;TRACE</DefineConstants>
     <ErrorReport>prompt</ErrorReport>
     <WarningLevel>4</WarningLevel>
+    <Prefer32Bit>false</Prefer32Bit>
   </PropertyGroup>
   <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
     <PlatformTarget>AnyCPU</PlatformTarget>
```

**Comment by fhnaseer** [comment]
My bad. Need to disable Prefer32Bit flag only and then it works in both AnyCPU and x64 configurations.
