### ISSUE TITLE
Error: The type initializer for 'NativeMagickImageCollection' threw an exception.

### ISSUE THREAD

**Issue by bkraul** [dlemstra/Magick.NET#424]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
With the last 2 versions of Magick.NET I am getting the error:
```
Error: The type initializer for 'NativeMagickImageCollection' threw an exception.
```

### Steps to Reproduce
Working with an MagickImageCollection as such:
```csharp
// create a collection of images in order to support multi-page.
using (MagickImageCollection pages = new MagickImageCollection())
{
...
}
```
This does not happen on release 7.10.2.

- Magick.NET version: .7.11.1 and 7.11.0.
- Environment (Operating system, version and so on): This has happened on Windows 10 Build 1809, and Windows 7.

**Comment by dlemstra** [comment]
And what is the exception that is being raised?

**Comment by bkraul** [comment]
@dlemstra, thanks for the reply. I am trying to get that information for you at the moment. Our situation might be a little different and might play into this error. We have a company-wide lockdown software called Carbon Black Security which basically ties down execution of exes and dlls unless they are either signed, have consistent publisher information that can be whitelisted, or at least are running inside a folder that is authorized.

I know this might actually need to be on another issue but it seems related, because this issue only happens on machines with that software. Here is my question.

The software is saying that an assembly is trying to be run in `magick.net-q8-x86.native.dll	c:\users\[user]\appdata\local\temp\magick.net.net40.7.11.1.0\`. Why would this be the case, if the application where the assembly is being loaded actually runs out of `C:\MyCompany\MyApp` which is an authorized folder by the software I just described?

**Comment by bkraul** [comment]
The `AppData\Local\Temp\magick.net.net40.7.11.1.0` behavior happens also on my dev machine which does not have the lock down software installed, and only for the last 2 versions. 7.10.2 does not do this.

**Comment by dlemstra** [comment]
This always happens with the AnyCPU version of Magick.NET. You can control the location of the folder with `MagickAnyCPU.CacheDirectory`.

**Comment by bkraul** [comment]
Setting the property you mentioned seems to have corrected the problem. I was never able to zero-in to the actual exception because my development environment is not restricted with the locking software. But it seems it was indeed caused by the default caching to the temp folder. As soon I configured to go to an authorized folder, the problem disappeared. Thanks again for your help.

**Comment by Yoda-Man** [comment]
I am getting this error only when I deploy the project it works fine from the dev project in visual studio
