### ISSUE TITLE
gif file wrong when I write a MagickImageCollection to a FileStream

### ISSUE THREAD

**Issue by Rinacm** [dlemstra/Magick.NET#425]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I'm trying to read some images from stream and then coalesce them to file, I found that when I use `MagickImageCollection.Write(string fileName)` method it runs correctly, but if I create a `FileStream` and then write it to stream the image will display like a static picture

### Steps to Reproduce
here's my code
```C#
var bytes = new MemoryStream(File.ReadAllBytes("E:\\VSProjects\\Resources\\response.zip"));
var dis = new List<MemoryStream>();
using (var zipArchive = new ZipArchive(bytes, ZipArchiveMode.Read)) {
    foreach (var zipArchiveEntry in zipArchive.Entries) {
        using (var stream = zipArchiveEntry.Open()) {
            var memoryStream = new MemoryStream();
            stream.CopyTo(memoryStream);
            memoryStream.Position = 0L;
            dis.Add(memoryStream);
        }
    }
}

using (var fs = new FileStream("E:\\VSProjects\\Resources\\test.gif", FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None)) {
    using (var collection = new MagickImageCollection()) {
        foreach (var imageStream in dis) {
            var img = new MagickImage(new Bitmap(Image.FromStream(imageStream))) {
                AnimationDelay = 100
            };
            collection.Add(img);
        }
        var settings = new QuantizeSettings {Colors = 256};
        collection.Quantize(settings);
        collection.Optimize();
        collection.Write(fs);
    }
}
```

### System Configuration

- Magick.NET version: .Net Framework 4.7.2
- Environment (Operating system, version and so on): Windows10 Pro 1809  (17763.437)
- Additional information: Visual Studio 2019

**Comment by dlemstra** [comment]
When you write to a stream ImageMagick will not know the output format. You should use the overload with `MagickFormat`: `collection.Write(fs, MagickFormat.Gif)`.

And the `MagickImageCollection` can read your image without loading it in a Bitmap first.

**Comment by Rinacm** [comment]
problem solved,thanks
