### ISSUE TITLE
Taking long time to generate a thumbnail

### ISSUE THREAD

**Issue by newETA** [dlemstra/Magick.NET#426]
I am trying to crop the image  and then resize it but it's taking a long time and time isn't consistent as well sometimes the same image will take about 10 sec sometimes more than that as well I experiment with  "imageresizing.net" the same image it's doing really fast within 3sec I was expecting same with  Magick.net as well.   Do you guys think I am missing anything in my code and that blocking the processing time?

The magick.net  will get base64 data string with removed unnecessary characters and convert it to bytes prior to start the processing of the image. 

My Code is below. 
```
public string GenerateThumbnail(CartImageData sci)
        {
           
            var imageFile = sci.ImageData;

            int isGrayscale = sci.isGrayscale;


            int img_height = sci.img_height;
            int img_width = sci.img_width;

            int img_x = sci.img_x;
            int img_y = sci.img_y;
            double img_scale = sci.img_scale;
            double crop_angle_degrees = sci.crop_angle_degrees;

            string is_ios = sci.is_ios;


            var datas = Convert.FromBase64String(imageFile);

        
            string entension = ".png";
            string newFileName = Guid.NewGuid().ToString();
            string thumbnailFileName = newFileName + "t" + entension;
          

            string savedThumnailLocation = Server.MapPath(@"~/content//thumbnail/" + thumbnailFileName);
          
            Percentage percent = new Percentage(img_scale * 100);

            using (MagickImage img = new MagickImage(datas))
            {
                var profile = img.GetExifProfile();

                if (is_ios == "true")
                {
                    img.AutoOrient();
                }

                var width_before = img.Width;

                img.Rotate(crop_angle_degrees);

                img.Scale(percent);
                var width = img.Width;

                img.Crop((img_x), img_y, img_width, img_height);

                var after_crop_width = img.Width;

                if (isGrayscale > 0)
                {
                    img.ColorSpace = ColorSpace.Gray;
                }

              img.Density = new Density(300, 300);

                MagickGeometry ge = new MagickGeometry(img_width, img_height);
               // ge.IgnoreAspectRatio = true;
               // img.Resize(ge);

                int thumbsize = 100;

                if (img.Width > img.Height)
                {
                    decimal ratio = img.Width / thumbsize;
                    int thumbWidth = thumbsize;
                    int thumbHeight = (int)((decimal)img.Height / ratio);
                    ge = new MagickGeometry(thumbWidth, thumbHeight);
                }
                else
                {
                    decimal ratio = img.Height / thumbsize;
                    int thumbWidth = (int)((decimal)img.Width / ratio);
                    int thumbHeight = thumbsize;
                    ge = new MagickGeometry(thumbWidth, thumbHeight);
                }
                ge.IgnoreAspectRatio = false;
                img.Resize(ge);
                img.Write(savedThumnailLocation);
            }

            string ImageFileName = string.Format("/content/thumbnail/{0}", thumbnailFileName); 


            return ImageFileName;
        }
```
Thank you.

**Comment by dlemstra** [comment]
Could you enter the information that was requested in the issue template?

**Comment by newETA** [comment]
If I understand correct please find the basic information for as follows:

          var imageFile = sci.ImageData;  //base64 base string please check in file link below file

            int isGrayscale = sci.isGrayscale;  // false(0)


            int img_height = sci.img_height; //900px
            int img_width = sci.img_width; //2400px

            int img_x = sci.img_x; //0
            int img_y = sci.img_y; //350
            double img_scale = sci.img_scale; //0.4
            double crop_angle_degrees = sci.crop_angle_degrees; // 0.0

            string is_ios = sci.is_ios; //NA

But these all information as you know will change based on the user selection. 

[base64Data.txt](https://github.com/dlemstra/Magick.NET/files/3090299/base64Data.txt) 

Thank you.

**Comment by dlemstra** [comment]
Where are you running this code? Which version are you using? Is your application (or website??) running in 32-bit or 64-bit mode?

**Comment by newETA** [comment]
Magic.Net-Q8-x64 and Version is 7.6.0.0 and we are using this for Website and running on 64 Bit mode.  Code is now in two places one is in my local another one is hosted.  Local is a little faster than server If you want you can check in the Dev site as well. 

http://dev.waluv.com/chooseprint is our dev site which is doing manipulation using Magic.Net library and  https://www.waluv.com/chooseprint  the production which is currently using "imageresizing.net" only for thumbnail for in background we are doing another process with Magic.net which is fine because of no user interaction involved in this. 

If you want you can give a test drive Dev vs Production before I used Magic.net for the production as well due to slow in performance I temporary changed with different code.  You can see the difference with the same image.

**Comment by newETA** [comment]
any updates in this please above sites may treat same because now both are running the Magick.net

**Comment by dlemstra** [comment]
You are doing a lot of operations on the image and I am having trouble to understand what you want to do. Have you tried to add logging to figure out which part of the operation is slow?
