### ISSUE TITLE
Exception thrown when opening CR2 file

### ISSUE THREAD

**Issue by Tichau** [dlemstra/Magick.NET#430]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When I try to open a CR2 file with the following code:

```
MagickReadSettings readSettings = new MagickReadSettings(new TiffReadDefines());
readSettings.Format = MagickFormat.Cr2;

using (MagickImage image = new MagickImage(this.InputFilePath, readSettings))
{
}
```

I get the following exception:

    ImageMagick.MagickCoderErrorException
        HResult=0x80131500
        Message=Input/output error `C:\Test\IMG_0422.CR2' @ error/dng.c/ReadDNGImage/429
        Source=Magick.NET-Q16-AnyCPU
        StackTrace:
        at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
        at ImageMagick.MagickImage.NativeMagickImage.ReadFile(MagickSettings settings)
        at ImageMagick.MagickImage.Read(String fileName, MagickReadSettings readSettings, Boolean ping)
        at ImageMagick.MagickImage..ctor(String fileName, MagickReadSettings readSettings)
        at FileConverter.ConversionJobs.ConversionJob_ImageMagick.Convert() in C:\Users\Adrien\Documents\GitHub\FileConverter\Application\FileConverter\ConversionJobs\ConversionJob_ImageMagick.cs:line 77

Note: I also tried without specifying the format, it generates the same exception. I added the format because of this mention in the documentation "Requires an explicit image format otherwise the image is interpreted as a TIFF image (e.g. cr2:image.cr2)."

### Steps to Reproduce
See the code and stacktrace linked in the description.

### System Configuration
Windows 10 64bits with ImageMagick-Q16-AnyCPU  v7.12.0

**Comment by dlemstra** [comment]
Can you share your image? It looks like libraw is unable to read that image.

**Comment by Tichau** [comment]
I can't share the image I'm using right now. I'll send you another image that reproduce the issue as soon as I find one.

**Comment by dlemstra** [comment]
Feel free to reach out by email if you want to share the image privately. It looks like you are getting some kind of IO error but without the file I would just be guessing where that is happening.

**Comment by Tichau** [comment]
The file was corrupted so ImageMagick was not able to open it.
