### ISSUE TITLE
Write TIFF corruption

### ISSUE THREAD

**Issue by DHitchenUK** [dlemstra/Magick.NET#432]
### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of Magick.NET
- [ x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Open a HEIC image and save as TIFF. The output TIFF image is corrupt and cannot be read by Windows. Performing the same with an output to JPG works perfectly, as does PNG.

### Steps to Reproduce
No errors produced. Windows cannot open the TIFF file

### System Configuration
Windows 10 1809 and 1903

- Magick.NET version: c7.12.0 Magck.NET-Q16-AnyCPU
- Environment (Operating system, version and so on): Visual Studio and Nuget Package
- Additional information:

**Comment by dlemstra** [comment]
It appears that Windows does not support the `YCBCR` color space. You will need to change the color space of the image to sRGB before you save the image.

**Comment by DHitchenUK** [comment]
Thank you, that helped a little. I run through 60 HEIC files, previously, 0 converted to tiff successfully, with the color space change, 5 now convert successfully. 55 do not. 

Windows Photo Viewer says "it appears that we do not support this file format"
