### ISSUE TITLE
Help with MagickImage.Compare

### ISSUE THREAD

**Issue by mudithaa** [dlemstra/Magick.NET#433]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET 

### System Configuration
Windows, Visual Studio 2019, C# with Magick.NET-Q16-AnyCPU version="7.12.0"

- Magick.NET version: 7.12.0
- Environment (Operating system, version and so on): Windows 10

### Question
I'm comparing an approved image with a new image. On visual inspection, I cannot see any changes at all. Where as the MagickImage.Compare method returns a double which is more than 0 and the delta image points to pixels which are hard to see by the naked eye. 

both images are png files. 

the code looks like below.
var result = testImage.Compare(approvedImage, ErrorMetric.Fuzz, delta)
if(result <>0)
{
   // something is not right
}
How do I tell the method to ignore minor pixel changes. As right now I'm getting lots of false positives.

**Comment by dlemstra** [comment]
The value that is being returned is a double. So instead of checking for zero you could check how close to zero  this is. Or you could tweak the `testImage.ColorFuzz` value and you will end up with zero when the images are almost the same.

**Comment by mudithaa** [comment]
Thanks for the quick reply.
I've tried that too. But when I compare an entirely different image I get a 0.2 where as some minor differences return 3.XXXX

With testImage.Fuzz should I set that to new Percentage(5) or less or higher ? I've not had much luck with that too

**Comment by dlemstra** [comment]
It probably depends what kind of value you should use. I think you should play around with the `ColorFuzz` value so more because that will probably help you the most. And you might need to do both. So first set the `ColorFuzz` and then check how close the value is to zero.

**Comment by mudithaa** [comment]
Hi thanks again and sorry for the long gap. Didn't get the chance to go back try it. 
I've created a git repo with what I'm trying to do. And it doesn't work for me even after changing the colourfuzz. The images that should fail then pass.

The images directory have the expected image and a generated image and to the naked eye they are the same. But they fail my comparison. 

When I use the color fuzz, then the images in Invalidimages directory also pass along with the generated image.

https://github.com/mudithaa/magic-image-compare

**Comment by dlemstra** [comment]
I just noticed that you use `ErrorMetric.Fuzz` to compare the images. I would advise you to switch to `ErrorMetric.RootMeanSquared` instead. My apologies for not seeing this much earlier. You probably need to play around with the `ColorFuzz` some more than `15%` looks a bit to high.

**Comment by mudithaa** [comment]
Thanks again for the reply. I tried that but the result of the compare remains the same for all the comparisons. In other words changing the ErrorMetric.RootMeanSquared and also the percentage to 85, 95, 50 didn't change the compare result. they remain the same.

**Comment by mudithaa** [comment]
![image](https://user-images.githubusercontent.com/4200294/63557143-d9b22400-c58a-11e9-9a59-22cae0b4aff1.png)
above is the output from the console app on git repo
below is the delta image generated when I compare two similar images. 

![637021503903286003](https://user-images.githubusercontent.com/4200294/63557161-f2bad500-c58a-11e9-879a-ca912d01fffa.png)

**Comment by dlemstra** [comment]
Are you sure that you are using the same code to generate that image? I am getting the following delta image:

![637021688675459908](https://user-images.githubusercontent.com/10426229/63594147-f748b300-c5b5-11e9-8074-ea9f9e1cd627.png).

But I played some more with your examples and for this type of image I got the best result when I remove the `ColorFuzz` and use `ErrorMetric.PerceptualHash` instead.

**Comment by mudithaa** [comment]
Thanks dlemstra. that did work in the sample project. But in the actual project it was really slow compared to other methods we tried. In the end we changed the screen resolution (these images are screenshots) to 1280 *1024 (previously 1900* something). and that worked with ErrorMetric.Fuzz 
thanks again for your help.
