### ISSUE TITLE
Pango throws an exception in Linux

### ISSUE THREAD

**Issue by bluerain610** [dlemstra/Magick.NET#434]
### Source Code

        public IActionResult test()
        {
            using (MemoryStream ms = new MemoryStream())
            {
                using (MagickImage image = new MagickImage())
                {
                    image.Read("pango:Some Text");
                    image.Format = MagickFormat.Png;
                    image.Write(ms);
                }

                return new FileContentResult(ms.ToArray(), "image/png");
            }
        }

### Exception
		
   middleware ex=ImageMagick.MagickBlobErrorException: UnableToOpenBlob 'Some Text': No such file or directory @ error/blob.c/OpenBlob/3495
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(MagickSettings settings)
   at ImageMagick.MagickImage.Read(String fileName, MagickReadSettings readSettings, Boolean ping)
   

### Version

- Magick.NET version: Magick.NET-Q16-AnyCPU
- Environment (Operating system, version and so on): CentOS Linux release 7.6.1810
- .Net Version：Net Core 2.2

### Question

Please have a look at the following issue: In NetCore app, Pango can be used successfully in Windows system, but an exception is thrown in Linux.

**Comment by dlemstra** [comment]
I have no idea why I have not responded to this issue last year. But this is not working on Linux because the Linux build has no Pango support.

**Comment by dlemstra** [comment]
The new release has just been published and it includes support for pango on Linux and macOS.
