### ISSUE TITLE
Issues with Multiple IIS 

### ISSUE THREAD

**Issue by Sitanshu89** [dlemstra/Magick.NET#435]
### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.11.0
- Environment (Operating system, version and so on): Windows 8, 64 bit

### Question

I have two different application in my IIS, and in both the application I am using ImageMagic for converting SVG to PNG and both the application has two different application pool.
In one application it is working fine but in another application it is throwing exception saying "The type initializer for 'NativeMagickSettings' threw an exception."
But if I am using one pool for both the application then it is working fine.

Please let me know how to use for two application pool.
I am using Magick.NET-Q16-AnyCPU.

**Comment by dlemstra** [comment]
What kind of exception is being raised? And do both application pools have the same settings?

**Comment by Sitanshu89** [comment]
Getting below exception 
System.TypeInitializationException: The type initializer for 'X64' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x64.Native.dll': Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

Yes both the pools have same settings.

**Comment by dlemstra** [comment]
And what is the exact version of Magick.NET that you are using? Are you using the AnyCPU version?

**Comment by Sitanshu89** [comment]
Yes, I am using  Magick.NET-Q16-AnyCPU  and 7.11.0 version.

**Comment by dlemstra** [comment]
You should set the `MagickAnyCPU.CacheDirectory` to a different folder for each application or you should set `MagickAnyCPU.HasSharedCacheDirectory` to `true`. If you prefer the latter then you will need to remove the cache folder on your machine first.

**Comment by Sitanshu89** [comment]
Could you please tell me how to do that, sorry for the silly question.

**Comment by dlemstra** [comment]
How to do what?

**Comment by Sitanshu89** [comment]
I mean how to set MagickAnyCPU.HasSharedCacheDirectory to true ?

**Comment by dlemstra** [comment]
`MagickAnyCPU.HasSharedCacheDirectory = true`? And you should do this before you call any of the Magick.NET code.
