### ISSUE TITLE
Is it possible to display an image in a WinForms application?

### ISSUE THREAD

**Issue by vince94** [dlemstra/Magick.NET#437]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
- Version: Magick.NET-Q8-AnyCPU (7.13.0)
- Environment: Windows 10, C#

### Question
I am trying to make a simple tool aimed at game developers (and myself tbh) who want to use pixel-based/raster fonts in their games' textboxes, but aren't using a game engine that supports automatic linebreaks, and have to use trial and error to see if their text runs offscreen.

To experiment, I'm following [this example](https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Drawing.md) to generate an image with text, but I don't know if it's possible to display the result onscreen (as opposed to writing a file to the disk, or just staying in memory like I assume it's doing now). Is this possible with a PictureBox or something like that?

**Comment by dlemstra** [comment]
When you are using .NET framework you can convert the `MagickImage` to a `Bitmap` or `BitmapSource` and use it into something to display the image..
