### ISSUE TITLE
Support -dFirstPage -dLastPage switches when using Ghostscript

### ISSUE THREAD

**Issue by deckertron9000** [dlemstra/Magick.NET#438]
### Is your feature request related to a problem? Please describe
Trying to quickly get dimensions of the first page of a very large pdf. 

### Describe the solution you'd like
Pass FrameIndex/FrameCount read settings down to gs delegate so it can parse one page instead of the whole pdf file.

### Describe alternatives you've considered
Calling gs directly, but this seems like it could make a nice, easy addition to this library

### Additional context
I tried modifying my delegates.xml file but was having no luck getting the changes to the gs line picked up.

**Comment by dlemstra** [comment]
This should already be happening. When reading a PDF file ImageMagick will add the arguments `-dFirstPage` and `-dLastPage` when you set the FrameIndex/FrameCount in Magick.NET. Why do you think that this is not happening?

**Comment by deckertron9000** [comment]
I have a 986 mb PDF file. When I use a filestream and ping a MagickImage it takes roughly 50 seconds to finish. When I run the ghostscript command directly with -dFirstPage and -dLastPage  switches it only takes a few seconds. I also didn't see any references to -dFirstPage and -dLastPage on the delegates.xml

**Comment by dlemstra** [comment]
Is it possible to share this file somewhere? I suspect it has to do with the fact that you are using a file stream. But I cannot test this without such a file. Maybe you could try reading it from a file instead?

**Comment by deckertron9000** [comment]
Okay, did some more debugging. Turns out the -dFirstPage and -dLastPage args are getting passed to ghostscript but it is just dreadfully slow. 

[Here's a link to the file](https://drive.google.com/file/d/109hZEDReqZDT8_0IkIPbNQXTlyANRTnV/view?usp=sharing)

Here's the code I'm using to test this :
    
    using (var fileStream = File.OpenRead("C:\\LargeFiles\\986_MB.pdf"))
    {
        var readSettings = new MagickReadSettings
        {
            FrameCount = 1,
            FrameIndex = 0,
            Debug = true,
            Verbose = true,
        };

        var sw = new Stopwatch();
        sw.Start();

        using (var image = new MagickImage())
        {
            image.Ping(fileStream, readSettings);

            sw.Stop();
            Console.WriteLine($"Interrogated in {sw.ElapsedMilliseconds} ms");


            Console.WriteLine($"ImageFormat: {image.Format}");
            Console.WriteLine($"Height: {image.Height}");
            Console.WriteLine($"Width: {image.Width}");
        }
    }

Here's the console output: 

> [ghostscript library 9.26] -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pamcmyk32" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -dUseCIEColor -dFirstPage=1 -dLastPage=1 "-sOutputFile=C:/Temp/magick-27216YGzAQHfcvFFw%d" "-fC:/Temp/magick-272164vudx2G2fRZN" "-fC:/Temp/magick-27216quh3Xnuko53b"C:/Temp/magick-27216YGzAQHfcvFFw1 PAM 612x787 612x787+0+0 8-bit ColorSeparation CMYK 1.83742MiB 0.000u 0:00.003
PDF:C:/Temp/magick-27216hCw5xuWRpZj5=>C:/Temp/magick-27216hCw5xuWRpZj5 PDF 612x787 612x787+0+0 16-bit ColorSeparation CMYK 1.83742MiB 24.453u 0:24.508
Interrogated in 50667 ms
ImageFormat: Pdf
Height: 787
Width: 612

**Comment by dlemstra** [comment]
Thanks for reporting this. The issues seems to be that we are reading the whole file byte per byte to get metadata from the PDF file. We use this metadata to instruct GhostScript. I just spend a couple hours rewriting the code to improve the performance. You should see a big improvement in the next release of Magick.NET.

**Comment by dlemstra** [comment]
Another improvement could be adding an option to skip reading the metadata. But that would mean that you will need to specify the color space for this CMYK file and the XMP profile will no longer be read. Would this be something that you could use?
