### ISSUE TITLE
EntryPointNotFoundException occurred in method:  MagickColor_IsCMYK_Set

### ISSUE THREAD

**Issue by jberke** [dlemstra/Magick.NET#439]
### Question
We deployed a new version of our code which is a website running in IIS. We had set the compilation and HttpRuntime target framework to 4.7.2. And we got this error:
An Exception of type: EntryPointNotFoundException occurred in method:  MagickColor_IsCMYK_Set
ExceptionMsg: Unable to find an entry point named 'MagickColor_IsCMYK_Set' in DLL 'Magick.NET-Q16-x64.Native.dll'

When we set the target's back to 4.6.1 the exception went away. 

Our code did work in the same configuration on our staging site. Any ideas of things we could check on?
### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 7.12.0.0
- Environment (Operating system, version and so on): Windows Server 2016 x64

**Comment by dlemstra** [comment]
I had a similar report in issue #143 but I never had a response on how and if that was resolved. And I don't understand why it would work in your staging site but not in production. Maybe you can try some of the things that I suggested in that issue?

**Comment by jberke** [comment]
I did Dumpbin /export on the current version in the temp directory and it the method is there but this is also working. I am trying to find a maintance window when we can set the framework version back to 4.7.2 and I'll report back here what I find:-)

**Comment by jberke** [comment]
Ok, we had another deploy this morning, and we pushed the site out with targeting 4.7.2. Everything worked fine, so my best guess it was some sort of transient error that occured when it was trying to extract the x64 assembly.

**Comment by jberke** [comment]
btw thanks for building and maintaining this project, it works great for what we needed!

**Comment by dlemstra** [comment]
Happy to hear that you got this resolved and I cannot resist to point this out: https://github.com/users/dlemstra/sponsorship
