### ISSUE TITLE
I need to remove transparency from a PNG and Convert to BMP with White background

### ISSUE THREAD

**Issue by TheColonel2688** [dlemstra/Magick.NET#44]
I need to remove transparency from a PNG and convert to BMP with white background. the commented out lines are things I have tried. it just keeps coming out transparent.

```
var image = blah.Item1;
var label = blah.Item2;
var drawblah = new Drawables().FillColor(Color.Black).TextAlignment(TextAlignment.Center).Gravity(Gravity.South).Font("BankGothic Md BT").FontPointSize(16).Text(50,105, label);
                image.Settings.Density = new Density(DPI, DPI);
//image.AlphaColor = Color.White;
//image.VirtualPixelMethod = VirtualPixelMethod.Transparent;
//image.TransparentChroma(Color.White, Color.White);
//image.BackgroundColor = Color.White;
image.Draw(drawblah);
```

**Comment by colnewman26** [comment]
I finally figured it out. I need to call image.Alpha(AlphaOption.Remove);

**Comment by dlemstra** [comment]
This works because the default background color is white. You can change the color with `image.Settings.BackgroundColor`.

**Comment by hn1** [comment]
image.Settings.BackgroundColor does not work. We had to use image.Alpha(AlphaOption.Remove);
Is this a bug that the background version does nothing?

**Comment by dlemstra** [comment]
I don't know what you are tring to do @hn1. But you are right that you still need to do the `image.Alpha(AlphaOption.Remove)`
