### ISSUE TITLE
Open tiff file with lzw compression, exception error "Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/656"

### ISSUE THREAD

**Issue by josecarvalho2** [dlemstra/Magick.NET#440]
### Prerequisites

- [x] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The tiff file with lzw compression, launch an exception "Can not read TIFF directory count. `TIFFFetchDirectory' @ error/tiff.c/TIFFErrors/656".

### Steps to Reproduce
Code example:
---
            System.IO.FileStream    fsSource = null;
            System.IO.FileStream    fsDest = null;
            ImageMagick.MagickImageCollection collImageMag = null;

            try
            {
                this.Cursor = System.Windows.Forms.Cursors.WaitCursor;

                System.DateTime dtBegin;
                dtBegin = System.DateTime.Now;

                string strSourcePathFileName;
                strSourcePathFileName = textBoxSourceFileName.Text;

                string  strSourceFileName;
                strSourceFileName = System.IO.Path.GetFileName(strSourcePathFileName);

                string strSourceExt;
                strSourceExt = System.IO.Path.GetExtension(strSourceFileName);

                string strDestFileName;
                strDestFileName = Papiro.platform.io.Path.FileNameReplaceExt(strSourceFileName, ".pdf");

                string strDestPathFileName;
                strDestPathFileName = textBoxDestPath.Text + System.IO.Path.DirectorySeparatorChar + strDestFileName;

                fsSource = new System.IO.FileStream(strSourcePathFileName, System.IO.FileMode.Open, System.IO.FileAccess.Read);

                ImageMagick.MagickReadSettings imageMagReadSettings;
                imageMagReadSettings = new ImageMagick.MagickReadSettings();
                imageMagReadSettings.SetDefine(ImageMagick.MagickFormat.Tif, "ignore-tags", "32931,32934,59932");
                imageMagReadSettings.SetDefine(ImageMagick.MagickFormat.Tif, "ignore-layers", true);

imageMagReadSettings);
                collImageMag = new ImageMagick.MagickImageCollection();
                collImageMag.AddRange(fsSource, imageMagReadSettings);

                fsDest = new System.IO.FileStream(strDestPathFileName, System.IO.FileMode.CreateNew, System.IO.FileAccess.Write);

                int     nPage = 1;  // nPage start at 1 to normal page numbering

                foreach ( ImageMagick.MagickImage itImage in collImageMag )
                {
                    if ( ((itImage.Format == ImageMagick.MagickFormat.Tif) || (itImage.Format == ImageMagick.MagickFormat.Tiff) || (itImage.Format == ImageMagick.MagickFormat.Tiff64)) &&
                            (itImage.ColorType != ImageMagick.ColorType.Bilevel) )
                    {
                        itImage.Settings.Compression = ImageMagick.CompressionMethod.JPEG;
                    }
                    itImage.Quality = 10;

                    nPage++;
                }

                collImageMag.Write(fsDest, ImageMagick.MagickFormat.Pdf);

                collImageMag.Dispose();
                collImageMag = null;

                fsDest.Close();
                fsDest = null;
                fsSource.Close();
                fsSource = null;

                System.DateTime dtEnd;
                dtEnd = System.DateTime.Now;

                this.Cursor = System.Windows.Forms.Cursors.Default;
                System.Windows.Forms.MessageBox.Show("Acabou! Demorei: " + dtEnd.Subtract(dtBegin).TotalSeconds + " segundos", "Information", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
            catch ( ImageMagick.MagickException exMagick )
            {
                if ( collImageMag != null )
                    collImageMag.Dispose();
                if ( fsDest != null )
                    fsDest.Close();
                if ( fsSource != null )
                    fsSource.Close();
                this.Cursor = System.Windows.Forms.Cursors.Default;
                System.Windows.Forms.MessageBox.Show(exMagick.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
            catch ( System.Exception ex )
            {
                if ( collImageMag != null )
                    collImageMag.Dispose();
                if ( fsDest != null )
                    fsDest.Close();
                if ( fsSource != null )
                    fsSource.Close();
                this.Cursor = System.Windows.Forms.Cursors.Default;
                System.Windows.Forms.MessageBox.Show(ex.Message, "Error", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
--------------------------------------------------------------------------
Attachment include: TIFF that gives the error
[Image0397.zip](https://github.com/dlemstra/Magick.NET/files/3199432/Image0397.zip)
[tiff-lzw-tags.txt](https://github.com/dlemstra/Magick.NET/files/3199434/tiff-lzw-tags.txt)

### System Configuration
C# Visual Studio 2015,Windows Server 2008 R2

- Magick.NET version:
- Environment (Operating system, version and so on): 7.13
- Additional information:

**Comment by dlemstra** [comment]
You are getting this exception because you appear to have a corrupt image.
