### ISSUE TITLE
White image generated while using Drawables().Composite.(...)Draw(...)

### ISSUE THREAD

**Issue by AFract** [dlemstra/Magick.NET#442]
Hello, 

With "Magick.NET-Q8-AnyCPU" version 7.11.0 aiming .Net 471 I was using the following code to resize an image ("originalImage") and place it in the middle of a blank new image ("newImage") :

```
	stream.Position = 0;
	using (var originalImage = new MagickImage(stream))
	{
		var size = new MagickGeometry(pictureFormat.Width, pictureFormat.Height);
		size.IgnoreAspectRatio = false;

		originalImage.Resize(size);

		using (var newImage = new MagickImage(new MagickImage(fillColor, pictureFormat.Width, pictureFormat.Height)))
		{
			var xPosition = (pictureFormat.Width - originalImage.Width) / 2;
			var yPosition = (pictureFormat.Height - originalImage.Height) / 2;

			new Drawables()
				.Composite(xPosition, yPosition, originalImage)
				.Draw(newImage);

			var memoryStream = new MemoryStream();
			newImage.Quality = 80;

			newImage.Write(memoryStream, MagickFormat.Png/*or jpg, same problem*/);

			IMemoryFile memoryFile = new MemoryFile(newName, null, memoryStream);
			return memoryFile;
		}
	}
```
It worked exactly as expected in version 7.11.0, but with version 7.11.1, 7.12.0, and 7.13.0 it seems to only output entirely white images.

I guess the way to use  			
```
new Drawables()
.Composite(xPosition, yPosition, originalImage)
.Draw(newImage);
```
Has evolved between those versions but I can't find anything in release information. 
Could you please tell me how to make it work again ?

The code above is only an excerpt but feel free to ask if you need something more.

Thanks for help and for your great library.

**Comment by dlemstra** [comment]
For some reason this method had `CopyAlpha` as the default composite operator. I changed this to `In` and that seems to resolve your issue. But I don't understand why this worked earlier. I suspect that something was fixed inside ImageMagick and that made this bug visible. This issue will be resolved in the next release that I will try to publish later this week/weekend.

**Comment by AFract** [comment]
Thanks a lot for your quick answer. There's no emergency, as fortunately it works with the previous version. 
I will keep you informed if upcoming version actually fix it when it will be available.
If I have to change something in my code, let me know.
