### ISSUE TITLE
Why does it center the Watermark Image on some images when I set it to SouthEast?

### ISSUE THREAD

**Issue by PtrStruct** [dlemstra/Magick.NET#444]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.13.0
- Environment (Operating system, version and so on): Windows 10 64x

### Question

I installed the Nuget package today just to try things out and I realized that the library behaved strange when trying to set a Image as a watermark on the bottom right using the example code in the documentations.

some images it works just fine but with other images it just centers the watermark and I have no idea to why that is.

This image watermarks just fine https://i.imgur.com/g7fdXsw.jpg
But with this one the watermark image just gets centered. https://i.imgur.com/BUBHbC2.jpg
Here is the watermark image https://i.imgur.com/r17aMIM.png

And I'm using this code snippet
```
// Read image that needs a watermark
using (MagickImage image = new MagickImage("MainImage.jpg"))
{
    // Read the watermark that will be put on top of the image
    using (MagickImage watermark = new MagickImage("WatermarkImage.png"))
    {
        // Draw the watermark in the bottom right corner
        image.Composite(watermark, Gravity.Southeast, CompositeOperator.Over);

        // Optionally make the watermark more transparent
        watermark.Evaluate(Channels.Alpha, EvaluateOperator.Divide, 4);

    }

    // Save the result
    image.Write("Processed.jpg");
}
```

**Comment by dlemstra** [comment]
Your watermark is pretty huge (1920x1080) and when you place in the south east corner of `BUBHbC2.jpg` (2000x1333) it will look like it is being centered. Your watermark is surround with a lot of whitespace so you might want to trim that.

**Comment by PtrStruct** [comment]
Is there a way to make it more "global"? To make sure the watermark image fits pretty much any image?

**Comment by dlemstra** [comment]
Then you will probably need to resize your watermark to a size that is a precentage of the image were you try to put it in.
