### ISSUE TITLE
reducing png image quality

### ISSUE THREAD

**Issue by zaib347** [dlemstra/Magick.NET#446]
i am reducing image quallity code shows me compress png size is less then orignial png.after writng to disk size of png is always greter to orignal 
  if (compressImageSize < originalImageSize)
                {
                    var compressImage = System.Drawing.Image.FromStream(memStream, true, true);
                    compressImage.Save(destFiles + "\\" + filename);
                }

**Comment by dlemstra** [comment]
I have no idea what you are asking? And this does not look like Magick.NET code?

**Comment by zaib347** [comment]
here is my complete code 
`  using (var memStream = new MemoryStream())
            {
                var magickImage = new MagickImage(originalImagePath);
              
                    magickImage.Quality = 85;
                    magickImage.Strip();
                     magickImage.Write(memStream);
                var compressImageSize = memStream.Length;
                if (compressImageSize < originalImageSize)
                {
                    var compressImage = System.Drawing.Image.FromStream(memStream, true, true);
                    compressImage.Save(destFiles + "\\" + filename);
                }`
compress png image size is less then original png image. when png image save to disk size 6 to 7 time higher then original path

**Comment by dlemstra** [comment]
You should not call `System.Drawing.Image.FromStream` and `compressImage.Save` but instead directly write the stream to file.
