### ISSUE TITLE
Write to MemoryStream with ImageMagick.JpegWriteDefines set

### ISSUE THREAD

**Issue by gerwintmg** [dlemstra/Magick.NET#447]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Writing to a stream  by defining

```code
Image.Write(imageStream, ImageMagick.MagickFormat.Jpg);"
```

works but

```code
 Image.Write(imageStream, new ImageMagick.JpegWriteDefines
                    {
                        OptimizeCoding = true,
                        ArithmeticCoding = true,
                        DctMethod = ImageMagick.Defines.DctMethod.Slow,
                        SamplingFactor = ImageMagick.Defines.SamplingFactor.Ratio422,
                    });
```
doesn't

### Steps to Reproduce
```code
            using (System.IO.Stream imageStream = new System.IO.MemoryStream()) {

                using (ImageMagick.MagickImage Image = new ImageMagick.MagickImage(fullImagefilePath)) {
                    Image.Quality = 65;
  
                    Image.Format = ImageMagick.MagickFormat.Jpg;
                    Image.Write(imageStream, new ImageMagick.JpegWriteDefines
                    {
                        OptimizeCoding = true,
                        ArithmeticCoding = true,
                        DctMethod = ImageMagick.Defines.DctMethod.Slow,
                        SamplingFactor = ImageMagick.Defines.SamplingFactor.Ratio422,
                    });
                }
              // any kind of utilization of the stream fails 

            }

```
### System Configuration
Visual studio 2017

- Magick.NET version: Nuget Magick.NET-Q8-AnyCPU  version 7.13.1.0   runtime v4.0.30319
- Environment (Operating system, version and so on):  Windows 10 Pro 6.3 17763.1.amd64fre.rs5_release.180914-1434
- Additional information:

**Comment by dlemstra** [comment]
Can you explain what doesn't work?

**Comment by gerwintmg** [comment]
> 
> 
> Can you explain what doesn't work?

When i use write() on a MagickImage with the param of ImageMagick.IWriteDefines,
I'm unable to utilize the resulting stream.
 When i try to utilize the stream i get

- ReadTimeout = 'imageStream.ReadTimeout' threw an exception of type 'System.InvalidOperationException'
- WriteTimeout = 'imageStream.WriteTimeout' threw an exception of type 'System.InvalidOperationException'

**Comment by dlemstra** [comment]
This seems to work for me:

```C#
using (FileStream fs = File.OpenWrite("i:/test.jpg"))
{
    imageStream.Position = 0;
    imageStream.CopyTo(fs);
}

using (var test = new MagickImage("i:/test.jpg"))
{
}
```

I really don't understand what kind of issue you are having.

**Comment by gerwintmg** [comment]
I've done some more tests.

and it seems that the .net framework doesn't support ArithmeticCoding.

the output looks corrupt to the .net native image lib.
and if i write a direct filestream no (default) image viewer wil open it.
The error i got came from GDI+

The image can be opened with "The Gimp", so now it just time to replace the .net defaults with Magick.net

My apology for thinking that error was here.
