### ISSUE TITLE
Issue with partially corrupt PNGs

### ISSUE THREAD

**Issue by AdamKallenbach** [dlemstra/Magick.NET#45]
Lets say I have the code below.
```
  using (var image = new MagickImage())
                    {
                        image.Warning += MagickImage_Warning;
                        image.Read(currentFile);
                    }
```
If this tries to read a PNG that is partially corrupted then the method will just run without ever timing out. It also isn't throwing an exception or executing the warning event.

**Comment by dlemstra** [comment]
Can you add a link to the image that you are using?

**Comment by AdamKallenbach** [comment]
Here is a dropbox link : [Corrupted Pictures](https://www.dropbox.com/sh/z4g3sr534ias2vm/AABY5uPQweP0LZkAMVa96hxPa?dl=0)

This is a folder that contains the images that are causing problems. If you would have a more preferred way of getting the images linked just let me know.

**Comment by dlemstra** [comment]
Dropbox link is perfect, will take a look at this in a couple days

**Comment by dlemstra** [comment]
This appears to be a bug in the png library. Upgrading to the latest release of libpng resolved the issue. I will try to publish a new release later this week.

**Comment by dlemstra** [comment]
The new release has been published last week. Can you update Magick.NET and give it another try? Feel free to close this issue when it is resolved.

**Comment by AdamKallenbach** [comment]
Thank you everything is working.
