### ISSUE TITLE
Extract Image Collection in HEIC Container

### ISSUE THREAD

**Issue by moutasem1989** [dlemstra/Magick.NET#451]
As an example, I have [This HEIC Sample File](https://github.com/dlemstra/Magick.NET/files/3231230/HEIC.Sample.zip). It contains an Image collection in one single container.
How do i determen how many images exist in this container?
how do i extract those images?

**Comment by dlemstra** [comment]
ImageMagick currently only supports reading a single image from that container. We might add support for reading multiple images in the future.

**Comment by moutasem1989** [comment]
It would be extremely helpful if you do. I am sorry to bother you, but is there an existing timeline for such features?
Till the point where it is included, could you point me in a direction where i can use such feature in C#? I should point out that I am teaching myself coding and so far i know nothing about C/C++.

**Comment by dlemstra** [comment]
The timeline is that it might happen at some point in the future. And I don't know any other libraries that can read HEIC images.

**Comment by dlemstra** [comment]
Turned out that it was not super difficult to add support for this and this will be available in the next release.

**Comment by moutasem1989** [comment]
that is really amazing !! thank you so much !
cant wait to see how you did it

**Comment by dlemstra** [comment]
You will need to use a `MagickImageCollection` to read all the images.

**Comment by moutasem1989** [comment]
So When i use `MagickImageCollection` to read the Images like this:
`public static async Task<MagickImageCollection> LoadImageCollectionFromHeicFile(StorageFile storageFile)
{
       /*
       var randomAccessStream = await storageFile.OpenReadAsync();
       Stream stream = randomAccessStream.AsStreamForRead();
       */
        byte[] fileBytes = null;
       if (storageFile == null) return null;
       using (var stream = await storageFile.OpenReadAsync())
       {
           fileBytes = new byte[stream.Size];
       }
       using (MagickImageCollection magickImages = new MagickImageCollection(fileBytes))
       {
           return magickImages;
       }
}`

It gets stuck at `using (MagickImageCollection magickImages = new MagickImageCollection(fileBytes))` and doesnt return any collection. 
Could you help me?

**Comment by dlemstra** [comment]
`fileBytes = new byte[stream.Size];` just creates an empty array? Not sure what you are trying to do?
