### ISSUE TITLE
Converting from MagickColor to ColorHSL results in zero saturation

### ISSUE THREAD

**Issue by Goztehm** [dlemstra/Magick.NET#454]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Create a MagickColor which clearly has a non-zero saturation, convert to ColorHSL, and the ColorHSL variable has a zero saturation (and hue).

### Steps to Reproduce

```
MagickColor c = new MagickColor(65535, 65535, 1000);
ColorHSL h = ColorHSL.FromMagickColor(c);
double saturation = h.Saturation;
```
### System Configuration

- Magick.NET version: Magick.NET-Q16-x64.7.13.1
- Environment (Operating system, version and so on): Windows 10
- Additional information: master/Source/Magick.NET/Shared/Colors/ColorHSL.cs line 132, Initialize(), currently has an error, using "Math.Min(red, Math.Max(green, blue))" rather than "Math.Min(red, Math.Min(green, blue))" to calculate min.

**Comment by dlemstra** [comment]
Thanks for reporting this and for telling me what to fix 👍 This bug will be resolved in the next version of Magick.NET

**Comment by Goztehm** [comment]
Thanks Dirk.
