### ISSUE TITLE
Docker .NET Core - Unable to load DLL 'Magick.NET-Q16-x64.Native.dll' or one of its dependencies: The specified module could not be found.

### ISSUE THREAD

**Issue by BjBlazkowicz** [dlemstra/Magick.NET#455]
I'm getting the following error when trying to run an app with dependency on Magick.NET in a docker container:

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x64.Native.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) at ImageMagick.Environment.NativeMethods.X64.Environment_SetEnv(IntPtr name, IntPtr value) at ImageMagick.Environment.NativeEnvironment.SetEnv(String name, String value)

The published out directory does not contain 'Magick.NET-Q16-x64.Native.dll', only 'Magick.NET-Q16-x64.dll'.

When running the app locally in windows 10 it works fine.

The docker image that I use as runtime is the following:

mcr.microsoft.com/dotnet/core/runtime:2.2

**Comment by dlemstra** [comment]
Which version of Magick.NET are you using? The questions in the issue template are there for a reason.
