### ISSUE TITLE
Not able to convert format into WebP using the Magick.NET

### ISSUE THREAD

**Issue by amar132** [dlemstra/Magick.NET#457]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration
Windows10, RAM:16GB

- Magick.NET version:  Magick.NET-Q16-AnyCPU (RunTime Version: v4.0.30319, Version: 7.4.6.0)
- Environment (Operating system, version and so on): Windows10, VS2015

### Question
I am trying to convert the image format to WebP. but the images is does not get any format and it shows no image. Also, how to SetDefine() method is missing from the object to define the lossless and other properties. Below is the code for more clarity:
ImageMagick.MagickImage objMagick = new MagickImage(fiImage);

                   
                    for (int i = 0; i <= ImgDim.GetUpperBound(0); i++)
                    {
                        int width = ImgDim[i, 0];
                        int height = ImgDim[i, 1];

                        objMagick.Resize(width, height);                        
                        var objClone = objMagick.Clone(width, height);
                        objClone.Quality = iImageQualityCompression;
                        objClone.UnsharpMask(0.25, 0.25, sharpenamount, sharpenThreshold);
                        objClone.Posterize(136);//136
                        objClone.Sharpen();
                        if (Image.SelectedSharpenOption == "option2")
                        {
                            objClone.Blur(0.38, 0.38);
                        }

                        objClone.Quality = 90;
                        
                        objClone.Format = MagickFormat.WebP;

                        // objClone.Write(sTargetDirectoryPath + width + '_' + height + '/' + fileName.Substring(sSourceDirectoryPath.Length).Split('.')[0] + '_' + width + 'x' + height + '`' + iImageQualityCompression.ToString() + '.' + fileName.Substring(sSourceDirectoryPath.Length).Split('.')[1]);
                        objClone.Write(sTargetDirectoryPath + width + '_' + height + '/' + 
                            fileName.Substring(sSourceDirectoryPath.Length).Split(new string[] { fiImage.Extension }, StringSplitOptions.None)[0] 
                            + '_' + width + 'x' + height + '`' + iImageQualityCompression.ToString() + ".webp");
                        objClone.Dispose();

**Comment by dlemstra** [comment]
I don't understand what your issue is?

**Comment by amar132** [comment]
I need to be able to convert an image from jpg or png to webp via .Net. I tried with the code above, but did not work out. Would you please help me with that.

**Comment by dlemstra** [comment]
Can you explain what is not working?

**Comment by amar132** [comment]
As I execute the application. The file generated from it does not have the extension as .webp

**Comment by dlemstra** [comment]
Why does it not have that extension? In your sample code you have a file name that ends with `.webp`. What is the extension of the file?

**Comment by amar132** [comment]
In the sample code, I am trying to save the file with that extension. And the resulted file does not have any extension. And when I download that file it comes out as .htm

**Comment by dlemstra** [comment]
This really sounds like a problem inside the web application where you are using this?

**Comment by amar132** [comment]
That could be true. Would you like me to give the code to you as a zip?

**Comment by dlemstra** [comment]
I cannot help you with that, you will need to fix that yourself.
