### ISSUE TITLE
Converting SVG including an image link with query string to Jpeg failed to render the linked image

### ISSUE THREAD

**Issue by thibnes** [dlemstra/Magick.NET#458]
With an SVG like
`<svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" viewBox=\"0 0 260 880\"><defs><image xlink:href=\"https://xxx.com/file.png?test=1\" preserveAspectRatio=\"none\" width=\"260\"....`

conversion to Jpeg works when the `<image xlink:href` does not contain a query string otherwise it skips the linked image.

**Comment by dlemstra** [comment]
Magick.NET uses librsvg and I suspect that this libary has some security policy in place to disable that.
