### ISSUE TITLE
Loading grayscale tga has incorrect number of channels and alpha channel.

### ISSUE THREAD

**Issue by VinCal** [dlemstra/Magick.NET#459]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Loading a tga grayscale image created in Photoshop (Image - Mode - Grayscale) seems to be corrupt. When I inspect the number of channels it should be 1, instead I get 5. The ColorType is also set to 'PaletteAlpha', instead of 'Grayscale'. 

Loading the same image but saved as a tif from Photoshop produces the correct results.

### Steps to Reproduce
I have attached both the tga and tif grayscale images. Loading them in the following way produces the incorrect results:

``` 
var grayscale = new MagickImage("grayscale.tga");
grayscale.ChannelCount; // 5
grayscale.HasAlpha; // true
```

```
var grayscale_tif = new MagickImage("grayscale.tif");
grayscale_tif .ChannelCount; // 1
grayscale_tif .HasAlpha; // false
```

### System Configuration
- Magick.NET version: Magick.NET-Q16-AnyCPU 7.13.1.0
- Environment (Operating system, version and so on): Windows 10
- Additional information:

[grayscale_images.zip](https://github.com/dlemstra/Magick.NET/files/3276375/grayscale_images.zip)

**Comment by dlemstra** [comment]
It looks like you found a bug in ImageMagick. This should be fixed inside ImageMagick.
