### ISSUE TITLE
Readme.md contains incorrect links to documentation

### ISSUE THREAD

**Issue by NiklasSch** [dlemstra/Magick.NET#460]
Readme.md contains incorrect links to the documentation.

This is what I've discovered:
- Supported Platforms - Linux and macOS https://github.com/dlemstra/Magick.NET/blob/master/Documentation/CrossPlatform.md
- Documentation - documentation
https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Readme.md
- Versioning - versioning strategy
https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Versioning.md

**Comment by dlemstra** [comment]
Thanks for noticing 👍  I am in the middle of a reorganization of the project and these links should be changed and some documentation should also be changed. Feel free to open up a pull request to fix the links in the readme.

**Comment by NiklasSch** [comment]
Done https://github.com/dlemstra/Magick.NET/pull/461! 👍

But the some checks are failing... :(

**Comment by dlemstra** [comment]
The builds are also very new 👍 Just pushed some changes to fix this.
