### ISSUE TITLE
How to change a image dpi?

### ISSUE THREAD

**Issue by futureflsl** [dlemstra/Magick.NET#462]
I want to change one image dpi,but I don't know how to do it with magick.NET

**Comment by dlemstra** [comment]
You can do that with the `Density` property of the `MagickImage`.

**Comment by futureflsl** [comment]
MagickImage img = new MagickImage(sfile);
   img.ColorSpace = ColorSpace.CMYK;
   img.Density = new Density(72,72);

I did like this,but it doesn't work!

**Comment by dlemstra** [comment]
Did you also `Write` the file?

**Comment by futureflsl** [comment]
thanks,today I try again,it can work,but last day It cannot work,I'm not sure why it happened
