### ISSUE TITLE
EXIF thumbnail for images generated via "CropToTiles"

### ISSUE THREAD

**Issue by yani-pi** [dlemstra/Magick.NET#463]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
- Magick.NET version: 7.13.1 - x64-OpenMP
- Environment (Operating system, version and so on): Windows 7, .NET v4.6.2

### Question
Hi,
I'm using "CropToTiles" to generate a list of images which are then resized and saved as JPEGs. The EXIF thumbnail written to the output image is the same as the original image, not the tile's thumbnail. Is there a way to generate the correct thumbnail for each tile, or to remove the EXIF thumbnail? The original image is a BigTIFF.

**Comment by dlemstra** [comment]
What you could do is call `GetExifProfile()` to retrieve the `ExifProfile`. And then you will need to call `profile.RemoveValue` to remove `ExifTag.JPEGInterchangeFormat` and `ExifTag.JPEGInterchangeFormatLength`. And when you are done you will need to call `SetExifProfile` to update the profile.

**Comment by yani-pi** [comment]
Thanks

**Comment by dlemstra** [comment]
In the next version of Magick.NET there will be a new method called `RemoveThumbnail` added to the `ExifProfile` class.
