### ISSUE TITLE
How to build ImageMagick part in 7.14.0?

### ISSUE THREAD

**Issue by t246246** [dlemstra/Magick.NET#465]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.14.0
- Environment (Operating system, version and so on): Windows 7

### Question
After downloading Magick.NET-7.14.0.0.zip, I noticed some folder is missing compared to 7.13.1.0, Documentation and ImageMagick.

As I usually start compiling with ImageMagick/Source/Checkout.cmd (written in Building.md), so I'd like to know there is some intentional change from this release.

Best Wishes,

**Comment by dlemstra** [comment]
The building documentation needs to be updated. Some of it will need to move to the project where the `ImageMagick` folder has moved to: https://github.com/dlemstra/Magick.Native. The ImageMagick library is now build in a separate repository. You will need to run `src/Magick.Native/install.cmd` to install it into this library.

**Comment by t246246** [comment]
On Windows 10 (just installed on VirtualBox, has no VisualStudio at the moment though), `install.cmd` goes further, but still it stopped as it cannot find nuget.exe.  Indeed nuget.exe is not exists at the specified location:

```
..\..\tools\windows\nuget.exe : The term '..\..\tools\windows\nuget.exe' is not recognized as the name of a cmdlet, fun
ction, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the pat
h is correct and try again.
At C:\Users\ryuichi\Desktop\Magick.NET-7.14.0.0\Magick.NET-7.14.0.0\src\Magick.Native\install.ps1:24 char:5
+     ..\..\tools\windows\nuget.exe install Magick.Native -Version $ver ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (..\..\tools\windows\nuget.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

Probably I have to setup Visual Studio first.

Anyway I am afraid the build script no longer works on Windows 7.

**Comment by t246246** [comment]
Well, I update powershell on Windows 7 and copy missing nuget.exe from 7.13.1.0 tree to tools/Windows.
Then it looks install.cmd successfully ends.

So I have a second question.
I have to build imagemagick by myself, due to some license issue, I have to remove some library.
In 7.13.1.0, I do the following:
- Get ImageMagick source (using ImageMagick/Source/Checkout.cmd).

- Remove unneeded folders from ImageMagick/Source/ImageMagick and  ImageMagick/Source/ImageMagick/VisualMagick.
- Remove unneeded config files from ImageMagick/Source/ImageMagick/VisualMagick/coders

Then run ImageMagick/Source/BuildAll.cmd.  (And follow the steps to make AnyCPU version.)

I'd like to build the same way in 7.14.0.0.  How do I archive it?

**Comment by dlemstra** [comment]
If you want to build your own version of ImageMagick you will need to use the new Magick.Native project that contains this and reference that inside this project.

**Comment by t246246** [comment]
Before modifying ImageMagick, I am trying to build as it is.  First, I download Magick.Native-2019.6.16.1220.zip and trying to build.

`src/ImageMagick/checkout.cmd` works. It got ImageMagick and its depending libraries sources.

What should I do next? So far I tried are:

`build/dotnet/windows/build.ImageMagick.cmd` seems to work. (Although it complains at first as it cannot find nuget.exe.) It compiles src and successfully ends.  But I cannot find the target object.
 
`build/dotnet/windows/build.Native.cmd` does not work at all.

Opening `src/Native/Magick.Native.sln` and trying to build with Visual Studio does not work.  (It does not find MagickCore.h.)

**Comment by dlemstra** [comment]
I will try to update the documentation next week.

**Comment by t246246** [comment]
After updating Magick.Native to 2019.7.21.1414, it looks Visual Studio 2019 is required.
Then I tried to compile again, but still stopped at `build/dotnet/windows/build.Native.cmd`

```
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.tar
       gets(376,5): error MSB8013: This project doesn't contain the Configuration and Platform combination of Release|W
       in32. [C:\Magick.Native-2019.7.21.1414\Magick.Native-2019.7.21.1414\src\Magick.Native
       \Magick.Native.vcxproj]
```

What should I do it for this?

**Comment by t246246** [comment]
I do the following before build/dotnet/windows/build.ImageMagick.cmd 

set QuantumName=Q16
set PlatformName=x86

then run build/dotnet/windows/build.ImageMagick.cmd  and build/dotnet/windows/build.Native.cmd

It produced `Magick.Native-Q16-x86.dll` and `Magick.Native-Q16-x86.lib` at `src/Magick.Native/bin/ReleaseQ16/x86`.  As well I can get x64 lib and dll, so I can do the next step.
