### ISSUE TITLE
Native dll is missing in the AnyCPU nuget package in version 7.14.0

### ISSUE THREAD

**Issue by hermanho** [dlemstra/Magick.NET#467]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The native dll is missing in AnyCPU package comparing with x64 version.

- Magick.NET version:
- Environment (Operating system, version and so on): windows 10
- Additional information:

Magick.NET-Q16-AnyCPU nuget package
![image](https://user-images.githubusercontent.com/2337380/59814745-f3e04380-9348-11e9-86f4-f53ef3238213.png)

Magick.NET-Q16-x64 nuget package
![image](https://user-images.githubusercontent.com/2337380/59814752-fa6ebb00-9348-11e9-9fdd-dd0d68edcfcb.png)

**Comment by dlemstra** [comment]
As you can read in `docs/Readme.md` the library is included as an embedded resource. So it is correct that you cannot find it in the NuGet package.

**Comment by hermanho** [comment]
When I install with Magick.NET-Q16-AnyCPU-7.14.0 nuget package, it throw with the following exception:
```
The type initializer for 'NativeMagickSettings' threw an exception. Unable to load DLL 'Magick.Native-Q16-x64.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E) 

System.TypeInitializationException:
   at ImageMagick.MagickSettings+NativeMagickSettings..ctor (Magick.NET-Q16-AnyCPU, Version=7.14.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec)
   at ImageMagick.MagickSettings..ctor (Magick.NET-Q16-AnyCPU, Version=7.14.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec)
   at ImageMagick.MagickImage..ctor (Magick.NET-Q16-AnyCPU, Version=7.14.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec)
```

However, it is no problem when I install with Magick.NET-Q16-x64-7.14.0 nuget package only means it does not work without runtimes folders.

**Comment by dlemstra** [comment]
It looks like your application cannot create the folder with the embedded resources in `%temp%`. Have you tried setting `MagickAnyCPU.CacheDirectory`?

**Comment by hermanho** [comment]
I tried with MagickAnyCPU.CacheDirectory = "C:\\temp\\" and everyone with full permission. There is no files outputted in that folder. When I step in with source code, the method "NativeLibraryLoader.Load" has not called so the embedded resource has not extracted.

**Comment by dlemstra** [comment]
Are you using the .netstandard2.0 version of the library or the net4.0 one?

**Comment by hermanho** [comment]
netstandard2.0, my project is asp.net core 2.2 and targetFramework is netcoreapp2.2

**Comment by dlemstra** [comment]
Then you will need to switch to the x64 version. At this moment there is no AnyCPU support for the netstandard2.0 build.

**Comment by hermanho** [comment]
It is breaking change! It works on Magick.NET-Q16-AnyCPU v7.13.1 but developers have to install x64 version when v7.14.0.

**Comment by dlemstra** [comment]
That was never my intention but I will take a look at this later tonight to confirm this.

**Comment by dlemstra** [comment]
Well it looks like you are right. It seems that I added support for the AnyCPU build for all platforms at some point in time. I really don't remember that I did this. But I will make sure I will publish a new release this weekend or next week to resolve your issue. Thanks for reporting this 👍

**Comment by ffMathy** [comment]
Is this on NuGet yet?

**Comment by dlemstra** [comment]
If you would read this issue you can get all the information that you are asking?
