### ISSUE TITLE
Image size is lighter from command-line tool than that of Magick.NET code

### ISSUE THREAD

**Issue by amar132** [dlemstra/Magick.NET#468]
- Magick.NET version:
-Windows 10, Magick.NET-Q16-AnyCPU: 7.14.0.0

### Question
My .Net code as below gives image with size 644KB and from command-line i get 395KB.
Is there something i need to change/add in the code?

All the input values are same in both the cases.

.NET code:
```C#
using (MagickImage image = new MagickImage(inPath))
{
    using (var newImage = image.Clone())
    {
        newImage.Resize(size.Width, size.Height);
        newImage.Strip();
        newImage.Format = MagickFormat.WebP;
        newImage.Quality.Equals(quality);
        newImage.Settings.SetDefine(MagickFormat.WebP, "lossless", "false");
        newImage.Write(outPath + ".webp");
    }
}
```

Command-line code: 
convert $inputFile -strip -resize $dimension -quality 90 -define webp:lossless=false $outFileName

**Comment by dlemstra** [comment]
Can you share the input image so I can try to reproduce your issue?

**Comment by amar132** [comment]
[new8.zip](https://github.com/dlemstra/Magick.NET/files/3316513/new8.zip)

There is the image. Sorry for the delay.
Thanks

**Comment by dlemstra** [comment]
What happens when you do `newImage.Quality = 90` instead of `newImage.Quality.Equals(quality);`?

**Comment by amar132** [comment]
Well, it worked. That was stupid of me. Thanks.

**Comment by amar132** [comment]
And thanks for the quick responses.
