### ISSUE TITLE
Reading tiff with old style jpeg compression gives an error "no decode delegate for this image format `' @ error/blob.c/CustomStreamToImage/764"

### ISSUE THREAD

**Issue by josecarvalho2** [dlemstra/Magick.NET#470]
### Prerequisites

Reading tiff with old style jpeg compression gives an error "no decode delegate for this image format `' @ error/blob.c/CustomStreamToImage/764".
The image file is read using AddRange from ImageCollection. But when i read the image from Read method of Image class (not imagecollection), no error is raised.

Code:

                ImageMagick.MagickReadSettings imageMagReadSettings;
                imageMagReadSettings = new ImageMagick.MagickReadSettings();
                imageMagReadSettings.SetDefine(ImageMagick.MagickFormat.Tif, "ignore-tags", "32931,32934,59932");

                collImageMag = new ImageMagick.MagickImageCollection();
                collImageMag.AddRange(fsSource, imageMagReadSettings);

Detail exception:
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadStream(MagickSettings settings, ReadWriteStreamDelegate reader, SeekStreamDelegate seeker, TellStreamDelegate teller)
   at ImageMagick.MagickImageCollection.AddImages(Stream stream, MagickReadSettings readSettings, Boolean ping)

- [x] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Which version are you using. I can read an image with old style jpeg compression without any issues with version `7.14.0.1`.

**Comment by josecarvalho2** [comment]
I have downloaded the last version right now, 7.14.0.1

**Comment by josecarvalho2** [comment]
I tested the file with bitmiracle.libtiff, and it runs ok.

**Comment by dlemstra** [comment]
Can you share the file? ImageMagick is more strict so that could be the reason that it cannot be read.

**Comment by josecarvalho2** [comment]
With other oldstyle file (the one as a attachment) gave a different error.

Stream position is at the end of the stream. Make sure to reset the stream position to 0.
Parameter name: stream

   at ImageMagick.Throw.IfNullOrEmpty(String paramName, Stream value)
   at ImageMagick.MagickImageCollection.AddImages(Stream stream, MagickReadSettings readSettings, Boolean ping)

The original oldstyle file was to big to send by email. I will send by wetransfer.

Cumprimentos

José Carvalho
Direção Técnica, Coordenador de Sistemas e Tecnologias de Informação
911 005 528

Delegação sul | Parque Industrial do Porto Alto, Lt. 14 2135-009 Samora Correia
[cid:ii_juv3jizd3]<https://www.papiro.pt/servico-de-destruicao-confidencial-de-documentos/>

Esta mensagem contém informação confidencial ou privilegiada, estando protegida por lei. Se não for o destinatário ou a pessoa autorizada a receber esta mensagem, não pode usar, copiar, divulgar ou tomar qualquer ação baseada nestas informações.
Se recebeu esta mensagem por engano, por favor, avise-nos imediatamente, e em seguida apague-a.
Agradecemos a sua cooperação.


De: Dirk Lemstra <notifications@github.com>
Enviada: 25 de junho de 2019 06:25
Para: dlemstra/Magick.NET <Magick.NET@noreply.github.com>
Cc: Papiro-José Carvalho <jose.carvalho@papiro.pt>; Author <author@noreply.github.com>
Assunto: Re: [dlemstra/Magick.NET] Reading tiff with old style jpeg compression gives an error "no decode delegate for this image format `' @ error/blob.c/CustomStreamToImage/764" (#470)


Can you share the file? ImageMagick is more strict so that could be the reason that it cannot be read.

**Comment by josecarvalho2** [comment]
jose.carvalho@papiro.pt sent you some files

1 item, 3.97 MB in total ・ Will be deleted on 2 July, 2019


Download link:
https://wetransfer.com/downloads/d8afb7a91a817900176e36d018c5ea5620190625175743/cddf2c880ab0bdcc280c3ea95fd208cc20190625175743/78aaed


Message:
The original oldstyle JPEG compression tiff file



1 item

00395CA2-oldstyle.TIF - 3.97 MB


[Get more out of WeTransfer, get Plus](https://wetransfer.com/plus?trk=WT201704_email&utm_campaign=WT_email_tracking&utm_content=general&utm_medium=plus_footer_ad_link&utm_source=notify_recipient_email)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add noreply@wetransfer.com to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by josecarvalho2** [comment]
With other oldstyle file (one in the (921) attachment) gave a different error.

Stream position is at the end of the stream. Make sure to reset the stream position to 0.
Parameter name: stream

   at ImageMagick.Throw.IfNullOrEmpty(String paramName, Stream value)
   at ImageMagick.MagickImageCollection.AddImages(Stream stream, MagickReadSettings readSettings, Boolean ping)
the file is 921.tif
[oldstyle.zip](https://github.com/dlemstra/Magick.NET/files/3326685/oldstyle.zip)

The original file is CA2.tif

**Comment by josecarvalho2** [comment]
wrong close

**Comment by dlemstra** [comment]
This is the error message:

```
Stream position is at the end of the stream. Make sure to reset the stream position to 0.
Parameter name: stream
```

You need to change the `Position` of the stream to `0`.

And next time please email me if you need to share something confidential. It looks like this contains personal data!

**Comment by josecarvalho2** [comment]
You were correct. when read the image using Image class in order to test and i Forget to make Seek in the stream. It runs ok. But what is the difference to the first file?

**Comment by dlemstra** [comment]
This must be something in your code.
