### ISSUE TITLE
Delegates for image format

### ISSUE THREAD

**Issue by josecarvalho2** [dlemstra/Magick.NET#471]
Is it possible to customize delegates for image format reading?. 
Where to search?

### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):

**Comment by dlemstra** [comment]
I don't understand what you are asking. Can you clarify your question?

**Comment by josecarvalho2** [comment]
For instance in order to customize a tiff file read, can i delegate the actions to some external lib like bitmiracle.libtiff?

**Comment by dlemstra** [comment]
You can read the pixels with Magick.NET if that library can export them in someway.
