### ISSUE TITLE
jpg image on watermark can,t be transparent 

### ISSUE THREAD

**Issue by zaib347** [dlemstra/Magick.NET#472]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):

### Question

i am using watermark png image will be transparent using following line of code but there is no effect on jpg

                
                        watermark.Evaluate(Channels.Alpha, EvaluateOperator.Divide, 4);

**Comment by dlemstra** [comment]
You first need to activate the alpha channel: `image.Alpha(AlphaOption.Activate)`.

**Comment by zaib347** [comment]
now my complete code looks like but its not working
   using (MagickImage watermark = new MagickImage(wmimage))
                    {
                        watermark.Alpha(AlphaOption.Activate);
                        watermark.Evaluate(Channels.Alpha, EvaluateOperator.Divide, 4);
                        image.Composite(watermark, placement, CompositeOperator.Over);
                        }

**Comment by dlemstra** [comment]
I did not see that you where diving the value. You will need to use `AlphaOption.Opaque` instead.

**Comment by zaib347** [comment]
Thanks its working fine
