### ISSUE TITLE
How to separate channel with transparency

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#473]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
- Magick.NET version: 7.14.1
- Environment (Operating system, version and so on): Windows 10 May 2019

### Question
I use this code to separate channel:
```csharp
var settings = new MagickSettings()
{
    BackgroundColor = Color.Transparent
};

using (var imgM = new MagickImage(@"D:\icon.png", settings))
{
    // imgM.HasAlpha returns True here

    using (var channelImg = imgM.Separate(Channels.Blue).First())
    {
        // channelImg.HasAlpha returns False    -> ??
    }
}
```

- The input image is transparent PNG file.
- After I separate Blue channel, the transparent area of output image is replaced by WHITE (or BLACK).

#### Input image
![folder](https://user-images.githubusercontent.com/3154213/60193233-e0ae0600-9869-11e9-9bfb-6f9057f6dcdb.png)

#### Output image (without checkerboard)
![image](https://user-images.githubusercontent.com/3154213/60193280-f7ecf380-9869-11e9-9785-c46be1adf9b1.png)

### My questions
- So how to keep transparency?
- And let's say I want to view both R and B channels, how to do it? I tried
  ```csharp
   imgM.Separate(Channels.Blue | Channels.Red).First()
  ```
  but it was still gray. Photoshop screenshot:

![image](https://user-images.githubusercontent.com/3154213/60193498-5ca84e00-986a-11e9-88a2-8aea37a6cc97.png)

Thanks!

**Comment by t246246** [comment]
Do you want the same result as the ImageMagick command?
```
magick icon.png -channel RGBA -separate -delete 0,1 -compose copy_opacity -composite result.png
```

**Comment by d2phap** [comment]
Thanks @t246246 !
That's exactly what I want to do.

**Comment by t246246** [comment]
Then, you don't need to call Separate() twice:
It would  be something like:
```
using (var image = new MagickImage("icon.png")) {
    IMagickImage blue = new MagickImage(), alpha = blue;
    foreach (var channel in image.Channels.Zip(image.Separate(), (c, i) => (c, i))) {
        switch (channel.Item1) {
          case PixelChannel.Blue:
              blue.Dispose();
              blue = channel.Item2;
              break;
          case PixelChannel.Alpha:
               alpha = channel.Item2;
               break;
           default:
               channel.Item2.Dispose();
               break;
          }
      }
      blue.Composite(alpha, CompositeOperator.CopyAlpha);
      blue.Write("result.png");
      blue.Dispose();
      alpha.Dispose();
}
```
I hope this will be also the answer of your second question.

**Comment by d2phap** [comment]
thanks again!
