### ISSUE TITLE
TemporaryFile throws an IOException

### ISSUE THREAD

**Issue by stepkillah** [dlemstra/Magick.NET#475]
### Description
Calling `ImageOptimizer.LosslessCompress` throws `IOException -> File already exists`. When calling this method it should create a `TemporaryFile` and this one throws exception when there is no free temporary file names or temp file folder reach limit of 65535 files. `TemporaryFile` calling `Path.GetTempFileName` in ctor which causing issue.

Here is a link to microsoft docs that says about `IOException`: https://docs.microsoft.com/ru-ru/dotnet/api/system.io.path.gettempfilename?view=netcore-2.2

This issue happens for me only on production, I don't have access to temp folder in production so I couldn't clear temporary files.

### Steps to Reproduce
1. Fill temp folder (tried on windows)
2. Create instance of `TemporaryFile`

### System Configuration

- Magick.NET-Q16-AnyCPU Version="7.14.0.1"

**Comment by stepkillah** [comment]
Found a way to change the default path for `Temp` folder using `Environment`. So not sure if it's a still a bug. Maybe mentioning this fact somewhere in docs will be a good way to prevent this.

```
        /// <summary>
        /// fix for default temp folder limit (https://docs.microsoft.com/ru-ru/dotnet/api/system.io.path.gettempfilename?view=netcore-2.2)
        /// </summary>
        /// <param name="env">Current website environment</param>
        /// <param name="folderName">Newly created temporary folder name</param>
        public static void FixTemporaryFolder(this IHostingEnvironment env, string folderName = "TEMP")
        {
            #region 
            var tempPath = Path.Combine(env.WebRootPath, folderName);
            if (!Directory.Exists(tempPath))
                Directory.CreateDirectory(tempPath);

            Environment.SetEnvironmentVariable("TEMP", tempPath);
            Environment.SetEnvironmentVariable("TMP", tempPath);
            #endregion

        }
```

**Comment by dlemstra** [comment]
The `TemporaryFile` class should automatically cleanup the file. Do you know what the cause is? Are there to many other temporary files in that folder?

**Comment by stepkillah** [comment]
@dlemstra It is automatically clean up the file, but if folder already full - it will throw an exception. As far as it is production server (shared hosting), I don't have access to temp folder to clean it up, and probably someone filled this folder on the server

**Comment by dlemstra** [comment]
Your work around is probably a good solution then.
