### ISSUE TITLE
Setting a grayscale image as an alpha channel doesn't work

### ISSUE THREAD

**Issue by thedonciuxx** [dlemstra/Magick.NET#476]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Q16 AnyCPU 7.14.0.2
- Environment (Operating system, version and so on): Windows 10 / .NET Core 2.2.202

### Question

I want to make an image that looks like this:
![White text on a transparent background fading to transparency on the right](https://user-images.githubusercontent.com/13348029/60398744-93c97880-9b64-11e9-984e-3296d35a0a16.png)
which is just some white text that fades to transparency.

It looked simple enough to do, except that for some reason no way I wanted to make it works...

The most logical solution for me was to make a grayscale image and use it as an alpha mask on a white image.

I looked at Image Magick documentation... I found info on CopyOpacity and after some digging figured out that on this wrapper, there's CopyAlpha...

It said that if both input images don't have an alpha channel enabled, then instead of copying and using the alpha values, it would use intensity.

But this doesn't seem to work.

This is my made MagickImage with your wrapper: (It's called `usernameMask`)
![White text on a black background fading to black on the right](https://user-images.githubusercontent.com/13348029/60398807-2e29bc00-9b65-11e9-9893-efd189c8d785.png)
That image was made by compositing
![Gradient from offset white on the left to offset black on the right](https://user-images.githubusercontent.com/13348029/60398875-ebb4af00-9b65-11e9-9355-eab2c8bddf58.png)
on to this
![White text on a black background](https://user-images.githubusercontent.com/13348029/60398873-de97c000-9b65-11e9-9a1a-ef1579da0339.png)
with `CompositeOperator.Darken`

This is the white image: (`usernameText`)
![White image](https://user-images.githubusercontent.com/13348029/60398826-68935900-9b65-11e9-98f0-0fe1a648dc05.png)

This is the code:
```cs
usernameText.Alpha(AlphaOption.Off);
usernameMask.Alpha(AlphaOption.Off);
Console.WriteLine(usernameText.HasAlpha); // Output: False
Console.WriteLine(usernameMask.HasAlpha); // Output: False

usernameText.Composite(usernameMask, CompositeOperator.CopyAlpha);

Console.WriteLine(usernameText.HasAlpha); // Output: True
Console.WriteLine(usernameMask.HasAlpha); // Output: False
```

This is the resulting image after:
![White image, again...](https://user-images.githubusercontent.com/13348029/60398826-68935900-9b65-11e9-98f0-0fe1a648dc05.png)

Is there a reason this isn't working?
Is there an easier way to do this?

**Comment by t246246** [comment]
It looks your usernameMask file is not GrayScale but RGBA, and the command

```% magick usernameText.png \( usernameMask.png -type GrayScale \) -compose copy_opacity -composite result.png```

works as you expected.  So you will need explicitly set ColorType.
```
usernameMask.ColorType = ColorType.GrayScale;```

**Comment by thedonciuxx** [comment]
```cs
usernameMask.ColorType = ColorType.Grayscale;
```
was not needed.

This problem was a stupid user error I made...

I, only after inspecting every line of code, noticed that I was filling the `usernameText` object with white before I wrote it...

The filling was just a debug line, which I forgot to remove...

Sorry for bothering you, because of my foolishness.
