### ISSUE TITLE
Why does Magick.NET require gswin64c.exe in Release mode, but NOT in Debug mode?

### ISSUE THREAD

**Issue by bkraul** [dlemstra/Magick.NET#477]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
Windows 10 64bit 1903

- Magick.NET version: 7.14.02 (Any-CPU)
- Environment (Operating system, version and so on): Windows 10 64bit 1903

### Question
Generally, in order to read PDF files using Magick.NET, all I have to do is include the ghostscript dlls, and use the `MagickNET.SetGhostscriptDirectory(ghostScriptPath);` method. I have noticed this works well, when the build is in Debug mode, and the reading of PDF files is generally fast.

However, when I change to Release mode, the exact same code that works in Debug fails with an error saying that it cannot execute command `gswin64c.exe` (shows all the call arguments, etc). Plus, once I do include the command-line executables, reading the PDF files is considerably slower. Is there a reason for this?

**Comment by dlemstra** [comment]
The GhostScript library is not thread safe. This means that one thread can use the library and any another thread will need to use the command line.
