### ISSUE TITLE
windows10 ，unable to draw the specified fontfamily of words

### ISSUE THREAD

**Issue by xunmi2git** [dlemstra/Magick.NET#478]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Window10 system, writing on the JPG image in cmyk format, unable to draw the specified font of words, the program will use the default font.

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

Magick.NET-Q8-AnyCPU

**Comment by dlemstra** [comment]
Your issues does not contain enough information. I have no idea what you are asking me.

**Comment by xunmi2git** [comment]
On Windows 8 system, Magick.NET-Q8-AnyCPU.dll is called by the program developed by C#, which can draw the text of specified font  on CMYK picture, and the same program on Windows 10 system draws the wrong font .I used Lifehack font test.

**Comment by dlemstra** [comment]
Is the font installed on both machines?
