### ISSUE TITLE
Read() gives unhandled exception error

### ISSUE THREAD

**Issue by mbj470** [dlemstra/Magick.NET#483]
- Magick.NET-AnyCPU version: 6.8.9.601

### Question
We have a C# ASP.Net application using Magick.NET that gives an unhandled exception errror of type 'System.AccessVioloationException' in Unknown Module. Here is some of the code that leads up to the error when it tries to Read()...

```
var settings = new MagickReadSettings();
settings.Density = new MagickGeometry(100,100);
settings.ColorSpace = ColorSpace.sRGB;
using (var images = new MagickImageCollection())
{
         images.Read(fileName, settings);  <---- Error here
```
This runs fine on our production server (Windows Server 2008 R2) but not in my local development Visual Studio 2016 environment.

What could be causing this?

**Comment by mbj470** [comment]
For a little more information, all this came to light when we tried moving our application from a Windows Server 2008 box to a Windows Server 2016 and noticed that pdf files that were being uploaded were not being converted to jpg files as our application needs.

**Comment by dlemstra** [comment]
First of all you should really upgrade to the latest version a lot of changes and fixes have been made. And that old version is not compatible with a recent version of Ghostscript. A breaking changes was made so you will need to either upgrade Magick.NET or downgrade Ghostscript.

**Comment by mbj470** [comment]
When I try to upgrade my solution through NuGet, I get the following build errors. 
![BuildErrors](https://user-images.githubusercontent.com/26581008/60808788-be13cb00-a14e-11e9-9af7-641d3f9e6673.PNG)

Below are the lines of code referenced in the errors...

var settings = new MagickReadSettings();
settings.Density = new MagickGeometry(100,100);  <- error here

var backgroundColor = new MagickColor("#FFFFFF");
newImage.ColorAlpha(backgroundColor);
newImage.Scale(.5);  <- error here

var settings = new MagickReadSettings();
settings.Density = new MagickGeometry(150, 150);  <- error here

var backgroundColor = new MagickColor("#FFFFFF");
newImage.ColorAlpha(backgroundColor)
newImage.Scale(.65);  <- error here

**Comment by dlemstra** [comment]
For `settings.Density` you will need to use the `Density` class. And for the scale method you will need to use a `Percentage` instead.

**Comment by mbj470** [comment]
Do you have any sample code showing how to use these?

**Comment by dlemstra** [comment]
There are no samples so you will need to figure that out yourself.

**Comment by mbj470** [comment]
When I try to use the Density class it looks like this...
![image](https://user-images.githubusercontent.com/26581008/60811728-82c8ca80-a155-11e9-93c3-916c77279fbb.png)
and gives me this error...
The type or namespace name could not be found (are you missing a using directive or an assembly reference?)
Is there something else that I need to download?

**Comment by dlemstra** [comment]
Have you tried restarting Visual Studio? You don't need to download anything else.

**Comment by mbj470** [comment]
After restarting, it's giving me these errors right off the bat...
![image](https://user-images.githubusercontent.com/26581008/60812284-c3751380-a156-11e9-9e6e-6b612852bef9.png)

**Comment by dlemstra** [comment]
It looks like you are using both the `6.8.9.601` and the `7.14.0.2` version in your project.

**Comment by mbj470** [comment]
Doing the upgrade causes the following condition and this compiler error...
c:\Users\mbjohnson\AppData\Local\Temp\Temporary ASP.NET Files\vs\015baea4\bb437211\assembly\dl3\6984fcd5\0073e4f7_542fd501\Magick.NET-Q16-AnyCPU.DLL'
c:\Users\mbjohnson\AppData\Local\Temp\Temporary ASP.NET Files\vs\015baea4\bb437211\assembly\dl3\09ad6db5\00398536_ffadcf01\Magick.NET-AnyCPU.DLL'

Why does it install both DLL's? What's causing this?

**Comment by dlemstra** [comment]
It does not install both DLL's but for some reason your project has referenced both versions. This really is a problem in your own project that I cannot help you with.

**Comment by mbj470** [comment]
It looks like Magick.NET-AnyCPU.DLL is what gets installed with the latest version. Will going into the bin folder of my solution and deleting the Magick.NET-Q16-AnyCPU.DLL correct the problem?

**Comment by dlemstra** [comment]
`Magick.NET-Q16-AnyCPU.dll` is the correct name of the library. You could try to remove the `Magick.NET-AnyCPU.DLL` file but as I have said before this is something you will need to figure out yourself.
