### ISSUE TITLE
Improper call to JPEG library in state 101

### ISSUE THREAD

**Issue by matty-red** [dlemstra/Magick.NET#487]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.14.0.0
- Environment (Operating system, version and so on): Windows 10

### Question
JPG optimizing failing with the following error message "Improper call to JPEG library in state 101".  Upgraded to the latest version as I thought it might be related to issue #363 but did not fix the issue.

```
Dim sourceFileInfo = New FileInfo(sourceFile)

Try
    Dim originalSize = sourceFileInfo.Length

    Dim destinationFileInfo = New FileInfo(sourceFileInfo.FullName)

    Dim optimizer As ImageMagick.ImageOptimizer = New ImageMagick.ImageOptimizer With {
        .IgnoreUnsupportedFormats = True
    }

    optimizer.Compress(destinationFileInfo)

    destinationFileInfo.Refresh()

    Dim saving = Math.Round((100 / originalSize) * (originalSize - destinationFileInfo.Length), 0)

    LogLine($"Optimized{vbTab}{destinationFileInfo.FullName}{vbTab}{originalSize}{vbTab}{destinationFileInfo.Length}{vbTab}{saving}%")

Catch ex As Exception
    LogLine(ex.Message)
    LogLine($"Invalid{vbTab}{sourceFileInfo.Name}{vbTab}{vbTab}{vbTab}")
End Try
```

**Comment by dlemstra** [comment]
Can you share your input image so I can reproduce this?

**Comment by matty-red** [comment]
Yeah sure, here is a sample image that is failing.
![EasterSearch_lrg-01](https://user-images.githubusercontent.com/13484814/61208420-48c86d00-a6ef-11e9-9458-637699bc267c.jpg)

**Comment by dlemstra** [comment]
Thanks for the image. I can reproduce your issue but I don't understand why this is happening. Will get back to you when I have more info.

**Comment by dlemstra** [comment]
Thanks for reporting this. This issue will be fixed in the next release.

**Comment by matty-red** [comment]
Thanks for the quick fix Dirk! Any idea when the next release might come?

**Comment by dlemstra** [comment]
I don't know but I might be able to create one this week.
