### ISSUE TITLE
Unable to load DLL 'Magick.NET-Q16-x86.Native.dll': The specified module could not be found

### ISSUE THREAD

**Issue by watoo** [dlemstra/Magick.NET#488]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
Code is deployed on windows server and that server is from a hosting provider company.
- When I run in visual studio it works fine, but on windows server it gives exception.
- Magick.NET version:
v 7.14.0.2

### Exception
`System.TypeInitializationException: The type initializer for 'NativeMagickSettings' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'Magick.NET-Q16-x86.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) at ImageMagick.Environment.NativeMethods.X86.Environment_Initialize() at ImageMagick.Environment.Initialize() at ImageMagick.MagickSettings.NativeMagickSettings..cctor() --- End of inner exception stack trace --- at ImageMagick.MagickSettings.NativeMagickSettings..ctor() at ImageMagick.MagickSettings..ctor() at ImageMagick.MagickImage..ctor() at projectname.controllername`

- I have confirmed the dlls in bin folder of deployed project.

How can I further debug it and figure out where the issue is?

**Comment by dlemstra** [comment]
What is the complete version that you are using? In other words the name of the NuGet package.

**Comment by watoo** [comment]
`Install-Package Magick.NET-Q16-x86 -Version 7.14.0.2`

**Comment by dlemstra** [comment]
And on which operating system are you running this?

**Comment by watoo** [comment]
My hosting provider didn't shared server information with me. So I have used the compression provided by .net

Thanks

**Comment by kalpeshboghara** [comment]
We are also facing same issue. When add Nuget Package into class library. 
Also ask same question into [here ](https://stackoverflow.com/q/57016879/3829595)

Here I am using window 10 pro

Thanks

**Comment by watoo** [comment]
Hi,
Unfortunately i'm not satisfied with .net image compression so decided to move back to Magick.NET. 
Please help me in fixing the above issue. My website is hosted at **Windows Server 2012 R2**.

**Comment by dlemstra** [comment]
This really sounds like a hosting issues. Have you tried using the 64 bit version of Magick.NET instead?
