### ISSUE TITLE
Message = "no decode delegate for this image format `INI' @ error/constitute.c/ReadImage/556"

### ISSUE THREAD

**Issue by Marcel0024** [dlemstra/Magick.NET#489]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Thrown exception when loading image in memory

ImageMagick.MagickMissingDelegateErrorException: no decode delegate for this image format `INI' @ error/constitute.c/ReadImage/556
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(MagickSettings settings)

### Steps to Reproduce
    using (var image = new MagickImage(inputPath)) // <-- throws error
    using (FileStream outImage = File.Create(outputPath)))
    {
        image.Write(outImage);
    }

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU Version="7.14.0.3"
- Environment (Operating system, version and so on): win10 x64

It also does not work on the ImageMagick library self, so it's probably not related to Magick.Net. Not sure where to post it.

![image](https://user-images.githubusercontent.com/14852157/61368271-ccb85b80-a88d-11e9-8392-2458c53b5fee.png)

The original image:

![example](https://user-images.githubusercontent.com/14852157/61368347-f5405580-a88d-11e9-9ab5-0e2e4b33946c.JPG)

**Comment by frankwaalkens** [comment]
#kutlibrary

**Comment by dlemstra** [comment]
What is the name of the file on disk? I cannot reproduce you issue on the command line. Which ImageMagick version are you using?

**Comment by Marcel0024** [comment]
I was using  ImageMagick 7.0.8-32 Q16 x64 when i ran that script.

Updating ImageMagick to ImageMagick 7.0.8-54 Q16 x64, i cannot reproduce it anymore in command line

**Comment by dlemstra** [comment]
I am unable to reproduce your issues. Is it possible to create a small repository that demonstrates this issue?

**Comment by Marcel0024** [comment]
Ok nevermind - the error in the title is wrong, i was grabbing the wrong file during debug. With the extension .ini oops.

The issue i'm having is converting the picture above to a different color profile, with this code:

    using (var image = new MagickImage(inputPath))
    using (var outImage = File.Create(outputPath))
    {
         var colorProfile = image.GetColorProfile();

         if (colorProfile == null)
         {
               image.TransformColorSpace(ColorProfile.USWebCoatedSWOP, ColorProfile.SRGB);
         }
         else if (!colorProfile.Equals(ColorProfile.SRGB))
         {
              image.AddProfile(ColorProfile.SRGB); // <-- throws error
         }

         image.Write(outImage);
    }


Error: 

> ImageMagick.MagickResourceLimitErrorException: ColorspaceColorProfileMismatch `icc' @ error/profile.c/ProfileImage/956
>    at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
>    at ImageMagick.MagickImage.NativeMagickImage.AddProfile(String name, Byte[] datum, Int32 length)
>    at TestApp.Program._colorProfileTest() in 

![image](https://user-images.githubusercontent.com/14852157/61517760-4411fa80-aa08-11e9-8e09-0361981f3085.png)

As far that i can tell, the picture does not contain a color profile. But .GetColorProfile() returns a profile with name 'icc'. That can't be right ?

**Comment by dlemstra** [comment]
The picture does contain a color profile? `colorProfile != null`?

**Comment by Marcel0024** [comment]
No, the foto contains an invalid/wrong color profile:

Opening in photoshop gives this error:
![image](https://user-images.githubusercontent.com/14852157/61527262-4ed68a80-aa1c-11e9-95ba-f00ea06c6eb6.png)

**Comment by dlemstra** [comment]
I have no idea what that message is saying (of toch wel?). Maybe you could do this:

```C#
var colorProfile = image.GetColorProfile();

if (colorProfile.ColorSpace == ColorSpace.Undefined)
{
     image.RemoveProfile(colorProfile.Name);
     // I should probably add this:
     // image.RemoveProfile(colorProfile);
}
else
{
     if (colorProfile == null)
     {
           image.TransformColorSpace(ColorProfile.USWebCoatedSWOP, ColorProfile.SRGB);
     }
     else if (!colorProfile.Equals(ColorProfile.SRGB))
     {
          image.AddProfile(ColorProfile.SRGB);
     }
}
```

**Comment by Marcel0024** [comment]
Yea thanks for your help

Ended updoing something like this:

    var colorProfile = image.GetColorProfile();

    if (colorProfile == null)
    {
        image.TransformColorSpace(ColorProfile.USWebCoatedSWOP, ColorProfile.SRGB);
    }
    else if (!colorProfile.Equals(ColorProfile.SRGB))
    {
        if (colorProfile.ColorSpace == ColorSpace.Undefined)
        {
            image.RemoveProfile(colorProfile.Name);
        }

        image.AddProfile(ColorProfile.SRGB);
    }

    image.Write(outImage);
