### ISSUE TITLE
How to Flatten an layared tiff image with MagickImage

### ISSUE THREAD

**Issue by meysamSamanpour** [dlemstra/Magick.NET#49]
Sorry if I am not supposed to ask questions here. 

How can I load a tiff image which has couple of layers and then write it on HDD as a flatten image. 
I tried this one and the result is fine, i will get an image with one layer which is the combination of all layers but I cannot get a flatten image. Actually i convert the image into PSD and then read the PSD and converet it to the original format which I think is not a good solution. 

```C#
public void FlatTheLayeredTiff(string filePath)
{
    var isMoreThanOneLayer = false;
    var extention = Path.GetExtension(filePath).ToLower();
    if (extention != ".tiff" && extention != ".tif") return;
    using (var image = new MagickImage(filePath))
    {
        using (var stream = new MemoryStream())
        {
            image.Write(stream, image.Format);
            using (var collection = new MagickImageCollection(stream))
            {
                if (collection.Count == 1) return;
            }
        }

        var psdPath = filePath.Substring(0, filePath.LastIndexOf(".") + 1) + "psd";
        image.Write(psdPath);

        using (var im = new MagickImage(psdPath))
        {
            im.Format = image.Format;
            im.Write(filePath);
        }
    }
}
```

**Comment by dlemstra** [comment]
Have you tried the following:

```C#
public void FlatTheLayeredTiff(string filePath)
{
  var extention = Path.GetExtension(filePath).ToLower();
  if (extention != ".tiff" && extention != ".tif") return;

  using (MagickImageCollection layers = new MagickImageCollection(filePath))
  {
    if (layers.Count == 1) return;

    using (MagickImage image = layers.Flatten())
    {
      image.Write(filePath);
    }
  }
}
```

**Comment by M22an** [comment]
On a slightly different note, is there a way to differentiate between multiple layers and multi-page tiff's ?

**Comment by dlemstra** [comment]
When a TIFF file contains a `tiff:37724` profile this means it is multi layer.

**Comment by dlemstra** [comment]
Can I close this issue @M22an ?

**Comment by troyzirk2** [comment]
Hi Dirk, I ran your above code using Magick.NET-Q16-AnyCPU 7.9.0.2, but the image was not flattened. I tried to attach the files, but could not, so I created a weblink zip for you to download. I included the original file and the "flattened" file, for comparison. The image contains a Photoshop alpha channel and work path.

https://vrxwestus.blob.core.windows.net/vrxstudios-downloads/DL_20190110.zip
