### ISSUE TITLE
Judgment of extension is wrong

### ISSUE THREAD

**Issue by manavu** [dlemstra/Magick.NET#491]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Q16-AnyCPU 7.14.1
- Environment (Operating system, version and so on):
Windows10

### Question

Is the extension not ttc instead of tcc?
DrawableFont class code

NG
```
private static readonly string[] _FontExtensions = new string[] { ".ttf", ".tcc", ".pfb", ".pfm", ".otf" };
```

OK
```
private static readonly string[] _FontExtensions = new string[] { ".ttf", ".ttc", ".pfb", ".pfm", ".otf" };
```

Japanese(multibyte string) could not be handled in windows environment.

**Comment by dlemstra** [comment]
Thanks for reporting this. Would you be willing to create a pull request for this?

**Comment by manavu** [comment]
I'm sorry. Inexperienced at github. I can not fix it

**Comment by dlemstra** [comment]
No problem, will do it myself then. Just wanted to give you the opportunity to do it yourself.
