### ISSUE TITLE
SetClippingPath method doesn't work

### ISSUE THREAD

**Issue by hn24** [dlemstra/Magick.NET#492]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported
 
### Description
Hi @dlemstra ,
I'm working with the SetClippingPath function. It's seem not work at this time. 
Could you please help me to take a look at it?

Thanks

### Steps to Reproduce
The step to reproduce is very simple:
1. Get my tif file and svg file from [images.zip](https://github.com/dlemstra/Magick.NET/files/3426152/images.zip)
2. Use this code to write the clipping path from svg to the tiff, then write it
```
using (var image = new MagickImage('input.tif'))
{
    image.SetClippingPath( File.ReadAllText(@"input.svg"), "Path 2");
    image.Write("output.tif", MagickFormat.Tiff);
}
```
3. Open this file again, you can see the it's missing the new clipping path
```` 
using (var image = new MagickImage("output.tif"))
{
    var clippingPath = image.GetClippingPath("Path 2");
}
````

### System Configuration

- Magick.NET version: Magick.NET-Q8-x64 v7.14.1.0
- Environment: Windows 10

**Comment by dlemstra** [comment]
The clip path of a tiff image is stored in an `EightBimProfile` and when you set it on the image it just sets an attribute on the image so other code can use it. If you want to have it stored in the image you will need to create an `EightBimProfile` and store the profile there. If you look at the code of the class you can see how it is read and reverse engineer how to store it in the profile.
