### ISSUE TITLE
Difference between Linux and Windows when converting svg to jpg/png

### ISSUE THREAD

**Issue by ktrickey** [dlemstra/Magick.NET#493]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When converting an SVG to jpeg or png (I haven't tried other bitmap formats) there is a difference in rendering when running on Linux as compared to Windows. The example SVG contains multiple tspan elements which should render next to each other (as tested in Chrome, Firefox and Edge). When running the test project (attached below) in Windows, the output matches the image displayed in the browser. On Linux each word overprints the previous one.

### Steps to Reproduce
Build and run the test project (attached) on Linux and Windows. The text in the generated bitmap.jpg on Linux will have over-printed text, when run on Windows it displays as expected. In browsers, the supplied SVG looks the same as the Windows bitmap version.

[Test project](https://github.com/dlemstra/Magick.NET/files/3430593/ImageMagick.zip)

### System Configuration

- Magick.NET version: 7.14.1
- Environment (Operating system, version and so on):
   First spotted in a Linux Container based on the MS .Net core runtime base image (Ubuntu Bionic variant) (.net core 2.2).
   Confirmed in a Hyper-V VM instance running Ubuntu 18.04.2LTS (.Net core 2.2 SDK installed)
   Windows version is 10.0.17763.557 (.Net Core 2.2)

**Comment by dlemstra** [comment]
This is happening because under Windows librsvg is being used an under Linux/macOS the internal library of ImageMagick is being used. I don't know when I will be able to add support for librsvg to the Linux build. For now you could install inkscape in your container and that should be used instead then.

**Comment by ktrickey** [comment]
That worked a treat. Thanks for your help.
