### ISSUE TITLE
HEIC Encode - no encode delegate for this image format HEIC

### ISSUE THREAD

**Issue by danwalmsley** [dlemstra/Magick.NET#495]
### Prerequisites

- [x ] I have written a descriptive issue title
- [ x] I have verified that I am using the latest version of ImageMagick
- [ x] I have searched [open](https://github.com/ImageMagick/ImageMagick/issues) and [closed](https://github.com/ImageMagick/ImageMagick/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am unable to encode an image as HEIC - 'no encode delegate for this image format `HEIC' .

### Steps to Reproduce
```
using (var encodedImage = new MagickImage(image.RawData.ToArray()
                , new PixelReadSettings(image.Width, image.Height, 
                StorageType.Float, PixelMapping.RGB)))
            {
                encodedImage.Format = MagickFormat.Heic;

                var memoryStream = new MemoryStream(5000000);
                encodedImage.Write(memoryStream);

                return memoryStream.ToArray();
            }
```

### System Configuration

This is on Windows 10 1903 - x64, im using it in a .net standard 2.0 library referenced from a UWP app.

- ImageMagick version:
`Include="Magick.NET-Q16-HDRI-x64" Version="7.14.1"`

**Comment by dlemstra** [comment]
Magick.NET only support decoding of the HEIF image due to licensing issues.

**Comment by danwalmsley** [comment]
Ah that explains it. Any chance you happen to know of another solution for .net?

**Comment by dlemstra** [comment]
I am not aware of a another solution for this.

**Comment by Poltuu** [comment]
Is this solution still correct ? any way to add the delegate to the library in order to generate .heic files ?

**Comment by dlemstra** [comment]
There now is support for writing avif files. Support for other encodings is still not possible due to licensing issues.
