### ISSUE TITLE
Can't make a clean conversion to JSON

### ISSUE THREAD

**Issue by Atario** [dlemstra/Magick.NET#497]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When I use ImageMagick to "convert" an image to JSON, like this:

     magick.exe convert foo.jpg json: > foo.json

…it gives me a JSON file full of metadata extracted/computed from the image.  If I do the equivalent in Magick.NET:

    fooImage.Write(fooMemoryStream, MagickFormat.Json);

…it gives me the same thing, except the "format" field is always "JSON" instead of the input image format, the "mimeType" field is always "application/json" instead of the input image mime type, the "filesize" field reflects the size of the JSON output instead of the input image, and so on.  Additionally, the MagickImage object's properties get altered too (one I know for sure is the .Format property is overwritten with MagickFormat.Json).

### Steps to Reproduce

See description

### System Configuration

- Magick.NET version:  Magick.NET-Q16-AnyCPU v.7.14.1 via NuGet
- Environment (Operating system, version and so on):  Win10, VS2017
- Additional information:  -

**Comment by dlemstra** [comment]
The JSON encoder inside ImageMagick does not support writing it only supports writing to a file. And when you execute that command on the command line you are writing to stdout (that is seen as a file). When you write to a stream ImageMagick internally first needs to write this to a file and that is why you get this odd output. Why advise would to be to write this to a temporary file that has a `.json` extension and then copy the file content to a stream.
