### ISSUE TITLE
Distribute .NET 3.5 build in NuGet

### ISSUE THREAD

**Issue by masaeedu** [dlemstra/Magick.NET#5]
This library would be very useful for people using Unity. Unity uses an old, .NET 3.5 equivalent version of Mono, so the .NET 4 version is incompatible.

**Comment by dlemstra** [comment]
Magick.NET is currently not supported on Mono. I published a .NET Core version this weekend. Is that supported by Unity?

**Comment by masaeedu** [comment]
@dlemstra No, unfortunately not. Nevertheless, we just need the ability to reference Magick .NET from .NET 3.5 class libraries. The compiled DLL can then be added to a Unity project.

Are there specific runtime requirements that Mono doesn't satisfy?

**Comment by dlemstra** [comment]
The NuGet package also contains a .NET 2.0 version of Magick.NET. Can you give that a try?

**Comment by masaeedu** [comment]
@dlemstra I'm not seeing this with the version I'm installing (Magick.NET-Q16-AnyCPU.7.0.0.0102). Is there a specific version that has the .NET 2.0 stuff in it?

**Comment by dlemstra** [comment]
Sorry you will need to pick either the x86 or the x64 version if you want a .NET 2.0 build. I don't have support for AnyCPU with the .NET 2.0 build at the moment.

**Comment by dlemstra** [comment]
I just tried to see if I could create a .NET 2.0 AnyCPU build of Magick.NET and I was able to do that. I am not sure if anyone needs it but the next version of Magick.NET will also include a .NET 2.0 AnyCPU build.
