### ISSUE TITLE
Add transparent text 

### ISSUE THREAD

**Issue by Yeshia** [dlemstra/Magick.NET#50]
I'm using the c# version of imagemagick. I just want to add transparent text to a white background. Seems easy enough in command line but can't figure out how to translate to c#. Any help would be appreciated. Thanks.

**Comment by dlemstra** [comment]
Can you also add the command that you execute on the command line to this post? I can then translate this for you and hopefully you will be able to translate the next command yourself :)

**Comment by Yeshia** [comment]
I haven't found an example of exactly what I want. I did find this which seems to make the background and text transparent. But I just want the text transparent. I will keep searching for the right command. 

convert -background transparent -fill rgba(255,255,255,0.35) -font arial.ttf -pointsize 20 label:"This is a test" -trim +repage testFile.png

**Comment by Yeshia** [comment]
This is the closest I can find, but it is the opposite of what I want. This creates a transparent background with a number on top. I want a white background with a transparent number carved out. This is going to be an Android icon. So I want the color of whatever the background is to go through the transparent numbers.  Maybe I do need a transparent background? Not sure if I am totally off here. 

magick  convert -background transparent -fill Black -pointsize 25 label:"99" -channel alpha -evaluate multiply 0.51 -trim +repage  testFile.png

**Comment by Yeshia** [comment]
And I figured it out, except I still would like to convert to C#

magick  convert -size 512x512 -background white -alpha remove -fill black -pointsize 400  -gravity center -geometry +10+10  label:"99" -transparent rgba(255,255,255,1) -channel a -negate out.png

**Comment by dlemstra** [comment]
Sorry for not getting back to you but I am trying to figure out a better way to do this on the command line. Will get back to you when I have more info.

**Comment by Yeshia** [comment]
I came up with a better command:

 convert -size 48x48 xc:white -fill red -font Open-Sans-Bold -pointsize 40  -gravity center +antialias -kerning -3 -annotate +0+3 30 -transparent red    out.png

**Comment by dlemstra** [comment]
I am working on some changes in ImageMagick to make it easier to draw transparent text. I will try to publish a new version with that feature in a couple days.

**Comment by dlemstra** [comment]
Sorry for taking this long with a reply but you can do this with the latest release:

```C#
using (MagickImage image = new MagickImage(MagickColors.White, 48, 48))
{
    image.Settings.FillColor = MagickColors.Transparent;
    image.Settings.StrokeColor = MagickColors.Transparent;
    image.Settings.FontPointsize = 40;
    image.Annotate("30", Gravity.Center);

    image.Write(@"i:\test.png");
}
```

Setting both the `FillColor` and the `StrokeColor` to transparent will allow you to draw transparent text.
