### ISSUE TITLE
Why is Text On Image So Small?

### ISSUE THREAD

**Issue by GlennIM** [dlemstra/Magick.NET#500]
var tempimage = new MagickImage(@"D:\\beautiful-girl-woman-young-127405_WEB.jpg");
            int textWidth = tempimage.Width - 10;
            tempimage.Dispose();

            MagickReadSettings settings = new MagickReadSettings()
            {
                FillColor = MagickColors.White, // -fill black
                StrokeColor = MagickColors.Black,
                Font = "Arial", // -font Arial
                Width = textWidth
            };

            using (var image = new MagickImage(@"D:\\beautiful-girl-woman-young-127405_WEB.jpg", settings))
            {
                image.Annotate("This is a Test", Gravity.Center);
                // write the image to the appropriate directory
                image.Write(@"D:\testimage.jpg");
            }

Below is testimage.jpg result. Why is the text on the image so small and how can I make it wider?

http://www.greatrecipes.top/testimage.jpg

**Comment by dlemstra** [comment]
You cannot use `Width` to set the width of the text in the read settings. The JPEG decoder will just ignore that. You can find some more info on how to add text to an image here: http://www.imagemagick.org/Usage/text/
