### ISSUE TITLE
Converting first page of pdf to png creates image with 2 pages

### ISSUE THREAD

**Issue by DSPAUL** [dlemstra/Magick.NET#502]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I am converting the first page of a pdf file to png to use as a preview image and it works perfectly for most pdf's but sometimes the image will have 2 pages on it with the left side just being blank and the right side being the actual first page as shown in the image below.  This only happens on the first page and on certain pdf's. Without `image.Alpha(AlphaOption.Remove); ` the left side is transparant. I can't put the original pdf file here because of file size restrictions but here is a link. 
https://thetrove.net/Books/Dungeons%20and%20Dragons/D&D%205th%20Edition/Core/Guildmasters%27%20Guide%20to%20Ravnica.pdf

I will also leave a link to a file that does work as it should for reference so you can try to find out why it behaves differently. https://drive.google.com/file/d/1Kr3ZKYy3Me0ZFOhOQAmKBZlB9JUauhW5/view

![77](https://user-images.githubusercontent.com/35136955/62978465-9f75b380-be21-11e9-81fb-ee819f49ed3c.png)

### My code
```
MagickReadSettings settings = new MagickReadSettings()
            {
                Density = new Density(100, 100),
                FrameIndex = 0, // First page
                FrameCount = 1, // Number of pages
            };
            using (MagickImage image = new MagickImage())
            {
                image.Read(pdf.Path, settings);
                image.Format = MagickFormat.Png;
                image.Alpha(AlphaOption.Remove);

                image.Write(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + @"\Library\" + pdf.ID.ToString() + ".png");
            }
```

### System Configuration

- Magick.NET version: 7.14.2
- Ghostscript version: 9.27

**Comment by dlemstra** [comment]
This appears the be a issue with Ghostscript. You can reproduce that with the following command:
```
"c:\Program Files (x86)\gs\gs9.27\bin\gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r100x100" -dFirstPage=1 -dLastPage=1 -sOutputFile=test.png -f"Guildmasters' Guide to Ravnica.pdf"
```

What you could do is call `image.Trim()` to get rid of the extra transparency.

**Comment by DSPAUL** [comment]
`image.Trim()` works great! Thank you for the quick response. 
Because this is an issue with ghostscript and not with magick.NET, I'm going to close it.
