### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by hn24** [dlemstra/Magick.NET#503]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi,
I'm running two parallel tasks to get the bounding box of my images and crop them. Sometimes, I got this error and my app exit although I covered the GetBoundingBox function within a try-catch, i tried again with the same image but i cannot reproduct the error:

> Application: MyApp.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Runtime.InteropServices.SEHException
>    at ImageMagick.MagickImage+NativeMethods+X64.MagickImage_BoundingBox_Get(IntPtr)
>    at ImageMagick.MagickImage+NativeMagickImage.get_BoundingBox()
>    at MyApp.Program.ValidateImage(System.Guid)
>    at System.Threading.Tasks.Parallel+<>c__DisplayClass31_0`2[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForEachWorker>b__0(Int32)
>    at System.Threading.Tasks.Parallel+<>c__DisplayClass17_0`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<ForWorker>b__1()
>    at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
>    at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)
>    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
>    at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
>    at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(System.Threading.Tasks.Task, Boolean)
>    at System.Threading.Tasks.TaskScheduler.TryRunInline(System.Threading.Tasks.Task, Boolean)
>    at System.Threading.Tasks.Task.InternalRunSynchronously(System.Threading.Tasks.TaskScheduler, Boolean)
>    at System.Threading.Tasks.Parallel.ForWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](Int32, Int32, System.Threading.Tasks.ParallelOptions, System.Action`1<Int32>, System.Action`2<Int32,System.Threading.Tasks.ParallelLoopState>, System.Func`4<Int32,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
>    at System.Threading.Tasks.Parallel.ForEachWorker[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.Guid>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.Guid>, System.Action`2<System.Guid,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.Guid,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.Guid,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.Guid,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
>    at System.Threading.Tasks.Parallel.ForEach[[System.Guid, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.Guid>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.Guid>)
>    at MyApp.Program.Main(System.String[])
> 

Sometimes, it is:

> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.     at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_BackgroundColor_Get(IntPtr instance)     at ImageMagick.MagickSettings.NativeMagickSettings.get_BackgroundColor()     at ImageMagick.MagickSettings..ctor()     at ImageMagick.MagickImage..ctor()     at MyApp.Program.ValidateImage(Guid imageId) in C:\MyApp\Program.cs:line 88

Also, i tried to enable / disable the OpenCL option but it still throw this error

### System Configuration

- Magick.NET version: tried with x64/any-cpu , q8 q16 but no luck
- Environment (Operating system, version and so on): Windows 10, x64

**Comment by dlemstra** [comment]
Do you also have some sample code that can be used to reproduce this issue?

**Comment by hn24** [comment]
> Do you also have some sample code that can be used to reproduce this issue?
Here, i compare two folders that contains tens TB of TIFF file, **newFilePath** is the image generated from **oldFilePath** by some filter/cropping before. Just open and collect info from them, then delete the old file.

  ```
  class Program
    {
        private static void ValidateImage(string newFilePath, string oldFilePath)
        {
            try
            {

                var info = new MyClass();
                info.OriginalSize = (int) new FileInfo(oldFilePath).Length;
                info.NewSize = (int) new FileInfo(newFilePath).Length;
                var passed = true;

                using (var oldImage = new MagickImage(oldFilePath))
                {
                    var oldBox = oldImage.BoundingBox;
                    info.OriginalBoxHeight = oldBox.Height;
                    info.OriginalBoxWidth = oldBox.Width;
                    info.OriginalHeight = oldImage.Height;
                    info.OriginalWidth = oldImage.Width;
                }


                using (var newImage = new MagickImage(newFilePath))
                {
                    var newBox = newImage.BoundingBox;
                    info.NewBoxHeight = newBox.Height;
                    info.NewBoxWidth = newBox.Width;
                    info.NewHeight = newImage.Height;
                    info.NewWidth = newImage.Width;

                    
                    //validate create thumb
                    try
                    {
                        newImage.Quality = 10;
                        newImage.Thumbnail(25, 25);
                        var tempFileName = Path.Combine(Path.GetTempPath(), Guid.NewGuid() + ".jpg");
                        newImage.Write(tempFileName);
                        File.Delete(tempFileName);
                    }
                    catch (Exception e)
                    {
                        passed = false;
                    }
                }

                //all
                if (passed)
                {
                    //delete the file
                    Console.WriteLine("Deleting " + oldFilePath);
                    File.Delete(oldFilePath);
                }

                //save the info
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
            }
        }





    }

    class MyClass
    {
        public int OriginalSize { get; set; }
        public int NewSize { get; set; }
        public int OriginalBoxHeight { get; set; }
        public int OriginalBoxWidth { get; set; }
        public int OriginalHeight { get; set; }
        public int OriginalWidth { get; set; }
        public int NewBoxHeight { get; set; }
        public int NewBoxWidth { get; set; }
        public int NewHeight { get; set; }
        public int NewWidth { get; set; }
    }
```

**Comment by dlemstra** [comment]
It looks like your code and stracktrace don't match up. Your crash is hapening when you do something in parallel but I don't see that happening here. I did find a possible issue inside the `MagickImage_BoundingBox_Get` method but that should only happen when you run out of memory. Have you checked if you are running out of memory? And are you disposing the image correctly like you do in the example above?

**Comment by hn24** [comment]
yes, i disposing the image as the same with the example. Just deleted some my personal lines. The error always come from this line

>    var oldBox = oldImage.BoundingBox;

**Comment by hn24** [comment]
Sometime, it come from the constrcutor of the image

>    using (var image = new MagickImage(inputPath))


![image](https://user-images.githubusercontent.com/53258318/63238694-bbd67d80-c271-11e9-92bd-7b5851833116.png)

**Comment by dlemstra** [comment]
Can you give this another try with the latest version? I added a fix that could help us track down the problem better.

**Comment by aqibshabbir** [comment]
Upgrading to Magick.Net 7.15.0 latest solved this issue.

**Comment by Kubsi009** [comment]
Hi Dirk Lemstra, 

I would need your help please , I was getting the same error "System.AccessViolationException: Attempted to read or write protected memory", as per your advise I used the latest version and while running with the new version I am getting error "ImageMagick.MagickResourceLimitErrorException: memory allocation failed" , could you please help as its bit urgent

**Comment by Kubsi009** [comment]
Hi Dirk Lemstra,

I would need your help please , I was getting the same error "System.AccessViolationException: Attempted to read or write protected memory", as per your advise I used the latest version and while running with the new version I am getting error "ImageMagick.MagickResourceLimitErrorException: memory allocation failed" , could you please help as its bit urgent
