### ISSUE TITLE
System.OverflowException accessing profile from specific JPG

### ISSUE THREAD

**Issue by fire-eggs** [dlemstra/Magick.NET#505]
# Description
A user submitted an image to us which we failed to load. We were using Magick.NET 7.14.03, but I have verified the problem still occurs with 7.14.2.0.

The image is attached. "Exported from darktable", according to our user.

### Steps to Reproduce

Our code (distilled):
```
var settings = new MagickReadSettings();
var imgM = new MagickImage(filename, settings);
var profile = imgM.GetExifProfile();
var exifTag = profile.GetValue(ExifTag.Orientation);
```
At the `profile.GetValue()` call, we get a System.OverflowException: Array dimensions exceeded supported range.  Examining profile in the debugger, `profile.Data` is a `{byte[38758]}` entity:

![image](https://user-images.githubusercontent.com/9809727/63214979-d2ec6280-c0ed-11e9-8dd9-c7118374bb02.png)

Call stack:
![image](https://user-images.githubusercontent.com/9809727/63214956-5fe2ec00-c0ed-11e9-9ab6-33c41d3aab1e.png)

### System Configuration

- Magick.NET version:  7.14.0.3 / 7.14.2.0
- Environment (Operating system, version and so on):  Win10.1803, x64, 
- Additional information:
The image in question.

[63210124-7b98c300-c0ea-11e9-9bc2-1860e9b21339.zip](https://github.com/dlemstra/Magick.NET/files/3512207/63210124-7b98c300-c0ea-11e9-9bc2-1860e9b21339.zip)

**Comment by fire-eggs** [comment]
FWIW, here is the metadata from exiftool.
[meta.txt](https://github.com/dlemstra/Magick.NET/files/3512218/meta.txt)

**Comment by dlemstra** [comment]
It looks like your profile contains some values that have an array or string with a ridiculous size. And Magick.NET needs some extra checks for this. I have made some local patches that make it possible to read the profile of your image. Will need to figure out some unit tests for this first though. Is this an urgent matter for you? It might be a while before a new release is available.

**Comment by fire-eggs** [comment]
Thank you for the fast response! We're working around this by catching the exception, there is no urgency on our part. Merely an advisory of yet-another-special-case, in case you wanted to handle it or at least not blow up on it.

**Comment by dlemstra** [comment]
The new release has been published

**Comment by forresthopkinsa** [comment]
I just got this error in 7.15.0

```
Unhandled OverflowException: Array dimensions exceeded supported range. - System.OverflowException: Array dimensions exceeded supported range.
   at ImageMagick.ExifReader.ReadArray[TDataType](UInt32 numberOfComponents, ReadMethod`1 read)
   at ImageMagick.ExifReader.ReadValue(ExifDataType dataType, UInt32 numberOfComponents)
   at ImageMagick.ExifReader.CreateValue(ExifTagValue tag, ExifDataType dataType, UInt32 numberOfComponents)
   at ImageMagick.ExifReader.CreateValue()
   at ImageMagick.ExifReader.AddValues(List`1 values, UInt32 index)
   at ImageMagick.ExifReader.ReadThumbnail(UInt32 offset)
   at ImageMagick.ExifReader.Read(Byte[] data)
   at ImageMagick.ExifProfile.InitializeValues()
   at ImageMagick.ExifProfile.get_Values()
```

**Comment by dlemstra** [comment]
Can you share an image that can be used to reproduce that issue @forresthopkinsa? Could also be an incorrect file.
