### ISSUE TITLE
Application crashed at MagickImage.Write() in Q8 build.

### ISSUE THREAD

**Issue by t246246** [dlemstra/Magick.NET#507]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using Q8 AnyCPU version installed from nuget, sample program crashes at magick.Write(). (It cannot be caught even adding [HandleProcessCorruptedStateExceptions])

No problem with Q16 version.

### Steps to Reproduce

Save attached file as indexed8.png.

```
using ImageMagick;
using System;
using System.IO;
using System.Runtime.ExceptionServices;

namespace ConsoleApp1
{
    class Program
    {
        [HandleProcessCorruptedStateExceptions]
        static void Main(string[] args)
        {
            using (var input = new MemoryStream())
            {
                try
                {
                    using (var output = new MemoryStream())
                    {
                        using (var magick = new MagickImage("../../indexed8.png"))
                        {
                            magick.RenderingIntent = RenderingIntent.Perceptual;
                            magick.BlackPointCompensation = true;
                            //if (magick.GetColorProfile() == null)
                            //    magick.AddProfile(ColorProfile.SRGB);
                            //magick.RemoveProfile("icc");
                            magick.ColorSpace = ColorSpace.Gray;
                            magick.ColorAlpha(MagickColors.White);
                            magick.Write(output, MagickFormat.Png00);
                        }
                    }
                }
                catch (Exception e)
                {
                    Console.Out.WriteLine(e.StackTrace);
                }
            }
        }
    }
}
```
![indexed8](https://user-images.githubusercontent.com/19387062/63333573-a26a2a00-c374-11e9-9122-8361d182cf6b.png)
### System Configuration

- Magick.NET version: 7.14.2.0 Q8 AnyCPU
- Environment (Operating system, version and so on): Windows 7 Professional 64 bit (version 6.1 Build 7601: Service Pack 1)
- Additional information: Visual Studio Enterprise 2017 (version 15.9.15). Compiled with ,NET Framework 4.7

**Comment by dlemstra** [comment]
It looks like you found a bug. Not sure what is causing this but I see that something is happening inside our PNG writer. Now I will need to figure out if this is our code or the PNG library.

**Comment by dlemstra** [comment]
The bug has been fixed in ImageMagick and I just published a new release that includes this fix.
