### ISSUE TITLE
is disposing required - and if so, why?

### ISSUE THREAD

**Issue by Tylertron1998** [dlemstra/Magick.NET#508]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
Windows x64 10 Pro, .NET Core 3.0

- Magick.NET version: Latest
- Environment (Operating system, version and so on): Windows 10

### Question
Is the disposal of MagickImage required - I have an interesting (and rather odd) usecase where I need to cache an instance of a magick image, for the lifetime of the app. I have no way of disposing of it - I remember getting a lot of files in %TEMP% when I was starting off with the library, and I think it was because of not disposing.

**Comment by dlemstra** [comment]
You need to dispose images to release all the resources used by that image. This includes memory and possibly temporary files that are use by that image to store the pixel. If you keep a single instance alive during the lifetime of your program I would not worry that much about it if you create it at the start of your image. It will most likely only use memory. But if it is huge and ImageMagick will need to swap to disk there will be files left in the `%TEMP` folder when your application stops.

**Comment by Tylertron1998** [comment]
could you define "huge" - how big would be the point where it gets moved to a physical file? And can I make sure to avoid that?

**Comment by dlemstra** [comment]
You cannot avoid that because it happens when you run out of memory. There is no definition for huge and that is why I used it it depends on how much memory is available on the system you are running it on.

**Comment by Tylertron1998** [comment]
Awesome. Seems the best thing for now is to just cache a byte[] and create a new disposable image each time. On that subject - is there any way to specify the format when doing `new MagickImage(bytes)` to avoid the (possible?) overhead of having to find the format?

**Comment by dlemstra** [comment]
You could do this: `new MagickImage(bytes, MagickFormat.YourFormat)`.

**Comment by Tylertron1998** [comment]
oh that's already a thing - my bad. Thank you so much for your help!

Last question; not sure how to go about this, but do you have any ideas when it comes to performance profiling ImageMagick? Of course, a lot of stuff is native, so stuff like dotTrace by Jetbrains don't give much information (managed code you get times for method executions, however not unmanged).

**Comment by dlemstra** [comment]
I don't have an answer to that question. I have also tried to find proper tooling to do this but so far I have not been able to find a good tool for this.

**Comment by Tylertron1998** [comment]
Okay - well thank you very much for your response, time, and clarity. If I do find any tooling to help profiling I'll mention you here. I will close this issue for now. Thanks!
