### ISSUE TITLE
Obtained the black image When PDF  to Jpeg？

### ISSUE THREAD

**Issue by AntPX** [dlemstra/Magick.NET#510]
result：
![20](https://user-images.githubusercontent.com/10260115/63844266-74ab6380-c9ba-11e9-8138-6ee153738abc.jpg)

src pdf:
![image](https://user-images.githubusercontent.com/10260115/63844332-9c9ac700-c9ba-11e9-87ee-8fa455842b2a.png)

code: just from example ConvertPDFToMultipleImages

Does anybody know why?
Thanks very much

**Comment by dlemstra** [comment]
Your PDF file probably has a transparent background changing the `BackgroundColor` in `settings` to `MagickColors.White` will probably give you the correct result.

**Comment by AntPX** [comment]
Sorry, the result is still the same.

**Comment by dlemstra** [comment]
Can you share your PDF file so I can try to reproduce your issue?

**Comment by AntPX** [comment]
[1.pdf](https://github.com/dlemstra/Magick.NET/files/3553473/1.pdf)

**Comment by AntPX** [comment]
More thanks！
Dlemstra！

**Comment by AntPX** [comment]
When the output image is changed to png , get the correct result.

**Comment by AntPX** [comment]
The process of converting PDF to PNG is relatively slow. Is there a good way to speed it up?
--------
More thanks！
Dlemstra！

**Comment by dlemstra** [comment]
When you use PNG you also get transparency and that is why you are getting a different result. If you want to write to a JPG you could use `image.ColorAlpha(MagickColors.White)` to make the transparent pixels white.

You might be able to speed to process up by choosing a different density. The example use `300` but for your use case a lower value might be good enough.

**Comment by AntPX** [comment]
Ok！
Thank you very much!
