### ISSUE TITLE
opencl doesnt run performance test in .net core 2.1 on IIS

### ISSUE THREAD

**Issue by SpongeB0T** [dlemstra/Magick.NET#511]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
Windows x64 10 Pro, .NET Core  2.1 web api
Magick.NET-Q8-AnyCPU nuget package (7.14.3)

-   Magick.NET version: Latest
-   Environment (Operating system, version and so on): Windows 10

### Question
If I delete the ImagemagickOpenCLDeviceProfile.xml and run my code to resize an image in Visual Studio Debug Mode the file will be recreated and OpenCL.IsEnabled is true. If do the same with the version that is published to IIS it doesnt recreate the xml and OpenCL.IsEnabled is always false. How can I change that?

**Comment by dlemstra** [comment]
The benchmark will only run when the machine where you are running the code on has a graphics card that supports OpenCL. And I am guessing that you are running this on a machine that has no support for this and that is why `OpenCL.IsEnabled` returns `false`.

**Comment by SpongeB0T** [comment]
The IIS is on the same machine.

**Comment by dlemstra** [comment]
Did you check if `ImagemagickOpenCLDeviceProfile.xml` is created in the folder of the user of your IIS process? And maybe you will need to enable `Load User Profile`?

**Comment by SpongeB0T** [comment]
`Load User Profile` is enabled. There is no file created.

**Comment by dlemstra** [comment]
Have you checked if your process can create a file there?

**Comment by SpongeB0T** [comment]
Yes the process can create files in that folder.

**Comment by dlemstra** [comment]
You might want to enable debug logging to get some more information. I wonder if you are looking in the correct folder.

**Comment by SpongeB0T** [comment]
Is there anything specific in the logs I should search for?

**Comment by SpongeB0T** [comment]
The logs of the IIS app show no configuration events but the local debug app has configuration events.

**Comment by dlemstra** [comment]
Magick.NET has it's own debug logging. You can find some info on how to add this to your app inside the documentation.

**Comment by SpongeB0T** [comment]
I know I used the Magick.NET debug logggin and I am saying the only difference I can see is that the debug log from the local app shows configuration events and the app on IIS doesnt.
Local app log:
[magick_vs_debug.log](https://github.com/dlemstra/Magick.NET/files/3554493/magick_vs_debug.log)

App on IIS log:
[magick_iis.log](https://github.com/dlemstra/Magick.NET/files/3554510/magick_iis.log)

**Comment by dlemstra** [comment]
The logging does not really give me more information and I also realized that we don't really have a lot of (read no) OpenCL debug logging. I should add this to the ImageMagick library.

**Comment by SpongeB0T** [comment]
Can you reproduce the problem on your pc? 

1. Create a new ASP.NET Core Web application
2. Choose API and uncheck configure for HTTPS
3. Install Magick.NET-Q8-AnyCPU nuget package (7.14.3)
4. Update Controller Action
```
  [Route("api/[controller]")]
  [ApiController]
  public class ValuesController : ControllerBase
  {
    // GET api/values
    [HttpGet]
    public ActionResult<string> Get()
    {

      var image = new MagickImage("imagePath");
      image.Resize(100, 100);

      return $"api is running. opencl {OpenCL.IsEnabled}";
    }
  }
```
5. Debug it with visual studio -> it will run the opencl benchmark if you delete the  `ImagemagickOpenCLDeviceProfile.xml` before running it and `OpenCL.IsEnabled` will be true.
6. Publish it with Publish method `FIile System` to IIS and run it-> it will not run the opencl benchmark and `OpenCL.IsEnabled` will be false.

If thats not the case then its on my end but I'am not sure what else I can try to solve it.

**Comment by dlemstra** [comment]
My guess is still that it has to do with permissions but we need some extra logging to get more info. And I don't have IIS installed on my development machine so I cannot test this myself and I will probably need your help with this. You can then test this with a development build.

p.s. You should really do `using (var image = new MagickImage("imagePath"))` to avoid memory leaks.

**Comment by SpongeB0T** [comment]
Ok

**Comment by dlemstra** [comment]
Could you test this again with the following debug build that I just created on my machine: https://www.dropbox.com/sh/2omlarb120mecwz/AAB_d_JPd4X_ubmW0UlVfmX_a?dl=0. If you cannot use this I could update Magick.Native and update it inside this project but that is a bit more work for me.

**Comment by SpongeB0T** [comment]
I think I need the x64 version if possible.

**Comment by dlemstra** [comment]
I can create a x64 build for you tonight (GMT+1) when I am back home from work.

**Comment by SpongeB0T** [comment]
Ok but i won't be able to test it on the weekend. I will test it on monday.

**Comment by dlemstra** [comment]
You could also create a build yourself. But that also requires you to build the Magick.Native library.

**Comment by dlemstra** [comment]
Just added the x64 version of the build to the folder.

**Comment by SpongeB0T** [comment]
You were right after all. It was an access problem. The IIS user needs rights for `C:\WINDOWS\system32\config\systemprofile\AppData\Local\`. After changing the access rights it worked.

**Comment by dlemstra** [comment]
Happy to hear that the extra logging helped you solved the issue. Will make sure this is added to the next release.
