### ISSUE TITLE
how to -set option:deskew:auto-crop 1 for image.Deskew()

### ISSUE THREAD

**Issue by Mr-Pearce** [dlemstra/Magick.NET#512]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
- Magick.NET version: Magick.NET-Q8-x64 7.14.3
- Environment (Operating system, version and so on): Windows

### Question
hi i made the following commandline (_ImageMagick-7.0.8-63-portable-Q16-x64_)
`convert "C:\input.bmp" -set option:deskew:auto-crop 1 -deskew 40% -fuzz 40% -trim +repage "O:\output.bmp"`

i (probably) remade this with imagemagick with
```
var image = new MagickImage("C:\input.bmp");
image.Deskew((Percentage)40);
image.Settings.FillColor = MagickColor.FromRgb(255, 255, 255);
image.ColorFuzz = new Percentage(40);
image.Trim();
```

but i don't get the same result as i cant get "**-set option:deskew:auto-crop 1**" to run.
I already tried 
`image.Settings.SetDefine("option:deskew:auto-crop", "true");`
 and 1 but it wont help

**Comment by dlemstra** [comment]
With the current version of Magick.NET you need to call  `image.SetArtifact("deskew:auto-crop",  "1")` to set that option. With the next version of Magick.NET you can use the new `DeskewSettings` class for this:

```C#
using (var image = new MagickImage("C:\input.bmp");
{
    var settings = new DeskewSettings()
    {
        AutoCrop = true,
        Threshold = new Percentage(40),
    };

    image.Deskew(settings);
}
```

**Comment by Mr-Pearce** [comment]
Ah thanks.
i tried `image.SetArtifact("option:deskew:auto-crop", "1");` but the "option" was too much.
Now it works like intended!
