### ISSUE TITLE
Control over where binaries are extracted

### ISSUE THREAD

**Issue by cannehag** [dlemstra/Magick.NET#514]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### Question
We are planning on starting to use the RUN_AS_PACKAGE feature in Azure AppServices. Using that, the wwwroot will be mounted as a read-only zip.
This will not work since Magick.NET extracts the binaries into wwwroot/runtime.
Is there a way of controlling where it should extract them? I would like to go up on directory and put the files there.

**Comment by dlemstra** [comment]
Does this answer your question: https://github.com/dlemstra/Magick.NET/tree/master/docs#anycpu?

**Comment by cannehag** [comment]
> Does this answer your question: https://github.com/dlemstra/Magick.NET/tree/master/docs#anycpu?

Oh it sure does! Totally missed that. Thank you!

**Comment by dlemstra** [comment]
No problem 👍 Feel free to reach out if you need more help.

**Comment by cannehag** [comment]
Hm, after testing this, I didn't get it to work.

`var directory = Path.Combine(Directory.GetCurrentDirectory(), "magick");
Directory.CreateDirectory(directory);
MagickAnyCPU.CacheDirectory = directory;
MagickNET.Initialize();
`

It will create the directory, but it's left empty after Initialize() is called, and the "default" runtimes directory is created and populated with the binaries.

**Comment by cannehag** [comment]
Since the directory "magick" is created, yes

**Comment by dlemstra** [comment]
Could you remove the `Directory.CreateDirectory(directory)` from your code? The directory is then probably not created because another part of the code initializes the Native library and extracts it in the default directory.

**Comment by cannehag** [comment]
If I do that, set line setting the CacheDirectory throws exception:
System.InvalidOperationException
Message=The specified directory does not exist.

p.s. Thanks, that was a long time ago that worked. Removed it from the profile :)

**Comment by dlemstra** [comment]
Yeah sorry I forgot that you could only do that with a directory that exists on disk. I still suspect that you execute some Magick.NET code before you set `MagickAnyCPU.CacheDirectory`. Would it be possible to check the creation date of those folders in milliseconds (not sure if that is even possible) and check which one is created first.

**Comment by cannehag** [comment]
So, I think I need some more explanation what to expect here.
The runtimes directory containing the different binaries are included in the artifact so that directory is not a problem, my bad.

The cachedirectory, what kind of files should I expect to see there? And, what is the difference between the CacheDirectory and the TempDirectory?

**Comment by dlemstra** [comment]
The `MagickAnyCPU.CacheDirectory` is the directory were the Native binaries that are inside the `AnyCPU` version of Magick.NET will be saved to. And `MagickNET.SetTempDirectory()` will set the directory where ImageMagick will save it's temporary files.

**Comment by cannehag** [comment]
I am initializing this in the beginning of my asp.net core project startup. The directory is created but it never have any files copied to it.
`
public void ConfigureServices(IServiceCollection services)
{
   var directory = Path.Combine(Directory.GetCurrentDirectory(), "..", "magicktemp");
   Directory.CreateDirectory(directory);
   MagickAnyCPU.CacheDirectory = directory;
   MagickNET.Initialize();
}
`

**Comment by dlemstra** [comment]
What happens if you move this to your `Program.cs` file?

**Comment by cannehag** [comment]
> What happens if you move this to your `Program.cs` file?

Nothing, the directory is empty in this case to. Moved the code to the very first thing that happens in Main()

**Comment by dlemstra** [comment]
Are you targeting .NET core? Maybe that is doing some magic that is not controlled by the Magick.NET library? I don't really understand what is happening in your situation. Is it possible to create a sample project that demonstrates the issue?

**Comment by cannehag** [comment]
The problem is that I don't really know what files to expect to be copied.
When publishing the site, I get a runtimes directory including the linux-x64, osx-x64, win-x64, win-x86.
This is ok from the RunAsPackage perspective since those directories and files are included in the zip-package.
But, what other "write to disk" operations are going on in Magick.NET? When are the files written so I can test this scenario?
Whatever test I do, I don't see any files written to the CacheDirectory, but I'm on the other hand not sure WHEN they are...

**Comment by dlemstra** [comment]
Magick,NET will only do "write to disk" operations in the temporary directory. And if you use the `AnyCPU` version of Magick.NET for .NET framework on Windows it will write files to the `MagickAnyCPU.CacheDirectory` directory.
