### ISSUE TITLE
Question/issue with MagickImage.Composite negating image colors

### ISSUE THREAD

**Issue by mrubinsk** [dlemstra/Magick.NET#515]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
.Net Framework 4.7.2 console application 

- Magick.NET version: 7.14.3 Q8 AnyCPU
- Environment (Operating system, version and so on): Windows 10 (local development), Windows Server 2016 Datacenter (production) both 64 bit.

### Question
I'm having an issue using composite, in an attempt to give the image a transparent border. The problem is that when the images are composed, it looks like the original image has it's colors inverted.  I've distilled the issue down to the following code:

```csharp
            byte[] imgBytes = File.ReadAllBytes("149917.jpg");
            MagickImage origImage = new MagickImage(imgBytes);

            MagickImage background = new MagickImage(new MagickColor(0, 0, 0, 0), 2000, 2000);
            background.Format = MagickFormat.Png;

            background.Composite(origImage, Gravity.Center, CompositeOperator.Over);

            byte[] composedImageBytes = background.ToByteArray();
            using (FileStream fs = File.Create("149917.png"))
            {
                fs.Write(composedImageBytes, 0, composedImageBytes.Length);
                fs.Close();
            }
```

When 149917.png is viewed, the colors of the original 149917.jpg image seem to be inverted. If In insert a 
```csharp
origImage.Negate();
```
immediately before the Composite() call, the resulting composite image looks as I would expect without the Negate() call.  

Any help is greatly appreciated. Am I missing something here? 

I've attached  149917.jpg file that I'm using in the above code, along with expected and actual output files.

Expected output:
![149917(expected)](https://user-images.githubusercontent.com/66822/64571410-cf857900-d331-11e9-8290-9a502ef94ec5.png)

Actual output:
![149917(actual)](https://user-images.githubusercontent.com/66822/64571414-d2806980-d331-11e9-9830-da5bdb029b8a.png)

Original file
![149917(original)](https://user-images.githubusercontent.com/66822/64571430-d90ee100-d331-11e9-832e-1b963549fb12.jpg)

**Comment by dlemstra** [comment]
Your JPEG file is in the CMYK colorspace. You will first need to change the colorspace of that image to SRGB and then do the composite operation:

```C#
byte[] imgBytes = File.ReadAllBytes("149917.jpg");
using (MagickImage origImage = new MagickImage(imgBytes))
{
    origImage.TransformColorSpace(ColorProfile.SRGB);

    using (MagickImage background = new MagickImage(MagickColors.None, 2000, 2000))
    {
        background.Format = MagickFormat.Png;

        background.Composite(origImage, Gravity.Center, CompositeOperator.Over);

        byte[] composedImageBytes = background.ToByteArray();
        using (FileStream fs = File.Create("149917.png"))
        {
            fs.Write(composedImageBytes, 0, composedImageBytes.Length);
            fs.Close();
        }
    }
}
```

**Comment by mrubinsk** [comment]
I was, indeed, missing something obvious. 

Thank you VERY much @dlemstra, VERY much.

**Comment by dlemstra** [comment]
No worries, this was not that obvious also took me some time to figure this out 😄
