### ISSUE TITLE
Is .cube type of lut available?

### ISSUE THREAD

**Issue by SLS8** [dlemstra/Magick.NET#516]
Hello.
Is it possible to translate this command parameter to .net? Thank you.

`magick.exe input.jpg cube:test.cube -hald-clut output.jpg`

**Comment by dlemstra** [comment]
Your command would translate to this:

```C#
using (var image = new MagickImage("input.jpg"))
{
    using (var cube = new MagickImage("cube:test.cube"))
    {
        image.HaldClut(cube);
        image.Write("output.jpg");
    }
}
```

**Comment by SLS8** [comment]
I didn't know I can write MagickImage("cube:..."). Thank you very much.
