### ISSUE TITLE
ConnectedComponent Area Property

### ISSUE THREAD

**Issue by bseay** [dlemstra/Magick.NET#517]
ImageMagick's ConnectedComponents feature exposes an **area** for each component it detects (an example of this can be seen in their documentation here: https://imagemagick.org/script/connected-components.php ) when you set the command line parameter: _-define connected-components:verbose=true_

Notice that the area is not just the width * height of the bounding region of the component; it is actually the pixel count of the component itself.

My request is that you expose this area as a property on the ConnectedComponent object.

**Comment by dlemstra** [comment]
For some reason this property is already available in the native library but not in Magick.NET. I just pushed a patch to add this in the next release that should be available very soon.

**Comment by bseay** [comment]
Thank you!
