### ISSUE TITLE
Need example of lossless optimization using a Stream

### ISSUE THREAD

**Issue by eat-sleep-code** [dlemstra/Magick.NET#518]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of Magick.NET

### System Configuration
- Magick.NET version: 7.14.3
- Environment (Operating system, version and so on): In Development, Windows 10, in production this will run on Windows Server

### Question

I have a model which stores image data as a byte array.   It looks like this:

```
using System;

namespace SliceThenSqueeze.Models
{
	public class ImageModel
	{
		public Guid ID { get; set; }
		public string FileName { get; set; }
		public string ContentType { get; set; }
		public byte[] FileData { get; set; }
		public int FileLength { get; set; }
		public int Width { get; set; }
		public int Height { get; set; }
		public int Resolution { get; set; }
		public string ImageType { get; set; }
		public DateTime Created { get; set; }

		public ImageModel()
		{
			ID = new Guid();
			FileName = string.Empty;
			ContentType = string.Empty;
			FileData = new byte[0];
			FileLength = 0;
			Width = 0;
			Height = 0;
			Resolution = 72;
			ImageType = string.Empty;
			Created = DateTime.Now;
		}
	}
}
```

I am trying to pass this model to a method to do Lossless Optimization and then update that ImageModel.

```
public static ImageModel Squeeze(this ImageModel imageToSqueeze)
{
	Stream inputStream = new MemoryStream(imageToSqueeze.FileData);
	inputStream.Position = 0;
	ImageOptimizer optimizer = new ImageOptimizer();
	optimizer.LosslessCompress(inputStream);
				
	// How do I get the optimized data from the ImageOptimizer to feed back to input.FileData ??
			
	return imageToSqueeze;
}
```

As you will see my inline comment, getting a bit confused on how to update the data in the model with the optimized data.

**Comment by dlemstra** [comment]
The `inputStream` has been modified so calling `inputStream.ToArray()` should give you the data that you want. And you can use the return value of `LosslessCompress` to check if the data was compressed.
