### ISSUE TITLE
The Resize Function not avaliable

### ISSUE THREAD

**Issue by pjkpjpk** [dlemstra/Magick.NET#519]
### Prerequisites

.Net core 2.2 ConsoleApplication
Magick.NET-Q8-AnyCPU 7.14.3

### Description
When i trying to  invoke the 'Resize'  function, the thread like is blocked and the cpu using rate raise to 100%。what causes that?  Is it a bug or some thing I have doing are wrong? 
But when i change the Magick.NET version to 6.0.0.0 and use the .net framework console application, the function worked well. 
please give me some information, Thanks a lot!

### Steps to Reproduce
the codes like below:
class Program
    {
        static void Main(string[] args)
        {
            using (MagickImage image = new MagickImage("filename"))
            {
                image.Quality = 100;
                MagickGeometry size = new MagickGeometry(100, 100);
                size.IgnoreAspectRatio = true;
                image.Resize(size);
                image.Write($"outputfilename");
            }
            Console.ReadKey();
        }
    }

### System Configuration

- Magick.NET version: Magick.NET-Q8-AnyCPU 7.14.3
- Environment (Operating system, version and so on): WIN7 64bit  .Net core 2.2 ConsoleApplication VS2019
- Additional information:

**Comment by dlemstra** [comment]
Your thread is not "blocked" and is using a lot of CPU because it is doing an initial OpenCL benchmark. You will either need to wait till the OpenCL benchmark is done or disable OpenCL with `OpenCL.IsEnabled=false`.

**Comment by pjkpjpk** [comment]
> Your thread is not "blocked" and is using a lot of CPU because it is doing an initial OpenCL benchmark. You will either need to wait till the OpenCL benchmark is done or disable OpenCL with `OpenCL.IsEnabled=false`.

Thanks for your quick reply! Follow your advice, the  code works well.
