### ISSUE TITLE
Resize() in c# has a different quality with -resize in cmd

### ISSUE THREAD

**Issue by erickao08** [dlemstra/Magick.NET#52]
I'm having issue with the Resize function. 

When I process the image with C#, the resize() will give me the image with the worse quality when the image size is decrease from width and height are 2000 to 200 or lower then I use cmd "-resize"

My code is below
C#
`                               MagickImage Small = fullsizeImg;
                                MagickGeometry size_Small = new MagickGeometry(80, 80);
                                size_Small.IgnoreAspectRatio = true;
                                Small.Resize(size_Small);
`
cmd
`
convert input.jpg -resize 135 output.jpg 
`
I tried AdaptiveResize() as well but the result is even worse.
Please check below. 

This is generated from Resize()
![size135_code](https://cloud.githubusercontent.com/assets/4998259/25968686/0d7efc96-3658-11e7-83a6-2c7a67b5746f.jpg)

This is generated from cmd
![size135_cmd](https://cloud.githubusercontent.com/assets/4998259/25968687/0d80c508-3658-11e7-83ad-3897fe2553aa.jpg)

Original size
![input](https://cloud.githubusercontent.com/assets/4998259/25968688/0d849516-3658-11e7-851e-03d278206629.jpg)

Thanks!

**Comment by dlemstra** [comment]
You should translate your command to this:
```C#
//  You should create a Clone here, otherwise you will be working on the original.
using (MagickImage Small = fullsizeImg.Clone())
{
  Small.Resize(135, 0); // This is what -resize 135 translate to
  Small.Write("output.jpg");
}

**Comment by erickao08** [comment]
Hi @dlemstra  I've tried it but no luck. 
Any advice?

Thank you!

**Comment by dlemstra** [comment]
I get the following output image with the code sample that I wrote:

![resized](https://cloud.githubusercontent.com/assets/10426229/26121510/ca12dc18-3a74-11e7-9894-c1e9f4175676.jpg)

Are you resizing the image multiple times? You might be enlarging the image at some point and that will result in an image with terrible quality.

**Comment by erickao08** [comment]
Yes you are right!
I think the input image got transformed in the process. 

Thank you!
