### ISSUE TITLE
Netstandard20 assembly on Mono/Linux with net46: FileInfo type unavailable

### ISSUE THREAD

**Issue by deanjl** [dlemstra/Magick.NET#520]
I am using Mono on a Linux computer (Debian 10), attempting to compile an FSharp project whose target framework is net46. I am referencing the lib/netstandard20/ assembly in the Magick.net nuget package, and have copied the Magick.Native build for Linux into the output directory.

For the source file that uses the Magick namespace, for each line that attempts to access it, the compiler produces the following error:

///////.fs(163,29): error FS1108: The type 'FileInfo' is required here and is unavailable. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. [///////.fsproj]

This is not an issue with the namespace of the file itself, which includes System.IO and recognizes 'FileInfo' just fine. The issue is Magick's access to 'FileInfo' which apparently requires Magick to access netstandard2 in my net46 environment.

It is not obvious to me how netstandard should be referenced in this context. It is not listed as an explicit dependency of Magick, and seems intended as the target framework itself, as opposed to a supplement to .NET Framework as Magick requires for mono-net46 users.

Thanks in advance.

**Comment by dlemstra** [comment]
I have no experience with mono but what happens when you add the following to your csproj:

```xml
<ItemGroup>
  <Reference Include="netstandard" />
</ItemGroup>
```

or this:
```xml
<ItemGroup>
  <compilation debug="true" targetFramework="4.6.1">
    <assemblies>
      <add assembly="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"/>
    </assemblies>
  </compilation>
</ItemGroup>
```

**Comment by deanjl** [comment]
No luck, unfortunately. The first piece of code merely triggered a "Could not resolve this reference" warning. The second piece of code, after placing it inside a 'target' element as necessary, had no effect at all.

**Comment by deanjl** [comment]
I have found the problem. .NET Framework 4.6.*1* supports .NET Standard 2.0. This project merely targets 4.6, which only supports .NET Standard 1.3, a subtle oversight on my part. This is presumably why I'm being asked to provide a reference. Closing the issue.
