### ISSUE TITLE
No tag 2019.9.20.748 for Magick.Native

### ISSUE THREAD

**Issue by t246246** [dlemstra/Magick.NET#521]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.14.4.0
- Environment (Operating system, version and so on):

### Question

When I donwload Magick.NET 7.14.4.0 and see the file src\Magick.Native\Magick.Native.version, its version is 2019.9.20.748, but there is no such tag in Magick.Native repositories. Latest is 2019.9.14.517.  How do I get the exact source to build Magick.NET 7.14.4.0?

**Comment by dlemstra** [comment]
You can get the correct source by running the batch file `install.cmd`.

**Comment by t246246** [comment]
It looks something has changed again.

As far as I understand, `src/Magick.Native/install.cmd` calls install.ps1 and it download binaries from dropbox, then do something.  Message says it installed Magick.Navive to src\Magick.Native\temp\..\temp but it looks there is nothing there.

I need source code because I have to modify some ImageMagick soruce.

**Comment by t246246** [comment]
Thank you. That's what I wanted to know.
Then I can download the source as a zip like this:
https://github.com/dlemstra/Magick.Native/archive/8fe81cf9eb9d9bc44c247d4fbfea14609600e3b6.zip
