### ISSUE TITLE
Add Noise Issue

### ISSUE THREAD

**Issue by JineshVP** [dlemstra/Magick.NET#522]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:Magick.NET-Q8-AnyCPU
- Environment (Operating system, version and so on):Windows

### Question
I used the following code to add noise in my images
using (MagickImage second = new MagickImage("D:\\Tiff\\45103424.jpg"))
            {
                second.AddNoise(NoiseType.Gaussian, 3.0, Channels.RGB);                
                second.Write("D:\\Tiff\\04221081neww112.jpg");
            }

but the output always shows rgb noise, i tried all options in Channels, but result same.
Is there any option for monochromatic noised image?

**Comment by dlemstra** [comment]
I dont really understand what you are asking. Is your original image monochrome or do you want to make it monochrome? Is it possible to add some images that explain what you want?

**Comment by JineshVP** [comment]
@dlemstra  my original image is not monochrome , but i need to add monochrome  noise into that image.

**Comment by JineshVP** [comment]
@dlemstra  i tried the following code
compiler.StartInfo.Arguments = string.Format("convert D:\\Tiff\\102105079.tif -set colorspace RGB -separate -seed 1000 -attenuate 10 +noise gaussian -combine D:\\Tiff\\102105079new.jpg")


![102105079](https://user-images.githubusercontent.com/8242008/66745202-05230200-ee9c-11e9-917d-c7b702b2ec4b.jpg)

**Comment by dlemstra** [comment]
If you are calling `convert.exe` directly you should probably ask your question here: https://imagemagick.org/discourse-server/
