### ISSUE TITLE
Environment Variables?

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#524]
How would I modify `MAGICK_MAP_LIMIT` and similar environment variables in ImageMagick.net?

**Comment by dlemstra** [comment]
Currently there is no option for this but I think it could be possible to add this to the library. But that setting that you want to control can already be controlled if you call `MagickNET.Initialize` with your own configuration. You will need to override the `policy,xml` file. My advise would be to add your own xml element to the embeded configuration:

```C#
var configFiles = ConfigurationFiles.Default;
configFiles.Policy.Data = AddCustomPolicy(configFiles.Policy.Data);
MagickNET.Initialize(configFiles);
```

**Comment by daxpandhi** [comment]
Ahh - thanks! I was originally looking for this, but the link in the initialization docs page leads to a 404. Couldn't find the XML folder in the source folder either.

I'm assuming it is the same as https://imagemagick.org/source/policy.xml 

Thanks, Dirk!

**Comment by daxpandhi** [comment]
Duh - nevermind. Just read the page properly and see it can write the files. Closing the issue. :) Thanks again!
