### ISSUE TITLE
Same file size regardless if image DPI is 300 or 72

### ISSUE THREAD

**Issue by eat-sleep-code** [dlemstra/Magick.NET#525]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.14.4
- Environment (Operating system, version and so on):  Windows 10 for development, Azure Web App production

### Question
If I pass a large (2700px x 2700px x 300dpi) image to the code, I am getting the same file size when I resize it to 1920px x 1920px, regardless if I set the Density or not.

If I don't set it, the output image is 2,197KB in size and Windows reports the DPI to be 300dpi.
If I set it using the following, the image is **still** 2,197KB and Windows reports the DPI to be 72dpi:

```
Stream inputStream = new MemoryStream(input.FileData);
inputStream.Position = 0;
using MagickImage inputImage = new MagickImage(inputStream);
inputImage.Density = new Density(72, 72, DensityUnit.PixelsPerInch);
inputImage.Resize(outputWidth, 0);
```

After performing this step, I execute:

```
Stream inputStream = new MemoryStream(imageToSqueeze.FileData);
inputStream.Position = 0;
ImageOptimizer optimizer = new ImageOptimizer();
//optimizer.OptimalCompression = true;  // DOESN'T SEEM TO MAKE SIZE DIFFERENCE, BUT TAKES TWICE AS LONG?
optimizer.IgnoreUnsupportedFormats = true;
optimizer.LosslessCompress(inputStream);
```

I would think the file size would be less?   Or is there no advantage to setting the density?

PS: Also see note about Optimal Compression seeming to have zero difference other than processing time.

**Comment by dlemstra** [comment]
DPI does not affect the size of your image. But are you sure that your image is resized? It is a bit odd that the size is the same. Can you share your input image?

Setting `optimizer.OptimalCompression = true` just means that different attempts are made to reduce the size of the image. And yes that will take longer but does not always mean that the size of the image will be reduced if you enable it.

**Comment by eat-sleep-code** [comment]
Zipping image, just so Github doesn't try to optimize the image themselves. :-)

[shutterstock_204488020.zip](https://github.com/dlemstra/Magick.NET/files/3699237/shutterstock_204488020.zip)

**Comment by dlemstra** [comment]
It seems I misunderstood you. I thought your input image was also `2,197KB`. Setting the density does nothing else besides setting some metadata in the image. It does nothing with the pixels of the image. I hope this answers your question.

**Comment by eat-sleep-code** [comment]
Thanks for the clarification.    I guess as I think about it, that makes sense.   Same number of pixels, just one has them crammed closer together.   Nevermind, apparently not enough caffeine.
