### ISSUE TITLE
Crop and resize order

### ISSUE THREAD

**Issue by stanley-zenfolio** [dlemstra/Magick.NET#527]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:
- Environment (Windows 10):

### Question
I have a large image to be resized to a small size, keeping aspect ratio. I can either crop first then resize or resize first then crop. Is there any performance difference?

**Comment by dlemstra** [comment]
Can you explain in more detail what you want to do? I don't understand why you want to crop the image and keep the aspect ratio.

**Comment by stanley-zenfolio** [comment]
For example, I have any image 5000x3000. I want to resize it to 500x400 for web display (filling the entire 500x400 area) but don't want the image distorted. I mistakenly stated "keeping aspect ratio". Should be "keeping image undistorted".
The image, after resized to fit height 400, would have width 667. But the area is only 500x400. So the image would have to be cropped on both left and right sides to make it fit into 500x400.
The question is: Shall I crop first or resize first? I guess I need to set IgnoreAspectRatio to true.

**Comment by dlemstra** [comment]
It will be faster to first resize the image and then crop the image. This will be faster because the area that you need to crop is a lot smaller than when you have the full size image.
