### ISSUE TITLE
Cannot open particular BMP file due to `length and filesize do not match`

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#528]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Cannot open the attached BMP file due to 
```
length and filesize do not match, @ error/bmp.c/ReadBMPImage/830
```

### Steps to Reproduce
1. Download the sample BMP file at: https://www.dropbox.com/s/ezaxmf1eurhboi8/jlf8.bmp?dl=0
2. Open with MagickViewer
3. See error

### System Configuration

- Magick.NET version: 7.14.4
- Environment (Operating system, version and so on): Win 10 Insider, build 18990.vb_Release.190921-1704
- Additional information:

#### Open with MagickViewer
![image](https://user-images.githubusercontent.com/3154213/67218615-40ec3780-f459-11e9-9199-e2a2696d54c9.png)

#### Open with MS Paint:
![image](https://user-images.githubusercontent.com/3154213/67218856-ac360980-f459-11e9-84c5-4e71ae8862ad.png)

**Comment by dlemstra** [comment]
It appears that this file reports an incorrect extra 4 bytes. This looks like a bug in the program that created that BMP file. I just pushed a patch to ImageMagick to only report a warning when there are an extra 4 bytes in the file. Will need to talk with the team to make sure this is okay. Will get back to you as soon as I have an answer.

**Comment by dlemstra** [comment]
I can confirm that this 'fix' will be available in the next release.

**Comment by d2phap** [comment]
Thanks @dlemstra !
