### ISSUE TITLE
Image Quality affected during resize

### ISSUE THREAD

**Issue by M22an** [dlemstra/Magick.NET#53]
I am trying to resize an image of any size to tabloid (11" x 17") and converting to PDF. Without the resize I am getting clear pdf but when I do a resize the PDF quality vastly deteriorates.

Can you help me out on this issue ?
[Testfile1_high_res7200by200_16bit_WithoutResize.pdf](https://github.com/dlemstra/Magick.NET/files/1018796/Testfile1_high_res7200by200_16bit_WithoutResize.pdf)
[Testfile1_high_res7200by200_16bit_WithResize.pdf](https://github.com/dlemstra/Magick.NET/files/1018797/Testfile1_high_res7200by200_16bit_WithResize.pdf)

Note: In addition to resize, I am also doing other operations like adding border, rotating the image, etc. The file (Testfile1_high_res7200by200_16bit_WithoutResize.pdf), has all other changes applied other than resize.

**Comment by dlemstra** [comment]
Can you also provide me with a small code sample that I can use to reproduce this issue?

**Comment by M22an** [comment]
Here is the minimalistic version that I could make,

Am also adding the input file here for reference 
[Testfile1_high_res7200by200_16bit.zip](https://github.com/dlemstra/Magick.NET/files/1018950/Testfile1_high_res7200by200_16bit.zip)

`
static void test(string inputFilePath)
    {
      using (MagickImageCollection images = new MagickImageCollection(inputFilePath))
      {
        var transformedImages = new MagickImageCollection();
        foreach (var image in images)
        {
          var targetDensity = GetImageDensity(image);

          image.Density = new Density(targetDensity, targetDensity, DensityUnit.PixelsPerInch);
          var imageWidthInInches = Convert.ToDouble(image.Width / targetDensity);
          var imageHeightInInches = Convert.ToDouble(image.Height / targetDensity);

          // Rotate the image if the image width is greater than its height
          if (imageWidthInInches > imageHeightInInches)
          {
            image.Rotate(-90);

            // Swap width and height as we are rotating the image 90 degrees
            imageWidthInInches = imageWidthInInches + imageHeightInInches;
            imageHeightInInches = imageWidthInInches - imageHeightInInches;
            imageWidthInInches = imageWidthInInches - imageHeightInInches;
          }

          double standardHeightInInches = 17.0, standardWidthInInches = 11.0;

          if (standardWidthInInches < imageWidthInInches || standardHeightInInches < imageHeightInInches)
          {
            // Consider the border size as well for the page when adjust the width and height
            double defaultBorderSizeInInches = 0.25 * 2; // For borders on both sides
            var widthReductionRatio = (imageWidthInInches - (standardWidthInInches - defaultBorderSizeInInches)) / imageWidthInInches;
            var heightReductionRatio = (imageHeightInInches - (standardHeightInInches - defaultBorderSizeInInches)) / imageHeightInInches;

            // Identify the max reduction ratio
            var maxReductionRatio = Math.Max(widthReductionRatio, heightReductionRatio);

            // Reduce the equivalant of Max reduction ratio from the images' width and height 
            imageWidthInInches -= (imageWidthInInches * maxReductionRatio);
            imageHeightInInches -= (imageHeightInInches * maxReductionRatio);

          }

          int maxPageHeightUnit = Convert.ToInt32(standardHeightInInches * targetDensity);
          int maxPageWidthUnit = Convert.ToInt32(standardWidthInInches * targetDensity);

          MagickGeometry ge = new MagickGeometry();

          // Identify the exact image units 
          ge.Height = Convert.ToInt32(imageHeightInInches * targetDensity);
          ge.Width = Convert.ToInt32(imageWidthInInches * targetDensity);

          // Adjust the height and width so that the image has even borders
          ge.Height = (maxPageHeightUnit - ge.Height) % 2 == 0 ? ge.Height : ge.Height + 1;
          ge.Width = (maxPageWidthUnit - ge.Width) % 2 == 0 ? ge.Width : ge.Width + 1;

          image.Resize(ge);

          image.BorderColor = new MagickColor("WHITE"); // This will create white color border irrespective of colorspace
          image.CompressionMethod = CompressionMethod.Zip;
          int horizontalBorder = Convert.ToInt32(maxPageWidthUnit - ge.Width) / 2;
          int verticalBorder = Convert.ToInt32(maxPageHeightUnit - ge.Height) / 2;
          image.Border(horizontalBorder, verticalBorder);

          transformedImages.Add(image);
        }

        transformedImages.Write("test.pdf");
      }
        
    }

`

**Comment by dlemstra** [comment]
I don't understand what you think that is wrong with the resize operation. It looks like it is blurry but I think that is happening because of the dithered gray pixels on the top and bottom of each color. When you open the image in an editor and put a window over the top and the bottom part you will notice that the color looks fine.

**Comment by M22an** [comment]
In the PDF that is generated, you can see that in places the text and the black line is not properly generated, looks like pixels are broken.

You can see the differences more clearly when you zoom in on both PDF files and focus on the text portion.

Is there any alternative way that I can use to make sure that pixels don't break ?

**Comment by dlemstra** [comment]
This looks like the correct behavior. You will loose some of the details when you make the image smaller. When you zoom in the pixels will be a bit blurred. What is the goal of your resize action?

**Comment by M22an** [comment]
My goal is to fit the image into a standard page size like Tabloid without without breaking pixels and loosing the aspect ratio
.

**Comment by dlemstra** [comment]
Have you tried to just change the density without resizing the image?

**Comment by M22an** [comment]
No I haven't tried that. How would I know the exact density to set ? Would it be proportional to the width and height that I am expecting ?

**Comment by M22an** [comment]
I did something like this
```csharp
if (tempImageWidthInInches >= (standardPageWidthInInches - defaultBorderSizeInInches))
{
  densityFactor = (tempImageWidthInInches / (standardPageWidthInInches - defaultBorderSizeInInches));
}
else if (tempImageHeightInInches >= (standardPageHeightInInches - defaultBorderSizeInInches))
  densityFactor = (tempImageHeightInInches / (standardPageHeightInInches - defaultBorderSizeInInches));

targetDensity = originalDensity * densityFactor;

image.Density = new Density(targetDensity, targetDensity, DensityUnit.PixelsPerInch);
```

but this is not producing results as expected. When looking for a legal size file (8.5" X 14") I end up with a file having 9.97" X 15.96". 

Any suggestions on what I might be doing wrong ?

**Comment by M22an** [comment]
Another thing is increasing the density of the image is increasing the size of the PDF file generated and is also taking longer time. Is this expected or Is there anything I am missing ?

**Comment by dlemstra** [comment]
The size of the file is increased because you want an image with a better quality. This needs to be stored somewhere and will take up more space. And creating an image with a better quality will also take more time.

I would not use the `originalDensity` in the calculation and just calculate the required density instead.

```C#
double x = image.Width / 14;
double y = image.Height / 8.5;
image.Density = new Density(x, y, DensityUnit.PixelsPerInch);
```

**Comment by M22an** [comment]
Thanks @dlemstra, I understand the impact. We started using a similar approach and are seeing better results at the moment. We run into slowness only when the resolution and density is really high, but that is acceptable as we won't expect such images on a regular basis.
