### ISSUE TITLE
Convert SVG with big png base64 code inside file to PNG format

### ISSUE THREAD

**Issue by NarekMayilyan** [dlemstra/Magick.NET#531]
### System Configuration
.net Core 2.1

- Magick.NET version:
Magick.NET-Q16-AnyCPU 7.7.0, Windows 10 OS

### Question
I'm trying to convert a SVG file (inside which there is a PNG file in base64 format) to a PNG format. The size of the PNG file inside the SVG is, for example, 22 MB, and when you try to convert the PNG file, you get just a white picture. Is it possible to convert such large files, if possible, then what is the problem ??

`  

           var settings = new MagickReadSettings
            {
                Format = format,
                BackgroundColor = MagickColors.Transparent
            };

            using (var magickImage = new MagickImage(bytesXml, settings))
            {
                bigPngBytes = magickImage.ToByteArray(MagickFormat.Png32);
            }

`

**Comment by dlemstra** [comment]
Can you share a sample file so I can better understand your issue?

**Comment by NarekMayilyan** [comment]
https://files.fm/u/degghdnv

**Comment by NarekMayilyan** [comment]
is there any news about my problem?

**Comment by dlemstra** [comment]
I have not had time to take a look at this. It looks like you have a white image? And the viewport is only `819x819` eventhough the "data" image is `8000x8000`?

**Comment by NarekMayilyan** [comment]
Yes, as a result of the conversion, I get a white picture, this happens when I try to attach large-resolution pictures with large sizes to the SVG (for example, like in this case 8000x8000)

**Comment by dlemstra** [comment]
It looks like the embedded PNG file is not completely read. I don't understand why but it will require me to step through it with a debugger. I won't be able to work on this anytime soon though. When I have more info I will get back to you.

**Comment by NarekMayilyan** [comment]
Ok, thank you.

**Comment by NarekMayilyan** [comment]
is there any news about my issue?

**Comment by dlemstra** [comment]
It turns out that you are running into a limit of the xml parsing library. There is an option to enable huge svg files but that is not yet possible to do with the current version of MagickNET. I just pushed a patch to allow this and in the next release of MagickNET you can do this:

```C#
var settings = new MagickReadSettings
{
    Format = format,
    BackgroundColor = MagickColors.Transparent
};

settings.SetDefine(MagickFormat.Svg, "xml-parse-huge", true);

using (var magickImage = new MagickImage(bytesXml, settings))
 {
     bigPngBytes = magickImage.ToByteArray(MagickFormat.Png32);
}
