### ISSUE TITLE
Output File DPI Always 96

### ISSUE THREAD

**Issue by mikelunn** [dlemstra/Magick.NET#532]
### Prerequisites

- [x] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of Magick.NET

### System Configuration

Windows 10
Ghostscript 9.26
- Magick.NET version: 7.0.9-1
- Environment (Operating system, version and so on):

### Question
I'm following one of the repo samples for converting pdf to png. It works fine but regardless of the DPI I set, each output file DPI is always 96.

```C#
MagickReadSettings settings = new MagickReadSettings();
settings.Density = new Density(300, 300);
using (MagickImageCollection images = new MagickImageCollection())
{
               
    images.Read(fileSource, settings);

    int page = 1;
    foreach (MagickImage image in images)
    {
       var fullFilePath = Path.Combine(outputPath + "\\", page + "-magik" + ".PNG");
       image.Format = MagickFormat.Png32;
       image.Write(fullFilePath);
       page++;
    }
}
````
Is this DPI setting the DPI that the file is read before the conversion? I've also tried using the ImageMagick command line with a 300 density and get the same results. Could this be an underlying issue with ImageMagick? Any direction or help is greatly appreciated. Thanks for this repo.

**Comment by dlemstra** [comment]
Is it possible to share the pdf file that you are using for testing?

**Comment by mikelunn** [comment]
@dlemstra Going to close this. Although MS image editor displays converted image  metadata as 96 DPI, the actual pixel dimensions seemed on par. I'm  referring to this SO post:
[why-does-imagemagick-always-convert-to-96-dpi](https://stackoverflow.com/questions/29747146/why-does-imagemagick-always-convert-to-96-dpi)
