### ISSUE TITLE
Add Watermark text to image

### ISSUE THREAD

**Issue by Edward-Zhou** [dlemstra/Magick.NET#534]
For command, we could try below to add transparent text to image
```
 convert -size 140x80 xc:none -fill grey \
          -gravity NorthWest -draw "text 10,10 'Copyright'" \
          -gravity SouthEast -draw "text 5,15 'Copyright'" \
          miff:- |\
    composite -tile - logo.jpg  wmark_text_tiled.jpg
```
I am wondering how to achieve this with `Magick.Net`.

I may need many `Copyright` over the image with position from top right to left bottom.

An expected result like below:

![image](https://user-images.githubusercontent.com/16079555/68370339-34652000-0177-11ea-8392-46f37635377b.png)

**Comment by Edward-Zhou** [comment]
I tryied command below, which works, but how to convert it to magick.net?

`convert -size 300x100 xc:none -fill grey -gravity NorthWest -draw "rotate 45 text 10,10 'Copyright'"  miff:- |  composite -tile - test.png  wmark_text_tiled.jpg`

**Comment by dlemstra** [comment]
Your last command would translate to this:

```C#
using (var copyright = new MagickImage("xc:none", 300, 100)) // -size 300x100 xc:none
{
    copyright.Draw(new Drawables()
        .FillColor(new MagickColor("grey")) // -fill grey
        .Gravity(Gravity.Northwest) // -gravity NorthWest
        .Rotation(45) // -draw "rotate 45"
        .Text(10, 10, "Copyright")); // -draw "text 10,10 'Copyright'"

    using (var image = new MagickImage("test.png"))
    {
        image.Tile(copyright, CompositeOperator.Over); // -tile
        image.Write("wmark_text_tiled");
    }
}
```
