### ISSUE TITLE
Tga convert to jpeg upside down

### ISSUE THREAD

**Issue by markiservera** [dlemstra/Magick.NET#535]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
-  [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

converting TGA to JPG results to upside down image when using .AutoOrient()

sample C# code

			using (MagickImage image = new MagickImage("[tga file path]"))
			{
				// Save as jpg
				image.AutoOrient();
				image.Write("testjpg.jpg");
			}

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Can you share an image that I can use to reproduce this issue?

**Comment by markiservera** [comment]
[football_seal.zip](https://github.com/dlemstra/Magick.NET/files/3844525/football_seal.zip)

**Comment by dlemstra** [comment]
This looks similar to this issue: https://github.com/ImageMagick/ImageMagick/issues/1406. Going to need to take another look at this in the future.

**Comment by dlemstra** [comment]
We just pushed a patch to the ImageMagick repository to fix this. This will be resolved in the next release.
