### ISSUE TITLE
watermarked PSD files has reddish image

### ISSUE THREAD

**Issue by markiservera** [dlemstra/Magick.NET#536]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

watermarking a PSD file results to a reddish image (doesnt happen on 7.14.2)
![image](https://user-images.githubusercontent.com/57522620/68828803-e81f6000-06e1-11ea-9eb8-373a1df5036e.png)

### Steps to Reproduce

used this C# code 
```
using (MagickImage image = new MagickImage("Lab16.psd"))
  {

    using (MagickImage watermark = new MagickImage("Watermark Grayscale.jpg"))
			{
				Gravity watermarkPosition = (Gravity)((int)5);
				image.Composite(watermark, watermarkPosition, CompositeOperator.Over);
				image.Write("ProcessedImage.psd");
			}
}
```
attached files
[test files.zip](https://github.com/dlemstra/Magick.NET/files/3844709/test.files.zip)

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Which version of Magick.NET did you use to test this and on what operating system?

**Comment by markiservera** [comment]
Magick.NET  = 7.14.2
OS = Windows 10

**Comment by dlemstra** [comment]
This issue is happening because your input image is in the `CIELab` colorspace. Previous versions of ImageMagick would change the colorspace automatically but in recent versions you will need to change the colorspace yourself. With `image.ColorSpace = ColorSpace.sRGB;` you will probably get the expected result.
