### ISSUE TITLE
How to use custom .ttf font on windows?

### ISSUE THREAD

**Issue by Calx-Takeno** [dlemstra/Magick.NET#537]
Version: Magick.NET-Q8-AnyCPU 7.14.5
Platform: windows 10/windows server 2016

I found MagickNET.FontFamilies property. It contains all fonts that allow to use.
I have installed this .ttf font to Window/Fonts folder. But I haven't found it in MagickNET.FontFamilies. 
Sholud I register this font to MagickNET.FontFamilies? But this property is readonly.
Could you give me some example codes about how to use custom .ttf font?
Could I install fonts when application initilization? Or dynamic load font file when running.

**Comment by dlemstra** [comment]
It might be possible that Windows needs a reboot before the font is available. Another reason could be the way that it was installed. But instead of installing the font you can also use the full path to the font as the font.

**Comment by Calx-Takeno** [comment]
Thank you.
It works now.
I closed this question.

maybe below code can help someone who look for using custom font.

var textReadSettings = new MagickReadSettings()
{
        Font = "fonts/custom.ttf",   //font path
        FontFamily = "Orbitron", 
};

**Comment by dlemstra** [comment]
Thanks for responding with how you got this resolved.
