### ISSUE TITLE
Convert Svg to Wmf

### ISSUE THREAD

**Issue by desfarik** [dlemstra/Magick.NET#539]
### Question

I want to convert svg image to wmf

```
            using (MagickImage image = new MagickImage(svgFilePath, MagickFormat.Svg))
            {
                image.Format = MagickFormat.Wmf;
                File.WriteAllBytes(wmfTempPath, image.ToByteArray());
            }
```
I have error like
`{"no encode delegate for this image format `WMF' @ error/constitute.c/WriteImage/1216"}`

After searching, i find that i need use libwmf, in command line like this --with-libwmf.

How can i configure using libwmf?

**Comment by dlemstra** [comment]
There is no support for creating `WMF` images in the ImageMagick library. I don't know which library you could use to do this but you cannot do it with this library.
