### ISSUE TITLE
PDF File size

### ISSUE THREAD

**Issue by shakazulu89** [dlemstra/Magick.NET#54]
Hello
I need to convert PDF to jpg or png then convert it back to PDF.
I am using the examples from the documentation. nothing fancy.
But i find that the resulting pdf size is 3 times bigger than the original. I notice that the page containing in the orig PDF gets converted with the largest size. Maybe here i need to find a way to optimize it better?
What will be the best way to keep the PDF size as the original?
Thanks!
Roy

**Comment by dlemstra** [comment]
I think you probably want to use another tool for this if you want to decrease the file size. Your input file probably contains text. When you use Magick.NET to convert the file it will convert the text into an image and that will make the size of the file a lot bigger. I don't know which tool you could use for this though.

**Comment by shakazulu89** [comment]
thanks @dlemstra .. appreciate it .. ill keep looking.
if anybody can recommend a library id be grateful ;)
