### ISSUE TITLE
Saving as PNG in MagickImage is creating a Grayscale image, even though Autograyscale is off

### ISSUE THREAD

**Issue by Cloudmersive** [dlemstra/Magick.NET#541]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Have some very simple code that takes in an image, draws it onto a blank, white image, and then saves it as output.  Unfortunately, the output for images with no colors inside is getting saved as a Grayscale PNG, not an RGB PNG.  While this may seem like a nice optimization, other software does NOT support Grayscale PNG.

```C#
using (MemoryStream ms = new MemoryStream(fileData))
{
   using (var img = new MagickImage(ms))
   using (var outputImg = new MagickImage(MagickColor.FromRgb(255, 255, 255), img.Width, img.Height))
   {
       img.TransformColorSpace(ColorProfile.SRGB);
       outputImg.TransformColorSpace(ColorProfile.SRGB);
       outputImg.ColorSpace = ColorSpace.RGB;
       outputImg.FloodFill(MagickColor.FromRgb(255, 255, 255), new PointD(0, 0));

       outputImg.Format = img.Format;
       outputImg.Composite(img, CompositeOperator.SrcOver);

       outputImg.TransformColorSpace(ColorProfile.SRGB);
       outputImg.ColorSpace = ColorSpace.RGB;

       outputImg.Settings.ColorSpace = ColorSpace.RGB;
       outputImg.Settings.ColorType = ColorType.TrueColor;
       outputImg.Settings.SetDefine("colorspace:auto-grayscale", "false");
       outputImg.SetAttribute("colorspace:auto-grayscale", "false");

       using (MemoryStream os = new MemoryStream())
       {
           outputImg.Write(os);
```
### Steps to Reproduce
See above.

I have tried all possible settings to force it to RGB and it just won't do ti.

- Magick.NET version: Magick.NET Q16 AnyCPU 7.14.5
- Environment (Operating system, version and so on): Windows 10

It would be nice if the optimization of auto saving as Grayscale did not exist or was off by default as it causes huge problems and is not easy to control

**Comment by dlemstra** [comment]
What happens when you replace setting all those `.Settings` and call `outputImg.PreserveColorType()` instead?
