### ISSUE TITLE
Density 0x0, no XMPProfile, Windows has 96x96 density

### ISSUE THREAD

**Issue by M4nju** [dlemstra/Magick.NET#544]
Hello,

i am using the newest Magick.Net Version Q8 AnyCpu (7.14.5). For me it is important to retain the density of the images i process. For that, i am using the Density Property from the MagickImage. 

My problem now is, that some images have a density of 0x0. But inside the windows Properties of the images i can see a resolution of 96x96.

I tried getting XMPProfile and ExifProfile but it just returns null (As explained in the issue https://github.com/dlemstra/Magick.NET/issues/87).

In the ImageMagick command line tool, they use the command "format" instead of "density" to get the resolution. Could this be the solution to the Problem? (Source: https://www.imagemagick.org/discourse-server/viewtopic.php?t=16110)

If I could use the "format" command with additional parameters just the way the source above shows, it maybe will give me more information? (Could not figure out how to do this witch Magick.Net :S ).

Test file:
![2013_Chevrolet_Camaro_ZL1_muscle_cars_sportcar_2560x1440](https://user-images.githubusercontent.com/38355359/70065942-24145980-15ec-11ea-9736-b03beb0f07b6.jpg)

Test source code:

 using (MagickImage image = new MagickImage(filePath))
            {
                var density = image.Density;
                var xmpProfile = image.GetXmpProfile();
                var exifProfil = image.GetExifProfile();
            }

Thanks for any kind of feedback.

Greetings,
David (Manju)

**Comment by dlemstra** [comment]
96 is a default resolution asigned to untaged images on windows. Your image has no density and that is why you cannot find it in the profile or the Density property.

**Comment by M4nju** [comment]
oh well.. guess so i have to create my own default. Thanks for the fast Help :D
