### ISSUE TITLE
Why does write image to stream creates bigger image size ?

### ISSUE THREAD

**Issue by aleksandarveljanov** [dlemstra/Magick.NET#545]
- Magick.NET version: Magick.NET-Q16-AnyCPU.7.0.6.102
- Environment: Visual Studio 2019, Windows 10, 1903

I am having an issuie when trying to write the image to stream/file. I'm doing a lossless compression on my stream, though it produces more bytes for some reason. Here is the code with comments on what is happening (also two images provided in attachment for the issuie):

```C#
MagickReadSettings settings = new MagickReadSettings();
settings.SetDefine("filter:support", "2");
settings.SetDefine("jpeg:fancy-upsampling", "off");
settings.SetDefine("png:compression-filter", $"5");
settings.SetDefine("png:compression-level", $"9");
settings.SetDefine("png:compression-strategy", $"2");
settings.SetDefine("png:exclude-chunk", "all");
settings.Format = MagickFormat.Png;
settings.CompressionMethod = CompressionMethod.LosslessJPEG;
IWriteDefines defines = new JpegWriteDefines { };**


using (MemoryStream memStream = new MemoryStream())
{
    // the image send here (png image stream) is reduced to 5.04 mb
    using (MagickImage magickImage = new MagickImage(image, settings))
    {
        // and here when i want to save to a stream it goes to 7.31 MB ??? 
        // Is there any other way to extract the stream from the MagickImage object apart from 
        //.Write() ?

        magickImage.Write(memStream, defines);
    }
}
```

Also I can see that in the .Write(Stream, IWriteDefines) in the second param for passing there is an interface in which you can send some object with additional param. depending on the output of the image you want to send. Though I cannot find anything related to .png image. I would highly appreciate any help with this since it's stalling our production environment.

Thanks a lot.

![after_Write](https://user-images.githubusercontent.com/9049196/70702177-f60ad580-1ccd-11ea-978e-c3e6e2064277.png)
![before_Write](https://user-images.githubusercontent.com/9049196/70702178-f6a36c00-1ccd-11ea-94f7-d49a0c1e12d9.png)

**Comment by dlemstra** [comment]
You should upgrade to a more recent version. It no longer displays that value because it is incorrect and can be confusing. If you want to optimize an image you might want to take a look at the `ImageOptimizer` class. It can help you with that. And I don't think that you are doing a lossless compression because you set `settings.SetDefine("png:exclude-chunk", "all");`. This means that not all chunks are written to the file. So maybe in your case `Compress` will work but otherwise you could give `LosslessCompress` a try.
