### ISSUE TITLE
Move support for Bitmap from Framework to Core

### ISSUE THREAD

**Issue by howff** [dlemstra/Magick.NET#547]
I can see MagickImage constructors and methods which deal with Bitmap objects (convert MagickImage to/from Bitmap) but they are in Magick's Framework directory and I am using Core on linux. Is it possible to move them into Core? (Sorry if this is a stupid question, I am new to .net!)

**Comment by dlemstra** [comment]
You cannot use them on Linux because they are not available on that platform. And that is why those files are not in the Shared/Core folder.

**Comment by howff** [comment]
Oh, although if I copy and paste the code from Framework/MagickImage.cs into my code then it seems to work :-)

**Comment by howff** [comment]
Oh, although if I copy and paste the code from Framework/MagickImage.cs into my code then it seems to work :-)

**Comment by dlemstra** [comment]
Which version of .NET Core are you using?

**Comment by howff** [comment]
.NET Core 2.2 with Microsoft's System.Drawing.Common package.

**Comment by dlemstra** [comment]
I will not add a dependency to the `System.Drawing.Common` package in the netstandard version. You can probably copy/paste the code from the folder you mentioned earlier and modify it to make it work for your situation.

**Comment by howff** [comment]
OK, thanks anyway.
