### ISSUE TITLE
ObjectDisposedException when accessing eps image

### ISSUE THREAD

**Issue by TioLuiso** [dlemstra/Magick.NET#548]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We have a code fragment in our codebase that reads an EPS image then tries to access some properties, like the Width and the Height

When it runs on linux, it explodes when trying to access the Width (but I guess it will explode trying to access just everything), with the following exception

`Cannot access a disposed object.
Object name: 'MagickImage'.`

`   at ImageMagick.NativeInstance.get_Instance()
   at ImageMagick.MagickImage.NativeMagickImage.get_Width()
   at ImageMagick.MagickImage.get_Width()
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\luis.desantiago\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 16`

### Steps to Reproduce
Have reduced the code needed to explode to the following sample:

```c#
using var stream = File.OpenRead("BLK.EPS");
using var image = new MagickImage();
MagickReadSettings settings = new MagickReadSettings();
settings.ColorSpace = ColorSpace.RGB;
image.Read(stream, settings);
Console.WriteLine($"Image is {image.Width} width and {image.Height} high");
```

When running on Windows, it works. When running on Linux, it exploded with the aforementioned exception. Have tried with various eps files. The one I have used in the sample is https://www.fileformat.info/format/eps/sample/282de7c75e4643239f3614304e745b16/download

### System Configuration

- Magick.NET version: 7.14.5
- Environment (Operating system, version and so on): Ubuntu 18.04 container running in Rancher 1.6
- Additional information:

**Comment by TioLuiso** [comment]
Ok, looks like the issue was because the container didn't have ghostscript, so it exploded. Maybe the exception could tell that

**Comment by dlemstra** [comment]
Thanks for reporting this. It appears ImageMagick returns null without raising an exception. I just added a patch for this to make sure an exception is raised instead.
