### ISSUE TITLE
Facial recognition/detection support

### ISSUE THREAD

**Issue by stanley-zenfolio** [dlemstra/Magick.NET#549]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):

### Question

How to use ImageMagicK or MagicK.Net to perform facial recognition/detection? Is it possible? If possible, any sample code?

**Comment by stanley-zenfolio** [comment]
Does ImageMagicK support content aware cropping?

**Comment by dlemstra** [comment]
ImageMagick has no facial recognition/detection. And there is no built in support for content aware cropping. There is a script for snart cropping made by Fred Weinhaus: http://www.fmwconcepts.com/imagemagick/smartcrop/index.php but I don't know how easy it will be to translate that. And this comes with a commercial fee.
