### ISSUE TITLE
Error Reading Stream as number rises to approx 200 image.Read(stream, settings);

### ISSUE THREAD

**Issue by kendallmark3** [dlemstra/Magick.NET#550]
```C#
public static Image Svg2Png(string s, int sizex = 100, int sizey = 100)
{
    //return null;
    byte[] bytes = Encoding.UTF8.GetBytes(s);
    MemoryStream stream = new MemoryStream(bytes);
    byte[] imgBytes;
    Bitmap image2;

    MagickReadSettings settings = new MagickReadSettings();
    settings.Density = new Density(500);
    settings.BackgroundColor = new MagickColor(ImageMagick.MagickColors.Transparent);
    //settings.Height = sizex;
    //settings.Width = sizey;
        
    using (MagickImage image = new MagickImage())
    {
        //fails here after about 200 calls
        image.Read(stream, settings);

        image.Format = MagickFormat.Png;
        //image.Resize(new Percentage(80));

        MagickGeometry mg = new MagickGeometry(sizex, sizey);
        //image.Resize(mg);
        image.Resize(sizex, sizey);
        image.Alpha(AlphaOption.Associate);

        imgBytes = image.ToByteArray();
        MemoryStream ms = new MemoryStream(imgBytes);
        ms.Seek(0, SeekOrigin.Begin);
        Bitmap bmp = new Bitmap(ms);
        image2 = (System.Drawing.Bitmap) bmp;
    }
    
    return image2;
}
```

**Comment by dlemstra** [comment]
It seems that you never dispose the `stream`? Have you checked if you are running out of memory? Is it possible to create a reproducible version of this issue? Where you do this in a loop with a certain string value.

p.s. I also got a similar email yesterday was that also send by you? There is no need to notify in both ways please just use the issues instead. I hardly every respond to those emails. In that email there was also a request for a licensed version but that is not available. If you want to support me you can sponsor me through GitHub: https://github.com/sponsors/dlemstra.

**Comment by kendallmark3** [comment]
Thank you for the quick response- and good catch we now close the stream after each call- but no difference as we ca see-

Ps the email you got was from my boss I will let him know your response 

We will continue to look for ways to corner this issue-

Mark

**Comment by dlemstra** [comment]
Do you have an update @kendallmark3?

**Comment by kendallmark3** [comment]
We did as you suggested and it did turn out to be a memory leak- after 5-6
exports our local machines were running out of memory when set up on the
monitors- we did some other things to optimize the overall API, but your
suggestion got us going the the right direction- Thank you

**Comment by dlemstra** [comment]
Happy to hear that you managed to resolved this issue. Please consider supporting me through GitHub sponsors.
