### ISSUE TITLE
PSD to Jpg   shows only alpha channel 

### ISSUE THREAD

**Issue by markiservera** [dlemstra/Magick.NET#551]
Hi,

  Im converting the attached PSD file [DE_Icon.zip](https://github.com/dlemstra/Magick.NET/files/3982890/DE_Icon.zip)  to jpg which results to a black image. I saw online that you need to set alphaunblend to false to remove the alpha channel but still wont work.

Im using this code in c#

```
var setting = new MagickReadSettings { Defines = new PsdReadDefines { AlphaUnblend = false } };

using (MagickImage image = new MagickImage("DE_Icon.psd", setting))
    {

         image.Write("output.jpg");
    }

```

**Comment by markiservera** [comment]
Also, the JPG will be used for preview and thumbnail, Just need to generate the correct image for previewing.

**Comment by dlemstra** [comment]
I suspect that you are usng a `Q8` version of Magick.NET and it appears that you found a bug. I just pushed a patch to the ImageMagick repository to fix this and you will no longer get a black image in the next release.

p.s. You won't need the settings because this image contains no alpha channel.
