### ISSUE TITLE
Blur only a specific rectangle

### ISSUE THREAD

**Issue by gizmo3845** [dlemstra/Magick.NET#552]
Hi,

I would like to achieve a blurring only in a specific rectangle of an image.
I don't know if using a region mask would be useful or if there is another way to do that.

Can someone help me ?

Thanks.

**Comment by dlemstra** [comment]
You could blur a specific part of the image with the following method:

```C#
using (var image = new MagickImage("logo:"))
{
    using (var mask = new MagickImage(MagickColors.White, image.Width, image.Height))
    {
        mask.Draw(new DrawableFillColor(MagickColors.Black), new DrawableRectangle(150, 50, 250, 100));

        image.SetWriteMask(mask);

        image.Blur(0, 5);

        image.Write("output.png");
    }
}
```

**Comment by gizmo3845** [comment]
Is it normal that Blur is very slow ( more than 10s for a 1920x2560 pixels image ) ?

Thanks.

**Comment by dlemstra** [comment]
Blur is not a fast process but how big is the area that you are blurring? Can you share an image and the code that you are using?
