### ISSUE TITLE
System.AccessViolationException in Resize() in Magick.NET-Q8-AnyCPU.7.14.5

### ISSUE THREAD

**Issue by b9chris** [dlemstra/Magick.NET#553]
I upgraded from Magick.NET 7.14.4 to 7.14.5.

All Resize() operations now fail with System.AccessViolationException.

Perhaps the move to the beta version of ImageMagick didn't go so well?

This occurs on both a Win10 64-bit v1909 Intel Surface Book dev machine and a Win Server 2016 Datacenter v1607 so I don't think the machine has anything to do with it, I think 7.14.5 is simply broken.

**Comment by dlemstra** [comment]
This could be an `OpenCL` issue but it is a bit odd that this also happens on the `Win Server 2016`. And the unit tests of this project do 10+ different resize operations that all passed my local machine and the build server in Azure. Have you tried running the code inside a docker container to see what happens there?

**Comment by aqibshabbir** [comment]
Upgrading to Magick.Net 7.15.0 latest solved this issue.
