### ISSUE TITLE
First use slow

### ISSUE THREAD

**Issue by gizmo3845** [dlemstra/Magick.NET#554]
Hi,

I'm using v7.14.5 Q8 AnyCPU, and When I first use a function it's very slow.
Example:
```
imageMagick = new MagickImage(imagePath);
imageMagick.Grayscale(); // takes 3.4s to execute
imgeMagick.Dispose(); 
imageMagick = new MagickImage(imagePath);
imageMagick.Grayscale(); // takes 80ms to execute
```

So the first Grayscale call takes a lot of time.
I've read that ImageMagick is doing some initialization that can cause that but is there a way to initialize prior to the first algorithm call ? Or, to use a cache that prevent that ?

Thanks for your help.

**Comment by dlemstra** [comment]
This should only happen the very first time that you execute that method. At that point an OpenCL benchmark wil run to determine if the `CPU` or the `GPU` should be used. The only option to prevent this would be to disable OpenCL accelerated method. But that should not be an issue if you don't run your code on a machine that has a very good video card.
