### ISSUE TITLE
ExifTag is complicated with 7.15.0

### ISSUE THREAD

**Issue by catester** [dlemstra/Magick.NET#557]
ExifTag was an enum in previous versions, now it's a class and you have to use static properties of ExifTag to specify tags. I think this is not good, enums are powerful and they are useful for serialization or storage on other systems. The ushort value for tags are well-known, I think it's better to allow access with these numbers.

For example, with `ExifProfile.GetValue<TValueType>(ExifTag<TValueType> tag)` we need to know TValueType of tag (so has to use predefined ExitTag.StaticProperty), but I could only know the tag ID (an integer).

ExifTag does not expose the underlying ushort value either (only ToString method which gets the string name in the internal enum ExifTagValue).

So what I suggest is renaming these types:
```
ExifTag -> ExifTagDefinition
ExifTag<TValueType> -> ExifTagDefinition<TValueType>
ExifTagValue -> ExifTag (and make this enum public)
```

And allow ExifTag enum to be used in places like  `ExifProfile.GetValue<TValueType>(ExifTag<TValueType> tag)`

**Comment by catester** [comment]
Well, I noticed I could do `(ushort)ExifTag` for getting  the underlying ushort value but still not vice versa:  `ExifTag(ushort value)` constructor is internal and no explicit operator.

**Comment by dlemstra** [comment]
These changes have been made to get better type safety when reading and writing exif values. And you don't need to know the `TValueType` because that is already know by the value of `ExifTag.StaticProperty`.  I am not going to make the changes that you suggested.

If you really want to use the ushort value (I don't understand why) you will need to create your own `GetValue` method:

```C#
public static object GetValue<TValueType>(ExifProfile profile, ushort value)
{
    switch (value)
    {
        case 0x828F:
            return profile.GetValue(ExifTag.BatteryLevel)?.GetValue();
        default:
            return null;
    }
}
```

Or you could do something like this instead:

```C#
public static void StoreValues(ExifProfile profile)
{
    foreach (var value in profile.Values)
    {
        var ushortTag = (ushort)value.Tag;
        if (ShouldStore(ushortTag)) {
            StoreValue(ushortTag, value.GetValue());
        }
    }
}
```

p.s. Starting your conversation with calling something a mess is not a very nice way to start a conversion.

**Comment by catester** [comment]
Sorry I called it a mess because it's a breaking change for me. Yes I see, I could do workarounds like huge switch statements. But for example IptcTag is still an enum and ExifTag is now a class, this sounds inconsistent.

> If you really want to use the ushort value (I don't understand why) 

Imagine you have a UI in which user updates Exif properties. So when the user saves, you need to write a huge switch statement to get an instance of a typed `ExifTag<TValueType>` from a serialized value in the UI.

Nevermind I will solve it by using reflection.

**Comment by dlemstra** [comment]
If you only need to update the value you don't need reflection. You could do something like this:

```
profile.Values.Where(value => (ushort)value.Tag == tag).First().SetValue(value);
```

And thanks for explaining your use case better. The example above works for when you need to update a value. Do you also need to add values? It might be possible to add `SetValue(ushort tag, object value)` to the `ExifProfile` class to make this possible. And how do you make sure that the user enters a value with the correct type in your UI?

**Comment by dlemstra** [comment]
Would you mind answering my questions @catester?

**Comment by catester** [comment]
> And how do you make sure that the user enters a value with the correct type in your UI?

Yes I understand, having typed ExifTag would be required in this case. So I guess I should adopt the new feature :) Thanks for the help.
