### ISSUE TITLE
Failed to convert an EPS file in Windows 10 with the username has umlaut

### ISSUE THREAD

**Issue by deepakkjose** [dlemstra/Magick.NET#558]
### Prerequisites

- Failed to convert an EPS file from a Windows machine (User name: TestMüller)

### Description
I have tried to convert the below (.EPS) file.
https://drive.google.com/file/d/15XAMS47w6z6hPJgqtjFrWhCSGsXF9dH5/view?usp=sharing.
then the following exception occurs

FailedToExecuteCommand `"C:/Program Files (x86)/gs/gs9.50/bin/gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pamcmyk32" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72" -g548x396 -dFirstPage=1 -dLastPage=1 -dEPSCrop  "-sOutputFile=C:/Users/Testmüller/AppData/Local/Temp/magick-33180gkIG7ZRqMHEn%d" "-fC:/Users/Testmüller/AppData/Local/Temp/magick-33180JABRbXTuDykN" "-fC:/Users/Testmüller/AppData/Local/Temp/magick-33180scwmQF3sLUAC" -c showpage' (1) @ error/ps.c/InvokePostscriptDelegate/225

### System Configuration
OS: Windows 10 (Windows user name: TestMüller)
Version: ImageMagick 6.9.3-2 Q8 x86
Ghost script version: 9.50

**Comment by dlemstra** [comment]
Are you using ImageMagick or Magick.NET?

**Comment by deepakkjose** [comment]
We are using Magick.Net. 6.9.3
Below code is throwing the exception on EPS file input.
Note: This is happened only in Windows user with the username having umlaut charater (Müller)

           var stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read)
           try
            {
                stream.Seek(0, SeekOrigin.Begin);
                result = new MagickImage(stream, _magickReadSettings);
            }
            catch (MagickErrorException ex)
            {               
            }

**Comment by dlemstra** [comment]
That version of Magick.NET is ancient. What happens when you upgrade to the latest version?

**Comment by deepakkjose** [comment]
@dlemstra Thanks for your response. The issue is reproduced with Magick.NET-Q8, Version=7.15.0.0.

_(*The earlier version was 7.12, not 6.9.3_, please excuse my mistake)

**Comment by dlemstra** [comment]
The problem here is that Magick.NET/ImageMagick has no problem reading or writing a file that contains an umlaut but that the Ghostscript library cannot read from that path. I would advise you to call `MagickNET.SetTempDirectory` with a path that does not an umlaut to prevent this from happening.

**Comment by deepakkjose** [comment]
@dlemstra Its works for us as you suggested.
We would like to raise a query regarding this to GhostScript (via https://bugs.ghostscript.com/).
Can you give a hint regarding Ghostscript command which causes the error?

**Comment by dlemstra** [comment]
I don't know what is causing this or what should be done to fix this.
