### ISSUE TITLE
How to get Magick.NET working within a Linux Docker container

### ISSUE THREAD

**Issue by ozziepeeps** [dlemstra/Magick.NET#561]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
I have a .NET Core 2.1 project that runs fine on Windows, but when I try to run it in Docker (with a Linux container) I get an exception:

DllNotFoundException: Unable to load shared library 'Magick.Native-Q16-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library libMagick.Native-Q16-x64.dll: No such file or directory
ImageMagick.Environment+NativeMethods+X64.Environment_Initialize()
ImageMagick.Environment+NativeEnvironment.Initialize()
ImageMagick.Environment.Initialize()
ImageMagick.MagickSettings+NativeMagickSettings..cctor()

- Magick.NET version: 7.15.0
- Environment (Operating system, version and so on): Docker

### Question
I've done some Googling and have found others reporting this problem, but haven't found any clear satisfactory answers that have helped me. I also read https://github.com/dlemstra/Magick.NET/blob/master/docs/CrossPlatform.md and followed the instructions above renaming the native library and prefixing "lib" to no avail.

I'm looking for some help in how to resolve the issue and am happy to provide anything else that may be useful.

What's interesting my use case is I have similar C# code using the same version of Magick.NET working fine in a AWS Lambda function, which is a similar Linux environment. I didn't need to do anything out of the ordinary to make that work correctly, which is why this failing use case is particularly strange.

Thanks in advance for your great library, community and help.

**Comment by ozziepeeps** [comment]
FYI I'm using `--runtime linux-musl-x64` when running `dotnet publish` so that the correct Linux binaries are present in my output folder (in my Docker container). Running an `ls` in my container shows `Magick.NET-Q16-AnyCPU.dll` and `Magick.Native-Q16-x64.dll.so` present.

**Comment by dlemstra** [comment]
What is your docker base image? Are you using an alpine image? These are not compatible with the native library.

**Comment by ozziepeeps** [comment]
Yes, it's an alpine image. Is there a document somewhere of what it is compatible with so I can explore other options?

**Comment by ozziepeeps** [comment]
Ok @dlemstra I was able to get things working in a container using stretch-slim (Debian) as a base image instead of alpine. Re-reading your CrossPlatform.md I see now that you mention issues with Alpine, however I guess I never joined the dots that that would manifest as a DllNotFoundException! This is likely me being a bit of a newcomer to the Docker space, but if there's anything you think we could add to the docs to help the community (or me!) in the future then let me know your thoughts.

I appreciate you taking the time to help.

**Comment by dlemstra** [comment]
This is not because you are new in the docker space but because the library just doesn't work with the alpine image. If you would have searched for `DllNotFoundException` in the closed issues your first hit would a similar issue. But I am really happy that you at least took the time to go through the `CrossPlatform.md` file. Would you be willing to help me with a PR to make this problem more clear there?

**Comment by ozziepeeps** [comment]
Sure I'd be happy to help. Let me send you a PR.
