### ISSUE TITLE
+antialias console command has no translation to .NET library?

### ISSUE THREAD

**Issue by zdickinson** [dlemstra/Magick.NET#564]
@dlemstra  

Hello! I'm attempting to translate the following console command to the .net library syntax 👍 
"+antialias input.ai output.tiff", but there doesn't appear to be a direct translation. Really I'm just trying to disable anti-aliasing when converting. Is this something you can help with? The below is what I'm trying:

            var readSettings = new MagickReadSettings {StrokeAntiAlias = false, TextAntiAlias = false};

            using (var image = new MagickImage(inputPath, readSettings))
            {
                image.Settings.StrokeAntiAlias = false;
                image.Settings.TextAntiAlias = false;
                image.Format = MagickFormat.Tiff;
                image.Write(outputPath);
            }

I've attached all my relevant files. 
[MagickNetTest.zip](https://github.com/dlemstra/Magick.NET/files/4109149/MagickNetTest.zip)

Thank you in advance for any feedback!

**Comment by dlemstra** [comment]
It appears that this setting is not available in the Magick.NET library yet. This will be added in the next release. In the next release you will need to set the `AntiAlias` to `false` in the `MagickReadSettings`. You don't need to set the strok and text antialias. And you will only need to set it before you read the image, not afterwards.

**Comment by zdickinson** [comment]
Awesome. Thanks for the quick response. Looking forward to it!

**Comment by dlemstra** [comment]
The new release has just been published. Please consider supporting me through GitHub sponsors.
