### ISSUE TITLE
Cannot find/load the native library from a different directory

### ISSUE THREAD

**Issue by xaviert0** [dlemstra/Magick.NET#565]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:  7.14.1.0
- Environment (Operating system, version and so on):
windows 10 dev
windows server 2016 prod 

### Question

I have an asp.net webforms project that uses magick.net .. eveything works fine with the native library within the bin directory

I am trying to have the native library on a different directory
I use the  ImageMagick.MagickNET.SetNativeLibraryDirectory call at application start to point to a different directory where the library has been placed, made sure all the permisions have been granted but the native library does not load

Unable to load DLL 'Magick.Native-Q8-x64.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) INNER TRACE: 
   at ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   at ImageMagick.Environment.Initialize()
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection..cctor()

are there any additional steps that need to be taken besides setting the directory?
is there a different "moment" (vs application start) to set it?

**Comment by dlemstra** [comment]
Is it possible to create a small sample application that demonstrates this issue? You need to make sure that you set the directory before you execute an Magick.NET code.

**Comment by jlankitus** [comment]
Hello! I get a very similar issue on Mac OS. I'll stay in touch to help figure out the problem
