### ISSUE TITLE
New update - Linux - System.EntryPointNotFoundException

### ISSUE THREAD

**Issue by justlearntutors** [dlemstra/Magick.NET#566]
System.EntryPointNotFoundException: Unable to find an entry point named 'MagickSettings_AntiAlias_Get' in shared library 'Magick.Native-Q16-x64.dll'. at ImageMagick.MagickSettings.NativeMethods.X64.MagickSettings_AntiAlias_Get(IntPtr instance) at ImageMagick.MagickSettings.NativeMagickSettings.get_AntiAlias() at ImageMagick.MagickSettings..ctor() at ImageMagick.MagickImage..ctor() at Justlearn.Controllers.AccountController.AccountUploadImage(String file, String signup) in C:\Justlearn\Justlearn\Controllers\AccountController.cs:line 10525

**Comment by dlemstra** [comment]
Next time please answer the questions in the template? I suspect that you are using an old version of the native library with the latest release.

**Comment by justlearntutors** [comment]
I have updated to the newest version.

**Comment by dlemstra** [comment]
What is the file version of the `Magick.Native-Q16-x64.dll`? I suspect that your `bin` folder contains an older version of that library. It should be `7.0.9.19`.

**Comment by justlearntutors** [comment]
I downloaded Magick from Nuget. The version is 7.15.1. The error is only on Linux server.

**Comment by justlearntutors** [comment]
Magick.NET-Q16-AnyCPU

**Comment by dlemstra** [comment]
As I said before I suspect that you are using an older version of the native library in your application. I have no idea what kind of setup you have so I have no idea how you ended up in this situation.

**Comment by justlearntutors** [comment]
15.0 is working fine. Only 15.1 contains the error.

**Comment by dlemstra** [comment]
The `MagickSettings_AntiAlias_Get` method was introduced in version 7.15.1. I suspect that you have an older version of `Magick.Native-Q16-x64.dll.so` on your Linux machine.

**Comment by justlearntutors** [comment]
How to update on Linux machine?

**Comment by dlemstra** [comment]
The library is part of Magick.NET but I suspect you have an issue with deploying it on your Linux machine. I have no idea how you do that but you should prob take a look in that part.

**Comment by dtechfish** [comment]
Did you ever find the cause of this error?  I'm getting the same after an NuGet upgrade.  I'm running on IIS Windows 2016

Unable to find an entry point named 'MagickSettings_AntiAlias_Get' in DLL 'Magick.Native-Q16-x64.dll'
--
