### ISSUE TITLE
long duration of rotation

### ISSUE THREAD

**Issue by Lemmes** [dlemstra/Magick.NET#567]
- Magick.NET-Q8-AnyCPU 7.15.1.0 
- Windows 10 Pro
- Intel i7-8700 @ 3.2GHz
- 40 GB RAM
- Samsung SSD 860 Pro 1TB

I'm rotating a few pretty large tif images (24 bit 10000*10000 pixels). This is the code I'm using.
``` csharp
        private void RotatePicture(string bild)
        {
            var readSettings = new MagickReadSettings();
            readSettings.BackgroundColor = MagickColors.Transparent;

            using (var image = new MagickImage(bild, readSettings))
            {
                image.Rotate(-_drehwinkel / Math.PI * 180);
                image.RePage();

                image.Write(Path.Combine(_zielVerzeichnisDrehung, Path.GetFileName(bild)));
            }
        }
```
Each picture takes pretty exactly 34 seconds to rotate around some odd degrees (81.something).
When I use gm.exe (I hope it is ok to mention this here...) each rotation takes about 2.5 seconds.
Is it expected to take so much longer (factor 14)?

... and thanks for providing the library :-)

**Comment by dlemstra** [comment]
What happens when you use `magick.exe` on the command line? Do you have a test image somewhere that we could use to test this with? Maybe you are using the x86 version of Magick.NET and then running into memory limits?

**Comment by Lemmes** [comment]
With `magick.exe` it takes on average 7.5 seconds per picture. I just double checked the architecture and found that my application was indeed built as x86 (prefer 32 bit - I don't know why Microsoft made that the default). So I rebuilt it as a 64 bit console app, reran the code and it finished at 27 seconds per image - better than before, but still around 3 times slower than with the cli.
I'd like to provide you a sample image but even as a zip archive it's still 181 MB large.

**Comment by Lemmes** [comment]
You can download the file here during the next five days:
https://my.hidrive.com/lnk/CCBJD5I5

Thanks!

**Comment by dlemstra** [comment]
If you are creating a console/windows application you could also switch to the `OpenMP` version that uses multiple cores.

**Comment by Lemmes** [comment]
Amazing - now we're more or less on par with `magick.exe` - 8 seconds per rotation. Does `magick.exe` use OpenMP? Oh - I see it does.
```
C:\Users\Bernd.COS>magick -version
Version: ImageMagick 7.0.9-20 Q8 x64 2020-01-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2018 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Visual C++: 180040629
Features: Cipher DPC Modules OpenCL OpenMP(2.0)
Delegates (built-in): bzlib cairo flif freetype gslib heic jng jp2 jpeg lcms lqr lzma openexr pangocairo png ps raw rsvg tiff webp xml zlib
``` 
I guess that means you can close the "issue".
Thanks again for your quick support!

**Comment by dlemstra** [comment]
Happy to hear that this got resolved. Please consider supporting me through GitHub sponsors.
