### ISSUE TITLE
Image cropping to transparent circle in c# (convert imagemagick command to c#)

### ISSUE THREAD

**Issue by dazusu** [dlemstra/Magick.NET#57]
Hi, I've done a fair bit of searching, but can't figure out how to convert the following ImageMagick command to C#, help would be much appreciated! (Essentially trying to take a portrait/head shot image, and crop it so it's a circle with transparent border, image to be cropped is usually 400x400 jpg or png)

` convert thumbnail.gif -alpha set \
    \( +clone -distort DePolar 0 \
       -virtual-pixel HorizontalTile -background None -distort Polar 0 \) \
    -compose Dst_In -composite -trim +repage circle_masked.png`

**Comment by dlemstra** [comment]
Your command would translate to this:

```C#
// convert thumbnail.gif
using (MagickImage image = new MagickImage(@"thumbnail.gif"))
{
    // - alpha set
    image.Alpha(AlphaOption.Set);

    // +clone
    using (IMagickImage clone = image.Clone())
    {
        // -distort DePolar 0
        clone.Distort(DistortMethod.DePolar, 0);

        // -virtual-pixel HorizontalTile
        clone.VirtualPixelMethod = VirtualPixelMethod.HorizontalTile;

        // -background None
        clone.BackgroundColor = MagickColors.None;

        // -distort Polar 0
        clone.Distort(DistortMethod.Polar, 0);

        // -compose Dst_In -composite
        image.Composite(clone, CompositeOperator.DstIn);

        // -trime
        image.Trim();

        // +repage
        image.RePage();

        // circle_masked.png
        image.Write("circle_masked.png");
    }
}
```

**Comment by dlemstra** [comment]
Can we close this issue @dazusu?

**Comment by dazusu** [comment]
Yes, thank you very much @dlemstra !
