### ISSUE TITLE
DllNotFoundException: Magick.Native-Q16-x64.dll

### ISSUE THREAD

**Issue by jlankitus** [dlemstra/Magick.NET#570]
### Description

I'm using Magick.Net in Unity 2019.3
This works will in Unity 2019.1.x but with the upgrade I continually get this error, 'DllNotFoundException: Magick.Native-Q16-x64.dll'

I've posted the issue to Unity forums but thought maybe someone here might know the issue, it seems to be with .dylib / .bundle files, or a .net version related change between editor versions?

### Steps to Reproduce

https://github.com/jlankitus/ImageMagickTest

The readme displays branch info on how to view the issue. Essentially the master branch works in 2019.1.x but when you upgrade to the latest Unity the .dll error occurs.

### System Configuration

macOS Catalina 10.15.2
Latest ImageMagick.Net
Unity 2019.3 (also happens in 2019.2)

**Comment by dlemstra** [comment]
This looks like a Unity issue to me. I have no idea how I can assist you with this.

**Comment by PalashBansal96** [comment]
For anyone coming here, this issue can be solved in Unity 2019.3.10 by renaming the osx native file from nuget to `Magick.Native-Q16-x64.bundle` from `Magick.Native-Q16-x64.dll.dylib`

**Comment by jlankitus** [comment]
yes can't wait to try, thank you so much!

**Comment by jlankitus** [comment]
It worked, Thank you so much :) :)
