### ISSUE TITLE
magickimage.Resize(Percentage) Takes a Long Time

### ISSUE THREAD

**Issue by mscirri** [dlemstra/Magick.NET#571]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When opening certain documents in our application, the call to MagickImage.Resize(Percentage) can take up to 100 seconds while with other documents it happens almost instantly.  I verified that there is no correlation between document size, document type, and the Percentage value passed in, as I consistently tested with JPEG document types and some documents that are larger take less time than the one that i have been testing with, regardless of the Percentage value. (There are multiple documents that seem to have this issue.)

### Steps to Reproduce

_magickReadSettings = new MagickReadSettings();
_magickReadSettings.Density = new Density(144, 144);
_magickReadSettings.ColorSpace = ColorSpace.CMYK;
_image = new MagickImage();
_image.Read(File.ReadAllBytes(LocalDocument.FullName), _magickReadSettings);
pictureBox.Image = _image.ToBitmap();
Percentage pct = (Percentage)(((double)pictureBox.Parent.ClientSize.Width / (double)_image.Width) * 100);
_image.Resize(pct);

For the documents that I have been testing with, the problem one is 2.37MB and the Percentage value end up being 16.16% .  ("Dr. 01-09-20_redacted.jpeg")  The other one ("SamplePNGImage_mb.jpeg")  is 3.41MB and the Percentage is 11.22%. That one resizes in less than 2 seconds.

### System Configuration
![Dr  01-09-20_redacted_full](https://user-images.githubusercontent.com/48359984/74287342-bb3a1380-4cf7-11ea-8c1d-5ec405523362.jpg)

![SamplePNGImage_mb](https://user-images.githubusercontent.com/48359984/74192245-22d25f00-4c23-11ea-8632-5571e2423b41.jpeg)

Winforms application written in C#.
Target Framework = .NET Framework 4.6.1

- Magick.NET version:   Magick.NET-Q16-HDRI-AnyCPU   
        Prod Version:  version="7.14.4" targetFramework="net461"     
        Also tested on:   7.15.1
- Environment:   App running on Windows Server 2016 and served via RDS.
- Additional information:

**Comment by roblizak** [comment]
Co-worker of the above author adding some details here...  

I put together a test application and used both the latest Q16 HDRI and Q16 non-HDRI version along with the last 6.X version.  Running on my machine, the images listed above all resized in 1-2 seconds.  Copying the test application to the RDS server resulted in the Q16 HDRI and Q16 non-HDRI 7.X version taking 7 seconds to resize the "Dr" image.  The 6.X version remained at around 2 seconds.  

As another test, I used the latest Q16 HDRI binary distribution and called out to the "magick" command line application from the C# program performing the resize that way and then loading the resulting image into the picture box in the C# program.  Time was 2 seconds.

It appears there is something weird going on with the .NET wrapper over the library with resizing under certain circumstances.  I gave a look at the source code but nothing seemed like it should cause this type of problem.

**Comment by dlemstra** [comment]
What is an RDS server? And it feels like the issue is related to the environment where you run this in.

**Comment by mscirri** [comment]
RDS = Remote Desktop Services

It is what we use to host the WinForms application.   The issue happens on that server, which is Windows 2016, on my Windows 10 laptop, and on my teammate's Windows 10 desktop.

**Comment by dlemstra** [comment]
It is possible that on your local machine you are using `OpenCl` acceleration. What happens when you set `OpenCL.IsEnabled` to `false`?
