### ISSUE TITLE
Hi , I have used the new DLL and getting the error "ImageMagick.Magick Resource Limit Error Exception: memory allocation failed" previously I was getting the error "System.AccessViolationException: 'Attempted to read or write protected memory.'"Could anyone help please

### ISSUE THREAD

**Issue by Kubsi009** [dlemstra/Magick.NET#572]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):

**Comment by dlemstra** [comment]
Please summarize your issue in the title instead of using that as the whole title. And please enter the requested information in your issue.

**Comment by dlemstra** [comment]
Please give it another try with version `7.15.3.0`.
