### ISSUE TITLE
Questions in converting ImageMagick commands to equivalent Magick.NET (Fuzzy C Threshold logic in C# .net core)

### ISSUE THREAD

**Issue by kart33k** [dlemstra/Magick.NET#573]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: 7.15.0
- Environment (Operating system, version and so on): Windows 10, VS 2019, .net core 2.2 console project

### Question
I am trying to Convert this Script
[http://www.fmwconcepts.com/imagemagick/fuzzythresh/index.php](url)

Image Comparison can be found here
[http://www.fmwconcepts.com/imagemagick/threshold_comparison/index.php](url)

FuzzyC -Means

There are some images that I am trying to convert from jpeg to BiLevel Tiff.
i am suing AutoThreshold OTSU and its working fine for most of the images but it fails for some images and the resulting images are mostly covered in black.

Then I found this script which used ImageMagick and the FuzzyC produced better results than AutoThreshold when converting to Black and white.

I tried to convert the code to C#  but there are some pieces which I am missing

I did not get how to use these lines from script
What does xc:"gray($mmean%) comapres to in C#
`convert $tmpA1 \( -size ${ww}x${hh} xc:"gray($mmean%)" \) \
		-compose difference -evaluate pow 2 $filter -negate $tmpD1`
`convert $tmpA1 \( -size ${ww}x${hh} xc:"gray($nmean%)" \) \
		-compose difference -evaluate pow 2 $filter -negate $tmpD1`
Any Guidance will be helpful.
I tried to find other articles but could not find "xc".

Code from the script from above URL
`while [ "$test" != "1" ]; do
	echo "Iteration $k"
	oldthresh=$thresh

	# get high mask and its mean
	convert $tmpA1 -threshold ${thresh}% $tmpM1
	getMean "$tmpM1"
	mmean=$mean
		
	# compute high membership as normalized inverse squared difference of each pixel from high mean
	# in this case we just use -compose difference -evalute pow 2 and negate it (so inverse squared distance scaled to Q)
	convert $tmpA1 \( -size ${ww}x${hh} xc:"gray($mmean%)" \) \
		-compose difference -evaluate pow 2 $filter -negate $tmpD1
		
	# apply multiply membership image by image as weighting and mask to get the resulting mean
	convert $tmpA1 $tmpD1 -compose multiply -composite \
		$tmpM1 -compose multiply -composite \
		$tmpH1
	getMean "$tmpH1"
	hmean=$mean
       #echo "mmean=$mmean; hmean=$hmean"
	# correct hmean using mmean
	hmean=`convert xc: -format "%[fx:(100*$hmean/$mmean)]" info:`

	# get low mean
	# low mean = 100% - high mean
	nmean=`convert xc: -format "%[fx:(100-$mmean)]" info:`	

	# compute low membership as normalized inverse squared difference of each pixel from high mean
	# in this case we just use -compose difference -evalute pow 2 and negate it (so inverse squared distance scaled to Q)
	convert $tmpA1 \( -size ${ww}x${hh} xc:"gray($nmean%)" \) \
		-compose difference -evaluate pow 2 $filter -negate $tmpD1

	# apply multiply membership image by image as weighting and mask to get the resulting mean
	# note: low mask is just the complement of the high mask, i.e. $tmpM1 -negate
	convert $tmpA1 $tmpD1 -compose multiply -composite \
		\( $tmpM1 -negate \) -compose multiply -composite \
		$tmpL1
	getMean "$tmpL1"
	lmean=$mean
##	echo "nmean=$nmean; lmean=$lmean"
	# correct lmean using nmean 
	lmean=`convert xc: -format "%[fx:(100*$lmean/$nmean)]" info:`

	# get new threshold
	thresh=`convert xc: -format "%[fx:($hmean+$lmean)/2]" info:`
	diff=`convert xc: -format "%[fx:abs($thresh-$oldthresh)]" info:`
##	test=`echo "$diff <= 0.000001" | bc`
	test=`convert xc: -format "%[fx:($diff<=0.01)?1:0]" info:`
	k=`expr $k + 1`
	echo "hmean=$hmean; lmean=$lmean; oldthresh=$oldthresh; thresh=$thresh; diff=$diff"
done`

c# code

`
using (MemoryStream memStream = new MemoryStream())
            {
                using (MagickImage image = new MagickImage(model.InputFileName))
                {
                    // 1) Convert to GrayScale
                    image.ColorSpace = ColorSpace.Gray;
                    
                    // 2) Get Image height and width

                    var imageHeight = image.Height;
                    var imageWidth = image.Width;

                    // 3) GetMinMax

                    var min = image.FormatExpression("%[min]");
                    var max = image.FormatExpression("%[max]");

                     min = image.FormatExpression($"%[fx:100*{min}/quantumrange]");
                     max = image.FormatExpression($"%[fx:100*{max}/quantumrange]");
                    // 4) GetMean()

                    var mean = image.FormatExpression("%[mean]");
                    mean = image.FormatExpression($"%[fx:100*{mean}/quantumrange]");

                    if (Math.Abs(radius) > .1)
                    {
                        image.FilterType = FilterType.Gaussian;
                    }

                    var threshold = Convert.ToDouble(image.FormatExpression($"%[fx:({min}+{max})/2]"));
                    double oldThreshold = 0;
                    double diff = Convert.ToDouble(image.FormatExpression($"%[fx:abs({threshold}-{oldThreshold})]"));

                    var test = diff == 0;
                    var count = 1;
                    while (!test)
                    {
                        Console.WriteLine($@"Iteration {count}");
                        oldThreshold = Convert.ToDouble(threshold);

                        // get high mask and its mean
                        image.Threshold(new Percentage(threshold));
                        
                        var imageM1 = image;
                        var mMean = GetMean(imageM1);
                        /*
                         * # compute high membership as normalized inverse squared difference of each pixel from high mean
	                       # in this case we just use -compose difference -evalute pow 2 and negate it (so inverse squared distance scaled to Q)
                         */
                        
                        //image.MeanShift(image.Width, image.Height, new Percentage(Convert.ToDouble(mMean)));
                        image.Compose = CompositeOperator.Difference;
                        image.Evaluate(Channels.Gray,EvaluateOperator.Pow,2);
                        image.Negate();
                        
                        var imageD1 = image;
                        // # apply multiply membership image by image as weighting and mask to get the resulting mean
                        image.Compose = CompositeOperator.Multiply;
                        image.Composite(imageD1);

                        
                        imageD1.Compose = CompositeOperator.Multiply;
                        imageD1.Composite(imageM1);

                        var imageH1 = imageD1;

                        var hMean = GetMean(imageH1);

                        hMean = image.FormatExpression($"%[fx:(100*{hMean}/{mMean})]");

                        var nMean = image.FormatExpression($"%[fx:(100-{mMean})]");

                        /*
                         * # compute low membership as normalized inverse squared difference of each pixel from high mean
	                       # in this case we just use -compose difference -evalute pow 2 and negate it (so inverse squared distance scaled to Q)
                         */
                        //image.MeanShift(image.Width,image.Height,new Percentage(Convert.ToDouble(nMean)));
                        image.Compose = CompositeOperator.Difference;
                        image.Evaluate(Channels.Gray, EvaluateOperator.Pow, 2);
                        image.Negate();
                        imageD1 = image;
                        /*
                         # apply multiply membership image by image as weighting and mask to get the resulting mean
	                     # note: low mask is just the complement of the high mask, i.e. $tmpM1 -negate
                         */
                        image.Compose = CompositeOperator.Multiply;
                        image.Composite(imageD1);
                        imageM1.Negate();
                        imageM1.Compose = CompositeOperator.Multiply;
                        var imageL1 = imageM1;

                        var lMean = GetMean(imageL1);
                        lMean = imageL1.FormatExpression($"%[fx:(100*{lMean}/{nMean})]");

                        //Get new threshold
                        threshold = Convert.ToDouble(imageL1.FormatExpression($"%[fx:({hMean}+{lMean})/2]"));
                        diff = Convert.ToDouble(imageL1.FormatExpression($"%[fx:abs({threshold}-{oldThreshold})]"));
                        test = diff <= 0.01;
                        if (diff <= 0.01)
                        {
                            imageL1.Write(new FileInfo($"fuzzy.gif"));
                        }
                        count = count + 1;
                    }
                    
                }
            }
`

**Comment by dlemstra** [comment]
Did you see this:

```
Licensing:
Copyright © Fred Weinhaus

My scripts are available free of charge for non-commercial (non-profit) use, ONLY.

For use of my scripts in commercial (for-profit) environments or non-free applications, please contact me (Fred Weinhaus) for licensing arrangements. My email address is fmw at alink dot net.

If you: 1) redistribute, 2) incorporate any of these scripts into other free applications or 3) reprogram them in another scripting language, then you must contact me for permission, especially if the result might be used in a commercial or for-profit environment.
```

**Comment by kart33k** [comment]
Sorry for that, I missed the last part where converting to another
scripting language.
But I thought that both are image magick, it was using command line tools
in c# . I will just leave it here and not go further

Thanks
