### ISSUE TITLE
Converting JPEG to TGA 16 bits per pixel

### ISSUE THREAD

**Issue by deckertron9000** [dlemstra/Magick.NET#575]
### Description
I'm trying to convert a jpeg image to tga 16 bits per pixel (non-paletted) format. Running an imagemagick convert operation directly with `convert spongebob.jpeg -depth 5 spongebob_16bit.tga` gives a file with expected format. Trying to reproduce the same output with Magick.NET results in incorrect bit depth or garbled images.

### Steps to Reproduce

    using (var image = new MagickImage("spongebob.jpeg"))
    {
        image.Depth = 5;
        image.Write("spongebob_16bpp.tga");
    }

### System Configuration

- Environment: Windows 10
- Magick.NET version: Magick.NET-Q16-AnyCPU 7.15.1

**Comment by deckertron9000** [comment]
![spongebob](https://user-images.githubusercontent.com/10391684/74754851-df39af80-5237-11ea-9211-ff9ca587794c.jpeg)

**Comment by dlemstra** [comment]
It seems that you will need to set the `Depth` on the `Settings` property of the `image` for this to work. But the problem here is this is not yet possible to do. I will need to add this property and publish a new release for this.

**Comment by deckertron9000** [comment]
One more quick question, I can create another issue if this is actually a bug, but is there a way to adjust pixels per inch when converting to a tga file? I've tried setting image Density to 300 and calling Resample but the output does not match `convert spongebob.jpeg -resample 300 spongebob_300ppi.tga` output file.

**Comment by dlemstra** [comment]
You should only call `Resample(300, 300)` and don't set the `Density` yourself. Why are you using `Resample`? Would you mind explaining your usecase to me?

**Comment by deckertron9000** [comment]
Apparently we have a customer that needs the Pixels Per Inch to be set to various sizes upon image download. 72x72 , 96x96 and 300x300 mainly. Doing some more digging it looks like .tga files don't have anywhere to store DPI information so an image editor just makes a guess when it reads it. I think I was confusing density and resampling so this seems like a non-issue. Does that sound right based on your knowledge?

**Comment by dlemstra** [comment]
TGA images have no DPI so I think you came to the correct conclusion.

**Comment by dlemstra** [comment]
Just published a new release but I forgot to include this... Going to publish a new release later today that includes this.
