### ISSUE TITLE
Where does ResourceLimits.Memory gets it defaults from?

### ISSUE THREAD

**Issue by Marcel0024** [dlemstra/Magick.NET#576]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration

- Magick.NET version: Magick.NET 7.15.1.0
- Environment (Operating system, version and so on): Windows 10 x64

### Question
I'm having some issues with Magick.NET on Azure Function.

I noticed some images are failing to upload on Azure Function, but works perfectly fine on my develop PC.

Turns out it's memory issues on Azure Function. On my PC ResourceLimits.Memory defaults to 4GB, but on Azure Function it defaults to 511MB, while according to the docs i should have around 1.5GB for the whole function.

So i'm wondering how does it calculate the default memory it can use? I don't want to just override without knowing where it gets the 511MB

**Comment by daxpandhi** [comment]
I believe you may find some information in #524 - the policy XMLs embedded in ImageMagick.NET are the source of all defaults, AFAIK.

**Comment by daxpandhi** [comment]
I have to do this on app startup to ensure my app's Magick can use more memory. Although mine is a desktop application scenario.

```cs
            long mem = (long)new ComputerInfo().TotalPhysicalMemory;

            try
            {
                ResourceLimits.Memory = (ulong)(mem * 0.9);
            }
            catch (Exception ex)
            {
                log.Error(ex);
            }
```

**Comment by Marcel0024** [comment]
Is the default 2GB? The thing i don't understand on local machine it goes to 4GB and on Azure function it goes to 511MB. Where/how does it change?

**Comment by daxpandhi** [comment]
Yes, 2GB is the default. Here is the full policy.xml where you can see the other settings too.

The relevant part for 2GB is: 
`<policy domain="resource" name="memory" value="2GiB"/>`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policymap [
<!ELEMENT policymap (policy)+>
<!ELEMENT policy (#PCDATA)>
<!ATTLIST policy domain (delegate|coder|filter|path|resource) #IMPLIED>
<!ATTLIST policy name CDATA #IMPLIED>
<!ATTLIST policy rights CDATA #IMPLIED>
<!ATTLIST policy pattern CDATA #IMPLIED>
<!ATTLIST policy value CDATA #IMPLIED>
]>
<!--
  Configure ImageMagick policies.

  Domains include system, delegate, coder, filter, path, or resource.

  Rights include none, read, write, and execute.  Use | to combine them,
  for example: "read | write" to permit read from, or write to, a path.

  Use a glob expression as a pattern.

  Suppose we do not want users to process MPEG video images:

    <policy domain="delegate" rights="none" pattern="mpeg:decode" />

  Here we do not want users reading images from HTTP:

    <policy domain="coder" rights="none" pattern="HTTP" />

  Lets prevent users from executing any image filters:

    <policy domain="filter" rights="none" pattern="*" />

  The /repository file system is restricted to read only.  We use a glob
  expression to match all paths that start with /repository:
  
    <policy domain="path" rights="read" pattern="/repository/*" />

  Any large image is cached to disk rather than memory:

    <policy domain="resource" name="area" value="1GB"/>

  Define arguments for the memory, map, area, width, height, and disk resources
  with SI prefixes (.e.g 100MB).  In addition, resource policies are maximums
  for each instance of ImageMagick (e.g. policy memory limit 1GB, -limit 2GB
  exceeds policy maximum so memory limit is 1GB).
-->
<policymap>
  <!-- <policy domain="resource" name="temporary-path" value="/tmp"/> -->
  <!-- <policy domain="resource" name="memory" value="2GiB"/> -->
  <!-- <policy domain="resource" name="map" value="4GiB"/> -->
  <!-- <policy domain="resource" name="width" value="100MP"/> -->
  <!-- <policy domain="resource" name="height" value="100MP"/> -->
  <!-- <policy domain="resource" name="area" value="1GB"/> -->
  <!-- <policy domain="resource" name="disk" value="16EB"/> -->
  <!-- <policy domain="resource" name="file" value="768"/> -->
  <!-- <policy domain="resource" name="thread" value="4"/> -->
  <!-- <policy domain="resource" name="throttle" value="0"/> -->
  <!-- <policy domain="resource" name="time" value="3600"/> -->
  <!-- <policy domain="system" name="precision" value="6"/> -->
  <policy domain="cache" name="shared-secret" value="passphrase"/>
  <policy domain="coder" rights="none" pattern="EPHEMERAL" />
  <policy domain="coder" rights="none" pattern="MVG" />
  <policy domain="coder" rights="none" pattern="MSL" />
  <policy domain="path" rights="none" pattern="@*" />
  <policy domain="path" rights="none" pattern="|*" />
</policymap>
```

**Comment by daxpandhi** [comment]
Just ran some tests. Looks like it assigns 25% of total RAM. I have 64GB and it assigned 16GB on startup.

**Comment by dlemstra** [comment]
This is correct by default ImageMagick will only uses 25% of the memory that is available on the system. If you are running your application in an environment where you only use the memory you probably want to change that limit yourself to 80/90% instead. I just pushed a patch to change the default value from 25% to 50%. This information should be added to the documenation so people are aware of this fact. I was also not aware about this.

**Comment by Marcel0024** [comment]
Maybe the 'default' in the policy.xml should also be removed? Very misleading imo as it's just ignored

**Comment by dlemstra** [comment]
The value in the `policy.xml` file will override the default. Can you clarify what you mean by your comment @Marcel0024?
