### ISSUE TITLE
Convertion of PNG to PDF returns blank PDF

### ISSUE THREAD

**Issue by JBPuzzled** [dlemstra/Magick.NET#580]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm using this library to convert images to PDF files. Overall it works well, but I stumbled upon a PNG file that is not converted to PDF correctly. The output is a blank PDF file. I'm not able to get it to work, hence this issue. The issue is quite similar to #196 , but since that one is resolved I created a new issue.

### Steps to Reproduce
Use the attached PNG file and try to convert it to PDF using the code below.

```csharp
using (var image = new MagickImage(inputStream))
{
  image.Write(outputStream, MagickFormat.Pdf);
}
```

### System Configuration
The logic runs in an Azure Function, written in .NET CORE C#.

- Magick.NET version: Magick.NET-Q16-AnyCPU v7.15.1
- Environment: Azure Function runtime ~2

![4ff2694cd72b34f8b5f31a7d2f0bba61](https://user-images.githubusercontent.com/57446139/75259511-711d5b80-57e8-11ea-9221-794c1efdf502.png)

**Comment by dlemstra** [comment]
This is failing because your image has a ridiculous high dpi: `128000x72000`. Not sure what happend there but it looks like a mistake. When you set the density to a more reasonable value you will get a PDF with that image.

**Comment by JBPuzzled** [comment]
Thank you for your fast response.

How did you come to those numbers? File properties do not show huge anomalies. When I check the image properties in Paint it gives a resolution of 96 dpi. Checking the density for the image in a test console app shows the following. I am probably overlooking things here.
![Knipsel](https://user-images.githubusercontent.com/57446139/75326571-2993df80-587b-11ea-8201-0bc4d7ac9d49.PNG)

We have no control over the input (image) from the business. Converting this image does not throw an exception, but the outcome is not right. We have to be able to detect faulty outcomes in these situations. Otherwise this will definitely disrupt business processes.

Is is possible to (detect and) transform images up front to make it work with the library if the library cannot handle files with specific properties? Some kind of preprocessing.

**Comment by dlemstra** [comment]
Sorry for the confusion. ImageMagick identify on the command line show the following output:
```
Geometry: 1280x720+0+0
Resolution: 0.01x0.01
Print size: 128000x72000
Units: PixelsPerCentimeter
```

I mixed up the density and the printing size. You will need `128000x72000` of pixels to "print" the image. 

My advise would be to check the DPI of the image before writing it. If it is below 72/96 (or whatever value works for you) make it higher and otherwise you are probably okay.

**Comment by JBPuzzled** [comment]
I followed up your advise and increased the resolution if it exceeds the lower limit of both the PPI and PPC. The image is now correctly converted into - or printed to - a PDF file. These limits feel very arbitrary, but we will continue testing to refine logic.

```c#
switch (image.Density.Units)
{
    case DensityUnit.PixelsPerInch:
        if (image.Density.X < 300)
        {
            image.Density = new Density(300, DensityUnit.PixelsPerInch);
        }
        break;
    case DensityUnit.PixelsPerCentimeter:
        if (image.Density.X < 118)
        {
            image.Density = new Density(118, DensityUnit.PixelsPerCentimeter);
        }
        break;
    case DensityUnit.Undefined:
    default:
        break;
}
```

Side note: I think it is strange that Paint returns a resolution of 96 dpi. Although this is per inch, it still does not add up.

At this point I want to thank you for your help. As this is really kind of a work around, I'd suggest to put this on the backlog or create another ticket for it. The issue is that writing - at least specific - PNG files with a large print size to PDF will produce a blank PDF, having incorrect dimensions as well. There is no exception or whatsoever that indicates an error, while the output is not correct.

**Comment by dlemstra** [comment]
Not sure what you mean. The current behavior is not going to change. The output is not wrong. It is exactly how you specified it.

**Comment by JBPuzzled** [comment]
Let me put is this way. Writing the attached PNG image to a new PDF file using the code of my first message succeeds in the sense that there is no error. However, the PDF does not contain the image and the dimensions are also not correct. I did not specify it to change dimensions or to print only a part of the image. Still you state that the output is not wrong. How come? Could you help me understand, please?

**Comment by dlemstra** [comment]
In your input image you have a specific DPI for your input image. The page size of your PDF file is limited to a certain width. Your image is still in the file but you are only seeing the north-west corner of the image. And that part of the image does not really contain anything. This is happening because due to your DPI the image has a size of 128000x72000 pixels. I hope this explains it a bit better?

**Comment by JBPuzzled** [comment]
Yes, it does. Thank you for your patience on this matter. I will take a closer look at the limited measures of PDF files and continue testing.
