### ISSUE TITLE
Saving animated WebP image crashes on Linux

### ISSUE THREAD

**Issue by DejanPelzel** [dlemstra/Magick.NET#581]
### Description
When trying to save an animated WebP on Linux (we have tested with Ubuntu 18.04 and Debian 10), the whole application crashes with the following message:
```dotnet: symbol lookup error: /home/test/Magick.Native-Q8-x64.dll.so: undefined symbol: WebPPictureCopy```

This works on Windows without any issues, however.

### Steps to Reproduce
```
using (var img = new MagickImageCollection("test.gif"))
{
    img.Coalesce();
    img.Write("test.webp", MagickFormat.WebP);
}
```

### System Configuration

- Magick.NET version: 7.15.3 Magick.NET-Q8-x64
- Environment (Operating system, version and so on): Ubuntu 18.04 LTS / Debian 10
- Additional information: Tested with .NET Core 3.0/3.1

**Comment by dlemstra** [comment]
This appears to be a linking order issue and I just pushed a patch to fix this in the Magick.Native library. A new release has been published this weekend so it will probably take another month before a new release will be published. How urgent is this issue for you? Would you prefer to have this a bit earlier?

**Comment by DejanPelzel** [comment]
Thanks for looking into it so quickly. It's not super urgent as we have a temporary workaround, so that works great :)

**Comment by dlemstra** [comment]
I had some time this weekend and I published a new release that includes a fix for your issue. And thank you for sponsoring me 🥳🥳🥳
