### ISSUE TITLE
Can EMF format pictures be supported on linux

### ISSUE THREAD

**Issue by zhou881117** [dlemstra/Magick.NET#585]
a image export from excel, the format is emf。
windows all is ok，System.Drawing.Common and this。
but linux 
System.Drawing.Common: width and height is error
Magick.NET :NoDecodeDelegateForThisImageFormat `EMF'

**Comment by dlemstra** [comment]
There is no support for reading emf files on Linux in ImageMagick so I cannot add this to Linux build of Magick.NET.

**Comment by zhou881117** [comment]
tks!

**Comment by ashahabov** [comment]
EMF is still not supported for Linux?
