### ISSUE TITLE
Some PNG files report "invalid chunk type" when loading

### ISSUE THREAD

**Issue by rmbrunet** [dlemstra/Magick.NET#586]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Some PNG files throw **"ND[AE]B: invalid chunk type `' @ error/png.c/MagickPNGErrorHandler/1715"** exception when loading. The files are properly shown on windows explorer and successfully loaded in other programs (like Paint.Net) and with other libraries (ImageSharp loads the images without issue) 

### Steps to Reproduce

Just load the imaged attached at the botom

```
string source = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.png");
string target = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Desktop), "test.jpg");

try {
	using (MagickImage image = new MagickImage(source)) {
		image.Write(target);
	}
}
catch (Exception ex) {
	ex.Message.Dump();
	ex.StackTrace.Dump();
}
```
Stack Trace
```
ND[AE]B: invalid chunk type `C:\Users\rmartinez\Desktop\test.png' @ error/png.c/MagickPNGErrorHandler/1715
   at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
   at ImageMagick.MagickImage.NativeMagickImage.ReadFile(MagickSettings settings)
   at ImageMagick.MagickImage.Read(String fileName, MagickReadSettings readSettings, Boolean ping)
   at ImageMagick.MagickImage.Read(String fileName, MagickReadSettings readSettings)
   at ImageMagick.MagickImage.Read(String fileName)
   at ImageMagick.MagickImage..ctor(String fileName)
```
### System Configuration : 

- Linqpad 6.6.8 (X64) 
- Magick.NET version: MagickNET-Q8-AnyCPU
- Environment :  Windows 10 Versoin 1909

Test Image

![test](https://user-images.githubusercontent.com/2124799/75687828-67727880-5c6c-11ea-8242-5a99b29d8688.png)

**Comment by rmbrunet** [comment]
Hello Dirk... I have been having this issue for a while (and addressing it with ImageSharp), I re-tested today after upgrading to MagickNet 7.15.4.

**Comment by dlemstra** [comment]
This file contains an invalid `eXIf` png chunk. This chunk has an invalid length. A lot of libraries just ignore this chunk. The libpng library that is being used by ImageMagick can read this part but it is very strict and it will raise an error when the file is incorrect.

**Comment by rmbrunet** [comment]
Isn't there a configuration setting in libpng to be a little bit less strict and ignore the chunk? The fact that many apps and libs can load the file hides the fact that is an invalid one.

**Comment by dlemstra** [comment]
The libpng library that is being used has no setting to be less strict and I also stepped trough it with a debugger to check if we could hack around this but the library will stop processing the file when this exception is being raised.

**Comment by rmbrunet** [comment]
Hello Dirk,

Then it seems we have to live with it. There is some other interesting thing: another team that works directly with ImageMagick successfully processed this same image (I assume using convert with expand) generating images with different sizes. I don't have ImageMagick installed but it would be surprising that ImageMagick can process the file while MagickNet can't. Will try to do a test when I have a chance.

Thanks

R.

**Comment by dlemstra** [comment]
They might be using an older version of the libpng library or ImageMagick that was less strict.

**Comment by rmbrunet** [comment]
This is what I get in ImageMagick (7.01.9-27)

![image](https://user-images.githubusercontent.com/2124799/75789423-ade0d980-5d37-11ea-9abd-9f1b9d3b3638.png)

**Comment by dlemstra** [comment]
And the `error/png.c` means that an exception will be raised in Magick.NET.
