### ISSUE TITLE
VC++ dependencies for OpenMP

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#587]
Sorry for skipping the form. This is pretty straightforward. Would it be possible to for me to include specific DLLs from the VC runtime required for the OpenMP flavor of ImageMagick.NET? If so, any ideas what those DLLs would be? No problem if not.

Just asking because installing VC++ is an additional step I'd like to skip in my software's installer.

**Comment by dlemstra** [comment]
I remember having a trick for this by including this with the installer a long time ago but I don't remember how. Will need to go through my archives. What kind of installer are you using?

**Comment by daxpandhi** [comment]
We're using NSIS.

**Comment by dlemstra** [comment]
On my way to work I realized that it might be sufficient to copy the necessary binaries to the bin folder. Not sure which one you will need but I think you can figure that out with a tool that show the dll dependencies of the native library.

**Comment by daxpandhi** [comment]
Yes, that's exactly what I was hoping for! We do that with a few Boost DLLs our code relies on. Would be great to pack all the files so its one less thing for the user to install. Especially in enterprise environments where admin rights are not available.

No hurry! Thanks!

**Comment by dlemstra** [comment]
The no hurry comment gave me the impression that you are expecting me to do something. But in my previous comment I said that you should copy the binaries to the folder. But while writing this comment I realized that it might be possible for me to include those files during the build the same way as the `.Native` library is included. Will need investigate this and I will probably need your help to test this.

**Comment by daxpandhi** [comment]
Oops - I misread. I'll try it out and let you know what the dependencies are.

Happy to help any way I can. :)
