### ISSUE TITLE
Umlauts are replaced

### ISSUE THREAD

**Issue by Reality80** [dlemstra/Magick.NET#588]
Hello,

I have the problem that when converting pdf to png the umlauts in the text are getting replaced.
I have tried to set the MagickReadSettings font (Arial) and unicode (UTF8) settings without success and I don't know any other approach. I hope you can help. Thank you in advance!

I'm using the latest Magick.NET version 7.15.4.0 (Magick.NET-Q8-x64), installed via nuget. My system is Windows 10 x64, german environment settings. I am also using the latest ghostscript version 9.50.

I've attached two screenshots. One of the original pdf text and the converted png text.

![pdf_text](https://user-images.githubusercontent.com/61983131/76235719-cbc4a780-622b-11ea-94cc-c3fdb224935c.png)
![png_text](https://user-images.githubusercontent.com/61983131/76235754-daab5a00-622b-11ea-8649-78bd0e8a66a8.png)

**Comment by dlemstra** [comment]
Can you share the PDF file so I can try to reproduce this issue?

**Comment by Reality80** [comment]
Yes, sure. I've attached it to this comment. Thank you!
What I found out, is that it is not possible to copy text out of this pdf file, maybe this is one of the reasons, I'm not sure.

[Source.PDF](https://github.com/dlemstra/Magick.NET/files/4311491/Source.PDF)

**Comment by dlemstra** [comment]
This appears to be a Ghostscript issue. When I run the Ghostscript command on the command line I get the following output:

```
"i:\>c:\Program Files\gs\gs9.27\bin\gswin64c.exe" -dSAFER -sDEVICE=pngalpha -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r72x72 -sOutputFile=Source.png Source.PDF
GPL Ghostscript 9.27 (2019-04-04)
Copyright (C) 2018 Artifex Software, Inc.  All rights reserved.
This software is supplied under the GNU AGPLv3 and comes with NO WARRANTY:
see the file COPYING for details.
Processing pages 1 through 1.
Page 1
Can't find CID font "Arial".
Attempting to substitute CID font /Adobe-Identity for /Arial, see doc/Use.htm#CIDFontSubstitution.
The substitute CID font "Adobe-Identity" is not provided either. attempting to use fallback CIDFont.See doc/Use.htm#CIDFontSubstitution.
Loading a TT font from %rom%Resource/CIDFSubst/DroidSansFallback.ttf to emulate a CID font Adobe-Identity ... Done.
Can't find CID font "Arial".
Attempting to substitute CID font /Adobe-Identity for /Arial, see doc/Use.htm#CIDFontSubstitution.
Can't find CID font "TimesNewRoman".
Attempting to substitute CID font /Adobe-Identity for /TimesNewRoman, see doc/Use.htm#CIDFontSubstitution.
>>showpage, press <return> to continue<<
```

More info can be found here: https://www.ghostscript.com/doc/current/Use.htm#CIDFontSubstitution
