### ISSUE TITLE
Multithreading PDF to image

### ISSUE THREAD

**Issue by ElBart00** [dlemstra/Magick.NET#59]
I've created a asp.net handler to create a png image from a pdf file on the fly. This works great, but when I display multiple pdf images on one page only one gets converted to an image. The other conversions fail with 
ImageMagick.MagickDelegateErrorException: PDFDelegateFailed `file not found (translated by me).
' @ error/pdf.c/ReadPDFImage/793

**Comment by dlemstra** [comment]
How did you make Ghostscript available to Magick.NET did you install it on your machine or did you use `MagickNET.SetGhostscriptDirectory`? And did you copy both files as described here: https://github.com/dlemstra/Magick.NET/tree/master/Documentation#ghostscript when you used the latter.

**Comment by ElBart00** [comment]
I'm using Ghostscript with the 2 files in the App_Data folder and set `MagickNET.SetGhostscriptDirectory`. This is working as expected as one PDF is converted.

**Comment by dlemstra** [comment]
Is it possible to attach debug logging to this post? https://github.com/dlemstra/Magick.NET/blob/master/Documentation/DetailedDebugInformation.md

**Comment by ElBart00** [comment]
The log is to big to post it here, but I found an error in it: Failed to remove: xxxxx/App_Data/TEMP/magick-39932RgAq-xWlE1Ya2.cache

**Comment by dlemstra** [comment]
That error is a probably false positive. We remove the file without checking if it exists. Are you able to find the 'file not found' (of de Nederlandse versie) error?

**Comment by ElBart00** [comment]
In the log it says: `ImageMagick.MagickDelegateErrorException: PDFDelegateFailed `Het systeem kan het opgegeven bestand niet vinden.
' @ error/pdf.c/ReadPDFImage/793
   bij ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadFile(MagickSettings settings)
   bij ImageMagick.MagickImageCollection.AddImages(String fileName, MagickReadSettings readSettings, Boolean ping)`

But when I stop the debugger on the exception I found a related exception: `FailedToExecuteCommand `"xxxxxxx/App_Data//gswin64c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r300x300"  "-sOutputFile=xxxxxxx/App_Data/TEMP/magick-46144763X2x5Q2p6F%d" "-fxxxxxxx/App_Data/TEMP/magick-46144VM2otn0ht_ER" "-fxxxxxxx/App_Data/TEMP/magick-46144nFaIQ9M4Jf-Q"' (Het systeem kan het opgegeven bestand niet vinden.
) @ error/delegate.c/ExternalDelegateCommand/460`

Is that of any help?

**Comment by dlemstra** [comment]
I am assuming that you checked if the file `gswin64c.exe` exists in your 'Data' folder? Maybe you will need to tell Windows to allow execution within that folder?

**Comment by ElBart00** [comment]
Yes, the first PDF is converted correctly, so I assume Magick is configured correctly and working as expected. This error occures only when 2 or more PDF's need to be converted simultaniously. The first conversion works as expected, but all subsequent simultanious conversions fail.

**Comment by dlemstra** [comment]
I think I have not explained clearly why this fails with a simultaneously conversion. When you convert only one file Magick.NET will load `gsdl64.dll` and use the library of Ghostscript to convert the PDF file. This seems to work on your system. The documentation of Ghostscript says that using the `gsdl64.dll` library is not thread safe. Inside ImageMagick there is a check to make sure only one thread is using the `gsdl64.dll` library. The next thread will be forced to use the executable `gswin64c.exe`. It looks like ImageMagick is not able to find or execute `gswin64c.exe`. I wonder if this is a a security issue where the identity of your application pool is not allowed to start that executable.

**Comment by ElBart00** [comment]
You're absolutely right. I've copied the wrong file. gswin64.exe in stead of gswin64c.exe. Sorry for the stupid mistake. Thanks for your patience.

**Comment by dlemstra** [comment]
No problem :) I am happy that we could resolve this issue 👍
