### ISSUE TITLE
Stroked rectangle is drawn incorrectly

### ISSUE THREAD

**Issue by snechaev** [dlemstra/Magick.NET#591]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
After updating to the latest Magick.NET build I found that stroked rectangle is drawn with non-solid strokes, while other stroked primitives (circles, lines, etc) are drawn with the solid strokes while the same settings are used.
![test7 4 6](https://user-images.githubusercontent.com/6499856/76952135-38802600-693f-11ea-9448-4d270221fc09.png)

Here we can see:
* red rectangle drawn by Rectangle operation - is drawn incorrectly. The strokes are not solid and maid with parts of thin diagonal lines/dots.
* black circle is ok (with the same stroke settings).
* green rectangle (with the same size as red) is drawn by 4 Line operations - also ok.

### Steps to Reproduce
Use the following code to reproduce the issue (.NET FW 4.5.1 console app Any CPU prefer 32bit, magick.net-q8-anyCPU 7.15.4)
```
        static void Main(string[] args)
        {
            const int width = 500;
            const int height = 500;
            const int strokeWidth = 5;

            using (var image = new MagickImage(MagickColors.Transparent, width, height))
            {
                var d = new Drawables();
                d.StrokeDashArray(4.0 * strokeWidth, 2.0 * strokeWidth);
                d.StrokeLineCap(LineCap.Round);
                d.StrokeAntialias(true);
                d.StrokeWidth(strokeWidth);
                d.FillColor(MagickColors.Transparent);

                ///////////////////////////////////
                d.StrokeColor(MagickColors.OrangeRed);
                d.Rectangle(5, 5, 200, 200);

                ///////////////////////////////////
                d.StrokeColor(Color.Black);
                d.Circle(100, 100, 70, 70);
                ///////////////////////////////////
                d.StrokeColor(Color.Green);
                d.Line(495, 495, 495, 300);
                d.Line(495, 300, 300, 300);
                d.Line( 300, 300, 300, 495);
                d.Line( 300, 495,495, 495);

                image.Draw(d);
                image.Write("test.png");
            }
        }
```
### System Configuration

- Magick.NET version: magick.net-q8-anyCPU 7.15.4 from nuget
- Environment: Win10 x64
- Additional information: 
I checked the release history and found that new behaviour was introduced in 7.4.6 (so, 7.4.5 works fine, and 7.4.6 works incorrectly).

The (correct) results from 7.4.5 looks as following:
![test](https://user-images.githubusercontent.com/6499856/76952584-e55aa300-693f-11ea-9631-04f578b998b3.png)

**Comment by dlemstra** [comment]
Thanks for reporting this and it seems we had this bug for a while now. This will be resolved in the next release. And thanks for the detailed report that allowed me to create a unit test with the sample that you provided.
