### ISSUE TITLE
MagickImage.Resize() is slow when called first

### ISSUE THREAD

**Issue by Prometheus3375** [dlemstra/Magick.NET#595]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET

### System Configuration
- Magick.NET 7.15.4 Q8 AnyCPU
- Windows 10 Enterprise LTSC 2019 x64
- Notebook with GeForce 940MX and Intel Core i7-7500U

Magick.NET is used inside .NET Core 3.1 WPF application.

### Question
I have such class.
```csharp
public class Frame: IApplier {
    public int ID { get; }
    public string Path { get; }
    public MagickImage ApplyingImage { get; }
    public string Name { get; }
    public MagickGeometry Geometry { get; }

    private Frame(int id, string path, MagickImage image) {
        ID = id;
        Path = path;
        ApplyingImage = image;
        Name = System.IO.Path.GetFileNameWithoutExtension(path);
        Geometry = new MagickGeometry(image.Width, image.Height) {
            FillArea = false,
            IgnoreAspectRatio = false,
            Greater = false,
            Less = false
        };
    }

    public MagickImage Apply(MagickImage image) {
#if TEST
        Debug.WriteLine($"Filter used {image.FilterType}");
#endif
        image.Resize(Geometry);

        if (image.Width < Geometry.Width || image.Height < Geometry.Height) {
            using var old = image;
            image = new MagickImage(MagickColors.Transparent, Geometry.Width, Geometry.Height);
            image.Composite(old, CompositeOperator.SrcOver);
        }

        image.Composite(ApplyingImage, CompositeOperator.SrcOver);
        return image;
    }

    public void Dispose() {
        ApplyingImage.Dispose();
    }
```
I have N instances of such class with `ApplyingImage` of size 64x64 and 1 bigger image to which I apply these instances. The very first `Resize()` call lasts around 3 seconds, all next calls are fast. It seems like first call loads something.
I found similar [issue](https://github.com/dlemstra/Magick.NET/issues/554), and seems here is the same behavior. I want to know next things:

1. Is my assumption of the same behavior correct?
2. If yes, then is there a way to run OpenCL benchmark before any call to MagickImage methods?
3. If there is no way, then how to disable OpenCL acceleration?

**Comment by dlemstra** [comment]
1. I think your assumption is correct and that this is happening due to OpenCL.
2. You can force the OpenCL benchmark by calling `OpenCL.Devices`.
3. If you want to disable OpenCL you should set `OpenCL.IsEnabled` to false.

**Comment by Prometheus3375** [comment]
Thank a lot, calling `OpenCL.Devices` helped.
What kind of problems can arise if I disable OpenCL?

**Comment by dlemstra** [comment]
No problems will arise but depending on your hardware it might be faster with OpenCL enabled.

**Comment by Prometheus3375** [comment]
Well, accessing `OpenCL.Devices` via `var _ = OpenCL.Devices;` increases RAM usage by ~50 MB which is quite a lot for may app. Is there any way to force OpenCL to run benchmarks via a method call?

**Comment by dlemstra** [comment]
That method is not doing much extra besides running the benchmark.

**Comment by Prometheus3375** [comment]
I has made several tests. OpenCL will use ~50 MB of RAM some moments later benchmark was run, regardless of the way it is accessed.
I noticed this because I put `var _ = OpenCL.Devices;` line in the main function and was surprised that right after startup RAM usage had increased by ~50 MB.

Thank you for your answers!
