### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by masaeedu** [dlemstra/Magick.NET#6]

**Comment by dlemstra** [comment]
I have created a work item for this: https://magick.codeplex.com/workitem/1376

**Comment by masaeedu** [comment]
From what I understand, you need to have the following installed:
 
 - Visual Studio 2008 (not just VC++ 2008)
 - Visual Studio 2015

Then you need to run:

 1. BuildAll.cmd in ImageMagick/Source
 2. msbuild for one of the solutions (depending on what platform you're targeting)

Is that more or less correct?

**Comment by dlemstra** [comment]
You will first need to run ImageMagick/Source/checkout.cmd to get the source of ImageMagick if you want to run BuildAll.cmd.

You can also skip building ImageMagick and just copy the libraries from my DropBox folder. You will get the download location when you run ImageMagick/CopyLibsFromDropbox.cmd

I will do a reinstall of my machine next week and I will then create a document that includes installation/building instructions.

**Comment by masaeedu** [comment]
Awesome, thanks Dirk!

**Comment by dlemstra** [comment]
I have added a simple document here: https://github.com/dlemstra/Magick.NET/blob/master/Building.md and here: https://github.com/dlemstra/Magick.NET/blob/master/Magick.NET.Core/Building.md.
