### ISSUE TITLE
Doesn't seem to support Chinese

### ISSUE THREAD

**Issue by mchenx** [dlemstra/Magick.NET#60]
I wanted to show name on the right bottom side of a image, the name could be English or Chinese, but it always print ???? for Chinese, even I tried to encode the test by UTF-8.

`var bytes = Encoding.Default.GetBytes("面朝大海的猪\r\n@m0078341");`
`var text = Encoding.UTF8.GetString(bytes, 0, bytes.Length);`
`var encoding = new DrawableTextEncoding(Encoding.UTF8);`
`var drawable = new DrawableText(38, 0, text);`
`var gravity = new DrawableGravity(Gravity.Southeast);`
`var font = new DrawableFont("Microsoft YaHei UI");`
`var antialias = new DrawableTextAntialias(true);`
`var size = new DrawableFontPointSize(14);`
`var color = new DrawableFillColor(Color.White);
img.Draw(drawable, gravity, font, antialias, size, color, encoding);`

**Comment by dlemstra** [comment]
I am able to write Chinese text on an image with the following code:
```
    using (MagickImage img = new MagickImage(MagickColors.Purple, 500, 500))
    {
        var drawables = new Drawables()
            .TextEncoding(Encoding.UTF8)
            .TextAntialias(true)
            .FontPointSize(14)
            .FillColor(MagickColors.White)
            .Gravity(Gravity.Southeast)
            .Font("Microsoft YaHei & Microsoft YaHei UI")
            .Text(38, 0, "面朝大海的猪\r\n@m0078341")
            .Draw(img);

        img.Write(@"i:\test.png");
    }
```
It appears that you are not using the correct font family name. You should use `Microsoft YaHei & Microsoft YaHei UI` instead. I just added a property to the MagickNET class to get a list of all font family names. You can use `MagickNET.FontFamilies` in the next version of Magick.NET.

**Comment by mchenx** [comment]
You are right, it was caused by the wrong font family name. Thanks a lot.

**Comment by kasradzenika** [comment]
Thanks, @dlemstra I think you should paste this piece of info over in your [**Drawing** section](https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Drawing.md), this is going to help a lot of people

**Comment by dlemstra** [comment]
@kasradzenika And you could help me with a PR 😄 The code can be found in the `Samples` folder.

**Comment by xucongli1989** [comment]
I have a same problem. The root cause is that the library reads all the font names incorrectly. I think you should refer to the method used by dotnet to get the font names.
# Get fonts from MagickImage
![image](https://user-images.githubusercontent.com/9961428/122659533-b4ed5e80-d1ab-11eb-98a2-fed082bdcd82.png)
![image](https://user-images.githubusercontent.com/9961428/122659595-507ecf00-d1ac-11eb-8bc0-b8e17883d262.png)

# Get fonts from dotnet
![image](https://user-images.githubusercontent.com/9961428/122659570-03026200-d1ac-11eb-9c4d-cd45d7292f5a.png)
![image](https://user-images.githubusercontent.com/9961428/122659603-5c6a9100-d1ac-11eb-8893-89944c501bba.png)

**Comment by dlemstra** [comment]
Can you share one of those font files that has the wrong name @xucongli1989?

**Comment by CainSakura** [comment]
> Can you share one of those font files that has the wrong name @xucongli1989?

Hi @dlemstra , I have similar issue and tracked down to here. Here's a pack of [sample fonts](https://temp.sh/osSQi/fonts-sample.7z) for you. Their names are messed up so I cannot identify all of them. Hope this helps.

**Comment by dlemstra** [comment]
I was unable to test it with those fonts but I found something that could probably cause the font naming issue. Please give it a try with the next release that will probably be published this weekend.

**Comment by CainSakura** [comment]
I just tried latest version 10.1.0 and it works now. Thanks for your efforts!
![image](https://user-images.githubusercontent.com/16740801/156946877-42e1c1be-b91f-4217-afc1-ffa7b046ea3f.png)
