### ISSUE TITLE
VS 2019 Crashes when trying to browse Types in Settings

### ISSUE THREAD

**Issue by simonbuehler** [dlemstra/Magick.NET#603]
### Description
hi,
when trying to add e.g. a ImageMagick.MagickColor to a app setting the VS 2019 crashes. This is the only library that shows such a behaviour

### Steps to Reproduce
* add  nuget package
* try to  browse the types

![grafik](https://user-images.githubusercontent.com/78061/78666826-383cd000-78d8-11ea-8409-9035b22a0547.png)
* boom

### System Configuration

- Magick.NET version:  tested with 7.15.4 and 7.15.5
-  win 10

**Comment by dlemstra** [comment]
This is an issue that should be reported somewhere else? This is probably a bug in Visual Studio instead?

**Comment by simonbuehler** [comment]
i suspect the native file beeing not found / linked / whatever ...
opened a bug https://developercommunity.visualstudio.com/content/problem/982184/vs-crash-when-trying-to-browse-types-of-assemly-in.html

lets see what feedback is given there

**Comment by daxpandhi** [comment]
`MagickColor` is not serializable to XML, so will throw such errors. 

I ran into this same problem. My workaround was creating a serializable counterpart in my application and use that to set the MagickColor in ImageMagick.

Here is my class in case its useful:

```
    [Serializable]
    public struct Rgba
    {
        /// <summary>   Initializes a new instance of the ProtoCore.RGBA class.</summary>
        /// <param name="r">    The r. </param>
        /// <param name="g">    The g. </param>
        /// <param name="b">    The b. </param>
        /// <param name="a">    (Optional) a. </param>
        public Rgba(double r = 0.0, double g = 0.0, double b = 0.0, double a = 1.0)
        {
            R = r;
            G = g;
            B = b;
            A = a;
        }

        /// <summary>   Gets or sets the r.</summary>
        /// <value> The r.</value>
        [XmlAttribute] public double R { get; set; }

        /// <summary>   Gets or sets the g.</summary>
        /// <value> The g.</value>
        [XmlAttribute] public double G { get; set; }

        /// <summary>   Gets or sets the b.</summary>
        /// <value> The b.</value>
        [XmlAttribute] public double B { get; set; }

        /// <summary>   Gets or sets a.</summary>
        /// <value> a.</value>
        [XmlAttribute] public double A { get; set; }

        #region Overrides of ValueType

        public override string ToString()
            => $"{R * 255},{G * 255},{B * 255},{A * 255}";

        public MagickColor ToMagickColor()
        {
            return new MagickColor(R, G, B, A);
        }

        #endregion
    }
```
