### ISSUE TITLE
No metadata in new file when converting CR2 to JPG using the API.

### ISSUE THREAD

**Issue by Mogrinnar** [dlemstra/Magick.NET#608]
### Is your feature request related to a problem? Please describe
Currently if I use the MagickImage API as instructed [here](https://github.com/dlemstra/Magick.NET/blob/master/docs/ReadRawImageFromCamera.md), I do have a converted JPG image. However the colors are slightly altered and there is no metadata.

If you look at this image:
![miCr2](https://user-images.githubusercontent.com/11793014/79178743-02b24e00-7dd4-11ea-9912-7a5e052ce780.jpg)
On the **right** is a jpg that was produced by https://www.online-convert.com. The original CR2 is not in the screenshot I attached but the colors look exactly like the picture on the right.

On the **left** is the jpg produced by MagickImage, using the following code
```
var settings = new MagickReadSettings();
settings.Format = MagickFormat.Cr2;
using (MagickImage image = new MagickImage(CR2FilePath, settings))
{
    image.Write(destinationFileName, MagickFormat.Jpg);
}
```
The file size is smaller, there is no metadata and the colors are altered.

### Describe the solution you'd like
I would like the conversion from CR2 to JPG to keep the metadata and the original colors.

### Describe alternatives you've considered
I have looked at the documentation [here ](https://www.imagemagick.org/Usage/formats/#crw)but in the API neither the `MagickReadSettings` nor the `MagickImageInfo` offer me processing options that can fix my issue.

### Additional context
I can submit all my code that uses the API but the lines above are the only MagickImage related ones.

**Comment by dlemstra** [comment]
Can you also share your input file?

**Comment by Mogrinnar** [comment]
Input and output files available [here](https://we.tl/t-uEELXpsraa).

**Comment by dlemstra** [comment]
The colors are the ones that are provided by the libraw library. I think you will need to report the issue there instead: https://github.com/LibRaw/LibRaw/issues. And the meta data is stored a bit different than in the CR2 format. You can get the names of the attributes with the following code:

```C#
 image.AttributeNames.Where(attribute => attribute.StartsWith("dng:"))
```

**Comment by dlemstra** [comment]
In the next release you will be able to do this:

```C#
var settings = new MagickReadSettings
{
    Defines = new DngReadDefines
    {
        UseCameraWhitebalance = true,
    },
};

using (var image = new MagickImage("yourFile", settings))
{
}
```

Not sure if that is the right option but it is closer to the colors that you are expecting. You might have to try some of the other properties.

**Comment by Mogrinnar** [comment]
Thank you very much for the support. I will test once the new release is out and share the results.

**Comment by dlemstra** [comment]
The new API has been published. Hope this works for you.

**Comment by kmgallahan** [comment]
@Mogrinnar Thanks for reporting this issue, and @dlemstra thanks even more for quickly adding the new settings option. Just ran into this issue and found the solution here. 👍
