### ISSUE TITLE
MagickImageCollection isnt animated if saved from stream

### ISSUE THREAD

**Issue by GeorgeTG** [dlemstra/Magick.NET#61]
Im trying to write a MagickImageCollection to a stream, so I can immediately set it as Image to a pictureBox, but also save to disk later if needed.
My issue is that
`collection.write`  with a path as an argument will write the file normally and the file is animated, but when trying to do something like this (sample code):
```
                this.imageStream = new MemoryStream();
                collection.Write(this.imageStream);
                this.imageStream.Position = 0;
                this.pictureBox.Image = Image.FromStream(this.imageStream);
                SaveFileDialog sfd = new SaveFileDialog();
                sfd.AddExtension = true;
                sfd.Filter = "Animated Images|*.gif";
                this.imageStream.Position = 0;
                if (sfd.ShowDialog() == DialogResult.OK) {
                    using (FileStream file = new FileStream(sfd.FileName, FileMode.Create, System.IO.FileAccess.Write)) {
                        byte[] bytes = new byte[this.imageStream.Length];
                        this.imageStream.Read(bytes, 0, (int)this.imageStream.Length);
                        file.Write(bytes, 0, bytes.Length);
                    }
                }
                collection.Dispose();
            }
```
both the picture box and the file are not animated, they are just the first frame, frozen.

**Comment by dlemstra** [comment]
Is the animation also lost when you write it to a file stream? Would it be possible to create a small sample project? I think this is an issue in System.Drawing.

**Comment by GeorgeTG** [comment]
Nope, if I pass a string argument to write which is a path, the saved file is properly animated

On Jun 18, 2017 21:14, Dirk Lemstra <notifications@github.com> wrote:

Is the animation also lost when you write it to a file stream? Would it be possible to create a small sample project? I think this is an issue in System.Drawing.

**Comment by dlemstra** [comment]
It seems I have not asked my question clear enough. Is the animation also lost when you do something like this:
```C#
using (MagickImageCollection collection = CreateCollection())
{
    using (FileStream fs = File.OpenWrite(@"c:\test.gif"))
    {
        collection.Write(fs);
    }
}
```

I think this is an issue with how the pictureBox handles the MemoryStream. Can you create a small sample project that I can use to reproduce the issue?

**Comment by GeorgeTG** [comment]
Ok, I will make one

On Jun 19, 2017 16:07, Dirk Lemstra <notifications@github.com> wrote:

It seems I have not asked my question clear enough. Is the animation also lost when you do something like this:

using (MagickImageCollection collection = CreateCollection())
{
    using (FileStream fs = File.OpenWrite(@"c:\test.gif"))
    {
        collection.Write(fs);
    }
}

I think this is an issue with how the pictureBox handles the MemoryStream. Can you create a small sample project that I can use to reproduce the issue?

**Comment by GeorgeTG** [comment]
https://github.com/GeorgeTG/test_stream_magick
Reproduce with this solution

**Comment by dlemstra** [comment]
Thanks for creating the project. I should have know why this happens but I also sometimes forget that you will need to specify the `MagickFormat` when you write to a stream. When you don't specify the format it will use the format of the first image in the `MagickImageCollection`. In your example project this is a `bmp` image so the file that is created becomes a `bmp` file and that is why you only see one frame. You can fix your code like this:

```C#
// set to picture box by stream
collection.Write(memoryStream, MagickFormat.Gif);
```

And you don't need the MakeBitmap method you can just do this:

```C#
collection.Add(new MagickImage(MagickColors.Red, 200, 200));
```

**Comment by dlemstra** [comment]
Is this issue resolve @GeorgeTG and can we close it?

**Comment by GeorgeTG** [comment]
Well, turns out I was missing something really obvious, specifying the format did the trick, thanks for the help!!
