### ISSUE TITLE
Alpha channel missing

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#611]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Alpha channel is ignored when saving to several formats that support it. When debugging, I can see that the MagickImage has an alpha channel with the data provided. However, the saved file does not show the A channel in Photoshop or other applications.

Maybe I'm not doing something write, but feels like if Alpha is On/Set, and data is being added it should save too. I've tried it on 7.14.x, 7.15.x and 7.16.x to confirm.

### Steps to Reproduce
Here is a test program to create 3 files that should have alpha channels.

```
    internal class Program
    {
        private static void Main(string[] args)
        {
            MagickImage mm = new MagickImage(MagickColors.Black, 1024, 1024)
            {
                ColorType = ColorType.TrueColorAlpha,
            };

            mm.Alpha(AlphaOption.Set); // Have tried all "positive" options

            float[] data = new float[1024 * 1024 * 4];

            Random r = new Random(256);

            for (int i = 0; i < data.Length; i++)
            {
                data[i] = (float)(Quantum.Max * r.NextDouble());
            }

            using (var pix = mm.GetPixelsUnsafe())
            {
                pix.SetPixels(data);
            }

            mm.BitDepth(16);

            mm.Write("D:\\rgba.psd", MagickFormat.Psd);
            mm.Write("D:\\rgba.tif", MagickFormat.Tiff);
            mm.Write("D:\\rgba.png", MagickFormat.Png);

            mm.Dispose();
        }
    }
```

### System Configuration
- Magick.NET version: `Magick.NET-Q16-HDRI-OpenMP-x64 7.16.0.0`
- Environment (Operating system, version and so on): `Win 7 SP1, Win 10 (all versions) .NET Fx 4.8`
- Additional information:

**Comment by dlemstra** [comment]
I am unable to reproduce your issue:

![afbeelding](https://user-images.githubusercontent.com/10426229/79384155-a92e5880-7f66-11ea-8efd-64574b7f5ab3.png)

`64 bit depth = 16 bit per channel * 4` . This means there is an alpha channel. And when I check the files with ImageMagick (maybe biased?) all the files have an alpha channel. Not sure why Photoshop seems to think that these images have no alpha channel.

**Comment by daxpandhi** [comment]
Very strange. I'll investigate more on my end see if I can reproduce it more extensively or if there is something wrong in my workflow that is causing the problem. Will check and report back. Thanks!
