### ISSUE TITLE
TIF EXIF data edit not functioning

### ISSUE THREAD

**Issue by postnik0706** [dlemstra/Magick.NET#616]
Hello Dirk, 
My goal is to have either UserComment, XPComment or ImageDescription modified for a TIF image. That does not work though with Magick.NET, but works when I do a command line PNG to TIF conversion with -comment parameter.
I have created a fork out of your repo and added a unit test to it replicating TIFF Exif issue with Exif being null after it was modified (with the same TIFF image as in other TIFF unit tests). The link can be found below. Will try figuring out on my own on how to fix this; any advice would be very much appreciated.
I also have a strong interest in getting your library run with ImageMagick compiled for Android. Will be working on that.

My repo/changeset location I mentioned:
https://github.com/postnik0706/Magick.NET/commit/ebfcd6eb1da29b70f983b8f691cd244e8c5a3f2d

Thanks!

**Comment by postnik0706** [comment]
Also added a PS1 file that replicates a successful Comment property edit.

**Comment by dlemstra** [comment]
The libtiff library that we use does not support writing exif tags. More info can be found here: https://stackoverflow.com/a/23251710. If you want to write the `TIFFTAG_IMAGEDESCRIPTION` you could use the `Comment` property of the `MagickImage` class. That is the same as the `-comment` option of the command line.

**Comment by postnik0706** [comment]
Understood. Thanks so much for advising!
The Comment property does not seem to be serializing either; I have checked in a code change to my repo demonstrating that.
The working 'Magick.exe' command line changes not only the ImageDescription but also the Title (seen as one of the file properties at Windows file explorer). I suspect there is something more complex behind that '-comment' command line option; not sure yet what that might be exactly.

**Comment by dlemstra** [comment]
What is the command  that you use that reproduces this? Maybe it depends on the input image whether the title is also set?

**Comment by postnik0706** [comment]
I use the same image from your repo that is used for the unit tests; PS1 file containing the command is added to my repository. Its normal location in your repo is: Magick.NET/tests/Magick.NET.Tests/PS1Scripts/command_line_test.ps1.

Below is the content of 'command_line_test.ps1' file (the path to magick.exe needs to be revised):
# Convert Png to Tiff and set comment.
C:\image\magick.exe -comment "test" "..\Images\Magick.NET.icon.png" ".\Magick.NET.icon.tif"

# Get image information.
C:\image\magick.exe identify -verbose ".\Magick.NET.icon.tif"

**Comment by dlemstra** [comment]
It seems that you found a bug in the `Comment` property. This will be resolved in the next release. A temporary work around would be `image.SetAttribute("comment", "test");`.

**Comment by postnik0706** [comment]
Great! Thanks so much!
