### ISSUE TITLE
Dot Net core 3.1 Invalid Parameter System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi) Error in Linux

### ISSUE THREAD

**Issue by antfusa** [dlemstra/Magick.NET#619]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When attempting to convert the image (ASP.Net Core 3.1) a method is called (passing in a IFormFile  var named "ImageUpload" and Quality is an int value)

```C#
using var webMemoryStream = new MemoryStream();

var size = new MagickGeometry(500, 500);
size.IgnoreAspectRatio = true;

 var image = new MagickImage(ImageUpload.OpenReadStream())
{
       Format = MagickFormat.WebP,
       Quality = Quality
};

if (image.Width > 500 && image.Height > 500)
{
    image.Resize(size);
}

// Write image to the memory
image.Write(webMemoryStream)
```

an exception is thrown saying:

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
An unhandled exception has occurred while executing the request.
System.ArgumentException: Parameter is not valid.
at System.Drawing.Bitmap.SetResolution(Single xDpi, Single yDpi)

This is not an issue in Windows locally, but once deployed into a Linux environment (with all the appropriate dependencies and packages) this error occurs. It seems like an issue with System.Drawing, which of course is a Microsoft package, but seems like something from the Magick libraries are not passing something into it, or the wrong thing (hence the param not valid msg)

### Steps to Reproduce
Run this code bit in an ASP.Net Core 3.1 instance in a Linux environment using "Magick.NET-Q16-AnyCPU" Version="7.16.1"

### System Configuration
Docker Linux Instance (Production)
Windows 10 (Dev. Env.)

- Magick.NET version:
 PackageReference Include="Magick.NET-Q16-AnyCPU" Version="7.16.1"

**Comment by dlemstra** [comment]
It looks like some code is missing from your example? I don't see the call to `Bitmap.SetResolution`. I would also adviste you to not use the `System.Drawing` package on Linux. Why do you need this?

**Comment by antfusa** [comment]
Strangely enough, we do not even have the system.drawing package in the application, but it still keeps referencing it. It seems to blow up on "size.IgnoreAspectRatio = true;". Maybe the project file is corrupt... We may need to copy it all over to a new file and try again, but just out of curiosity, Magick does not rely on system.drawing dependencies does it (under the hood)?

**Comment by dlemstra** [comment]
The .NET Framework version of the library has a reference to `System.Drawing` to make it possible to convert a `MagickImage` to and from a `Bitmap`. I have seen a couple times that the wrong version of the binary ends up in the bin folder. You should be using the `netstandard20` version of the library.

I think I should move this to a separate library that can be used by those who really need this functionality. But that is not an easy change due to the three different versions (Q8/Q16/Q16-HDRI) of the library. This will require me to move the interfaces to a separate library so I can change the `System.Drawing` code into extension methods. Will need to think about this and come up with a plan on how to do this.

**Comment by dlemstra** [comment]
The next release will have support for `System.Drawing` with `netstandard20` but this has been moved to a separate NuGet package that you can download here: https://www.nuget.org/packages/Magick.NET.SystemDrawing/
