### ISSUE TITLE
How to get font metrics of the text drawn and how to add shadow to the text?

### ISSUE THREAD

**Issue by mchenx** [dlemstra/Magick.NET#62]
Sorry but I have two dumb questions :

I use Composite to add watermark to an image, and I want to add some text right after the watermark. However, the length of the text could vary, so I need to draw the text first and get position of the text, then I can draw the watermark according to where the text position. So is there a way to get where the test is drawn, or to get what is the width/height of the text ?

For some picture, it's close to white, so I'd like to add a gray shadow to the text so that the text has a outline and is visible.

**Comment by dlemstra** [comment]
Have you tried the `FontTypeMetrics` methods of the `MagickImage` you want to draw it on?

You can create a shadow with the `Shadow` method of the `MagickImage` class. You will then need to composite your text on top of that shadow.

**Comment by mchenx** [comment]
Hmmm, FontTypeMetrics cannot specify font size, so I'm not sure what font size is the returned TextHeight/TextWidth for

**Comment by dlemstra** [comment]
Its using the `image.Settings.FontPointsize`.

**Comment by mchenx** [comment]
That works~
