### ISSUE TITLE
image pixel getting wrapped for resize factor less (1/8x )

### ISSUE THREAD

**Issue by manjunthcm** [dlemstra/Magick.NET#621]
### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of Magick.NET
- [x ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
First of all, heartfelt thanks for the great work, both in Magick.Net and ImageMagick.
Want to bring to your notice, one of the observation that i had.
I want to resize the image to fit into the web preview. So i resize the incoming image to match the preview size.
Sometimes the image will be bit large, so to match the preview size, the resize factor becomes less than 1/8 or so. for eg, i want to resize the image of Size 360x900 pixels to 40x100 pixels.
the resized image has right hand side pixels wrapped to left hand side.
When i try samething with command line utility, the resize works perfect even with resize to 1% of actual Size.

### Steps to Reproduce
Take a bigger image of size 360/900 pixels
Set IgnoreAspectRatio to true for MagicGrometry
call resize as either, 
                    image.resize(40,100);  or image.resize(magicgeometry)

### System Configuration
i7 2.6GHz, 16GB RAM - Windows 10 Version 1809

- Magick.NET version : Magick.Net-Q16-AnyCPU - v7.16.1
- Environment (Operating system, version and so on) : Windows 10 Version 1809
- Additional information:

**Original image** :  ( Part of the image pasted here )
![image](https://user-images.githubusercontent.com/62284247/80694682-7b165000-8af2-11ea-8801-d78f86e0a217.png)

**Resized iamge from NuGet package**  :  ( Part of the image pasted here , seen at 350%, ignore the blurness )
![image](https://user-images.githubusercontent.com/62284247/80695808-0e9c5080-8af4-11ea-99e5-5348676b1efd.png)

**Reized image from command line** : ( part of the image pasted here , seen at 350 % )
command used :   _magick orig.tiff -resize 40x100 resized.tif_
[ though i get an warning here, _magick: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/1037_.
![image](https://user-images.githubusercontent.com/62284247/80696186-aac65780-8af4-11ea-87e7-b9f3e8d822df.png)

any help is highly appreciated
Thanks

**Comment by dlemstra** [comment]
Are you running this on the same machine? What happens when you set `OpenCL.IsEnabled` to `false` in the .NET code?

**Comment by manjunthcm** [comment]
Oh My Bad.. many apologies for wasting your time..
to answer your questions first..
1) yes, both were ran on Same machine
2) Setting OpenCL.IsEnabled = false, did not make any diffrence

I was _saving the resized image as a byte array RAW file_.
Unfortunately, i just used  **image.ToByteArray( )**

Since it is CMYK Tiff, now i tried doing like..
**image.ToByteArray(MagickFormat.Cmyk)**

_this resolved the problem._

Many Thanks
