### ISSUE TITLE
Error: No error code parallel reading RAW images

### ISSUE THREAD

**Issue by drakth** [dlemstra/Magick.NET#629]
### Prerequisites

- [x] I have written a descriptive issue title
- [X ] I have verified that I am using the latest version of Magick.NET
- [X ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
While trying to read canon RAW files (.CR2) in parallel using Parallel.ForEach i get the following error:

ImageMagick.MagickCoderErrorException: 'No error `F:\XXX\XXX\XXX\RAW\IMG_1688.CR2' @ error/dng.c/ReadDNGImage/467'

### Steps to Reproduce

            Parallel.ForEach(archivos, (currentFile) =>
                {
                    string rutaArchivo = Path.GetFileName(currentFile);

                    using (MagickImage image = new MagickImage(currentFile))
                    {

                        image.Thumbnail(new MagickGeometry(64, 64));
                        Bitmap bp = image.ToBitmap();
                        imglstGrande.Images.Add(bp);

                        rutas[numero] = rutaArchivo;

                        Application.DoEvents();
                        ListViewItem item = new ListViewItem();
                        item.ImageIndex = contador;
                        item.Text = rutas[contador];
                        lstImagenes.Items.Add(item);

                        numero++;
                        contador++;
                    }

                });

### System Configuration

- Magick.NET version: 7.17.0
- Environment (Operating system, version and so on): Windows 10 Visual Studio 2019
- Additional information:

**Comment by dlemstra** [comment]
Can you also reproduce the issue when you dispose the `bp` variable? And what is the most minimal program that can be used to reproduce the issue? Are you running this in 64 bit? You might hit a memory limit when you don't dispose the `bp` or read a big set of large images. And can you also include the test file or files that can be used to reproduce this?

**Comment by drakth** [comment]
Hello,
Thank you for your reply. 
Yes, it seems to be a memory issue. I added the dispose but it doesnt seem to do anything, unless im doing something wrong, the below console example program reproduces the issue. The .CR2 files should be in the same directory as the executable.

Im on a 64 Bit system. As for uploading the test files that would be a bit complicated, since im testing with 21 .CR2 files and those would be quite a big upload, but i would need to read far more files, maybe hundreds since im dealing with astrophotography files.

`        static void Main(string[] args)
        {
            string ruta = Environment.CurrentDirectory;

            DirectoryInfo di = new DirectoryInfo(ruta);
            string[] rutas = new string[di.GetFiles().Length];

            int numero = 0;
            int contador = 0;
            int totalArchivos = 0;

            contador = 0;
            totalArchivos = di.GetFiles().Length;

            string[] archivos = Directory.GetFiles(ruta, "*.cr2");

            if (archivos.Count() != 0)
            {
                Parallel.ForEach(archivos, (currentFile) =>
                {
                    string rutaArchivo = Path.GetFileName(currentFile);

                    using (MagickImage image = new MagickImage(currentFile))
                    {
                        image.Thumbnail(new MagickGeometry(64, 64));
                        Bitmap bp = image.ToBitmap();

                        rutas[numero] = rutaArchivo;

                        numero++;
                        contador++;

                        bp.Dispose();
                        image.Dispose();

                    }

                });

            }
        }`

**Comment by dlemstra** [comment]
Would it be possible to add a link to the set of images on something like onedrive or dropbox?
