### ISSUE TITLE
Make PCX background transparent in C#

### ISSUE THREAD

**Issue by devomage** [dlemstra/Magick.NET#63]
I am trying to make a PCX image background transparent.  The following code works fine, but removes portions of the image that might have the target color.  If only all the images I am working with had a magenta background - rather than some having a black background.

Any suggestions would be helpful.

`image_transparency_color = image.GetColormap(0).ToColor();
image.Transparent(image_transparency_color);`

Sample image:
https://www.dropbox.com/s/d5wpr1n6rjpqy9s/image.pcx?dl=0

**Comment by dlemstra** [comment]
You could use a different approach and use the `FloodFill` method. This changes the pixel color and all its surrounding pixels that have the same color:

```C#
using (MagickImage image = new MagickImage(@"i:\pcx\image.pcx"))
{
    image.FloodFill(MagickColors.Transparent, 0, 0);

    image.Write(@"i:\pcx\image.png");
}
```

**Comment by devomage** [comment]
Overall, I think image.Transparent worked slightly better.  If you look closely to the original example image - after applying your suggestion - it spreads into some of the image.  Here are a few more example images where you can see the results are much worse... or in the case of "cage1" - no pixels are changed.

I was thinking of trying to deal with each channel separately - but wasnt able to read/write any specific data.

Any further suggestions?  PCX seems to be fully supported - there has to be a solution.


https://www.dropbox.com/s/erif6kyisuwmykj/Barrel.pcx?dl=0
https://www.dropbox.com/s/3xyxagj4jcrwsbm/Brazier2.pcx?dl=0
https://www.dropbox.com/s/xkc5m1s7b3xrxq7/cage1.pcx?dl=0
https://www.dropbox.com/s/m5kyae5sy7l0c9w/Lantern.pcx?dl=0

**Comment by dlemstra** [comment]
I did not realize that the you consider the first color of your colormap the background color. The following code works for all the images that you provided:

```C#
using (MagickImage image = new MagickImage(@"i:\pcx\image.pcx"))
{
    // Enables the alpha channel
    image.Alpha(AlphaOption.Set);

    // Sets the first color in the colormap to transparent.
    image.SetColormap(0, MagickColors.Transparent);

    image.Write(@"i:\pcx\image.png");
}
```

**Comment by devomage** [comment]
Worked perfectly on over 400 images!  I would have never have figured it out without help.  Thank you very much.
