### ISSUE TITLE
ColorProfile not got as expected

### ISSUE THREAD

**Issue by wsion** [dlemstra/Magick.NET#633]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I've had an application using this MagickImage. MagickImage.GetColorProfile() always gave me correct result. But today I found an image file not working.
You can get a copy of this file via https://raw.githubusercontent.com/wsion/swap/master/source.jpg
Photoshop shows sRGB IEC61966-2.1(8bpc)

### Steps to Reproduce
I simply used this code snippet to reproduce the issue with the image I found.
`var image = new MagickImage(@"C:\Users\wei wei\Desktop\source.jpg");
var profile = image.GetColorProfile(); `
The variable profile is null.

### System Configuration
Windows, tried all Q8 Q16 and Q16-HDRI (AnyCpu)

- Magick.NET version: Latest which is 7.17.0
- Environment (Operating system, version and so on): Windows 10 x64 with .Net 4.5
- Additional information: None

Dear author, hope you could take a quick look. @dlemstra

**Comment by dlemstra** [comment]
I don't know why Photoshop thinks that the image has a color profile. Libjpeg cannot find an `APP2` marker in the file. Maybe it displays a default color profile?

**Comment by wsion** [comment]
@dlemstra Thanks for your quick response. Just used exif tool to check the ICC color profile, it matches your reult. So it's definitely an issue of the source image file. I'm closing this issue now.
