### ISSUE TITLE
unable to build and run on mac

### ISSUE THREAD

**Issue by msasso69** [dlemstra/Magick.NET#634]
### Description

Hello,
I'm new to Magick.NET and I'd like to use it in my application that runs on Windows (using Winforms) and on Mac (using Xamarin.Mac).
With Windows everything is working fine, but on Mac I'm not able to use it.
I tried with both v7.17.0 and v7.17.0 but when I build my application I get the following link error:

    Mono.Linker.LoadException: Error while processing references of 'VisualSEO.Spider, Version=2.1.2.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

My main doubt is that the native library that I get in my bin folder is Magick.Native-Q8-x64.dll (14.7MB) that if I'm not wrong is the Windows version and not the one for macOS. Am I correct?

What am I doing wrong?

Another question: I installed the package with NuGet choosing Magick.NET-Q8-x64 since my machine is 64 bits and in the package Magick.NET-Q8-AnyCpu I did not see any native x86 libraries for Mac. Is 64 bits the only architecture supported on Mac?

Please help
Thanks

### System Configuration

- Magick.NET version: v7.17.0 and v.7.17.0.1
- Environment (Operating system, version and so on): macOS 10.13, VS2019 for Mac, mono 6.8

**Comment by dlemstra** [comment]
Not sure why you get the `PresentationCore` reference. You should only get that reference when you use the net40 version of the library. Maybe the wrong version of the `Magick.NET-Q8-x64` library ended up in your bin folder? And yes only 64 bit is supported on Mac.

**Comment by msasso69** [comment]
Thanks for answering so soon,

yes, I'm referencing the net40 lib since I'm building with mono as net461 and I have no PresentationCore.dll anywhere. Should I have it?

These are the lines that have bin added by NuGet to the project where I use Magick:
```
    <Reference Include="Magick.NET-Q8-x64">
      <HintPath>..\packages\Magick.NET-Q8-x64.7.17.0.1\lib\net40\Magick.NET-Q8-x64.dll</HintPath>
    </Reference>
    ...
  <Import Project="..\packages\Magick.NET-Q8-x64.7.17.0.1\build\net40\Magick.NET-Q8-x64.targets" Condition="Exists('..\packages\Magick.NET-Q8-x64.7.17.0.1\build\net40\Magick.NET-Q8-x64.targets')" />
```
and the files that go to the bin folder and in the app MonoBundle are:

```
Magick.Native-Q8-x64.dll (despite I'm running on macos this looks to me the one in packages/Magick.NET-Q8-x64.7.17.0.1/runtimes/win-x64/native, it has the same size. Is it correct?)
Magick.NET-Q8-x64.dll
Magick.NET-Q8-x64.xml (this one does not go in the app MonoBundle, but I think it's ok)
```
  
I'm not a macOS expert at all, shouldn't I expect to have the following one somewhere?
```
Magick.Native-Q8-x64.dll.dylib
```

Is there a reference project that builds on mac that I can use to get "inspiration"?
Thanks again for your support

**Comment by dlemstra** [comment]
You should not need the `PresentationCore.dll` file and I really wish I had a good plan to move it out of the library to a separate library. But that is something else...

I don't own a Mac and I have not seen any other reference projects. To run this on Mac you will need to use the netstandard20 version of the library and make sure the file `runtimes/osx-x64/Magick.Native-Q8-x64.dll.dylib` ends up in your bin folder. The `.targets` file of the project probably only works on Windows.

**Comment by msasso69** [comment]
no luck :(

I referenced the dll found in netstandard20 directly as you suggested (and at least now it builds)
I then manually copied the .dylib into the .app/Contents/MonoBundle (and also into the bin folders of all the projects depending on the project where I use Magick)
but when I hit the code where I use Magick the application crashes miserably (I'm not getting an exception, directly a crash)

I also tried the dll in net20, same result: it builds but it crashes when using Magick

I'm now short of ideas

**Comment by WaterKH** [comment]
Maybe this will help? Looks like you need to take off the .dylib

https://github.com/dlemstra/Magick.NET/issues/22#issuecomment-600029537

**Comment by msasso69** [comment]
Thanks, it helped a bit. Stripping off .dylib my app does not crash anymore but hangs in the first code of Magick that I hit, and precisely in the constructor of MagickImage:
```
using (var ms = new System.IO.MemoryStream(this.Content, index: 0, count: this.Content.Length, writable: false, publiclyVisible: true))
{
	var img = new ImageMagick.MagickImage(ms);
	smPageData.Width = img.Width;
	smPageData.Height = img.Height;
}
```
The only hint that I get when I pause the debugger is the following in the thread tab:
```
9 <Thread Pool> 0xC in ImageMagick.Environment.NativeMethods.X64.Environment_Initialize
```
I even locked the access to the Magick code in order to avoid multiple threads running it concurrently but the execution gets always stuck at the constructor.
By the way, is Magick thread safe on Mac? Do I need to serialise (lock) the calls? (On Windows looks like I don't have to)

Thanks

**Comment by msasso69** [comment]
could it be that I'm missing some os dependency/module in my mac machine?
I see that freakmaxi solved a similar issue on linux (https://github.com/dlemstra/Magick.NET/issues/121) rebuilding ImageMagik with all modules. Should I do the same? Is there a guide how to do that on macos? How is ImageMagik related to Magick.NET?

**Comment by dlemstra** [comment]
That are a lot of questions. Below is an answer to each of them.

> I even locked the access to the Magick code in order to avoid multiple threads running it concurrently but the execution gets always stuck at the constructor.
By the way, is Magick thread safe on Mac? Do I need to serialise (lock) the calls? (On Windows looks like I don't have to)

The Magick.NET library is thread safe on all platforms. And spots that need a lock will have a lock inside ImageMagick or Magick.NET. I don't understand why it is stuck inside `Environment_Initialize`. There is a lock inside the C# code that calls the native library so that should not be a problem. Can you try renaming the native library back to `Magick.Native-Q8-x64.dll.dylib`?

> could it be that I'm missing some os dependency/module in my mac machine?

That is probably not the issue.

> I see that freakmaxi solved a similar issue on linux (#121) rebuilding ImageMagik with all modules. Should I do the same?

Don't think you will need to do that.

> Is there a guide how to do that on macos?

There are not macos guides on how to do that. I also don't own a mac so someone from the community will need to do that.

> How is ImageMagik related to Magick.NET?

The Magick.NET library calls the API of the ImageMagick library. The is done through a PInvoke of the methods inside the Native library.

**Comment by msasso69** [comment]
Thanks for your answers, 
good that I will not have to bother of thread concurrency nor rebuilding the whole ImageMagick stack (hopefully).
Sorry for bothering you with so many questions, but I'm not sure I got your hint of renaming the native library back to `Magick.Native-Q8-x64.dll.dylib`, before renaming it I was getting a crash, now the application hangs.
I'll try to build Magick.NET on VS2019 for Mac and see where it hangs.

**Comment by msasso69** [comment]
found the catch!
my Mac development machine is a macos10.13, but according to https://developers.google.com/speed/webp/docs/precompiled the latest libwebp supports macos10.14 and newer:
`libwebp-1.0.3-mac-10.14.tar.gz : 64-bit executables and libraries for Mac OS X 10.14 (Mojave) platform`
I moved to a macos10.15 and it works! :)
To your knowledge are there previous versions of Magicking.NET/libwep that support WebP formats in macOS <= 10.13?
One more thing: I noticed that on Mac the MagickImage .ToBitmap() is missing. Shall I open a separate issue?

**Comment by msasso69** [comment]
Side comment: I noticed that .ToBitmap() is not available in the netstandard version (I used netstandard2 only), and I guess that depends of the lack of support for System.Drawing in .NET Core, but I read that there is now a System.Drawing.Common available. Can it be used to make .ToBitmap() available also in the netstandard flavor of Magick.NET?

**Comment by dlemstra** [comment]
The `ToBitmap` method uses the `System.Drawing` code and that will not be available in the netstandard version. It might be possible to do this in the future if I move the `System.Drawing` code to a separate library. Still trying to figure out how I should make that possible.
