### ISSUE TITLE
Color Profile issue while converting EPS to JPG

### ISSUE THREAD

**Issue by SriniUday** [dlemstra/Magick.NET#639]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [X] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I am using ImageMagick-6.2.2-Q16 to convert EPS to JPG using the below arguments and getting the output with actual color profile.

convert -profile "C:\Windows\System32\spool\drivers\color\USWebCoatedSWOP.icc" -profile "C:\Windows\System32\spool\drivers\color\sRGB Color Space Profile.icm" -density 150 -resize 1000 -quality 100 "C:\Temp\EpsToJpg\Sample.eps" "C:\Temp\EpsToJpg\Sample_GPL.jpg"

But While using Magick.NET-Q16-AnyCPU with latest version 7.17.0.0, I am getting incorrect color profile as output.

### Steps to Reproduce

       static void ConvertImageUsingImageMagick()
        {
            string inputfile = @"c:\temp\EpsToJpg\Sample.eps";
            string outputfile = @"c:\temp\EpsToJpg\Sample_DLL.jpg";
            // Uses sRGB.icm, eps/pdf produce better result when you set this before loading.
            var settings = new MagickReadSettings();
            settings.ColorSpace = ColorSpace.sRGB;
            settings.Density = new Density(300);
           // Create empty image 
            using (var image = new MagickImage())
            {
                // Reads the eps image, the specified settings tell Ghostscript to create an sRGB image
                image.Read(inputfile, settings);
                image.Quality = 100;
                ColorProfile icmColorProfile = new ColorProfile(@"C:\Windows\System32\spool\drivers\color\sRGB Color Space Profile.icm");
                image.TransformColorSpace(ColorProfile.USWebCoatedSWOP, icmColorProfile);

                // Save image as jpg
                image.Write(outputfile);
            }
        }
### System Configuration

- Magick.NET version: 7.17.0.0
- Environment (Operating system, version and so on): Windows 7
[EPSTOJPG.zip](https://github.com/dlemstra/Magick.NET/files/4669009/EPSTOJPG.zip)

- Additional information:

**Comment by dlemstra** [comment]
The version that you using is not the latest, That is `7.17.0.1` and that version also includes a fix for CMYK to RGB conversion.

**Comment by dlemstra** [comment]
Can we close this @SriniUday?

**Comment by SriniUday** [comment]
> Can we close this @SriniUday?

I have updated with the new version 7.19.0, but still I am getting incorrect color in the output.

**Comment by dlemstra** [comment]
The ImageMagick that you are using is ancient and it looks like that output is incorrect. You should remove `settings.ColorSpace = ColorSpace.sRGB;` to make sure the image is read as CMYK and then perform the color transformation. And because your output format is JPEG you could also decide to keep the image as CMYK by removing the color transformation if the software that you use can understand CMYK JPEG files.

**Comment by SriniUday** [comment]
> The ImageMagick that you are using is ancient and it looks like that output is incorrect. You should remove `settings.ColorSpace = ColorSpace.sRGB;` to make sure the image is read as CMYK and then perform the color transformation. And because your output format is JPEG you could also decide to keep the image as CMYK by removing the color transformation if the software that you use can understand CMYK JPEG files.

Thanks for reviewing and getting back on this.
For loading EPS file, the setting.ColorSpace is required to load the image. Application throws exception if we discard Colorspace. Please let me know, what are the steps to get JPG from an **EPS** file with the same color output which was used in that EPS file.

**Comment by dlemstra** [comment]
What kind of exception are you getting when the Colorspace is discarded? Removing that statement should fix part of the issues with the color. And if your software understands CMYK jpeg files I would advise you to remove the call to `TransformColorSpace`.

**Comment by SriniUday** [comment]
> What kind of exception are you getting when the Colorspace is discarded? Removing that statement should fix part of the issues with the color. And if your software understands CMYK jpeg files I would advise you to remove the call to `TransformColorSpace`.

I am getting attached exception when I removed Colorspace. 
![image](https://user-images.githubusercontent.com/64850534/84737106-d928c500-afc4-11ea-8e5b-e05a1ea7d114.png)

Code Snippet:
static void ConvertImageUsingImageMagick()
        {
            string inputfile = @"c:\temp\EpsToJpg\Sample.eps";
            string outputfile = @"c:\temp\EpsToJpg\Sample_DLL.jpg";
            using (var image = new MagickImage())
            {
                image.Read(inputfile);
                image.Quality = 100;
                image.Density = new Density(300);
                image.Write(outputfile);
            }
        }

**Comment by dlemstra** [comment]
The Ghostscript version that you are using is ancient (released 18 Apr 2005). I would advise you to upgrade your version of Ghostscript to a more recent one.
