### ISSUE TITLE
SVG to PNG without antialiasing?

### ISSUE THREAD

**Issue by bwaldron** [dlemstra/Magick.NET#64]
@dlemstra, thanks so much for writing these libraries as they are a lifesaver for us.  I've been digging in the code and docs for a way to convert an SVG to raster (PNG) without antialiasing, but can not seems to find it.

The same command in command line would be:

magick +antialias test.svg test.png

Am I missing it or is it unsupported in Magick.NET?

**Comment by dlemstra** [comment]
The +antialias property sets both the `image.Settings.StrokeAntialias` and the `image.Settings.TextAntialias` property to `false`. Not sure which one (or both) you need in your situation but I think you should be able to figure that out 😄.

**Comment by bwaldron** [comment]
Thanks @dlemstra.  That worked for me.  Similarly, is there a way to turn off dithering (+dithering)?

**Comment by dlemstra** [comment]
That is the correct wat do disable dithering when doing quantization.

**Comment by dlemstra** [comment]
Do you need more help @bwaldron or can we close this issue?
