### ISSUE TITLE
MagickImage.Interpolate seems to have no effect on resize

### ISSUE THREAD

**Issue by tonyp7** [dlemstra/Magick.NET#642]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
AdaptiveResize says "Resize using the Mesh interpolation". If I do a manual "Resize" and set PixelInterpolateMethod to PixelInterpolateMethod.Mesh, I should expect the same result. But it does not seem to work. In fact, it looks like setting a value to an ImageMagick Interpolate does nothing at all.

### Steps to Reproduce
Here's a test code that resize an image in 3 different modes and display it in 3 different pictureboxes. Picturebox image is set to "Normal" as to not generate its own interp.

```csharp
MagickGeometry geo = new MagickGeometry(280, 280);
geo.IgnoreAspectRatio = true;

MagickImage imgAdaptive = new MagickImage(Properties.Resources.gray_asphalt_road_between_green_trees_3523512 );
MagickImage imgMeshResize = (MagickImage)imgAdaptive.Clone();
MagickImage imgBilinearResize = (MagickImage)imgAdaptive.Clone();

imgAdaptive.AdaptiveResize(geo);
pictureBoxAdaptiveResize.Image = imgAdaptive.ToBitmap();

imgMeshResize.Interpolate = PixelInterpolateMethod.Mesh;
imgMeshResize.Resize(geo);
pictureBoxMesh.Image = imgMeshResize.ToBitmap();

imgBilinearResize.Interpolate = PixelInterpolateMethod.Bilinear;
imgBilinearResize.Resize(geo);
pictureBoxBilinear.Image = imgBilinearResize.ToBitmap();
```

![Image](https://idyl.io/wp-content/uploads/2020/05/magickimage_interp.png)

[Souce image used](https://www.pexels.com/photo/gray-asphalt-road-between-green-trees-3523512)

[Link to the entire VS2019 project for convenience](https://idyl.io/WindowsFormsApp1.zip)

### System Configuration

- Magick.NET version: 7.17.0.1
- Environment (Operating system, version and so on): Win10, VS2019, Magick.NET added through nuget.

**Comment by dlemstra** [comment]
It always surprised me but it seems that you found a missing feature in the Magick.NET library. There is a resize operation that uses the `Interpolate` option but it requires a specific call. On the command line you would need to do a `-interpolative-resize` instead of a `-resize` to make this work. In the next version of Magick.NET I will either add an `InterpolativeResize` or an extra overload to the `Resize` method. Have not decided which one I prefer. Would love to know where you would have expected it.

**Comment by tonyp7** [comment]
Thanks for replying and taking this in so quickly!

If it were me, I would not add a InterpolativeResize method and I would expect Resize to work with whatever value MagickImage.Interpolate was set to (if not what is the point of having the property exposed to begin with?)

However, if you are telling me that in the native library it is a separate operation, then I believe for the sake of keeping the .NET library as close as possible to the original ImageMagick, you should add this method.

**Comment by dlemstra** [comment]
`InterpolativeResize` has been added to the `MagickImage` class in the latest release.

**Comment by tomasr78** [comment]
How to use InterpolativeResize with my code below https://github.com/dlemstra/Magick.NET/discussions/810 when converting PDF to Image?

I have tried to use this way but the produced PNG file size is the same.

```
var defines = new PdfReadDefines() { Interpolate = true };
magickReadSettings.Defines = defines;
```
