### ISSUE TITLE
Replace color

### ISSUE THREAD

**Issue by jueqing1015** [dlemstra/Magick.NET#643]
Example: I need to replace all the red in a picture, including some similar ones, with white

The original ImageMagick has a similar operation, but in the MAGICK.NET Not found in
convert 2.jpg -alpha set -channel RGBA -fuzz 10% -fill "rgb(0,0,0)" -opaque "rgb(255,255,255)" new.png
Is it possible to integrate this function?

**Comment by dlemstra** [comment]
Your command would translate to this:

```C#
using (var image = new MagickImage(" 2.jpg:")) // 2.jpg
{
    image.Alpha(AlphaOption.Set); // -alpha set
    image.ColorFuzz = new Percentage(10); // -fuzz 10%
    image.Opaque(
        target: MagickColors.White, // -opaque "rgb(255,255,255)"
        fill: MagickColors.Black); // -fill "rgb(0,0,0)"
    image.Write("new.png"); // new.png
}
```

Not sure why you need the `-channel RGBA` option though.
