### ISSUE TITLE
Type initializer for NativeMagickSettings can't find native dll (Windows)

### ISSUE THREAD

**Issue by Regenhardt** [dlemstra/Magick.NET#648]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

At runtime, the type initializer for NativeMagickSettings throws an exception, as it can not find Magick.Native-Q16-x64.dll. Same exception as #556 .
I'm on Windows 10 x64. 
I installed Magick.NET-Q16-x64 in my netstandard13 library and use it from a netFx462 project.
The bin directory contains all DLLs. The Magick.NET-Q16-x64.dll wasn't copied on build, so I copied it manually.

This is the code calling Magick.NET:

        using var image = new MagickImage(fileContent);
        using var stream = new MemoryStream();
        image.Write(stream, MagickFormat.Pdfa);
        return stream.ToArray();

Any idea what I'm doing wrong?

### Steps to Reproduce

netFx462 project on Windows, install Magick.NET-Q16-x64 via NuGet, try to convert image to pdf.

### System Configuration

- Magick.NET version: Magick.NET-Q16-x64 v7.17.0.1
- Environment: Windows 10 x64 1909

**Comment by dlemstra** [comment]
Can you share a sample of your project somewhere so I can reproduce this issue? And this is not related to your error message bu did you also install Ghostscript?

**Comment by dlemstra** [comment]
Did you resolve this issue @Regenhardt and can we close it?

**Comment by Regenhardt** [comment]
Turns out the dependency isn't copied to bin on build. I got an open issue on the dotnet repo now.
