### ISSUE TITLE
Unable to decompress the jpeg file.

### ISSUE THREAD

**Issue by Gormy** [dlemstra/Magick.NET#65]
I catch two errors ('Unable to decompress the jpeg file.' and 'Unable to compress the jpeg file.') for all my .jpg, .jpeg files on my Windows Server 2012 R2.

But on another machines all works fine.

**Comment by dlemstra** [comment]
Do you have a sample file and a small code sample that I can use to reproduce your issue? And what is the exact error message that you are receiving?

**Comment by Gormy** [comment]
Screenshot:
http://prntscr.com/foolro

On my notebook all works fine. On Windows Server 2012 R2 not.
[ImagesCompress.zip](https://github.com/dlemstra/Magick.NET/files/1104945/ImagesCompress.zip)

**Comment by Gormy** [comment]
The issue reproduce only on one machine. Png files compress without error.

**Comment by Gormy** [comment]
I fix this issue use only english letters in temp path (I switch Path.GetTempFileName() to my a function) to save a temp file for JpegOptimization.

**Comment by dlemstra** [comment]
What kind of characters did you have in the path? Would love to get this fixed.

**Comment by Gormy** [comment]
I have path to the temp file as C:\Users\Администратор\AppData\Local\Temp.
And I catch error if try compress any files with not english letters.

**Comment by dlemstra** [comment]
I tried to run this:
```
var optimizer = new ImageOptimizer();
optimizer.Compress(@"i:\Администратор\logo.png");
```
And it worked without any issues

**Comment by Gormy** [comment]
Try on .jpg file. Issue reproduce only with .jpg, .jpeg files.

**Comment by dlemstra** [comment]
Aww of course sorry. I am going to reopen this issue because this is a bug. You should be able to read the file.
