### ISSUE TITLE
Change image text color and Text deepening

### ISSUE THREAD

**Issue by jueqing1015** [dlemstra/Magick.NET#651]
Sorry, because my English is not very good, the problem description may be a little fluent.
I will describe my problem again
I now want to replace the color of the text part of an image with another color
But the color of the text part is not uniform black. What should I do with this question?
The following is a demonstration picture
It can be seen that no matter what color the text part of the image is, it can become red
https://user-images.githubusercontent.com/65677359/82962572-2aabe880-9ff3-11ea-995f-0d81f0c37c54.jpg
https://user-images.githubusercontent.com/65677359/82962577-2da6d900-9ff3-11ea-9a4e-36e408594f82.jpg
Sorry, because I do n’t know what ’s wrong here, the image cannot be uploaded

**Comment by dlemstra** [comment]
If you want to replace a color of an image you will replace all the occurrences of that color and not just the text. If you know the area where the text is and that area does not contain other pixels in that same color you might be able to replace the color. But because you have black in different shades this also won't be an easy task.

**Comment by jueqing1015** [comment]
I found a way to deal with it. So how do you deepen the color?
Is that I want to emphasize the dark color in the image to make it clearer

**Comment by dlemstra** [comment]
Maybe @fmw42 can help us with this? I do think that you will need to explain in a bit more detail what you want to accomplish though and show a sample image.

**Comment by jueqing1015** [comment]
![1](https://user-images.githubusercontent.com/65677359/83611894-36c81500-a5b4-11ea-8946-ac863284a7ca.jpg)
![1 - 副本](https://user-images.githubusercontent.com/65677359/83611929-434c6d80-a5b4-11ea-89d7-3c0a3c70a47e.jpg)
![1](https://user-images.githubusercontent.com/65677359/83611936-48a9b800-a5b4-11ea-8e73-c6848bca59e8.jpg)
![1 - 副本](https://user-images.githubusercontent.com/65677359/83611942-4ba4a880-a5b4-11ea-9828-17515b40eb44.jpg)
You can see that the two parts of the text in the image are very different. I just want to implement such a function
Is there the following function? This is the function of PHOTOSHOP
![3](https://user-images.githubusercontent.com/65677359/83612115-89a1cc80-a5b4-11ea-9e7f-34cf9809417a.jpg)

**Comment by fmw42** [comment]
See -level at https://imagemagick.org/script/command-line-options.php#level and https://imagemagick.org/Usage/color_mods/#levels.  It is like the PS tool above for setting the input low and high values and the middle (gamma) value. To set the output values other than 0 and 255, you have to use +level in addition to -level. Clip values can be added using -contrast-stretch. See https://imagemagick.org/script/command-line-options.php#contrast-stretch

**Comment by jueqing1015** [comment]
@fmw42 @dlemstra 
I want to adjust to the following parameters. How to adjust with MAGICK.NET
![0000](https://user-images.githubusercontent.com/65677359/83737274-58450180-a685-11ea-8c7d-68c7bbbf97ef.jpg)

**Comment by fmw42** [comment]
Sorry, I do not use Magick.Net.  But in command line that would be

`convert image -level 5.88%x87.45%x0.82 result`

where the numbers in percent are the values divided by 255 for the first two, i.e. 15/255 and 223/255 assuming you are on Q16 ImageMagick. If on Q8 ImageMagick, you can use your exact values of 15 and 223.

**Comment by dlemstra** [comment]
In Magick.NET you can do this:

```C#`
var blackPointPercentage = new Percentage(5.88);
var whitePointPercentage = new Percentag (87.45);
var gamma = 0.82;
image.Level(blackPointPercentage, whitePointPercentage, gamma);
```

**Comment by jueqing1015** [comment]
@fmw42 @dlemstra 
Another question is whether such image effects can be processed,
My understanding may be to enlarge all the pixels of the image. I don't know if my understanding is correct.
If my understanding is correct, how to operate it with MAGICK.NET?
https://user-images.githubusercontent.com/65677359/83611894-36c81500-a5b4-11ea-8946-ac863284a7ca.jpg
https://user-images.githubusercontent.com/65677359/83611942-4ba4a880-a5b4-11ea-9828-17515b40eb44.jpg

**Comment by fmw42** [comment]
I do not understand what you want? Please explain in words what the effect is.

**Comment by jueqing1015** [comment]
I want to process the picture 1 into the effect of picture 2
https://user-images.githubusercontent.com/65677359/83611942-4ba4a880-a5b4-11ea-9828-17515b40eb44.jpg
https://user-images.githubusercontent.com/65677359/83611894-36c81500-a5b4-11ea-8946-ac863284a7ca.jpg

**Comment by fmw42** [comment]
No, I do not know how that could be done. ImageMagick is a raster processor and does not know about text characters.
