### ISSUE TITLE
error while converting memory stream to image 

### ISSUE THREAD

**Issue by kp1007** [dlemstra/Magick.NET#659]
Invalid input: Unexpected end of file: Extent in iloc box references data outside of file bounds (points to file position 487380)
 `' @ error/heic.c/IsHeifSuccess/136

files which are near 1.5 mb or more size is not processed with this code, i want to convert them from stream 

```C#
using (var image = new MagickImage(context.Request.Files[0].InputStream))
{
    image.Format = MagickFormat.Jpg;
    // Create byte array that contains a jpeg file
    byte[] data = image.ToByteArray();

    Stream stream = new MemoryStream(data);
    var fileStream = stream;
    var length = stream.Length;

    var fileByteArray = new byte[length];
    fileStream.Read(fileByteArray, 0, (int)length);
}
```

**Comment by kp1007** [comment]
actually that issue because file  size is reduced before process, here I posted two heic files 
one is original and second  is it's  lower size file.

these both files converted to jpg using https://imazing.com/heic
but reduce.heic file is not perform using ImageMagick 

[heic.zip](https://github.com/dlemstra/Magick.NET/files/4763709/heic.zip)

**Comment by dlemstra** [comment]
The process that is used to reduce the file size apparently breaks something. The library that we use is strict abouts its input and raises an exception when the input file is invalid. I suspect that the imazing library decides to ignore the fact that the file is invalid.
