### ISSUE TITLE
DIY Ordered Dither Threshold Maps

### ISSUE THREAD

**Issue by 0kuwa** [dlemstra/Magick.NET#66]
I am using "Magick.NET" from "NuGet".
I would like to convert a grayscale image to a screen tone image I created.
(Convert to monochrome screen tone)
I do not know how to read "xml" created by me.

I do not know the method of "DIY Ordered Dither Threshold Maps".
http://www.imagemagick.org/Usage/quantize/#diy_threshold

Please tell me.

**Comment by dlemstra** [comment]
Do you have an xml example?

**Comment by 0kuwa** [comment]
Thank you.

With "600 dpi" and "1200 dpi" images
Screen lines "65, 70, 85, 120, 133"
Screen angle "45, 25"
I want to generate a screen tone that combines screen lines and screen angles.
I would like to have a result close to Photoshop.
I am planning to create xml from now on.

Example:
input image(600dpi)
![600dpi_gray](https://user-images.githubusercontent.com/29696513/27672587-e41c3b20-5cd6-11e7-8620-e846154deaa9.png)

out mono image(600dpi)
screen lines"65"/screen angle"45"
![600dpi_mono65l45a](https://user-images.githubusercontent.com/29696513/27672603-fec72bb0-5cd6-11e7-873c-d0ac66fe126e.png)

out mono image(600dpi)
screen lines"65"/screen angle"25"
![600dpi_mono65l25a](https://user-images.githubusercontent.com/29696513/27672615-11c340f0-5cd7-11e7-9510-b5a69590070b.png)

**Comment by dlemstra** [comment]
Do you have an example of the `threshold.xml` file that you used to create those image?

**Comment by 0kuwa** [comment]
'Thresholds.xml'
I will attach the things in the process of making.
I am not convinced with the screen tone pattern I have created by myself.
You may create hundreds of patterns, including angles and 32 x 32.

I am happy that I can load "thresholds.xml" by myself.

[ScreenToneTest.zip](https://github.com/dlemstra/Magick.NET/files/1118379/ScreenToneTest.zip)

**Comment by 0kuwa** [comment]
I am creating "thresholds.xml".
We were able to create a satisfactory "thresholds.xml" pattern to some extent.
I have not made a pattern of angles yet.
I am planning to create it later.
I'd like to reading "thresholds.xml" using "Magick.Net".
I do not know how to reading "xml" created by me.
Please tell me.
[ScreenToneTest2.zip](https://github.com/dlemstra/Magick.NET/files/1121106/ScreenToneTest2.zip)

**Comment by 0kuwa** [comment]
I am creating "thresholds.xml".
We were able to create a satisfactory "thresholds.xml" pattern to some extent.
I have not made a pattern of angles yet.
I am planning to create it later.
I'd like to reading "thresholds.xml" using "Magick.Net".
I do not know how to reading "xml" created by me.
Please tell me.

[ScreenToneTest2.zip](https://github.com/dlemstra/Magick.NET/files/1121110/ScreenToneTest2.zip)

**Comment by 0kuwa** [comment]
I am creating "thresholds.xml".
We were able to create a satisfactory "thresholds.xml" pattern to some extent.
I have not made a pattern of angles yet.
I am planning to create it later.
I'd like to reading "thresholds.xml" using "Magick.Net".
I do not know how to reading "xml" created by me.
Please tell me.

[ScreenToneTest2.zip](https://github.com/dlemstra/Magick.NET/files/1121115/ScreenToneTest2.zip)

**Comment by dlemstra** [comment]
What you could do for now is to call `MagickNET.Initialize` at the start of your program. You will need to copy all the xml files from this folder: https://github.com/dlemstra/Magick.NET/tree/master/Source/Magick.NET.Native/Resources/xml and replace the `thresholds.xml` file with your own version. I am working on some changes to make this easier and that will also include documentation that explains how you could use it. I will leave this issue open and leave a comment here when that is done.

**Comment by 0kuwa** [comment]
Great!
It worked correctly with "MagickNET.Initialize"!
Thank you!

**Comment by dlemstra** [comment]
I just published a new release that includes an extra option to initialize the ImageMagick library. You can find it here: https://github.com/dlemstra/Magick.NET/blob/master/Documentation/Initialization.md
