### ISSUE TITLE
Missing Shadow Interfaces

### ISSUE THREAD

**Issue by danpetitt** [dlemstra/Magick.NET#663]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Upgrading to latest version causes compile errors due to missing `Shadow` function declarations in `IMagickImage.cs`

### Steps to Reproduce
Try to call `image.Shadow(int x, int y, double sigma, Percentage alpha, MagickColor color)` and VS errors with missing definition.

However the code exists in the [implementation file](https://github.com/dlemstra/Magick.NET/blob/80ae33a6a6f7bbaa46668467f85c7584ef33b8b0/src/Magick.NET/Shared/MagickImage.cs#L5674) but the [interface is missing](https://github.com/dlemstra/Magick.NET/blob/80ae33a6a6f7bbaa46668467f85c7584ef33b8b0/src/Magick.NET.Core/IMagickImage.cs#L2437).

### System Configuration
- VS2019
- .NET Framework 4.6
- Magick.NET version: 7.19.0
- Environment (Operating system, version and so on): Windows 10 Pro 2004

**Comment by dlemstra** [comment]
This is not defined in the `IMagickImage` interface but in the `IMagickImage<TQuantumType>` interface. This separation had to be made to make it possible to move the `System.Drawing` code to a separate library.

**Comment by danpetitt** [comment]
Thanks again Dirk
