### ISSUE TITLE
Missing Composite Interface

### ISSUE THREAD

**Issue by danpetitt** [dlemstra/Magick.NET#664]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Upgrading to latest version causes compile errors due to missing `Composite` function declaration in `IMagickImage.cs`

### Steps to Reproduce
Try to call `image.Compose(image)` and VS errors with missing definition.

However the code exists in the [implementation file](https://github.com/dlemstra/Magick.NET/blob/master/src/Magick.NET/Shared/MagickImage.cs#L1839) but the interface is missing completely.

### System Configuration
- VS2019
- .NET Framework 4.6
- Magick.NET version: 7.19.0
- Environment (Operating system, version and so on): Windows 10 Pro 2004

**Comment by dlemstra** [comment]
This is not defined in the `IMagickImage` interface but in the `IMagickImage<TQuantumType>` interface. This separation had to be made to make it possible to move the `System.Drawing` code to a separate library.

**Comment by danpetitt** [comment]
Thanks Dirk; I spotted that and was just about to update once i got everything building again 👍  sorry to waste your time

**Comment by dlemstra** [comment]
No worries, this will probably help someone in the future.
