### ISSUE TITLE
Load image

### ISSUE THREAD

**Issue by jueqing1015** [dlemstra/Magick.NET#668]
Whether to consider adding a new category in NEW MAGICKIMAGE()
new magickimage(new MagickGeometry());
This method is relative to
Can be applied, only need to open a part of the image, or need to crop a part of the image, and no longer need two steps to achieve the effect, you can achieve the effect in one step

**Comment by dlemstra** [comment]
I don't think that this should be added to the library. With the current API you are already able to do what you need to accomplish And yes that means some extra typing on your side but you could always decide to hide the logic inside an extension method if you need to use the same logic at multiple places.
