### ISSUE TITLE
Color Profile: threw an exception of type 'System.ArgumentNullException'

### ISSUE THREAD

**Issue by MatthiasJost** [dlemstra/Magick.NET#67]
I have this exception in my new environment.

ImageMagick.ColorProfile.SRGB = 'ImageMagick.ColorProfile.SRGB' threw an exception of type 'System.ArgumentNullException'

Do you know what that could be?

I ues Visual Studio 2017 (15.2) with .NET Core 1.1. I used the same code with an older version of VS and .NET Core before.

**Comment by dlemstra** [comment]
I think I would need a bit more information. Not sure if this is caused by your code or by Magick.NET. Maybe we can take a look at this together on Skype? I might be available tonight or tomorrow.

**Comment by MatthiasJost** [comment]
@dlemstra Thank you.

**Comment by MatthiasJost** [comment]
I tested the new version and it works! Thank you.
