### ISSUE TITLE
"Null count for \"XMLPacket\" (type 1, writecount -3, passcount 1)" error when trying to load a TIF file

### ISSUE THREAD

**Issue by ionutboanta-walkerscott** [dlemstra/Magick.NET#672]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I have a TIF image that has the "XMLPacket" field set as "0". I'm not sure how it ended up that way, nor do I have control over it in order to fix the header (the file is read from an Azure Blob stream).

When I try to Ping/load it, I get the following exception:

"Null count for "XMLPacket" (type 1, writecount -3, passcount 1). `_TIFFVSetField' @ error/tiff.c/TIFFErrors/664\".

### Steps to Reproduce

Try to load a TIF file with a bad "XMLPacket" field (in my case its value is "0")

### System Configuration

- Magick.NET version: Magick.NET-Q8-x64. I tried with both 7.14.3 (currently used) and 7.19.0.1
- Environment (Operating system, version and so on): Windows 10, 64 bits
- Additional information: The code is implemented in an Azure Function. The issue occurs both locally and when deployed

**Comment by dlemstra** [comment]
This is probably happening because your file is corrupt. Thanks for testing the most recent version because that could include a change to the tiff library. If you can share your file i can confirm that it is corrupt.

**Comment by ionutboanta-walkerscott** [comment]
@dlemstra Sorry, I cannot really share the file as it is not public. Would sharing some of the Exif data be enough?
The thing is that the image can be opened in any Photo Viewer.
Also, the final purpose of this is to generate a thumbnail of the file. I checked some other thumbnailing tool (https://www.fookes.com/easy-thumbnails) and the image gets loaded and the thumbnail generated.

I guess another question would be: Is there any way to ignore the "XMLPacket" tag when loading/Pinging the image if it would throw an error?

**Comment by dlemstra** [comment]
We are using a library called libtiff that is very strict about it's input and does a lot of checks to make sure the file is correct. Other programs are less strict (for example Photo Viewer) and will open the image without making sure that the file is correct. I don't think you can ignore this. Feel free to send a link to the file by email so I can take a better look at the file.

**Comment by ionutboanta-walkerscott** [comment]
@dlemstra Sorry, I cannot share the image privately either.
Would sharing its Exif metadata be helpful in any way?

**Comment by dlemstra** [comment]
The problem is the file and it is very likely that it is corrupt. I cannot help you with this without a file.
