### ISSUE TITLE
DllNotFoundException on Windows Server 2008, is there a new dependency? 

### ISSUE THREAD

**Issue by catester** [dlemstra/Magick.NET#675]
Hi,
I tested v7.20.0 on Windows Server 2008 and got this error:

```
[DllNotFoundException: Unable to load DLL 'Magick.Native-Q8-x64.dll': The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)]
.Environment_Initialize() +0
.Initialize() +89
```

The same code works on Windows Server 2012. Is there a new dependency like VisualC++ runtime? Though I could not see it in Dependency Walker. Or maybe ImageMagick native started to use new Windows APIs that were missing in Win2008/Win7?

Note that there were no problems with v7.17.0.1, something must be changed after v7.18 or so.

**Comment by dlemstra** [comment]
The only new dependency starting with 7.18 is the new `Core` library that has been added. I don't know why you would get this error though. You don't need the VisualC++ runtime anymore unless you are using the OpenMP version.

**Comment by catester** [comment]
Ok I will re-examine it. Maybe it's similar to #366 or some function not existing in older Windows:

> My issue was that I was using "RegGetValue" which is only available on Vista+.

https://stackoverflow.com/a/8912684/451632

**Comment by catester** [comment]
I noticed there is a new import `IPHLPAPI.DLL` in new version of Magic.Native DLL, though MS docs say the called functions from this DLL are supported on Win2008.

I am not saying it's necessarily a function in `IPHLPAPI.DLL`, it could be a function in existing imports that is not supported on Win2008 but recently added to Magic.Native source (or to some its dependency's source)

Here is a screenshot of Dependency Walker of each version side by side (Magic.Native v7.0.10.13 works on Win2008, v7.0.10.21 does not):

![image](https://user-images.githubusercontent.com/3868141/85563868-7378b080-b636-11ea-84bd-82f7408be5f7.png)

I know Win2008 is very old but for legacy reasons I still keep it at supported list.

**Comment by catester** [comment]
Ok, I figured out the problem. I ran Dependency Walker directly on the problem virtual machine (win2008)

Here is the screenshot:
![image](https://user-images.githubusercontent.com/3868141/85584504-dfafe000-b647-11ea-8211-67c1d48bdc8e.png)

So these functions only exist on 

Minimum supported client | Windows 7 [desktop apps \| UWP apps]
-- | --
Minimum supported server | Windows Server 2008 R2 [desktop apps \| UWP apps]

https://docs.microsoft.com/en-us/windows/win32/api/errhandlingapi/nf-errhandlingapi-setthreaderrormode
https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-tryacquiresrwlockexclusive

and I was testing on an early version of Windows Server 2008 (SP1 not R2). This could help future surfers.

**Comment by dlemstra** [comment]
Does this mean that your issue is resolved by upgrading to R2 and can we close this issue?

**Comment by catester** [comment]
Of course I am not using Windows Server 2008 myself so it's not a matter of me upgrading, it's about deploying a tool that supports a minimum OS. That was one of the virtual machines I was testing. So know that after Magic.Native v7.0.10.13 (Magick.NET v7.17.0.1), your minimum supported OS is changed.

I found this:

> On January 14, 2020, support for Windows Server 2008 and 2008 R2 ended.

So maybe we should not care about it at all, I am closing the issue.
