### ISSUE TITLE
Duplicate types in Magick.NET.Core.dll and Magick.NET-Q8-AnyCPU.dll

### ISSUE THREAD

**Issue by catester** [dlemstra/Magick.NET#676]
I noticed that there are some duplicate types/members since you separated the DLLs.
Some of us may like to merge DLLs to get a single deployable DLL and these duplicates cause conflicts (e.g. when using ILRepack).

For example, `ImageMagick.IMagickImageExtensions` (static class for extension methods) is found in Magick.NET.Core.dll and Magick.NET-Q8-AnyCPU.dll.

Here are other duplicates I noticed:

```
ImageMagick.ByteConverter
ImageMagick.FileHelper
ImageMagick.Bytes
ImageMagick.EnumHelper
ImageMagick.Throw
ImageMagick.TypeHelper
ImageMagick.ValidatedNotNullAttribute
```

Maybe the ones in Magick.NET.Core.dll could be used or extended when necessary?

**Comment by dlemstra** [comment]
Those classes are duplicated in all those libraries to avoid using `InternalsVisibleTo`. I was not aware of this use case. The next release that will be poblished very soon will switch to using `InternalsVisibleTo`.

**Comment by catester** [comment]
Ok thanks but beware with `InternalsVisibleTo`, when you sign assemblies it stops working and you need to update the attribute so I always avoid it.

By the way if those classed are internal, there would be no problem merging as they could be renamed.
However at least for `ImageMagick.IMagickImageExtensions`, I noticed it's a public class and as far as I know 2 public classes in 2 different assemblies would not be useful for consumers due to scoping anyway.

The actual problem I had was, even when the merge was successful through renaming, I would get duplicate interface errors when obfuscating. So it appears to be some conflicts.

**Comment by dlemstra** [comment]
It seems I misunderstood you that you had the same issue with those internal classes. If is only the public classes we could resolve this issues by renaming the classes. Or am I missing something here?

**Comment by dlemstra** [comment]
Can you give it another try with the release that was just published (7.20.0.1)?

**Comment by catester** [comment]
Ok I can workaround merge problem by passing `/union` parameter to ILRepack.

I see that you made `IMagickImageExtensions` internal in 7.20.0.1.

I digged further and my actual problem is this:

There are method signatures like these:
```
IPixelCollection<TQuantumType>.SetArea(int x, int y, int width, int height, byte[] values)
IPixelCollection<TQuantumType>.SetArea(int x, int y, int width, int height, TQuantumType[] values)
```

Then there is this
```
PixelCollection : IPixelCollection<byte>
```

So when this interface is inherited there are duplicate method signatures because `TQuantumType` becomes `byte`.
So if you process the assembly in some way, for example weawing or obfuscating, the VTable analyzers complain about duplicate signatures.

Note that this is not a runtime problem. It runs perfectly fine. So if you must have signatures with `byte` along with `TQuantumType` then you can ignore my issue, I can workaround by modifying VTable analyzer to skip duplicate signatures.

**Comment by dlemstra** [comment]
This appears to be a mistake in my code. There is an old "quantum" check that was copied to the Core library and should not be there. I think I will need to rename the `SetPixels` and `SetArea` methods that have a non quantum overload.

**Comment by dlemstra** [comment]
The new release has just been published @catester. Are the duplicate names now gone?
