### ISSUE TITLE
Magick.Net.Core 

### ISSUE THREAD

**Issue by meysamSamanpour** [dlemstra/Magick.NET#68]
Hi,  
I was using the Magick.net.core but today I realized that you unlisted this package. Is there any problem ? Actually I wanted to ask a question about the performance of this version which I found slower than the Magick.net, and then I saw in the nuget page that you have unlisted that package. 

Thanks, 
Meysam

**Comment by meysamSamanpour** [comment]
I just now read in other issues that you moved the package into the normal one. Sorry for raising that issue. thanks.

**Comment by dlemstra** [comment]
No problem you can check the release notes here: https://github.com/dlemstra/Magick.NET/releases 😃
