### ISSUE TITLE
Can't install Magick.NET through NuGet

### ISSUE THREAD

**Issue by Erapchu** [dlemstra/Magick.NET#682]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Completely can't use only this NuGet (i'm already try all versions) in ANY Visual Studio solution. While installing, window with NuGet list is freezing and can't be used more. At result, NuGet is not installed. I tried to download NuGet package manually and install through package-manger console - doesn't help.

### Steps to Reproduce

Just try to install any of those NuGet packages in any empty solution.

### System Configuration

- Magick.NET version: Any. I've already tried all versions.
- Environment (Operating system, version and so on): Windows 10 Home, Visual Studio 2019 with latest update, .Net Core 3.1.0.
- Additional information:

**Comment by Insire** [comment]
> Just try to install any of those NuGet packages in any empty solution.
assuming you meant project file here, i just tried to install ``Magick.NET-Q8-AnyCPU 7.20.0.1`` and that works as expected.

![grafik](https://user-images.githubusercontent.com/11455827/85917364-e44be280-b859-11ea-875e-731fd84ae405.png)

**Comment by Erapchu** [comment]
> > Just try to install any of those NuGet packages in any empty solution.
> 
> assuming you meant project file here, i just tried to install `Magick.NET-Q8-AnyCPU 7.20.0.1` and that works as expected.
> 
> ![grafik](https://user-images.githubusercontent.com/11455827/85917364-e44be280-b859-11ea-875e-731fd84ae405.png)

Ok, on my side this is not possible. 
![image](https://user-images.githubusercontent.com/37536541/85917499-b7f98b80-b884-11ea-8b72-2f4be70c3b60.png)
After start installing in any project (and only this - Magick.NET!) NuGet package (WPF, Console or others) as you can see that in output window installation process stopped and freeze NuGet browser window. I just can't use it anyway. What problem is it?

**Comment by Insire** [comment]
Here are some things you can try:
- download the nuget exe manually and see if you can fetch packages with that via cli
``nuget.exe Install-Package Magick.NET-Q8-AnyCPU -ProjectName ConsoleProject1``
- maybe try another PC or VM

**Comment by Erapchu** [comment]
Ok, thank you. I'll try it via nuget.exe and on VM.

**Comment by skymeson** [comment]
I'm also having an issue. Using Visual Studio 2019. Getting an error reading resources. 

![image_magick](https://user-images.githubusercontent.com/2335758/86195655-6c164300-bb1f-11ea-915d-f4ab56338b5b.PNG)
