### ISSUE TITLE
Add .netcoreapp3.0 as TargetFramework to Magick.NET.SystemWindowsMedia

### ISSUE THREAD

**Issue by Insire** [dlemstra/Magick.NET#683]
### Is your feature request related to a problem? Please describe
I have an application thats targeting netcoreapp3.1 and i'm using ``Magick.NET.SystemWindowsMedia`` version ``1.0.2`` in there. Nuget generates this warning 

```Severity	Code	Description	Project	File	Line	Suppression State
Warning	NU1701	Package 'Magick.NET.SystemWindowsMedia 1.0.2' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.	MvvmScarletToolkit.Samples	E:\Code\MvvmScarletToolkit\src\MvvmScarletToolkit.Samples\MvvmScarletToolkit.Samples.csproj	1	
```

### Describe the solution you'd like
I'd like to see .netcoreapp3.0 [added ](https://github.com/dlemstra/Magick.NET/blob/master/src/Magick.NET.SystemWindowsMedia/Magick.NET.SystemWindowsMedia.csproj#L3)as TargetFramework to Magick.NET.SystemWindowsMedia
```xml
<TargetFrameworks>net40;netcoreapp3.0</TargetFrameworks>
```

### Describe alternatives you've considered
I could suppress the warning.

### Additional context
The repository in question can be found [here](https://github.com/Insire/MvvmScarletToolkit).

**Comment by dlemstra** [comment]
Thanks for the link to your repository. It helped me figure out why I was unable to add support for `netcoreapp3.0` before. I had to change the project `Sdk` from `Microsoft.NET.Sdk` to `Microsoft.NET.Sdk.WindowsDesktop`. And I also had to add `UseWPF` to the properties group. Support for `netcoreapp3.0` will become available in the next release.
