### ISSUE TITLE
How do I properly add text to an image and center it

### ISSUE THREAD

**Issue by PtrStruct** [dlemstra/Magick.NET#688]
So I'm trying to create something like this, but I can't seem to get it to work.
[https://i.imgur.com/8rqJ1sW.png](https://i.imgur.com/8rqJ1sW.png)

I tried using the example that was in the documentation but using `TextGravity = Gravity.Center` doesn't actually seem to center anything.

This is what I have so far.
```
var textToWrite = "INSERT TEXT INTO IMAGE";
var readSettings = new MagickReadSettings()
{
    Font = "Consolas",
    TextGravity = Gravity.Center,
    BackgroundColor = MagickColors.Transparent,
    Height = 250, // height of text box
    Width = 300 // width of text box
};

using (var image = new MagickImage(@"C:/PahToFile.png"))
{
    using (var caption = new MagickImage($"label:{textToWrite}", readSettings))
    {
        // Add the caption layer on top of the background image
        // at position 590,450
        image.Composite(caption, 0, 0, CompositeOperator.Over);
        Image.ImageBase64 = ImageProcessor.ImageToBase64(image.ToByteArray());
        //image.Write(@"C:/PahToFile.png");
    }
}

```
And my approach was going to be.. Center both the texts vertically and horizontally but then maybe add some margin in between? I honestly have no idea what approach I should go for.

**Comment by dlemstra** [comment]
You will need to do `image.Composite(caption, Gravity.Center, CompositeOperator.Over);` instead.
