### ISSUE TITLE
Cannot new  the MagickSettings class

### ISSUE THREAD

**Issue by meysamSamanpour** [dlemstra/Magick.NET#69]
What I want to do: 

I have byteArray of an image in memory, its about 1700 x 800 px I wanted to loaded into a MagickImage Object, but I need that MagickImage as 170 x 80 px. The things now I am doing is to create a MagickImage from bytearray and then resize it but I have performance issue. 

```
 var cachedImage = new MagickImage(imageFromCache);
cachedImage.Resize(170, 80); 

```
the resize takes about 50ms which is alot for my case while I have 10s of images. 
I thought I can use MagickSettings and read command to make a MagickImage of 170 x 80 px and then I dont need to resize it, but I found out that the width and height have been removed in new version (7.0.6.1000). 
And I cannot new the MagickSettings because it does not have a ctr without any arguments. I checked the code and found out that there is a size but the access level is protected. 

So what is the best way to create that MagickImage object and how to new a MagickSettings object ?

**Comment by dlemstra** [comment]
You will need to use the `MagickReadSettings` class to specify the options when you read the file. But you cannot resize an image with that. And even if the decoder would be able to recognize this it would still need to resize your image. Maybe you could use one of the faster `Scale` or `Thumbnail` methods?

**Comment by dlemstra** [comment]
@meysamSamanpour Do you need more help or can we close this issue.

**Comment by meysamSamanpour** [comment]
Sorry for late response. Thanks for your help. Yes you can close the question.
