### ISSUE TITLE
ImageMagick.MagickBlobErrorException: 'unable to open image 'C:\Test-123\Test.Abc\Test.Abc.UnitTests\bin\Debug\StaticResources\20191211_Playback_Wk_16.pdf': Permission denied @ error/blob.c/OpenBlob/3539

### ISSUE THREAD

**Issue by weslyin** [dlemstra/Magick.NET#690]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) 
(https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Hi,
below is my simple code snippet, i keep getting this error, i have given full permissions.
i am using the latest Majick.net 7.20.0.1
```
public void ConvertPdfToTIFF(FileInfo fileInfo, string targetFile)
        {
            var settings = new MagickReadSettings
            {
                Compression = _compression,
                ColorSpace = _colorSpace,
                ColorType = _colorType,
                Format = MagickFormat.Ptif
            };
            settings.Density = new ImageMagick.Density(300, 300, DensityUnit.PixelsPerInch);
            settings.UseMonochrome = true;
            settings.Compression = CompressionMethod.Group4;

            using (MagickImageCollection images = new MagickImageCollection())
            {
            
                images.Read(fileInfo, settings); // Blows up here 
                images.Write(targetFile + "\\test.tiff");
            }
}
```

i am calling this method froma simple unit test like this below, the method is wrapped inside TiffConverter class:-
```
[TestClass]
    public class Test_TiffConverter
    {
        public static string[] AllowableExtensions => new[] { ".png", ".pdf", ".jpg", ".jpeg", ".gif" };
        [TestMethod]
        public void Test_TiffConversion()
        {
            MagickNET.SetGhostscriptDirectory(@"C:\Program Files (x86)\gs\gs9.18\bin");
          
            var files = Directory.GetFiles("C:\\Digi-Ops\\DigiOps.Crm\\DigiOps.Crm.UnitTests\\bin\\Debug\\StaticResources");
    
            TiffConverter tiffConverter = new TiffConverter(null, CompressionMethod.Group4, ColorSpace.Gray, ColorType.Grayscale);

            foreach (var item in files)
            {
                var fileInfo = new FileInfo(item);
                var extension = fileInfo.Extension;

                if (AllowableExtensions.Contains(extension, StringComparer.OrdinalIgnoreCase) && extension == ".pdf")
                {
                 using (FileStream fs = fileInfo.Open(FileMode.Open,FileAccess.Read))
                    {
                        tiffConverter.ConvertPdfToTIFF(fileInfo, Constants.XML_STORE_CCR);
                        
                    }
                }
                else
                {
                    tiffConverter.ConvertImageToTiff(item, Constants.XML_STORE_CCR);
                }

            }

        }
    }
```
**Error:**
ImageMagick.MagickBlobErrorException: 'unable to open image 'C:\Digi-Ops\DigiOps.Crm\DigiOps.Crm.UnitTests\bin\Debug\StaticResources\20191211_Playback_Wk_16.pdf': Permission denied @ error/blob.c/OpenBlob/3539
### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU v 7.20.0.1
- Environment (Operating system, version and so on): Windows 7 Enterprise Service pack 1
- Additional information: Using Visual Studio 2019

**Comment by dlemstra** [comment]
I don't understand this block:

```C#
if (AllowableExtensions.Contains(extension, StringComparer.OrdinalIgnoreCase) && extension == ".pdf")
{
    using (FileStream fs = fileInfo.Open(FileMode.Open,FileAccess.Read))
    {
        tiffConverter.ConvertPdfToTIFF(fileInfo, Constants.XML_STORE_CCR);                        
    }
}
else
{
    tiffConverter.ConvertImageToTiff(item, Constants.XML_STORE_CCR);
}
```

If you use `&& extension == ".pdf"` the first statement is not used.

And because you are using `using (FileStream fs = fileInfo.Open(FileMode.Open,FileAccess.Read))` you are locking the file stream and then you will get an error that the permission to read the file will be denied. I also don't understand why you even have that statement.

**Comment by weslyin** [comment]
Thanks for your reply @dlemstra , yes i have remove the extension, it already validates in AllowableExtensions, if i try to use in no lock way like 
` FileStream fs =fileInfo.Open(FileMode.Open, FileAccess.Read,FileShare.Read);`

now i get a different error like

> ImageMagick.MagickCoderErrorException: 'Not a TIFF or MDI file, bad magic number 20517 (0x5025). `' @ error/tiff.c/TIFFErrors/661'

any example on what type of file objects i should be using to get the PDF to TIFF working will be of great help.

**Comment by weslyin** [comment]
@dlemstra  Thanks for your help. such a silly thing which i didnt see. i passed in just the path as string to the Image.Read(stringpath,settings); and that worked. 

appreciate your help here.
