### ISSUE TITLE
BUG: issue with using BMP files that are visible in other image libraries / viewers

### ISSUE THREAD

**Issue by unquietwiki** [dlemstra/Magick.NET#692]
**Original issue:** https://github.com/d2phap/ImageGlass/issues/708

**Error:** length and filesize do not match (filename) @ error/bmp.c/ReadBMPImage/846

**Version:** 7.20.0.1 (and older)
 
A user of https://github.com/Kosalos/Fractal2New reported to https://github.com/d2phap/ImageGlass/ that their fractal images were failing to load correctly in ImageGlass, even though the BMP files would load in other image viewers. ImageGlass uses this library to do a lot of the image rendering work. @d2phap suggested we let you all know about this occurrence; @fire-eggs was working with the original reporter of the issue. Thanks!

**Comment by dlemstra** [comment]
The next version of Magick.NET will include a new class called `BmpReadDefines` and you can use that to enable the option `IgnoreFileSize`. You will then be able to read the BMP image without any issues.

**Comment by dlemstra** [comment]
The new version has just been published.
