### ISSUE TITLE
Does Magick.NET support the same file formats as ImageMagick?

### ISSUE THREAD

**Issue by manfromarce** [dlemstra/Magick.NET#694]
There are some file formats like DJVU, JBIG, JXL, JXR that appear on ImageMagick website (https://imagemagick.org/script/formats.php) but are not available in Magick.NET's Format Enum. They also don't appear in a list I got with MagickNet.SupportedFormats class in C#.
Does Magick.NET support these files? They also require extra libraries in ImageMagick binary version.

**Comment by dlemstra** [comment]
The format `DJVU` requires the `libdjvu` library and that is not supported on Windows (also use GPL license).
The format `JBIG` requires the `jbig` library that uses a GPL license and that is not compatible with the apache license of this library.
The format `JXL` requires the `brunsli` library that is not supported on Windows.
The format `JXR` requires `JXRDecApp.exe` that you need to download and put in the same folder as the binaries of Magick.NET

**Comment by manfromarce** [comment]
Thank you for your help, can you please tell me also what is required for the FlashPix (fpx) format?

**Comment by dlemstra** [comment]
Fpx is currently unsupported on Windows.
