### ISSUE TITLE
how to setting the dpi when i convert a svg to pdf

### ISSUE THREAD

**Issue by crazyboy12** [dlemstra/Magick.NET#7]
when i convert a page of svg to pdf , it seems that magick.net use 90dpi as the dpi to convert the svg,but i want to change it to be 96dpi ,how can i do this? thanks

**Comment by dlemstra** [comment]
You can set the DPI of a MagickImage with the Density property,

**Comment by crazyboy12** [comment]
is it mostly like  this?

> MagickImageCollection collection = new MagickImageCollection();
>MagickImage svg = new MagickImage(svgpath);
>svg.Density = new PointD(300, 300);
>collection.Add(Svg);
>collection.Write(pdfpath);

**Comment by dlemstra** [comment]
Do you want to read the svg image with a 96 DPI? Or do you just want to set it to 96 DPI when you write it?

**Comment by dlemstra** [comment]
@crazyboy12 Where you able to resolve your issue and can I close this?
