### ISSUE TITLE
Reading 8bim without loading full file into memory

### ISSUE THREAD

**Issue by valadas** [dlemstra/Magick.NET#70]
I have some old c++ code that uses

`
MagickImage magickImage = new MagickImage();
magickImage.ping(path);
EightBimProfile eightBimProfile = magickImage.Get8BimProfile();
`
and it does work. I am now trying to do the same in a c# code and it does not get the 8Bim profile, I actually have to open the file for it to work. Is this something that got changed in some version or is there a difference between the way ping works in .net and on that old c++ code?

What I would like to do is increase the speed for reading the 8Bim profile, I do not need to load the image, I just need the 8bim data.

Thanks.

**Comment by dlemstra** [comment]
What type of file are you trying to read and can you add that file to this issue? Were you using Magick++ and do you want to change it to Magick.NET?

**Comment by valadas** [comment]
Thanks for the quick reply. I am reading from a tiff file saved from Photoshop. I want to use Magick.NET and the old project I am not sure, I only have part of the code.

Anyway, it looks like just EightBimProfile eightBimProfile = new EightBimProfile(path); works but the previous way of doing it (ping then GetEightBimProfile) does not work. My problem is fixed but I don't know if doing it the old way should work or it is normal.

**Comment by dlemstra** [comment]
Your fix might work because the 8BIM reader will just continue reading the file until the 8BIM marker is found but I don't know if it will always work.

It looks like we changed the tiff reader to not read the profiles when the image is being pinged. Not sure why we changed that but I will now go through the history to figure that out.

**Comment by valadas** [comment]
Wow, that was quick, it works perfectly, I was coming back to say I had the same issue for the icc profile but I saw it was already fixed! I updated the Nuget package and reverted to my old code, everything works perfectly and I think ping is faster than what I dit.

It's complicated to buy alcool for someone else on Amazon so... Enjoy the socks :)

**Comment by dlemstra** [comment]
Thanks for the gift, did not know that buying alcohol for someone else is that complicated on amazon.

**Comment by valadas** [comment]
You are welcome. Yes, they ask for ID in the country it is shipped or an international passport.
