### ISSUE TITLE
Magick.NET.SystemWindowsMedia v2.0.0 nuget packages misses netcoreapp3.0 target

### ISSUE THREAD

**Issue by Insire** [dlemstra/Magick.NET#701]
### Magick.Net version being used

```xml
        <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="7.21.0" />
        <PackageReference Include="Magick.NET.SystemWindowsMedia" Version="2.0.0" />
```

### Description
Taking the title into consideration, one can't use Magick.NET.SystemWindowsMedia in a .netcoreapp since, the package is not being used, despite it being installed.

You can take a look at the public meta data via [fuget](https://www.fuget.org/packages/Magick.NET.SystemWindowsMedia/2.0.0/lib/net40/Magick.NET.SystemWindowsMedia.dll/ImageMagick/IMagickImageExtentions)

The result of the package not being used or deployed is, that the extension method for turning a ``MagickImage`` into a ``BitmapSource`` isnt available.

![grafik](https://user-images.githubusercontent.com/11455827/87969251-0f74cb00-cac2-11ea-893f-fb380b88debf.png)

You can take a look at my previous bug report #683 if you want to validate this yourself. The screenshot was taking from the ``MvvmScarletToolkit.Samples`` project [here](https://github.com/Insire/MvvmScarletToolkit/blob/master/src/MvvmScarletToolkit.Samples/ViewModel/Image.cs#L75).

Screenshot of the debug output, validating that the required dll isnt being deployed:

![grafik](https://user-images.githubusercontent.com/11455827/87969486-87db8c00-cac2-11ea-8b4c-02d9ab42e824.png)

Edit: did download and extract the .nuget file. 

there is no folder for .netcoreapp which would contain the appropriate dlls. Only the .net40 stuff is present.
![grafik](https://user-images.githubusercontent.com/11455827/87969914-4697ac00-cac3-11ea-92ef-a82cae9fbd9d.png)

**Comment by dlemstra** [comment]
Thanks for reporting this. Turns out that I forgot to add the netcoreapp3.0 files to the package. That will be resolved in the next release that I will try to publish this week.

**Comment by dlemstra** [comment]
The new version has been published.

**Comment by Insire** [comment]
Tested the new version. Its working now. Thanks! :)
