### ISSUE TITLE
Unexpected results when using Magick.Net to convert pdf to png images.

### ISSUE THREAD

**Issue by rotvel** [dlemstra/Magick.NET#706]
As part of converting a project to .Net Core I'm trying the pdf conversion routines of Magick.Net. 

With a dpi of 300 I'm saving pages of pdf comic books as png files. The properties of saved images are read using IrfanView. 

Windows 10 2004. Ghostscript 9.52. This particular image is a grayscale cover of a book.

In the old project I use the Ghostscript.Net wrapper around the gs library (or a simple Process wrapper around the gs exe). I set -sDEVICE=png16m and the result is:

Page-01.png (looks exactly like in original pdf)
DPI: 300x300
Size: 7.587.354 bytes, 
Original colors: 24 bits per pixel, 
Current colors: 24 bits per pixel, 

In the new project I use Magick.Net with a loop similar to the one in the examples. The result is:

Page-01.png (the image have a more blueish tinge than the original).
DPI: 8x8
Size: 12.445.197 bytes, 
Original colors: 48 bits per pixel, 
Current colors: 24 bits per pixel, 

Other pdfs exhibit similar results. Larger (or smaller) file sizes. Differences in color space, difference in bits per pixel (32 or 48 bits vs the 24 bits of png16m). Some have what looks like inverted colors.

It looks like Magick.Net is not using the png16m output device. What is it using? Am I'm missing some configuration, Ie: is there a way to tell Magick.Net what output device to use for Ghostscript conversion?

**Comment by dlemstra** [comment]
Can you share your PDF file so I can understand better what is happening?

**Comment by rotvel** [comment]
Sure. https://drive.google.com/file/d/1GV5SklwTWRmxqAahx2I1yGfAKFj6O0zh/view?usp=sharing

**Comment by rotvel** [comment]
I tried saving the file as a jpg directly in the images loop (Quality 98, Interlace.Plane). The colors became worse. 

I've attached a version of the cover converted by the old project and one converted by the new

![page-01](https://user-images.githubusercontent.com/25582414/88445814-91982300-ce25-11ea-88b5-698e04591d2d.jpg)
![page-01](https://user-images.githubusercontent.com/25582414/88445818-99f05e00-ce25-11ea-8c6b-52d4a317911c.jpg)

**Comment by dlemstra** [comment]
This is is happening because Magick.NET notices that this is a CMYK image and it will use the `pamcmyk32` device. To avoid this and to force sRGB you can do this:

```C#
var settings = new MagickReadSettings
{
    ColorSpace = ColorSpace.scRGB
};

using (var image = new MagickImage("Found - Maya Le Maitre.pdf", settings))
{
}
```

**Comment by rotvel** [comment]
Okay, so Magick.Net is in a way lower level than using other methods. So I tried reading the first page like this

`      public void ReadPdf()
        {
            using var images = new MagickImageCollection();

            var settings = new MagickReadSettings
            {
                Density = new Density(300, 300),
                FrameIndex = 0, // First page
                FrameCount = 1, // Number of pages
                ColorSpace = ColorSpace.sRGB
            };
         
            images.Read("Found - Maya Le Maitre.pdf", settings);

            var page = 1;
            foreach (var image in images)
            {
                image.Format = MagickFormat.Jpg;
                image.Interlace = Interlace.Plane;
                image.Quality = 98;
                
                /*if (image.Height > 3100)
                {
                    image.Resize(new MagickGeometry
                    {
                        Greater = true,
                        Less = false,
                        Height = 3056
                    });
                }*/

                image.Write("page-1.jpg");
                page++;
            }
        }`

And it looked like using the png16m device to read the pdf. 

But when I tried the resizing code that's commented out above, the colors were still correct but a black border was added around the cover image. Can you explain what's going on?

**Comment by rotvel** [comment]
`using var images = new MagickImageCollection();

 var settings = new MagickReadSettings
 {
     Density = new Density(300, 300),
     FrameIndex = 0, // First page
     FrameCount = 1, // Number of pages
     ColorSpace = ColorSpace.sRGB
};
         
images.Read("Found - Maya Le Maitre.pdf", settings);

foreach (var image in images)
{
    image.Format = MagickFormat.Jpg;
    image.Interlace = Interlace.Plane;
    image.Quality = 98;
                
/*if (image.Height > 3100)
{
    image.Resize(new MagickGeometry
    {
           Greater = true,
            Less = false,
            Height = 3056
    });
}*/

image.Write("page-1.jpg");`

**Comment by rotvel** [comment]
`
using var images = new MagickImageCollection();

 var settings = new MagickReadSettings
 {
     Density = new Density(300, 300),
     FrameIndex = 0, // First page
     FrameCount = 1, // Number of pages
     ColorSpace = ColorSpace.sRGB
};
         
images.Read("Found - Maya Le Maitre.pdf", settings);

foreach (var image in images)
{
    image.Format = MagickFormat.Jpg;
    image.Interlace = Interlace.Plane;
    image.Quality = 98;
                
/*if (image.Height > 3100)
{
    image.Resize(new MagickGeometry
    {
           Greater = true,
            Less = false,
            Height = 3056
    });
}*/

image.Write("page-1.jpg");
`

**Comment by rotvel** [comment]
Nevermind. For my usecases I need more control over the pdf extracting process than Magick.Net provides. So I'll switch back to a gs exe wrapper (which Magick.Net uses anyway) for the extraction and Magick for the image conversion. 

Thanks for looking into this. I'm closing the issue now.
