### ISSUE TITLE
[Question] Convert Gif to MP4 

### ISSUE THREAD

**Issue by mhamri** [dlemstra/Magick.NET#71]
hi, ImageMagick had ability to convert gif to mp4, I wonder if this library carry the same ability or not? 

Thanks

**Comment by dlemstra** [comment]
This library can also do that but you will need to download ffmpeg.exe and put that in the binary folder that also contains the Magick.NET library.

**Comment by dlemstra** [comment]
Did my reply answer your question @mhamri  and can we close this issue?

**Comment by mhamri** [comment]
yes, thanks indeed

**Comment by MatthewPlaudis** [comment]
hey @dlemstra  I was hoping to do the same thing, wondering if you could elaborate a little more. is ffmpeg available as a Nuget package in visual studio? or should I download the extension externally?

**Comment by dlemstra** [comment]
ffmpeg is an executable that you will need to download and place into the `bin` folder of your project.
