### ISSUE TITLE
Fonts are not used/found on Azure Web App Service

### ISSUE THREAD

**Issue by mchenx** [dlemstra/Magick.NET#72]
I have my web service deployed on Azure using web app service, I could see the png file was added as watermark, and I can see shadows created and some numbers, alphabets printed.
The only problem is, again, the Chinese is shown as question marks ( ? ), this time I believe I wrote exactly correct font family name, but is this again related to the font family?

I previously raised this [https://github.com/dlemstra/Magick.NET/issues/60](https://github.com/dlemstra/Magick.NET/issues/60)
Seem to be related...

I googled and some developer said that was caused by GDI objects not accessable but I doubt that in my case

**Comment by mchenx** [comment]
Today I created a simple web service and deployed on azure web app service, and there are two APIs
, one is to get the installed font families on that cloud web app service
[http://testfontgdi.azurewebsites.net/api/values](url)
and the other returns a jpeg that generates completely using GDI+ (Graphics, Bitmap classes, DrawArc, DrawBezier, DrawString, DrawEllipse methods, etc.)
[http://testfontgdi.azurewebsites.net/api/values/6](url)

`using (var image = new Bitmap(640, 480))
            {
                using (var g = Graphics.FromImage(image))
                {
                    g.FillRectangle(Brushes.WhiteSmoke, new Rectangle(0, 0, 640, 480));

                    using (var brush = new SolidBrush(Color.Red))
                    {
                        using (var pen1 = new Pen(brush, 3.7f))
                        {
                            g.DrawArc(pen1, new Rectangle(new Point(10, 15), new Size(170, 188)), 35.1f, 46.7f);
                        }
                    }

                    using (var pen2 = new Pen(Color.GreenYellow, 5.2f))
                    {
                        g.DrawBezier(pen2, new Point(615, 134), new Point(44, 87), new Point(321, 129), new Point(45, 322));
                    }

                    using (var pen3 = new Pen(Color.OrangeRed, 2.5f))
                    {
                        g.DrawEllipse(pen3, new Rectangle(new Point(223, 137), new Size(126, 76)));
                    }

                    using (var family = new FontFamily("Microsoft YaHei UI"))
                    {
                        using (var font = new Font(family, 20.2f))
                        {
                            using (var brush = Brushes.RoyalBlue)
                            {
                                g.DrawString("中国上海\n国家会展中心1101", font, brush, new PointF(350f, 250f));
                            }
                        }
                    }
                }

                using (var ms = new MemoryStream())
                {
                    image.Save(ms, ImageFormat.Jpeg);
                    imageFile = File(ms.ToArray(), "image/jpeg");
                }
            }`

I cannot use "Microsoft YaHei & Microsoft YaHei UI" as the font family in above code as there is no such font family.

**Comment by dlemstra** [comment]
Are you printing the fonts with `MagickNET.FontFamilies` in your first API call?

**Comment by mchenx** [comment]
nope, I called  
`new InstalledFontCollection().FontFamilies.Select(f => f.Name);`

**Comment by mchenx** [comment]
I updated the API to print MagickNET.FontFamilies and found no "Microsoft YaHei UI" but "Microsoft YaHei" only. Now I can get Chinese characters printed after changed the FontFamily to be "Microsoft YaHei". 

Probably I should query the MagickNET.FontFamilies and pickup one from it dynamicly.

Thanks for looking at this question, thanks!

**Comment by dlemstra** [comment]
Did you use markdown yourself to create the links in this issue? They all point to a strange url. Wondering if this is a bug on github or if you created the links yourself.

**Comment by mchenx** [comment]
Yeah, I added the links wrongly... now fixed

**Comment by dlemstra** [comment]
No problem just want to know if it was a github bug. I'll close this issue for now then.

**Comment by mchenx** [comment]
Sure, thanks a lot for the help.
