### ISSUE TITLE
Magick.Net hangs on (probably) invalid EXIF data -- keeps consuming memory until terminated

### ISSUE THREAD

**Issue by artyomszasa** [dlemstra/Magick.NET#723]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
We've found rare case when Magick.NET hangs on ExifProfile.Values while consuming infinite memory. Memory usage goes up to 30 GB RAM (I don't have more and can't confirm whether there is a limit).

### Steps to Reproduce
See minimal program: https://gist.github.com/artyomszasa/2cf62acdefe8b8c845a8066e3666a80a
And an attached image. 
![t25](https://user-images.githubusercontent.com/843989/91823554-ab553300-ec39-11ea-883a-fcca029f9264.jpg)

### System Configuration
- Magick.NET version: 7.21.1
- Environment (Operating system, version and so on): Ubuntu 20.04, dotnet-sdk 3.1.302
- Additional information:

When I strip exif profile manually (both convert and gimp work) then file is processed successfully.

**Comment by catester** [comment]
Could it be you calling GetExifProfile repeatedly in foreach loop?

```
foreach (var value in image.GetExifProfile().Values)
```

Did you try this?
```
var exifProfile = image.GetExifProfile();
foreach (var value in exifProfile.Values)
```

**Comment by artyomszasa** [comment]
I used `image.GetExifProfile().Values` only in the minimal example to reproduce the issue, the original code where the problem appeared looks like this:
```csharp
try
{
    var exifProfile = _native.GetExifProfile();
    if (null != exifProfile)
    {
        foreach (var value in exifProfile.Values)
        {
            var v = Helpers.StringifyImageData(value.GetValue());
            if (null != v)
            {
                var tag = value.Tag.ToString();
                if (!exif.ContainsKey(tag))
                {
                    exif.Add(tag, v);
                }
            }
        }
    }
}
catch (Exception exn)
{
    Console.WriteLine(exn);
}
```

When using debugger the `exifProfile.Value` just never returns. You don't really need the loop, once the getter is invoked CPU goes 100%, memory usage is growing continously, no exception is thrown. Once process reaches the maximum memory it is terminated by the system.

As I wrote before there is a pretty straightforward workaround -- removing the exif data before processing. So it's no blocker for me but I think there may be an issue in EXIF profile processing and the sample image may help finding the problem.

**Comment by dlemstra** [comment]
A new release that fixes this issue has just been published.
