### ISSUE TITLE
 Exception "Bad Code Word" thrown when read an image

### ISSUE THREAD

**Issue by snk88** [dlemstra/Magick.NET#73]
I tried to read an image but it throw an exception. Any advice?

ImageMagick.MagickCoderErrorException: Bad code word at line 1441 of strip 0 (x 1680). `Fax3Decode1D' @ error/tiff.c/TIFFErrors/572
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadFile(MagickSettings settings)

**Comment by dlemstra** [comment]
You are getting this error because your tiff file is corrupt and that is why you are unable to read it.

**Comment by snk88** [comment]
The file is not corrupt and I can open the file using Windows Photo Viewer or GIMP

**Comment by dlemstra** [comment]
Windows Photo Viewer and GIMP are less strict about the data in the file. ImageMagick/Magick.NET will throw an error instead of ignoring the error data. If you save the image inside GIMP you will be able to use Magick.NET to read the file because GIMP will write the image without the error data.

**Comment by dlemstra** [comment]
Does that answer your question @snk88 ?

**Comment by dlemstra** [comment]
Closing due to lack of response
