### ISSUE TITLE
WriteBlob Failed <path> @ error/png.c/MagickPNGErrorHandler/1715

### ISSUE THREAD

**Issue by pravinohalhbg** [dlemstra/Magick.NET#734]
Description
Hi I'm creating a large image in memory with dimension as 61000x184320, with 32 bit depth
I'm trying to save the memory image to disk, it took a while for saving(15mins), and ultimately crashed with the error "WriteBlob Failed <path> @ error/png.c/MagickPNGErrorHandler/1715".
I'm using Magick.NET-Q16-x64 v7.21.1.0, Machine configuration is I7 with 16 GB RAM
Here is that code that I'm using  
        using (var finalImage = new MagickImage(MagickColors.None, finalImageWidth, finalImageHeight))
          {
              finalImage.Write(savePath);
          }

**Comment by dlemstra** [comment]
Is it possible to create a `Program.cs` file that demonstrates this issue? Or can you reproduce this issue with just creating a transparent `61000x184320` image and save it to disk?

**Comment by dlemstra** [comment]
Ping @pravinohalhbg

**Comment by pravinohalhbg** [comment]
@dlemstra Sorry was busy with project work, will definitely let you know by tomorrow. Thanks.

**Comment by pravinohalhbg** [comment]
@dlemstra I tried to reproduce the issue. Getting this error WriteBlob Failed `C:\largefinalimage345.png' @ error/png.c/MagickPNGErrorHandler/1715

**Comment by pravinohalhbg** [comment]
Code

 class Program
    {
        static void Main(string[] args)
        {
            try
            {               
                CreateLargeImage();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                Console.ReadLine();
            }
        }
        private static void CreateLargeImage()
        {
            using (var finalImage = new MagickImage(MagickColors.Transparent, 61000, 184320))
            {

                finalImage.Write(@"C:\largefinalimage345.png");
                Console.WriteLine("File written to C:\\largefinalimage345.png");
            }
        }
    }

**Comment by pravinohalhbg** [comment]
@dlemstra any updates in this?

**Comment by dlemstra** [comment]
I have not had time to investigate this. Is it possible that you are running out of disk space? Your image requires `61000 * 184320 * 16 bits` to hold it's pixels. That is around 67GB and will never fit in the 16GB memory that your machine has. The pixels will be stored on disk in a temporary folder. And then when the image is encoded it also requires additional disk space to save the image. I have no idea how much that is that is but do you have enough disk space available for the image?

**Comment by pravinohalhbg** [comment]
How much disk space will the image consume, any idea? Is this feasible to create such a large image?

**Comment by pravinohalhbg** [comment]
you mean 67GB RAM?

**Comment by dlemstra** [comment]
The image is written on disk. The output is written on disk and that is less than 67GB because the pixels are compressed. But to keep the image in memory ImageMagick will "swap to disk" to store the pixels there instead of in memory. This is done because you don't have enough memory to store 67GB of pixel data. So in total you will need 67 + the compressed PNG file as disk space. My guess is that it would probably be around 80GB of free disk space.

**Comment by pravinohalhbg** [comment]
@dlemstra Thanks, for the detailed figures, I'll discuss with the team and let you know whether we need to go with this approach.

**Comment by pravinohalhbg** [comment]
@dlemstra  what if we use Magick.NET-Q8 instead of Magick.NET-Q16. How much will the size of the image be reduced? Can we compress the image without losing its quality up to some extent?

**Comment by dlemstra** [comment]
If you switch to Q8 you will use half the memory. This version uses 8 bit instead of 16 bit per channel. PNG will compress the image without losing quality.

**Comment by pravinohalhbg** [comment]
Thanks @dlemstra , I'll try Q8 and let you know, we are already using PNG, any other compression function, an algorithm we can use in Magick.Net to reduce the size of the final image?

**Comment by dlemstra** [comment]
You could use another format that has better compression. But what works best in your situation is probably trail on error. AVIF is a very promising format but the compression in that format will probably be a lot longer than using PNG.
