### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by danpetitt** [dlemstra/Magick.NET#741]
Hi Dirk; thanks again for a great library. Do you have any plans on supporting the new AVIF format?

**Comment by dlemstra** [comment]
Support for reading was AVIF introduced in this version: https://github.com/dlemstra/Magick.NET/releases/tag/7.20.0.0. And I just updated the release notes to include the note about write support for this version: https://github.com/dlemstra/Magick.NET/releases/tag/7.22.0.0.

**Comment by d2phap** [comment]
Thanks @dlemstra for AVIF support.
However, I tested with the samples in https://github.com/link-u/avif-sample-images, there are some files that Magick.NET cannot open:

![image](https://user-images.githubusercontent.com/3154213/94366176-df245b00-0108-11eb-81ab-8c62d7f07449.png)


```
https://github.com/link-u/avif-sample-images/blob/master/plum-blossom-small.profile0.10bpc.yuv420.alpha-full.avif
https://github.com/link-u/avif-sample-images/blob/master/plum-blossom-small.profile0.10bpc.yuv420.alpha-full.monochrome.avif
https://github.com/link-u/avif-sample-images/blob/master/plum-blossom-small.profile0.10bpc.yuv420.alpha-limited.avif
...
```

**Comment by dlemstra** [comment]
You will need to report this issue to the developers of https://github.com/strukturag/libheif. Magick.NET uses that library to read the AVIF images.

**Comment by agravity-philipp** [comment]
@d2phap have you reported this isse to the developers of https://github.com/strukturag/libheif? I could not find the ticket and I have the same issue.

**Comment by d2phap** [comment]
@agravity-philipp oh I think I forgot.

**Comment by agravity-philipp** [comment]
@d2phap I did that for you: https://github.com/strukturag/libheif/issues/697

**Comment by agravity-philipp** [comment]
Hi @dlemstra ! 
Please note, that this issue was fixed: https://github.com/strukturag/libheif/issues/697#issuecomment-1314288074

**Comment by dlemstra** [comment]
We will need to wait for a release before we can have this fix in the Magick.NET library

**Comment by agravity-philipp** [comment]
Hi @dlemstra ! This was already released in version [v1.14.0](https://github.com/strukturag/libheif/releases/tag/v1.14.0) or at least it is in the current version 1.14.2. Is it already included in [12.2.2](https://github.com/dlemstra/Magick.NET/releases/tag/12.2.2) ?

**Comment by dlemstra** [comment]
In the release overview (https://github.com/dlemstra/Magick.NET/releases) I also have a note of the dependencies that are updated. And the file https://github.com/dlemstra/Magick.NET/blob/main/src/Magick.Native/libraries.md contains the most recent versions of the libraries (note: it might be possible that this is not yet released).

But to answer your question the update to 1.14.0 was done in version [12.2.2](https://github.com/dlemstra/Magick.NET/releases/tag/12.2.2).

**Comment by Rombersoft** [comment]
I've just converted PNG with size 235Kb to AVIF with 10Kb using the 13.5.0 library version and the result is very very bad picture quality.
I compared the result with the native Linux application ImageMagick (convert) and the result was 21Kb, and the picture quality
is far better.

**Comment by dlemstra** [comment]
Please don't hijack issues to ask questions. Please use a new discussion instead.
