### ISSUE TITLE
Annotating text on image does not work

### ISSUE THREAD

**Issue by jtrinanes** [dlemstra/Magick.NET#744]
Hi,

I'm using Magick.NET version 7.15.4 and I have a weird issue with it.

I want to set a text to the bottom-left corner of the image but instead the text was placed on the top-right.

![image](https://user-images.githubusercontent.com/44257372/94451870-81177680-01e1-11eb-9e9d-de9120b6318a.png)

using the following code below:

// place the x, y, width and height
image.Annotate (text, new MagickGeomerty(5, 436, 590, 14));

even using the Gravity.Southwest enum does not work.

**Comment by dlemstra** [comment]
Do you also experience this issue when you upgrade Magick.NET to the latest version? With the code below the image is drawn in the correct position:

```C#
using (var image = new MagickImage(MagickColors.Red, 100, 100))
{
    image.Annotate("Test", Gravity.Southwest);

    image.Write("test.png");
}
```

**Comment by jtrinanes** [comment]
Hi,

I upgraded Magick.NET to 7.22.0 and I'm getting an error message.

![image](https://user-images.githubusercontent.com/44257372/94530904-5aebe800-026e-11eb-9bd2-5ad92ba085f9.png)

**Comment by dlemstra** [comment]
The `AddProfile` method has been renamed to `SetProfile`.
