### ISSUE TITLE
NonconformingDrawingPrimitiveDefinition `font-style'  after Upgrade to 7.22 from 7.11.1

### ISSUE THREAD

**Issue by Schrall** [dlemstra/Magick.NET#747]
After Upgrading to the Version 7.22 i get Local and in my Docker Image this Error:

ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `font-style' @ error/draw.c/RenderMVGContent/4458
  at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
  at ImageMagick.NativeHelper.CheckException(IntPtr exception)
  at ImageMagick.DrawingWand.NativeDrawingWand.Render()
  at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
  at ImageMagick.MagickImage.Draw(IDrawables`1 drawables)
  at ImageMagick.Drawables.Draw(IMagickImage`1 image)
  at Infrastructure.Services.DocumentService.GetGigFlyer(Document picture, GigPublish gigPublish) 

To prove that my Code has no Bugs i tried the Example from your Docs:

```
using (var image = new MagickImage(new MagickColor("#ff00ff"), 512, 128))
{
    new Drawables()
      // Draw text on the image
      .FontPointSize(72)
      .Font("Comic Sans")
      .StrokeColor(new MagickColor("yellow"))
      .FillColor(MagickColors.Orange)
      .TextAlignment(TextAlignment.Center)
      .Text(256, 64, "Magick.NET")
      // Add an ellipse
      .StrokeColor(new MagickColor(0, Quantum.Max, 0))
      .FillColor(MagickColors.SaddleBrown)
      .Ellipse(256, 96, 192, 8, 0, 360)
      .Draw(image);
}
```

System Configuration
MacOs 10.15.6
dotnet 3.1.202

My Dockerfile:

```FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR /app
COPY . /app

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
#NPIO
RUN apt-get update
RUN apt-get install -y apt-utils && apt-get install -y libgdiplus libc6-dev
RUN ln -s /usr/lib/libgdiplus.so /usr/lib/gdiplus.dll
#NPIO

#Magick.net
RUN apt-get install -y --no-install-recommends apt-utils && apt-get install libfreetype6 -y && apt-get install fontconfig -y                      
#Magick.net

RUN apt-get install tzdata -y

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080/tcp
VOLUME /opt/bandbee/documents
VOLUME /opt/bandbee/config
ENTRYPOINT ["dotnet", "Web.dll"]
```

When i try to downgrade i get the same Error on my Local Maschine and the following Error in my Docker Container:

System.IO.FileNotFoundException: Could not load file or assembly 'Magick.NET.Core, Version=5.0.0.0, Culture=neutral, PublicKeyToken=2004825badfa91ec'. The system cannot find the file specified.

Thanks for your Support.

**Comment by dlemstra** [comment]
Is it possible to create a small sample that demonstrates the issue? Or can you reproduce the issue with the sample code that you pasted in this issue? And why are you installing `libgdiplus` in the container. That should not be required.

**Comment by Schrall** [comment]
I created a new Project 
Referenced Magick.NET-Q16-AnyCPU 7.22

```class Program
    {
        static void Main(string[] args)
        {
            using (var image = new MagickImage(new MagickColor("#ff00ff"), 512, 128))
            {
                new Drawables()
                    // Draw text on the image
                    .FontPointSize(72)
                    .Font("Arial")
                    .StrokeColor(new MagickColor("yellow"))
                    .FillColor(MagickColors.Orange)
                    .TextAlignment(TextAlignment.Center)
                    .Text(256, 64, "Magick.NET")
                    // Add an ellipse
                    .StrokeColor(new MagickColor(0, Quantum.Max, 0))
                    .FillColor(MagickColors.SaddleBrown)
                    .Ellipse(256, 96, 192, 8, 0, 360)
                    .Draw(image);
            }
        }
    }
```

I get almost the same error:

ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4381
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.NativeHelper.CheckException(IntPtr exception)
   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
   at ImageMagick.DrawingWand.Draw(IEnumerable`1 drawables)
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
   at ImageMagick.MagickImage.Draw(Drawables drawables)
   at ImageMagick.Drawables.Draw(IMagickImage image)
   at Magick.net_Test.Program.Main(String[] args) in /Users/development/RiderProjects/Bandbee/Bandbee/Magick.net_Test/Program.cs:line 12


if i remove everything with Text, it works
```
 new Drawables()
                    // Draw text on the image
                    // .FontPointSize(72)
                    // .Font("Arial")
                    // .StrokeColor(new MagickColor("yellow"))
                    // .FillColor(MagickColors.Orange)
                    // .TextAlignment(TextAlignment.Center)
                    // .Text(256, 64, "Magick.NET")
                    // Add an ellipse
                    .StrokeColor(new MagickColor(0, Quantum.Max, 0))
                    .FillColor(MagickColors.SaddleBrown)
                    .Ellipse(256, 96, 192, 8, 0, 360)
                    .Draw(image);
```


And in  [https://dotnetfiddle.net/TMaYjp](https://dotnetfiddle.net/TMaYjp)
i get a slightly different error:

Fontconfig error: Cannot load default config file
Unhandled exception. ImageMagick.MagickDrawErrorException: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4458
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception)
   at ImageMagick.NativeHelper.CheckException(IntPtr exception)
   at ImageMagick.DrawingWand.NativeDrawingWand.Render()
   at ImageMagick.MagickImage.Draw(IEnumerable`1 drawables)
   at ImageMagick.MagickImage.Draw(IDrawables`1 drawables)
   at ImageMagick.Drawables.Draw(IMagickImage`1 image)
   at Program.Main()
Command terminated by signal 6

**Comment by dlemstra** [comment]
I cannot reproduce your issue on Windows. Your `Dockerfile` is missing `FROM` so I don't know what your base image is. And you probably need to install `fontconfig` and run `fc-cache` in your container to allow drawing of text.

**Comment by Schrall** [comment]
Sorry for the Docker From

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

It worked before and it really changed after Update to 7.22. 

in the Dockerfile is the apt-get install fontconfig -y command included 
After the Deployment, i copy all Googlefonts in the DockerContainer. 

```#install fonts
docker cp /opt/bandbee/fonts/fonts/ BandbeeWebApiTest:/
docker exec BandbeeWebApiTest mkdir -p $pkgdir
docker exec BandbeeWebApiTest find /fonts -type f -name "*.ttf" -exec install -Dm644 {} $pkgdir \;
docker exec BandbeeWebApiTest fc-cache -f > /dev/null
```

**Comment by dlemstra** [comment]
Did you already solve this @Schrall?

**Comment by AbdulAzeezC** [comment]
Getting this error on migrating to a latest Magick lib "exception: Magick: NonconformingDrawingPrimitiveDefinition `text' @ error/draw.c/RenderMVGContent/4470"

currently we are using version imageMagick version 7.1.0-2
the same issue was not observed previously, as there is no change around this code since long time in our code.

some more inputs here we are trying to draw over an image & giving inputs like below (Note that some of the getter & setters are purely our application level.
If you can kindly help with the syntax of drawableText or something is got changed in between these versions prior to above mentioned version??

std::vectorMagick::Drawable aDrawList;
// font
aDrawList.push_back(DrawableFont(iImage.getDynAdFontFilePath()));
NGN_LOG_INFORMATION("Abdul Font related issue check "<< iImage.getDynAdFontFilePath()<<"\n"; // font color
aDrawList.push_back(DrawableFillColor(Color(iImage.getDynAdFontColor())));
// font size
aDrawList.push_back(DrawablePointSize(iImage.getDynAdFontSize()));
// text
const double aDX=BTB_Utils::convert<double, string>(iImage.getDynAdLocationX());
const double aDY=BTB_Utils::convert<double, string>(iImage.getDynAdLocationY());
aDrawList.push_back(DrawableText(aDX, aDY , iPriceCurrency));

**Comment by dlemstra** [comment]
There really is no need to post the same message twice @AbdulAzeezC. And as I said in the other place you are reporting this at the wrong spot.
