### ISSUE TITLE
Magick.NET-Q8-AnyCPU PDF Read Issue

### ISSUE THREAD

**Issue by Kubsi009** [dlemstra/Magick.NET#748]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Hi Team , 

Please note that we are using Magick.NET-Q8-AnyCPU to read the pdf and convert to TIFF files.
When we are reading some of the PDF's it takes for ever , it never completes and blocks the other PDF's to process , even tried to capture the error if any , but looks like it never errors , its just keep on reading the PDF .

Our PDF contains 10-30 pages always , the PDF's which were not able to read as per me were with different frames (not sure I used the correct word or not ) Ex: when you click the content in PDF's every paragraph will be selected as different format , those PDF's will never be read .Also editable PDF;s.

Could you please let me know is there a setting to avoid these and generate TIFF successfully 

Code 
                            MagickReadSettings settings = new MagickReadSettings();
                            settings.Density = new Density(200, 200);

                            settings.Compression = CompressionMethod.Group4; // Fax any format
                            settings.UseMonochrome = true;

                            using (MagickImageCollection collection = new MagickImageCollection())
                            {
                                try
                                {
                                    collection.Read(file, settings);
                                 }

### System Configuration

- Magick.NET version:
- Environment (Operating system, version and so on):
- Additional information:

**Comment by t246246** [comment]
I think you would get better answer if you could provide your problematic pdf.

For now, I can say,

Magick.NET and ImageMagick relys on GhostScript for reading PDF.  As you say you can read some pdf, ghostscript is installed.
Supposed you are using Windows, you can convert pdf to pam using ghostscript from the command line like this:

"C:/Program Files (x86)/gs/gs9.27/bin/gswin32c.exe" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -r200 -sDEVICE=pamcmyk32  -o output.pam input.pdf

If it does not work, it is a problem with ghostscript. (If you omit -q -dQUIET, you might be see which page had been processed.)

**Comment by dlemstra** [comment]
Can you give it another try with the new release that will likely be published later today? This looks like the same issue reported here: https://github.com/dlemstra/Magick.NET/discussions/795.

**Comment by dlemstra** [comment]
The new release has been published. Can you give it another try @Kubsi009?
