### ISSUE TITLE
How to detect if an image is mostly grayscale?

### ISSUE THREAD

**Issue by szh** [dlemstra/Magick.NET#75]
Given an image which could be either a full-color photo or a scan of a document, I'd like to detect how colorful the photo is so I can make a good guess as to which it is. I found this command [here](http://www.imagemagick.org/discourse-server/viewtopic.php?t=19580#p81226): `convert image -colorspace HSL -channel g -separate +channel -format "%[fx:mean]" info:`, but how can I accomplish this with Magick.NET?

Thanks

**Comment by dlemstra** [comment]
That command would translate to this:

```C#
using (MagickImage image = new MagickImage("image"))
{
    // -colorspace HSL
    image.ColorSpace = ColorSpace.HSL;

    // -channel g -separate +channel
    using (IMagickImage channel = image.Separate(Channels.Gray).First())
    {
        // -format "%[fx:mean]"
        Console.WriteLine(channel.FormatExpression("%[fx:mean]")));
    }
}
```

**Comment by szh** [comment]
Nice! Thank you
