### ISSUE TITLE
Unable to read font 'DejaVuSans'

### ISSUE THREAD

**Issue by jtrinanes** [dlemstra/Magick.NET#753]
Hi,

We're experimenting with moving our apps to Linux app service in Azure. We have an image processing app that uses MagickImage.NET. 

We encounter an error like below when processing an image:

**ImageMagick.MagickTypeErrorException: UnableToReadFont `DejaVuSans' @ error/annotate.c/RenderFreetype/1391**

We don't encounter the error in Windows app service, but in Linux app service. Does it have to do with the installed font in the host OS?

**Comment by dlemstra** [comment]
That is correct you will need to have the font installed in the host OS. On Linux font-config will be used so that means you will need to make sure to run `fc-cache` after the font has been installed.
