### ISSUE TITLE
The type initializer for 'nativemagicksettings' threw an exception. The type initializer for 'x64' threw an exception

### ISSUE THREAD

**Issue by linzhuzhang** [dlemstra/Magick.NET#755]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The type initializer for 'nativemagicksettings' threw an exception. The type initializer for 'x64' threw an exception.
 This error will be reported when calling the Magick.NET-Q16-AnyCPU DLL What is the cause? How to solve this problem?

### System Configuration

The program runs in window server 2012 R2
IIS version = 7.5
Net framework 4.5.2. 

- Magick.NET version: Magick.NET-Q16-AnyCPU  AND  Magick.NET-Q8-AnyCPU
- Environment (Operating system, version and so on):
- Additional information:

**Comment by dlemstra** [comment]
Please don't ask the same question in two different places.
