### ISSUE TITLE
Bad IFD Offset when using Adobes XMP Toolkit to read XMP data from ImageMagick saved image

### ISSUE THREAD

**Issue by danpetitt** [dlemstra/Magick.NET#758]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If I use magick.net to save a JPEG image, it is not readable by the [Adobe XMP-Toolkit](https://github.com/adobe/XMP-Toolkit-SDK); when the toolkit tries to read the XMP data, it returns an `Out of bounds IFD` error message when attempting to read the TIFF thumbnail.

I have reported this to Adobe https://github.com/adobe/XMP-Toolkit-SDK/issues/19 and they were looking into it; but i thought I would try a bit of investigation.

If I open the image (saved by magick.net) into paint.net and re-save; the XMP toolkit is then able to open the image.

So I tried to save the image as PNG from magick.net, that also returns an `Out of bounds IFD` message.

I do accept that this may be an issue with Adobe's XMP Toolkit but what I find odd is the same broken image, resaved using paint.net then works so was wondering if its actually more an issue with ImageMagick saving an incompatible format.

It also does not work if I 'store, strip and re-set' the metadata to the image, so it must be something to do with the way the metadata is saved into the image.

### Steps to Reproduce
Open up attached solution and run in Debug x64 (I have only provided debug xmp dll's). I have two images, the first one 'working' is the image saved from paint.net; the second 'notworking' is the image which was originally saved using ImageMagick.net.

[CsXmpMagickNetTest.zip](https://github.com/dlemstra/Magick.NET/files/5365617/CsXmpMagickNetTest.zip)

### System Configuration
- Magick.NET version: 7.22.0
- Environment (Operating system, version and so on): Windows 10 desktop or Azure App Service
- Additional information: Test solution attached

**Comment by t246246** [comment]
So far I checked, exif is broken for 2 files: NotWorking-Two-Weeks-In-Hell_S0E0_891087_4-3.jpg and 92224549-db027600-ee99-11ea-8880-cdc9a3f484eb.jpg (that is attached  at adobe/XMP-Toolkit-SDK#19)

$ ./exiv2 -pe NotWorking-Two-Weeks-In-Hell_S0E0_891087_4-3.jpg 1>/dev/null
Warning: Directory Photo has an unexpected next pointer; ignored.
Error: Directory GPSInfo: IFD exceeds data buffer, cannot read next pointer.
Error: Directory Thumbnail: IFD exceeds data buffer, cannot read next pointer.

After removing exif (APP1), same command does not report error.

You said you created jpeg (and PNG) files with Magick.NET, but how to create them?  I believe there is a input file. If the input file has already broken exif, there is no surprise the output is broken at the same point, provided if it just copies that part. (I don't know about Paint.NET, however, it might reconstruct exif by copying as many as that can read.)

So, can you provide a input file for Magick.NET (which I guess created by some Adobe software), and the exact C# program (or imagemagick command line) to create that jpeg?

**Comment by dlemstra** [comment]
Is it possible that Paint.NET just ignores the exif data?

**Comment by dlemstra** [comment]
A new release of Magick.NET that resolves this issue has been published.
