### ISSUE TITLE
Cannot download the Magick.Native library

### ISSUE THREAD

**Issue by coldwarrior5** [dlemstra/Magick.NET#759]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
The Magick.Net project cannot be built given the Magick.Native library cannot be downloaded from the dropbox.
I tried manually navigating to the various versions of the Magick.Native library and could not find the content.

### Steps to Reproduce
1.  Download the latest release of the Magick.Net from https://github.com/dlemstra/Magick.NET/releases
2.  Download the latest NuGet from https://www.nuget.org/downloads
3.  Place the nuget.exe into the Magick.NET-X.XX.X.X\tools\windows folder
4.  Go into the Magick.NET-X.XX.X.X\src\Magick.Native folder and double click on install.cmd which will start to download the native libraries
5.  404 Not found error appears

### System Configuration
Windows 10 Pro version 2004
Intel Core i5-9600K
32 GB RAM
nVidia 1050Ti
Magick.NET version 7.22.0.0

**Comment by dlemstra** [comment]
I have changed the location where the Magick.Native library is stored. This has moved to the GitHub package registry. To download the package you will need create a personal access token (only read:packages) here:

![afbeelding](https://user-images.githubusercontent.com/10426229/95912663-60cfe600-0da3-11eb-8a3a-a5e4bd40a83f.png)

Then you will need to run `create-nuget-config.cmd <your username> <your token>` in the folder `src\Magick.Native` to create a nuget.config file. And then you can use `install.cmd` to install the Magick.Native library.

**Comment by coldwarrior5** [comment]
I can confirm that the new procedure for downloading binaries works as expected thus I will mark this issue as resolved.

Could you just update the documentation to reflect the new procedure there as well, with an additional step to download the latest nuget.exe which has to be placed under tools/windows in order for this new installation process to work?

I appreciate your quick fix and help with this.

**Comment by dlemstra** [comment]
Feel free to open a PR to make these changes. That would be really helpful for me.
