### ISSUE TITLE
nuget package assemblies for .net framework contain references to .net Core

### ISSUE THREAD

**Issue by baboongd** [dlemstra/Magick.NET#761]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
the .Net FRAMEWORK binaries and the project both are referencing .net Core, which defeats the purpose of having a pure framework dll. Currently using it in an enviroment without Core support, so it's unusable despite targeting framework 4.

### System Configuration

- Magick.NET version: 7.22
- Environment (Operating system, version and so on): win 10, vs 2017
- Additional information:

**Comment by baboongd** [comment]
Turns out you need both Magic.Core and framework assemblies

**Comment by dlemstra** [comment]
How did you come to this conclusion? There should be no references to .NET Core in the Framework build.
