### ISSUE TITLE
Can't get black/white masks to work

### ISSUE THREAD

**Issue by LennardF1989** [dlemstra/Magick.NET#766]
I've been toying with this for over 4 hours this evening, I'm at wits end to get this sorted out...

I have the attached TIFF. This TIFF has a Clip Path that I want to cut out.

[ZDCF0757.zip](https://github.com/dlemstra/Magick.NET/files/5455242/ZDCF0757.zip)

When I do:
```
            using var magic = new MagickImage("ZDCF0757.tif");
            magic.Clip();
            magic.Write("output.png");
```

I get a clipped image, but it has a white outline. The clip path doesn't match what I see in Photoshop in this case (almost as if it's extended by a few pixels). I presumed this was because the resulting PNG doesn't actually have a alpha-channel if I look at it in Photoshop, meaning the alpha is probably premultiplied which causes the white outline.

No matter what I try, I cannot a proper masked image this way without the white outline.

If I do the following:
```
            magic.Alpha(AlphaOption.Transparent);
            magic.Clip();
            magic.Negate(Channels.Alpha);
```
 The white border is gone and the image seems to respect the path as defined in Photoshop, but the applied path causes aliased lines which look ugly.

After some playing around, I figured out the following:
```
            magic.Alpha(AlphaOption.Extract);
            magic.Clip();
```
I have no idea why this works. After saving, loading it again and then negating it, I'm left with a proper black/white mask which when applied onto the TIFF in Photoshop results in a perfectly smooth cutout.

So me idea was, okay, so far so good, for mysterious reasons I'm left with the actual mask I'm looking for, but I'm not complaining. 

However, I simply cannot find a way to load the original TIFF, enable the alpha channel and replace it with the black/white version :( I've tried numerous of combinations, composition techniques based on command-line example, no matter what I do I just can't get it to work and it's really frustrating me because I know exactly what should happen!

I mean, if this were a Bitmap, I would loop over the pixels and write the values of say the R-channel of the mask as the A-channel of the original.

Could someone please help me figure this out. I don't mind spending hours trying to figure something out, but this, with my previous attempts, has cost me over 8 hours of evening time by now with no results :(

I'm obviously doing something wrong in general, and I'm pretty sure there is a one-pass solution to what I want to achieve, I'm just not seeing it anymore.

**Comment by LennardF1989** [comment]
I just couldn't stand it and gave it a another shot, doing things step by step and, ladies and gentleman, I got him! I'm so proud of myself right now :P Absolute love for ImageMagick, but damn, that took a long time to make sense...

Just for the record, in case other people want to achieve the same thing:
```
                //Enable the alpha layer and set it to fully transparent
                magic.Alpha(AlphaOption.Transparent);

                //Separate the alpha layer from the image
                var result = magic.Separate(Channels.Alpha).First();

                //Set the clip path
                result.Clip();

                //Inverse all colors inside the path
                result.Negate();

                //Copy the resulting mask back into the image as new alpha layer
                magic.Composite(result, CompositeOperator.CopyAlpha);
```

`magic` in this case is the original image which has a clipping path.

**Comment by dlemstra** [comment]
Thanks for coming back to this issue to tell us how you fixed this.
