### ISSUE TITLE
Entry point 'MagickSettings_Depth_Get' not found after update to 7.22.0 from 7.15.1

### ISSUE THREAD

**Issue by ahovland** [dlemstra/Magick.NET#771]
### Description
My Azure api app loads images from Azure blob storage using the MagickImage class. This has worked perfectly with Magick.NET-Q16-AnyCPU version 7.15.1. 

After update to 7.22.1, and without any code changes, the MagickImage constructor now throws an System.EntryPointNotFoundException with the message "Unable to find an entry point named 'MagickSettings_Depth_Get' in DLL 'Magick.Native-Q16-x86.dll'".

### Steps to Reproduce
Stack trace
```
Exception: System.EntryPointNotFoundException
Message: Unable to find an entry point named 'MagickSettings_Depth_Get' in DLL 'Magick.Native-Q16-x86.dll'.
at ImageMagick.MagickSettings.NativeMethods.X86.MagickSettings_Depth_Get(IntPtr instance)
at ImageMagick.MagickSettings.NativeMagickSettings.get_Depth()
at ImageMagick.MagickSettings..ctor()
at ImageMagick.MagickImage..ctor()
```

### System Configuration
- Magick.NET version: 7.22.1
- Environment: Microsoft Azure api app

**Comment by dlemstra** [comment]
It looks like you are using an older version of the `Magick.Native` library. That method was added between those versions.

**Comment by ahovland** [comment]
What do I do to use the newer Magick.Native library?
The Magick.NET 7.22.1 Nuget package depends only on Magick.NET.Core (>= 5.1.0), which is installed automatically (by Visual Studio) when I update to 7.22.1 from 7.15.1.

**Comment by dlemstra** [comment]
The newer native library should be used automatically. But it looks like for some reason your project is using the older version?

**Comment by ahovland** [comment]
When adding Magick.NET-Q16-AnyCPU 7.22.1 to a new and "empty" Visual Studio project using .NET Framework 4.7.2, the following assemblies are added to the bin folders:

**Magick.NET.Core.dll** (file version 5.1.0.0)
**Magick.NET-Q16-AnyCPU.dll** (file version 7.22.1.0)

I can't see any Magick.Native library files.

**Comment by dlemstra** [comment]
I did not see you were using the AnyCPU version of Magick.NET. This means that the native library is embeded inside the `Magick.NET-Q16-AnyCPU.dll` file that is around 17mb. 

Are you setting the `MagickAnyCPU.CacheDirectory` folder yourself? You probably need to empty that folder after an upgrade of Magick.NET otherwise the Native library will not be overwritten.

**Comment by ahovland** [comment]
No, I don't set the MagickAnyCPU.CacheDirectory folder yourself?
What is the default path?

**Comment by dlemstra** [comment]
The default path is %temp% followed by a name depending on the version you are using. In your case that should be `Magick.NET.net40.7.22.1.0`. And I just realized that a while back I changed the code to always create that folder to avoid upgrade issues. I don't understand why your app is using the wrong version of the library.

**Comment by coldwarrior5** [comment]
Have you tried downloading DLLs from https://www.nuget.org/packages/Magick.NET-Q16-AnyCPU/
and https://www.nuget.org/packages/Magick.NET.Core/.
I use these and have no issues so far.
