### ISSUE TITLE
DDS Encoder won't generate mipmaps

### ISSUE THREAD

**Issue by n00mkrad** [dlemstra/Magick.NET#772]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When writing a DDS file, mipmaps are not being generated.

### Steps to Reproduce
Run this:
```cs
var defines = new DdsWriteDefines { Compression = DdsCompression.Dxt1, Mipmaps = 8, FastMipmaps = true };
img.Settings.SetDefines(defines);
string outPath = Path.ChangeExtension(path, null) + ".dds";
img.Write(outPath);
```
The output will not have any mipmaps.

### System Configuration

- Magick.NET version: 7.22.1.0
- Environment (Operating system, version and so on): Windows 10 v2004
- Additional information: Project is on .NET Framework 4.7.2

**Comment by dlemstra** [comment]
What are the dimensions of your input image? They need to be a power of two otherwise no mipmaps will be generated.

**Comment by n00mkrad** [comment]
Thanks, that was the problem.
