### ISSUE TITLE
v7.22.x always returns thumbnail size of JP2 format

### ISSUE THREAD

**Issue by d2phap** [dlemstra/Magick.NET#774]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I recently updated to the latest version, and I found this issue:

![image](https://user-images.githubusercontent.com/3154213/97945945-f7e8f600-1dc3-11eb-811a-1694a9d9163c.png)

When I debug, Magick.NET return the thumbnail size, the MagickSettings is default value in this case.
This does not happen in v7.16.x

![image](https://user-images.githubusercontent.com/3154213/97945776-7f823500-1dc3-11eb-9250-fe2d67ac93e1.png)

### Steps to Reproduce
- Sample: [sample1 (1).zip](https://github.com/dlemstra/Magick.NET/files/5479075/sample1.1.zip)

### System Configuration
- Magick.NET version: 7.22.1
- Environment (Operating system, version and so on): Windows 10 20H2

**Comment by dlemstra** [comment]
Is there anything special in your settings? The folowing unit tests passes without any issues:

```C#
using (var image = new MagickImage(@"I:\issues\magick\774\sample1 (1).jp2"))
{
    Assert.Equal(2717, image.Width);
    Assert.Equal(3701, image.Height);
    Assert.Equal(2717, image.BaseWidth);
    Assert.Equal(3701, image.BaseHeight);
}
```

**Comment by d2phap** [comment]
Thanks and sorry, it's due to the settings!
