### ISSUE TITLE
Merging PDFs Creates Far Too Large a Result

### ISSUE THREAD

**Issue by mlavie** [dlemstra/Magick.NET#78]
I am trying to merge multiple PDFs into a single PDF via AppendVertically(). The resulting PDF file is about 20 times larger than the sum of the individual PDFs.

I did a test in which I only merged a single file (1.2 MB). and the resulting PDF file was **20 times larger** (28.6 MB) than the single file from which it was constructed!

Also, the command:
`MagickImage magickImage = new MagickImage(inputFilePath, magickReadSettings);
`
is **painfully** slow.

Here is my code. I'd appreciate knowing what I am doing wrong. Maybe I really am as stupid as my ex claims!

```
public static MemoryStream MergePdfs
	(
	List<String>	p_inputFilePaths
	)
{
	MemoryStream mergedPdfFile = null;

	try
	{
		MagickReadSettings magickReadSettings = new MagickReadSettings() { Density= new Density(150, 150) };

		using (MagickImageCollection magickImageCollection = new MagickImageCollection())
		{
			foreach (String inputFilePath in p_inputFilePaths)
			{
				MagickImage magickImage = new MagickImage(inputFilePath, magickReadSettings);
				magickImageCollection.Add(magickImage);
			}

			magickImageCollection.AppendVertically();
			mergedPdfFile = new MemoryStream();
			magickImageCollection.Write(mergedPdfFile, MagickFormat.Pdf);
		}
	}
	catch(Exception ex)
	{
		if (mergedPdfFile != null)
		{
			mergedPdfFile.Dispose();
			mergedPdfFile = null;
		}

		throw new XCException(ex, AlertLevel.Standard, "Could not merge multiple PDF files into a single PDF file vertically, due to: " + ex.Message);
	}

	return mergedPdfFile;
}

```

**Comment by dlemstra** [comment]
In think your input PDF file is a vector format file and contains mostly text. When you read that it will be converted to a raster format. When you save the file to disk it will remain in the raster format and result in a much larger file. If your goal is to merge PDF files you might want to look for another tool.

**Comment by mlavie** [comment]
OK - thank you for the explanation.
