### ISSUE TITLE
Gradient Caption Magick.NET

### ISSUE THREAD

**Issue by Nihaarn1997** [dlemstra/Magick.NET#781]
Hi,
I am working on a C# project which currently invokes IM commands for creating images with titles. I'm now switching over to using Magick.NET.
Having trouble converting the following command to Magick.NET - 
convert -size 374x550 -background none -font "PathToFontFile" -gravity center caption:"Title" ( -clone 0 -alpha opaque -sparse-color Barycentric "0, 0 #070504  %[fx:w-1],0 #000000" ) ( -clone 0 -alpha transparent ) -reverse -compose dstover -composite "PathToLocation"

I'd really appreciate any help as I have been stuck on this for weeks now.

Thanks
Nihaar Nandedkar

(Note: Below is an example of what I am trying to achieve)
![hEDTOverlay#cdcd37#37cdffRubik-Medium](https://user-images.githubusercontent.com/74175275/98669756-c221af80-2377-11eb-9acd-80021ceaac2f.png)

**Comment by dlemstra** [comment]
What have you tried so far? At what point are you stuck?

**Comment by Nihaarn1997** [comment]
What we have tried:
1. Successfully overlaid gradient text over an image using the IM command as stated in the issue
2. Overlay single color text over an image using the read() and composite() methods of Magick.NET


Where we are stuck:
1. Switching over from using IM commands to Magick.NET library
2. Below is an example of how we achieved vertical, horizontal and arc gradient overlay text

convert -size 374x550 -background none -font "PathToFontFile" -gravity center caption:"Nations Cup" ( -clone 0 -alpha opaque -sparse-color Barycentric **"0, 0 #070504  %[fx:w-1],0 #000000"** ) ( -clone 0 -alpha transparent ) -reverse -compose dstover -composite "PathToLocation"

convert -size 374x550 -background none -font "PathToFontFile" -gravity center caption:"Nations Cup" ( -clone 0 -alpha opaque -sparse-color Barycentric **"0, 0 #070504  0,%[fx:h-1], #000000"** ) ( -clone 0 -alpha transparent ) -reverse -compose dstover -composite "PathToLocation"

convert -size 374x550 -background none -font "PathToFontFile" -gravity center caption:"Nations Cup" ( +clone -sparse-color Barycentric **"0, %h #070504  %w,0 #000000"** ) -compose In -composite -virtual-pixel transparent -distort arc 80 ( +clone -background none -shadow 100x2+4+4 ) +swap -background none -compose over -layers merge +repage "PathToLocation"

3. The gradient effect (vertical, horizontal & arc) requires 2 colors as input and a few other parameters along with it, not sure how to pass to to the below code

                MagickReadSettings settings = new MagickReadSettings();
                settings.FillColor = MagickColor.FromRgb(r, g, b);
                settings.Font = ConfigurationManager.AppSettings["fontpath"] + singleFont.SystemFontName;
                settings.Width = writableDetails.WidthWritable;
                settings.Height = writableDetails.HeightWritable;
                settings.BackgroundColor = MagickColor.FromRgba(255, 255, 255, 0);
                settings.TextGravity = Gravity.Center;
                settings.TextInterlineSpacing = writableDetails.InterlineSpace;

**Comment by dlemstra** [comment]
The example command that you have does not create the sample image that you provided? Here is a translation of your first command:

```
convert -size 374x550 -background none -font "PathToFontFile" -gravity center caption:"Nations Cup"
( -clone 0 -alpha opaque -sparse-color Barycentric "0, 0 #070504 %[fx:w-1],0 #000000" )
( -clone 0 -alpha transparent ) -reverse -compose dstover -composite "PathToLocation"
```

```C#
var readSettings = new MagickReadSettings
{
    // -size 374x550
    Width = 374,
    Height = 550,

    // -background none
    BackgroundColor = MagickColors.None,

    // -font "PathToFontFile"
    Font = "PathToFontFile",

    // -gravity center
    TextGravity = Gravity.Center,
};

// caption:"Nations Cup"
using (var image = new MagickImage("caption:Nations Cup", readSettings))
{
    // -clone 0
    using (var clone1 = image.Clone())
    {
        // -alpha opaque
        clone1.Alpha(AlphaOption.Opaque);

        // -sparse-color Barycentric "0, 0 #070504 %[fx:w-1],0 #000000"
        var sparseColorArgs = new[]
        {
            // 0, 0 #070504
            new SparseColorArg(0, 0, new MagickColor("#070504")),

            // %[fx:w-1],0 #000000
            new SparseColorArg(image.Width - 1, 0, new MagickColor("#000000")),
        };

        // -sparse-color Barycentric
        clone1.SparseColor(SparseColorMethod.Barycentric, sparseColorArgs);

        // -clone 0
        using (var clone2 = image.Clone())
        {
            // -alpha transparent
            clone2.Alpha(AlphaOption.Transparent);

            // -reverse changes the order of the images. The order was:
            // image, clone1, clone2 but this is not clone2, clone1, image.

            // -compose dstover -composite
            // Because there are there images some special magick is happening.
            using (var clone3 = clone2.Clone())
            {
                clone2.Composite(clone1, CompositeOperator.DstOver);

                clone2.Composite(image, CompositeOperator.CopyAlpha);

                clone3.Composite(clone2, CompositeOperator.Over);

                // "PathToLocation"
                clone3.Write("PathToLocation");
            }
        }
    }
}
```

Feel free to ask if you have any further questions.

**Comment by Nihaarn1997** [comment]
Thanks for the help, the above code worked perfectly for both horizontal and vertical gradient effects.
Replaced 
```

if (gradient_vertical)
                sparseColorArgs[1] = new SparseColorArg(0, imgMain.Height - 1, new MagickColor(singleColor2.TextColor));
else if (gradient_horizontal)
                sparseColorArgs[1] = new SparseColorArg(imgMain.Width - 1, 0, new MagickColor(singleColor2.TextColor));
```
We need help with overlaying the caption in an arc where we pass the angle of arc as parameter to the IM command. Below is the command for it

convert -size 374x550 -background none -font "PathToFontFile" -gravity center caption:"Nations Cup" ( +clone -sparse-color Barycentric "0, %h #070504 %w,0 #000000" ) -compose In -composite -virtual-pixel transparent -distort arc 80 ( +clone -background none -shadow 100x2+4+4 ) +swap -background none -compose over -layers merge +repage "PathToLocation"

Can you please help us in translating this command to Magick.NET code?

**Comment by dlemstra** [comment]
What have you tried yourself and where are you stuck?
