### ISSUE TITLE
I keep getting weird � characters?

### ISSUE THREAD

**Issue by PtrStruct** [dlemstra/Magick.NET#783]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

So I'm currently loading a PSD file and I'm processing each layer, however some layers are named like this 
`Copyright © 2020`

And the `©` becomes a  `�` when I try to grab the `.Label` property.
Is there some encoding property I'm missing or what's a good way of dealing with this?
### Steps to Reproduce

```
var psdPath = "...";
using (var image = new MagickImageCollection(psdPath))
            {
forreach(var img in image)
//This is where I grab the label
//if the layer is named something like Copyright © 2020 the `©` becomes a  `�` 
var text = img.Label;
}
```

### System Configuration

- Magick.NET version: Latest
- Environment (Operating system, version and so on): Windows 10 20H2
- Additional information:

**Comment by dlemstra** [comment]
Currently ImageMagick only support ASCII layer names. Can you share an image that has an UTF8 (or other on ASCII) layer name? I could investigate if we could somehow add support for this.

**Comment by dlemstra** [comment]
Looks like support for this was already added: https://github.com/dlemstra/Magick.NET/discussions/620#discussioncomment-8943.
