### ISSUE TITLE
Creation of MagickImage from byte[] fails

### ISSUE THREAD

**Issue by topmotive-oliverappel** [dlemstra/Magick.NET#785]
I found a problem that a MagickImage could not be created from a byte[] from version > 7.20.1. The following  code throws an exception 
`ImageMagick.MagickCorruptImageErrorException: length and filesize do not match`
While on a first glance it looks like the image is corrupt, I need to say the image loads fine in different image viewers, etc.
`var i = File.ReadAllBytes("..\845.bmp")
MagickImage image = new MagickImage(imageData)`

- Magick.NET version: > 7.20.1
- Environment: .NET Framework 4.8

Full exception:
`ImageMagick.MagickCorruptImageErrorException: length and filesize do not match ' @ error/bmp.c/ReadBMPImage/845
at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
at ImageMagick.MagickImage.NativeMagickImage.ReadBlob(IMagickSettings1 settings, Byte[] data, Int32 offset, Int32 length)
at ImageMagick.MagickImage.Read(Byte[] data, Int32 offset, Int32 length, IMagickReadSettings1 readSettings, Boolean ping)
at ImageMagick.MagickImage.Read(Byte[] data, IMagickReadSettings1 readSettings)`

**Comment by dlemstra** [comment]
This is happening due to an extra check that was added to validate if the `BMP` is correct. You could use `BmpReadDefines` and set `IgnoreFileSize` to true to allow reading those invalid files.

**Comment by topmotive-oliverappel** [comment]
Thanks @dlemstra, for your fast response! I wonder if you could point me in the direction on an example? BmpReadDefines does not seem to implement IReadDefines.

**Comment by topmotive-oliverappel** [comment]
@dlemstra, Forget it, I have found what I was looking for Thanks for your help!

**Comment by dlemstra** [comment]
Thanks for your remarkt it appears that the `BmpReadDefines` class inherits from the wrong base class. This will be resolved in the release that will be published later today.
