### ISSUE TITLE
Improve processing speed for CMYK colorspace

### ISSUE THREAD

**Issue by bolekro** [dlemstra/Magick.NET#786]
Firstly, thank you for your work on this great library!

### Is your feature request related to a problem? Please describe
I am using Magick.NET to save Bitmap (already in CMYK) as a tiff CMYK (colorspace = ColorSpace.CMYK):

```C#
Stopwatch timer = new Stopwatch();
timer.Start();
MemoryStream stream = new MemoryStream();
Console.WriteLine($"Stream {timer.ElapsedMilliseconds}");
bmp.Save(stream, System.Drawing.Imaging.ImageFormat.Bmp);
Console.WriteLine($"bmp.Save {timer.ElapsedMilliseconds}");
stream.Position = 0;
testImg.Read(stream, MagickFormat.Bmp);
Console.WriteLine($"testImg.Read {timer.ElapsedMilliseconds}");
testImg.Density = new Density(dpi, dpi);
Console.WriteLine($"testImg.Density {timer.ElapsedMilliseconds}");
testImg.Format = MagickFormat.Tiff;
Console.WriteLine($"testImg.Format {timer.ElapsedMilliseconds}");
testImg.ColorSpace = colorSpace;
Console.WriteLine($"testImg.colorSpace {timer.ElapsedMilliseconds}");
testImg.Write(path)
```

The time it takes to process the setting of ColorSpace.CMYK is ca. 2.4s on i9-9940X 16GB RAM (my images are 90Mpx, 360DPI), which is killing a time sensitive application at the moment:

![image](https://user-images.githubusercontent.com/7785455/99515851-c6f4ed80-298d-11eb-9d54-c18134dfeace.png)

### Describe the solution you'd like
Improvement in the processing time with CMYK colorspace or any suggestion how to improve it on my side, ideally to reduce it below 500ms.

**Comment by dlemstra** [comment]
Next time you could use ` ` ` (without the spaces) to create a multi line code block. I now also just realized a new use case where a user could to `bitmap.ToMagickImage()` to avoid the encoding and decoding. Will take a look at your question later this week.

**Comment by dlemstra** [comment]
Is it possible to share your input image?

**Comment by dlemstra** [comment]
What happens when you use `testImg.Read(bmp)` instead? This requires the `Magick.NET.SystemDrawing` library.

**Comment by bolekro** [comment]
1. I cannot share the exact image but will create a synthetic one with a similar processing time.
2. Which method overload would that be? My "bmp" is System.Drawing.Bitmap not read from a file but generated in a machine vision pipeline.

**Comment by dlemstra** [comment]
The overload is an extension method that you will get when you install the `Magick.NET.SystemDrawing` library in your project. It might be interesting to add an optimization there by copying the pixels when the format is a memory mapped image.

**Comment by bolekro** [comment]
Thanks for the suggestion, `testImg.Read(bmp)` simplified the code and is on avg. 140ms faster.

**Comment by dlemstra** [comment]
Please share your image so I can take a look if it is possible to improve the performance.

**Comment by dlemstra** [comment]
Ping @bolekro.
