### ISSUE TITLE
Calling Optimize on gif throw error

### ISSUE THREAD

**Issue by mhamri** [dlemstra/Magick.NET#79]
```images are not the same size `C:/Users/me/AppData/Local/Temp/magick-13572-QYoWi7zZxm6' @ error/layer.c/OptimizeLayerFrames/968```

```
   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.Optimize(IMagickImage image)
   at ImageMagick.MagickImageCollection.Optimize()
   at xxx.xxxInfrustructure.MagickNetHelper.SaveAsGif(String fileNameAndPath) in C:\Users\me\documents\visual studio 2017\Projects\xxxx\xxxxx\Infrustructure\MagickNetHelper.cs:line 69
   at xxx.xxx.Models.ImageCache.SaveToCacheAsync(String fileId, Stream file) in C:\Users\me\documents\visual studio 2017\Projects\xxxx\xxxxx\Models\ImageCache.cs:line 73
```

my code : 

```C#
public void Load(Stream fileStream,string fileNameAndPath)
        {
            _imageMagick = new MagickImageCollection(fileStream);
            _imageMagick.Optimize();
            _imageMagick.Write(fileNameAndPath);
        }
```
I'm getting this error while when I load the gif, and loop thorugh the images, all of them are 300x300. but after calling .Optimize(), I'm getting this error.
according to [this link](http://www.imagemagick.org/Usage/anim_opt/#semitrans_opt) i should be able to call it, also I couldn't find anything equivalent with `-layers OptimizeFrame`.

any suggestion how should I call in which order to optimize the gif to decrease its size without loosing so much of quality?

**Comment by dlemstra** [comment]
Can you add a link to your gif image?

**Comment by mhamri** [comment]
I'm testing with this one

https://drive.google.com/file/d/0B6-EFvM-Pvk8UXJFWkRkNk80Wkk/view?usp=sharing

**Comment by dlemstra** [comment]
I just tried the code below with your test image and it create an output image.

```C#
using (FileStream fs = File.OpenRead(@"i:\gif\cat-original.gif"))
{
    using (MagickImageCollection images = new MagickImageCollection(fs))
    {
        images.Optimize();
        images.OptimizeTransparency();
        images.Write(@"i:\gif\test.gif");
    }
}
```

I don't get your exception. Are your sharing your `_imageMagick` list with other threads? Or are you reusing the collection?

I also had to call `images.Coalesce();` before `images.Optimize()` because your test image is already optimized and would result in an incorrect image if you don't do that.

**Comment by dlemstra** [comment]
Did you solve your issue @mhamri ?

**Comment by mhamri** [comment]
Yes, but one thing is missing from your code is the usage of the
images.Coalesce();

Would you please put the full code here

**Comment by tomasr78** [comment]
Why not to merge images.Coalesce(); and images.Optimize(); to one method? Does using images.Coalesce(); on all gifs even if they are not optimized has any side effect? 

I also got `images are not the same size` when re-saving animated gif using magick.net.

**Comment by dlemstra** [comment]
I don't understand what you are trying to ask @tomasr78. And those two methods will not be combined because you can use them together but also ony use `Optimize`.
