### ISSUE TITLE
Docker-Win .NET Core 3.1 Unable to load DLL 'Magick.Native-Q8-x64.dll' or one of its dependencies

### ISSUE THREAD

**Issue by nfMalde** [dlemstra/Magick.NET#792]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I found many issues regarding this but the solutions that helped others in .NET Core 2.2
Im using Windows Container with image of  "mcr.microsoft.com/dotnet/core/aspnet:3.1".

I also did the step descripbed here to set the NativeLibPath:
```
string nativeDir = System.IO.Path.Combine(dir, "runtimes", "win-x64", "native");
ImageMagick.MagickNET.SetNativeLibraryDirectory(nativeDir);
```
Im still getting the error "Unable to load DLL 'Magick.Native-Q8-x64.dll'" and cant find any error in my dockerfile:
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base 
WORKDIR /app
EXPOSE 80
EXPOSE 443


FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build 
WORKDIR /src
COPY ["Web/MyWebApp/MyWebApp.csproj", "Web/MyWebApp/"]
# Copy last successfull build of ngapp
COPY ["Tools/MyApp/MyApp.csproj", "Tools/MyApp/"]

RUN dotnet restore "Web/MyWebApp/MyWebApp.csproj"
RUN dotnet restore "Tools/MyApp/MyApp.csproj"
WORKDIR /src/
COPY . .
WORKDIR /src/Tools/MyApp
RUN dotnet build   "MyApp.csproj" -c Release -o /app/build-m
WORKDIR "/src/Web/MyWebApp"
RUN dotnet build "MyWebApp.csproj" -c Release -o /app/build


FROM build as consoleAppPublish
WORKDIR /src/Tools/MyApp 
RUN dotnet publish "MyApp.csproj" -c Release -o /console-app/publish 

FROM build as apppublish
WORKDIR /src/Web/MyWebApp 
RUN dotnet publish "MyWebApp.csproj" -c Release -o /app/publish

WORKDIR /app/publish/ClientApp/dist
COPY --from=build /src/Web/ngapp .

FROM base as final

WORKDIR /app/
COPY --from=apppublish /app/publish .
COPY --from=consoleAppPublish /console-app/publish /app/consoleapp 
COPY --from=build /src/Web/MyWebApp/start-apps.bat .
ENTRYPOINT ["start-apps.bat"]
```
### Steps to Reproduce
Deploy an App referencing to "Magick.NET-Q8-x64"

### System Configuration

- Magick.NET version:Magick.NET-Q8-x64 7.22.2.1
- Environment (Operating system, version and so on): Docker, Windows Container, mcr.microsoft.com/dotnet/core/aspnet:3.1
- Additional information:

**Comment by dlemstra** [comment]
Can you create a small sample project on GitHub that demonstrates this issue? Also not clear to me why you need to do `SetNativeLibraryDirectory`. Are you sure that the native library is in that folder?

**Comment by nfMalde** [comment]
Hi!  I set the NativeDir cause it was a solution for some who had the same issue :-) I made a test project with both cases. Setting the native dir and letting it at default.
https://github.com/nfMalde/MagickTest-3-1

Double checked it in both cases the native/ dll  exists. Maybe the docker container is thinking he has to look at a different runtime folder?

Best,
Malte

**Comment by IcoDeveloper** [comment]
Any news on this?  I'm running into the same issue - both with and without SetNativeLibraryDirectory and with doublechecking that the Magick.Native-Q8-x64.dll actually is in the specified directory.

some more input that might be relevant: 

```
> dumpbin /dependents Magick.Native-Q8-x64.dll
Image has the following dependencies:

    KERNEL32.dll
    WS2_32.dll
    USER32.dll
    ADVAPI32.dll
    urlmon.dll
    gdiplus.dll
    bcrypt.dll
    GDI32.dll
    SHELL32.dll
    ole32.dll
    OLEAUT32.dll
    DNSAPI.dll
    IPHLPAPI.DLL
```
of these, urlmon.dll and gdiplus.dll seem to be missing in the mcr.microsoft.com/dotnet/core/aspnet:3.1 image. 
This suggests that a different docker image is required to actually run Magick.net; any ideas what might work here would be greatly appreciated.

**Comment by IcoDeveloper** [comment]
And some more info: the mcr.microsoft.com/dotnet/aspnet image is based off nanoserver, which does not include gdiplus. So far, it doesn't look possible to add gdiplus to nano server just by copying in a couple of dlls.

What does work is using an image based on server core, with the obvious downside of increasing image size to about 5GB.

While there is no official MS image for 3.1 based on server core, there is one for 5.0.

I've successfully verified that using `FROM mcr.microsoft.com/dotnet/aspnet:5.0-windowsservercore-ltsc2019 AS base` no longer throws an exception initializing Magick.Net

If you want a differnt version of the runtime (like 3.1) you'll have to create your own image - you can base it on the [MS dockerfile for 5.0](https://github.com/dotnet/dotnet-docker/blob/master/src/aspnet/5.0/windowsservercore-ltsc2019/amd64/Dockerfile)

**Comment by nfMalde** [comment]
Thanks!  Basing on servercore Magick.NET and other image processing libs work.
