### ISSUE TITLE
Strange bug while trying to get a hex color by histogram.

### ISSUE THREAD

**Issue by Marko97IT** [dlemstra/Magick.NET#799]
How to reproduce the bug:
```
using (MagickImage Image = new MagickImage(ImageBlob))
{
    Dictionary<IMagickColor<ushort>, int> Histogram = Image.Histogram();
    IMagickColor<ushort> DominantColor = Histogram.Aggregate((x, y) => x.Value > y.Value ? x : y).Key;
    Console.WriteLine(string.Format("#{0}{1}{2}", DominantColor.R.ToString("X2"), DominantColor.G.ToString("X2"), DominantColor.B.ToString("X2")));
}
```
The output will be #**B9**B9**B2**B2**7E**7E while it should be #B9B27E.
Adding .Substring(2) after ToString("X2") solves the problem.

The same problem also occurs using:
`Console.WriteLine("#" + DominantColor.ToShortString());`

therefore I think the problem is on the Histogram method.

Magick.NET Q16 AnyCPU v7.22.2.2

**Comment by dlemstra** [comment]
This is not a bug but a feature. You are using the`Q16` version of Magick.NET and this means that the `MagickColor` has 16-bits per channel `B9B9`, `B2B2` and `7E7E`. I don't mind introducing an extra method that will only use the 8-bit version of the color but I have no idea what name this method should have.

**Comment by Marko97IT** [comment]
.GetHexColor8bit()
.ToHexColor8bit()

**Comment by dlemstra** [comment]
Decided to call it `ToHexString` instead. And this will become available in the next release.
