### ISSUE TITLE
Question - how to use gravity/center in .net?

### ISSUE THREAD

**Issue by philDGit** [dlemstra/Magick.NET#80]
I have used the command line, including a Gravity center option. I just installed Magick.NET-Q8-x64 with NuGet to my .net project, and I can't figure out how to use the gravity/center option. I have an image that when resized, causes some "white space" on the left edge (due to preserving the ratio), but I'd like to have the image centered so that half of the white space is on the left, and half on the right. From the command line it works as I want it to, but how do I specify the options to get this result in .net?

**Comment by dlemstra** [comment]
What are the command line commands that your are using? I might be able to help you translate this to .NET. But it might just be enough for you to set `image.Settings.TextGravity`.

**Comment by philDGit** [comment]
Thanks for the quick reply.

Here are the switches we use:

-resize  559x287 -quality 60   -gravity center -extent 559x287

**Comment by dlemstra** [comment]
`-gravity center -extent 559x287` translates to this:

```C#
image.Extent(559, 287, Gravity.Center);
```

**Comment by philDGit** [comment]
Thank you.  That worked.

Phil D
