### ISSUE TITLE
Running on Mac with Mono (net47) requires copying native library to bin and stripping dylib from filename

### ISSUE THREAD

**Issue by APIWT** [dlemstra/Magick.NET#802]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If you include any variant of Magick.NET in a CSPROJ file (via a nuget reference) and attempt to run on Mac (when using Mono), the application will fail (with either a DllNotFoundException or an EntryPointNotFoundException depending on the variant used). However, if you copy the native binary from the nupkg into the bin directory and rename the file to drop the `.dylib` extension, it runs fine.

### Steps to Reproduce
1. Create a console application targeting .NET 4.7/4.8 on a Mac (Rider or Visual Studio are fine)
2. Add a reference to any variant of Magick.NET nuget package into the CSPROJ.
3) Add some code in the program entry point (ie: `var x = new MagickImage();`) to force the library to load.
4) The application crashes.

### System Configuration
I am using OSX 10.15.7 with the latest version of Mono installed.

- Magick.NET version: 7.22.2.2
- Environment (Operating system, version and so on): OSX 10.15.7, Mono, .NET Framework 4.7 target
- Additional information: I started by trying the AnyCPU package, but it was failing so I ended up switching to the architecture-specific packages. Same issue, same workaround.

**Comment by APIWT** [comment]
After some experimenting, I have a hypothesis as to what might be happening.

If I follow the repro steps, there is already a native file in my bin directory, but it appears to be the Windows version of the native binary rather than the Mac version. Therefore, when I take the `dylib` from the `nupkg` and manually copy/rename it into my `bin` directory, it is actually replacing the Windows DLL with the Mac version.

I was able to figure this out by comparing the file sizes. The Windows version clocks in at 20.3 MB, where the Mac version is 29.2 MB.

I'm not super strong with debugging the build targets, but is it possible that it is something going on with this part?

**Comment by APIWT** [comment]
@dlemstra Thanks for looking into this!

I'm actually working around this by piping the output of our `net47` application into a `netcoreapp` application (which has the ability to use `Magick.NET`, but it would be cool to support it without this workaround.

I'd love to move the `net47` app to `netstandard`, but I don't think it is possible currently since it is a `Xamarin.UITest` project.

Should we keep the issue open for future readers/contributors? I've found my workaround for now but I have a feeling it will be a bit anticlimactic for others.

**Comment by dlemstra** [comment]
Closing this now since direct support for `net40` has been removed.

**Comment by fabiomaulo** [comment]
The problem here is that `net40` or `net461` or `net472` are **not supposed** to work with Mono or outside of Windows.
The right, not supported, target is `monomac`.
BTW I'll open another issue to support, at least, `net40` for new versions. (if @dlemstra can make me a favor)
