### ISSUE TITLE
In the PowerShell script, Why need to use two DLL files?

### ISSUE THREAD

**Issue by kyjdp** [dlemstra/Magick.NET#804]
I am using Magick.net features in PowerShell scripts.

but, I found that, successfully run the script, I need to use two DLL files,
Magick.NET.Core.dll
Magick.NET-Q16-AnyCPU.dll

If I only use a DLL【Magick.NET-Q16-AnyCPU.dll】 file, it will prompt the error.
I tried it a few years ago, only one DLL can also be successfully run.

I recorded a video demo in the link below.
https://www19.zippyshare.com/v/fVRvFmNh/file.html

powershell Code:

```
Add-Type -Path ".\Magick.NET-Q16-AnyCPU.dll"

$image = New-Object ImageMagick.MagickImage ".\bg.jpg"

$image.Format = 'jpeg'
$image.Quality = 99
$image.Write(".\bg-q99.jpg")

$image.Dispose()

```
Dll ver: 7.22.2.2

All related files:
https://www76.zippyshare.com/v/Oq133tZS/file.html

Can I use only one DLL? which DLL file is it?

My programming level, English expression is not very good,  it may describe the mistake, thanks for developer's hard work, thank you in advance

**Comment by dlemstra** [comment]
The `Magick.NET.Core` library is a dependency of `Magick.NET-Q16-AnyCPU` library so they both need to be in the same folder.
