### ISSUE TITLE
Set border color is invalid, in PowerShell

### ISSUE THREAD

**Issue by kyjdp** [dlemstra/Magick.NET#805]
Set border color is invalid, in PowerShell, I recorded a video demo

https://www108.zippyshare.com/v/4YXX6NTB/file.html

Powershell Code:

```
Add-Type -Path ".\Magick.NET-Q16-AnyCPU.dll"

$image = New-Object ImageMagick.MagickImage ".\bg.jpg"

$image.Border(50)

$image.BorderColor = #ffff00

$image.Write(".\bg-border.jpg")

$image.Dispose()
```

**All relevant documents:**
https://www.upload.ee/files/12630987/border.zip.html

**Comment by APIWT** [comment]
@kyjdp I could be completely wrong, but I think it might be the syntax of border color. Try this:
```
Add-Type -Path ".\Magick.NET-Q16-AnyCPU.dll"

$image = New-Object ImageMagick.MagickImage ".\bg.jpg"

$image.Border(50)

$image.BorderColor = "#ffff00"

$image.Write(".\bg-border.jpg")

$image.Dispose()
```

**Comment by dlemstra** [comment]
I think you will need to do this instead:

`$image.BorderColor = New-Object ImageMagick.MagickColor "#ffff00"`

Not sure if that is proper powershell syntax though

**Comment by kyjdp** [comment]
@APIWT @dlemstra 
Thank you for your reply. The above two methods are not effective. It's strange

**Comment by dlemstra** [comment]
Closing this now because I have no idea how to resolve this in powershell. Who ever finds this issue and finds a solution please leave a reply below.
