### ISSUE TITLE
Supporting Guetzli compression ? 

### ISSUE THREAD

**Issue by meysamSamanpour** [dlemstra/Magick.NET#81]
Guetzli is the new JPEG compression encoder introduced by google. It can be up to 35% more effective. If Magick.Net can support this kind of compression then it would be great because of of the ranking factor in google for a webpage is how much effectively did you compressed your images and if you use the new technique then you will get better rank. So supporting this encoder can be a big change and advantages. 

https://arstechnica.com/information-technology/2017/03/google-jpeg-guetzli-encoder-file-size/

**Comment by dlemstra** [comment]
We had a discussion about this in the ImageMagick repository: https://github.com/ImageMagick/ImageMagick/issues/403. I don't think this will be a build in feature in ImageMagick anytime soon. I do think that someone (maybe even me) could create a Guetzli.NET project that could do this. I would see this as a separate library.

**Comment by meysamSamanpour** [comment]
Thanks for the reply. Yes you right this cannot be in the Magick.Net library. I have a question which maybe is not 100% related to this topic but what is the best way to compress an image using jpg encoder I have this question because Google analyzer suggested me that I can compress up to 50 percent my pictures. I am using Magick.net and I compress them something like this 

```
 image.Format = MagickFormat.Jpeg;
 image.Quality = 80;
 image.Write(@"d:\temp\magickOutPut_80.jpg"); 
```

is there anything I am missing? or should I worried about something else ?

**Comment by dlemstra** [comment]
Have you tried the `ImageOptimizer`? This class was introduced to stop the Google analyzer complaining about optimizing images. I think you now need the `Compress` method instead of the `LosslessCompress` method.

**Comment by meysamSamanpour** [comment]
I am creating new file with MagickImage and then composite some jpg on it and then save it on HDD. Is there any way that I can optimise the MagickImage object in memory ?  because I am saving the image on s3 for if I wanted to run the compress on HDD I need to save it on server and then save it again on S3. and one other question in the new version of Magick.Net the compress does not have the quality parameter? 
thanks again

**Comment by dlemstra** [comment]
The quality parameter is only available in the `JpegOptimizer` and not in the `ImageOptimizer` because its JPEG specific.

Can you copy a `MemoryStream` to S3? I have another issue to add support for `Stream`s in the ImageOptimizers.

**Comment by meysamSamanpour** [comment]
yes I we can save MempryStream into the S3 actually this is the way we already save images on S3. Thanks for considering to support this feature.

**Comment by meysamSamanpour** [comment]
I found out that my approach was wrong. I was loading the already compressed jpeg files and then compress them again and save them back so google would not accept these kind of files. But when I create Png and add those files on it and compress it then google accept it as a proper compression.
