### ISSUE TITLE
Cannot get EXIF data from tiff images by GetExifProfile

### ISSUE THREAD

**Issue by hn24** [dlemstra/Magick.NET#811]
### Prerequisites
- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of ImageMagick
- [x] I have searched open and closed issues to ensure it has not already been reported

### Description
Hi, I'm going to get exif data from images by GetExifProfile method, it works fine with the JPEG files, but it always return null for tiff

### Steps to Reproduce
1. Download some images from https://github.com/ianare/exif-samples/tree/master/tiff
2. Use this code:
> var tiff = @"[image path]";
> using var document = new MagickImage(tiff);
> var exifProfile = document.GetExifProfile();
3. Look at the **exifProfile** , it's null

### System Configuration

- ImageMagick version: latest
- Environment (Operating system, version and so on): Windows

**Comment by dlemstra** [comment]
Those files contain no aditional EXIF data and if they did it would be stored on the image as an `exif:` atribute instead.
