### ISSUE TITLE
new MagickImage(file.FileInfo) fails to understand long path naming on UNC drives (\\?\).

### ISSUE THREAD

**Issue by duckheadsoftware** [dlemstra/Magick.NET#823]
### Prerequisites

- [x] I have written a descriptive issue title
- [x ] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
When trying to open a file using FileInfo, all is well for local hard drives, even when using long filename support (\\?\), however, for UNC paths, this fails (fileinfo object returns the path as \\?\\server\folder)

### Steps to Reproduce
Open a UNC photo where the FileInfo object is using long filename support.

- Magick.NET version: Magick.NET.SystemWindowsMedia 3.0.2, Magick.NET-Q8-x64 7.22.2.2
- Environment (Operating system, version and so on): Windows 10 20H2 64-bit, 
- Additional information: unc share is on ip4 network via cable

**Comment by dlemstra** [comment]
For long file name you will need two backslashes? Should this not be `\\?\server\folder` instead? And ImageMagick will automatically add those backslashes and the question mark when it detects the filename exceeds the length. But it doesn't seem to check if the path already contains this. Just pushed a patch the the ImageMagick repository to fix this.

**Comment by duckheadsoftware** [comment]
Thanks, the fileinfo object works with all other IO functions, it already has all the \\?\ bits correctly. Thanks for the patch.
