### ISSUE TITLE
MagickSearchResult X and Y are 0 when using SubimageSearch

### ISSUE THREAD

**Issue by Lazygeek1981** [dlemstra/Magick.NET#825]
Hello,

I'm a big fan of Magick.NET but I think I've encountered a bug today when using the SubImageSearch() function for the first time.

### Description
When starting the subimage search from the command line I got ``` @ 200,118 ``` as the best matching coordinates which is the expected answer.

When calling the same method from my code with 

`using var subimage = new MagickImage("subimage.jpg");`
`using (var image = new MagickImage(imageFile))`
`{`
` var subimageCoords = image.SubImageSearch(subimage);`
` }`

the subimageCoords.BestMatch.X and subimageCoords.BestMatch.Y properties are 0 while BestMatch.Width and BestMatch.Height is filled correctly.

Am I missing something here? I would expect the results to be the same as when using the command line version of ImageMagick

### Steps to Reproduce
1. Start a subimage-search from the command line
2. Start a subimage search from a .net core command line project using the same images
3. Compare the results.

### System Configuration
- Magick.NET version: Magick.NET-Q16-AnyCPU 7.22.2.2
- .net core 3.1 console application
- Windows 10 64bit

**Comment by dlemstra** [comment]
Can you share some tests images so I can reproduce this easier?

**Comment by Lazygeek1981** [comment]
Ok, now I'm confused. I started to put together some test image for you and now it's working as expected. ¯\\_(ツ)_/¯ 
The only difference is that the code in my original post is shortened and I took out some cropping.
Seems like with "in memory" cropping it's not working and without cropping it works fine.

So the following code produces the unexpected behavior.
```
           using var subimage = new MagickImage(@"C:\Users\chris\Desktop\Images\subimage.jpg");
           using (var image = new MagickImage(@"C:\Users\chris\Desktop\Images\large.jpg"))
            {
                image.Crop(new MagickGeometry(240, 350, 680, 350));
                var subimageCoords = image.SubImageSearch(subimage);
            }
```
![subimagesearchwithcropping](https://user-images.githubusercontent.com/2317406/103374359-b2049180-4ad7-11eb-970f-d01279e83256.png)

While cropping the image, saving it to disk and then loading the cropped image works fine with subimage search.
```
            using var subimage = new MagickImage(@"C:\Users\chris\Desktop\Images\subimage.jpg");
            using (var image = new MagickImage(@"C:\Users\chris\Desktop\Images\notsolarge.jpg"))
            {
                var subimageCoords = image.SubImageSearch(subimage);
            }
```
![subimagesearchwithoutcropping](https://user-images.githubusercontent.com/2317406/103374427-dceee580-4ad7-11eb-9f4a-db90f2c52182.png)

So I will just do the cropping in advance and load the cropped images from a temp folder. 

Any ideas why this is happening?

Here are the images I'm working with plus the cmd line results.

Large image:
![large](https://user-images.githubusercontent.com/2317406/103374437-e4ae8a00-4ad7-11eb-8437-af56ad838bda.jpg)
Not so large image:
![notsolarge](https://user-images.githubusercontent.com/2317406/103374441-e5dfb700-4ad7-11eb-9855-b5bc659eba8d.jpg)
Cmd line results:
![notsolarge_result_cmd-0](https://user-images.githubusercontent.com/2317406/103374443-e6784d80-4ad7-11eb-854f-fb8e84cedd24.jpg)
Cmd line results 2:
![notsolarge_result_cmd-1](https://user-images.githubusercontent.com/2317406/103374444-e6784d80-4ad7-11eb-8602-12364ff414ea.jpg)
Subimage:
![subimage](https://user-images.githubusercontent.com/2317406/103374446-e710e400-4ad7-11eb-911d-86a8a7e8ffd9.jpg)

**Comment by dlemstra** [comment]
It seems that the issue is that after the `Crop` operation the `Page` of the `image` is set. Calling `image.RePage()` resolves that issue. It is a bit strange that you don't need that on the command line though.

**Comment by Lazygeek1981** [comment]
Happy new year :-) and thanks a lot for your response. So this isn't a bug at all. I changed my code accordingly and everything is working now as expected.
