### ISSUE TITLE
JPEG XL ignores quality setting and only works in lossless mode

### ISSUE THREAD

**Issue by n00mkrad** [dlemstra/Magick.NET#828]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Encoding JPEG XL images ignores the quality setting and always uses lossles mode, even though the reference library should support lossy compression.

### Steps to Reproduce
Convert an image to JPEG XL with different MagickImage.Quality values

### System Configuration

- Magick.NET version: 7.22.3
- Environment (Operating system, version and so on): Windows 10 v2004
- Additional information: .NET 4.7.2

**Comment by n00mkrad** [comment]
Update:
It seems like it's not lossless, but uses a specific compression level, possibly 95. Either way, it ignores MagickImage.Quality.

**Comment by dlemstra** [comment]
The JXL encoder is super new and only has a minimal feature set. Will need to figure out how we can set the quality in the JPEG-XL library. This might not be possible yet in the current API.

**Comment by n00mkrad** [comment]
Oh, okay. I thought it would be pretty easy with the reference library.

Take your time then.

**Comment by n00mkrad** [comment]
I can confirm that the current implementation is NOT lossless:

10x Diff, PNG -> JXL:

![png2jxl](https://user-images.githubusercontent.com/61149547/103486436-420b4980-4dfe-11eb-9f37-a49c28302542.png)

10x Diff, JPEG -> JXL:

![jpeg2jxl](https://user-images.githubusercontent.com/61149547/103486446-4afc1b00-4dfe-11eb-8ffe-96ce1d4baf2f.png)

**Comment by dlemstra** [comment]
If you want lossless compression you will need to set the quality to `100`. That is the only encoder option that is currently implemented.

**Comment by dlemstra** [comment]
We added support for the quality setting and also setting the `effort`.
