### ISSUE TITLE
MagickImage.Draw(DrawableCircle) doesn't work in some cases

### ISSUE THREAD

**Issue by TheFizz** [dlemstra/Magick.NET#829]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
If the circle is too big, it will cause `MagickImage.Draw(DrawableCircle)` to throw  `'non-conforming drawing primitive definition 'circle'`

### Steps to Reproduce
The following code throws an exception on line `9` when `sideSize` is around `7000` or greater. There is no issue with lower values.

```C#
int sideSize = 7000;
int centerPoint = sideSize / 2;
int circleRadius = sideSize / 2;

DrawableCircle circle = new DrawableCircle(centerPoint, centerPoint, centerPoint + circleRadius, centerPoint);
DrawableFillColor fillColor = new DrawableFillColor(MagickColors.Black);
using (MagickImage mask = new MagickImage(MagickColors.Transparent, sideSize, sideSize))
{
    mask.Draw(circle, fillColor);
}
```

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU v7.22.3
- Environment (Operating system, version and so on): Win10, Target Framework - .NET Core 3.1 (For use in AWS Lambda)
- Additional information: Same issue in v7.22.2.2 as well

**Comment by dlemstra** [comment]
The problem here is that we have a limit for the number of points that can be drawn. This appears to be an old security check that has been replaced with a better method. In the next version of Magick.NET you should not run into this issue until you hit a memory limit.
