### ISSUE TITLE
.Extent doesn't set color

### ISSUE THREAD

**Issue by invertedburger** [dlemstra/Magick.NET#83]
Hi,
I'm trying to extent image with color, but color is always white no matter what I do.

 image.Extent(300, 200, Gravity.Northwest, new MagickColor(0, 255, 0));

**Comment by dlemstra** [comment]
I just tried the following code and it creates a correct image:

```C#
using (MagickImage image = new MagickImage("logo:"))
{
    image.Extent(800, 800, Gravity.Northwest, new MagickColor(0, 255, 0));
    image.Write(@"i:\test.jpg");
}
```

Is your image really smaller than 300x200?

**Comment by invertedburger** [comment]
It is working correctly, I had something stupid in my code. Sorry.
