### ISSUE TITLE
IMagickColor and other interface types are not included in the downloaded package. 

### ISSUE THREAD

**Issue by swuqi** [dlemstra/Magick.NET#831]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am using the latest version of Magick.NET
- [ ] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Steps to Reproduce

When I build the Magic.NET project from Visual Studio 2019, it shows a lot of errors not finding IMagickColor type like below.
error CS0246: The type or namespace name 'IMagickColor<>' could not be found
................

### System Configuration

- Magick.NET version: 7.22.3.0
- Environment (Operating system, version and so on):  Windows 2019
- Additional information:

**Comment by dlemstra** [comment]
Are you trying to build this project or are you trying to use this library in your own project?

**Comment by swuqi** [comment]
I'm trying to build the library from source code and then use it in our project.



Thanks,

Shangwu



-------- Original message --------

**Comment by dlemstra** [comment]
This looks like a problem in your project setup. Maybe you don't have the `.Core` library in your solution?

**Comment by swuqi** [comment]
Thank you for quick response. Let me build the .core project first. I found a file as imagickcolor{quatanm❵.cs. Is that the correct file name?



Thanks,

Shangwu



-------- Original message --------

**Comment by swuqi** [comment]
When you firstly build Magick.Core project, the error will be gone and the project will be built successfully.
