### ISSUE TITLE
Incorrect Orientation values reading .heic files

### ISSUE THREAD

**Issue by FloridaMatt** [dlemstra/Magick.NET#836]
Magick.Net-Q8-x64
MacOS Big Sur version 11.1
c# / Visual Studio for Mac 8.8.4 build 30

After reading a .heic image whose Exif indicates the orientation is other than topleft, image.Orientation erroneously returns TopLeft instead of the correct orientation.

workaround:  if img.Orientation = TopLeft, examine the Exif's orientation value.  if not 1 (TopLeft) either correct img.Orientation or rotate the img as applicable.
[02774B05-3B0F-4070-8B05-501A9249A4FE.heic.zip](https://github.com/dlemstra/Magick.NET/files/5791854/02774B05-3B0F-4070-8B05-501A9249A4FE.heic.zip)

**Comment by FloridaMatt** [comment]
Further detail:
    MagickImage img = new Magickimage(<some heic file>);

Results depend on whether or not the file's exif data contains values for TileLength and TileWidth.

If they are NOT present, the above statement:
    loads the image
    rotates it according to exif Orientation
    sets img.Orientation to TopLeft, but leaves exif orientation unchanged.

If they ARE present, it only
    loads the image
    sets img.Orientation to TopLeft, but leaves exif orientation unchanged.

**Comment by dlemstra** [comment]
Heic images are automatically changed to `TopLeft` when possible. You can prevent that from happening by setting the define `heic:preserve-orientation`. 

```C#
var settings = new MagickReadSettings();
settings.SetDefine(MagickFormat.Heic, "preserve-orientation", true);

using (var image = new MagickImage("fileName", settings))
{
}
```

**Comment by dlemstra** [comment]
And the next version of Magick.NET will include `HeicReadDefines` with a property to set this.
