### ISSUE TITLE
ARM Support

### ISSUE THREAD

**Issue by duckheadsoftware** [dlemstra/Magick.NET#839]

**Comment by dlemstra** [comment]
Not sure what you are asking or telling me?

**Comment by duckheadsoftware** [comment]
Thanks for the fast response, I was looking for clarification on what the libraries are, and for.

 

For example, the documentation doesn’t mention Magick.NET.Core or Magick.NET.SystemWindowsMedia – what scenarios are these for ?

**Comment by dlemstra** [comment]
Good question @raffaeler. I will update the documentation later today to make this more clear. The TLDR is that currently there is only ARM support for Windows.

**Comment by raffaeler** [comment]
@dlemstra  So, the AnyCPU does not work on linux-arm?
Thank you

**Comment by dlemstra** [comment]
That is correct. I will update the documentation to make it more clear what is supported on which platform.
