### ISSUE TITLE
Does not compress PNG file

### ISSUE THREAD

**Issue by Gormy** [dlemstra/Magick.NET#84]
![1a black with gold closet_e4cbd7d5](https://user-images.githubusercontent.com/6727243/28816868-0db85fa8-76af-11e7-9655-72acb3c0905c.png)
This file does not compress. Is it issue?

**Comment by dlemstra** [comment]
Your message needs a bit more details. What do you mean by:

> This file does not compress.

**Comment by Gormy** [comment]
I try compress this image by 
var imageOptimizer = new ImageOptimizer();
imageOptimizer.LosslessCompress(filePath);
use last version of library

**Comment by Gormy** [comment]
Magick.NET-Q16-AnyCPU 7.0.6.102

**Comment by Gormy** [comment]
Magick.NET-Q16-AnyCPU 7.0.6.102

**Comment by dlemstra** [comment]
It is possible that this file cannot be compressed further with the default options. You could set `OptimalCompression` to `true` to try more options. This will take a bit longer though.

**Comment by Gormy** [comment]
Does not help.

**Comment by meysamSamanpour** [comment]
What is your expectation? when you compress PNG with jpeg encoder it will compress to a amount you want. But first you have to indicate what do you expect from compression ?

**Comment by Gormy** [comment]
I compress this image use online compressor and the image compress to ~60%. I want to same effect.

**Comment by dlemstra** [comment]
I don't know what they do with the image but the `ImageOptimizer` could not make it smaller. Can you also share a compressed version of the image?

**Comment by iprida** [comment]
@Gormy try to save file without metatadata. The ImageMagick parameter for this is [`-strip`](https://www.imagemagick.org/script/command-line-options.php#strip)

**Comment by dlemstra** [comment]
The metadata is already stripped in the PNG optimizer.

**Comment by Gormy** [comment]
![1a black with gold closet_e4cbd7d5-min](https://user-images.githubusercontent.com/6727243/29305204-1438dd0c-81a0-11e7-91dd-197b7fb27481.png)

**Comment by andibadra** [comment]
in this case, you should used optipng (optimizer tool) separately. Since ImageMagick is an image library, not an optimizer.
Most online image converter is used optimizer tool to reduce png size, but that also make png file become lossy even is lossless format.

**Comment by dlemstra** [comment]
The optimizer in Magick.NET is a lossless optimizer which means that it will not modify the image. It appears that the software that you used slightly modified the image. But that slight change made a big difference in the file size. The PNG optimizer can only do lossless compression at the moment. I will have to investigate what has happened to the image to figure out what was done. I might be able to add this to Magick.NET but don't expect this anytime soon. Unless you can tell me what was done with the image exactly :)

**Comment by wintrue** [comment]
@Gormy The optimizer in Magick.NET is a lossless optimizer which means that it will not modify the image. It appears that the software that you used slightly modified the image. But that slight change made a big difference in the file size. The PNG optimizer can only do lossless compression at the moment. I will have to investigate what has happened to the image to figure out what was done. I might be able to add this to Magick.NET but don't expect this anytime soon. Unless you can tell me what was done with the image exactly :)

**Comment by IgorHoruzha** [comment]
> The optimizer in Magick.NET is a lossless optimizer which means that it will not modify the image. It appears that the software that you used slightly modified the image. But that slight change made a big difference in the file size. The PNG optimizer can only do lossless compression at the moment. I will have to investigate what has happened to the image to figure out what was done. I might be able to add this to Magick.NET but don't expect this anytime soon. Unless you can tell me what was done with the image exactly :)

![123compressed](https://user-images.githubusercontent.com/29505510/52844771-05e97580-310e-11e9-9190-45053650122b.png)
![123raw](https://user-images.githubusercontent.com/29505510/52844772-05e97580-310e-11e9-823a-1aa0ceb2c4f3.png)

<img width="926" alt="how_to_compress_png" src="https://user-images.githubusercontent.com/29505510/52844844-37624100-310e-11e9-8e6f-2763785e7ec6.PNG">


To compress png files you mast change color type to ColorType.PaletteAlpha;


```
           FileInfofile = new FileInfo(@"{file path}"); 
            using (MemoryStream memoryStream = new MemoryStream())
            {
                using (var magickImage = new MagickImage(file))
                {
                    magickImage.Strip();
                    magickImage.ColorType = ColorType.PaletteAlpha;              
                    magickImage.Write(memoryStream);
                    memoryStream.Position = 0;

                    ImageOptimizer optimizer = new ImageOptimizer();
                    optimizer.LosslessCompress(memoryStream);
                    optimizer.OptimalCompression = true;//More hard process.    
                    optimizer.Compress(memoryStream);
                 
                    File.WriteAllBytes($"Converted\\{file.Name}", memoryStream.ToArray());
                }
            }

```
