### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by duckheadsoftware** [dlemstra/Magick.NET#840]
I'm getting a little confused with all the different parts (Magick.NET.Core vs Magick.NET.SystemWindowsMedia vs everything else) and can't seem to find the documentation to help.

For example, what do I need to create a WPF app in .net 5 that compiles to x86, x64, and ARM ?

.Net 5 (net5.0-windows10.0.18362.0) - check
Magick.NET-Q8-AnyCPU ? - will this compile to ARM as well ?
Magick.NET.SystemWindowsMedia ?
Magick.NET.Core ?

thanks

**Comment by dlemstra** [comment]
There currently is no ARM support for this library.
