### ISSUE TITLE
Add password for PdfInfo.Create method to support protected PDF files

### ISSUE THREAD

**Issue by tomasr78** [dlemstra/Magick.NET#842]
Recently the PdfInfo class introduced to read various(currently only page count) PDF properties https://github.com/dlemstra/Magick.NET/issues/268

Unfortunately, it can't open protected PDF files. Please add a password option, the implementation could look like

`var pdfInfo = PdfInfo.Create(@"C:\YourFile.pdf", "password");`

**Comment by dlemstra** [comment]
Published the new release that includes this feature. Have fun!
