### ISSUE TITLE
PSB - Improper image header `TEST (2).psb' @ error/psd.c/ReadPSDImage/2429

### ISSUE THREAD

**Issue by MattiaCamponesco** [dlemstra/Magick.NET#845]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Hi everyone,
while using libraries specified in footer I encount an error in opening 2 specific psb extended images (link to download them below).
I tried by using older version of library but the error persists. I don't know if it is something wrong in the image, but opening them in PS it seems all ok (channels, bits, ...).

This is the StackTrace:
```
at ImageMagick.NativeInstance.CheckException(IntPtr exception, IntPtr result)
at ImageMagick.MagickImage.NativeMagickImage.ReadFile(IMagickSettings`1 settings)
at ImageMagick.MagickImage.Read(String fileName, IMagickReadSettings`1 readSettings, Boolean ping)
at ImageMagick.MagickImage.Read(FileInfo file, IMagickReadSettings`1 readSettings)
at TosiLabGraficheSync.Managers.ImageManager.GeneratePreview_ImageFile(PreviewDto preview)
```

### Steps to Reproduce

Images:
- [Example1](https://filesharing.systemceramics.com/AreaDiScambio/DownloadHandlerAreaDiScambio.aspx?Token=17076c2d-6f78-4dd6-a779-10e69e20fc16)
- [Example2](https://filesharing.systemceramics.com/AreaDiScambio/DownloadHandlerAreaDiScambio.aspx?Token=b7c7e9ea-8f3c-4103-8a48-467ff7cfd622)

### System Configuration

- Magick.NET version:  Magick.NET.Core 6.1.0 + Magick.NET-Q8-AnyCPU 7.23.1
- Environment (Operating system, version and so on): Windows 10 Enterprise - 10.0.17763
- Additional information:

**Comment by dlemstra** [comment]
It might be possible that this is something that we don't support. Will need to investigate this and I will get back to you when I know more.

**Comment by dlemstra** [comment]
It looks like we are unable to read the image because the mode is `Multichannel`. Can you share a screenshot of how these images look like in PS?

**Comment by MattiaCamponesco** [comment]
Here are the images data (sorry for italian labels) :

![Schermata 2021-02-10 alle 09 52 40](https://user-images.githubusercontent.com/74658001/107495211-14998480-6b90-11eb-8361-705ee7f8ce09.png)
![Schermata 2021-02-10 alle 09 52 20](https://user-images.githubusercontent.com/74658001/107495216-15cab180-6b90-11eb-8a15-f47a98b28f2f.png)
![Schermata 2021-02-10 alle 09 52 05](https://user-images.githubusercontent.com/74658001/107495214-15321b00-6b90-11eb-8eb9-0d1076db1654.png)


The image is multichannel as you said.

**Comment by dlemstra** [comment]
With some patches to @ImageMagick I was able to get the following output image:

![test](https://user-images.githubusercontent.com/10426229/107562486-2d318b00-6be0-11eb-820a-b33d835d3956.jpg)

You should be able to read these files in the next release.

**Comment by MattiaCamponesco** [comment]
Perfect, it's awesome. Thank you so much.
