### ISSUE TITLE
PdfInfo.Create signature taking a Stream parameter

### ISSUE THREAD

**Issue by mickaelleclerc** [dlemstra/Magick.NET#846]
PdfInfo class allows to read properties of a Pdf file. There is no signature of PdfInfo.Create taking a Stream parameter.

Is it possible to add this signature ?
`var pdfInfo = PdfInfo.Create(myStream);`

**Comment by dlemstra** [comment]
Ghostscript only supports reading from a file so your stream will need to be written to a file first. It is more efficient if you write it to a file yourself first and then first pass it to `PdfInfo.Create` and later to `MagickImage` to read the image.

**Comment by mickaelleclerc** [comment]
Thanks for your reply. No problem I will do that.
