### ISSUE TITLE
OpenCL_GetDevices

### ISSUE THREAD

**Issue by daxpandhi** [dlemstra/Magick.NET#85]
I found an error in an older version. 7.0.2.600 (Q16 x64) - I'm unable to change the version or test it on others at the moment, but wanted to report it. I'll investigate more when I get to my test machine and add notes.

More than 4 individuals on completely different hardware have reported the same issue - the common denominator was that they/we all upgraded to Windows 10 Creators update.

```C#
Exception: System.AccessViolationException
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Source: ImageMagick.OpenCL.NativeMethods.X64.OpenCL_GetDevices(UIntPtr& length)
```

The offending code - the error is thrown when the `Devices` object is queried in any form.
```C#
var cls = OpenCL.Devices.OrderBy(device => device.BenchmarkScore);

foreach (OpenCLDevice device in cls)
{
   sb.AppendLine($"[{device.DeviceType.ToString().ToUpper()}] {device.Name} ({device.Version})");
}
```

The error is fatal and the application crashes. No inner exception.

Additional crash info, if it helps:
```INI
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=Process512.exe
Sig[1].Name=Application Version
Sig[1].Value=2.1.140.319
Sig[2].Name=Application Timestamp
Sig[2].Value=597601d2
Sig[3].Name=Fault Module Name
Sig[3].Value=OclCpuBackEnd64.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=6.6.0.359
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=57dc2696
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0000000000141cdc
```

**Comment by daxpandhi** [comment]
Just confirmed - have the latest Intel OpenCL drivers (1.6.1.1).

**Comment by dlemstra** [comment]
That version is over a year old so it might be possible that this is fixed in the current release. Are you able to test it with the latest release?

**Comment by daxpandhi** [comment]
Writing that test right now. I mainly wanted to report it in case other people "stuck" on an older version like me run into it.

**Comment by daxpandhi** [comment]
OpenCL works - only accessing the OpenCL device list throws the error!

Tested on it on the latest version on NuGet (7.0.6.102) - and it works. :) Closing the issue.
