### ISSUE TITLE
Sample for combining images fails

### ISSUE THREAD

**Issue by mgalusha** [dlemstra/Magick.NET#86]
New to Magick.NET and most everything works as expected. I note that the sample in https://github.com/dlemstra/Magick.NET/blob/master/Documentation/CombiningImages.md throws an error in VS under framework 3.5 for the line   using(MagickImage result = images.Mosaic()). If I change it to  use the Interface the error disappears and it will compile and run. using(IMagickImage result = images.Mosaic())

Version 7.0.6.600 Q8-AnyCPU

**Comment by dlemstra** [comment]
Thanks for reporting this 👍. I just pushed a fix to update the documentation in two samples.
