### ISSUE TITLE
CR3 to JPG Produces Pink Shading

### ISSUE THREAD

**Issue by troyzirk2** [dlemstra/Magick.NET#866]
Hi,

- I have verified that I am using the latest version of Magick.NET.
- I have searched all issues to ensure it has not already been reported.

I am experiencing an issue in converting CR3 to JPG. All of the JPGs have a pink shading. Please see screenshot:

![CR3 to JPG Pink Screenshot](https://user-images.githubusercontent.com/22964152/108885312-845e3500-75bc-11eb-8717-30634074029e.png)

Here is the code that I am using to convert CR3 to JPG:

using (var img = new MagickImage([local file path]))
{
	// resize to 960 x 640 and save as jpg.

	img.Scale(0, 640);
	img.Density = new Density(96);
	img.Quality = 90;
	img.SetProfile(ColorProfile.SRGB);
	img.ColorSpace = ColorSpace.sRGB;
	img.Write([local file path]);
}

- Magick.NET version:  Magick.NET-Q16-AnyCPU v.7.23.2.
- Environment: Windows 10, Visual Studio 2019 Community Edition.

Best Regards,
Troy.

**Comment by dlemstra** [comment]
Can you share one of your input images so I can better test what is happening?

**Comment by troyzirk2** [comment]
Here you go.[https://vrxwestus.blob.core.windows.net/vrxstudios-downloads/9P4A2302.zip](url)

**Comment by dlemstra** [comment]
We are using the libraw library inside ImageMagick and it looks like the camera that took this picture (EOS R5) is not yet supported: https://www.libraw.org/supported-cameras. But it seems to be supported with the snapshot. I think we will need to wait for a new release or maybe try the snapshot or the latest commit instead.

**Comment by troyzirk2** [comment]
Thank you for your information, it is greatly appreciated. We have photographers who are now sending us more CR3 files, and this may be a showstopper. Approximately when do you expect the libraw library to be updated to support EOS R5? Is it possible for us to try the snapshot or latest commit to see if it resolves this specific issue? There could be an Amazon gift card in it for you, for your assistance... :)

**Comment by dlemstra** [comment]
Using master of the libraw library produces the following output image:
![test](https://user-images.githubusercontent.com/10426229/109031429-03d72b80-76c5-11eb-8d43-010095217f94.jpg)

**Comment by troyzirk2** [comment]
Terrif! I'm not the greatest at this, so how do I use the latest commit of the libraw library? I'll try to muddle my way through...

**Comment by dlemstra** [comment]
This will require rebuilding of the `Magick.Native` library. I don't mind using the latest master in ImageMagick also and publishing a new release in the next couple days.

**Comment by troyzirk2** [comment]
Thank you so much for that. I will keep my eyes peeled for your new release! :)

**Comment by dlemstra** [comment]
The new release has been published.

**Comment by troyzirk2** [comment]
Thank you so much Dirk! I will test it out. I’m sure it will work. 😊

Best Regards.

Troy Zirk
Marketing Technologist | VRX Studios

[http://www.vrxstudios.com/images/LogoEmail.png]

T: +1.604.605.0050<tel:+1.604.630.1172> | M: +1.778.319.9670<tel:+1.604.340.3364>
troy.zirk@vrxstudios.com<mailto:troy.zirk@vrxstudios.com>

Suite 415, The Landing, 375 Water Street,<x-apple-data-detectors://3/>
Vancouver, BC, Canada, V6B 5C6<x-apple-data-detectors://3/>
www.vrxstudios.com<http://www.vrxstudios.com/>

**Comment by troyzirk2** [comment]
Hi Dirk,

Long time no hear! I hope you are doing well, and that you had a great year to-date. 😊

We have some raw image files (NEF, CR2, CR3, etc.) that, when trying to open, trigger warning: "Data corrupted at `nnnnnnnnn' @ warning/dng.c/LibRawDataError/360". However, we can successfully open them in Photoshop and the Windows Photos app.

Is this something that I need to report to the LibRaw team, or is there something I can do in my app currently that I can ignore this specific issue/error message? The thing is, I don’t know if I can just ignore all messages of this type, because maybe the errors are valid on some other files.

[Ringer]      Please note our office is closed from December 24th noon PST  – January 3rd and will re-open on January 4th, 2022

Best Regards.

Troy Zirk
Marketing Technologist | VRX Studios

[http://www.vrxstudios.com/images/LogoEmail.png]

T: +1.604.605.0050 | M: +1.778.319.9670
***@***.******@***.***>

Suite 415, The Landing, 375 Water Street,
Vancouver, BC, Canada, V6B 5C6
www.vrxstudios.com<http://www.vrxstudios.com/>


Notice Regarding Confidentiality of Transmission: This message is intended only for the person to which it is addressed and contains information that is privileged and confidential. If you are not the intended recipient, you are hereby notified that any dissemination or copying of this communication is strictly prohibited. If you have received this email in error, please destroy all copies of this email immediately and notify us by telephone at 604.605.0050 or by e-mail at ***@***.******@***.***>).
