### ISSUE TITLE
Invalid date format specified for png

### ISSUE THREAD

**Issue by briankitt** [dlemstra/Magick.NET#88]
Received this today on a PNG file?  Not sure why I am getting this, but there is nothing I can do to correct this.
I opened it in fireworks, saved it, and now Magick.NET seems to be ok with it.

Perhaps this is just an error that you can ignore?

Invalid date format specified for png:tIME `f6030a5c-ae0d-401d-9b9f-110e3c4b9cc3.png' @ error/png.c/write_tIME_chunk/8178 at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) at ImageMagick.MagickImage.NativeMagickImage.WriteFile(MagickSettings settings)

**Comment by briankitt** [comment]
Here is a link to the image you can download.

http://www.kitt.us/data/f6030a5c-ae0d-401d-9b9f-110e3c4b9cc3.png

**Comment by dlemstra** [comment]
Is that the "unfixed" image? And what did you do with the image? The error message seems to be coming from the PNG encoder (writer).

**Comment by briankitt** [comment]
In this case, I was changing the density because it was not the density
that I wanted to work with.

**Comment by dlemstra** [comment]
Okay, I will give it a try myself when I get home.

**Comment by dlemstra** [comment]
I tried the following and I did not get an exception:
```C#
using (MagickImage image = new MagickImage(@"i:\png\f6030a5c-ae0d-401d-9b9f-110e3c4b9cc3.png"))
{
    image.Settings.Density = new Density(72);
    image.Write(@"i:\test.png");
}
```

Do you get the exception with this example? What do I need to change to get the exception?

**Comment by briankitt** [comment]
I can't believe it?  Today it works?  That's unreal.  That is definitely
the same image that was throwing an error yesterday.

I guess close it off unless you can see someplace in that code that the
error showed, where date format is checked?

**Comment by dlemstra** [comment]
It appears to be related to the moment when you execute your program: https://github.com/ImageMagick/ImageMagick/issues/685. Will publish a new release tomorrow to fix this.

**Comment by glennrp** [comment]
The problem was the use of unsigned int to contain the timezone offset hours.  The bug existed for users east of the GMT timezone, during the period that GMT was in the previous day to the user's day.
Fixed now.

**Comment by briankitt** [comment]
Aha.  My server is in a different timezone than I am

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dlemstra** [comment]
Going to take me a while longer. Need to update some of the ImageMagick dependencies and that takes a while.

**Comment by dlemstra** [comment]
One of the unit tests is failing and I cannot figure out why it fails. Will investigate that later this week.

**Comment by dlemstra** [comment]
The new release that includes a fix for this has been published.
