### ISSUE TITLE
Magick.NET-Q8-AnyCPU - Version 7.14.5 failed in Windows Store Certification

### ISSUE THREAD

**Issue by edsonmata** [dlemstra/Magick.NET#880]
Has any version of Magick solved this microsoft store certification problem ?

![image](https://user-images.githubusercontent.com/5148183/111355987-abad9c80-8666-11eb-8afd-391673bd7cab.png)

My Version:
![image](https://user-images.githubusercontent.com/5148183/111356352-0ba44300-8667-11eb-95cc-05b443bc5909.png)

**Comment by dlemstra** [comment]
Please don't create both an issue and a discussion with the same question.

**Comment by edsonmata** [comment]
@dlemstra Do you have solution to : https://github.com/dlemstra/Magick.NET/discussions/879
