### ISSUE TITLE
Providing your own mipmaps with DXT5 compression

### ISSUE THREAD

**Issue by Garanas** [dlemstra/Magick.NET#884]
### Is your feature request related to a problem? Please describe
I'm working on a tool to influence mipmap generation. As an example, to remove repeating elements depending on the mipmap level. Or to change the alpha channel depending on the mipmap level. The file format required is DDS. The goal is to make a small tool to automate this process from the command line.

The only approach to influencing the generated mipmaps is via `DdsWriteDefines` and then writing out a collection of images. Sadly, this only supports DXT1 or None as its compression and I'd like the library to support DXT5 too such that I can influence the alpha channel.

### Describe the solution you'd like
I'd like the library to support other DDS compression formats when providing your own mipmaps. As an example BC3 / DXT5 for alpha support.

### Describe alternatives you've considered
There does not appear to be alternative options. The only element I could find was the following forum topic:
 - https://legacy.imagemagick.org/discourse-server/viewtopic.php?f=2&t=30236&start=15

The current implementation is described in that topic and appreciated a lot already!

### Additional context
I use version 7.23.3 of Magick.Net-Q8-AnyCPU.

**Comment by dlemstra** [comment]
When you don't supply the compression it will use the default depending on the image format (`DXT1`, `DXT3`, `DXT5` or `DX10`). You are not the first one running into this misunderstanding though. What can I do to make it more clear that this only forces either DXT1 or no compression?

To write your own mipmaps you will need to read the image with a `MagickImageCollection` to read all the images. And when you set the boolean `MipmapsFromCollection` in the `DdsWriteDefines` the images in the collection (except for the first one) will be used as the mipmaps.

**Comment by Garanas** [comment]
Ah, that is good to know! I think the following suggestions may help:
 - Change the description of `DdsWriteDefines.Compression` from `Gets or sets the compression that will be used (dds:compression)`  to `Gets or sets whether the compression of the images should be overridden (dds:compression)`
 - Change the description of `DdsCompression.None` from `None.`  to `No compression is overridden: the compression of the images in the collection is used.`
 - Change the description of `DdsCompression.Dxt1` from `DXT1.` to `Overrides the compression of all the images in the collection to DXT1.`
 
The description at the moment doesn't describe the behavior, leaving it to my own interpretation and that was off. I think adding a clear description as to what behavior you can expect will solve this problem for future users too.

Personally I'd like to change the name of the member variables / enumerations too - but that is a breaking change. As an example, change `None` to `DoNotOverride`. 

In my application this doesn't happen - but what is the behavior if your collection uses different compressions? Does it use the top-level compression, of the texture itself?

**Comment by dlemstra** [comment]
`None` means `No` compression. It does not mean that the compression will not be overriden, it means all images will not be compressed.

**Comment by dlemstra** [comment]
I have updated the comments, thanks for your suggestions.
