### ISSUE TITLE
GIF shows artifacts where individual images don't

### ISSUE THREAD

**Issue by sthewissen** [dlemstra/Magick.NET#885]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of Magick.NET
- [X] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I combine a list of Bitmaps into a GIF using Magick.NET. I've verified that the individual PNGs coming in are correct by storing them individually. However, when I combine them into a GIF some of the frames have heavy artifacts.

### Steps to Reproduce

```
static void CreateGif(List<Bitmap> images, string path)
{
    using var collection = new MagickImageCollection();

    for (var i = 0; i < images.Count; i++)
    {
        var magick = new MagickImage();

        using (var memStream = new MemoryStream())
        {
            images[i].Save(memStream, images[i].RawFormat);
            memStream.Position = 0;
            magick.Read(memStream);
        }

        magick.AnimationDelay = 15;
        magick.GifDisposeMethod = GifDisposeMethod.Previous;
        magick.SetCompression(CompressionMethod.NoCompression);

        collection.Add(magick);
    }

    collection.Write(path);
}
```

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU 7.23.3
- Environment (Operating system, version and so on): macOS BigSur 11.0.1
- Additional information: Visual Studio for Mac 8.9.1

**Comment by dlemstra** [comment]
I would advise you to remove these statements:

```C#
magick.GifDisposeMethod = GifDisposeMethod.Previous;
magick.SetCompression(CompressionMethod.NoCompression);
```

And add this instead before you do the writing:

```C#
// Doing this will reduce the size of the image
collection.Optimize();
collection.OptimizeTransparency();

// This prevents dithering
collection.Quantize(new QuantizeSettings()
{
    DitherMethod = DitherMethod.No,
});
```

The noise is happing due to dithering, the commands above avoid that. For now you will also need to set the `Colors` of the `QuantizeSettings`, this will be resolved in the next release. The default will change from `1` to `256`.
