### ISSUE TITLE
CropToTiles not adhering to Rotate request

### ISSUE THREAD

**Issue by kirk-marple** [dlemstra/Magick.NET#887]
### Prerequisites

- [x] I have written a descriptive issue title
- [X] I have verified that I am using the latest version of Magick.NET
- [X] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
I'm loading an image from a stream, and auto-rotating it based on the orientation.

I've found that if I call CropToTiles on this image, those tiles are not getting rotated.

### Steps to Reproduce

                var image = new MagickImage(stream);
                image.Rotate(90);
                var tiles =.CropToTiles(tileWidth, tileHeight)
                (for each of the tiles...)
                tile.Write(stream, format);

If I simply write the original source, it's correctly rotated.  But if I write out a tile, it's not being rotated.

By design, bug, ...?  Thanks!

### System Configuration

- Magick.NET version: Magick.NET-Q16-AnyCPU, 7.23.3.0
- Environment (Operating system, version and so on): Win10 x64
- Additional information:

**Comment by dlemstra** [comment]
It does not look like you are auto-rotating based on the orientation. That would be done with the `AutoOrient` method. And I don't understand your problem is it possible to attach images to demonstrate this issue?

**Comment by kirk-marple** [comment]
Thanks for the quick response. I had written a simpler example than the code I'm using.

Here's my source; an iPhone image, which requires rotation for proper display.

![dog-portrait-2](https://user-images.githubusercontent.com/13594550/112525842-8bfd2f00-8d5e-11eb-89ae-98601eb03c7e.jpg)

And here's one of my tiles:
![default](https://user-images.githubusercontent.com/13594550/112526294-0463f000-8d5f-11eb-89b4-abbd8fce0bf0.jpg)

Here's the actual load and autorotate code.  I can use AutoOrient instead if that would change anything.  I hadn't noticed that method before.

```
        public static async Task<MagickImage> LoadImageAsync(ILogger logger, HttpClient client, Uri uri, bool autoRotate = false)
        {
            var sw = Stopwatch.StartNew();

            try
            {
                MagickImage image;

                if (uri.Scheme == Uri.UriSchemeFile)
                {
                    image = new MagickImage(uri.LocalPath);
                }
                else
                {
                    using var stream = new MemoryStream(await client.GetByteArrayAsync(uri));

                    image = new MagickImage(stream);
                }

                logger.LogDebug($"Successfully loaded image, took [{sw.Elapsed}].");

                return autoRotate ? AutoRotateImage(image, image.Orientation) : image;
            }
            catch (Exception e)
            {
                logger.LogException($"Failed to load image.", e);
                throw;
            }
        }
        private static MagickImage AutoRotateImage(MagickImage image, OrientationType orientation)
        {
            if (orientation == OrientationType.TopLeft)
                return image;

            double r = CalculateRotation(orientation);

            if (r != 0.0)
                image.Rotate(r);

            return image;
        }
```

**Comment by kirk-marple** [comment]
Additionally, here's my tiling/saving code.  I'm using this to create compatible IIIF tiles for OpenSeadragon viewing, which works great other than this rotation issue.

```
            var level = new IIIFLevel { Width = source.Width, Height = source.Height, Factor = 1, Tiles = source.CropToTiles(tileWidth, tileHeight.Value)?.ToList() };

            levels.Add(level);

            files.AddRange(await SaveLevelAsync(logger, folderPath, source, level, format, optimize));
```

```
        public static void SaveImage(ILogger logger, MagickImage source, MagickFormat format, ref string filePath, bool? optimize = null)
        {
            filePath = Path.ChangeExtension(filePath, InferExtension(format));

            var sw = Stopwatch.StartNew();

            try
            {
                using var stream = File.Create(filePath);

                source.Write(stream, format);

                logger.LogDebug($"Successfully saved image [{filePath}], took [{sw.Elapsed}].");
            }
            catch (Exception e)
            {
                logger.LogException($"Failed to save image [{filePath}].", e);
                throw;
            }

            if (optimize ?? true)
                OptimizeImage(logger, filePath);
        }
```

**Comment by kirk-marple** [comment]
Figured this out; AutoOrient worked perfectly.  Hadn't seen that method before, but I wasn't resetting Orientation manually after manually rotating.  Thanks for the help, closing!
