### ISSUE TITLE
JPG to PDF : Specify PDF version

### ISSUE THREAD

**Issue by M22an** [dlemstra/Magick.NET#89]
Currently all image files are being converted to PDF version 1.3 which is really outdated. 

Is there a way to convert the same to PDF version 1.6 or later ?

**Comment by dlemstra** [comment]
ImageMagick / Magick.NET will try to use the lowest version possible and with your image that appears to be 1.3. You can force 1.6 if you set the format to `MagickFormat.Pdfa`.

**Comment by M22an** [comment]
Thanks @dlemstra, that did the trick. Is there a way to explicitly specify the version to use ? We are looking for a way to make things consistent across all the PDF's we generate. So this would be really useful.

**Comment by dlemstra** [comment]
There is no explicit version option at this moment and I wonder if we should add that. We support 1.3 up to 1.7 and with `MagickFormat.Pdfa` you can force 1.6.

**Comment by M22an** [comment]
Ya, that would be a good option for us. Right now by setting to Pdfa, I think there is a possibility of files generating in 1.6 and 1.7 (correct me if I am wrong). 

For the moment this is not a big issue, but ideally we would like to stick to one version either 1.6 or 1.7.

**Comment by dlemstra** [comment]
I'll see if I can add an option that you could use to force a specific version. Maybe it should be a minimum version but that means you might have an issue if we ever start to support version 1.8.

**Comment by dlemstra** [comment]
It took two years but this feature has now been added. In the next version you can use `image.Settings.SetDefine(MagickFormat.Pdf, "version", "1.7")` to force version 1.7 when creating the PDF file.
