### ISSUE TITLE
Lossless JPEG XL compression ratio is much worse than in previous versions

### ISSUE THREAD

**Issue by n00mkrad** [dlemstra/Magick.NET#890]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Converting an 89 MB folder of PNGs to JXL results in too large files:
Core 6.1.0 / Magick 7.23.1: 61 MB
Core 6.1.3 / Magick 7.23.3: 97 MB (!)

### Steps to Reproduce
1) Download this archive: https://icedrive.net/0/98VFu8RrzS
2) Convert the images to JPEG XL. They will be larger than the original files, which was not the case with 6.1.0/7.23.1.

### System Configuration

- Magick.NET version: 7.23.3
- Environment (Operating system, version and so on): Windows 10 x64 v2004
- Additional information: .NET 4.7.2

**Comment by dlemstra** [comment]
We have updated the jpeg-xl library between those versions. It might be possible that something has changed in the library that causes you to get a larger file. Have you checked what happens when you use the default tooling of the jpeg-xl library?

**Comment by dlemstra** [comment]
Can you give it another try with the latest release @n00mkrad? We have recently updated jpeg-xl and I am getting pretty small images now.
