### ISSUE TITLE
Convert SVG to PNG

### ISSUE THREAD

**Issue by TonyLugg** [dlemstra/Magick.NET#90]
When I convert a simple SVG file to PNG it is not working.  With this SVG:

```xml
<svg width="23" height="23" xmlns="http://www.w3.org/2000/svg">
	<circle cx="11.5" cy="11.5" r="8.5" stroke="cyan" fill="transparent" stroke-width="3"/>
	<circle cx="11.5" cy="11.5" r="10.5" stroke="black" fill="transparent" stroke-width="1"/>
	<circle cx="11.5" cy="11.5" r="6.5" stroke="black" fill="transparent" stroke-width="1"/>
</svg>
```

The two black circles are there but they cyan circle is not.  It is also not transparent and it needs to be.  My code is below:

```vb.net
Dim lcSvgPath As String = IO.Path.Combine(TestFilesFolder, txtFileName.Text.Trim)
Using loImage As New MagickImage(lcSvgPath)
    loImage.Format = MagickFormat.Png
    Dim lcPngPath As String = IO.Path.ChangeExtension(lcSvgPath, "png")
    Using loPngStream As New IO.FileStream(lcPngPath, IO.FileMode.Create)
        loImage.Write(loPngStream)
    End Using
End Using
````

It is probably a configuration issue, but I don't know where to turn.

I tried with a stroke of ff0000 too, and that did not work either.

EDIT:  I got transparent background to work using:
            `loImage.Transparent(MagickColors.White)`

EDIT2:  I changed the individual stroke and fill attributes to style:
`<circle cx="11.5" cy="11.5" r="8.5" style="fill:none;stroke:cyan;stroke-width:1"/>`
and this seemed to fix the issue with the colored circle not showing.  I still can't get a transparent background without converting white to transparent, which may not always be desirable.  The SVG displays transparent, but the PNG does not without the transparent conversion of white.

`Thanks.

**Comment by dlemstra** [comment]
Sorry for the late reply but I forgot to investigate this. A proper fix will be doing the following before you load the image:
```VB.NET
image.BackgroundColor = MagickColors.Transparent
```

And changing `fill="transparent"` to `fill="none"` seems to resolve the transparent fill issue.

**Comment by TonyLugg** [comment]
Thank you Dirk.  You have an awesome library!
