### ISSUE TITLE
ImageMagick.MagickCorruptImageErrorException:“improper image header `' @ error/rle.c/ReadRLEImage/221”

### ISSUE THREAD

**Issue by hunter20212021** [dlemstra/Magick.NET#901]
var settings = new MagickReadSettings { Format = MagickFormat.Rle };
         
            using (var image = new MagickImage(d1, settings))
            {
              

            }

![image](https://user-images.githubusercontent.com/82394045/114414249-39869400-9be1-11eb-92ce-84102e00b0b1.png)

**Comment by hunter20212021** [comment]
[Uploading Item.7z…]()
this is file 
 var d1 = System.IO.File.ReadAllBytes("d:\\item.dat");

**Comment by hunter20212021** [comment]
[Uploading Item.zip…]()

**Comment by hunter20212021** [comment]
[Uploading Item.zip…]()

**Comment by dlemstra** [comment]
That error message means that the file that you are providing to the ImageMagick library is corrupt. Did you check if the file is valid?
