### ISSUE TITLE
Setting LZW compression has no effect

### ISSUE THREAD

**Issue by VTol-zz** [dlemstra/Magick.NET#902]
[sample.zip](https://github.com/dlemstra/Magick.NET/files/6297892/sample.zip)

### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
TIF image is written with no compression, although LZW has been set.

### Steps to Reproduce
```
using (var img = new MagickImage(@"C:\Temp\sample_LZW.tif"))
{ 
	img.SetCompression(CompressionMethod.LZW);
	img.Write(@"C:\Temp\sample_NoCompression.tif");
}
```
Source and resulting images attached.

### System Configuration

- Magick.NET version: 7.23.3
- Environment (Operating system, version and so on): Windows 10 x64
- Additional information:

**Comment by VTol-zz** [comment]
Now I see it. The name of the method seems to me a bit confusing for getting the value...

Nevertheless, why the following code does not write to LZW, when original image is LZW compressed? 
```
using (var img = new MagickImage(@"C:\Temp\sample_LZW.tif"))
{
	img.Write(@"C:\Temp\sample_NoCompression.tif");
}
```

And why the next one writes to 8bit grayscale LZW tif, despite of 24bit color LZW tif on input?
```
using (var img = new MagickImage(@"C:\Temp\sample_LZW.tif"))
{
	img.Settings.Compression = CompressionMethod.LZW;
	img.Write(@"C:\Temp\sample_NoCompression.tif");
}
```

Or should I explicitly set all the settings I rely on?

**Comment by dlemstra** [comment]
The description is incorrect. It should be `Sets the compression` instead of `Gets the compression`. Thanks for your remark about this, did not even notice it when I posted it here.

ImageMagick will let the user decided which compression/settings to use. Some are inherited but most settings rely on the user settings this.

And the tiff coder will try to change the image to grayscale when it can. You can prevent this from happening by doing this:

```C#
img.PreserveColorType()
```

**Comment by VTol-zz** [comment]
Now it is clear! Thank you for help!
