### ISSUE TITLE
Value should be greater than zero. Parameter name: width

### ISSUE THREAD

**Issue by pc8181** [dlemstra/Magick.NET#908]
Hi Sir, 
      
              Using image As New MagickImage(_srcPsdImagePath$)
                                              Using newImage = image.Clone()
                                                  Dim _geo As New MagickGeometry(-2, 750)  'ERROR LINE
                                                  _geo.IgnoreAspectRatio = False
                                                  newImage.Resize(_geo)
                                                  newImage.Density = New Density(100) 'resolution
                                                  newImage.Strip()
                                                  newImage.Format = MagickFormat.Jpg
                                                  newImage.Quality = 100
                                                  newImage.Settings.SetDefine(MagickFormat.Jpg, "lossless", "false")
                                                  Dim _savePath$ = IO.Path.ChangeExtension(_srcPsdImagePath, ".jpg")
                                                  newImage.Write(_savePath$)
                                                  _geo = Nothing
                                              End Using
                     End Using
     
This code is working fine in Magick.NET-Q8-AnyCPU.dll **Version: 7.21.1.0** 
but the same code is not working a new project with version **7.23.3.0**

Error Line is : 
                     `     Dim _geo As New MagickGeometry(-2, 750)`

Error:
    `Value should be greater than zero. Parameter name: width`

please help how to resolve

Thanks

**Comment by dlemstra** [comment]
A negative value for the Width is no longer allowed. Why were you doing this?

**Comment by pc8181** [comment]
m used this codes for generate PSD (to jpg) thumbnails for my control which show thumbnails only jpg images

**Comment by dlemstra** [comment]
I think you will get the same result when you use `0` instead of `-2`. And if you want to use a percentage you can do this: `new MagickGeometry("50%")`.

**Comment by pc8181** [comment]
ThanQ So Much, It's Working Fine
