### ISSUE TITLE
Reading Pdf from byte array results in empty MagickImageCollection on Alpine Linux in Docker

### ISSUE THREAD

**Issue by Atrejoe** [dlemstra/Magick.NET#909]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Reading a Pdf from a byte array on Alpine Linux in Docker results in an empty MagickImageCollection.
Transforming the MagickImageCollection to PNG then fails, error message:
> Operation requires at least one image

This *does* work when running on Windows.

Note that I ensure the relevant ImageMagick binaries are copied into the Docker Image by specifying the runtime suitable for Alpine Linux:
> `--runtime linux-musl-x64`

(*Inspired by: #561*)

### Steps to Reproduce

Create docker image (and start it)

```dockerfile
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build
WORKDIR /src
# copy project files
COPY ["*.sln", "."]
RUN dotnet restore "myproject.csproj"
COPY . .
WORKDIR "/src/myproject"
RUN dotnet build "myproject.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "myproject.csproj" -c Release -o /app/publish --runtime linux-musl-x64 #using linux-musl-x64 addresses #561

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

ENTRYPOINT ["dotnet", "myproject.dll"]
```

Offending code:
``` csharp
//Get pdf as byte array
var pdf = await GetPdf();

var settings = new MagickReadSettings
{
// Settings the density to 300 dpi will create an image with a better quality
Density = new Density(300),
Format = MagickFormat.Pdf,
Verbose = true
};

using (var images = new MagickImageCollection())
{
// Add all the pages of the pdf file to the collection
images.Read(pdf, settings); //<- given the error below, I would have expected and exception or warning here

//Skipping check, in order to demonstrate problem
//if (images.Count == 0)
//	throw new System.Exception($"{pdf.Length:n0} byte pdf file resulted in 0 images");

using var ms = new MemoryStream();
// Create new image that appends all the pages horizontally
using (var horizontal = images.AppendHorizontally()) //<-- this would throw exception : "Operation requires at least one image"
{
	// Save result as a png
	horizontal.Write(ms, MagickFormat.Png);
}
```

Using sample file:
https://static01.nyt.com/images/2021/04/21/nytfrontpage/scan.pdf

output:
```bash
'gs' -sstdout=%stderr -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 '-sDEVICE=pamcmyk32' -dTextAlphaBits=4 -dGraphicsAlphaBits=4 '-r300x300'  '-sOutputFile=/tmp/magick-kutweUb35-T21E2DGziN90Bx1niEoAJH%d' '-f/tmp/magick-o2hB41ha5L1UW8p2VeF5H87-BbNeiLJc' '-f/tmp/magick-v643DQgl4zSyAagmYUPZsl2FwYKOBkKc'
```

Any hints on what I can further do to pinpoint the issue? Am I using the correct libraries, can I make the process more verbose?

### System Configuration

- Magick.NET version:  Magick.NET.Core 6.2.0 (and 5.2.2), Magick.NET-Q16-AnyCPU 7.23.4 (and 7.22.2.2)
- Environment (Operating system, version and so on): Alpine Linux on Docker (both WSL and on dedicated Linux machine (QNAP))
- Additional information: none

**Comment by dlemstra** [comment]
You are reading PDF files. This will require you to install Ghostscript inside your container.

**Comment by Atrejoe** [comment]
Sounds like a plan, I will report back when I have results.

**Comment by Atrejoe** [comment]
Great this works: I installed ghostscript on the Docker instance by adding:

```dockerfile
...
RUN apk add ghostscript
...
ENTRYPOINT ["dotnet", "myproject.dll"]
```
