### ISSUE TITLE
SVG to PNG Text Intermittently Boxes

### ISSUE THREAD

**Issue by TonyLugg** [dlemstra/Magick.NET#91]
Some of my SVG icons have text in them.  Sometimes the text shows fine, and another time it will display as boxes (one box where each character would go).  Is there a way to ensure the text will always work?

The link below demonstrates two icons, the left with a single character and the right with 5 digits (intended).
[Bad Conversion](http://www.vdis.com/download/files/svgtextissue.png)
 
I run the same code again and get this:

[Good Conversion](http://www.vdis.com/download/files/svgtextok.png)

**Comment by TonyLugg** [comment]
I know this is a strange one, but any thoughts?

**Comment by dlemstra** [comment]
It might be a bug in librsvg. I updated the library to a new version and I will publish a new release soon that includes the version. Probably needs some more testing. Are you running in parallel?

**Comment by TonyLugg** [comment]
Sorry, what do you mean by parallel?  I just have an ASPX page that takes some parameters, pulls in the SVG text, uses Magick.NET to convert it to png, then pushes it onto the response output stream.

**Comment by dlemstra** [comment]
I was wondering if you were running into multi threading issues. I don't know what fixes have been made in the new release of librsvg but that might fix your issue.

**Comment by TonyLugg** [comment]
Hope so.  Will you release the update through NuGet?

**Comment by dlemstra** [comment]
The new release will be published on NuGet. One of my unit tests is now failing with the latest ImageMagick code so I first need to figure out why that fails. Hope I can publish a new release soon.

**Comment by dlemstra** [comment]
The new release has been published, can you give it another try?

**Comment by TonyLugg** [comment]
Same issue I'm afraid.  When calling multiple times to convert a batch of SVGs, some work and some don't.  I suppose it could be a threading issue as the calls are made asynchronously to the server.  However, it is only text that is messed up, everything else renders/converts properly.  

Do you think setting the textlength in svg code would help?

**Comment by dlemstra** [comment]
Can you create a small sample that I could use to reproduce the issue? Maybe with a parallel loop?

**Comment by TonyLugg** [comment]
I just created a test WPF app and looped through 30 conversions and it worked perfectly.  There must be something in the ASP.NET that messes things up.  I'll try the same thing with a small web app and see what happens.  I did put a 5 second delay between calling my conversion page in my web app to ensure there was only one conversion happening at a time, but it did not help.

**Comment by TonyLugg** [comment]
Here is the WPF program: [WPF Program](http://www.vdis.com/download/files/magick/MagickNetTestWpf.zip)

The result of the WPF loop of 30 conversions: [WPF Result](http://www.vdis.com/download/files/magick/MagickImages-WPF.png)

Here is the ASP.NET program: [ASP.NET Program](http://www.vdis.com/download/files/magick/MagickNetTestWeb.zip)

The result of the ASP.NET loop of 30 conversions: [ASP.NET Result](http://www.vdis.com/download/files/magick/MagickImages-ASP.NET.png)

**Comment by dlemstra** [comment]
I had to change some of your code in the WPF program to this:

```vb.net
Parallel.ForEach(mcolDataItems, Sub(loDataItem)
                                    CreatePng(loDataItem)
                                End Sub)
```

And now I can reproduce your issue.

**Comment by TonyLugg** [comment]
OK, so why is the issue happening?  More importantly, can you come up with a fix, especially for the web version?  Thanks for working on this!

**Comment by dlemstra** [comment]
It turned out there is some kind of multithreading issue inside the pango library that is being used by librsvg. I could not find the exact cause but we decided to disable multi threading for the svg and pango decoder. The new release that I just published includes this fix.

**Comment by TonyLugg** [comment]
Issue resolved!  Thank you so much.
