### ISSUE TITLE
Can't read image with CPU i7 7700

### ISSUE THREAD

**Issue by Augus** [dlemstra/Magick.NET#92]
Can't read image with CPU i7 7700, it's very strange.

**Comment by dlemstra** [comment]
Your description does not contain enough information to reproduce the issue. Why are you blaming the CPU?

**Comment by dlemstra** [comment]
@Augus Can you provide me with more information?

**Comment by Augus** [comment]
Hello @dlemstra , this issue is feedback from our customer, not only appear one time, as long as it's i7 7770 or i5 3470, and this crash when program call this function
`using (MagickImage image = new MagickImage((string)list[0]))`

This problem only occurs when the image is in the `JPEG` format.

**Comment by Augus** [comment]
@dlemstra Any idea about this problem?

**Comment by dlemstra** [comment]
What kind of exception are you receiving?
