### ISSUE TITLE
Strong pink tint when copying from grayscale to sRGB image

### ISSUE THREAD

**Issue by jyrkive** [dlemstra/Magick.NET#921]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Grayscale images copied to sRBG images have a strong pink tint. Observed result with the test program below: ![result](https://user-images.githubusercontent.com/1665617/117452036-f7384480-af4b-11eb-8a8c-c75466fcf631.png)

The source image is pure white: ![grayscale](https://user-images.githubusercontent.com/1665617/117451950-db34a300-af4b-11eb-90a2-181753a17788.png)

### Steps to Reproduce

```cs
using System;
using ImageMagick;

namespace MagickNetTest
{
    class Program
    {
        static void Main(string[] args)
        {
            // Load some grayscale text from disk. (This is the attached "source image" above.)
            var text = new MagickImage("grayscale.png");
            // text.ColorSpace = ColorSpace.sRGB;

            // Create the target image.
            var transparent = new MagickColor(0, 0, 0, 0);
            var target = new MagickImage(transparent, 45 + text.Width, 32);

            // Copy source image to target.
            double x = 45;
            double y = Math.Truncate((32 - text.Height) / 2.0);
            target.CopyPixels(text, text.BoundingBox, new PointD(x, y));

            // Save the target image to disk.
            target.Write("result.png");
        }
    }
}
```

Workaround: the issue disappears if I convert the grayscale image to sRGB first by uncommenting the line `text.ColorSpace = ColorSpace.sRGB;`

### System Configuration

- Magick.NET version: Q8-AnyCPU, v7.23.4
- Environment (Operating system, version and so on): Windows 10 20H2
- Additional information:

**Comment by dlemstra** [comment]
Your workaround is the actual fix for this issue. The `CopyPixels` method of `MagickImage` will "just" copy the pixels from one image to another. And if you copy a grayscale image (1 channel) to a transparent image (4 channels) it will copy that one channel to the red channel of the transparent image. If you don't want that to happen you will need to change the number of channels in your source image and as you figured out you can use `text.ColorSpace = ColorSpace.sRGB` for that.

**Comment by jyrkive** [comment]
I see. Thanks for the advice. 👍🏻
