### ISSUE TITLE
Remove lines from bi-tonal images.

### ISSUE THREAD

**Issue by tdhintz** [dlemstra/Magick.NET#93]
I'm trying to replicate something like the following windows BAT command using C#.  [Source](http://www.imagemagick.org/discourse-server/viewtopic.php?t=22338)

```
convert Test2image.png -strip -write mpr:ORG ^
  ( +clone ^
    -negate ^
    -morphology Erode rectangle:50x1 ^
    -mask mpr:ORG -morphology Dilate rectangle:50x1 ^
    +mask ^
  ) ^
  -compose Lighten -composite ^
  ( +clone ^
    -morphology HMT "1x4:1,0,0,1" ^
  ) ^
  -compose Lighten -composite ^
  ( +clone ^
    -morphology HMT "1x3:1,0,1" ^
  ) ^
  -compose Lighten -composite ^
  ( +clone ^
    -morphology HMT "3x1:1,0,1" ^
  ) ^
  -compose Lighten -composite ^
  out.png
```

The first part seems easy but the rest is lost in translation.  What is the C# equiv to this command?

```
myimage.Strip();
using (var mask = myimage.Clone())
{
    mask.Negate();
    mask.Morphology(MorphologyMethod.Erode, "rectangle:50x1");
    // now what?
}
```

**Comment by tdhintz** [comment]
On-line documentation for -/+mask has problems.

**Comment by dlemstra** [comment]
Why did you close this issue?

**Comment by tdhintz** [comment]
I found the Community forum for ImageMagick .Net and asked the question there.  I seemed to be successful answering my own question and the result is posted there.

**Comment by dlemstra** [comment]
Link to the forum: https://www.imagemagick.org/discourse-server/viewtopic.php?f=27&t=32573. And your result looks correct.
