### ISSUE TITLE
The type initializer for NativeMagickSettings threw an exception

### ISSUE THREAD

**Issue by Keither** [dlemstra/Magick.NET#930]
Hi, i use Install-Package Magick.NET-Q16-AnyCPU for my website asp.net mvc in window server 2019

this code throw error
using (var image = new MagickImage(fileName))
"The type initializer for NativeMagickSettings threw an exception"

i debug in local (window 10), it is OK, not error

Sorry my Englisht not good!
Thanks!

**Comment by Keither** [comment]
i have multi site, one site working and other site error

**Comment by tonylu1105** [comment]
How did you fix the problem?

**Comment by Keither** [comment]
before use using (var image = new MagickImage(fullPath))
i use this
`var appPath = HttpContext.Current.Server.MapPath("~/upload");
MagickAnyCPU.CacheDirectory = appPath;
MagickAnyCPU.HasSharedCacheDirectory = true;
MagickNET.SetTempDirectory(appPath);
OpenCL.IsEnabled = false;
using (var image = new MagickImage(fullPath))
{
}`
