### ISSUE TITLE
A ConvertPDFToImage console demo, add to systemctl ,it do not work

### ISSUE THREAD

**Issue by willingtolove** [dlemstra/Magick.NET#932]
## HELP ME! HELP ME!

A ConvertPDFToImage console demo, add to systemctl ,it do not work!

I run the demo ,like  ` ./MagickTest`  ,it work well;
but, when i add it to systemctl ,it do not work; like "`systemctl start pdftoimage`";

### the code:

```c#
        private static void pdftoimage()
        {
            //MagickNET.SetGhostscriptDirectory("/usr/bin");
            
            string path = @"TestDoc.pdf";
            MagickReadSettings settings = new MagickReadSettings();
            settings.Density = new Density(300, 300); //设置质量
            using (MagickImageCollection images = new MagickImageCollection())
            {
                try
                {
                    images.Read(path, settings);
                    Console.WriteLine("count:"+images.Count);
                    for (int i = 0; i < images.Count; i++)
                    {
                        MagickImage image = (MagickImage)images[i];
                        image.Format = MagickFormat.Jpg;
                        image.Write("image/"+ (i + 1) + ".jpg");
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
                }
            }
        }
```
- no exception;
- mages.Count is 0;

### the systemctl service

```xml
[Unit]
 Description=magicktest server
 After=sshd.service
 [Service]
 EnvironmentFile=/etc/default/magicktest
 WorkingDirectory=/home/parasaga/codetest/pdftoimage
 ExecStart=/home/parasaga/codetest/pdftoimage/MagickTest
 ExecReload=/bin/kill -HUP $MAINPID
 StandardOutput=/home/parasaga/codetest/pdftoimage/stdout.log
 StandardError=/home/parasaga/codetest/pdftoimage/stderr.log
 KillMode=process
 Restart=on-failure
 RestartPreventExitStatus=255
 Type=simple
 [Install]
 WantedBy=multi-user.target
 Alias=magicktest.service
```

**Comment by dlemstra** [comment]
I don't think I can help you with this. If it works when running outside of `systemctl` but doesn't when you use `systemctl` it must be something in your setup. Maybe ImageMagick is unable to find Ghostscript?

**Comment by willingtolove** [comment]
> I don't think I can help you with this. If it works when running outside of `systemctl` but doesn't when you use `systemctl` it must be something in your setup. Maybe ImageMagick is unable to find Ghostscript?

i install ghostscript :  `apt install ghostscript`

**Comment by willingtolove** [comment]
> > I don't think I can help you with this. If it works when running outside of `systemctl` but doesn't when you use `systemctl` it must be something in your setup. Maybe ImageMagick is unable to find Ghostscript?
> 
> i install ghostscript : `apt install ghostscript`
> 
> if ImageMagick is unable to find Ghostscript, why no exception?

I solved the problem：i copy the `gs` to path of my app, it work well; but i do not know why !

**Comment by dlemstra** [comment]
The `gs` executable needs to be in the path of your app. But if that happens an exception should be raised instead. I just pushed a fix to the ImageMagick repository to fix this.
