### ISSUE TITLE
ImageMagick.MagickImageErrorException: width or height exceeds limit

### ISSUE THREAD

**Issue by redonisc** [dlemstra/Magick.NET#933]
Hello,

I got this issue with a panoramic photo with the following pixel dimensions 18992x1504, 96dpi, size 4.48mb.

ImageMagick.MagickImageErrorException: width or height exceeds limit `L:\124\164822-202105121120371.webp' @ error/webp.c/WriteWEBPImage/1119
   at ImageMagick.MagickExceptionHelper.Check(IntPtr exception) in /_/src/Magick.NET/Exceptions/MagickExceptionHelper.cs:line 18
   at ImageMagick.MagickImage.NativeMagickImage.WriteFile(IMagickSettings`1 settings) in /_/src/Magick.NET/Native/MagickImage.cs:line 6548

### Description
While trying to convert a jpg to webp format, using the following code:

```
            using (var img = new MagickImage(OriginalPath))
            {
                using (var newImage = img.Clone())
                {
                    newImage.Format = MagickFormat.WebP;
                    newImage.Quality = 95;
                    newImage.Settings.SetDefine(MagickFormat.WebP, "lossless", "false");
                    newImage.Write(outputFile);
                }
            }
```

### System Configuration
Windows Server 2016
Magick.NET version:Q8x64 (7.24.0)

**Comment by dlemstra** [comment]
The maximum width or height of a `webp` image is `16383`. To save that file as a webp image you will need to reduce the width of the image.
