### ISSUE TITLE
Setting color primaries has no effect on the image

### ISSUE THREAD

**Issue by mr-zorg** [dlemstra/Magick.NET#942]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

I have sets of raw Red, Green, and Blue 16bit color channels which I combine into a color bitmap, and then save as EXR file using Magick.NET.

I would like to define the primaries and whitePoint for a colorspace using the xy chromaticity in Yxy. I might be able to settle for defining the primaries in XYZ, Yuv, or LAB.

I am using the below snippet to save my image to EXR:

```

var pixelReadSettings = new PixelReadSettings(4096, 3000, StorageType.Float, PixelMapping.RGB);
using (var image = new MagickImage(floatRawBitmapBuffer, pixelReadSettings))
{
	//image.Settings.ColorSpace = ColorSpace.XyY; //this line doesn't do anything
	image.ColorSpace = ColorSpace.XyY; //By setting that. I'm just getting a very yellow image
	//Any values supplied to the following 4 properties have no effect on output
	image.ChromaWhitePoint = new PrimaryInfo(0.5d, 0.5d, 0.5d); 
	image.ChromaRedPrimary = new PrimaryInfo(0.5d, 0.5d, 0.5d);
	image.ChromaGreenPrimary = new PrimaryInfo(0.5d, 0.5d, 0.5d);
	image.ChromaBluePrimary = new PrimaryInfo(0.5d, 0.5d, 0.5d);
	image.SetProfile(ColorProfile.SRGB, ColorTransformMode.Quantum);
	image.Format = MagickFormat.Exr;
	image.Settings.Compression = CompressionMethod.Piz;
	image.Write(outputPath);
}

```

Please let me know if this is a bug and if not, how to correctly use the library to achieve my goal.

### Steps to Reproduce
In the following file I included the input (a color test chart bitmap to be supplied as floatRawBitmapBuffer) and output of the above code snippet.

https://www.dropbox.com/sh/pmcf0s69jx07ihw/AAAXUEaw06amZaG5Xe7zBXXWa?dl=0

### System Configuration

- Magick.NET version: Magick.NET-Q16-HDRI-OpenMP-x64 7.24.0
- Environment (Operating system, version and so on): Windows 10

**Comment by dlemstra** [comment]
Those settings are not use by the `exr` coder and it looks like that coder only supports writing the image in the RGB colorspace. I don't really understand what you are trying to accomplish. You should probably ask your question in the ImageMagick discussions: https://github.com/ImageMagick/ImageMagick/discussions. And if we have an answer there I can help you translate it to C#.

**Comment by mr-zorg** [comment]
Thank you for the reply. I am currently experimenting with ICC profiles, if I have any questions related to that I will ask in ImageMagick discussions.
