### ISSUE TITLE
NoTagFound `https:decode' @ error/delegate.c/InvokeDelegate/1736,StackTrace:   at ImageMagick.MagickImageCollection.NativeMagickImageCollection.ReadFile(IMagickSettings`1 settings)

### ISSUE THREAD

**Issue by shixb** [dlemstra/Magick.NET#944]
.net core 2.1.1应用程序，引用 Magick.NET-Q16-AnyCPU 7.22.1版本
程序部署在Linux系统报错了。
var settings = new MagickReadSettings();
// Settings the density to 300 dpi will create an image with a better quality
settings.Density = new Density(300);

using (var images = new MagickImageCollection())
{
    // Add all the pages of the pdf file to the collection
    images.Read("Snakeware.pdf", settings);
｝

**Comment by dlemstra** [comment]
I dont understand what you are trying to tell/ask me. Your error message seems to be from something else? It looks like you are trying to read an image directly from an url? You probably need curl or wget for that, not sure which one ImageMagick uses though.

**Comment by TomMorant** [comment]
> I dont understand what you are trying to tell/ask me. Your error message seems to be from something else? It looks like you are trying to read an image directly from an url? You probably need curl or wget for that, not sure which one ImageMagick uses though.

Well, in. Net core 2.1.1, I refer to magic.net-q16-anycpu 7.22.1. My service is deployed in the way of docker in the Ubuntu server. I want to use the program to convert PDF format to JPG format. Now the program can't be called. What should we do??? Program error as the title

**Comment by dlemstra** [comment]
How are you reading the PDF file and did you install `ghostscript` in the container?
