### ISSUE TITLE
BrightnessContrast method freezes

### ISSUE THREAD

**Issue by Tortila90** [dlemstra/Magick.NET#95]
For unknown reason this simple code freezes (hangs) while calling BrightnessContrast method.
```csharp
using (MagickImage magickImage = new MagickImage(@"E:/input.jpg"))
{
	magickImage.BrightnessContrast(new Percentage(50), new Percentage(50));
	magickImage.Write(@"E:/output.jpg");
}
```

I tried both Q8.AnyCPU and Q16.AnyCPU versions. It worked fine only once, just when I installed Q16 and removed Q8 from references. The next run failed again though.
I also tried SepiaTone and Blur functions. Same result. Rotate, however, works fine.
I tried to play with CacheDirectory. No success.

According to logs it freezes somewhere between image.c/GetImageVirtualPixelMethod and image.c/SetImageStorageClass, but I'm not sure.

Could you please help me?

**Comment by Tortila90** [comment]
For x64 it throws the following error:
```
Could not load file or assembly 'Magick.NET-x64' or one of its dependencies.
An attempt was made to load a program with an incorrect format.
```

For x86 it works. I'll keep searching how to fix it for x64.
What will the status of this issue be then? Do you need my help to solve it?

**Comment by dlemstra** [comment]
All the methods that you mention have OpenCL acceleration. The first time an OpenCL function is called a benchmark will run to determine if the GPU or if the CPU is faster. For you that might feel like it is hanging. You could decide to wait until the benchmark finishes (You can find the results in `%LOCALAPPDATA%\ImageMagick`). Or you can decide to disable OpenCL with `OpenCL.IsEnabled = false`.

**Comment by dlemstra** [comment]
And your `x64` error looks like you are trying to use a `x64` library inside a `x32` application pool.

**Comment by Tortila90** [comment]
Sorry, I was uncertain. "Freezes" actually means "stops". I was waiting for 5+ minutes and nothing happened.

I was using x32 application pool, so I switched the application pool to x64. And with x64 library I experienced the same problem as with AnyCPU. It just stops.

`OpenCL.IsEnabled = false` did the trick, and it works for x64 and AnyCPU.

**Comment by mvaccarouy** [comment]
where do you put the "OpenCL.IsEnabled = false"
