### ISSUE TITLE
Cool Library - More examples would be great

### ISSUE THREAD

**Issue by jackbond** [dlemstra/Magick.NET#97]
I've found a few examples of how to use this library, but some more examples on how to do animated gifs would be awesome. In my case, I'm trying to display some winning numbers in a sequence. Basically I've got an image(40px wide) for each number and I'd like to have an animated gif where each number appears after a short delay. There are five winning numbers so the total image width would be 200px.  I tried adding the images to a MagickImageCollection, each with a different AnimationDelay, and then calling AppendHorizontally, but the resulting image wasn't animated. Any help would be appreciated. Thanks.

**Comment by dlemstra** [comment]
I would also love to see more examples but I have a limited amount of time that I can spend on this project. But I can create an example for you. The primary issue is that you will need to create an image for each 'frame' in the animation. This means you start with an image with 1 number then an image with 2 numbers until you get an image with 5 numbers. Below is an example of how you could do that.

```C#
int[] numbers = new int[] { 1, 2, 3, 4, 5 };

int height = 100;
int numberWidth = 40;
int width = numberWidth * numbers.Length;
int delay = 100;

MagickReadSettings settings = new MagickReadSettings()
{
    TextGravity = Gravity.Center,
    BackgroundColor = MagickColors.Purple,
    FillColor = MagickColors.Green,
    Width = numberWidth,
    Height = height,
};

using (MagickImageCollection result = new MagickImageCollection())
{
    // Start with an empty image:
    MagickImage background = new MagickImage(settings.BackgroundColor, width, height);

    // Set the delay before the next image is shown.
    background.AnimationDelay = delay;

    // Add the frame to the animation.
    result.Add(background);

    // Now add all the numbers
    using (MagickImageCollection numberImages = new MagickImageCollection())
    {
        foreach (int number in numbers)
        {
            MagickImage numberImage = new MagickImage("label:" + number, settings);
            numberImages.Add(numberImage);

            // Add the images that are currently in the collection. This means we
            // will get these sequences: 1, 1-2, 1-3, 1-4, 1-5.
            IMagickImage frame = numberImages.AppendHorizontally();

            // Make sure the image has the correct width
            frame.Extent(width, frame.Height);

            // Set the delay before the next image is shown.
            frame.AnimationDelay = 100;

            // Add the frame to the animation.
            result.Add(frame);
        }

        result.Write(@"i:\test.gif");
    }
}
```

**Comment by jackbond** [comment]
@dlemstra I ran the code you sent, and the resulting image was exactly what I was looking for. Thank you so much. I had looked at the examples from www.imagemagick.org, but couldn't quite figure out how to apply them using your library. Thanks again for all your hard work.
