### ISSUE TITLE
MagickCoderErrorException when writing a MagickImage to disk that is created from MemoryStream

### ISSUE THREAD

**Issue by CFekkes** [dlemstra/Magick.NET#983]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am using the latest version of Magick.NET
- [x] I have searched [open](https://github.com/dlemstra/Magick.NET/issues) and [closed](https://github.com/dlemstra/Magick.NET/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

An error is thrown when trying to write a MagickImage to disk. This MagickImage is created from a MemoryStream to which a **32-bit** image was written. 

Exception Unhandled:

> ImageMagick.MagickCoderErrorException: 'E:\Output.tif: Unknown tag 317. `TIFFSetField' @ error/tiff.c/TIFFErrors/595'

### Steps to Reproduce

1. Create a 32-bit image (in my case 128x128) at path: `E:\32bitImage.tif` (or use attached file)
2. Run the following code:

```
static void Main()
{
        string inputFilePath = @"E:\32bitImage.tif";
        string outputFilePath = @"E:\Output.tif";
        var tiffWriteDefines = new TiffWriteDefines { Alpha = TiffAlpha.Unspecified };

        // Write image to stream
        MemoryStream memoryStream = new System.IO.MemoryStream();
        IMagickImage<float> image = new MagickImage(inputFilePath);
        image.Write(memoryStream, tiffWriteDefines);

        // Create image from stream
        memoryStream.Position = 0;
        IMagickImage<float> image2 = new MagickImage(memoryStream, new PixelReadSettings(128, 128, StorageType.Float, PixelMapping.RGB));
        image2.Write(outputFilePath, tiffWriteDefines); // this will crash
}
```

### Files
[32bitImage.zip](https://github.com/dlemstra/Magick.NET/files/6742742/32bitImage.zip)

### System Configuration

- Magick.NET-Q16-HDRI-x64 -Version 8.0.1
- Windows 10 x64
- Visual Studio 2019 v16.8.6

**Comment by dlemstra** [comment]
I suspect that you think that the `new PixelReadSettings(128, 128, StorageType.Float, PixelMapping.RGB)` overload does something different from you think it does. When you use the `PixelReadSettings` overload it expects a byte array that contains pixels instead of TIFF image data.

You did however find a bug inside ImageMagick that will be fixed in the next release.
