### ISSUE TITLE
MagicImage(MemoryStream ) coming as null even the position is set to zero

### ISSUE THREAD

**Issue by ManojLingala** [dlemstra/Magick.NET#984]
I'm using .NETCore on Mac Os , the nuget pkg which Im using is the latest version "Magick.NET-Q8-x64" Version="8.0.0".

Gist of the sample is to achieve 
 Read the image from url (I'm using webclient ) apply new dimensions and get the byteArray 
![Screen Shot 2021-07-01 at 12 29 48 pm](https://user-images.githubusercontent.com/24389850/124056871-dc74de80-da69-11eb-85bd-a956958fa6e7.png)
 
![Screen Shot 2021-07-01 at 12 30 06 pm](https://user-images.githubusercontent.com/24389850/124056954-ff06f780-da69-11eb-9364-54c6bc434b1b.png)

I have ensured the position is set to 0 and tried mutiple options like setting it as _RAW_ , nothing worked .<<internal exception says image not found>> .

Could you please provide any pointers ?

**Comment by dlemstra** [comment]
Could you please also copy past the code of that method inside this issue? You are now making me type this from the screenshot instead of copying it. If I want to test your issue I  really need the code.

**Comment by dlemstra** [comment]
Closing this issue due to the fact that I got no response.
