### ISSUE TITLE
Unable to load shared library 'Magick.Native-Q8-x64.dll'  when run on Azure Consumption Function Plan (Linux)

### ISSUE THREAD

**Issue by samuelya** [dlemstra/Magick.NET#989]
### Description

I am getting the following error when I call the function to create a sample image. It's working locally but I'm getting an error when I deploy it to Azure Function

Exception while executing function: CreateNewImage The type initializer for 'NativeMagickColor' threw an exception. Unable to load shared library 'Magick.Native-Q8-x64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMagick.Native-Q8-x64.dll: cannot open shared object file: No such file or directory 

### Steps to Reproduce
     - Create Azure Consumption Function Plan (Linux)
     - install NuGet package "Magick.NET-Q8-AnyCPU" 8.0.1
     - Use Magick function to create a basic image
     - It should work locally
     - However, it breaks when you publish to Azure
    
```csharp
public MemoryStream CreateImageWithText(string text)
        {
            using var image = new MagickImage(new MagickColor("black"), 1024, 1024);
            new Drawables()
                // Draw text on the image
                .FontPointSize(72)
                .Font("Comic Sans")
                .StrokeColor(new MagickColor("yellow"))
                .FillColor(MagickColors.Orange)
                .TextAlignment(TextAlignment.Center)
                .Text(512, 512, text)
                // Add an ellipse
                .StrokeColor(new MagickColor(0, Quantum.Max, 0))
                .FillColor(MagickColors.SaddleBrown)
                .Ellipse(256, 96, 192, 8, 0, 360)
                .Draw(image);

            var memoryStream = new MemoryStream();
            image.Write(memoryStream, MagickFormat.Png);
            memoryStream.Position =0;
            return memoryStream;
        }
```

### System Configuration

- Magick.NET version: "Magick.NET-Q8-AnyCPU" 
- Environment (Operating system, version and so on): Azure Consumption Function Plan (Linux)

**Comment by dlemstra** [comment]
It looks like the native library is not copied to your project output?

**Comment by dlemstra** [comment]
The problem is indeed that the native library is not copied to the output directory. You can make this happen with the following changes to your `.csproj` file:

This will make sure that only the linux native library is copied to the output:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
```
And this makes sure that the native library is copied to the `bin` directory of the `publish` folder:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Target Name="CopyRequiredNativeAssets" AfterTargets="_GenerateFunctionsPostBuild">
    <ItemGroup>
      <NativeAssetToCopy Include="$(OutDir)\Magick.Native-*.so" />
    </ItemGroup>
    <Copy SourceFiles="@(NativeAssetToCopy)" DestinationFolder="$(OutDir)\bin" />
  </Target>
</Project>
```

I have only tested this with the command: `func azure functionapp publish`
