### ISSUE TITLE
Square gif creates useless imageLeftPosition

### ISSUE THREAD

**Issue by Boquete** [dlemstra/Magick.NET#99]
Generating gif from cut to square images creates gif with usesless ImageLeftPosition;
http://www.fileformat.info/user/anonymous/download/ad0de6171d884a4b8fe89c75d60677ad/metadata.xml

Code:
```
private static void GenerateGif(List<Uri> pics)
        {
            using (MagickImageCollection collection = new MagickImageCollection())
            {
                for (int i=0; i < pics.Count(); i++ )
                {
                    var rawImage = pics[i].ToString().Replace("file:///", "");
                    var info = new MagickImageInfo(rawImage);
                    var rawImageHeight = info.Height;
                    var remadeImage = new MagickImage(rawImage);
                    remadeImage.Crop(rawImageHeight, rawImageHeight);
                    collection.Add(remadeImage);
                    collection[i].AnimationDelay = (App.animationDelay / 10); // Set the time delay (in 1/100th of a second) to pause after drawing the images that are read in or created after this setting has been defined.
                }
                var gifName = App.sessionGuid + "_" + "gif";
                var gifPath = AppDomain.CurrentDomain.BaseDirectory + gifName + ".gif";
                App.gifUri = new Uri(gifPath);
                collection.Write(gifPath);
            }
        }

```

So basically I cut image to Height x Height size, and generate  gif from such made picture. ImageLeft position should be 0 but is 80 in case of 640x480 -> 480x480 (difference is 160 - 80*2)

Image meta after cut: http://www.fileformat.info/user/anonymous/download/935c2d6a0c9840c0988bac478d054ba4/metadata.xml

**Comment by dlemstra** [comment]
Is your issue resolved when you call `remageImage.RePage` after `Crop` (http://www.imagemagick.org/Usage/crop/#crop)?

**Comment by Boquete** [comment]
Same time I got notification from you I found RePage - that's it, it works great with it. 
Solved.
