### ISSUE TITLE
`'WriteBlob Failed ' @ error/png.c/MagickPNGErrorHandler/1715` PNG Encoder not threadsafe?

### ISSUE THREAD

**Issue by JasonKleban** [dlemstra/Magick.NET#991]
### Description

I have three images that I'm generating using Magick.NET-Q16-AnyCPU.  When I generate them in sequence, it runs fine.  When I generate _just one_ using System.Threading.Tasks~Task.Factory.StartNew kind of stuff, it also works fine.  But when I try to generate all **three** in parallel, I consistently get thrown **two** exceptions: `'WriteBlob Failed' @ error/png.c/MagickPNGErrorHandler/1715` .  I'm also concerned that under production loads, that simultaneous requests would randomly hit this error even if the isolated operation is kept sequential.

[I see discussion here](https://stackoverflow.com/questions/29397831/is-imagemagick-thread-safe-with-without-threads-option#:~:text=ImageMagick%20is%20thread%20safe%20but,module%20with%20our%20own%20mutexes.) that encoders might not be threadsafe, but will have their use serialized internally with a mutex.  I wonder if perhaps this isn't happening for PNG?

### Steps to Reproduce

(I will try to gather a repro of this as I continue to investigate, but perhaps I can get some guidance in the meantime)

### System Configuration

- Magick.NET version:  Magick.NET-Q16-AnyCPU  v8.0.1
- Environment (Operating system, version and so on):  Windows 10, dotnet core in Azure Functions, running locally in Azure Function Core Tools at the moment.

**Comment by dlemstra** [comment]
I don't have an answer for your question. It really depends on how you are doing the parallelization. Is it possible to share some more details?

**Comment by JasonKleban** [comment]
I was able to get past this.  I was doing threading in a stupid way - calling StartNew when I was already in async code - and when I fixed that the troubles stopped.  However, it might be of concern still that it is possible to cause MagickPNG handler this kind of trouble from outside.  Thanks for looking at it.
