### ISSUE TITLE
PDF Crop Issue

### ISSUE THREAD

**Issue by ashishgehlot** [dlemstra/Magick.NET#995]
### Description
I am implementing Magick.Net in C# where we are are converting PostScript to PDF. 
We have encountered multiple time with the issue where output PDF gets cropped from Right & Bottom side.
Sample postscript that I used to covert is attached in below link. 
https://drive.google.com/file/d/12QI2Qw35nLPu3IFP5gaIYUqr-sNR74Mh/view?usp=sharing

Output of PDF(PFA):
[Outpu.pdf](https://github.com/dlemstra/Magick.NET/files/6815687/Outpu.pdf)

### Steps to Reproduce
I have used below code to do my job

var outputFilename = @"D:\output.pdf";
MagickNET.SetGhostscriptDirectory(gsPath);
var settings = new MagickReadSettings();
settings.Density = new Density(300, 300);
using (var image = new MagickImageCollection(postScriptInputFileName, settings))
{
 image.Write(outputFilename);
}

### System Configuration
12 GB Ram
AMD Ryzen 5 2500U

- Magick.NET version: 7.16 & 8.0.0.0
- Environment (Operating system, version and so on): Windows 10 pro X64

**Comment by dlemstra** [comment]
I think think you should use this library to do that operation. You probably want to use GhostScript directly instead of also using ImageMagick. I would advise you to search for an alternative library.
